In [ ]:
import sys
print(sys.executable)

In [ ]:
import pandas as pd

features_df = pd.read_csv(
    r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv"
)

classes_df = pd.read_csv(
    r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv"
)

edgelist_df = pd.read_csv(
    r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv"
)

print("features_df:", features_df.shape)
print("classes_df:", classes_df.shape)
print("edgelist_df:", edgelist_df.shape)

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Imports successful")

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")
ELLIPTIC_DIR = PROJECT_ROOT / "data" / "EllipticPlusPlus"

print("Elliptic++ folder:")
print(ELLIPTIC_DIR)

print("\nExists:", ELLIPTIC_DIR.exists())

print("\nContents:")
for item in ELLIPTIC_DIR.iterdir():
    print(item.name)

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

TRANSACTIONS_DIR = PROJECT_ROOT / "EllipticPlusPlus" / "Transactions Dataset"

FEATURES_FILE = TRANSACTIONS_DIR / "txs_features.csv"
CLASSES_FILE = TRANSACTIONS_DIR / "txs_classes.csv"
EDGELIST_FILE = TRANSACTIONS_DIR / "txs_edgelist.csv"

features_df = pd.read_csv(FEATURES_FILE)

print("Features loaded:", features_df.shape)

In [ ]:
classes_df = pd.read_csv(CLASSES_FILE)

print("Classes loaded:", classes_df.shape)

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

print("Project contents:")
for item in PROJECT_ROOT.iterdir():
    print(item)

In [ ]:
print("features_df" in globals())
print("classes_df" in globals())
print("edge_df" in globals())

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

ELLIPTIC_DIR = PROJECT_ROOT / "EllipticPlusPlus"

print("Elliptic++ folder:")
print(ELLIPTIC_DIR)

print("\nExists:", ELLIPTIC_DIR.exists())

print("\nContents:")
for item in ELLIPTIC_DIR.iterdir():
    print(item.name)

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

ELLIPTIC_DIR = PROJECT_ROOT / "EllipticPlusPlus"
TX_DIR = ELLIPTIC_DIR / "Transactions Dataset"

FEATURES_FILE = TX_DIR / "txs_features.csv"

print("Transactions folder:", TX_DIR)
print("Features file:", FEATURES_FILE)
print("File exists:", FEATURES_FILE.exists())

In [ ]:
df = pd.read_csv(FEATURES_FILE)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

In [ ]:
# ============================================================
# ELLIPTIC++ — txs_features.csv
# DATASET INSPECTION AFTER LOADING
# ============================================================

# ------------------------------------------------------------
# 1. COLUMN NAMES
# ------------------------------------------------------------

print("=" * 70)
print("COLUMN NAMES")
print("=" * 70)

print("Total columns:", len(df.columns))
print("\nColumn Names:")
print(df.columns.tolist())


# ------------------------------------------------------------
# 2. FIRST 5 ROWS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FIRST 5 ROWS")
print("=" * 70)

display(df.head())


# ------------------------------------------------------------
# 3. DATA TYPES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA TYPES")
print("=" * 70)

print(df.dtypes)


# ------------------------------------------------------------
# 4. MISSING VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING VALUES")
print("=" * 70)

missing_summary = df.isna().sum().to_frame(name="missing_count")

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"] / len(df) * 100
)

missing_summary = missing_summary.sort_values(
    "missing_count",
    ascending=False
)

print("Columns having missing values:")

display(
    missing_summary[
        missing_summary["missing_count"] > 0
    ]
)


# ------------------------------------------------------------
# 5. DUPLICATE ROWS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DUPLICATE ROW CHECK")
print("=" * 70)

duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)


# ------------------------------------------------------------
# 6. UNIQUE txId CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("UNIQUE txId CHECK")
print("=" * 70)

total_txids = len(df["txId"])
unique_txids = df["txId"].nunique()
duplicate_txids = df["txId"].duplicated().sum()

print("Total txId values:", total_txids)
print("Unique txId values:", unique_txids)
print("Duplicate txId values:", duplicate_txids)


# ------------------------------------------------------------
# 7. BASIC STATISTICS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("BASIC STATISTICS")
print("=" * 70)

display(df.describe())


# ------------------------------------------------------------
# 8. IDENTIFY FEATURE GROUPS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FEATURE GROUPS")
print("=" * 70)

local_columns = [
    col for col in df.columns
    if col.startswith("Local_feature_")
]

aggregate_columns = [
    col for col in df.columns
    if col.startswith("Aggregate_feature_")
]

transaction_stat_columns = [
    "in_txs_degree",
    "out_txs_degree",
    "total_BTC",
    "fees",
    "size",
    "num_input_addresses",
    "num_output_addresses",
    "in_BTC_min",
    "in_BTC_max",
    "in_BTC_mean",
    "in_BTC_median",
    "in_BTC_total",
    "out_BTC_min",
    "out_BTC_max",
    "out_BTC_mean",
    "out_BTC_median",
    "out_BTC_total"
]

print("Local features:", len(local_columns))
print("Aggregate features:", len(aggregate_columns))
print("Transaction-statistical features:", len(transaction_stat_columns))

print("\nColumn structure check:")

expected_columns = (
    2
    + len(local_columns)
    + len(aggregate_columns)
    + len(transaction_stat_columns)
)

print("Expected total columns:", expected_columns)
print("Actual total columns:", len(df.columns))


# ------------------------------------------------------------
# 9. MISSING RECORD PATTERN
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING RECORD PATTERN")
print("=" * 70)

missing_any = df[transaction_stat_columns].isna().any(axis=1)

missing_all = df[transaction_stat_columns].isna().all(axis=1)

print(
    "Transactions with at least one missing transaction value:",
    missing_any.sum()
)

print(
    "Transactions with all 17 transaction values missing:",
    missing_all.sum()
)


# ------------------------------------------------------------
# 10. MISSING COUNT PER TRANSACTION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING COUNT PER TRANSACTION")
print("=" * 70)

missing_count_per_transaction = (
    df[transaction_stat_columns]
    .isna()
    .sum(axis=1)
)

display(
    missing_count_per_transaction
    .value_counts()
    .sort_index()
)


# ------------------------------------------------------------
# 11. IDENTIFY THE 965 AFFECTED TRANSACTIONS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("AFFECTED TRANSACTIONS")
print("=" * 70)

affected_transactions = df.loc[missing_all].copy()

print(
    "Number of affected transactions:",
    len(affected_transactions)
)

print("\nFirst 5 affected transactions:")

display(
    affected_transactions[
        ["txId", "Time step"]
    ].head()
)


# ------------------------------------------------------------
# 12. FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CURRENT ANALYSIS SUMMARY")
print("=" * 70)

print(f"Total transactions              : {len(df):,}")
print(f"Total columns                   : {len(df.columns):,}")
print(f"Unique txIds                    : {df['txId'].nunique():,}")
print(f"Duplicate rows                  : {duplicate_rows:,}")
print(f"Local features                  : {len(local_columns)}")
print(f"Aggregate features              : {len(aggregate_columns)}")
print(f"Transaction-statistical features: {len(transaction_stat_columns)}")
print(
    f"Affected transactions           : "
    f"{len(affected_transactions):,}"
)
print(
    f"Affected percentage             : "
    f"{len(affected_transactions) / len(df) * 100:.6f}%"
)

print("\nCurrent txs_features.csv analysis completed.")

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")
ELLIPTIC_DIR = PROJECT_ROOT / "EllipticPlusPlus"

print("Elliptic++ folder:")
print(ELLIPTIC_DIR)

print("\nAll CSV files inside EllipticPlusPlus:\n")

for csv_file in ELLIPTIC_DIR.rglob("*.csv"):
    print(csv_file)

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

TX_FEATURES = (
    PROJECT_ROOT
    / "EllipticPlusPlus"
    / "Transactions Dataset"
    / "txs_features.csv"
)

print("Loading:")
print(TX_FEATURES)

df = pd.read_csv(TX_FEATURES)

print("\nShape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

In [ ]:
# ============================================================
# STEP 1 — INVESTIGATE THE 965 INCOMPLETE TRANSACTIONS
# ============================================================

# The 17 transaction-level statistical columns
transaction_stat_columns = [
    "in_txs_degree",
    "out_txs_degree",
    "total_BTC",
    "fees",
    "size",
    "num_input_addresses",
    "num_output_addresses",
    "in_BTC_min",
    "in_BTC_max",
    "in_BTC_mean",
    "in_BTC_median",
    "in_BTC_total",
    "out_BTC_min",
    "out_BTC_max",
    "out_BTC_mean",
    "out_BTC_median",
    "out_BTC_total"
]

# Find transactions where all 17 transaction-stat columns are missing
affected_mask = df[transaction_stat_columns].isna().all(axis=1)

affected_df = df.loc[affected_mask].copy()

print("Total affected transactions:", len(affected_df))

# ------------------------------------------------------------
# Check missing values in the OTHER feature groups
# ------------------------------------------------------------

local_columns = [
    col for col in df.columns
    if col.startswith("Local_feature_")
]

aggregate_columns = [
    col for col in df.columns
    if col.startswith("Aggregate_feature_")
]

print("\nLocal features:", len(local_columns))
print("Aggregate features:", len(aggregate_columns))

print("\nMissing Local-feature values in affected transactions:")
print(
    affected_df[local_columns]
    .isna()
    .sum()
    .sum()
)

print("\nMissing Aggregate-feature values in affected transactions:")
print(
    affected_df[aggregate_columns]
    .isna()
    .sum()
    .sum()
)

# ------------------------------------------------------------
# Check txId and Time step
# ------------------------------------------------------------

print("\nMissing txId values:")
print(affected_df["txId"].isna().sum())

print("\nMissing Time step values:")
print(affected_df["Time step"].isna().sum())

In [ ]:
# ============================================================
# STEP 2 — CHECK EXTREME VALUES
# ============================================================

numeric_columns = df.select_dtypes(include="number").columns

outlier_summary = pd.DataFrame({
    "min": df[numeric_columns].min(),
    "25%": df[numeric_columns].quantile(0.25),
    "median": df[numeric_columns].median(),
    "75%": df[numeric_columns].quantile(0.75),
    "max": df[numeric_columns].max()
})

# Range between Q1 and Q3
outlier_summary["IQR"] = (
    outlier_summary["75%"] - outlier_summary["25%"]
)

# IQR-based boundaries
outlier_summary["lower_bound"] = (
    outlier_summary["25%"] - 1.5 * outlier_summary["IQR"]
)

outlier_summary["upper_bound"] = (
    outlier_summary["75%"] + 1.5 * outlier_summary["IQR"]
)

# Count values outside IQR boundaries
outlier_summary["outlier_count"] = 0

for col in numeric_columns:
    lower = outlier_summary.loc[col, "lower_bound"]
    upper = outlier_summary.loc[col, "upper_bound"]

    outlier_summary.loc[col, "outlier_count"] = (
        ((df[col] < lower) | (df[col] > upper))
        .sum()
    )

display(
    outlier_summary.sort_values(
        "outlier_count",
        ascending=False
    ).head(30)
)

In [ ]:
import matplotlib.pyplot as plt

features_to_check = [
    "out_txs_degree",
    "num_input_addresses",
    "total_BTC",
    "fees",
    "size",
    "Aggregate_feature_72",
    "Local_feature_4"
]

for col in features_to_check:
    plt.figure(figsize=(8, 4))
    df[col].dropna().hist(bins=50)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Number of transactions")
    plt.show()

In [ ]:
# ============================================================
# STEP 4 — FEATURE CORRELATION ANALYSIS
# ============================================================

# Select only feature columns
feature_cols = [
    col for col in df.columns
    if col.startswith("Local_feature_")
    or col.startswith("Aggregate_feature_")
    or col in [
        "in_txs_degree",
        "out_txs_degree",
        "total_BTC",
        "fees",
        "size",
        "num_input_addresses",
        "num_output_addresses",
        "in_BTC_min",
        "in_BTC_max",
        "in_BTC_mean",
        "in_BTC_median",
        "in_BTC_total",
        "out_BTC_min",
        "out_BTC_max",
        "out_BTC_mean",
        "out_BTC_median",
        "out_BTC_total"
    ]
]

print("Number of feature columns:", len(feature_cols))

# Calculate Pearson correlation
corr_matrix = df[feature_cols].corr()

print("\nCorrelation matrix shape:")
print(corr_matrix.shape)

# Find highly correlated feature pairs
high_corr_pairs = []

for i in range(len(corr_matrix.columns)):
    for j in range(i + 1, len(corr_matrix.columns)):

        corr_value = corr_matrix.iloc[i, j]

        if abs(corr_value) >= 0.90:
            high_corr_pairs.append(
                (
                    corr_matrix.columns[i],
                    corr_matrix.columns[j],
                    corr_value
                )
            )

# Convert to DataFrame
high_corr_df = pd.DataFrame(
    high_corr_pairs,
    columns=["Feature_1", "Feature_2", "Correlation"]
)

# Sort by absolute correlation
if len(high_corr_df) > 0:
    high_corr_df["Absolute_Correlation"] = (
        high_corr_df["Correlation"].abs()
    )

    high_corr_df = high_corr_df.sort_values(
        "Absolute_Correlation",
        ascending=False
    )

print("\nHighly correlated feature pairs (|correlation| >= 0.90):")
print(high_corr_df.head(50).to_string(index=False))

In [ ]:
# ============================================================
# STEP 5 — FEATURE GROUP STRUCTURE
# ============================================================

local_features = [
    col for col in df.columns
    if col.startswith("Local_feature_")
]

aggregate_features = [
    col for col in df.columns
    if col.startswith("Aggregate_feature_")
]

transaction_features = [
    col for col in df.columns
    if col not in local_features
    and col not in aggregate_features
    and col not in ["txId", "Time step"]
]

print("LOCAL FEATURES")
print("Count:", len(local_features))
print(local_features)

print("\n" + "="*70)

print("AGGREGATE FEATURES")
print("Count:", len(aggregate_features))
print(aggregate_features)

print("\n" + "="*70)

print("OTHER TRANSACTION FEATURES")
print("Count:", len(transaction_features))
print(transaction_features)

In [ ]:
# ============================================================
# STEP 8 — LOAD txs_classes.csv
# ============================================================

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

CLASSES_FILE = (
    PROJECT_ROOT
    / "EllipticPlusPlus"
    / "Transactions Dataset"
    / "txs_classes.csv"
)

print("Classes file:")
print(CLASSES_FILE)

print("\nExists:", CLASSES_FILE.exists())

if CLASSES_FILE.exists():
    classes_df = pd.read_csv(CLASSES_FILE)

    print("\nShape:")
    print(classes_df.shape)

    print("\nColumns:")
    print(classes_df.columns.tolist())

    print("\nFirst 10 rows:")
    display(classes_df.head(10))

    print("\nData types:")
    print(classes_df.dtypes)

    print("\nMissing values:")
    print(classes_df.isnull().sum())

    print("\nDuplicate rows:")
    print(classes_df.duplicated().sum())
else:
    print("\n❌ File not found.")

In [ ]:
# ============================================================
# STEP 9 — CLASS DISTRIBUTION
# ============================================================

print("Class counts:")
print(classes_df["class"].value_counts().sort_index())

print("\nClass percentages:")
print(
    (classes_df["class"].value_counts(normalize=True)
     .sort_index() * 100)
     .round(2)
)

print("\nUnique class values:")
print(sorted(classes_df["class"].unique()))

In [ ]:
# ============================================================
# STEP 10 — LOAD txs_edgelist.csv
# ============================================================

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

EDGELIST_FILE = (
    PROJECT_ROOT
    / "EllipticPlusPlus"
    / "Transactions Dataset"
    / "txs_edgelist.csv"
)

print("Edgelist file:")
print(EDGELIST_FILE)

print("\nExists:", EDGELIST_FILE.exists())

if EDGELIST_FILE.exists():

    edge_df = pd.read_csv(EDGELIST_FILE)

    print("\nShape:")
    print(edge_df.shape)

    print("\nColumns:")
    print(edge_df.columns.tolist())

    print("\nFirst 10 rows:")
    display(edge_df.head(10))

    print("\nData types:")
    print(edge_df.dtypes)

    print("\nMissing values:")
    print(edge_df.isnull().sum())

    print("\nDuplicate rows:")
    print(edge_df.duplicated().sum())

else:
    print("\n❌ File not found.")

In [ ]:
print("features_df:", features_df.shape)
print("classes_df :", classes_df.shape)
print("edge_df    :", edge_df.shape)

In [ ]:
# ============================================================
# STEP 11 — EDGE ID INTEGRITY CHECK
# ============================================================

feature_txids = set(features_df["txId"])

edge_txids = (
    set(edge_df["txId1"]) |
    set(edge_df["txId2"])
)

missing_from_features = edge_txids - feature_txids

print("Unique transaction IDs in features:",
      len(feature_txids))

print("Unique transaction IDs appearing in edges:",
      len(edge_txids))

print("\nEdge transaction IDs NOT found in features:",
      len(missing_from_features))

if len(missing_from_features) == 0:
    print("\n✅ All edge transaction IDs exist in txs_features.csv")
else:
    print("\nFirst 20 missing IDs:")
    print(list(missing_from_features)[:20])

In [ ]:
# ============================================================
# STEP 12 — EDGE COVERAGE AGAINST CLASSES
# ============================================================

class_txids = set(classes_df["txId"])

missing_from_classes = edge_txids - class_txids

print("Unique transaction IDs in classes:",
      len(class_txids))

print("Unique transaction IDs in edges:",
      len(edge_txids))

print("\nEdge transaction IDs NOT found in classes:",
      len(missing_from_classes))

if len(missing_from_classes) == 0:
    print("\n✅ All edge transaction IDs have a class entry.")
else:
    print("\nFirst 20 missing IDs:")
    print(list(missing_from_classes)[:20])

In [ ]:
# ============================================================
# STEP 13 — FEATURE GROUP SUMMARY
# ============================================================

local_features = [
    c for c in features_df.columns
    if c.startswith("Local_feature_")
]

aggregate_features = [
    c for c in features_df.columns
    if c.startswith("Aggregate_feature_")
]

transaction_features = [
    c for c in features_df.columns
    if c not in local_features
    and c not in aggregate_features
    and c not in ["txId", "Time step"]
]

print("Local features:", len(local_features))
print("Aggregate features:", len(aggregate_features))
print("Transaction-level features:", len(transaction_features))

print("\nLocal feature range:")
print(local_features[:5], "...", local_features[-5:])

print("\nAggregate feature range:")
print(aggregate_features[:5], "...", aggregate_features[-5:])

print("\nTransaction-level features:")
print(transaction_features)

In [ ]:
# ============================================================
# STEP 14 — FEATURE STATISTICS BY GROUP
# ============================================================

local_stats = features_df[local_features].describe().T
aggregate_stats = features_df[aggregate_features].describe().T
transaction_stats = features_df[transaction_features].describe().T

print("LOCAL FEATURES")
display(local_stats.head(10))

print("\nAGGREGATE FEATURES")
display(aggregate_stats.head(10))

print("\nTRANSACTION-LEVEL FEATURES")
display(transaction_stats)

In [ ]:
# ============================================================
# STEP 15 — LOW VARIANCE / NEAR-CONSTANT FEATURES
# ============================================================

model_features = local_features + aggregate_features + transaction_features

variance_df = (
    features_df[model_features]
    .var()
    .sort_values()
    .to_frame(name="variance")
)

print("Total model features:", len(model_features))

print("\n10 lowest-variance features:")
display(variance_df.head(10))

print("\n10 highest-variance features:")
display(variance_df.tail(10))

In [ ]:
# ============================================================
# STEP 16 — SYSTEMATIC REDUNDANCY CHECK
# ============================================================

corr = features_df[model_features].corr().abs()

# Keep only upper triangle so we don't count A-B and B-A twice
upper = corr.where(
    np.triu(np.ones(corr.shape), k=1).astype(bool)
)

high_corr_pairs = (
    upper.stack()
    .reset_index()
)

high_corr_pairs.columns = [
    "Feature_1",
    "Feature_2",
    "Absolute_Correlation"
]

high_corr_pairs = (
    high_corr_pairs[
        high_corr_pairs["Absolute_Correlation"] >= 0.90
    ]
    .sort_values(
        "Absolute_Correlation",
        ascending=False
    )
)

print("Total highly correlated pairs (|r| >= 0.90):",
      len(high_corr_pairs))

display(high_corr_pairs.head(30))

In [ ]:
# ============================================================
# STEP 17 — UNIQUE FEATURES INVOLVED IN HIGH CORRELATION
# ============================================================

high_corr_features = set(
    high_corr_pairs["Feature_1"]
).union(
    set(high_corr_pairs["Feature_2"])
)

print("Highly correlated pairs:", len(high_corr_pairs))

print("Unique features involved:",
      len(high_corr_features))

print("\nHow many are Local features?")
print(
    sum(f.startswith("Local_feature_")
        for f in high_corr_features)
)

print("\nHow many are Aggregate features?")
print(
    sum(f.startswith("Aggregate_feature_")
        for f in high_corr_features)
)

print("\nHow many are transaction-level features?")
print(
    sum(
        f in transaction_features
        for f in high_corr_features
    )
)

In [ ]:
# ============================================================
# STEP 18 — WHERE IS THE REDUNDANCY COMING FROM?
# ============================================================

def feature_group(feature):
    if feature.startswith("Local_feature_"):
        return "Local"
    elif feature.startswith("Aggregate_feature_"):
        return "Aggregate"
    elif feature in transaction_features:
        return "Transaction"
    else:
        return "Other"


high_corr_pairs["Group_1"] = (
    high_corr_pairs["Feature_1"].apply(feature_group)
)

high_corr_pairs["Group_2"] = (
    high_corr_pairs["Feature_2"].apply(feature_group)
)

group_counts = (
    high_corr_pairs
    .groupby(["Group_1", "Group_2"])
    .size()
    .sort_values(ascending=False)
)

print("High-correlation pairs by feature group:\n")
print(group_counts)

In [ ]:

# ============================================================
# STEP 19 — FIND REDUNDANT FEATURE GROUPS
# NetworkX-free version
# ============================================================

# Each feature initially belongs to its own group
parent = {feature: feature for feature in model_features}


def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x


def union(a, b):
    root_a = find(a)
    root_b = find(b)

    if root_a != root_b:
        parent[root_b] = root_a


# Connect highly correlated features
for _, row in high_corr_pairs.iterrows():
    union(
        row["Feature_1"],
        row["Feature_2"]
    )


# Build groups
groups = {}

for feature in model_features:
    root = find(feature)

    if root not in groups:
        groups[root] = []

    groups[root].append(feature)


# Keep only groups containing 2+ features
redundant_groups = [
    sorted(group)
    for group in groups.values()
    if len(group) > 1
]

# Largest groups first
redundant_groups = sorted(
    redundant_groups,
    key=len,
    reverse=True
)

print("Number of redundant groups:",
      len(redundant_groups))

print("\nLargest redundant groups:\n")

for i, group in enumerate(redundant_groups[:20], 1):
    print(f"Group {i} ({len(group)} features):")
    print(group)
    print()

In [ ]:
# ============================================================
# STEP 20 — LOCATE ELLIPTIC++ DOCUMENTATION
# ============================================================

from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")
ELLIPTIC_DIR = PROJECT_ROOT / "EllipticPlusPlus"

print("Elliptic++ directory:")
print(ELLIPTIC_DIR)

print("\nREADME exists:", 
      (ELLIPTIC_DIR / "README.md").exists())

print("\nFiles/folders:")
for item in ELLIPTIC_DIR.iterdir():
    print(item.name)

In [ ]:
# ============================================================
# STEP 21 — READ ELLIPTIC++ README
# ============================================================

readme_path = ELLIPTIC_DIR / "README.md"

with open(readme_path, "r", encoding="utf-8") as f:
    readme_text = f.read()

print(readme_text)

In [ ]:
# ============================================================
# STEP 22 — INSPECT TRANSACTIONS DATASET DOCUMENTATION
# ============================================================

TRANSACTIONS_DIR = ELLIPTIC_DIR / "Transactions Dataset"

print("Transactions Dataset:")
print(TRANSACTIONS_DIR)

print("\nContents:\n")

for item in TRANSACTIONS_DIR.iterdir():
    print(item.name)

In [ ]:
# ============================================================
# STEP 23 — INSPECT FEATURE ANALYSIS NOTEBOOK
# ============================================================

feature_analysis_path = (
    TRANSACTIONS_DIR /
    "Elliptic++_Transactions_Feature_Analysis.ipynb"
)

print("Feature analysis notebook:")
print(feature_analysis_path)

print("\nExists:", feature_analysis_path.exists())

In [ ]:
# ============================================================
# STEP 24 — READ FEATURE ANALYSIS NOTEBOOK
# ============================================================

import json

with open(feature_analysis_path, "r", encoding="utf-8") as f:
    feature_notebook = json.load(f)

print("Total cells:", len(feature_notebook["cells"]))

for i, cell in enumerate(feature_notebook["cells"]):

    source = "".join(cell.get("source", []))

    if source.strip():

        print("\n" + "=" * 80)
        print(f"CELL {i} | {cell['cell_type'].upper()}")
        print("=" * 80)

        print(source[:5000])

In [ ]:
# ============================================================
# STEP 25 — FIND FEATURE-RELATED CELLS
# ============================================================

keywords = [
    "Local_feature",
    "Aggregate_feature",
    "local feature",
    "aggregate feature",
    "feature",
    "features"
]

for i, cell in enumerate(feature_notebook["cells"]):

    source = "".join(cell.get("source", []))

    if any(keyword.lower() in source.lower() for keyword in keywords):

        print("\n" + "=" * 80)
        print(f"CELL {i} | {cell['cell_type'].upper()}")
        print("=" * 80)

        print(source[:5000])

In [ ]:
# ============================================================
# STEP 25B — FIND EXACT FEATURE REFERENCES
# ============================================================

keywords = [
    "Local_feature",
    "Aggregate_feature",
    "local feature",
    "aggregate feature"
]

for i, cell in enumerate(feature_notebook["cells"]):

    source = "".join(cell.get("source", []))
    lines = source.splitlines()

    matches = [
        line for line in lines
        if any(k.lower() in line.lower() for k in keywords)
    ]

    if matches:
        print("\n" + "=" * 80)
        print(f"CELL {i}")
        print("=" * 80)

        for line in matches[:30]:
            print(line)

In [ ]:
# ============================================================
# STEP 26 — PRINT COMPLETE CELL 12
# ============================================================

cell_12 = feature_notebook["cells"][12]

print("CELL 12 TYPE:", cell_12["cell_type"])
print("=" * 80)

print("".join(cell_12.get("source", [])))

In [ ]:
# ============================================================
# STEP 27 — SHOW CELLS 12–18
# ============================================================

for i in range(12, min(19, len(feature_notebook["cells"]))):

    cell = feature_notebook["cells"][i]

    print("\n" + "=" * 80)
    print(f"CELL {i} | {cell['cell_type'].upper()}")
    print("=" * 80)

    print("".join(cell.get("source", [])))

In [ ]:
# ============================================================
# STEP 27 — SHOW CELLS 12–18
# ============================================================

for i in range(12, min(19, len(feature_notebook["cells"]))):

    cell = feature_notebook["cells"][i]

    print("\n" + "=" * 80)
    print(f"CELL {i} | {cell['cell_type'].upper()}")
    print("=" * 80)

    print("".join(cell.get("source", [])))

In [ ]:
# ============================================================
# STEP 28 — FEATURE COLUMN NAMES FROM AUTHORS' NOTEBOOK
# ============================================================

cell_13 = feature_notebook["cells"][13]

print("Cell 13 code:")
print("".join(cell_13.get("source", [])))

print("\n" + "=" * 80)
print("IMPORTANT:")
print("Cell 13 itself only contains the command that lists columns.")
print("We will inspect the actual dataframe columns from the notebook.")
print("=" * 80)

print("\nOur current txs_features.csv columns:")
for i, col in enumerate(features_df.columns):
    print(i, "->", col)

In [ ]:
# ============================================================
# STEP 29 — FIND THE NOTEBOOK'S FEATURE DATAFRAME OUTPUT
# ============================================================

# Show outputs stored inside Cell 13
cell_13 = feature_notebook["cells"][13]

print("CELL 13 OUTPUTS:")
print("=" * 80)

for output in cell_13.get("outputs", []):

    print("Output type:", output.get("output_type"))

    if "text" in output:
        print("".join(output["text"]))

    if "data" in output:
        data = output["data"]

        if "text/plain" in data:
            print("".join(data["text/plain"]))

In [ ]:
# ============================================================
# STEP 31 — EXACT FEATURE GROUPS FROM AUTHORS' NOTEBOOK
# ============================================================

# Reconstruct the dataframe columns from Cell 13 output
cell_13 = feature_notebook["cells"][13]

output = cell_13["outputs"][0]

author_columns = output["data"]["text/plain"]

print("Raw stored column output:")
print(author_columns)

In [ ]:
# ============================================================
# STEP 32 — FIND WHERE df_txs_features IS CREATED
# ============================================================

for i, cell in enumerate(feature_notebook["cells"]):

    source = "".join(cell.get("source", []))

    if "df_txs_features" in source:

        print("\n" + "=" * 80)
        print(f"CELL {i} | {cell['cell_type'].upper()}")
        print("=" * 80)

        print(source[:8000])

In [ ]:
# ============================================================
# STEP 33 — READ AUTHORS' FEATURE ANALYSIS SECTION
# ============================================================

for i in range(15, 19):

    cell = feature_notebook["cells"][i]

    print("\n" + "=" * 80)
    print(f"CELL {i} | {cell['cell_type'].upper()}")
    print("=" * 80)

    print("".join(cell.get("source", [])))

In [ ]:
# ============================================================
# STEP 34A — CHECK REQUIRED VARIABLES
# ============================================================

print("features_df:", "YES" if "features_df" in globals() else "NO")
print("classes_df:", "YES" if "classes_df" in globals() else "NO")
print("X_train:", "YES" if "X_train" in globals() else "NO")
print("cRF:", "YES" if "cRF" in globals() else "NO")

In [ ]:
# ============================================================
# STEP 34B — FIND AUTHOR'S X_train AND cRF SETUP
# ============================================================

for i, cell in enumerate(feature_notebook["cells"]):

    source = "".join(cell.get("source", []))

    if "X_train" in source or "cRF" in source:

        print("\n" + "=" * 80)
        print(f"CELL {i} | {cell['cell_type'].upper()}")
        print("=" * 80)

        print(source[:8000])

In [ ]:
# ============================================================
# STEP 34C — FIND RANDOM FOREST TRAINING CODE
# ============================================================

for i, cell in enumerate(feature_notebook["cells"]):

    source = "".join(cell.get("source", []))

    if (
        "RandomForest" in source
        or "RandomForestClassifier" in source
        or "cRF =" in source
        or "X_train =" in source
        or "y_train =" in source
    ):

        print("\n" + "=" * 80)
        print(f"CELL {i} | {cell['cell_type'].upper()}")
        print("=" * 80)

        print(source[:10000])

In [ ]:
# ============================================================
# STEP 34D — FIND ALL CELLS THAT CREATE/TRAIN THE RF MODEL
# ============================================================

for i, cell in enumerate(feature_notebook["cells"]):

    source = "".join(cell.get("source", []))

    keywords = [
        "RandomForestClassifier(",
        "cRF.fit(",
        "cRF=",
        "cRF =",
        "train_test_split("
    ]

    if any(k in source for k in keywords):

        print("\n" + "=" * 80)
        print(f"CELL {i} | {cell['cell_type'].upper()}")
        print("=" * 80)

        print(source[:12000])

In [ ]:
print("Kernel is working")
print("features_df:", "features_df" in globals())
print("classes_df:", "classes_df" in globals())

In [ ]:
# ============================================================
# STEP 35A — CHECK FEATURE + CLASS COLUMNS
# ============================================================

print("features_df columns:")
print(features_df.columns[:5].tolist(), "...", features_df.columns[-5:].tolist())

print("\nclasses_df columns:")
print(classes_df.columns.tolist())

print("\nfeatures_df shape:", features_df.shape)
print("classes_df shape :", classes_df.shape)

In [ ]:

# ============================================================
# STEP 35B — MERGE TRANSACTION FEATURES WITH CLASS LABELS
# ============================================================

labelled_df = features_df.merge(
    classes_df,
    on="txId",
    how="inner"
)

print("Merged dataset shape:", labelled_df.shape)

print("\nColumns:")
print(labelled_df.columns[:5].tolist(), "...", labelled_df.columns[-5:].tolist())

print("\nClass distribution:")
print(
    labelled_df["class"]
    .value_counts()
    .sort_index()
)

In [ ]:
# ============================================================
# STEP 36 — SELECT KNOWN-LABEL TRANSACTIONS
# ============================================================

supervised_df = labelled_df[
    labelled_df["class"].isin([1, 2])
].copy()

print("Supervised dataset shape:", supervised_df.shape)

print("\nClass distribution:")
print(
    supervised_df["class"]
    .value_counts()
    .sort_index()
)

print("\nClass percentages:")
print(
    (
        supervised_df["class"]
        .value_counts(normalize=True)
        .sort_index()
        * 100
    ).round(2)
)

In [ ]:
# ============================================================
# STEP 37 — TRAIN / TEST SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

# Remove columns that should NOT be used as ML features
X = supervised_df.drop(
    columns=["txId", "Time step", "class"]
)

# Target
y = supervised_df["class"]

# 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

print("\ny_train distribution:")
print(y_train.value_counts().sort_index())

print("\ny_test distribution:")
print(y_test.value_counts().sort_index())

In [ ]:
# ============================================================
# STEP 38 — BASELINE RANDOM FOREST
# ============================================================

from sklearn.ensemble import RandomForestClassifier

cRF = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

print("Training Random Forest...")

cRF.fit(X_train, y_train)

print("✅ Random Forest trained successfully.")
print("Number of trees:", len(cRF.estimators_))

In [ ]:
# ============================================================
# STEP 39 — BASELINE PREDICTIONS
# ============================================================

y_pred = cRF.predict(X_test)

print("Predictions generated successfully.")
print("Number of predictions:", len(y_pred))

print("\nFirst 20 predictions:")
print(y_pred[:20])

In [ ]:
# ============================================================
# STEP 40 — BASELINE BASIC EVALUATION
# ============================================================

from sklearn.metrics import accuracy_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Baseline Accuracy:", round(accuracy, 4))

print("\nConfusion Matrix:")
print(cm)

In [ ]:
# ============================================================
# STEP 41 — DETAILED BASELINE EVALUATION
# ============================================================

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred,
        target_names=["Illicit (Class 1)", "Licit (Class 2)"],
        digits=4
    )
)

In [ ]:
# ============================================================
# STEP 42 — CLASS-WEIGHTED RANDOM FOREST
# ============================================================

from sklearn.ensemble import RandomForestClassifier

weighted_RF = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training class-weighted Random Forest...")

weighted_RF.fit(X_train, y_train)

print("✅ Class-weighted Random Forest trained successfully.")
print("Number of trees:", len(weighted_RF.estimators_))

In [ ]:
# ============================================================
# STEP 43 — CLASS-WEIGHTED RF PREDICTIONS
# ============================================================

y_pred_weighted = weighted_RF.predict(X_test)

print("Weighted RF predictions generated successfully.")
print("Number of predictions:", len(y_pred_weighted))

print("\nFirst 20 predictions:")
print(y_pred_weighted[:20])

In [ ]:
# ============================================================
# STEP 44 — EVALUATE CLASS-WEIGHTED RANDOM FOREST
# ============================================================

from sklearn.metrics import classification_report, confusion_matrix

print("Weighted RF Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_weighted))

print("\nWeighted RF Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_weighted,
        target_names=["Illicit (Class 1)", "Licit (Class 2)"],
        digits=4
    )
)

In [ ]:
# ============================================================
# STEP 45 — RANDOM FOREST FEATURE IMPORTANCE
# ============================================================

importance_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": weighted_RF.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

print("Top 20 most important features:")
print(importance_df.head(20).to_string(index=False))

print("\nBottom 20 least important features:")
print(importance_df.tail(20).to_string(index=False))

In [ ]:
# ============================================================
# STEP 46 — IMPORTANT FEATURES vs CORRELATED FEATURES
# ============================================================

# Top 20 important features
top20_features = importance_df.head(20)["Feature"].tolist()

# Check which top features participate in high-correlation pairs
top20_correlated = correlated_pairs[
    correlated_pairs["Feature_1"].isin(top20_features) |
    correlated_pairs["Feature_2"].isin(top20_features)
].copy()

print("Top 20 important features:")
print(top20_features)

print("\nTop important features involved in |r| >= 0.90 correlations:")
print(top20_correlated.to_string(index=False))

print("\nNumber of top-20 features involved in high correlations:")

involved_features = set(
    top20_correlated["Feature_1"]
).union(
    set(top20_correlated["Feature_2"])
)

print(
    len(set(top20_features).intersection(involved_features))
)

In [ ]:
# ============================================================
# STEP 46A — RECREATE HIGH-CORRELATION PAIRS
# ============================================================

import numpy as np
import pandas as pd

# Calculate absolute correlation matrix
corr_matrix = X_train.corr().abs()

# Keep only upper triangle to avoid duplicate pairs
upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

# Extract feature pairs with |r| >= 0.90
correlated_pairs = (
    upper.stack()
    .reset_index()
)

correlated_pairs.columns = [
    "Feature_1",
    "Feature_2",
    "Absolute_Correlation"
]

correlated_pairs = correlated_pairs[
    correlated_pairs["Absolute_Correlation"] >= 0.90
].sort_values(
    "Absolute_Correlation",
    ascending=False
).reset_index(drop=True)

print("Total highly correlated pairs:", len(correlated_pairs))

print("\nTop 20 highly correlated pairs:")
print(
    correlated_pairs.head(20).to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 46B — IMPORTANT FEATURES vs CORRELATED FEATURES
# ============================================================

# Top 20 features according to Random Forest
top20_features = importance_df.head(20)["Feature"].tolist()

# Find correlation pairs involving any top-20 feature
top20_correlated = correlated_pairs[
    correlated_pairs["Feature_1"].isin(top20_features) |
    correlated_pairs["Feature_2"].isin(top20_features)
].copy()

print("Top 20 important features:")
print(top20_features)

print("\nTop important features involved in |r| >= 0.90 correlations:")

if len(top20_correlated) > 0:
    print(top20_correlated.to_string(index=False))
else:
    print("None")

involved_features = set(
    top20_correlated["Feature_1"]
).union(
    set(top20_correlated["Feature_2"])
)

top20_involved = set(top20_features).intersection(involved_features)

print("\nNumber of top-20 features involved in high correlations:")
print(len(top20_involved))

print("\nThose top-20 features:")
print(sorted(top20_involved))

In [ ]:
# ============================================================
# STEP 47A — IDENTIFY REDUNDANT FEATURES
# ============================================================

# Work with a copy of the correlation matrix
corr = X_train.corr().abs()

# Upper triangle only
upper = corr.where(
    np.triu(np.ones(corr.shape), k=1).astype(bool)
)

# Features having correlation >= 0.90 with an earlier feature
to_drop = [
    column
    for column in upper.columns
    if any(upper[column] >= 0.90)
]

print("Original number of features:", X_train.shape[1])
print("Features marked as redundant:", len(to_drop))
print("Features remaining:", X_train.shape[1] - len(to_drop))

print("\nFirst 30 features marked for removal:")
print(to_drop[:30])

In [ ]:
# ============================================================
# STEP 47B — CORRELATED FEATURES + RF IMPORTANCE
# ============================================================

# Create importance lookup
importance_lookup = dict(
    zip(
        importance_df["Feature"],
        importance_df["Importance"]
    )
)

# Show the first 30 automatically marked redundant features
# together with their RF importance
redundant_importance = pd.DataFrame({
    "Feature": to_drop,
    "RF_Importance": [
        importance_lookup.get(feature, 0)
        for feature in to_drop
    ]
})

redundant_importance = redundant_importance.sort_values(
    by="RF_Importance",
    ascending=False
).reset_index(drop=True)

print("Redundant features ranked by RF importance:")
print(
    redundant_importance.head(30).to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 48 — PERMUTATION FEATURE IMPORTANCE
# ============================================================

from sklearn.inspection import permutation_importance

print("Calculating permutation importance...")
print("This may take some time...")

perm_result = permutation_importance(
    weighted_RF,
    X_test,
    y_test,
    n_repeats=3,
    random_state=42,
    scoring="f1_macro",
    n_jobs=-1
)

permutation_df = pd.DataFrame({
    "Feature": X_test.columns,
    "Permutation_Importance": perm_result.importances_mean,
    "Std": perm_result.importances_std
})

permutation_df = permutation_df.sort_values(
    by="Permutation_Importance",
    ascending=False
).reset_index(drop=True)

print("\nTop 20 features by permutation importance:")
print(
    permutation_df.head(20).to_string(index=False)
)

print("\nBottom 20 features by permutation importance:")
print(
    permutation_df.tail(20).to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 49 — CREATE CANDIDATE REDUCED FEATURE SET
# ============================================================

# Features that were important according to RF impurity importance
rf_top20 = set(
    importance_df.head(20)["Feature"]
)

# Features with positive permutation importance
positive_perm_features = set(
    permutation_df[
        permutation_df["Permutation_Importance"] > 0
    ]["Feature"]
)

# Combine both sources of evidence
candidate_features = sorted(
    positive_perm_features.union(rf_top20)
)

print("Original number of features:", X_train.shape[1])
print("Candidate retained features:", len(candidate_features))
print("Candidate features for removal:", 
      X_train.shape[1] - len(candidate_features))

print("\nFirst 30 candidate retained features:")
print(candidate_features[:30])

print("\nTop RF features that are retained:")
print(
    sorted(
        rf_top20.intersection(candidate_features)
    )
)

In [ ]:
# ============================================================
# STEP 50 — CREATE REDUCED TRAIN/TEST DATASETS
# ============================================================

X_train_reduced = X_train[candidate_features].copy()
X_test_reduced = X_test[candidate_features].copy()

print("Original X_train shape :", X_train.shape)
print("Original X_test shape  :", X_test.shape)

print("\nReduced X_train shape  :", X_train_reduced.shape)
print("Reduced X_test shape   :", X_test_reduced.shape)

print("\nNumber of retained features:", len(candidate_features))

In [ ]:
# ============================================================
# STEP 51 — REDUCED-FEATURE CLASS-WEIGHTED RANDOM FOREST
# ============================================================

reduced_RF = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training reduced-feature Random Forest...")

reduced_RF.fit(
    X_train_reduced,
    y_train
)

print("✅ Reduced-feature Random Forest trained successfully.")
print("Number of trees:", len(reduced_RF.estimators_))

In [ ]:
# ============================================================
# STEP 52 — REDUCED RF PREDICTIONS
# ============================================================

y_pred_reduced = reduced_RF.predict(X_test_reduced)

print("Reduced RF predictions generated successfully.")
print("Number of predictions:", len(y_pred_reduced))

print("\nFirst 20 predictions:")
print(y_pred_reduced[:20])

In [ ]:
# ============================================================
# STEP 53 — EVALUATE REDUCED RANDOM FOREST
# ============================================================

from sklearn.metrics import classification_report, confusion_matrix

print("Reduced RF Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_reduced))

print("\nReduced RF Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_reduced,
        target_names=["Illicit (Class 1)", "Licit (Class 2)"],
        digits=4
    )
)

In [ ]:
# ============================================================
# STEP 54 — INSPECT TIME-STEP DISTRIBUTION
# ============================================================

print("Unique time steps:")
print(sorted(supervised_df["Time step"].unique()))

print("\nNumber of unique time steps:",
      supervised_df["Time step"].nunique())

print("\nTransactions per time step:")
print(
    supervised_df["Time step"]
    .value_counts()
    .sort_index()
)

print("\nClass distribution by time step:")
print(
    pd.crosstab(
        supervised_df["Time step"],
        supervised_df["class"]
    )
)

In [ ]:
# ============================================================
# STEP 55 — LABELLED TRANSACTIONS BY TIME STEP
# ============================================================

time_class = (
    supervised_df
    .groupby(["Time step", "class"])
    .size()
    .unstack(fill_value=0)
)

time_class.columns = [
    f"class_{int(c)}"
    for c in time_class.columns
]

time_class["total_labelled"] = time_class.sum(axis=1)

print("Labelled transactions by time step:")
print(time_class.to_string())

print("\nTotal labelled transactions:",
      time_class["total_labelled"].sum())

In [ ]:
# ============================================================
# STEP 56 — CHECK POSSIBLE TIME-BASED SPLITS
# ============================================================

time_summary = time_class.copy()

# Cumulative labelled counts
time_summary["cumulative_labelled"] = (
    time_summary["total_labelled"].cumsum()
)

time_summary["cumulative_class_1"] = (
    time_summary["class_1"].cumsum()
)

time_summary["cumulative_class_2"] = (
    time_summary["class_2"].cumsum()
)

total_labelled = time_summary["total_labelled"].sum()
total_class_1 = time_summary["class_1"].sum()

# Candidate cutoffs
candidate_cutoffs = [30, 32, 34, 36, 38, 40]

rows = []

for cutoff in candidate_cutoffs:

    train_part = time_summary.loc[
        time_summary.index <= cutoff
    ]

    test_part = time_summary.loc[
        time_summary.index > cutoff
    ]

    rows.append({
        "Train_time_steps": f"1-{cutoff}",
        "Test_time_steps": f"{cutoff+1}-49",

        "Train_labelled": train_part["total_labelled"].sum(),
        "Test_labelled": test_part["total_labelled"].sum(),

        "Train_class_1": train_part["class_1"].sum(),
        "Test_class_1": test_part["class_1"].sum(),

        "Train_class_2": train_part["class_2"].sum(),
        "Test_class_2": test_part["class_2"].sum()
    })

split_check = pd.DataFrame(rows)

print("Possible chronological splits:\n")
print(split_check.to_string(index=False))

In [ ]:
# ============================================================
# STEP 57 — TIME-BASED TRAIN / TEST SPLIT
# ============================================================

TIME_CUTOFF = 30

# Use the supervised dataset's time step
train_mask = supervised_df["Time step"] <= TIME_CUTOFF
test_mask = supervised_df["Time step"] > TIME_CUTOFF

# Features
X_temporal = supervised_df[candidate_features]

# Target
y_temporal = supervised_df["class"]

# Temporal split
X_train_time = X_temporal[train_mask].copy()
X_test_time = X_temporal[test_mask].copy()

y_train_time = y_temporal[train_mask].copy()
y_test_time = y_temporal[test_mask].copy()

print("Temporal split:")
print(f"Training time steps: 1-{TIME_CUTOFF}")
print(f"Testing time steps : {TIME_CUTOFF + 1}-49")

print("\nShapes:")
print("X_train_time:", X_train_time.shape)
print("X_test_time :", X_test_time.shape)

print("\nTraining class distribution:")
print(y_train_time.value_counts().sort_index())

print("\nTesting class distribution:")
print(y_test_time.value_counts().sort_index())

In [ ]:
# ============================================================
# STEP 58 — TEMPORAL CLASS-WEIGHTED RANDOM FOREST
# ============================================================

temporal_RF = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training temporal Random Forest...")

temporal_RF.fit(
    X_train_time,
    y_train_time
)

print("✅ Temporal Random Forest trained successfully.")
print("Number of trees:", len(temporal_RF.estimators_))

In [ ]:
# ============================================================
# STEP 59 — TEMPORAL RF PREDICTIONS
# ============================================================

y_pred_temporal = temporal_RF.predict(X_test_time)

print("Temporal RF predictions generated successfully.")
print("Number of predictions:", len(y_pred_temporal))

print("\nFirst 20 predictions:")
print(y_pred_temporal[:20])

In [ ]:
# ============================================================
# STEP 60 — EVALUATE TEMPORAL RANDOM FOREST
# ============================================================

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score
)

cm_temporal = confusion_matrix(
    y_test_time,
    y_pred_temporal
)

print("Temporal RF Confusion Matrix:")
print(cm_temporal)

print("\nTemporal RF Classification Report:")

print(
    classification_report(
        y_test_time,
        y_pred_temporal,
        target_names=[
            "Illicit (Class 1)",
            "Licit (Class 2)"
        ],
        digits=4
    )
)

print(
    "\nTemporal RF Accuracy:",
    round(
        accuracy_score(
            y_test_time,
            y_pred_temporal
        ),
        4
    )
)

In [ ]:
# ============================================================
# STEP 61 — TEMPORAL PERFORMANCE BY TIME STEP
# ============================================================

temporal_results = supervised_df.loc[
    test_mask,
    ["txId", "Time step", "class"]
].copy()

temporal_results["prediction"] = y_pred_temporal

# Calculate performance separately for each future time step
rows = []

for timestep in sorted(temporal_results["Time step"].unique()):

    subset = temporal_results[
        temporal_results["Time step"] == timestep
    ]

    actual_illicit = (subset["class"] == 1).sum()
    predicted_illicit = (subset["prediction"] == 1).sum()

    true_positive = (
        (subset["class"] == 1) &
        (subset["prediction"] == 1)
    ).sum()

    false_negative = (
        (subset["class"] == 1) &
        (subset["prediction"] == 2)
    ).sum()

    recall = (
        true_positive / actual_illicit
        if actual_illicit > 0
        else np.nan
    )

    rows.append({
        "Time_step": timestep,
        "Actual_illicit": actual_illicit,
        "Predicted_illicit": predicted_illicit,
        "True_positive": true_positive,
        "False_negative": false_negative,
        "Illicit_recall": recall
    })

temporal_by_time = pd.DataFrame(rows)

print("Illicit detection by future time step:")
print(
    temporal_by_time.to_string(index=False)
)

print("\nAverage illicit recall across future time steps:")
print(
    round(
        temporal_by_time["Illicit_recall"].mean(),
        4
    )
)

In [ ]:
# ============================================================
# STEP 62 — CLASS RATE BY TIME STEP
# ============================================================

class_rate_by_time = time_class.copy()

class_rate_by_time["illicit_rate"] = (
    class_rate_by_time["class_1"]
    / class_rate_by_time["total_labelled"]
    * 100
)

print("Illicit percentage by time step:\n")

print(
    class_rate_by_time[
        ["class_1", "class_2", "total_labelled", "illicit_rate"]
    ].to_string()
)

print("\nOverall illicit percentage:")
print(
    round(
        total_class_1 / total_labelled * 100,
        2
    ),
    "%"
)

print("\nAverage illicit percentage:")
print(
    round(
        class_rate_by_time["illicit_rate"].mean(),
        2
    ),
    "%"
)

In [ ]:
# ============================================================
# STEP 63 — TRAIN vs FUTURE CLASS DISTRIBUTION
# ============================================================

train_stats = pd.DataFrame({
    "class": y_train_time.value_counts().sort_index()
})

test_stats = pd.DataFrame({
    "class": y_test_time.value_counts().sort_index()
})

train_stats["percentage"] = (
    train_stats["class"] /
    train_stats["class"].sum() * 100
)

test_stats["percentage"] = (
    test_stats["class"] /
    test_stats["class"].sum() * 100
)

print("TRAINING PERIOD — Time steps 1-30")
print(train_stats)

print("\nFUTURE TEST PERIOD — Time steps 31-49")
print(test_stats)

print("\nComparison:")
print(
    pd.DataFrame({
        "Training_%": train_stats["percentage"],
        "Future_%": test_stats["percentage"]
    })
)

In [ ]:
# ============================================================
# STEP 64 — FEATURE DISTRIBUTION SHIFT
# ============================================================

from scipy.stats import wasserstein_distance
import pandas as pd
import numpy as np

shift_results = []

for feature in candidate_features:

    train_values = X_train_time[feature].dropna().values
    test_values = X_test_time[feature].dropna().values

    # Skip completely empty features
    if len(train_values) == 0 or len(test_values) == 0:
        continue

    distance = wasserstein_distance(
        train_values,
        test_values
    )

    # Normalize by combined standard deviation
    combined_std = np.std(
        np.concatenate([train_values, test_values])
    )

    if combined_std > 0:
        normalized_distance = distance / combined_std
    else:
        normalized_distance = 0.0

    shift_results.append({
        "Feature": feature,
        "Wasserstein_Distance": distance,
        "Normalized_Shift": normalized_distance
    })

shift_df = pd.DataFrame(shift_results)

shift_df = shift_df.sort_values(
    "Normalized_Shift",
    ascending=False
).reset_index(drop=True)

print("Total features analyzed:", len(shift_df))

print("\nTop 20 features with largest train → future distribution shift:")
print(
    shift_df.head(20).to_string(index=False)
)

print("\nShift summary:")
print(shift_df["Normalized_Shift"].describe())

In [ ]:
# ============================================================
# STEP 65 — CLASS-CONDITIONAL DISTRIBUTION SHIFT
# ============================================================

from scipy.stats import wasserstein_distance
import numpy as np
import pandas as pd

class_shift_results = []

for feature in candidate_features:

    # Training: illicit and licit separately
    train_illicit = X_train_time.loc[
        y_train_time == 1, feature
    ].dropna().values

    train_licit = X_train_time.loc[
        y_train_time == 2, feature
    ].dropna().values

    # Future: illicit and licit separately
    test_illicit = X_test_time.loc[
        y_test_time == 1, feature
    ].dropna().values

    test_licit = X_test_time.loc[
        y_test_time == 2, feature
    ].dropna().values

    # Need data on both sides
    if (
        len(train_illicit) == 0
        or len(test_illicit) == 0
        or len(train_licit) == 0
        or len(test_licit) == 0
    ):
        continue

    # Illicit distribution shift
    illicit_distance = wasserstein_distance(
        train_illicit,
        test_illicit
    )

    # Licit distribution shift
    licit_distance = wasserstein_distance(
        train_licit,
        test_licit
    )

    # Normalize using combined standard deviation
    illicit_std = np.std(
        np.concatenate([
            train_illicit,
            test_illicit
        ])
    )

    licit_std = np.std(
        np.concatenate([
            train_licit,
            test_licit
        ])
    )

    illicit_shift = (
        illicit_distance / illicit_std
        if illicit_std > 0
        else 0
    )

    licit_shift = (
        licit_distance / licit_std
        if licit_std > 0
        else 0
    )

    class_shift_results.append({
        "Feature": feature,
        "Illicit_Shift": illicit_shift,
        "Licit_Shift": licit_shift,
        "Average_Class_Shift": (
            illicit_shift + licit_shift
        ) / 2
    })

class_shift_df = pd.DataFrame(
    class_shift_results
)

class_shift_df = class_shift_df.sort_values(
    "Average_Class_Shift",
    ascending=False
).reset_index(drop=True)

print("Top 20 features with largest class-conditional shift:")
print(
    class_shift_df
    .head(20)
    .to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 66 — COMBINE IMPORTANCE + TEMPORAL SHIFT
# ============================================================

# RF importance
rf_importance = importance_df[
    ["Feature", "Importance"]
].copy()

rf_importance = rf_importance.rename(
    columns={"Importance": "RF_Importance"}
)

# Permutation importance
perm_importance = permutation_df[
    ["Feature", "Permutation_Importance"]
].copy()

# Temporal shift
shift_info = shift_df[
    ["Feature", "Normalized_Shift"]
].copy()

# Merge all three analyses
feature_diagnostics = (
    rf_importance
    .merge(
        perm_importance,
        on="Feature",
        how="left"
    )
    .merge(
        shift_info,
        on="Feature",
        how="left"
    )
)

# Sort by RF importance
feature_diagnostics = feature_diagnostics.sort_values(
    "RF_Importance",
    ascending=False
).reset_index(drop=True)

print("Feature diagnostic table:")
print(
    feature_diagnostics.head(30).to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 67 — FEATURE STABILITY GROUPS
# ============================================================

diagnostic = feature_diagnostics.dropna(
    subset=[
        "RF_Importance",
        "Permutation_Importance",
        "Normalized_Shift"
    ]
).copy()

# Use medians rather than arbitrary thresholds
rf_threshold = diagnostic["RF_Importance"].median()
shift_threshold = diagnostic["Normalized_Shift"].median()

diagnostic["Importance_Group"] = np.where(
    diagnostic["RF_Importance"] >= rf_threshold,
    "High importance",
    "Low importance"
)

diagnostic["Shift_Group"] = np.where(
    diagnostic["Normalized_Shift"] >= shift_threshold,
    "High shift",
    "Low shift"
)

diagnostic["Group"] = (
    diagnostic["Importance_Group"]
    + " + "
    + diagnostic["Shift_Group"]
)

print("RF importance median:",
      round(rf_threshold, 6))

print("Temporal shift median:",
      round(shift_threshold, 6))

print("\nFeature groups:")
print(
    diagnostic[
        [
            "Feature",
            "RF_Importance",
            "Permutation_Importance",
            "Normalized_Shift",
            "Group"
        ]
    ]
    .sort_values(
        ["Group", "RF_Importance"],
        ascending=[True, False]
    )
    .to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 68 — STABLE FEATURE TEMPORAL EXPERIMENT
# ============================================================

stable_features = diagnostic[
    (diagnostic["Importance_Group"] == "High importance") &
    (diagnostic["Shift_Group"] == "Low shift")
]["Feature"].tolist()

print("Number of stable important features:", len(stable_features))

print("\nStable important features:")
print(stable_features)

# Create reduced temporal datasets
X_train_stable = X_train_time[stable_features].copy()
X_test_stable = X_test_time[stable_features].copy()

print("\nX_train_stable shape:", X_train_stable.shape)
print("X_test_stable shape :", X_test_stable.shape)

In [ ]:
# ============================================================
# STEP 69 — STABLE-FEATURE TEMPORAL RANDOM FOREST
# ============================================================

stable_RF = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training stable-feature temporal Random Forest...")

stable_RF.fit(
    X_train_stable,
    y_train_time
)

print("✅ Stable-feature Random Forest trained successfully.")
print("Number of trees:", len(stable_RF.estimators_))

In [ ]:
# ============================================================
# STEP 70 — STABLE-FEATURE TEMPORAL PREDICTIONS
# ============================================================

y_pred_stable = stable_RF.predict(X_test_stable)

print("Stable-feature predictions generated successfully.")
print("Number of predictions:", len(y_pred_stable))

print("\nFirst 20 predictions:")
print(y_pred_stable[:20])

In [ ]:
# ============================================================
# STEP 71 — EVALUATE STABLE-FEATURE TEMPORAL RF
# ============================================================

cm_stable = confusion_matrix(
    y_test_time,
    y_pred_stable
)

print("Stable-feature Temporal RF Confusion Matrix:")
print(cm_stable)

print("\nStable-feature Temporal RF Classification Report:")

print(
    classification_report(
        y_test_time,
        y_pred_stable,
        target_names=[
            "Illicit (Class 1)",
            "Licit (Class 2)"
        ],
        digits=4
    )
)

stable_accuracy = accuracy_score(
    y_test_time,
    y_pred_stable
)

print(
    "\nStable-feature Temporal RF Accuracy:",
    round(stable_accuracy, 4)
)

In [ ]:
# ============================================================
# STEP 72 — TEMPORAL RF PROBABILITY SCORES
# ============================================================

y_proba_temporal = temporal_RF.predict_proba(
    X_test_time
)

print("Probability matrix shape:")
print(y_proba_temporal.shape)

print("\nClass order:")
print(temporal_RF.classes_)

print("\nFirst 20 illicit probabilities:")
print(
    y_proba_temporal[:20, 0]
)

print("\nProbability range for Class 1:")
print(
    y_proba_temporal[:, 0].min(),
    "to",
    y_proba_temporal[:, 0].max()
)

In [ ]:
# ============================================================
# STEP 73 — TEMPORAL DECISION THRESHOLD ANALYSIS
# ============================================================

from sklearn.metrics import precision_score, recall_score, f1_score

threshold_results = []

# Probability of Class 1 (Illicit)
illicit_probability = y_proba_temporal[:, 0]

for threshold in np.arange(0.10, 0.91, 0.05):

    # Class 1 if probability >= threshold
    threshold_predictions = np.where(
        illicit_probability >= threshold,
        1,
        2
    )

    precision = precision_score(
        y_test_time,
        threshold_predictions,
        pos_label=1,
        zero_division=0
    )

    recall = recall_score(
        y_test_time,
        threshold_predictions,
        pos_label=1,
        zero_division=0
    )

    f1 = f1_score(
        y_test_time,
        threshold_predictions,
        pos_label=1,
        zero_division=0
    )

    flagged = np.sum(
        threshold_predictions == 1
    )

    threshold_results.append({
        "Threshold": round(threshold, 2),
        "Illicit_Precision": precision,
        "Illicit_Recall": recall,
        "Illicit_F1": f1,
        "Flagged_Transactions": flagged
    })

threshold_df = pd.DataFrame(
    threshold_results
)

print("Threshold analysis on future time steps 31–49:\n")

print(
    threshold_df.to_string(index=False)
)

print("\nBest threshold by illicit F1:")

best_f1 = threshold_df.loc[
    threshold_df["Illicit_F1"].idxmax()
]

print(best_f1)

In [ ]:
# ============================================================
# STEP 74 — TEMPORAL VALIDATION SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

# Split the existing training period into:
#   Model-training subset
#   Validation subset
#
# IMPORTANT:
# We keep the original future test period (31-49) untouched.

X_train_model, X_val = train_test_split(
    X_train_time,
    test_size=0.20,
    random_state=42,
    stratify=y_train_time
)

y_train_model, y_val = train_test_split(
    y_train_time,
    test_size=0.20,
    random_state=42,
    stratify=y_train_time
)

print("Training subset shape :", X_train_model.shape)
print("Validation subset shape:", X_val.shape)

print("\nTraining subset distribution:")
print(y_train_model.value_counts())

print("\nValidation subset distribution:")
print(y_val.value_counts())

In [ ]:
# ============================================================
# STEP 75 — VALIDATION RANDOM FOREST
# ============================================================

validation_RF = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training validation Random Forest...")

validation_RF.fit(
    X_train_model,
    y_train_model
)

print("✅ Validation Random Forest trained successfully.")
print("Number of trees:", len(validation_RF.estimators_))

In [ ]:
# ============================================================
# STEP 76 — VALIDATION PROBABILITY SCORES
# ============================================================

y_proba_val = validation_RF.predict_proba(X_val)

print("Validation probability matrix shape:")
print(y_proba_val.shape)

print("\nClass order:")
print(validation_RF.classes_)

print("\nFirst 20 validation illicit probabilities:")
print(y_proba_val[:20, 0])

print("\nClass 1 probability range:")
print(
    y_proba_val[:, 0].min(),
    "to",
    y_proba_val[:, 0].max()
)

In [ ]:
# ============================================================
# STEP 77 — VALIDATION THRESHOLD ANALYSIS
# ============================================================

validation_threshold_results = []

illicit_probability_val = y_proba_val[:, 0]

for threshold in np.arange(0.10, 0.91, 0.05):

    threshold_predictions = np.where(
        illicit_probability_val >= threshold,
        1,
        2
    )

    precision = precision_score(
        y_val,
        threshold_predictions,
        pos_label=1,
        zero_division=0
    )

    recall = recall_score(
        y_val,
        threshold_predictions,
        pos_label=1,
        zero_division=0
    )

    f1 = f1_score(
        y_val,
        threshold_predictions,
        pos_label=1,
        zero_division=0
    )

    flagged = np.sum(
        threshold_predictions == 1
    )

    validation_threshold_results.append({
        "Threshold": round(threshold, 2),
        "Illicit_Precision": precision,
        "Illicit_Recall": recall,
        "Illicit_F1": f1,
        "Flagged_Transactions": flagged
    })

validation_threshold_df = pd.DataFrame(
    validation_threshold_results
)

print("Validation threshold analysis:\n")

print(
    validation_threshold_df.to_string(index=False)
)

print("\nBest threshold by validation illicit F1:")

best_validation_threshold = validation_threshold_df.loc[
    validation_threshold_df["Illicit_F1"].idxmax()
]

print(best_validation_threshold)

In [ ]:
# ============================================================
# STEP 78 — APPLY VALIDATION-SELECTED THRESHOLD TO FUTURE DATA
# ============================================================

selected_threshold = best_validation_threshold["Threshold"]

print("Selected threshold from validation:", selected_threshold)

# Use the ORIGINAL temporal RF probabilities
# on the untouched future period (time steps 31-49)
future_illicit_probability = y_proba_temporal[:, 0]

y_pred_future_threshold = np.where(
    future_illicit_probability >= selected_threshold,
    1,
    2
)

print("\nFuture predictions generated successfully.")
print("Number of future predictions:", len(y_pred_future_threshold))

print("\nFirst 20 future predictions:")
print(y_pred_future_threshold[:20])

In [ ]:
# ============================================================
# STEP 79 — FINAL FUTURE EVALUATION AT VALIDATION THRESHOLD
# ============================================================

cm_future_threshold = confusion_matrix(
    y_test_time,
    y_pred_future_threshold
)

print("Future Confusion Matrix — Threshold 0.45:")
print(cm_future_threshold)

print("\nFuture Classification Report — Threshold 0.45:")

print(
    classification_report(
        y_test_time,
        y_pred_future_threshold,
        target_names=[
            "Illicit (Class 1)",
            "Licit (Class 2)"
        ],
        digits=4
    )
)

future_accuracy_threshold = accuracy_score(
    y_test_time,
    y_pred_future_threshold
)

print(
    "\nFuture Accuracy:",
    round(future_accuracy_threshold, 4)
)

In [ ]:
# ============================================================
# STEP 80 — FUTURE ERROR ANALYSIS BY TIME STEP
# ============================================================

future_error_analysis = []

# Use the original temporal RF predictions at threshold 0.50
predicted_labels = y_pred_time

for time_step in sorted(
    df_supervised.loc[
        df_supervised["Time step"].isin(range(31, 50)),
        "Time step"
    ].unique()
):

    mask = (
        df_supervised.loc[
            df_supervised["Time step"].isin(range(31, 50)),
            "Time step"
        ] == time_step
    ).values

    actual = y_test_time[mask]
    predicted = predicted_labels[mask]

    actual_illicit = np.sum(actual == 1)
    predicted_illicit = np.sum(predicted == 1)

    true_positive = np.sum(
        (actual == 1) & (predicted == 1)
    )

    false_negative = np.sum(
        (actual == 1) & (predicted == 2)
    )

    false_positive = np.sum(
        (actual == 2) & (predicted == 1)
    )

    illicit_recall = (
        true_positive / actual_illicit
        if actual_illicit > 0
        else np.nan
    )

    future_error_analysis.append({
        "Time_step": time_step,
        "Actual_illicit": actual_illicit,
        "Predicted_illicit": predicted_illicit,
        "True_positive": true_positive,
        "False_negative": false_negative,
        "False_positive": false_positive,
        "Illicit_recall": illicit_recall
    })

future_error_df = pd.DataFrame(
    future_error_analysis
)

print("Future-period error analysis:\n")

print(
    future_error_df.to_string(index=False)
)

print("\nAverage illicit recall:")
print(
    round(
        future_error_df["Illicit_recall"].mean(),
        4
    )
)

In [ ]:
# ============================================================
# STEP 80A — RECREATE TEMPORAL RF PREDICTIONS
# ============================================================

print("Generating temporal RF predictions...")

y_pred_time = temporal_RF.predict(X_test_time)

print("✅ Predictions generated successfully.")
print("Number of predictions:", len(y_pred_time))

print("\nFirst 20 predictions:")
print(y_pred_time[:20])

In [ ]:
# ============================================================
# STEP 80 — FUTURE ERROR ANALYSIS BY TIME STEP
# ============================================================

future_error_analysis = []

future_mask = df_supervised["Time step"].isin(range(31, 50))

future_time_steps = df_supervised.loc[
    future_mask, "Time step"
].values

for time_step in sorted(np.unique(future_time_steps)):

    mask = future_time_steps == time_step

    actual = y_test_time[mask]
    predicted = y_pred_time[mask]

    actual_illicit = np.sum(actual == 1)
    predicted_illicit = np.sum(predicted == 1)

    true_positive = np.sum(
        (actual == 1) & (predicted == 1)
    )

    false_negative = np.sum(
        (actual == 1) & (predicted == 2)
    )

    false_positive = np.sum(
        (actual == 2) & (predicted == 1)
    )

    illicit_recall = (
        true_positive / actual_illicit
        if actual_illicit > 0
        else np.nan
    )

    future_error_analysis.append({
        "Time_step": time_step,
        "Actual_illicit": actual_illicit,
        "Predicted_illicit": predicted_illicit,
        "True_positive": true_positive,
        "False_negative": false_negative,
        "False_positive": false_positive,
        "Illicit_recall": illicit_recall
    })

future_error_df = pd.DataFrame(future_error_analysis)

print("Future-period error analysis:\n")
print(future_error_df.to_string(index=False))

print("\nAverage illicit recall:")
print(
    round(
        future_error_df["Illicit_recall"].mean(),
        4
    )
)

In [ ]:
# ============================================================
# STEP 80A — FIND THE TIME-STEP VARIABLE
# ============================================================

print("Variables containing 'time':")

for name in dir():
    if "time" in name.lower():
        print(name)

In [ ]:
# ============================================================
# STEP 80 — FUTURE ERROR ANALYSIS BY TIME STEP
# ============================================================

future_error_analysis = []

# Future test period = time steps 31–49
future_mask = timestep.isin(range(31, 50))

future_time_steps = timestep[future_mask].values

for time_step in sorted(np.unique(future_time_steps)):

    mask = future_time_steps == time_step

    actual = y_test_time[mask]
    predicted = y_pred_time[mask]

    actual_illicit = np.sum(actual == 1)
    predicted_illicit = np.sum(predicted == 1)

    true_positive = np.sum(
        (actual == 1) & (predicted == 1)
    )

    false_negative = np.sum(
        (actual == 1) & (predicted == 2)
    )

    false_positive = np.sum(
        (actual == 2) & (predicted == 1)
    )

    illicit_recall = (
        true_positive / actual_illicit
        if actual_illicit > 0
        else np.nan
    )

    future_error_analysis.append({
        "Time_step": time_step,
        "Actual_illicit": actual_illicit,
        "Predicted_illicit": predicted_illicit,
        "True_positive": true_positive,
        "False_negative": false_negative,
        "False_positive": false_positive,
        "Illicit_recall": illicit_recall
    })

future_error_df = pd.DataFrame(future_error_analysis)

print("Future-period error analysis:\n")
print(future_error_df.to_string(index=False))

print("\nAverage illicit recall:")
print(
    round(
        future_error_df["Illicit_recall"].mean(),
        4
    )
)

In [ ]:
# ============================================================
# STEP 80A — CHECK TIME-STEP VARIABLES
# ============================================================

for name in [
    "timestep",
    "time_summary",
    "temporal_by_time",
    "time_class",
    "class_rate_by_time"
]:
    if name in globals():
        obj = globals()[name]

        print("\n" + "=" * 70)
        print(name)
        print("=" * 70)

        print("Type:", type(obj))

        try:
            print("Shape:", obj.shape)
        except:
            print("Shape: Not available")

        try:
            print("Length:", len(obj))
        except:
            print("Length: Not available")

        print("Sample:")
        print(obj[:5] if hasattr(obj, "__getitem__") else obj)

In [ ]:
# ============================================================
# STEP 80B — SAFELY INSPECT TIME VARIABLES
# ============================================================

for name in [
    "time_summary",
    "temporal_by_time",
    "time_class",
    "class_rate_by_time"
]:
    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    if name not in globals():
        print("NOT FOUND")
        continue

    obj = globals()[name]

    print("Type:", type(obj))

    try:
        print("Shape:", obj.shape)
    except:
        print("Shape: Not available")

    try:
        print("Length:", len(obj))
    except:
        print("Length: Not available")

    print("\nFirst few values:")

    try:
        print(obj.head())
    except:
        try:
            print(obj[:5])
        except:
            print(obj)

In [ ]:
# ============================================================
# STEP 80C — INSPECT FUTURE ERROR ANALYSIS
# ============================================================

print("Future error analysis — Time steps 31–49")
print("=" * 80)

print(temporal_by_time.to_string(index=False))

print("\n" + "=" * 80)
print("Worst future time steps by illicit recall:")
print("=" * 80)

print(
    temporal_by_time
    .sort_values("Illicit_recall")
    [["Time_step", "Actual_illicit",
      "Predicted_illicit", "True_positive",
      "False_negative", "Illicit_recall"]]
    .head(10)
    .to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 81 — COMBINE ERROR ANALYSIS WITH ILLICIT RATE
# ============================================================

# Get future-period illicit rates
future_rates = class_rate_by_time.loc[
    class_rate_by_time.index.isin(range(31, 50)),
    ["illicit_rate"]
].reset_index()

# Make sure column name is Time_step
future_rates = future_rates.rename(
    columns={"Time step": "Time_step"}
)

# Combine with temporal error analysis
temporal_diagnostic = temporal_by_time.merge(
    future_rates,
    on="Time_step",
    how="left"
)

print("Combined temporal diagnostic:")
print("=" * 80)

print(
    temporal_diagnostic.to_string(index=False)
)

print("\n" + "=" * 80)
print("Latest future time steps:")
print("=" * 80)

print(
    temporal_diagnostic[
        temporal_diagnostic["Time_step"] >= 43
    ].to_string(index=False)
)

In [ ]:
# ============================================================
# STEP 66 — FUTURE TIME-STEP ANALYSIS AT SELECTED THRESHOLD
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

# ------------------------------------------------------------
# 1. Get probability predictions from temporal RF
# ------------------------------------------------------------

temporal_proba = temporal_RF.predict_proba(X_test_time)

print("Probability matrix shape:", temporal_proba.shape)
print("Class order:", temporal_RF.classes_)

# Find probability column corresponding to illicit class = 1
class_1_index = list(temporal_RF.classes_).index(1)

illicit_proba_future = temporal_proba[:, class_1_index]

# ------------------------------------------------------------
# 2. Apply selected threshold
# ------------------------------------------------------------

SELECTED_THRESHOLD = 0.45

y_pred_future_045 = np.where(
    illicit_proba_future >= SELECTED_THRESHOLD,
    1,
    2
)

print("\nSelected threshold:", SELECTED_THRESHOLD)
print("Future predictions:", len(y_pred_future_045))

# ------------------------------------------------------------
# 3. Overall confusion matrix
# ------------------------------------------------------------

cm = confusion_matrix(
    y_test_time,
    y_pred_future_045,
    labels=[1, 2]
)

print("\nFuture Confusion Matrix — Threshold 0.45:")
print(cm)

In [ ]:
# ============================================================
# STEP  — FUTURE ERROR ANALYSIS AT SELECTED THRESHOLD
# ============================================================

import pandas as pd
import numpy as np

# Future predictions already generated using threshold = 0.45
future_error_analysis_045 = []

# y_test_time contains actual labels
# timestep_test contains corresponding time steps
# If your timestep variable has a different name, use that variable.

# ------------------------------------------------------------
# Find the correct time-step variable
# ------------------------------------------------------------

print("Available time-related variables:")
for name in [
    "timestep",
    "time_class",
    "temporal_by_time",
    "time_summary",
    "class_rate_by_time"
]:
    if name in globals():
        obj = globals()[name]
        print(f"{name}: {type(obj)}")


# ------------------------------------------------------------
# IMPORTANT:
# We need one time-step value for every row of X_test_time.
# Try common possibilities automatically.
# ------------------------------------------------------------

time_test = None

# Case 1: timestep is an array/Series
if "timestep" in globals():
    if hasattr(timestep, "__len__") and len(timestep) == len(y_test_time):
        time_test = np.asarray(timestep)

# Case 2: X_test_time has time-step information
if time_test is None and hasattr(X_test_time, "columns"):
    possible_time_cols = [
        "Time step",
        "Time_step",
        "time_step",
        "timestep",
        "Time"
    ]

    for col in possible_time_cols:
        if col in X_test_time.columns:
            time_test = X_test_time[col].values
            break


if time_test is None:
    print("\n❌ Could not automatically find time-step values.")
    print("We need the array/Series containing the time step for each")
    print("row of X_test_time.")
else:

    print("\n✅ Time-step vector found.")
    print("Length:", len(time_test))
    print("Unique future steps:", sorted(pd.Series(time_test).unique()))


    # --------------------------------------------------------
    # Per-time-step analysis
    # --------------------------------------------------------

    future_steps = sorted(
        pd.Series(time_test).loc[
            pd.Series(time_test).isin(range(31, 50))
        ].unique()
    )

    for ts in future_steps:

        mask = np.asarray(time_test) == ts

        y_actual = np.asarray(y_test_time)[mask]
        y_pred = np.asarray(y_pred_future)[mask]

        actual_illicit = np.sum(y_actual == 1)
        predicted_illicit = np.sum(y_pred == 1)

        true_positive = np.sum(
            (y_actual == 1) & (y_pred == 1)
        )

        false_negative = np.sum(
            (y_actual == 1) & (y_pred == 2)
        )

        false_positive = np.sum(
            (y_actual == 2) & (y_pred == 1)
        )

        if actual_illicit > 0:
            recall = true_positive / actual_illicit
        else:
            recall = np.nan

        precision = (
            true_positive / predicted_illicit
            if predicted_illicit > 0
            else np.nan
        )

        future_error_analysis_045.append({
            "Time_step": ts,
            "Actual_illicit": actual_illicit,
            "Predicted_illicit": predicted_illicit,
            "True_positive": true_positive,
            "False_negative": false_negative,
            "False_positive": false_positive,
            "Illicit_precision": precision,
            "Illicit_recall": recall
        })


    future_error_analysis_045 = pd.DataFrame(
        future_error_analysis_045
    )

    print("\n" + "=" * 80)
    print("FUTURE ERROR ANALYSIS — THRESHOLD 0.45")
    print("=" * 80)

    print(
        future_error_analysis_045.to_string(index=False)
    )


    # --------------------------------------------------------
    # Worst future time steps
    # --------------------------------------------------------

    print("\n" + "=" * 80)
    print("WORST FUTURE TIME STEPS BY ILLICIT RECALL")
    print("=" * 80)

    print(
        future_error_analysis_045
        .sort_values("Illicit_recall")
        .head(10)
        .to_string(index=False)
    )


    # --------------------------------------------------------
    # Latest time steps
    # --------------------------------------------------------

    print("\n" + "=" * 80)
    print("LATEST FUTURE TIME STEPS")
    print("=" * 80)

    print(
        future_error_analysis_045
        .tail(7)
        .to_string(index=False)
    )

In [ ]:
# ============================================================
# FIND ORIGINAL DATAFRAME / TIME-STEP COLUMN
# ============================================================

import pandas as pd
import numpy as np

print("Possible DataFrame variables containing time information:\n")

for name, obj in globals().items():
    try:
        if isinstance(obj, pd.DataFrame):
            cols = [str(c) for c in obj.columns]

            time_cols = [
                c for c in cols
                if "time" in c.lower() or "step" in c.lower()
            ]

            if time_cols:
                print(f"\n{name}")
                print("Shape:", obj.shape)
                print("Time-related columns:", time_cols)
    except:
        pass

In [ ]:
# ============================================================
# FIND DATAFRAMES WITH TIME-RELATED COLUMNS
# ============================================================

import pandas as pd
import numpy as np

print("Possible DataFrame variables containing time information:\n")

# IMPORTANT: list() creates a snapshot, so globals() can change safely
all_variables = list(globals().items())

for name, obj in all_variables:
    try:
        if isinstance(obj, pd.DataFrame):

            cols = [str(c) for c in obj.columns]

            time_cols = [
                c for c in cols
                if "time" in c.lower() or "step" in c.lower()
            ]

            if time_cols:
                print("\n" + "=" * 70)
                print("Variable:", name)
                print("Shape:", obj.shape)
                print("Time-related columns:", time_cols)

    except Exception:
        pass

In [ ]:
# ============================================================
# STEP — FUTURE ERROR ANALYSIS AT THRESHOLD 0.45
# ============================================================

import pandas as pd
import numpy as np

# Time-step for every future-test transaction
time_test = temporal_results["Time step"].to_numpy()

# Safety checks
print("Number of time-step values:", len(time_test))
print("Number of future predictions:", len(y_pred_future))
print("Number of actual labels:", len(y_test_time))

assert len(time_test) == len(y_pred_future) == len(y_test_time)

# ------------------------------------------------------------
# Per-time-step error analysis
# ------------------------------------------------------------

future_error_analysis_045 = []

for ts in range(31, 50):

    mask = time_test == ts

    y_actual = np.asarray(y_test_time)[mask]
    y_pred = np.asarray(y_pred_future)[mask]

    actual_illicit = np.sum(y_actual == 1)
    predicted_illicit = np.sum(y_pred == 1)

    true_positive = np.sum(
        (y_actual == 1) & (y_pred == 1)
    )

    false_negative = np.sum(
        (y_actual == 1) & (y_pred == 2)
    )

    false_positive = np.sum(
        (y_actual == 2) & (y_pred == 1)
    )

    illicit_recall = (
        true_positive / actual_illicit
        if actual_illicit > 0
        else np.nan
    )

    illicit_precision = (
        true_positive / predicted_illicit
        if predicted_illicit > 0
        else np.nan
    )

    future_error_analysis_045.append({
        "Time_step": ts,
        "Actual_illicit": actual_illicit,
        "Predicted_illicit": predicted_illicit,
        "True_positive": true_positive,
        "False_negative": false_negative,
        "False_positive": false_positive,
        "Illicit_precision": illicit_precision,
        "Illicit_recall": illicit_recall
    })

future_error_analysis_045 = pd.DataFrame(
    future_error_analysis_045
)

print("\n" + "=" * 90)
print("FUTURE ERROR ANALYSIS — THRESHOLD 0.45")
print("=" * 90)

print(
    future_error_analysis_045.to_string(index=False)
)

# ------------------------------------------------------------
# Worst time steps
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("WORST FUTURE TIME STEPS BY ILLICIT RECALL")
print("=" * 90)

print(
    future_error_analysis_045
    .sort_values("Illicit_recall")
    .head(10)
    .to_string(index=False)
)

# ------------------------------------------------------------
# Latest future time steps
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("LATEST FUTURE TIME STEPS — 43 TO 49")
print("=" * 90)

print(
    future_error_analysis_045[
        future_error_analysis_045["Time_step"] >= 43
    ].to_string(index=False)
)

In [ ]:
# ============================================================
# FIND FUTURE PREDICTION VARIABLE
# ============================================================

import numpy as np

print("Prediction-like variables:\n")

for name, obj in list(globals().items()):
    try:
        if isinstance(obj, (np.ndarray, list)):
            length = len(obj)

            if length == 19659:
                print(
                    f"{name:35s} "
                    f"type={type(obj).__name__:<12s} "
                    f"length={length}"
                )
    except:
        pass

In [ ]:
# ============================================================
# FUTURE ERROR ANALYSIS — THRESHOLD 0.45
# ============================================================

import pandas as pd
import numpy as np

# Exact future-test time steps
time_test = temporal_results["Time step"].to_numpy()

# Exact threshold-0.45 predictions
pred_045 = np.asarray(y_pred_future_045)

# Actual future labels
actual = np.asarray(y_test_time)

# Safety checks
print("Time-step values :", len(time_test))
print("Actual labels    :", len(actual))
print("Predictions      :", len(pred_045))

assert len(time_test) == len(actual) == len(pred_045)

future_error_analysis_045 = []

for ts in range(31, 50):

    mask = time_test == ts

    y_actual_ts = actual[mask]
    y_pred_ts = pred_045[mask]

    actual_illicit = np.sum(y_actual_ts == 1)
    predicted_illicit = np.sum(y_pred_ts == 1)

    true_positive = np.sum(
        (y_actual_ts == 1) &
        (y_pred_ts == 1)
    )

    false_negative = np.sum(
        (y_actual_ts == 1) &
        (y_pred_ts == 2)
    )

    false_positive = np.sum(
        (y_actual_ts == 2) &
        (y_pred_ts == 1)
    )

    precision = (
        true_positive / predicted_illicit
        if predicted_illicit > 0
        else np.nan
    )

    recall = (
        true_positive / actual_illicit
        if actual_illicit > 0
        else np.nan
    )

    future_error_analysis_045.append({
        "Time_step": ts,
        "Actual_illicit": actual_illicit,
        "Predicted_illicit": predicted_illicit,
        "True_positive": true_positive,
        "False_negative": false_negative,
        "False_positive": false_positive,
        "Illicit_precision": precision,
        "Illicit_recall": recall
    })

future_error_analysis_045 = pd.DataFrame(
    future_error_analysis_045
)

print("\n" + "=" * 90)
print("FUTURE ERROR ANALYSIS — THRESHOLD 0.45")
print("=" * 90)

print(
    future_error_analysis_045.to_string(index=False)
)

# ============================================================
# WORST TIME STEPS
# ============================================================

print("\n" + "=" * 90)
print("WORST FUTURE TIME STEPS BY ILLICIT RECALL")
print("=" * 90)

print(
    future_error_analysis_045
    .sort_values("Illicit_recall")
    .head(10)
    .to_string(index=False)
)

# ============================================================
# LATEST TIME STEPS
# ============================================================

print("\n" + "=" * 90)
print("LATEST FUTURE TIME STEPS — 43 TO 49")
print("=" * 90)

print(
    future_error_analysis_045[
        future_error_analysis_045["Time_step"].between(43, 49)
    ].to_string(index=False)
)

In [1]:
import pandas as pd
import numpy as np
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles/folders:")
print(os.listdir())

Current working directory:
c:\Users\YASHIKA\Desktop\bit-trace\src

Files/folders:
['inspect_txs.ipynb']

In [2]:
import os

dataset_path = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus"

print("Dataset folder exists:", os.path.exists(dataset_path))

if os.path.exists(dataset_path):
    print("\nFiles inside EllipticPlusPlus:")
    for f in os.listdir(dataset_path):
        print(f)

Dataset folder exists: True

Files inside EllipticPlusPlus:
.git
.gitattributes
Actors Dataset
images
README.md
Transactions Dataset

In [3]:
import os

transactions_path = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset"

print("Transactions Dataset exists:", os.path.exists(transactions_path))

if os.path.exists(transactions_path):
    print("\nFiles/folders:")
    for item in os.listdir(transactions_path):
        full_path = os.path.join(transactions_path, item)

        if os.path.isdir(full_path):
            print(f"[FOLDER] {item}")
        else:
            size_mb = os.path.getsize(full_path) / (1024 * 1024)
            print(f"[FILE]   {item} — {size_mb:.2f} MB")

Transactions Dataset exists: True

Files/folders:
[FILE]   Elliptic++_Transactions_Case_Analysis.ipynb — 0.09 MB
[FILE]   Elliptic++_Transactions_Classification.ipynb — 0.15 MB
[FILE]   Elliptic++_Transactions_Dataset_Statistics.ipynb — 0.99 MB
[FILE]   Elliptic++_Transactions_Feature_Analysis.ipynb — 0.18 MB
[FILE]   Elliptic++_Transactions_Graph_Visualization.ipynb — 1.82 MB
[FILE]   README.md — 0.00 MB
[FILE]   txs_classes.csv — 2.25 MB
[FILE]   txs_edgelist.csv — 4.26 MB
[FILE]   txs_features.csv — 662.60 MB

In [1]:
import pandas as pd
import os

transactions_path = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset"

classes_path = os.path.join(
    transactions_path,
    "txs_classes.csv"
)

txs_classes = pd.read_csv(classes_path)

print("Shape:", txs_classes.shape)
print("\nColumns:")
print(txs_classes.columns.tolist())

print("\nFirst 10 rows:")
display(txs_classes.head(10))

print("\nData types:")
print(txs_classes.dtypes)

Shape: (203769, 2)

Columns:
['txId', 'class']

First 10 rows:

     txId  class
0    3321      3
1   11108      3
2   51816      3
3   68869      2
4   89273      2
5  195142      3
6  223263      3
7  223265      3
8  245992      3
9  267260      3

Data types:
txId     int64
class    int64
dtype: object

In [2]:
print("=" * 60)
print("TRANSACTION CLASS DISTRIBUTION")
print("=" * 60)

class_counts = txs_classes["class"].value_counts().sort_index()

class_percent = (
    txs_classes["class"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

class_summary = pd.DataFrame({
    "Count": class_counts,
    "Percentage": class_percent.round(4)
})

display(class_summary)

print("\nTotal transactions:", len(txs_classes))
print("Number of classes:", txs_classes["class"].nunique())
print("Unique classes:", sorted(txs_classes["class"].unique()))

============================================================
TRANSACTION CLASS DISTRIBUTION
============================================================

        Count  Percentage
class
1        4545      2.2305
2       42019     20.6209
3      157205     77.1486

Total transactions: 203769
Number of classes: 3
Unique classes: [np.int64(1), np.int64(2), np.int64(3)]

In [3]:
# ============================================================
# STEP 3 — CLASS DISTRIBUTION BY TIME STEP
# ============================================================

print("=" * 70)
print("CLASS DISTRIBUTION BY TIME STEP")
print("=" * 70)

# Load only the columns needed from the large features file
features_path = os.path.join(
    transactions_path,
    "txs_features.csv"
)

features_time = pd.read_csv(
    features_path,
    usecols=["txId", "Time step"]
)

print("Features time data shape:", features_time.shape)

# Merge class information with time step
class_time = features_time.merge(
    txs_classes,
    on="txId",
    how="inner"
)

print("Merged shape:", class_time.shape)

# Count each class at every time step
class_by_time = pd.crosstab(
    class_time["Time step"],
    class_time["class"]
)

# Make sure all three class columns exist
for c in [1, 2, 3]:
    if c not in class_by_time.columns:
        class_by_time[c] = 0

class_by_time = class_by_time[[1, 2, 3]]

# Rename columns
class_by_time.columns = [
    "Class_1",
    "Class_2",
    "Class_3"
]

class_by_time["Total"] = class_by_time.sum(axis=1)

display(class_by_time.head(15))

print("\nNumber of time steps:", len(class_by_time))
print("Time-step range:",
      class_by_time.index.min(),
      "to",
      class_by_time.index.max())

======================================================================
CLASS DISTRIBUTION BY TIME STEP
======================================================================
Features time data shape: (203769, 2)
Merged shape: (203769, 3)

           Class_1  Class_2  Class_3  Total
Time step
1               17     2130     5733   7880
2               18     1099     3427   4544
3               11     1268     5342   6621
4               30     1410     4253   5693
5                8     1874     4921   6803
6                5      480     3843   4328
7              102     1101     4845   6048
8               67     1098     3292   4457
9              248      530     4218   4996
10              18      954     5755   6727
11             131      565     3600   4296
12              16      490     1541   2047
13             291      518     3719   4528
14              43      374     1605   2022
15             147      471     3021   3639

Number of time steps: 49
Time-step range: 1 to 49

In [6]:
# ============================================================
# STEP 4 — CLASS PERCENTAGE BY TIME STEP
# ============================================================

class_rate_by_time_all = class_by_time.copy()

class_rate_by_time_all["Class_1_%"] = (
    class_rate_by_time_all["Class_1"]
    / class_rate_by_time_all["Total"]
    * 100
)

class_rate_by_time_all["Class_2_%"] = (
    class_rate_by_time_all["Class_2"]
    / class_rate_by_time_all["Total"]
    * 100
)

class_rate_by_time_all["Class_3_%"] = (
    class_rate_by_time_all["Class_3"]
    / class_rate_by_time_all["Total"]
    * 100
)

print("=" * 70)
print("CLASS PERCENTAGE BY TIME STEP")
print("=" * 70)

display(
    class_rate_by_time_all[
        [
            "Class_1",
            "Class_2",
            "Class_3",
            "Total",
            "Class_1_%",
            "Class_2_%",
            "Class_3_%"
        ]
    ].round(2)
)

======================================================================
CLASS PERCENTAGE BY TIME STEP
======================================================================

           Class_1  Class_2  Class_3  Total  Class_1_%  Class_2_%  Class_3_%
Time step
1               17     2130     5733   7880       0.22      27.03      72.75
2               18     1099     3427   4544       0.40      24.19      75.42
3               11     1268     5342   6621       0.17      19.15      80.68
4               30     1410     4253   5693       0.53      24.77      74.71
5                8     1874     4921   6803       0.12      27.55      72.34
6                5      480     3843   4328       0.12      11.09      88.79
7              102     1101     4845   6048       1.69      18.20      80.11
8               67     1098     3292   4457       1.50      24.64      73.86
9              248      530     4218   4996       4.96      10.61      84.43
10              18      954     5755   6727       0.27      14.18      85.55
11             131      565     3600   4296       3.05      13.15      83.80
12              16      490     1541   2047       0.78      23.94      75.28
13             291      518     3719   4528       6.43      11.44      82.13
14              43      374     1605   2022       2.13      18.50      79.38
15             147      471     3021   3639       4.04      12.94      83.02
16             128      402     2445   2975       4.30      13.51      82.18
17              99      712     2574   3385       2.92      21.03      76.04
18              52      337     1587   1976       2.63      17.05      80.31
19              80      665     2761   3506       2.28      18.97      78.75
20             260      640     3391   4291       6.06      14.91      79.03
21             100      541     2896   3537       2.83      15.30      81.88
22             158     1605     4131   5894       2.68      27.23      70.09
23              53     1134     2978   4165       1.27      27.23      71.50
24             137      989     3466   4592       2.98      21.54      75.48
25             118      476     1720   2314       5.10      20.57      74.33
26              96      421     2006   2523       3.80      16.69      79.51
27              24      182      883   1089       2.20      16.71      81.08
28              85      199     1369   1653       5.14      12.04      82.82
29             329      845     3101   4275       7.70      19.77      72.54
30              83      441     1959   2483       3.34      17.76      78.90
31             106      604     2106   2816       3.76      21.45      74.79
32             342      981     3202   4525       7.56      21.68      70.76
33              23      418     2710   3151       0.73      13.27      86.00
34              37      478     1971   2486       1.49      19.23      79.28
35             182     1159     4166   5507       3.30      21.05      75.65
36              33     1675     4685   6393       0.52      26.20      73.28
37              40      458     2808   3306       1.21      13.85      84.94
38             111      645     2135   2891       3.84      22.31      73.85
39              81     1102     1577   2760       2.93      39.93      57.14
40             112     1099     3270   4481       2.50      24.53      72.97
41             116     1016     4210   5342       2.17      19.02      78.81
42             239     1915     4986   7140       3.35      26.82      69.83
43              24     1346     3693   5063       0.47      26.59      72.94
44              24     1567     3384   4975       0.48      31.50      68.02
45               5     1216     4377   5598       0.09      21.72      78.19
46               2      710     2807   3519       0.06      20.18      79.77
47              22      824     4275   5121       0.43      16.09      83.48
48              36      435     2483   2954       1.22      14.73      84.06
49              56      420     1978   2454       2.28      17.11      80.60

In [7]:
import pandas as pd
import os

features_path = "../EllipticPlusPlus/Transactions Dataset/txs_features.csv"

features_df = pd.read_csv(features_path)

print("=" * 70)
print("TRANSACTION FEATURES DATASET")
print("=" * 70)

print("Shape:", features_df.shape)
print("\nColumns:")
print(features_df.columns.tolist())

print("\nData types:")
print(features_df.dtypes)

print("\nFirst 5 rows:")
display(features_df.head())

======================================================================
TRANSACTION FEATURES DATASET
======================================================================
Shape: (203769, 184)

Columns:
['txId', 'Time step', 'Local_feature_1', 'Local_feature_2', 'Local_feature_3', 'Local_feature_4', 'Local_feature_5', 'Local_feature_6', 'Local_feature_7', 'Local_feature_8', 'Local_feature_9', 'Local_feature_10', 'Local_feature_11', 'Local_feature_12', 'Local_feature_13', 'Local_feature_14', 'Local_feature_15', 'Local_feature_16', 'Local_feature_17', 'Local_feature_18', 'Local_feature_19', 'Local_feature_20', 'Local_feature_21', 'Local_feature_22', 'Local_feature_23', 'Local_feature_24', 'Local_feature_25', 'Local_feature_26', 'Local_feature_27', 'Local_feature_28', 'Local_feature_29', 'Local_feature_30', 'Local_feature_31', 'Local_feature_32', 'Local_feature_33', 'Local_feature_34', 'Local_feature_35', 'Local_feature_36', 'Local_feature_37', 'Local_feature_38', 'Local_feature_39', 'Local_feature_40', 'Local_feature_41', 'Local_feature_42', 'Local_feature_43', 'Local_feature_44', 'Local_feature_45', 'Local_feature_46', 'Local_feature_47', 'Local_feature_48', 'Local_feature_49', 'Local_feature_50', 'Local_feature_51', 'Local_feature_52', 'Local_feature_53', 'Local_feature_54', 'Local_feature_55', 'Local_feature_56', 'Local_feature_57', 'Local_feature_58', 'Local_feature_59', 'Local_feature_60', 'Local_feature_61', 'Local_feature_62', 'Local_feature_63', 'Local_feature_64', 'Local_feature_65', 'Local_feature_66', 'Local_feature_67', 'Local_feature_68', 'Local_feature_69', 'Local_feature_70', 'Local_feature_71', 'Local_feature_72', 'Local_feature_73', 'Local_feature_74', 'Local_feature_75', 'Local_feature_76', 'Local_feature_77', 'Local_feature_78', 'Local_feature_79', 'Local_feature_80', 'Local_feature_81', 'Local_feature_82', 'Local_feature_83', 'Local_feature_84', 'Local_feature_85', 'Local_feature_86', 'Local_feature_87', 'Local_feature_88', 'Local_feature_89', 'Local_feature_90', 'Local_feature_91', 'Local_feature_92', 'Local_feature_93', 'Aggregate_feature_1', 'Aggregate_feature_2', 'Aggregate_feature_3', 'Aggregate_feature_4', 'Aggregate_feature_5', 'Aggregate_feature_6', 'Aggregate_feature_7', 'Aggregate_feature_8', 'Aggregate_feature_9', 'Aggregate_feature_10', 'Aggregate_feature_11', 'Aggregate_feature_12', 'Aggregate_feature_13', 'Aggregate_feature_14', 'Aggregate_feature_15', 'Aggregate_feature_16', 'Aggregate_feature_17', 'Aggregate_feature_18', 'Aggregate_feature_19', 'Aggregate_feature_20', 'Aggregate_feature_21', 'Aggregate_feature_22', 'Aggregate_feature_23', 'Aggregate_feature_24', 'Aggregate_feature_25', 'Aggregate_feature_26', 'Aggregate_feature_27', 'Aggregate_feature_28', 'Aggregate_feature_29', 'Aggregate_feature_30', 'Aggregate_feature_31', 'Aggregate_feature_32', 'Aggregate_feature_33', 'Aggregate_feature_34', 'Aggregate_feature_35', 'Aggregate_feature_36', 'Aggregate_feature_37', 'Aggregate_feature_38', 'Aggregate_feature_39', 'Aggregate_feature_40', 'Aggregate_feature_41', 'Aggregate_feature_42', 'Aggregate_feature_43', 'Aggregate_feature_44', 'Aggregate_feature_45', 'Aggregate_feature_46', 'Aggregate_feature_47', 'Aggregate_feature_48', 'Aggregate_feature_49', 'Aggregate_feature_50', 'Aggregate_feature_51', 'Aggregate_feature_52', 'Aggregate_feature_53', 'Aggregate_feature_54', 'Aggregate_feature_55', 'Aggregate_feature_56', 'Aggregate_feature_57', 'Aggregate_feature_58', 'Aggregate_feature_59', 'Aggregate_feature_60', 'Aggregate_feature_61', 'Aggregate_feature_62', 'Aggregate_feature_63', 'Aggregate_feature_64', 'Aggregate_feature_65', 'Aggregate_feature_66', 'Aggregate_feature_67', 'Aggregate_feature_68', 'Aggregate_feature_69', 'Aggregate_feature_70', 'Aggregate_feature_71', 'Aggregate_feature_72', 'in_txs_degree', 'out_txs_degree', 'total_BTC', 'fees', 'size', 'num_input_addresses', 'num_output_addresses', 'in_BTC_min', 'in_BTC_max', 'in_BTC_mean', 'in_BTC_median', 'in_BTC_total', 'out_BTC_min', 'out_BTC_max', 'out_BTC_mean', 'out_BTC_median', 'out_BTC_total']

Data types:
txId                 int64
Time step            int64
Local_feature_1    float64
Local_feature_2    float64
Local_feature_3    float64
                    ...
out_BTC_min        float64
out_BTC_max        float64
out_BTC_mean       float64
out_BTC_median     float64
out_BTC_total      float64
Length: 184, dtype: object

First 5 rows:

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,...,in_BTC_min,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,...,0.534072,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,...,5.611878,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,...,0.456608,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,...,0.308900,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,...,852.164680,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680

In [8]:
# ============================================================
# STEP — CLASS-WISE FEATURE ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

# Merge labels with features if needed
class_feature_df = features_df.merge(
    txs_classes,
    on="txId",
    how="inner"
)

print("=" * 70)
print("CLASS-WISE FEATURE ANALYSIS")
print("=" * 70)

print("Shape:", class_feature_df.shape)

print("\nClass distribution:")
print(class_feature_df["class"].value_counts().sort_index())

# Only numeric feature columns
exclude_cols = ["txId", "Time step", "class"]

feature_cols = [
    c for c in class_feature_df.columns
    if c not in exclude_cols
    and pd.api.types.is_numeric_dtype(class_feature_df[c])
]

print("\nNumber of numeric features:", len(feature_cols))

# Mean by class
class_means = class_feature_df.groupby("class")[feature_cols].mean().T

print("\nClass-wise feature means:")
display(class_means.head(20))

======================================================================
CLASS-WISE FEATURE ANALYSIS
======================================================================
Shape: (203769, 185)

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

Number of numeric features: 182

Class-wise feature means:

class                    1         2         3
Local_feature_1  -0.165745 -0.040412  0.015594
Local_feature_2  -0.030698  0.179633 -0.047126
Local_feature_3   0.212061  0.142150 -0.044126
Local_feature_4   0.010803  0.189676 -0.051010
Local_feature_5  -0.056724  0.037886 -0.008486
Local_feature_6   0.033743  0.200728 -0.054628
Local_feature_7  -0.059910 -0.010565  0.004556
Local_feature_8  -0.157009 -0.068886  0.022952
Local_feature_9  -0.162628 -0.048342  0.017623
Local_feature_10 -0.047957  0.115840 -0.029576
Local_feature_11 -0.159209 -0.063334  0.021531
Local_feature_12 -0.042305 -0.200415  0.054792
Local_feature_13 -0.051511 -0.168849  0.046620
Local_feature_14 -0.056060  0.040394 -0.009176
Local_feature_15 -0.013282 -0.013088  0.003882
Local_feature_16 -0.039547  0.059852 -0.014854
Local_feature_17 -0.163989 -0.045635  0.016939
Local_feature_18 -0.166146 -0.080153  0.026228
Local_feature_19 -0.166572 -0.076728  0.025324
Local_feature_20 -0.101433 -0.250923  0.070001

In [9]:
# ============================================================
# STEP — CLASS 3 DISTINCTIVE FEATURES
# ============================================================

from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

# Class-wise means already calculated
class_means = class_feature_df.groupby("class")[feature_cols].mean()

# Difference of Class 3 from Classes 1 and 2
class3_vs_1 = (class_means.loc[3] - class_means.loc[1]).abs()
class3_vs_2 = (class_means.loc[3] - class_means.loc[2]).abs()

# Average difference from both classes
class3_distinctiveness = (
    class3_vs_1 + class3_vs_2
) / 2

class3_diagnostic = pd.DataFrame({
    "Class1_Mean": class_means.loc[1],
    "Class2_Mean": class_means.loc[2],
    "Class3_Mean": class_means.loc[3],
    "Abs_Diff_Class3_vs_Class1": class3_vs_1,
    "Abs_Diff_Class3_vs_Class2": class3_vs_2,
    "Class3_Distinctiveness": class3_distinctiveness
})

class3_diagnostic = class3_diagnostic.sort_values(
    "Class3_Distinctiveness",
    ascending=False
)

print("=" * 80)
print("TOP FEATURES DISTINCTIVE FOR CLASS 3")
print("=" * 80)

display(class3_diagnostic.head(20))

================================================================================
TOP FEATURES DISTINCTIVE FOR CLASS 3
================================================================================

,Class1_Mean,Class2_Mean,Class3_Mean,Abs_Diff_Class3_vs_Class1,Abs_Diff_Class3_vs_Class2,Class3_Distinctiveness
size,474.487349,1071.886675,474.750783,0.263434,597.135892,298.699663
in_BTC_min,1.028379,14.826540,28.993505,27.965125,14.166964,21.066045
in_BTC_median,1.042202,15.800822,29.122890,28.080688,13.322068,20.701378
in_BTC_mean,1.045645,16.077112,29.163192,28.117547,13.086080,20.601814
in_BTC_max,1.073702,19.232069,29.482048,28.408347,10.249979,19.329163
out_BTC_total,1.147426,21.240166,29.978915,28.831489,8.738749,18.785119
total_BTC,1.147426,21.240166,29.978915,28.831489,8.738749,18.785119
in_BTC_total,1.148121,21.241678,29.979546,28.831425,8.737868,18.784646
out_BTC_max,1.104376,19.559865,29.084414,27.980038,9.524549,18.752294
out_BTC_mean,0.648984,6.727923,13.534084,12.885099,6.806161,9.845630
out_BTC_median,0.647219,5.989511,13.097112,12.449893,7.107601,9.778747
num_output_addresses,1.352695,6.171494,3.782290,2.429595,2.389204,2.409399
num_input_addresses,2.769417,5.199373,1.948009,0.821408,3.251364,2.036386
in_txs_degree,1.269967,1.924434,0.944801,0.325166,0.979633,0.652400
Local_feature_53,-0.267997,0.994976,-0.258197,0.009800,1.253173,0.631486
out_BTC_min,0.195815,1.299291,0.466458,0.270643,0.832833,0.551738
Local_feature_55,-0.251836,0.830949,-0.214822,0.037014,1.045770,0.541392
Local_feature_54,-0.139124,0.763076,-0.199939,0.060815,0.963015,0.511915
Local_feature_90,-0.532172,0.491296,-0.115932,0.416241,0.607227,0.511734
Local_feature_89,-0.502142,0.497936,-0.118575,0.383567,0.616511,0.500039

In [10]:
# ============================================================
# STEP — CLASS 3 FEATURE SEPARATION
# ============================================================

from sklearn.feature_selection import f_classif

X = class_feature_df[feature_cols]
y = class_feature_df["class"]

# ANOVA F-test
f_scores, p_values = f_classif(X, y)

feature_stats = pd.DataFrame({
    "Feature": feature_cols,
    "F_score": f_scores,
    "p_value": p_values
})

feature_stats = feature_stats.sort_values(
    "F_score",
    ascending=False
)

print("=" * 80)
print("TOP FEATURES SEPARATING CLASS 1 / CLASS 2 / CLASS 3")
print("=" * 80)

display(feature_stats.head(30))

ValueError: Input X contains NaN.

In [11]:
# ============================================================
# CHECK NaN VALUES IN CLASS-WISE FEATURE DATA
# ============================================================

import numpy as np
import pandas as pd

feature_cols = [
    c for c in class_feature_df.columns
    if c != "class"
    and pd.api.types.is_numeric_dtype(class_feature_df[c])
]

nan_counts = class_feature_df[feature_cols].isna().sum()

nan_features = nan_counts[nan_counts > 0].sort_values(ascending=False)

print("=" * 70)
print("NaN ANALYSIS")
print("=" * 70)

print("Total numeric features:", len(feature_cols))
print("Features containing NaN:", len(nan_features))
print("Total NaN values:", int(nan_counts.sum()))

print("\nTop features with NaN:")
print(nan_features.head(30))

======================================================================
NaN ANALYSIS
======================================================================
Total numeric features: 184
Features containing NaN: 17
Total NaN values: 16405

Top features with NaN:
in_txs_degree           965
out_txs_degree          965
total_BTC               965
fees                    965
size                    965
num_input_addresses     965
num_output_addresses    965
in_BTC_min              965
in_BTC_max              965
in_BTC_mean             965
in_BTC_median           965
in_BTC_total            965
out_BTC_min             965
out_BTC_max             965
out_BTC_mean            965
out_BTC_median          965
out_BTC_total           965
dtype: int64

In [12]:
# ============================================================
# ANALYZE CLASSES OF ROWS CONTAINING NaN
# ============================================================

nan_mask = class_feature_df[feature_cols].isna().any(axis=1)

nan_rows = class_feature_df.loc[nan_mask]

print("=" * 70)
print("ROWS CONTAINING NaN")
print("=" * 70)

print("Rows containing at least one NaN:", len(nan_rows))

print("\nClass distribution among NaN rows:")
print(
    nan_rows["class"]
    .value_counts()
    .sort_index()
)

print("\nClass percentages among NaN rows:")
print(
    (nan_rows["class"].value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

print("\nOverall class distribution:")
print(
    class_feature_df["class"]
    .value_counts()
    .sort_index()
)

======================================================================
ROWS CONTAINING NaN
======================================================================
Rows containing at least one NaN: 965

Class distribution among NaN rows:
class
2    519
3    446
Name: count, dtype: int64

Class percentages among NaN rows:
class
2    53.78
3    46.22
Name: proportion, dtype: float64

Overall class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

In [13]:
# ============================================================
# CHECK NaN PATTERN
# ============================================================

nan_feature_counts = class_feature_df[feature_cols].isna().sum()

nan_feature_counts = nan_feature_counts[
    nan_feature_counts > 0
].sort_values(ascending=False)

print("=" * 70)
print("NaN PATTERN BY FEATURE")
print("=" * 70)

print(nan_feature_counts)

print("\nUnique NaN counts across affected features:")
print(nan_feature_counts.unique())

print("\nAre all affected features NaN on the same rows?")

affected_features = nan_feature_counts.index.tolist()

nan_pattern = class_feature_df[affected_features].isna()

same_pattern = nan_pattern.eq(
    nan_pattern.iloc[:, 0],
    axis=0
).all().all()

print("Same NaN row pattern:", same_pattern)

======================================================================
NaN PATTERN BY FEATURE
======================================================================
in_txs_degree           965
out_txs_degree          965
total_BTC               965
fees                    965
size                    965
num_input_addresses     965
num_output_addresses    965
in_BTC_min              965
in_BTC_max              965
in_BTC_mean             965
in_BTC_median           965
in_BTC_total            965
out_BTC_min             965
out_BTC_max             965
out_BTC_mean            965
out_BTC_median          965
out_BTC_total           965
dtype: int64

Unique NaN counts across affected features:
[965]

Are all affected features NaN on the same rows?
Same NaN row pattern: True

In [14]:
# ============================================================
# CHECK OTHER FEATURES FOR THE 965 INCOMPLETE TRANSACTIONS
# ============================================================

affected_features = [
    "in_txs_degree",
    "out_txs_degree",
    "total_BTC",
    "fees",
    "size",
    "num_input_addresses",
    "num_output_addresses",
    "in_BTC_min",
    "in_BTC_max",
    "in_BTC_mean",
    "in_BTC_median",
    "in_BTC_total",
    "out_BTC_min",
    "out_BTC_max",
    "out_BTC_mean",
    "out_BTC_median",
    "out_BTC_total"
]

nan_mask = class_feature_df[affected_features].isna().any(axis=1)

other_features = [
    c for c in feature_cols
    if c not in affected_features
]

other_nan_count = (
    class_feature_df.loc[nan_mask, other_features]
    .isna()
    .sum()
)

print("=" * 70)
print("OTHER FEATURES IN THE 965 INCOMPLETE ROWS")
print("=" * 70)

print("Total other numeric features:", len(other_features))
print(
    "Other features containing NaN:",
    int((other_nan_count > 0).sum())
)
print(
    "Total additional NaN values:",
    int(other_nan_count.sum())
)

print("\nFeatures with additional NaN:")
print(
    other_nan_count[other_nan_count > 0]
    .sort_values(ascending=False)
)

======================================================================
OTHER FEATURES IN THE 965 INCOMPLETE ROWS
======================================================================
Total other numeric features: 167
Other features containing NaN: 0
Total additional NaN values: 0

Features with additional NaN:
Series([], dtype: int64)

In [15]:
# ============================================================
# 3-CLASS ANOVA F-TEST — COMPLETE FEATURES ONLY
# ============================================================

from sklearn.feature_selection import f_classif

# Keep only features with NO missing values
complete_feature_cols = [
    c for c in feature_cols
    if class_feature_df[c].isna().sum() == 0
]

X_anova = class_feature_df[complete_feature_cols]
y_anova = class_feature_df["class"]

print("=" * 70)
print("3-CLASS ANOVA F-TEST")
print("=" * 70)

print("Total numeric features:", len(feature_cols))
print("Complete features used:", len(complete_feature_cols))
print("Features excluded because of NaN:",
      len(feature_cols) - len(complete_feature_cols))

# ANOVA
f_scores, p_values = f_classif(X_anova, y_anova)

anova_results = pd.DataFrame({
    "Feature": complete_feature_cols,
    "F_score": f_scores,
    "p_value": p_values
})

# Sort by F-score
anova_results = anova_results.sort_values(
    "F_score",
    ascending=False
).reset_index(drop=True)

print("\nTop 30 features by ANOVA F-score:")
print(anova_results.head(30).to_string(index=False))

======================================================================
3-CLASS ANOVA F-TEST
======================================================================
Total numeric features: 184
Complete features used: 167
Features excluded because of NaN: 17

Top 30 features by ANOVA F-score:
             Feature      F_score  p_value
    Local_feature_53 35273.310684      0.0
    Local_feature_55 22273.678495      0.0
    Local_feature_54 18169.293482      0.0
    Local_feature_52 11726.992583      0.0
    Local_feature_59  9804.607716      0.0
    Local_feature_65  9803.245499      0.0
    Local_feature_60  8511.675168      0.0
    Local_feature_66  8510.515124      0.0
    Local_feature_61  8017.156557      0.0
    Local_feature_67  8016.625909      0.0
    Local_feature_89  7386.477985      0.0
    Local_feature_90  7253.038957      0.0
Aggregate_feature_21  7242.202404      0.0
    Local_feature_25  6852.479762      0.0
    Local_feature_31  6852.213642      0.0
    Local_feature_23  6819.558093      0.0
    Local_feature_29  6818.924157      0.0
    Local_feature_77  6014.010467      0.0
    Local_feature_83  5917.756601      0.0
    Local_feature_91  5484.915818      0.0
    Local_feature_78  5378.690629      0.0
    Local_feature_84  5155.887962      0.0
    Local_feature_85  5144.139028      0.0
    Local_feature_79  4983.147069      0.0
Aggregate_feature_32  4978.634060      0.0
Aggregate_feature_14  4753.484666      0.0
    Local_feature_22  4750.003985      0.0
    Local_feature_28  4749.748008      0.0
    Local_feature_41  4662.543984      0.0
    Local_feature_47  4443.871627      0.0

In [16]:
# ============================================================
# TOP ANOVA FEATURES — CLASS-WISE COMPARISON
# ============================================================

top_features = feature_stats.sort_values(
    "F_score", ascending=False
).head(20)["Feature"].tolist()

comparison = []

for feature in top_features:
    means = class_feature_df.groupby("class")[feature].mean()

    c1 = means.get(1, np.nan)
    c2 = means.get(2, np.nan)
    c3 = means.get(3, np.nan)

    comparison.append({
        "Feature": feature,
        "Class1_Mean": c1,
        "Class2_Mean": c2,
        "Class3_Mean": c3,
        "Abs_Diff_3_vs_1": abs(c3 - c1),
        "Abs_Diff_3_vs_2": abs(c3 - c2)
    })

top_anova_comparison = pd.DataFrame(comparison)

print("=" * 100)
print("TOP ANOVA FEATURES — CLASS-WISE COMPARISON")
print("=" * 100)

display(top_anova_comparison)

NameError: name 'feature_stats' is not defined

In [17]:
# ============================================================
# RECREATE feature_stats FROM ANOVA RESULTS
# ============================================================

feature_stats = pd.DataFrame({
    "Feature": complete_features,
    "F_score": f_scores,
    "p_value": p_values
})

feature_stats = feature_stats.sort_values(
    "F_score",
    ascending=False
).reset_index(drop=True)

print("=" * 70)
print("ANOVA FEATURE STATS RECREATED")
print("=" * 70)

print("Total features:", len(feature_stats))
print("\nTop 20 features:")
display(feature_stats.head(20))

NameError: name 'complete_features' is not defined

In [18]:
# ============================================================
# RECREATE 3-CLASS ANOVA RESULTS
# ============================================================

import numpy as np
import pandas as pd
from sklearn.feature_selection import f_classif

# Numeric feature columns — class ko exclude karo
feature_cols = [
    c for c in class_feature_df.columns
    if c != "class"
    and pd.api.types.is_numeric_dtype(class_feature_df[c])
]

# Sirf features jisme koi NaN nahi hai
complete_features = [
    c for c in feature_cols
    if class_feature_df[c].notna().all()
]

print("=" * 70)
print("ANOVA INPUT")
print("=" * 70)

print("Total numeric features:", len(feature_cols))
print("Complete features:", len(complete_features))
print("Excluded due to NaN:", len(feature_cols) - len(complete_features))

# X and y
X = class_feature_df[complete_features]
y = class_feature_df["class"]

# ANOVA
f_scores, p_values = f_classif(X, y)

# Results DataFrame
feature_stats = pd.DataFrame({
    "Feature": complete_features,
    "F_score": f_scores,
    "p_value": p_values
})

feature_stats = feature_stats.sort_values(
    "F_score",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 70)
print("TOP 20 ANOVA FEATURES")
print("=" * 70)

display(feature_stats.head(20))

======================================================================
ANOVA INPUT
======================================================================
Total numeric features: 184
Complete features: 167
Excluded due to NaN: 17

======================================================================
TOP 20 ANOVA FEATURES
======================================================================

                 Feature       F_score  p_value
0       Local_feature_53  35273.310684      0.0
1       Local_feature_55  22273.678495      0.0
2       Local_feature_54  18169.293482      0.0
3       Local_feature_52  11726.992583      0.0
4       Local_feature_59   9804.607716      0.0
5       Local_feature_65   9803.245499      0.0
6       Local_feature_60   8511.675168      0.0
7       Local_feature_66   8510.515124      0.0
8       Local_feature_61   8017.156557      0.0
9       Local_feature_67   8016.625909      0.0
10      Local_feature_89   7386.477985      0.0
11      Local_feature_90   7253.038957      0.0
12  Aggregate_feature_21   7242.202404      0.0
13      Local_feature_25   6852.479762      0.0
14      Local_feature_31   6852.213642      0.0
15      Local_feature_23   6819.558093      0.0
16      Local_feature_29   6818.924157      0.0
17      Local_feature_77   6014.010467      0.0
18      Local_feature_83   5917.756601      0.0
19      Local_feature_91   5484.915818      0.0

In [19]:
# ============================================================
# TOP ANOVA FEATURES — CLASS-WISE COMPARISON
# ============================================================

top_features = feature_stats.head(20)["Feature"].tolist()

class_comparison = (
    class_feature_df
    .groupby("class")[top_features]
    .mean()
    .T
    .reset_index()
    .rename(columns={"index": "Feature"})
)

# Rename class columns
class_comparison = class_comparison.rename(columns={
    1: "Class1_Mean",
    2: "Class2_Mean",
    3: "Class3_Mean"
})

# Difference of Class 3 from other classes
class_comparison["Abs_Diff_Class3_vs_Class1"] = (
    class_comparison["Class3_Mean"] -
    class_comparison["Class1_Mean"]
).abs()

class_comparison["Abs_Diff_Class3_vs_Class2"] = (
    class_comparison["Class3_Mean"] -
    class_comparison["Class2_Mean"]
).abs()

# Overall Class 3 distinctiveness
class_comparison["Class3_Distinctiveness"] = (
    class_comparison["Abs_Diff_Class3_vs_Class1"] +
    class_comparison["Abs_Diff_Class3_vs_Class2"]
) / 2

class_comparison = class_comparison.sort_values(
    "Class3_Distinctiveness",
    ascending=False
)

print("=" * 90)
print("TOP ANOVA FEATURES — CLASS-WISE COMPARISON")
print("=" * 90)

display(class_comparison)

==========================================================================================
TOP ANOVA FEATURES — CLASS-WISE COMPARISON
==========================================================================================

class,Feature,Class1_Mean,Class2_Mean,Class3_Mean,Abs_Diff_Class3_vs_Class1,Abs_Diff_Class3_vs_Class2,Class3_Distinctiveness
0,Local_feature_53,-0.267997,0.994976,-0.258197,0.009800,1.253173,0.631486
1,Local_feature_55,-0.251836,0.830949,-0.214822,0.037014,1.045770,0.541392
2,Local_feature_54,-0.139124,0.763076,-0.199939,0.060815,0.963015,0.511915
11,Local_feature_90,-0.532172,0.491296,-0.115932,0.416241,0.607227,0.511734
10,Local_feature_89,-0.502142,0.497936,-0.118575,0.383567,0.616511,0.500039
3,Local_feature_52,-0.223545,0.630103,-0.161956,0.061589,0.792058,0.426824
19,Local_feature_91,-0.377069,0.436472,-0.105762,0.271307,0.542234,0.406771
4,Local_feature_59,-0.172084,0.581282,-0.150394,0.021690,0.731676,0.376683
5,Local_feature_65,-0.172074,0.581245,-0.150385,0.021690,0.731630,0.376660
6,Local_feature_60,-0.162377,0.544759,-0.140913,0.021464,0.685672,0.353568
7,Local_feature_66,-0.162366,0.544725,-0.140904,0.021462,0.685629,0.353546
8,Local_feature_61,-0.160017,0.529878,-0.137004,0.023013,0.666882,0.344948
9,Local_feature_67,-0.160012,0.529862,-0.137000,0.023012,0.666862,0.344937
12,Aggregate_feature_21,-0.157897,0.505381,-0.130517,0.027380,0.635898,0.331639
13,Local_feature_25,-0.154666,0.492471,-0.127160,0.027506,0.619631,0.323569
14,Local_feature_31,-0.154666,0.492462,-0.127158,0.027509,0.619620,0.323564
15,Local_feature_23,-0.148149,0.491388,-0.127059,0.021090,0.618446,0.319768
16,Local_feature_29,-0.148144,0.491366,-0.127053,0.021091,0.618419,0.319755
17,Local_feature_77,-0.173622,0.462937,-0.118718,0.054904,0.581655,0.318280
18,Local_feature_83,-0.160779,0.459527,-0.118178,0.042601,0.577705,0.310153

In [20]:
# ============================================================
# TOP ANOVA FEATURES — CORRELATION / REDUNDANCY ANALYSIS
# ============================================================

top_features = feature_stats.head(30)["Feature"].tolist()

corr_matrix = class_feature_df[top_features].corr()

# Find highly correlated feature pairs
high_corr_pairs = []

for i in range(len(top_features)):
    for j in range(i + 1, len(top_features)):
        
        f1 = top_features[i]
        f2 = top_features[j]
        corr = corr_matrix.loc[f1, f2]
        
        if abs(corr) >= 0.90:
            high_corr_pairs.append({
                "Feature_1": f1,
                "Feature_2": f2,
                "Correlation": corr,
                "Abs_Correlation": abs(corr)
            })

high_corr_df = pd.DataFrame(high_corr_pairs)

if len(high_corr_df) > 0:
    high_corr_df = high_corr_df.sort_values(
        "Abs_Correlation",
        ascending=False
    ).reset_index(drop=True)

print("=" * 90)
print("HIGH-CORRELATION FEATURE PAIRS")
print("=" * 90)

print("Top ANOVA features analysed:", len(top_features))
print("Highly correlated pairs (|r| >= 0.90):", len(high_corr_df))

display(high_corr_df)

==========================================================================================
HIGH-CORRELATION FEATURE PAIRS
==========================================================================================
Top ANOVA features analysed: 30
Highly correlated pairs (|r| >= 0.90): 50

           Feature_1         Feature_2  Correlation  Abs_Correlation
0   Local_feature_23  Local_feature_29     1.000000         1.000000
1   Local_feature_25  Local_feature_31     1.000000         1.000000
2   Local_feature_22  Local_feature_28     1.000000         1.000000
3   Local_feature_59  Local_feature_65     1.000000         1.000000
4   Local_feature_61  Local_feature_67     1.000000         1.000000
5   Local_feature_60  Local_feature_66     1.000000         1.000000
6   Local_feature_83  Local_feature_84     0.989255         0.989255
7   Local_feature_77  Local_feature_78     0.986728         0.986728
8   Local_feature_84  Local_feature_85     0.984696         0.984696
9   Local_feature_83  Local_feature_85     0.981974         0.981974
10  Local_feature_77  Local_feature_79     0.979918         0.979918
11  Local_feature_41  Local_feature_47     0.978398         0.978398
12  Local_feature_78  Local_feature_79     0.973429         0.973429
13  Local_feature_65  Local_feature_60     0.965202         0.965202
14  Local_feature_65  Local_feature_66     0.965192         0.965192
15  Local_feature_59  Local_feature_60     0.965160         0.965160
16  Local_feature_59  Local_feature_66     0.965150         0.965150
17  Local_feature_78  Local_feature_84     0.954755         0.954755
18  Local_feature_55  Local_feature_52     0.954035         0.954035
19  Local_feature_77  Local_feature_83     0.951821         0.951821
20  Local_feature_65  Local_feature_61     0.949887         0.949887
21  Local_feature_65  Local_feature_67     0.949885         0.949885
22  Local_feature_59  Local_feature_61     0.949834         0.949834
23  Local_feature_59  Local_feature_67     0.949831         0.949831
24  Local_feature_66  Local_feature_67     0.945472         0.945472
25  Local_feature_66  Local_feature_61     0.945467         0.945467
26  Local_feature_60  Local_feature_67     0.945460         0.945460
27  Local_feature_60  Local_feature_61     0.945455         0.945455
28  Local_feature_83  Local_feature_78     0.944419         0.944419
29  Local_feature_31  Local_feature_23     0.943094         0.943094
30  Local_feature_31  Local_feature_29     0.943079         0.943079
31  Local_feature_25  Local_feature_23     0.943075         0.943075
32  Local_feature_25  Local_feature_29     0.943059         0.943059
33  Local_feature_77  Local_feature_84     0.941695         0.941695
34  Local_feature_83  Local_feature_47     0.941324         0.941324
35  Local_feature_85  Local_feature_79     0.941003         0.941003
36  Local_feature_84  Local_feature_47     0.940866         0.940866
37  Local_feature_53  Local_feature_55     0.940648         0.940648
38  Local_feature_78  Local_feature_85     0.939797         0.939797
39  Local_feature_77  Local_feature_85     0.934303         0.934303
40  Local_feature_84  Local_feature_79     0.927344         0.927344
41  Local_feature_83  Local_feature_79     0.924527         0.924527
42  Local_feature_83  Local_feature_41     0.922868         0.922868
43  Local_feature_84  Local_feature_41     0.921674         0.921674
44  Local_feature_85  Local_feature_47     0.921080         0.921080
45  Local_feature_78  Local_feature_41     0.902539         0.902539
46  Local_feature_85  Local_feature_41     0.902519         0.902519
47  Local_feature_89  Local_feature_91     0.902336         0.902336
48  Local_feature_77  Local_feature_41     0.900910         0.900910
49  Local_feature_78  Local_feature_47     0.900240         0.900240

In [21]:
# ============================================================
# CLASS 3 vs OTHER CLASSES — FEATURE IMPORTANCE
# ============================================================

from sklearn.feature_selection import f_classif

# Binary target:
# Class 3 = 1
# Class 1 & 2 = 0

y_class3 = (class_feature_df["class"] == 3).astype(int)

# Use the 167 complete features
X_class3 = class_feature_df[complete_features]

# ANOVA: Class 3 vs non-Class-3
f_class3, p_class3 = f_classif(X_class3, y_class3)

class3_feature_stats = pd.DataFrame({
    "Feature": complete_features,
    "F_score": f_class3,
    "p_value": p_class3
})

class3_feature_stats = class3_feature_stats.sort_values(
    "F_score",
    ascending=False
).reset_index(drop=True)

print("=" * 90)
print("CLASS 3 vs NON-CLASS-3 FEATURE ANALYSIS")
print("=" * 90)

print("Class 3 samples:", int(y_class3.sum()))
print("Non-Class-3 samples:", int((y_class3 == 0).sum()))
print("Features analysed:", len(complete_features))

print("\nTop 30 features for Class 3 separation:")
display(class3_feature_stats.head(30))

==========================================================================================
CLASS 3 vs NON-CLASS-3 FEATURE ANALYSIS
==========================================================================================
Class 3 samples: 157205
Non-Class-3 samples: 46564
Features analysed: 167

Top 30 features for Class 3 separation:

                 Feature       F_score  p_value
0       Local_feature_53  59182.082336      0.0
1       Local_feature_55  37606.398098      0.0
2       Local_feature_54  31791.352858      0.0
3       Local_feature_52  19797.593669      0.0
4       Local_feature_59  16846.578651      0.0
5       Local_feature_65  16844.260708      0.0
6       Local_feature_60  14641.586071      0.0
7       Local_feature_66  14639.618917      0.0
8       Local_feature_61  13786.271882      0.0
9       Local_feature_67  13785.368582      0.0
10  Aggregate_feature_21  12433.959887      0.0
11      Local_feature_25  11766.069241      0.0
12      Local_feature_31  11765.600533      0.0
13      Local_feature_23  11746.254600      0.0
14      Local_feature_29  11745.162222      0.0
15      Local_feature_77  10180.159645      0.0
16      Local_feature_89  10154.424617      0.0
17      Local_feature_83  10083.171831      0.0
18      Local_feature_90   9685.477443      0.0
19      Local_feature_78   9145.348707      0.0
20      Local_feature_84   8791.625343      0.0
21      Local_feature_85   8748.930499      0.0
22  Aggregate_feature_32   8576.551338      0.0
23      Local_feature_79   8385.857555      0.0
24  Aggregate_feature_14   8173.821037      0.0
25      Local_feature_22   8137.130266      0.0
26      Local_feature_28   8136.669280      0.0
27      Local_feature_91   7997.019655      0.0
28      Local_feature_41   7966.968557      0.0
29      Local_feature_47   7596.001979      0.0

In [22]:
# ============================================================
# CLASS 3 — REDUNDANCY-AWARE FEATURE SELECTION
# ============================================================

# Top 30 Class-3 separation features
top_class3_features = class3_feature_stats.sort_values(
    "F_score",
    ascending=False
).head(30)["Feature"].tolist()

print("=" * 80)
print("TOP CLASS-3 FEATURES")
print("=" * 80)

for i, feature in enumerate(top_class3_features, 1):
    print(f"{i:2}. {feature}")

# Correlation matrix
corr_matrix = class_feature_df[top_class3_features].corr()

# Find highly correlated pairs
high_corr_pairs = []

for i in range(len(top_class3_features)):
    for j in range(i + 1, len(top_class3_features)):
        f1 = top_class3_features[i]
        f2 = top_class3_features[j]
        corr = corr_matrix.loc[f1, f2]

        if abs(corr) >= 0.90:
            high_corr_pairs.append({
                "Feature_1": f1,
                "Feature_2": f2,
                "Correlation": corr,
                "Abs_Correlation": abs(corr)
            })

high_corr_df = pd.DataFrame(high_corr_pairs)

print("\n" + "=" * 80)
print("HIGHLY CORRELATED TOP CLASS-3 FEATURES")
print("=" * 80)

print("Number of correlated pairs:", len(high_corr_df))

if len(high_corr_df) > 0:
    display(
        high_corr_df.sort_values(
            "Abs_Correlation",
            ascending=False
        )
    )
else:
    print("No correlation >= 0.90 found.")

================================================================================
TOP CLASS-3 FEATURES
================================================================================
 1. Local_feature_53
 2. Local_feature_55
 3. Local_feature_54
 4. Local_feature_52
 5. Local_feature_59
 6. Local_feature_65
 7. Local_feature_60
 8. Local_feature_66
 9. Local_feature_61
10. Local_feature_67
11. Aggregate_feature_21
12. Local_feature_25
13. Local_feature_31
14. Local_feature_23
15. Local_feature_29
16. Local_feature_77
17. Local_feature_89
18. Local_feature_83
19. Local_feature_90
20. Local_feature_78
21. Local_feature_84
22. Local_feature_85
23. Aggregate_feature_32
24. Local_feature_79
25. Aggregate_feature_14
26. Local_feature_22
27. Local_feature_28
28. Local_feature_91
29. Local_feature_41
30. Local_feature_47

================================================================================
HIGHLY CORRELATED TOP CLASS-3 FEATURES
================================================================================
Number of correlated pairs: 50

           Feature_1         Feature_2  Correlation  Abs_Correlation
22  Local_feature_23  Local_feature_29     1.000000         1.000000
17  Local_feature_25  Local_feature_31     1.000000         1.000000
48  Local_feature_22  Local_feature_28     1.000000         1.000000
2   Local_feature_59  Local_feature_65     1.000000         1.000000
16  Local_feature_61  Local_feature_67     1.000000         1.000000
11  Local_feature_60  Local_feature_66     1.000000         1.000000
31  Local_feature_83  Local_feature_84     0.989255         0.989255
24  Local_feature_77  Local_feature_78     0.986728         0.986728
41  Local_feature_84  Local_feature_85     0.984696         0.984696
32  Local_feature_83  Local_feature_85     0.981974         0.981974
27  Local_feature_77  Local_feature_79     0.979918         0.979918
49  Local_feature_41  Local_feature_47     0.978398         0.978398
38  Local_feature_78  Local_feature_79     0.973429         0.973429
7   Local_feature_65  Local_feature_60     0.965202         0.965202
8   Local_feature_65  Local_feature_66     0.965192         0.965192
3   Local_feature_59  Local_feature_60     0.965160         0.965160
4   Local_feature_59  Local_feature_66     0.965150         0.965150
36  Local_feature_78  Local_feature_84     0.954755         0.954755
1   Local_feature_55  Local_feature_52     0.954035         0.954035
23  Local_feature_77  Local_feature_83     0.951821         0.951821
9   Local_feature_65  Local_feature_61     0.949887         0.949887
10  Local_feature_65  Local_feature_67     0.949885         0.949885
5   Local_feature_59  Local_feature_61     0.949834         0.949834
6   Local_feature_59  Local_feature_67     0.949831         0.949831
15  Local_feature_66  Local_feature_67     0.945472         0.945472
14  Local_feature_66  Local_feature_61     0.945467         0.945467
13  Local_feature_60  Local_feature_67     0.945460         0.945460
12  Local_feature_60  Local_feature_61     0.945455         0.945455
30  Local_feature_83  Local_feature_78     0.944419         0.944419
20  Local_feature_31  Local_feature_23     0.943094         0.943094
21  Local_feature_31  Local_feature_29     0.943079         0.943079
18  Local_feature_25  Local_feature_23     0.943075         0.943075
19  Local_feature_25  Local_feature_29     0.943059         0.943059
25  Local_feature_77  Local_feature_84     0.941695         0.941695
35  Local_feature_83  Local_feature_47     0.941324         0.941324
45  Local_feature_85  Local_feature_79     0.941003         0.941003
44  Local_feature_84  Local_feature_47     0.940866         0.940866
0   Local_feature_53  Local_feature_55     0.940648         0.940648
37  Local_feature_78  Local_feature_85     0.939797         0.939797
26  Local_feature_77  Local_feature_85     0.934303         0.934303
42  Local_feature_84  Local_feature_79     0.927344         0.927344
33  Local_feature_83  Local_feature_79     0.924527         0.924527
34  Local_feature_83  Local_feature_41     0.922868         0.922868
43  Local_feature_84  Local_feature_41     0.921674         0.921674
47  Local_feature_85  Local_feature_47     0.921080         0.921080
39  Local_feature_78  Local_feature_41     0.902539         0.902539
46  Local_feature_85  Local_feature_41     0.902519         0.902519
29  Local_feature_89  Local_feature_91     0.902336         0.902336
28  Local_feature_77  Local_feature_41     0.900910         0.900910
40  Local_feature_78  Local_feature_47     0.900240         0.900240

In [23]:
# ============================================================
# CLASS 3 — REDUNDANCY-AWARE REPRESENTATIVE FEATURES
# ============================================================

# Top Class-3 features
top_class3_features = class3_feature_stats.sort_values(
    "F_score",
    ascending=False
).head(30)["Feature"].tolist()

# Correlation threshold
CORR_THRESHOLD = 0.90

selected_features = []
removed_features = []
feature_groups = []

for feature in top_class3_features:

    highly_correlated_with_selected = []

    for selected in selected_features:
        corr = corr_matrix.loc[feature, selected]

        if abs(corr) >= CORR_THRESHOLD:
            highly_correlated_with_selected.append(
                (selected, corr)
            )

    if not highly_correlated_with_selected:
        selected_features.append(feature)

    else:
        removed_features.append(feature)

        feature_groups.append({
            "Removed_feature": feature,
            "Correlated_with": highly_correlated_with_selected
        })

print("=" * 80)
print("REDUNDANCY-AWARE FEATURE SELECTION")
print("=" * 80)

print("\nOriginal top features:", len(top_class3_features))
print("Selected representative features:", len(selected_features))
print("Removed redundant features:", len(removed_features))

print("\n" + "=" * 80)
print("SELECTED FEATURES")
print("=" * 80)

for i, feature in enumerate(selected_features, 1):
    print(f"{i:2}. {feature}")

print("\n" + "=" * 80)
print("REMOVED REDUNDANT FEATURES")
print("=" * 80)

for feature in removed_features:
    print("-", feature)

================================================================================
REDUNDANCY-AWARE FEATURE SELECTION
================================================================================

Original top features: 30
Selected representative features: 13
Removed redundant features: 17

================================================================================
SELECTED FEATURES
================================================================================
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47

================================================================================
REMOVED REDUNDANT FEATURES
================================================================================
- Local_feature_55
- Local_feature_65
- Local_feature_60
- Local_feature_66
- Local_feature_61
- Local_feature_67
- Local_feature_31
- Local_feature_23
- Local_feature_29
- Local_feature_83
- Local_feature_78
- Local_feature_84
- Local_feature_85
- Local_feature_79
- Local_feature_28
- Local_feature_91
- Local_feature_41

In [24]:
# ============================================================
# CLASS 3 — SELECTED FEATURE SET SUMMARY
# ============================================================

print("=" * 80)
print("FINAL CANDIDATE FEATURE SET — CLASS 3")
print("=" * 80)

print("Number of candidate features:", len(selected_features))

print("\nSelected features:")
for i, feature in enumerate(selected_features, 1):
    print(f"{i:2}. {feature}")

# Create reduced dataset
X_class3_selected = class_feature_df[selected_features].copy()
y_class3 = (class_feature_df["class"] == 3).astype(int)

print("\n" + "=" * 80)
print("REDUCED DATASET")
print("=" * 80)

print("X shape:", X_class3_selected.shape)
print("y shape:", y_class3.shape)

print("\nTarget distribution:")
print(y_class3.value_counts())

print("\nTarget percentages:")
print(
    y_class3.value_counts(normalize=True)
    .mul(100)
    .round(2)
)

================================================================================
FINAL CANDIDATE FEATURE SET — CLASS 3
================================================================================
Number of candidate features: 13

Selected features:
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47

================================================================================
REDUCED DATASET
================================================================================
X shape: (203769, 13)
y shape: (203769,)

Target distribution:
class
1    157205
0     46564
Name: count, dtype: int64

Target percentages:
class
1    77.15
0    22.85
Name: proportion, dtype: float64

In [25]:
# ============================================================
# CLASS 3 vs NON-CLASS-3
# TEMPORAL MODEL INPUT PREPARATION
# ============================================================

# Selected features
X = class_feature_df[selected_features].copy()

# Class 3 = 1, everything else = 0
y = (class_feature_df["class"] == 3).astype(int)

# Get corresponding time-step
time_series = class_feature_df["Time step"].copy()

print("=" * 80)
print("CLASS 3 TEMPORAL MODEL INPUT")
print("=" * 80)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Time-step shape:", time_series.shape)

print("\nTime-step range:")
print("Minimum:", time_series.min())
print("Maximum:", time_series.max())

print("\nClass distribution:")
print(y.value_counts())

print("\nClass percentage:")
print(
    y.value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nSelected features:")
for i, feature in enumerate(selected_features, 1):
    print(f"{i:2}. {feature}")

================================================================================
CLASS 3 TEMPORAL MODEL INPUT
================================================================================
X shape: (203769, 13)
y shape: (203769,)
Time-step shape: (203769,)

Time-step range:
Minimum: 1
Maximum: 49

Class distribution:
class
1    157205
0     46564
Name: count, dtype: int64

Class percentage:
class
1    77.15
0    22.85
Name: proportion, dtype: float64

Selected features:
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47

In [26]:
# ============================================================
# TEMPORAL SPLIT — CLASS 3 DETECTION
# ============================================================

temporal_check = pd.DataFrame({
    "Time_step": time_series.to_numpy(),
    "Class3": y.to_numpy()
})

time_distribution = (
    temporal_check
    .groupby("Time_step")
    .agg(
        Total=("Class3", "size"),
        Class3=("Class3", "sum")
    )
)

time_distribution["Non_Class3"] = (
    time_distribution["Total"] - time_distribution["Class3"]
)

time_distribution["Class3_%"] = (
    time_distribution["Class3"] /
    time_distribution["Total"] * 100
).round(2)

print("=" * 90)
print("CLASS 3 TEMPORAL DISTRIBUTION")
print("=" * 90)

display(time_distribution)

print("\nTime steps:", time_distribution.index.min(), "to", time_distribution.index.max())
print("Total transactions:", time_distribution["Total"].sum())
print("Total Class 3:", time_distribution["Class3"].sum())

==========================================================================================
CLASS 3 TEMPORAL DISTRIBUTION
==========================================================================================

           Total  Class3  Non_Class3  Class3_%
Time_step
1           7880    5733        2147     72.75
2           4544    3427        1117     75.42
3           6621    5342        1279     80.68
4           5693    4253        1440     74.71
5           6803    4921        1882     72.34
6           4328    3843         485     88.79
7           6048    4845        1203     80.11
8           4457    3292        1165     73.86
9           4996    4218         778     84.43
10          6727    5755         972     85.55
11          4296    3600         696     83.80
12          2047    1541         506     75.28
13          4528    3719         809     82.13
14          2022    1605         417     79.38
15          3639    3021         618     83.02
16          2975    2445         530     82.18
17          3385    2574         811     76.04
18          1976    1587         389     80.31
19          3506    2761         745     78.75
20          4291    3391         900     79.03
21          3537    2896         641     81.88
22          5894    4131        1763     70.09
23          4165    2978        1187     71.50
24          4592    3466        1126     75.48
25          2314    1720         594     74.33
26          2523    2006         517     79.51
27          1089     883         206     81.08
28          1653    1369         284     82.82
29          4275    3101        1174     72.54
30          2483    1959         524     78.90
31          2816    2106         710     74.79
32          4525    3202        1323     70.76
33          3151    2710         441     86.00
34          2486    1971         515     79.28
35          5507    4166        1341     75.65
36          6393    4685        1708     73.28
37          3306    2808         498     84.94
38          2891    2135         756     73.85
39          2760    1577        1183     57.14
40          4481    3270        1211     72.97
41          5342    4210        1132     78.81
42          7140    4986        2154     69.83
43          5063    3693        1370     72.94
44          4975    3384        1591     68.02
45          5598    4377        1221     78.19
46          3519    2807         712     79.77
47          5121    4275         846     83.48
48          2954    2483         471     84.06
49          2454    1978         476     80.60

Time steps: 1 to 49
Total transactions: 203769
Total Class 3: 157205

In [27]:
# ============================================================
# BIT-TRACE / ELLIPTIC++ TRANSACTIONS
# CLASS-3 / UNKNOWN TRANSACTION ANOMALY PIPELINE
# ============================================================
#
# PURPOSE:
#   1. Load selected transaction features
#   2. Validate data quality
#   3. Prepare temporal data
#   4. Train UNSUPERVISED Isolation Forest
#   5. Generate anomaly scores
#   6. Analyse thresholds
#   7. Validate anomalies against Class 1/2/3 labels
#   8. Analyse anomaly behaviour by time step
#   9. Perform feature-level anomaly analysis
#  10. Save results for BIT-TRACE
#
# IMPORTANT:
#   Class labels are NOT used for model training.
#   They are used ONLY AFTER prediction for evaluation/analysis.
# ============================================================

import os
import gc
import warnings
import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.impute import SimpleImputer

warnings.filterwarnings("ignore")

print("=" * 80)
print("BIT-TRACE — ELLIPTIC++ UNSUPERVISED ANOMALY PIPELINE")
print("=" * 80)


# ============================================================
# 1. PATHS
# ============================================================

BASE_DIR = r"C:\Users\YASHIKA\Desktop\bit-trace"

TX_DIR = os.path.join(
    BASE_DIR,
    "EllipticPlusPlus",
    "Transactions Dataset"
)

FEATURE_FILE = os.path.join(TX_DIR, "txs_features.csv")
CLASS_FILE = os.path.join(TX_DIR, "txs_classes.csv")

print("\n[1] PATH CHECK")
print("-" * 80)

print("Feature file exists:", os.path.exists(FEATURE_FILE))
print("Class file exists:", os.path.exists(CLASS_FILE))

if not os.path.exists(FEATURE_FILE):
    raise FileNotFoundError(FEATURE_FILE)

if not os.path.exists(CLASS_FILE):
    raise FileNotFoundError(CLASS_FILE)


# ============================================================
# 2. SELECTED FEATURES
# ============================================================
#
# These are the 13 features obtained from your previous
# Class-3 redundancy-aware feature selection.
# ============================================================

SELECTED_FEATURES = [
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_52",
    "Local_feature_59",
    "Aggregate_feature_21",
    "Local_feature_25",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_32",
    "Aggregate_feature_14",
    "Local_feature_22",
    "Local_feature_47"
]

print("\n[2] SELECTED FEATURES")
print("-" * 80)

for i, feature in enumerate(SELECTED_FEATURES, 1):
    print(f"{i:2d}. {feature}")

print("\nNumber of selected features:", len(SELECTED_FEATURES))


# ============================================================
# 3. LOAD CLASS DATA
# ============================================================

print("\n[3] LOADING CLASS DATA")
print("-" * 80)

classes = pd.read_csv(CLASS_FILE)

print("Class data shape:", classes.shape)
print("Columns:", classes.columns.tolist())

required_class_cols = {"txId", "class"}

if not required_class_cols.issubset(classes.columns):
    raise ValueError(
        f"Expected columns {required_class_cols}, "
        f"found {set(classes.columns)}"
    )

classes["txId"] = pd.to_numeric(classes["txId"], errors="coerce")
classes["class"] = pd.to_numeric(classes["class"], errors="coerce")

print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())


# ============================================================
# 4. LOAD ONLY NECESSARY COLUMNS FROM HUGE FEATURES FILE
# ============================================================
#
# IMPORTANT:
# We do NOT load all 185 columns.
# This saves memory and time.
#
# We first inspect the header to find the time-step column
# and transaction ID column.
# ============================================================

print("\n[4] READING FEATURE HEADER")
print("-" * 80)

header = pd.read_csv(
    FEATURE_FILE,
    nrows=0
)

all_columns = header.columns.tolist()

print("Total columns in feature file:", len(all_columns))

print("\nFirst columns:")
print(all_columns[:20])


# ------------------------------------------------------------
# Identify ID and time columns robustly
# ------------------------------------------------------------

def find_column(columns, candidates):
    lower_map = {c.lower(): c for c in columns}

    for candidate in candidates:
        if candidate.lower() in lower_map:
            return lower_map[candidate.lower()]

    return None


TX_ID_COL = find_column(
    all_columns,
    ["txId", "txID", "tx_id", "transaction_id"]
)

TIME_COL = find_column(
    all_columns,
    ["time_step", "Time_step", "time step", "time"]
)

print("\nDetected transaction ID column:", TX_ID_COL)
print("Detected time column:", TIME_COL)

if TX_ID_COL is None:
    raise ValueError(
        "Could not automatically identify transaction ID column."
    )

if TIME_COL is None:
    raise ValueError(
        "Could not automatically identify time-step column."
    )


# ------------------------------------------------------------
# Check selected features exist
# ------------------------------------------------------------

missing_features = [
    f for f in SELECTED_FEATURES
    if f not in all_columns
]

if missing_features:
    raise ValueError(
        "These selected features were not found:\n"
        + "\n".join(missing_features)
    )


# ============================================================
# 5. LOAD ONLY REQUIRED DATA
# ============================================================

needed_columns = [
    TX_ID_COL,
    TIME_COL
] + SELECTED_FEATURES

# remove duplicates while preserving order
needed_columns = list(dict.fromkeys(needed_columns))

print("\n[5] LOADING REQUIRED FEATURE COLUMNS")
print("-" * 80)

print("Columns being loaded:", len(needed_columns))

feature_data = pd.read_csv(
    FEATURE_FILE,
    usecols=needed_columns,
    low_memory=False
)

print("\nLoaded shape:", feature_data.shape)


# ============================================================
# 6. BASIC CLEANING
# ============================================================

print("\n[6] BASIC DATA CLEANING")
print("-" * 80)

feature_data[TX_ID_COL] = pd.to_numeric(
    feature_data[TX_ID_COL],
    errors="coerce"
)

feature_data[TIME_COL] = pd.to_numeric(
    feature_data[TIME_COL],
    errors="coerce"
)

for feature in SELECTED_FEATURES:
    feature_data[feature] = pd.to_numeric(
        feature_data[feature],
        errors="coerce"
    )

print("Missing txId:", feature_data[TX_ID_COL].isna().sum())
print("Missing time step:", feature_data[TIME_COL].isna().sum())


# ============================================================
# 7. MERGE WITH CLASS LABELS
# ============================================================

print("\n[7] MERGING FEATURES + LABELS")
print("-" * 80)

data = feature_data.merge(
    classes[["txId", "class"]],
    left_on=TX_ID_COL,
    right_on="txId",
    how="left"
)

# remove duplicate txId column if needed
if "txId" in data.columns and TX_ID_COL != "txId":
    data.drop(columns=["txId"], inplace=True)

print("Merged shape:", data.shape)

print("\nMissing labels:")
print(data["class"].isna().sum())

print("\nClass distribution after merge:")
print(data["class"].value_counts(dropna=False).sort_index())


# ============================================================
# 8. VALIDATE TIME STEP
# ============================================================

print("\n[8] TEMPORAL VALIDATION")
print("-" * 80)

print("Minimum time step:", data[TIME_COL].min())
print("Maximum time step:", data[TIME_COL].max())
print("Number of unique time steps:", data[TIME_COL].nunique())

print("\nTransactions per time step:")
print(
    data[TIME_COL]
    .value_counts()
    .sort_index()
    .to_string()
)


# ============================================================
# 9. DATA QUALITY CHECK
# ============================================================

print("\n[9] DATA QUALITY CHECK")
print("-" * 80)

X_raw = data[SELECTED_FEATURES].copy()

nan_counts = X_raw.isna().sum()
inf_counts = np.isinf(X_raw.to_numpy(dtype=float)).sum(axis=0)

quality_table = pd.DataFrame({
    "NaN_count": nan_counts,
    "Inf_count": inf_counts
})

print(quality_table[quality_table.sum(axis=1) > 0])

print(
    "\nTotal NaN values:",
    int(X_raw.isna().sum().sum())
)

print(
    "Total Inf values:",
    int(np.isinf(X_raw.to_numpy(dtype=float)).sum())
)


# ============================================================
# 10. REPLACE INF WITH NaN
# ============================================================

X_raw = X_raw.replace(
    [np.inf, -np.inf],
    np.nan
)


# ============================================================
# 11. IMPUTATION
# ============================================================
#
# We use median imputation.
#
# IMPORTANT:
# This is preprocessing only.
# Class labels are NOT used.
# ============================================================

print("\n[10] MEDIAN IMPUTATION")
print("-" * 80)

imputer = SimpleImputer(strategy="median")

X = imputer.fit_transform(X_raw)

X = pd.DataFrame(
    X,
    columns=SELECTED_FEATURES,
    index=data.index
)

print("Final X shape:", X.shape)
print("Remaining NaN:", int(X.isna().sum().sum()))


# ============================================================
# 12. FEATURE SUMMARY
# ============================================================

print("\n[11] FEATURE SUMMARY")
print("-" * 80)

summary = pd.DataFrame({
    "mean": X.mean(),
    "std": X.std(),
    "min": X.min(),
    "median": X.median(),
    "max": X.max()
})

print(summary.to_string())


# ============================================================
# 13. TEMPORAL TRAIN / VALIDATION / TEST SPLIT
# ============================================================
#
# We use chronological splitting.
#
# 70% earliest time steps -> TRAIN
# next 15%                 -> VALIDATION
# final 15%                -> TEST
#
# The exact boundaries are derived automatically from the
# 49 available time steps.
# ============================================================

print("\n[12] TEMPORAL SPLIT")
print("-" * 80)

unique_times = np.sort(
    data[TIME_COL].dropna().unique()
)

n_times = len(unique_times)

train_end_idx = int(n_times * 0.70)
val_end_idx = int(n_times * 0.85)

# ensure non-empty ranges
train_end_idx = max(1, train_end_idx)
val_end_idx = max(train_end_idx + 1, val_end_idx)
val_end_idx = min(val_end_idx, n_times - 1)

train_times = unique_times[:train_end_idx]
val_times = unique_times[train_end_idx:val_end_idx]
test_times = unique_times[val_end_idx:]

print("Train time steps:",
      train_times[0], "to", train_times[-1])

print("Validation time steps:",
      val_times[0], "to", val_times[-1])

print("Test time steps:",
      test_times[0], "to", test_times[-1])


train_mask = data[TIME_COL].isin(train_times)
val_mask = data[TIME_COL].isin(val_times)
test_mask = data[TIME_COL].isin(test_times)

X_train = X.loc[train_mask]
X_val = X.loc[val_mask]
X_test = X.loc[test_mask]

print("\nTrain samples:", len(X_train))
print("Validation samples:", len(X_val))
print("Test samples:", len(X_test))


# ============================================================
# 14. TRAINING DATA LABEL INDEPENDENCE CHECK
# ============================================================
#
# This is only for reporting.
# Labels are NOT passed into Isolation Forest.
# ============================================================

print("\n[13] TRAINING DATA LABEL DISTRIBUTION")
print("-" * 80)

print(
    data.loc[train_mask, "class"]
    .value_counts()
    .sort_index()
)

print(
    "\nNOTE: These labels are NOT used for model training."
)


# ============================================================
# 15. ISOLATION FOREST
# ============================================================

print("\n[14] TRAINING ISOLATION FOREST")
print("-" * 80)

model = IsolationForest(
    n_estimators=300,
    max_samples="auto",
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train)

print("Isolation Forest training complete.")


# ============================================================
# 16. GENERATE SCORES
# ============================================================
#
# sklearn decision_function:
#   higher = more normal
#
# Therefore:
#   anomaly_score = -decision_function
#
# higher anomaly_score = more anomalous
# ============================================================

print("\n[15] GENERATING ANOMALY SCORES")
print("-" * 80)

data["anomaly_score"] = np.nan
data["iforest_prediction"] = np.nan

train_scores = -model.decision_function(X_train)
val_scores = -model.decision_function(X_val)
test_scores = -model.decision_function(X_test)

train_pred = model.predict(X_train)
val_pred = model.predict(X_val)
test_pred = model.predict(X_test)

data.loc[train_mask, "anomaly_score"] = train_scores
data.loc[val_mask, "anomaly_score"] = val_scores
data.loc[test_mask, "anomaly_score"] = test_scores

data.loc[train_mask, "iforest_prediction"] = train_pred
data.loc[val_mask, "iforest_prediction"] = val_pred
data.loc[test_mask, "iforest_prediction"] = test_pred


# ============================================================
# 17. SCORE DISTRIBUTION
# ============================================================

print("\n[16] ANOMALY SCORE DISTRIBUTION")
print("-" * 80)

score_summary = pd.DataFrame({
    "Train": train_scores,
    "Validation": pd.Series(val_scores),
    "Test": pd.Series(test_scores)
})

print(
    score_summary.describe(
        percentiles=[0.01, 0.02, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    ).to_string()
)


# ============================================================
# 18. THRESHOLD ANALYSIS
# ============================================================
#
# Instead of trusting the default Isolation Forest threshold,
# analyse several anomaly-rate thresholds.
# ============================================================

print("\n[17] THRESHOLD ANALYSIS")
print("-" * 80)

threshold_rates = [
    0.01,
    0.02,
    0.03,
    0.05,
    0.10
]

threshold_rows = []

test_score_series = pd.Series(
    test_scores,
    index=data.index[test_mask]
)

for rate in threshold_rates:

    threshold = test_score_series.quantile(
        1 - rate
    )

    anomaly_mask = test_score_series >= threshold

    threshold_rows.append({
        "Anomaly_Rate": rate,
        "Threshold": threshold,
        "Anomalies": int(anomaly_mask.sum())
    })

threshold_table = pd.DataFrame(threshold_rows)

print(
    threshold_table.to_string(index=False)
)


# ============================================================
# 19. CHOOSE 5% THRESHOLD FOR INITIAL INVESTIGATION
# ============================================================
#
# NOTE:
# 5% is an investigation threshold, NOT a claim that 5% are
# actually fraudulent.
# ============================================================

chosen_rate = 0.05

chosen_threshold = test_score_series.quantile(
    1 - chosen_rate
)

print("\nChosen investigation threshold:", chosen_threshold)

data["is_anomaly"] = False

data.loc[
    test_mask &
    (data["anomaly_score"] >= chosen_threshold),
    "is_anomaly"
] = True


# ============================================================
# 20. OVERALL TEST ANOMALY SUMMARY
# ============================================================

print("\n[18] TEST ANOMALY SUMMARY")
print("-" * 80)

test_results = data.loc[test_mask].copy()

print("Test transactions:", len(test_results))
print(
    "Detected anomalies:",
    int(test_results["is_anomaly"].sum())
)

print(
    "Observed anomaly percentage:",
    round(
        test_results["is_anomaly"].mean() * 100,
        2
    ),
    "%"
)


# ============================================================
# 21. CLASS-WISE ANOMALY ANALYSIS
# ============================================================
#
# IMPORTANT:
# Labels are used ONLY now for evaluation.
# ============================================================

print("\n[19] CLASS-WISE ANOMALY ANALYSIS")
print("-" * 80)

class_analysis = (
    test_results
    .groupby("class")
    .agg(
        Total=("class", "size"),
        Anomalies=("is_anomaly", "sum"),
        Mean_Anomaly_Score=("anomaly_score", "mean"),
        Median_Anomaly_Score=("anomaly_score", "median"),
        Max_Anomaly_Score=("anomaly_score", "max")
    )
)

class_analysis["Anomaly_%"] = (
    class_analysis["Anomalies"]
    / class_analysis["Total"]
    * 100
)

print(
    class_analysis.to_string()
)


# ============================================================
# 22. CLASS-3 SPECIFIC ANALYSIS
# ============================================================

print("\n[20] CLASS-3 / UNKNOWN ANALYSIS")
print("-" * 80)

class3_test = test_results[
    test_results["class"] == 3
]

non_class3_test = test_results[
    test_results["class"] != 3
]

print("Class-3 test samples:", len(class3_test))
print("Non-Class-3 test samples:", len(non_class3_test))

print(
    "\nClass-3 anomalies:",
    int(class3_test["is_anomaly"].sum())
)

print(
    "Class-3 anomaly percentage:",
    round(
        class3_test["is_anomaly"].mean() * 100,
        2
    ),
    "%"
)

print(
    "\nNon-Class-3 anomalies:",
    int(non_class3_test["is_anomaly"].sum())
)

print(
    "Non-Class-3 anomaly percentage:",
    round(
        non_class3_test["is_anomaly"].mean() * 100,
        2
    ),
    "%"
)


# ============================================================
# 23. CLASS-1 / ILLICIT OVERLAP
# ============================================================

print("\n[21] KNOWN ILLICIT OVERLAP")
print("-" * 80)

class1_test = test_results[
    test_results["class"] == 1
]

class2_test = test_results[
    test_results["class"] == 2
]

print("Known Class-1 samples:", len(class1_test))
print(
    "Class-1 detected as anomaly:",
    int(class1_test["is_anomaly"].sum())
)

if len(class1_test) > 0:
    print(
        "Class-1 anomaly rate:",
        round(
            class1_test["is_anomaly"].mean() * 100,
            2
        ),
        "%"
    )

print("\nKnown Class-2 samples:", len(class2_test))
print(
    "Class-2 detected as anomaly:",
    int(class2_test["is_anomaly"].sum())
)

if len(class2_test) > 0:
    print(
        "Class-2 anomaly rate:",
        round(
            class2_test["is_anomaly"].mean() * 100,
            2
        ),
        "%"
    )


# ============================================================
# 24. TEMPORAL ANOMALY ANALYSIS
# ============================================================

print("\n[22] TEMPORAL ANOMALY ANALYSIS")
print("-" * 80)

temporal_analysis = (
    test_results
    .groupby(TIME_COL)
    .agg(
        Transactions=("class", "size"),
        Anomalies=("is_anomaly", "sum"),
        Mean_Anomaly_Score=("anomaly_score", "mean"),
        Class3_Count=("class", lambda x: (x == 3).sum()),
        Class1_Count=("class", lambda x: (x == 1).sum()),
        Class2_Count=("class", lambda x: (x == 2).sum())
    )
)

temporal_analysis["Anomaly_%"] = (
    temporal_analysis["Anomalies"]
    / temporal_analysis["Transactions"]
    * 100
)

temporal_analysis["Class3_%"] = (
    temporal_analysis["Class3_Count"]
    / temporal_analysis["Transactions"]
    * 100
)

print(
    temporal_analysis.to_string()
)


# ============================================================
# 25. TOP ANOMALOUS TRANSACTIONS
# ============================================================

print("\n[23] TOP 30 ANOMALOUS TEST TRANSACTIONS")
print("-" * 80)

top_anomalies = (
    test_results
    .sort_values(
        "anomaly_score",
        ascending=False
    )
    [[
        TX_ID_COL,
        TIME_COL,
        "class",
        "anomaly_score"
    ]]
    .head(30)
)

print(
    top_anomalies.to_string(index=False)
)


# ============================================================
# 26. FEATURE-LEVEL ANOMALY ANALYSIS
# ============================================================
#
# We compare:
#
#   normal test transactions
#           VS
#   detected anomalies
#
# using standardized absolute deviations based on the
# training distribution.
# ============================================================

print("\n[24] FEATURE-LEVEL ANOMALY ANALYSIS")
print("-" * 80)

train_feature_mean = X_train.mean()
train_feature_std = X_train.std().replace(0, np.nan)

test_feature_values = X.loc[test_mask]

z_test = (
    test_feature_values
    - train_feature_mean
) / train_feature_std

z_test = z_test.abs()

z_test["is_anomaly"] = test_results["is_anomaly"].values

normal_z = z_test[
    z_test["is_anomaly"] == False
].drop(columns="is_anomaly")

anomaly_z = z_test[
    z_test["is_anomaly"] == True
].drop(columns="is_anomaly")

feature_effect = pd.DataFrame({
    "Normal_Mean_Abs_Z": normal_z.mean(),
    "Anomaly_Mean_Abs_Z": anomaly_z.mean()
})

feature_effect["Difference"] = (
    feature_effect["Anomaly_Mean_Abs_Z"]
    - feature_effect["Normal_Mean_Abs_Z"]
)

feature_effect = feature_effect.sort_values(
    "Difference",
    ascending=False
)

print(
    feature_effect.to_string()
)


# ============================================================
# 27. TOP FEATURES ASSOCIATED WITH DETECTED ANOMALIES
# ============================================================

print("\n[25] TOP FEATURES ASSOCIATED WITH DETECTED ANOMALIES")
print("-" * 80)

print(
    feature_effect
    .head(13)
    .to_string()
)


# ============================================================
# 28. CLASS-3 FEATURE COMPARISON
# ============================================================

print("\n[26] CLASS-3 VS NON-CLASS-3 — ANOMALY SCORE")
print("-" * 80)

class3_score = test_results.loc[
    test_results["class"] == 3,
    "anomaly_score"
]

non_class3_score = test_results.loc[
    test_results["class"] != 3,
    "anomaly_score"
]

print(
    "Class-3 mean score:",
    class3_score.mean()
)

print(
    "Non-Class-3 mean score:",
    non_class3_score.mean()
)

print(
    "Class-3 median score:",
    class3_score.median()
)

print(
    "Non-Class-3 median score:",
    non_class3_score.median()
)


# ============================================================
# 29. SAVE RESULTS
# ============================================================

print("\n[27] SAVING RESULTS")
print("-" * 80)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "outputs",
    "elliptic_transactions"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

# Main transaction-level results
result_file = os.path.join(
    OUTPUT_DIR,
    "elliptic_transaction_anomaly_results.csv"
)

data.to_csv(
    result_file,
    index=False
)

# Class analysis
class_file = os.path.join(
    OUTPUT_DIR,
    "class_wise_anomaly_analysis.csv"
)

class_analysis.to_csv(
    class_file
)

# Temporal analysis
temporal_file = os.path.join(
    OUTPUT_DIR,
    "temporal_anomaly_analysis.csv"
)

temporal_analysis.to_csv(
    temporal_file
)

# Feature analysis
feature_file = os.path.join(
    OUTPUT_DIR,
    "anomaly_feature_analysis.csv"
)

feature_effect.to_csv(
    feature_file
)

# Threshold table
threshold_file = os.path.join(
    OUTPUT_DIR,
    "anomaly_threshold_analysis.csv"
)

threshold_table.to_csv(
    threshold_file,
    index=False
)

print("Saved:")
print("1.", result_file)
print("2.", class_file)
print("3.", temporal_file)
print("4.", feature_file)
print("5.", threshold_file)


# ============================================================
# 30. FINAL PIPELINE SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("PIPELINE COMPLETE")
print("=" * 80)

print("\nDataset:")
print("  Transactions:", len(data))
print("  Time steps:", data[TIME_COL].nunique())

print("\nFeatures:")
print("  Original selected:", len(SELECTED_FEATURES))
print("  Used:", len(SELECTED_FEATURES))

print("\nModel:")
print("  Isolation Forest")
print("  Estimators:", 300)
print("  Training:", "earlier time steps only")
print("  Labels used during training: NO")

print("\nInvestigation threshold:")
print("  Anomaly rate:", chosen_rate * 100, "%")
print("  Threshold:", chosen_threshold)

print("\nTest results:")
print("  Test transactions:", len(test_results))
print(
    "  Detected anomalies:",
    int(test_results["is_anomaly"].sum())
)

print("\nClass-3:")
print("  Test Class-3:", len(class3_test))
print(
    "  Class-3 anomalies:",
    int(class3_test["is_anomaly"].sum())
)

print("\nOutput directory:")
print(OUTPUT_DIR)

print("\n" + "=" * 80)
print("NEXT STAGE AFTER THIS:")
print("TRANSACTION GRAPH + ANOMALY CORRELATION")
print("=" * 80)


# Free some temporary memory
gc.collect()

================================================================================
BIT-TRACE — ELLIPTIC++ UNSUPERVISED ANOMALY PIPELINE
================================================================================

[1] PATH CHECK
--------------------------------------------------------------------------------
Feature file exists: True
Class file exists: True

[2] SELECTED FEATURES
--------------------------------------------------------------------------------
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47

Number of selected features: 13

[3] LOADING CLASS DATA
--------------------------------------------------------------------------------
Class data shape: (203769, 2)
Columns: ['txId', 'class']

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[4] READING FEATURE HEADER
--------------------------------------------------------------------------------
Total columns in feature file: 184

First columns:
['txId', 'Time step', 'Local_feature_1', 'Local_feature_2', 'Local_feature_3', 'Local_feature_4', 'Local_feature_5', 'Local_feature_6', 'Local_feature_7', 'Local_feature_8', 'Local_feature_9', 'Local_feature_10', 'Local_feature_11', 'Local_feature_12', 'Local_feature_13', 'Local_feature_14', 'Local_feature_15', 'Local_feature_16', 'Local_feature_17', 'Local_feature_18']

Detected transaction ID column: txId
Detected time column: Time step

[5] LOADING REQUIRED FEATURE COLUMNS
--------------------------------------------------------------------------------
Columns being loaded: 15

Loaded shape: (203769, 15)

[6] BASIC DATA CLEANING
--------------------------------------------------------------------------------
Missing txId: 0
Missing time step: 0

[7] MERGING FEATURES + LABELS
--------------------------------------------------------------------------------
Merged shape: (203769, 16)

Missing labels:
0

Class distribution after merge:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[8] TEMPORAL VALIDATION
--------------------------------------------------------------------------------
Minimum time step: 1
Maximum time step: 49
Number of unique time steps: 49

Transactions per time step:
Time step
1     7880
2     4544
3     6621
4     5693
5     6803
6     4328
7     6048
8     4457
9     4996
10    6727
11    4296
12    2047
13    4528
14    2022
15    3639
16    2975
17    3385
18    1976
19    3506
20    4291
21    3537
22    5894
23    4165
24    4592
25    2314
26    2523
27    1089
28    1653
29    4275
30    2483
31    2816
32    4525
33    3151
34    2486
35    5507
36    6393
37    3306
38    2891
39    2760
40    4481
41    5342
42    7140
43    5063
44    4975
45    5598
46    3519
47    5121
48    2954
49    2454

[9] DATA QUALITY CHECK
--------------------------------------------------------------------------------
Empty DataFrame
Columns: [NaN_count, Inf_count]
Index: []

Total NaN values: 0
Total Inf values: 0

[10] MEDIAN IMPUTATION
--------------------------------------------------------------------------------
Final X shape: (203769, 13)
Remaining NaN: 0

[11] FEATURE SUMMARY
--------------------------------------------------------------------------------
                              mean       std       min    median        max
Local_feature_53      1.785345e-17  1.000002 -0.488366 -0.487907   6.508779
Local_feature_54      6.695042e-17  1.000002 -0.232553 -0.232553  15.543521
Local_feature_52      3.347521e-17  1.000002 -0.414036 -0.413893   7.999066
Local_feature_59      3.124353e-17  1.000002 -0.172895 -0.172877  14.878400
Aggregate_feature_21 -2.901185e-17  1.000002 -0.349933 -0.349933   8.502634
Local_feature_25      2.231681e-17  1.000002 -0.155662 -0.155656  21.548029
Local_feature_77      3.124353e-17  1.000002 -0.264425 -0.264107  15.220632
Local_feature_89      8.926723e-18  1.000002 -0.761984 -0.492331   6.887737
Local_feature_90      6.248706e-17  1.000002 -0.694235 -0.485812   6.506444
Aggregate_feature_32  4.463361e-17  1.000002 -0.145126 -0.143707  18.455157
Aggregate_feature_14  1.785345e-17  1.000002 -0.224985 -0.191190  33.569912
Local_feature_22      1.366904e-17  1.000002 -0.139732 -0.139728  25.474087
Local_feature_47      1.785345e-17  1.000002 -0.243236 -0.243236  10.995786

[12] TEMPORAL SPLIT
--------------------------------------------------------------------------------
Train time steps: 1 to 34
Validation time steps: 35 to 41
Test time steps: 42 to 49

Train samples: 136265
Validation samples: 30680
Test samples: 36824

[13] TRAINING DATA LABEL DISTRIBUTION
--------------------------------------------------------------------------------
class
1      3462
2     26432
3    106371
Name: count, dtype: int64

NOTE: These labels are NOT used for model training.

[14] TRAINING ISOLATION FOREST
--------------------------------------------------------------------------------
Isolation Forest training complete.

[15] GENERATING ANOMALY SCORES
--------------------------------------------------------------------------------

[16] ANOMALY SCORE DISTRIBUTION
--------------------------------------------------------------------------------

ValueError: array length 136265 does not match index length 36824

In [28]:
# ============================================================
# [16] ANOMALY SCORE DISTRIBUTION — FIXED
# ============================================================

print("=" * 80)
print("ANOMALY SCORE DISTRIBUTION")
print("=" * 80)

score_summary = pd.DataFrame({
    "Split": ["Train", "Validation", "Test"],
    "Samples": [
        len(train_scores),
        len(val_scores),
        len(test_scores)
    ],
    "Mean_Score": [
        np.mean(train_scores),
        np.mean(val_scores),
        np.mean(test_scores)
    ],
    "Std_Score": [
        np.std(train_scores),
        np.std(val_scores),
        np.std(test_scores)
    ],
    "Min_Score": [
        np.min(train_scores),
        np.min(val_scores),
        np.min(test_scores)
    ],
    "Median_Score": [
        np.median(train_scores),
        np.median(val_scores),
        np.median(test_scores)
    ],
    "Max_Score": [
        np.max(train_scores),
        np.max(val_scores),
        np.max(test_scores)
    ]
})

print(score_summary.to_string(index=False))

================================================================================
ANOMALY SCORE DISTRIBUTION
================================================================================
     Split  Samples  Mean_Score  Std_Score  Min_Score  Median_Score  Max_Score
     Train   136265   -0.127619   0.087435  -0.187823     -0.169255   0.268584
Validation    30680   -0.123678   0.088502  -0.187786     -0.169131   0.250759
      Test    36824   -0.121554   0.090663  -0.187823     -0.167228   0.255413

In [29]:
# ============================================================
# [17] ANOMALY SCORES + TRUE CLASSES
#     EVALUATION ONLY — LABELS NOT USED FOR TRAINING
# ============================================================

print("=" * 80)
print("UNSUPERVISED ANOMALY DETECTION — CLASS-WISE EVALUATION")
print("=" * 80)

# Create evaluation dataframe
train_eval = merged.iloc[train_idx][["txId", "class", "Time step"]].copy()
val_eval   = merged.iloc[val_idx][["txId", "class", "Time step"]].copy()
test_eval  = merged.iloc[test_idx][["txId", "class", "Time step"]].copy()

train_eval["anomaly_score"] = train_scores
val_eval["anomaly_score"]   = val_scores
test_eval["anomaly_score"]  = test_scores

eval_df = pd.concat(
    [train_eval, val_eval, test_eval],
    ignore_index=True
)

print("\nEvaluation dataset shape:", eval_df.shape)

print("\nClass distribution:")
print(eval_df["class"].value_counts().sort_index())

print("\nAnomaly score statistics by class:")
class_score_stats = eval_df.groupby("class")["anomaly_score"].agg(
    ["count", "mean", "std", "min", "median", "max"]
)

print(class_score_stats)

================================================================================
UNSUPERVISED ANOMALY DETECTION — CLASS-WISE EVALUATION
================================================================================

NameError: name 'merged' is not defined

In [30]:
# ============================================================
# BIT-TRACE — UNSUPERVISED ANOMALY DETECTION
# CLASS-WISE EVALUATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 80)
print("UNSUPERVISED ANOMALY DETECTION — CLASS-WISE EVALUATION")
print("=" * 80)

# ------------------------------------------------------------
# 1. RECREATE EVALUATION DATA FROM THE DATAFRAME
# ------------------------------------------------------------

# Your main merged dataframe was not retained in memory.
# Recreate only the required metadata from the loaded dataset.

eval_df = pd.DataFrame({
    "txId": data["txId"].values,
    "Time step": data["Time step"].values,
    "class": data["class"].values
})

print("\nEvaluation dataframe:", eval_df.shape)

# ------------------------------------------------------------
# 2. ATTACH ANOMALY SCORES
# ------------------------------------------------------------

eval_df["anomaly_score"] = np.nan

eval_df.loc[train_idx, "anomaly_score"] = train_scores
eval_df.loc[val_idx, "anomaly_score"] = val_scores
eval_df.loc[test_idx, "anomaly_score"] = test_scores

# ------------------------------------------------------------
# 3. VERIFY
# ------------------------------------------------------------

print("\nMissing anomaly scores:",
      eval_df["anomaly_score"].isna().sum())

print("Total rows:", len(eval_df))

# ------------------------------------------------------------
# 4. SCORE SUMMARY BY CLASS
# ------------------------------------------------------------

class_summary = (
    eval_df
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
    .round(6)
)

print("\n" + "=" * 80)
print("ANOMALY SCORE BY ORIGINAL CLASS")
print("=" * 80)

print(class_summary)

# ------------------------------------------------------------
# 5. CLASS-WISE SCORE QUANTILES
# ------------------------------------------------------------

quantiles = (
    eval_df
    .groupby("class")["anomaly_score"]
    .quantile([0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99])
    .unstack()
)

quantiles.columns = [
    "Q01", "Q05", "Q10", "Q25",
    "Q50", "Q75", "Q90", "Q95", "Q99"
]

print("\n" + "=" * 80)
print("CLASS-WISE ANOMALY SCORE QUANTILES")
print("=" * 80)

print(quantiles.round(6))

# ------------------------------------------------------------
# 6. MOST ANOMALOUS TRANSACTIONS
# ------------------------------------------------------------

# Isolation Forest:
# lower score = more anomalous

most_anomalous = (
    eval_df
    .sort_values("anomaly_score", ascending=True)
    .head(50)
)

print("\n" + "=" * 80)
print("TOP 50 MOST ANOMALOUS TRANSACTIONS")
print("=" * 80)

print(
    most_anomalous[
        ["txId", "Time step", "class", "anomaly_score"]
    ].to_string(index=False)
)

# ------------------------------------------------------------
# 7. CLASS DISTRIBUTION AMONG TOP ANOMALIES
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("CLASS DISTRIBUTION AMONG TOP ANOMALIES")
print("=" * 80)

for n in [50, 100, 500, 1000, 5000]:

    top_n = eval_df.nsmallest(n, "anomaly_score")

    counts = top_n["class"].value_counts().sort_index()

    percentages = (
        top_n["class"]
        .value_counts(normalize=True)
        .sort_index()
        .mul(100)
        .round(2)
    )

    result = pd.DataFrame({
        "Count": counts,
        "Percentage": percentages
    })

    print(f"\nTop {n} anomalies:")
    print(result)

# ------------------------------------------------------------
# 8. CLASS 3 REPRESENTATION IN ANOMALIES
# ------------------------------------------------------------

overall_class3_pct = (
    (eval_df["class"] == 3).mean() * 100
)

print("\n" + "=" * 80)
print("CLASS 3 ANOMALY REPRESENTATION")
print("=" * 80)

print(f"Overall Class 3 percentage: {overall_class3_pct:.2f}%")

for n in [50, 100, 500, 1000, 5000]:

    top_n = eval_df.nsmallest(n, "anomaly_score")

    class3_count = (top_n["class"] == 3).sum()
    class3_pct = class3_count / n * 100

    enrichment = class3_pct / overall_class3_pct

    print(
        f"Top {n:5d}: "
        f"Class 3 = {class3_count:5d} "
        f"({class3_pct:6.2f}%) | "
        f"Enrichment = {enrichment:.3f}x"
    )

# ------------------------------------------------------------
# 9. TEMPORAL ANOMALY ANALYSIS
# ------------------------------------------------------------

temporal = (
    eval_df
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly_Score=("anomaly_score", "mean"),
        Median_Anomaly_Score=("anomaly_score", "median"),
        Class3_Count=("class", lambda x: (x == 3).sum())
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"]
    / temporal["Transactions"]
    * 100
)

print("\n" + "=" * 80)
print("MOST ANOMALOUS TIME STEPS")
print("=" * 80)

print(
    temporal
    .sort_values("Mean_Anomaly_Score")
    .head(15)
    .round(4)
)

print("\n" + "=" * 80)
print("EVALUATION COMPLETE")
print("=" * 80)

================================================================================
UNSUPERVISED ANOMALY DETECTION — CLASS-WISE EVALUATION
================================================================================

Evaluation dataframe: (203769, 3)

NameError: name 'train_idx' is not defined

In [31]:
# ============================================================
# RECREATE SPLIT INDICES + CLASS-WISE ANOMALY EVALUATION
# ============================================================

import numpy as np
import pandas as pd

print("=" * 80)
print("RECREATING TEMPORAL INDICES")
print("=" * 80)

# ------------------------------------------------------------
# 1. RECREATE TEMPORAL INDICES
# ------------------------------------------------------------

# Based on your actual temporal split:
# Train      = time steps 1–34
# Validation = time steps 35–41
# Test       = time steps 42–49

train_idx = np.where(time_steps <= 34)[0]
val_idx   = np.where((time_steps >= 35) & (time_steps <= 41))[0]
test_idx  = np.where(time_steps >= 42)[0]

print("Train indices:", len(train_idx))
print("Validation indices:", len(val_idx))
print("Test indices:", len(test_idx))
print("Total:", len(train_idx) + len(val_idx) + len(test_idx))

# ------------------------------------------------------------
# 2. SANITY CHECK
# ------------------------------------------------------------

assert len(train_idx) == 136265
assert len(val_idx) == 30680
assert len(test_idx) == 36824

print("\nSplit sizes verified.")

# ------------------------------------------------------------
# 3. CREATE EVALUATION DATAFRAME
# ------------------------------------------------------------

eval_df = pd.DataFrame({
    "txId": data["txId"].values,
    "Time step": data["Time step"].values,
    "class": data["class"].values
})

# ------------------------------------------------------------
# 4. ATTACH ALREADY-COMPUTED ANOMALY SCORES
# ------------------------------------------------------------

eval_df["anomaly_score"] = np.nan

eval_df.loc[train_idx, "anomaly_score"] = train_scores
eval_df.loc[val_idx, "anomaly_score"] = val_scores
eval_df.loc[test_idx, "anomaly_score"] = test_scores

print("\nMissing anomaly scores:",
      eval_df["anomaly_score"].isna().sum())

assert eval_df["anomaly_score"].notna().all()

# ------------------------------------------------------------
# 5. CLASS-WISE ANOMALY SCORE
# ------------------------------------------------------------

class_summary = (
    eval_df
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print("\n" + "=" * 80)
print("ANOMALY SCORE BY ORIGINAL CLASS")
print("=" * 80)

print(class_summary.round(6))

# ------------------------------------------------------------
# 6. TOP ANOMALIES
# ------------------------------------------------------------

top_100 = (
    eval_df
    .sort_values("anomaly_score", ascending=True)
    .head(100)
)

print("\n" + "=" * 80)
print("TOP 100 MOST ANOMALOUS TRANSACTIONS")
print("=" * 80)

print(
    top_100[
        ["txId", "Time step", "class", "anomaly_score"]
    ].head(30).to_string(index=False)
)

# ------------------------------------------------------------
# 7. CLASS DISTRIBUTION AMONG TOP ANOMALIES
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("CLASS DISTRIBUTION AMONG TOP ANOMALIES")
print("=" * 80)

for n in [50, 100, 500, 1000, 5000]:

    top_n = eval_df.nsmallest(n, "anomaly_score")

    counts = (
        top_n["class"]
        .value_counts()
        .sort_index()
    )

    percentages = (
        top_n["class"]
        .value_counts(normalize=True)
        .sort_index()
        .mul(100)
    )

    result = pd.DataFrame({
        "Count": counts,
        "Percentage": percentages.round(2)
    })

    print(f"\nTop {n} anomalies:")
    print(result)

# ------------------------------------------------------------
# 8. CLASS-3 ENRICHMENT
# ------------------------------------------------------------

overall_class3_pct = (
    (eval_df["class"] == 3).mean() * 100
)

print("\n" + "=" * 80)
print("CLASS-3 REPRESENTATION IN ANOMALIES")
print("=" * 80)

print(
    f"Overall Class-3 percentage: "
    f"{overall_class3_pct:.2f}%"
)

for n in [50, 100, 500, 1000, 5000]:

    top_n = eval_df.nsmallest(n, "anomaly_score")

    class3_count = (
        top_n["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / n * 100
    )

    enrichment = (
        class3_pct / overall_class3_pct
    )

    print(
        f"Top {n:5d}: "
        f"Class-3 = {class3_count:5d} "
        f"({class3_pct:6.2f}%) | "
        f"Enrichment = {enrichment:.3f}x"
    )

# ------------------------------------------------------------
# 9. TEMPORAL ANOMALY ANALYSIS
# ------------------------------------------------------------

temporal = (
    eval_df
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly_Score=("anomaly_score", "mean"),
        Median_Anomaly_Score=("anomaly_score", "median"),
        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"]
    / temporal["Transactions"]
    * 100
)

print("\n" + "=" * 80)
print("MOST ANOMALOUS TIME STEPS")
print("=" * 80)

print(
    temporal
    .sort_values("Mean_Anomaly_Score")
    .head(15)
    .round(4)
)

print("\n" + "=" * 80)
print("UNSUPERVISED EVALUATION COMPLETE")
print("=" * 80)

================================================================================
RECREATING TEMPORAL INDICES
================================================================================

NameError: name 'time_steps' is not defined

In [32]:
# ============================================================
# BIT-TRACE — FINAL RECOVERY + UNSUPERVISED EVALUATION
# No dependency on time_steps / train_idx / val_idx
# ============================================================

import numpy as np
import pandas as pd

print("=" * 80)
print("RECOVERING TEMPORAL SPLITS FROM LOADED DATA")
print("=" * 80)

# ------------------------------------------------------------
# 1. GET TIME STEP DIRECTLY FROM DATA
# ------------------------------------------------------------

time_steps = data["Time step"].to_numpy()

print("Total rows:", len(time_steps))
print("Time range:", time_steps.min(), "to", time_steps.max())

# ------------------------------------------------------------
# 2. RECREATE INDICES
# ------------------------------------------------------------

train_idx = np.where(time_steps <= 34)[0]

val_idx = np.where(
    (time_steps >= 35) &
    (time_steps <= 41)
)[0]

test_idx = np.where(time_steps >= 42)[0]

print("\nTrain samples:", len(train_idx))
print("Validation samples:", len(val_idx))
print("Test samples:", len(test_idx))

assert len(train_idx) == 136265
assert len(val_idx) == 30680
assert len(test_idx) == 36824

print("✓ Temporal split verified")

# ------------------------------------------------------------
# 3. BUILD EVALUATION DATAFRAME
# ------------------------------------------------------------

eval_df = pd.DataFrame({
    "txId": data["txId"].to_numpy(),
    "Time step": data["Time step"].to_numpy(),
    "class": data["class"].to_numpy()
})

# ------------------------------------------------------------
# 4. ATTACH EXISTING ISOLATION FOREST SCORES
# ------------------------------------------------------------

eval_df["anomaly_score"] = np.nan

eval_df.loc[train_idx, "anomaly_score"] = train_scores
eval_df.loc[val_idx, "anomaly_score"] = val_scores
eval_df.loc[test_idx, "anomaly_score"] = test_scores

print("\nMissing scores:",
      eval_df["anomaly_score"].isna().sum())

assert eval_df["anomaly_score"].notna().all()

print("✓ All anomaly scores attached")

# ============================================================
# 5. CLASS-WISE ANOMALY SCORES
# ============================================================

print("\n" + "=" * 80)
print("CLASS-WISE ANOMALY SCORE ANALYSIS")
print("=" * 80)

class_summary = (
    eval_df
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
    .round(6)
)

print(class_summary)

# ============================================================
# 6. CLASS-WISE QUANTILES
# ============================================================

print("\n" + "=" * 80)
print("CLASS-WISE SCORE QUANTILES")
print("=" * 80)

quantiles = (
    eval_df
    .groupby("class")["anomaly_score"]
    .quantile([
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ])
    .unstack()
)

quantiles.columns = [
    "Q01",
    "Q05",
    "Q10",
    "Q25",
    "Q50",
    "Q75",
    "Q90",
    "Q95",
    "Q99"
]

print(quantiles.round(6))

# ============================================================
# 7. TOP ANOMALOUS TRANSACTIONS
# ============================================================

print("\n" + "=" * 80)
print("TOP 30 MOST ANOMALOUS TRANSACTIONS")
print("=" * 80)

top_30 = (
    eval_df
    .nsmallest(30, "anomaly_score")
)

print(
    top_30[
        [
            "txId",
            "Time step",
            "class",
            "anomaly_score"
        ]
    ].to_string(index=False)
)

# ============================================================
# 8. CLASS DISTRIBUTION AMONG TOP ANOMALIES
# ============================================================

print("\n" + "=" * 80)
print("CLASS DISTRIBUTION AMONG TOP ANOMALIES")
print("=" * 80)

for n in [50, 100, 500, 1000, 5000]:

    top_n = eval_df.nsmallest(
        n,
        "anomaly_score"
    )

    counts = (
        top_n["class"]
        .value_counts()
        .sort_index()
    )

    percentages = (
        top_n["class"]
        .value_counts(normalize=True)
        .sort_index()
        * 100
    )

    result = pd.DataFrame({
        "Count": counts,
        "Percentage": percentages.round(2)
    })

    print(f"\nTop {n} anomalies:")
    print(result)

# ============================================================
# 9. CLASS-3 ENRICHMENT
# ============================================================

print("\n" + "=" * 80)
print("CLASS-3 ENRICHMENT")
print("=" * 80)

overall_class3_pct = (
    (eval_df["class"] == 3).mean()
    * 100
)

print(
    f"Overall Class-3 percentage: "
    f"{overall_class3_pct:.2f}%"
)

for n in [50, 100, 500, 1000, 5000]:

    top_n = eval_df.nsmallest(
        n,
        "anomaly_score"
    )

    class3_count = (
        top_n["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / n * 100
    )

    enrichment = (
        class3_pct /
        overall_class3_pct
    )

    print(
        f"Top {n:5d}: "
        f"Class-3 = {class3_count:5d} "
        f"({class3_pct:6.2f}%) | "
        f"Enrichment = {enrichment:.3f}x"
    )

# ============================================================
# 10. TEMPORAL ANOMALY ANALYSIS
# ============================================================

print("\n" + "=" * 80)
print("TEMPORAL ANOMALY ANALYSIS")
print("=" * 80)

temporal = (
    eval_df
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),

        Mean_Anomaly_Score=(
            "anomaly_score",
            "mean"
        ),

        Median_Anomaly_Score=(
            "anomaly_score",
            "median"
        ),

        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"]
    / temporal["Transactions"]
    * 100
)

print("\nMost anomalous time steps:")
print(
    temporal
    .sort_values(
        "Mean_Anomaly_Score"
    )
    .head(15)
    .round(4)
)

# ============================================================
# 11. TEST-SET-ONLY ANALYSIS
# ============================================================

print("\n" + "=" * 80)
print("TEST SET — FINAL UNSUPERVISED ANALYSIS")
print("=" * 80)

test_eval = eval_df.loc[test_idx].copy()

print("Test samples:", len(test_eval))

test_class_summary = (
    test_eval
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print("\nTest-set anomaly scores by class:")
print(test_class_summary.round(6))

# ============================================================
# 12. FINAL STATUS
# ============================================================

print("\n" + "=" * 80)
print("PIPELINE STATUS")
print("=" * 80)

print("✓ Elliptic++ loaded")
print("✓ 13 selected features")
print("✓ Temporal split preserved")
print("✓ Isolation Forest trained")
print("✓ Anomaly scores generated")
print("✓ Class-wise evaluation completed")
print("✓ Temporal anomaly analysis completed")
print("✓ Test-set analysis completed")

print("\nNEXT STEP:")
print("Use the output above to decide whether")
print("the anomaly scores meaningfully separate the classes.")
print("=" * 80)

================================================================================
RECOVERING TEMPORAL SPLITS FROM LOADED DATA
================================================================================
Total rows: 203769
Time range: 1 to 49

Train samples: 136265
Validation samples: 30680
Test samples: 36824
✓ Temporal split verified

Missing scores: 0
✓ All anomaly scores attached

================================================================================
CLASS-WISE ANOMALY SCORE ANALYSIS
================================================================================
       Samples      Mean       Std       Min    Median       Max
class
1         4545 -0.161532  0.044583 -0.187823 -0.185225  0.118625
2        42019 -0.029228  0.115872 -0.187823 -0.037998  0.268584
3       157205 -0.150748  0.057363 -0.187823 -0.175425  0.216187

================================================================================
CLASS-WISE SCORE QUANTILES
================================================================================
            Q01       Q05       Q10       Q25       Q50       Q75       Q90  \
class
1     -0.187691 -0.187644 -0.187574 -0.187369 -0.185225 -0.162070 -0.065279
2     -0.187203 -0.186252 -0.181549 -0.134047 -0.037998  0.061418  0.127582
3     -0.187644 -0.187465 -0.187062 -0.184912 -0.175425 -0.139999 -0.082084

            Q95       Q99
class
1     -0.063153 -0.037687
2      0.168010  0.193703
3     -0.035455  0.094786

================================================================================
TOP 30 MOST ANOMALOUS TRANSACTIONS
================================================================================
     txId  Time step  class  anomaly_score
310414790          2      3      -0.187823
 94208734          7      3      -0.187823
 33356722          9      3      -0.187823
226550846          9      3      -0.187823
 41777392         11      3      -0.187823
235428537         11      3      -0.187823
152492980         13      3      -0.187823
240789881         15      3      -0.187823
243780864         15      1      -0.187823
288170821         19      3      -0.187823
362960728         19      1      -0.187823
363088189         19      3      -0.187823
363714729         19      3      -0.187823
209682088         20      3      -0.187823
209708391         20      3      -0.187823
210231187         20      3      -0.187823
100005088         21      3      -0.187823
115193634         21      3      -0.187823
306358852         22      3      -0.187823
372812179         22      3      -0.187823
372876158         22      3      -0.187823
331530806         23      3      -0.187823
336710813         23      3      -0.187823
272095019         24      3      -0.187823
272289601         24      3      -0.187823
 84324995         26      3      -0.187823
 84353479         26      3      -0.187823
 84722792         26      3      -0.187823
 84723702         26      3      -0.187823
 84749869         26      3      -0.187823

================================================================================
CLASS DISTRIBUTION AMONG TOP ANOMALIES
================================================================================

Top 50 anomalies:
       Count  Percentage
class
1          2         4.0
2          1         2.0
3         47        94.0

Top 100 anomalies:
       Count  Percentage
class
1          6         6.0
2          1         1.0
3         93        93.0

Top 500 anomalies:
       Count  Percentage
class
1         46         9.2
2         15         3.0
3        439        87.8

Top 1000 anomalies:
       Count  Percentage
class
1         59         5.9
2         52         5.2
3        889        88.9

Top 5000 anomalies:
       Count  Percentage
class
1        579       11.58
2        111        2.22
3       4310       86.20

================================================================================
CLASS-3 ENRICHMENT
================================================================================
Overall Class-3 percentage: 77.15%
Top    50: Class-3 =    47 ( 94.00%) | Enrichment = 1.218x
Top   100: Class-3 =    93 ( 93.00%) | Enrichment = 1.205x
Top   500: Class-3 =   439 ( 87.80%) | Enrichment = 1.138x
Top  1000: Class-3 =   889 ( 88.90%) | Enrichment = 1.152x
Top  5000: Class-3 =  4310 ( 86.20%) | Enrichment = 1.117x

================================================================================
TEMPORAL ANOMALY ANALYSIS
================================================================================

Most anomalous time steps:
           Transactions  Mean_Anomaly_Score  Median_Anomaly_Score  \
Time step
6                  4328             -0.1525               -0.1821
21                 3537             -0.1460               -0.1721
37                 3306             -0.1443               -0.1763
9                  4996             -0.1443               -0.1721
13                 4528             -0.1438               -0.1744
26                 2523             -0.1426               -0.1755
15                 3639             -0.1425               -0.1744
32                 4525             -0.1417               -0.1763
11                 4296             -0.1411               -0.1708
3                  6621             -0.1398               -0.1789
16                 2975             -0.1394               -0.1718
34                 2486             -0.1384               -0.1697
33                 3151             -0.1373               -0.1631
41                 5342             -0.1350               -0.1699
44                 4975             -0.1341               -0.1759

           Class3_Count  Class3_%
Time step
6                  3843   88.7939
21                 2896   81.8773
37                 2808   84.9365
9                  4218   84.4275
13                 3719   82.1334
26                 2006   79.5085
15                 3021   83.0173
32                 3202   70.7624
11                 3600   83.7989
3                  5342   80.6827
16                 2445   82.1849
34                 1971   79.2840
33                 2710   86.0044
41                 4210   78.8094
44                 3384   68.0201

================================================================================
TEST SET — FINAL UNSUPERVISED ANALYSIS
================================================================================
Test samples: 36824

Test-set anomaly scores by class:
       Samples      Mean       Std       Min    Median       Max
class
1          408 -0.142143  0.044922 -0.187570 -0.164898  0.079297
2         8433 -0.048760  0.108555 -0.187748 -0.067687  0.255413
3        27983 -0.143191  0.071871 -0.187823 -0.176599  0.200976

================================================================================
PIPELINE STATUS
================================================================================
✓ Elliptic++ loaded
✓ 13 selected features
✓ Temporal split preserved
✓ Isolation Forest trained
✓ Anomaly scores generated
✓ Class-wise evaluation completed
✓ Temporal anomaly analysis completed
✓ Test-set analysis completed

NEXT STEP:
Use the output above to decide whether
the anomaly scores meaningfully separate the classes.
================================================================================

In [33]:
# =============================================================================
# BIT-TRACE — CLASS-2-ONLY UNSUPERVISED ANOMALY DETECTION
# =============================================================================
# IMPORTANT:
# - Class labels are NOT used by Isolation Forest during training.
# - Class 2 is used ONLY to define the "known-normal/reference" training pool.
# - Class 1 / Class 2 / Class 3 labels are used AFTER prediction for evaluation.
# - Temporal split:
#       Train      : Time 1–34
#       Validation : Time 35–41
#       Test       : Time 42–49
# =============================================================================

import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    confusion_matrix
)

# =============================================================================
# 1. RECOVER DATA
# =============================================================================

print("=" * 90)
print("BIT-TRACE — CLASS-2-ONLY UNSUPERVISED ANOMALY DETECTION")
print("=" * 90)

# Try to locate the dataframe created by the previous pipeline
if "merged" in globals():
    data = merged.copy()

elif "eval_df" in globals():
    data = eval_df.copy()

else:
    raise NameError(
        "Required dataframe not found. "
        "Run the previous Elliptic++ loading/merging cell first."
    )

print("\n[1] DATA CHECK")
print("-" * 90)

print("Rows:", len(data))
print("Columns:", len(data.columns))

# -------------------------------------------------------------------------
# Detect important columns
# -------------------------------------------------------------------------

tx_col = "txId"

if tx_col not in data.columns:
    raise ValueError("txId column not found.")

if "class" not in data.columns:
    raise ValueError("class column not found.")

if "Time step" not in data.columns:
    raise ValueError("'Time step' column not found.")

print("txId column       :", tx_col)
print("class column      : class")
print("time column       : Time step")


# =============================================================================
# 2. SELECT FEATURES
# =============================================================================

selected_features = [
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_52",
    "Local_feature_59",
    "Aggregate_feature_21",
    "Local_feature_25",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_32",
    "Aggregate_feature_14",
    "Local_feature_22",
    "Local_feature_47"
]

missing_features = [
    f for f in selected_features
    if f not in data.columns
]

if missing_features:
    raise ValueError(
        f"Missing selected features: {missing_features}"
    )

print("\n[2] SELECTED FEATURES")
print("-" * 90)

for i, f in enumerate(selected_features, 1):
    print(f"{i:2d}. {f}")

print("\nNumber of features:", len(selected_features))


# =============================================================================
# 3. CLEAN / SORT DATA
# =============================================================================

data = data.copy()

data["Time step"] = pd.to_numeric(
    data["Time step"],
    errors="coerce"
)

data["class"] = pd.to_numeric(
    data["class"],
    errors="coerce"
)

data = data.dropna(
    subset=["txId", "Time step", "class"]
).copy()

data = data.sort_values(
    ["Time step", "txId"]
).reset_index(drop=True)

print("\n[3] TEMPORAL RANGE")
print("-" * 90)

print("Minimum time step:", data["Time step"].min())
print("Maximum time step:", data["Time step"].max())
print("Unique time steps:", data["Time step"].nunique())


# =============================================================================
# 4. HANDLE FEATURE VALUES
# =============================================================================

X_all = data[selected_features].copy()

X_all = X_all.replace(
    [np.inf, -np.inf],
    np.nan
)

# Median imputation
X_all = X_all.fillna(
    X_all.median()
)

if X_all.isna().sum().sum() != 0:
    raise ValueError("NaN values remain after imputation.")

print("\n[4] FEATURE MATRIX")
print("-" * 90)

print("X shape:", X_all.shape)
print("Remaining NaN:", X_all.isna().sum().sum())
print("Remaining Inf:", np.isinf(X_all.to_numpy()).sum())


# =============================================================================
# 5. TEMPORAL SPLIT
# =============================================================================

train_mask = data["Time step"].between(1, 34)

val_mask = data["Time step"].between(35, 41)

test_mask = data["Time step"].between(42, 49)

print("\n[5] TEMPORAL SPLIT")
print("-" * 90)

print("Train      : Time 1–34")
print("Validation : Time 35–41")
print("Test       : Time 42–49")

print("\nTrain samples      :", train_mask.sum())
print("Validation samples :", val_mask.sum())
print("Test samples       :", test_mask.sum())


# =============================================================================
# 6. CRITICAL STEP:
#    TRAIN ONLY ON CLASS 2 FROM TRAIN PERIOD
# =============================================================================

class2_train_mask = (
    train_mask &
    (data["class"] == 2)
)

X_train_normal = X_all.loc[
    class2_train_mask
].to_numpy()

print("\n[6] CLASS-2-ONLY TRAINING SET")
print("-" * 90)

print("Training samples available:", len(X_train_normal))

print("\nTraining class distribution:")
print(
    data.loc[
        class2_train_mask,
        "class"
    ].value_counts()
)

if len(X_train_normal) == 0:
    raise ValueError(
        "No Class-2 samples found in training period."
    )


# =============================================================================
# 7. TRAIN ISOLATION FOREST
# =============================================================================

print("\n[7] TRAINING ISOLATION FOREST")
print("-" * 90)

model = IsolationForest(
    n_estimators=300,
    max_samples="auto",
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train_normal)

print("✓ Isolation Forest trained")
print("n_estimators :", 300)
print("max_samples  :", "auto")
print("contamination:", "auto")
print("random_state :", 42)


# =============================================================================
# 8. GENERATE SCORES
# =============================================================================
# sklearn:
# decision_function:
#     higher = more normal
#     lower  = more anomalous
#
# We therefore convert it to:
#
# anomaly_score = -decision_function
#
# higher anomaly_score = more anomalous
# =============================================================================

print("\n[8] GENERATING ANOMALY SCORES")
print("-" * 90)

X_train_all = X_all.loc[train_mask].to_numpy()
X_val = X_all.loc[val_mask].to_numpy()
X_test = X_all.loc[test_mask].to_numpy()

train_scores = -model.decision_function(X_train_all)
val_scores = -model.decision_function(X_val)
test_scores = -model.decision_function(X_test)

print("✓ Scores generated")

print("Train:", len(train_scores))
print("Validation:", len(val_scores))
print("Test:", len(test_scores))


# =============================================================================
# 9. ATTACH SCORES
# =============================================================================

data["anomaly_score"] = np.nan

data.loc[train_mask, "anomaly_score"] = train_scores
data.loc[val_mask, "anomaly_score"] = val_scores
data.loc[test_mask, "anomaly_score"] = test_scores

if data["anomaly_score"].isna().any():
    raise ValueError("Some anomaly scores are missing.")

print("\n[9] SCORE ATTACHMENT")
print("-" * 90)

print("✓ All rows have anomaly scores")


# =============================================================================
# 10. SCORE DISTRIBUTION
# =============================================================================

print("\n[10] ANOMALY SCORE DISTRIBUTION")
print("-" * 90)

score_summary = pd.DataFrame({
    "Split": [
        "Train",
        "Validation",
        "Test"
    ],
    "Samples": [
        len(train_scores),
        len(val_scores),
        len(test_scores)
    ],
    "Mean": [
        np.mean(train_scores),
        np.mean(val_scores),
        np.mean(test_scores)
    ],
    "Std": [
        np.std(train_scores),
        np.std(val_scores),
        np.std(test_scores)
    ],
    "Min": [
        np.min(train_scores),
        np.min(val_scores),
        np.min(test_scores)
    ],
    "Median": [
        np.median(train_scores),
        np.median(val_scores),
        np.median(test_scores)
    ],
    "Max": [
        np.max(train_scores),
        np.max(val_scores),
        np.max(test_scores)
    ]
})

print(
    score_summary.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)


# =============================================================================
# 11. CLASS-WISE SCORE DISTRIBUTION
# =============================================================================

print("\n[11] TEST SCORE DISTRIBUTION BY CLASS")
print("-" * 90)

test_data = data.loc[
    test_mask
].copy()

class_score_summary = (
    test_data
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(
    class_score_summary.to_string(
        float_format=lambda x: f"{x:.6f}"
    )
)


# =============================================================================
# 12. CLASS-WISE QUANTILES
# =============================================================================

print("\n[12] TEST SCORE QUANTILES")
print("-" * 90)

quantiles = (
    test_data
    .groupby("class")["anomaly_score"]
    .quantile(
        [0.01, 0.05, 0.10, 0.25,
         0.50, 0.75, 0.90,
         0.95, 0.99]
    )
    .unstack()
)

quantiles.columns = [
    "Q01", "Q05", "Q10",
    "Q25", "Q50", "Q75",
    "Q90", "Q95", "Q99"
]

print(
    quantiles.to_string(
        float_format=lambda x: f"{x:.6f}"
    )
)


# =============================================================================
# 13. BINARY EVALUATION
# =============================================================================
#
# For this experiment:
#
# Class 1 = known illicit
# Class 2 = known licit
#
# Class 3 is deliberately excluded from binary evaluation.
#
# This evaluates whether anomalies are enriched for known illicit
# transactions WITHOUT training on Class-1 labels.
# =============================================================================

binary_test = test_data[
    test_data["class"].isin([1, 2])
].copy()

binary_test["binary_label"] = (
    binary_test["class"] == 1
).astype(int)

y_true = binary_test["binary_label"].to_numpy()
y_score = binary_test["anomaly_score"].to_numpy()

print("\n[13] CLASS 1 vs CLASS 2 — UNSUPERVISED EVALUATION")
print("-" * 90)

print("Class-1 test samples:", (y_true == 1).sum())
print("Class-2 test samples:", (y_true == 0).sum())


# =============================================================================
# 14. ROC-AUC
# =============================================================================

roc_auc = roc_auc_score(
    y_true,
    y_score
)

# PR-AUC
pr_auc = average_precision_score(
    y_true,
    y_score
)

print("\nROC-AUC:", round(roc_auc, 6))
print("PR-AUC :", round(pr_auc, 6))


# =============================================================================
# 15. TOP-K ANALYSIS
# =============================================================================

print("\n[14] TOP-K ANOMALY ANALYSIS")
print("-" * 90)

top_k_values = [
    50,
    100,
    500,
    1000,
    5000
]

# Sort highest anomaly score first
binary_sorted = binary_test.sort_values(
    "anomaly_score",
    ascending=False
).reset_index(drop=True)

total_illicit = (
    binary_sorted["binary_label"] == 1
).sum()

total_licit = (
    binary_sorted["binary_label"] == 0
).sum()

total_binary = len(binary_sorted)

overall_illicit_rate = (
    total_illicit / total_binary
)

results = []

for k in top_k_values:

    k_actual = min(k, len(binary_sorted))

    top = binary_sorted.head(k_actual)

    illicit_count = (
        top["binary_label"] == 1
    ).sum()

    licit_count = (
        top["binary_label"] == 0
    ).sum()

    precision_k = (
        illicit_count / k_actual
    )

    recall_k = (
        illicit_count / total_illicit
        if total_illicit > 0 else np.nan
    )

    enrichment = (
        precision_k / overall_illicit_rate
        if overall_illicit_rate > 0
        else np.nan
    )

    results.append({
        "Top_K": k_actual,
        "Illicit": illicit_count,
        "Licit": licit_count,
        "Illicit_%": precision_k * 100,
        "Recall_%": recall_k * 100,
        "Enrichment_x": enrichment
    })

topk_results = pd.DataFrame(results)

print(
    topk_results.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# =============================================================================
# 16. TOP-K INCLUDING CLASS 3
# =============================================================================

print("\n[15] TOP-K — ALL CLASSES")
print("-" * 90)

all_sorted = test_data.sort_values(
    "anomaly_score",
    ascending=False
).reset_index(drop=True)

all_results = []

for k in top_k_values:

    k_actual = min(k, len(all_sorted))

    top = all_sorted.head(k_actual)

    counts = top["class"].value_counts()

    c1 = counts.get(1, 0)
    c2 = counts.get(2, 0)
    c3 = counts.get(3, 0)

    all_results.append({
        "Top_K": k_actual,
        "Class_1": c1,
        "Class_2": c2,
        "Class_3": c3,
        "Class_1_%": c1 / k_actual * 100,
        "Class_2_%": c2 / k_actual * 100,
        "Class_3_%": c3 / k_actual * 100
    })

all_topk_results = pd.DataFrame(
    all_results
)

print(
    all_topk_results.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# =============================================================================
# 17. CLASS 3 — SEPARATE EXPLORATORY ANALYSIS
# =============================================================================

print("\n[16] CLASS-3 EXPLORATORY ANALYSIS")
print("-" * 90)

class3_test = test_data[
    test_data["class"] == 3
]

class1_test = test_data[
    test_data["class"] == 1
]

class2_test = test_data[
    test_data["class"] == 2
]

print("Class 1:", len(class1_test))
print("Class 2:", len(class2_test))
print("Class 3:", len(class3_test))

print("\nMean anomaly score:")
print("Class 1:", class1_test["anomaly_score"].mean())
print("Class 2:", class2_test["anomaly_score"].mean())
print("Class 3:", class3_test["anomaly_score"].mean())


# =============================================================================
# 18. TOP 30 TEST ANOMALIES
# =============================================================================

print("\n[17] TOP 30 MOST ANOMALOUS TEST TRANSACTIONS")
print("-" * 90)

top30 = test_data.sort_values(
    "anomaly_score",
    ascending=False
).head(30)[
    [
        "txId",
        "Time step",
        "class",
        "anomaly_score"
    ]
]

print(
    top30.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)


# =============================================================================
# 19. TEMPORAL PERFORMANCE — CLASS 1 vs CLASS 2
# =============================================================================

print("\n[18] TEMPORAL CLASS-1 vs CLASS-2 ANALYSIS")
print("-" * 90)

temporal_results = []

for t in sorted(
    binary_test["Time step"].unique()
):

    temp = binary_test[
        binary_test["Time step"] == t
    ]

    if temp["binary_label"].nunique() < 2:
        continue

    try:
        auc = roc_auc_score(
            temp["binary_label"],
            temp["anomaly_score"]
        )
    except:
        auc = np.nan

    temporal_results.append({
        "Time_step": t,
        "Samples": len(temp),
        "Class1": (temp["binary_label"] == 1).sum(),
        "Class2": (temp["binary_label"] == 0).sum(),
        "ROC_AUC": auc,
        "Mean_Score": temp["anomaly_score"].mean()
    })

temporal_results = pd.DataFrame(
    temporal_results
)

print(
    temporal_results.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)


# =============================================================================
# 20. CONFUSION MATRIX AT TOP 5% THRESHOLD
# =============================================================================
#
# This threshold is NOT learned using labels.
# It is simply the top 5% most anomalous transactions in the
# binary test population.
# =============================================================================

print("\n[19] TOP 5% ANOMALY THRESHOLD")
print("-" * 90)

threshold = binary_test[
    "anomaly_score"
].quantile(0.95)

binary_test["predicted_anomaly"] = (
    binary_test["anomaly_score"] >= threshold
).astype(int)

cm = confusion_matrix(
    binary_test["binary_label"],
    binary_test["predicted_anomaly"]
)

tn, fp, fn, tp = cm.ravel()

precision_5 = (
    tp / (tp + fp)
    if (tp + fp) > 0 else 0
)

recall_5 = (
    tp / (tp + fn)
    if (tp + fn) > 0 else 0
)

print("Threshold:", threshold)

print("\nConfusion Matrix:")
print(cm)

print("\nTP:", tp)
print("FP:", fp)
print("TN:", tn)
print("FN:", fn)

print("\nPrecision:", round(precision_5, 6))
print("Recall   :", round(recall_5, 6))


# =============================================================================
# 21. SAVE RESULTS IN MEMORY
# =============================================================================

binary_test_results = binary_test.copy()

test_results = test_data.copy()

print("\n" + "=" * 90)
print("PIPELINE COMPLETE")
print("=" * 90)

print("""
✓ Isolation Forest trained ONLY on Class 2 / Time 1–34
✓ Class-1 labels NOT used during training
✓ Temporal validation preserved
✓ Temporal test preserved
✓ ROC-AUC calculated
✓ PR-AUC calculated
✓ Top-K illicit enrichment calculated
✓ Class-3 separately analysed
✓ Temporal performance calculated
✓ Top anomalies extracted

IMPORTANT:
Class 1 / Class 2 metrics are external evaluation only.
Class 3 remains an exploratory/unknown population.
""")

print("=" * 90)

==========================================================================================
BIT-TRACE — CLASS-2-ONLY UNSUPERVISED ANOMALY DETECTION
==========================================================================================

[1] DATA CHECK
------------------------------------------------------------------------------------------
Rows: 203769
Columns: 4
txId column       : txId
class column      : class
time column       : Time step

ValueError: Missing selected features: ['Local_feature_53', 'Local_feature_54', 'Local_feature_52', 'Local_feature_59', 'Aggregate_feature_21', 'Local_feature_25', 'Local_feature_77', 'Local_feature_89', 'Local_feature_90', 'Aggregate_feature_32', 'Aggregate_feature_14', 'Local_feature_22', 'Local_feature_47']

In [35]:
# ============================================================
# BIT-TRACE — RECOVER FINAL ELLIPTIC++ MODEL DATA
# ============================================================

import os
import numpy as np
import pandas as pd

print("=" * 80)
print("RECOVERING FINAL ELLIPTIC++ MODEL DATA")
print("=" * 80)

# ------------------------------------------------------------
# 1. SELECTED FEATURES
# ------------------------------------------------------------

SELECTED_FEATURES = [
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_52",
    "Local_feature_59",
    "Aggregate_feature_21",
    "Local_feature_25",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_32",
    "Aggregate_feature_14",
    "Local_feature_22",
    "Local_feature_47"
]

print("\n[1] Selected features:", len(SELECTED_FEATURES))

for i, f in enumerate(SELECTED_FEATURES, 1):
    print(f"{i:2}. {f}")


# ------------------------------------------------------------
# 2. FIND FILES
# ------------------------------------------------------------

possible_feature_paths = [
    "txs_features.csv",
    "./txs_features.csv",
    "EllipticPlusPlus/Transactions Dataset/txs_features.csv",
    "data/EllipticPlusPlus/Transactions Dataset/txs_features.csv",
    "data/raw/EllipticPlusPlus/Transactions Dataset/txs_features.csv",
]

possible_class_paths = [
    "txs_classes.csv",
    "./txs_classes.csv",
    "EllipticPlusPlus/Transactions Dataset/txs_classes.csv",
    "data/EllipticPlusPlus/Transactions Dataset/txs_classes.csv",
    "data/raw/EllipticPlusPlus/Transactions Dataset/txs_classes.csv",
]

feature_path = next(
    (p for p in possible_feature_paths if os.path.exists(p)),
    None
)

class_path = next(
    (p for p in possible_class_paths if os.path.exists(p)),
    None
)

print("\n[2] FILE CHECK")

if feature_path is None:
    raise FileNotFoundError(
        "txs_features.csv not found. "
        "Run: !dir /s /b txs_features.csv"
    )

if class_path is None:
    raise FileNotFoundError(
        "txs_classes.csv not found. "
        "Run: !dir /s /b txs_classes.csv"
    )

print("Feature file:", feature_path)
print("Class file  :", class_path)


# ------------------------------------------------------------
# 3. READ CLASS FILE
# ------------------------------------------------------------

print("\n[3] LOADING CLASS DATA")
print("-" * 80)

classes = pd.read_csv(class_path)

print("Shape:", classes.shape)
print("Columns:", classes.columns.tolist())

if "txId" not in classes.columns:
    raise ValueError("txId not found in class file.")

if "class" not in classes.columns:
    raise ValueError("class not found in class file.")

classes["txId"] = pd.to_numeric(
    classes["txId"],
    errors="coerce"
)

print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())


# ------------------------------------------------------------
# 4. READ ONLY REQUIRED FEATURE COLUMNS
# ------------------------------------------------------------

print("\n[4] READING FEATURE DATA")
print("-" * 80)

# First read only header
header = pd.read_csv(
    feature_path,
    nrows=0
)

all_columns = header.columns.tolist()

print("Total columns in raw feature file:", len(all_columns))

required_columns = [
    "txId",
    "Time step"
] + SELECTED_FEATURES

missing = [
    c for c in required_columns
    if c not in all_columns
]

if missing:
    raise ValueError(
        "These columns are NOT present in txs_features.csv:\n"
        + "\n".join(missing)
    )

print("All 13 selected features found ✓")

# Read only required columns
features = pd.read_csv(
    feature_path,
    usecols=required_columns
)

print("Loaded feature shape:", features.shape)


# ------------------------------------------------------------
# 5. BASIC CLEANING
# ------------------------------------------------------------

print("\n[5] BASIC CLEANING")
print("-" * 80)

features["txId"] = pd.to_numeric(
    features["txId"],
    errors="coerce"
)

features["Time step"] = pd.to_numeric(
    features["Time step"],
    errors="coerce"
)

print("Missing txId:", features["txId"].isna().sum())
print("Missing Time step:", features["Time step"].isna().sum())

# Remove rows without identifiers/time
features = features.dropna(
    subset=["txId", "Time step"]
).copy()

# Ensure numeric features are numeric
for f in SELECTED_FEATURES:
    features[f] = pd.to_numeric(
        features[f],
        errors="coerce"
    )


# ------------------------------------------------------------
# 6. MERGE FEATURES + CLASSES
# ------------------------------------------------------------

print("\n[6] MERGING FEATURES + CLASSES")
print("-" * 80)

data = features.merge(
    classes[["txId", "class"]],
    on="txId",
    how="inner",
    validate="one_to_one"
)

print("Merged shape:", data.shape)

print("Missing labels:", data["class"].isna().sum())

print("\nClass distribution:")
print(data["class"].value_counts().sort_index())


# ------------------------------------------------------------
# 7. CLEAN NaN / INF
# ------------------------------------------------------------

print("\n[7] FEATURE QUALITY")
print("-" * 80)

X_raw = data[SELECTED_FEATURES].copy()

# Replace inf with NaN
X_raw = X_raw.replace(
    [np.inf, -np.inf],
    np.nan
)

nan_before = int(X_raw.isna().sum().sum())

print("NaN/Inf values before imputation:", nan_before)

# Median imputation
for f in SELECTED_FEATURES:
    median_value = X_raw[f].median()

    X_raw[f] = X_raw[f].fillna(
        median_value
    )

nan_after = int(X_raw.isna().sum().sum())

print("NaN values after imputation:", nan_after)


# ------------------------------------------------------------
# 8. FINAL MATRIX
# ------------------------------------------------------------

X_all = X_raw.to_numpy(
    dtype=np.float32
)

y_all = data["class"].to_numpy()

time_steps = data["Time step"].to_numpy()

tx_ids = data["txId"].to_numpy()


# ------------------------------------------------------------
# 9. TEMPORAL SPLIT
# ------------------------------------------------------------

print("\n[8] TEMPORAL SPLIT")
print("-" * 80)

train_idx = np.where(
    time_steps <= 34
)[0]

val_idx = np.where(
    (time_steps >= 35) &
    (time_steps <= 41)
)[0]

test_idx = np.where(
    time_steps >= 42
)[0]

print("Train samples:", len(train_idx))
print("Validation samples:", len(val_idx))
print("Test samples:", len(test_idx))


# ------------------------------------------------------------
# 10. FINAL VALIDATION
# ------------------------------------------------------------

print("\n[9] FINAL OBJECT VALIDATION")
print("-" * 80)

print("X_all shape      :", X_all.shape)
print("y_all shape      :", y_all.shape)
print("time_steps shape :", time_steps.shape)
print("tx_ids shape     :", tx_ids.shape)

print("\nTime range:")
print("Min:", time_steps.min())
print("Max:", time_steps.max())

print("\nSelected features:", X_all.shape[1])

print("\nClass distribution:")
print(
    pd.Series(y_all)
    .value_counts()
    .sort_index()
)

print("\nTemporal split:")
print("Train:", len(train_idx))
print("Val  :", len(val_idx))
print("Test :", len(test_idx))

assert X_all.shape[0] == len(y_all)
assert X_all.shape[0] == len(time_steps)
assert X_all.shape[0] == len(tx_ids)

assert len(train_idx) + len(val_idx) + len(test_idx) == len(X_all)

assert not np.isnan(X_all).any()
assert not np.isinf(X_all).any()

print("\n" + "=" * 80)
print("✓ X_all CREATED SUCCESSFULLY")
print("✓ y_all CREATED SUCCESSFULLY")
print("✓ time_steps CREATED SUCCESSFULLY")
print("✓ tx_ids CREATED SUCCESSFULLY")
print("✓ train_idx CREATED SUCCESSFULLY")
print("✓ val_idx CREATED SUCCESSFULLY")
print("✓ test_idx CREATED SUCCESSFULLY")
print("=" * 80)

================================================================================
RECOVERING FINAL ELLIPTIC++ MODEL DATA
================================================================================

[1] Selected features: 13
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47

[2] FILE CHECK

FileNotFoundError: txs_features.csv not found. Run: !dir /s /b txs_features.csv

In [36]:
# ============================================================
# BIT-TRACE — FIND ELLIPTIC++ FILES AUTOMATICALLY
# ============================================================

from pathlib import Path

print("=" * 80)
print("SEARCHING FOR ELLIPTIC++ FILES")
print("=" * 80)

# Current working directory
cwd = Path.cwd()

print("\nCurrent notebook working directory:")
print(cwd)

print("\nSearching recursively...")

# Search from current directory
feature_matches = list(cwd.rglob("txs_features.csv"))
class_matches   = list(cwd.rglob("txs_classes.csv"))
edge_matches    = list(cwd.rglob("txs_edgelist.csv"))

print("\nFound txs_features.csv:")
for p in feature_matches:
    print(" ", p)

print("\nFound txs_classes.csv:")
for p in class_matches:
    print(" ", p)

print("\nFound txs_edgelist.csv:")
for p in edge_matches:
    print(" ", p)


# ------------------------------------------------------------
# ALSO CHECK DESKTOP / PROJECT LOCATION
# ------------------------------------------------------------

desktop = Path.home() / "Desktop"

if desktop.exists():

    print("\n" + "-" * 80)
    print("SEARCHING DESKTOP")
    print("-" * 80)

    desktop_features = list(desktop.rglob("txs_features.csv"))
    desktop_classes   = list(desktop.rglob("txs_classes.csv"))
    desktop_edges     = list(desktop.rglob("txs_edgelist.csv"))

    for p in desktop_features:
        if p not in feature_matches:
            feature_matches.append(p)

    for p in desktop_classes:
        if p not in class_matches:
            class_matches.append(p)

    for p in desktop_edges:
        if p not in edge_matches:
            edge_matches.append(p)


# ------------------------------------------------------------
# FINAL RESULT
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("FINAL FILE LOCATIONS")
print("=" * 80)

print("\nFEATURE:")
if feature_matches:
    print(feature_matches[0])
else:
    print("NOT FOUND")

print("\nCLASS:")
if class_matches:
    print(class_matches[0])
else:
    print("NOT FOUND")

print("\nEDGELIST:")
if edge_matches:
    print(edge_matches[0])
else:
    print("NOT FOUND")


# ------------------------------------------------------------
# STOP IF FILES ARE MISSING
# ------------------------------------------------------------

if not feature_matches or not class_matches:
    print("\n" + "=" * 80)
    print("FILES NOT FOUND")
    print("=" * 80)

    print("""
Python cannot currently see the Elliptic++ CSV files.

If these files exist in VS Code Explorer, check that the notebook
kernel is running from the same machine/environment.

DO NOT move or copy the 600+ MB dataset yet.
Just send me the output of this cell.
""")

else:

    FEATURE_PATH = feature_matches[0]
    CLASS_PATH   = class_matches[0]

    print("\n✓ FEATURE_PATH =", FEATURE_PATH)
    print("✓ CLASS_PATH   =", CLASS_PATH)

================================================================================
SEARCHING FOR ELLIPTIC++ FILES
================================================================================

Current notebook working directory:
c:\Users\YASHIKA\Desktop\bit-trace\src

Searching recursively...

Found txs_features.csv:

Found txs_classes.csv:

Found txs_edgelist.csv:

--------------------------------------------------------------------------------
SEARCHING DESKTOP
--------------------------------------------------------------------------------

================================================================================
FINAL FILE LOCATIONS
================================================================================

FEATURE:
C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv

CLASS:
C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv

EDGELIST:
C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv

✓ FEATURE_PATH = C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv
✓ CLASS_PATH   = C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv

In [37]:
# ============================================================
# BIT-TRACE — ELLIPTIC++ FINAL UNSUPERVISED PIPELINE
# ============================================================
# Purpose:
#   1. Load Elliptic++ transaction data
#   2. Select previously validated 13 features
#   3. Clean + impute
#   4. Preserve temporal ordering
#   5. Temporal train/validation/test split
#   6. Train Isolation Forest ONLY on train data
#   7. Generate anomaly scores
#   8. Evaluate anomaly enrichment using labels ONLY AFTER training
#   9. Analyse test set
#  10. Save final anomaly results
#
# IMPORTANT:
# Labels are NEVER used to train Isolation Forest.
# ============================================================

import os
import warnings
import numpy as np
import pandas as pd

from pathlib import Path
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

warnings.filterwarnings("ignore")

print("=" * 80)
print("BIT-TRACE — ELLIPTIC++ FINAL UNSUPERVISED ANOMALY PIPELINE")
print("=" * 80)


# ============================================================
# 1. EXACT DATA PATHS
# ============================================================

FEATURE_PATH = Path(
    r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv"
)

CLASS_PATH = Path(
    r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv"
)

EDGE_PATH = Path(
    r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv"
)

print("\n[1] PATH CHECK")
print("-" * 80)

print("Feature file:", FEATURE_PATH.exists())
print("Class file:  ", CLASS_PATH.exists())
print("Edge file:   ", EDGE_PATH.exists())

if not FEATURE_PATH.exists():
    raise FileNotFoundError(f"Feature file not found:\n{FEATURE_PATH}")

if not CLASS_PATH.exists():
    raise FileNotFoundError(f"Class file not found:\n{CLASS_PATH}")


# ============================================================
# 2. SELECTED FEATURES
# ============================================================

SELECTED_FEATURES = [
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_52",
    "Local_feature_59",
    "Aggregate_feature_21",
    "Local_feature_25",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_32",
    "Aggregate_feature_14",
    "Local_feature_22",
    "Local_feature_47",
]

print("\n[2] SELECTED FEATURES")
print("-" * 80)

for i, f in enumerate(SELECTED_FEATURES, 1):
    print(f"{i:2d}. {f}")

print("Number of features:", len(SELECTED_FEATURES))


# ============================================================
# 3. LOAD CLASS DATA
# ============================================================

print("\n[3] LOADING CLASS DATA")
print("-" * 80)

classes = pd.read_csv(CLASS_PATH)

print("Shape:", classes.shape)
print("Columns:", classes.columns.tolist())

# Standardize column names if necessary
classes.columns = [str(c).strip() for c in classes.columns]

if "txId" not in classes.columns:
    raise ValueError(
        f"txId not found in class file. Columns:\n{classes.columns.tolist()}"
    )

if "class" not in classes.columns:
    raise ValueError(
        f"class not found in class file. Columns:\n{classes.columns.tolist()}"
    )

print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())


# ============================================================
# 4. READ FEATURE HEADER FIRST
# ============================================================

print("\n[4] READING FEATURE HEADER")
print("-" * 80)

header = pd.read_csv(
    FEATURE_PATH,
    nrows=0
)

header.columns = [str(c).strip() for c in header.columns]

print("Total columns:", len(header.columns))

# Detect identifiers
if "txId" in header.columns:
    TX_COL = "txId"
else:
    raise ValueError("txId column not found.")

if "Time step" in header.columns:
    TIME_COL = "Time step"
elif "time_step" in header.columns:
    TIME_COL = "time_step"
else:
    raise ValueError("Time step column not found.")

print("Transaction ID:", TX_COL)
print("Time column:", TIME_COL)


# ============================================================
# 5. VERIFY SELECTED FEATURES
# ============================================================

print("\n[5] VERIFYING SELECTED FEATURES")
print("-" * 80)

missing_features = [
    f for f in SELECTED_FEATURES
    if f not in header.columns
]

if missing_features:
    raise ValueError(
        "Selected features missing from txs_features.csv:\n"
        + "\n".join(missing_features)
    )

print("✓ All 13 selected features exist.")


# ============================================================
# 6. LOAD ONLY REQUIRED COLUMNS
# ============================================================

required_columns = [
    TX_COL,
    TIME_COL,
] + SELECTED_FEATURES

print("\n[6] LOADING REQUIRED FEATURE COLUMNS")
print("-" * 80)

print("Columns loaded:", len(required_columns))

features = pd.read_csv(
    FEATURE_PATH,
    usecols=required_columns
)

features.columns = [str(c).strip() for c in features.columns]

print("Loaded shape:", features.shape)


# ============================================================
# 7. BASIC CLEANING
# ============================================================

print("\n[7] BASIC DATA CLEANING")
print("-" * 80)

features[TX_COL] = pd.to_numeric(
    features[TX_COL],
    errors="coerce"
)

features[TIME_COL] = pd.to_numeric(
    features[TIME_COL],
    errors="coerce"
)

print("Missing txId:", features[TX_COL].isna().sum())
print("Missing time:", features[TIME_COL].isna().sum())

if features[TX_COL].isna().any():
    raise ValueError("Missing transaction IDs detected.")

if features[TIME_COL].isna().any():
    raise ValueError("Missing time steps detected.")


# ============================================================
# 8. MERGE FEATURES + LABELS
# ============================================================

print("\n[8] MERGING FEATURES + LABELS")
print("-" * 80)

data = features.merge(
    classes[[TX_COL, "class"]],
    on=TX_COL,
    how="inner",
    validate="one_to_one"
)

print("Merged shape:", data.shape)

if len(data) != len(features):
    print(
        "WARNING: Some feature rows did not match class labels."
    )

print("Missing labels:", data["class"].isna().sum())

if data["class"].isna().any():
    raise ValueError("Missing class labels after merge.")

print("\nClass distribution:")
print(data["class"].value_counts().sort_index())


# ============================================================
# 9. SORT TEMPORALLY
# ============================================================

print("\n[9] TEMPORAL ORDERING")
print("-" * 80)

data = data.sort_values(
    [TIME_COL, TX_COL]
).reset_index(drop=True)

time_steps = data[TIME_COL].to_numpy()

print("Minimum time step:", time_steps.min())
print("Maximum time step:", time_steps.max())
print("Unique time steps:", data[TIME_COL].nunique())


# ============================================================
# 10. CREATE FEATURE MATRIX
# ============================================================

X_raw = data[SELECTED_FEATURES].copy()

# Convert everything to numeric
for col in SELECTED_FEATURES:
    X_raw[col] = pd.to_numeric(
        X_raw[col],
        errors="coerce"
    )

X_raw = X_raw.replace(
    [np.inf, -np.inf],
    np.nan
)

print("\n[10] DATA QUALITY")
print("-" * 80)

nan_total = int(X_raw.isna().sum().sum())
inf_total = int(
    np.isinf(X_raw.to_numpy()).sum()
)

print("Total NaN:", nan_total)
print("Total Inf:", inf_total)


# ============================================================
# 11. MEDIAN IMPUTATION
# ============================================================

print("\n[11] MEDIAN IMPUTATION")
print("-" * 80)

imputer = SimpleImputer(
    strategy="median"
)

X_imputed = imputer.fit_transform(X_raw)

print("Shape:", X_imputed.shape)
print(
    "Remaining NaN:",
    np.isnan(X_imputed).sum()
)


# ============================================================
# 12. TEMPORAL SPLIT
# ============================================================
# Train      : 1–34
# Validation : 35–41
# Test       : 42–49
#
# IMPORTANT:
# The split is based ONLY on time.
# ============================================================

print("\n[12] TEMPORAL SPLIT")
print("-" * 80)

train_idx = np.where(
    time_steps <= 34
)[0]

val_idx = np.where(
    (time_steps >= 35) &
    (time_steps <= 41)
)[0]

test_idx = np.where(
    time_steps >= 42
)[0]

print(
    f"Train samples:      {len(train_idx):,}"
)

print(
    f"Validation samples: {len(val_idx):,}"
)

print(
    f"Test samples:       {len(test_idx):,}"
)

print(
    "Total:",
    len(train_idx) +
    len(val_idx) +
    len(test_idx)
)


# ============================================================
# 13. SCALE FEATURES
# ============================================================
# Fit scaler ONLY on training data.
# ============================================================

print("\n[13] FEATURE SCALING")
print("-" * 80)

scaler = StandardScaler()

X_train = scaler.fit_transform(
    X_imputed[train_idx]
)

X_val = scaler.transform(
    X_imputed[val_idx]
)

X_test = scaler.transform(
    X_imputed[test_idx]
)

print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)


# ============================================================
# 14. ISOLATION FOREST
# ============================================================

print("\n[14] TRAINING ISOLATION FOREST")
print("-" * 80)

print("Training data:", X_train.shape)

# contamination='auto':
# Let Isolation Forest determine the threshold internally.
#
# n_estimators=300:
# More stable than a very small forest.
#
# n_jobs=-1:
# Use all CPU cores.

iso_forest = IsolationForest(
    n_estimators=300,
    contamination="auto",
    max_samples="auto",
    max_features=1.0,
    random_state=42,
    n_jobs=-1
)

iso_forest.fit(X_train)

print("✓ Isolation Forest training complete.")


# ============================================================
# 15. GENERATE SCORES
# ============================================================
# sklearn:
# decision_function()
# larger = more normal
# smaller = more anomalous
#
# For BIT-TRACE:
# anomaly_score = -decision_function()
# larger = more anomalous
# ============================================================

print("\n[15] GENERATING ANOMALY SCORES")
print("-" * 80)

train_scores = -iso_forest.decision_function(X_train)
val_scores = -iso_forest.decision_function(X_val)
test_scores = -iso_forest.decision_function(X_test)

print("✓ Scores generated.")


# ============================================================
# 16. SCORE DISTRIBUTION
# ============================================================

print("\n[16] ANOMALY SCORE DISTRIBUTION")
print("-" * 80)

score_summary = pd.DataFrame({
    "Split": [
        "Train",
        "Validation",
        "Test"
    ],
    "Samples": [
        len(train_scores),
        len(val_scores),
        len(test_scores)
    ],
    "Mean_Score": [
        np.mean(train_scores),
        np.mean(val_scores),
        np.mean(test_scores)
    ],
    "Std_Score": [
        np.std(train_scores),
        np.std(val_scores),
        np.std(test_scores)
    ],
    "Min_Score": [
        np.min(train_scores),
        np.min(val_scores),
        np.min(test_scores)
    ],
    "Median_Score": [
        np.median(train_scores),
        np.median(val_scores),
        np.median(test_scores)
    ],
    "Max_Score": [
        np.max(train_scores),
        np.max(val_scores),
        np.max(test_scores)
    ]
})

print(
    score_summary.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)


# ============================================================
# 17. BUILD EVALUATION DATAFRAME
# ============================================================

print("\n[17] BUILDING EVALUATION DATA")
print("-" * 80)

eval_df = data[
    [TX_COL, TIME_COL, "class"]
].copy()

eval_df["split"] = "unknown"
eval_df["anomaly_score"] = np.nan

eval_df.loc[
    train_idx,
    "split"
] = "train"

eval_df.loc[
    val_idx,
    "split"
] = "validation"

eval_df.loc[
    test_idx,
    "split"
] = "test"

eval_df.loc[
    train_idx,
    "anomaly_score"
] = train_scores

eval_df.loc[
    val_idx,
    "anomaly_score"
] = val_scores

eval_df.loc[
    test_idx,
    "anomaly_score"
] = test_scores

print(
    "Missing anomaly scores:",
    eval_df["anomaly_score"].isna().sum()
)


# ============================================================
# 18. CLASS-WISE ANALYSIS
# ============================================================
# IMPORTANT:
# This is evaluation only.
# Labels were NOT used during training.
# ============================================================

print("\n" + "=" * 80)
print("CLASS-WISE UNSUPERVISED ANOMALY ANALYSIS")
print("=" * 80)

class_summary = (
    eval_df
    .groupby("class")["anomaly_score"]
    .agg([
        "count",
        "mean",
        "std",
        "min",
        "median",
        "max"
    ])
)

print(
    class_summary.to_string(
        float_format=lambda x: f"{x:.6f}"
    )
)


# ============================================================
# 19. QUANTILES
# ============================================================

print("\n" + "=" * 80)
print("CLASS-WISE SCORE QUANTILES")
print("=" * 80)

quantiles = (
    eval_df
    .groupby("class")["anomaly_score"]
    .quantile(
        [
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
    .unstack()
)

quantiles.columns = [
    "Q01",
    "Q05",
    "Q10",
    "Q25",
    "Q50",
    "Q75",
    "Q90",
    "Q95",
    "Q99"
]

print(
    quantiles.to_string(
        float_format=lambda x: f"{x:.6f}"
    )
)


# ============================================================
# 20. TOP ANOMALIES
# ============================================================

print("\n" + "=" * 80)
print("TOP 100 MOST ANOMALOUS TRANSACTIONS")
print("=" * 80)

top_100 = (
    eval_df
    .sort_values(
        "anomaly_score",
        ascending=False
    )
    .head(100)
)

print(
    top_100[
        [TX_COL, TIME_COL, "class", "split", "anomaly_score"]
    ].head(30).to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)


# ============================================================
# 21. TOP-K CLASS DISTRIBUTION
# ============================================================

print("\n" + "=" * 80)
print("CLASS DISTRIBUTION AMONG TOP ANOMALIES")
print("=" * 80)

overall_class3_pct = (
    (eval_df["class"] == 3).mean() * 100
)

for k in [50, 100, 500, 1000, 5000]:

    top_k = (
        eval_df
        .nlargest(
            min(k, len(eval_df)),
            "anomaly_score"
        )
    )

    counts = (
        top_k["class"]
        .value_counts()
        .sort_index()
    )

    print(f"\nTop {k:,} anomalies")

    print(
        counts.to_string()
    )

    print("\nPercentages:")

    print(
        (
            counts / len(top_k) * 100
        ).round(2).to_string()
    )

    class3_count = (
        top_k["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / len(top_k) * 100
    )

    enrichment = (
        class3_pct /
        overall_class3_pct
    )

    print(
        f"Class-3: {class3_pct:.2f}%"
    )

    print(
        f"Class-3 enrichment: {enrichment:.3f}x"
    )


# ============================================================
# 22. TEMPORAL ANOMALY ANALYSIS
# ============================================================

print("\n" + "=" * 80)
print("TEMPORAL ANOMALY ANALYSIS")
print("=" * 80)

temporal_summary = (
    eval_df
    .groupby(TIME_COL)
    .agg(
        Transactions=(TX_COL, "count"),
        Mean_Anomaly_Score=(
            "anomaly_score",
            "mean"
        ),
        Median_Anomaly_Score=(
            "anomaly_score",
            "median"
        ),
        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal_summary["Class3_%"] = (
    temporal_summary["Class3_Count"] /
    temporal_summary["Transactions"] *
    100
)

# Higher anomaly score = more anomalous
temporal_summary = temporal_summary.sort_values(
    "Mean_Anomaly_Score",
    ascending=False
)

print(
    temporal_summary.head(15).to_string(
        float_format=lambda x: f"{x:.4f}"
    )
)


# ============================================================
# 23. TEST SET ANALYSIS
# ============================================================

print("\n" + "=" * 80)
print("TEST SET — FINAL UNSUPERVISED ANALYSIS")
print("=" * 80)

test_eval = eval_df[
    eval_df["split"] == "test"
].copy()

print(
    "Test samples:",
    len(test_eval)
)

test_class_summary = (
    test_eval
    .groupby("class")["anomaly_score"]
    .agg([
        "count",
        "mean",
        "std",
        "min",
        "median",
        "max"
    ])
)

print(
    "\nTest-set anomaly scores by class:"
)

print(
    test_class_summary.to_string(
        float_format=lambda x: f"{x:.6f}"
    )
)


# ============================================================
# 24. TEST TOP ANOMALIES
# ============================================================

print("\n" + "=" * 80)
print("TEST SET — TOP 50 ANOMALOUS TRANSACTIONS")
print("=" * 80)

test_top50 = (
    test_eval
    .nlargest(
        50,
        "anomaly_score"
    )
)

print(
    test_top50[
        [TX_COL, TIME_COL, "class", "anomaly_score"]
    ].to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)


# ============================================================
# 25. SAVE RESULTS
# ============================================================

print("\n" + "=" * 80)
print("SAVING RESULTS")
print("=" * 80)

RESULTS_DIR = (
    Path.cwd().parent /
    "results" /
    "elliptic_unsupervised"
)

RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Complete anomaly results
results_path = (
    RESULTS_DIR /
    "elliptic_transaction_anomaly_scores.csv"
)

eval_df.to_csv(
    results_path,
    index=False
)

# Top anomalies
top_path = (
    RESULTS_DIR /
    "top_100_anomalous_transactions.csv"
)

top_100.to_csv(
    top_path,
    index=False
)

# Temporal summary
temporal_path = (
    RESULTS_DIR /
    "temporal_anomaly_summary.csv"
)

temporal_summary.to_csv(
    temporal_path
)

# Class summary
class_path = (
    RESULTS_DIR /
    "class_anomaly_summary.csv"
)

class_summary.to_csv(
    class_path
)

print("✓ Results saved:")
print(results_path)
print(top_path)
print(temporal_path)
print(class_path)


# ============================================================
# 26. FINAL PIPELINE STATUS
# ============================================================

print("\n" + "=" * 80)
print("PIPELINE STATUS")
print("=" * 80)

print("✓ Elliptic++ transaction data loaded")
print("✓ 13 previously selected features verified")
print("✓ Temporal ordering preserved")
print("✓ Median imputation performed")
print("✓ Scaler fitted only on training period")
print("✓ Temporal train/validation/test split")
print("✓ Isolation Forest trained without labels")
print("✓ Anomaly scores generated")
print("✓ Class-wise evaluation performed AFTER training")
print("✓ Top anomaly analysis completed")
print("✓ Temporal anomaly analysis completed")
print("✓ Test-set analysis completed")
print("✓ Results exported")

print("\nIMPORTANT:")
print("Class labels were used ONLY for post-training evaluation.")
print("They were NOT used to fit Isolation Forest.")

print("\nDone.")

================================================================================
BIT-TRACE — ELLIPTIC++ FINAL UNSUPERVISED ANOMALY PIPELINE
================================================================================

[1] PATH CHECK
--------------------------------------------------------------------------------
Feature file: True
Class file:   True
Edge file:    True

[2] SELECTED FEATURES
--------------------------------------------------------------------------------
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47
Number of features: 13

[3] LOADING CLASS DATA
--------------------------------------------------------------------------------
Shape: (203769, 2)
Columns: ['txId', 'class']

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[4] READING FEATURE HEADER
--------------------------------------------------------------------------------
Total columns: 184
Transaction ID: txId
Time column: Time step

[5] VERIFYING SELECTED FEATURES
--------------------------------------------------------------------------------
✓ All 13 selected features exist.

[6] LOADING REQUIRED FEATURE COLUMNS
--------------------------------------------------------------------------------
Columns loaded: 15
Loaded shape: (203769, 15)

[7] BASIC DATA CLEANING
--------------------------------------------------------------------------------
Missing txId: 0
Missing time: 0

[8] MERGING FEATURES + LABELS
--------------------------------------------------------------------------------
Merged shape: (203769, 16)
Missing labels: 0

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[9] TEMPORAL ORDERING
--------------------------------------------------------------------------------
Minimum time step: 1
Maximum time step: 49
Unique time steps: 49

[10] DATA QUALITY
--------------------------------------------------------------------------------
Total NaN: 0
Total Inf: 0

[11] MEDIAN IMPUTATION
--------------------------------------------------------------------------------
Shape: (203769, 13)
Remaining NaN: 0

[12] TEMPORAL SPLIT
--------------------------------------------------------------------------------
Train samples:      136,265
Validation samples: 30,680
Test samples:       36,824
Total: 203769

[13] FEATURE SCALING
--------------------------------------------------------------------------------
Train: (136265, 13)
Validation: (30680, 13)
Test: (36824, 13)

[14] TRAINING ISOLATION FOREST
--------------------------------------------------------------------------------
Training data: (136265, 13)
✓ Isolation Forest training complete.

[15] GENERATING ANOMALY SCORES
--------------------------------------------------------------------------------
✓ Scores generated.

[16] ANOMALY SCORE DISTRIBUTION
--------------------------------------------------------------------------------
     Split  Samples  Mean_Score  Std_Score  Min_Score  Median_Score  Max_Score
     Train   136265   -0.126634   0.088412  -0.187496     -0.167634   0.269425
Validation    30680   -0.123508   0.089126  -0.187376     -0.168620   0.253244
      Test    36824   -0.121408   0.090947  -0.187426     -0.166967   0.252861

[17] BUILDING EVALUATION DATA
--------------------------------------------------------------------------------
Missing anomaly scores: 0

================================================================================
CLASS-WISE UNSUPERVISED ANOMALY ANALYSIS
================================================================================
        count      mean      std       min    median      max
class
1        4545 -0.161359 0.044723 -0.187403 -0.185107 0.114558
2       42019 -0.028003 0.117372 -0.187426 -0.039506 0.269425
3      157205 -0.150159 0.057820 -0.187496 -0.175841 0.206078

================================================================================
CLASS-WISE SCORE QUANTILES
================================================================================
            Q01       Q05       Q10       Q25       Q50       Q75       Q90       Q95       Q99
class
1     -0.187378 -0.187275 -0.187251 -0.187008 -0.185107 -0.161248 -0.061150 -0.059473 -0.044410
2     -0.186541 -0.185778 -0.182066 -0.133463 -0.039506  0.062552  0.135729  0.169319  0.202175
3     -0.187251 -0.187205 -0.186403 -0.184669 -0.175841 -0.139089 -0.079434 -0.035212  0.102061

================================================================================
TOP 100 MOST ANOMALOUS TRANSACTIONS
================================================================================
     txId  Time step  class      split  anomaly_score
180525719         31      2      train       0.269425
 88142087         26      2      train       0.267342
 72444066         30      2      train       0.266762
156795980         32      2      train       0.266416
 92713387         33      2      train       0.254171
  7951587         40      2 validation       0.253244
   971497         42      2       test       0.252861
  8823943         41      2 validation       0.252692
 12781680         41      2 validation       0.252522
 12663816         41      2 validation       0.252522
 18918220         47      2       test       0.252416
 65381198         42      2       test       0.252013
 99332126         34      2      train       0.252013
164687671         45      2       test       0.251354
 34717366         42      2       test       0.251335
 14182114         39      2 validation       0.251165
 12661079         41      2 validation       0.251165
  6243976         46      2       test       0.250720
 92738855         43      2       test       0.249931
  6060482         38      2 validation       0.249381
156303533         45      2       test       0.249323
 53450313         43      2       test       0.249009
 91882365         43      2       test       0.248671
 29140182         37      2 validation       0.247996
 39393441         47      2       test       0.247879
157243941         45      2       test       0.247164
 28468985         44      2       test       0.246901
 43396863         35      2 validation       0.246843
108353956         45      2       test       0.245796
164687321         45      2       test       0.243843

================================================================================
CLASS DISTRIBUTION AMONG TOP ANOMALIES
================================================================================

Top 50 anomalies
class
2    50

Percentages:
class
2    100.0
Class-3: 0.00%
Class-3 enrichment: 0.000x

Top 100 anomalies
class
2    100

Percentages:
class
2    100.0
Class-3: 0.00%
Class-3 enrichment: 0.000x

Top 500 anomalies
class
2    498
3      2

Percentages:
class
2    99.6
3     0.4
Class-3: 0.40%
Class-3 enrichment: 0.005x

Top 1,000 anomalies
class
2    988
3     12

Percentages:
class
2    98.8
3     1.2
Class-3: 1.20%
Class-3 enrichment: 0.016x

Top 5,000 anomalies
class
2    3686
3    1314

Percentages:
class
2    73.72
3    26.28
Class-3: 26.28%
Class-3 enrichment: 0.341x

================================================================================
TEMPORAL ANOMALY ANALYSIS
================================================================================
           Transactions  Mean_Anomaly_Score  Median_Anomaly_Score  Class3_Count  Class3_%
Time step
39                 2760             -0.0877               -0.1369          1577   57.1377
19                 3506             -0.0963               -0.1490          2761   78.7507
12                 2047             -0.0992               -0.1396          1541   75.2809
40                 4481             -0.1060               -0.1470          3270   72.9748
8                  4457             -0.1061               -0.1479          3292   73.8613
23                 4165             -0.1071               -0.1546          2978   71.5006
22                 5894             -0.1084               -0.1672          4131   70.0882
29                 4275             -0.1105               -0.1522          3101   72.5380
45                 5598             -0.1116               -0.1724          4377   78.1886
17                 3385             -0.1117               -0.1474          2574   76.0414
43                 5063             -0.1141               -0.1454          3693   72.9409
27                 1089             -0.1155               -0.1664           883   81.0836
14                 2022             -0.1157               -0.1447          1605   79.3769
49                 2454             -0.1163               -0.1592          1978   80.6031
5                  6803             -0.1178               -0.1728          4921   72.3357

================================================================================
TEST SET — FINAL UNSUPERVISED ANALYSIS
================================================================================
Test samples: 36824

Test-set anomaly scores by class:
       count      mean      std       min    median      max
class
1        408 -0.143264 0.043923 -0.187251 -0.163634 0.072743
2       8433 -0.048117 0.109312 -0.187376 -0.066810 0.252861
3      27983 -0.143177 0.071808 -0.187426 -0.177481 0.199629

================================================================================
TEST SET — TOP 50 ANOMALOUS TRANSACTIONS
================================================================================
     txId  Time step  class  anomaly_score
   971497         42      2       0.252861
 18918220         47      2       0.252416
 65381198         42      2       0.252013
164687671         45      2       0.251354
 34717366         42      2       0.251335
  6243976         46      2       0.250720
 92738855         43      2       0.249931
156303533         45      2       0.249323
 53450313         43      2       0.249009
 91882365         43      2       0.248671
 39393441         47      2       0.247879
157243941         45      2       0.247164
 28468985         44      2       0.246901
108353956         45      2       0.245796
164687321         45      2       0.243843
 32915977         45      2       0.243355
 81789779         45      2       0.243046
151742640         45      2       0.242760
  8005107         42      2       0.242759
 34978872         42      2       0.242704
164687672         45      2       0.242670
 33454081         45      2       0.242300
106319919         44      2       0.241548
156307670         45      2       0.240274
 41342269         42      2       0.239877
164686469         45      2       0.239607
 13269003         47      2       0.238901
  3098169         47      2       0.238401
  2462027         48      2       0.235677
 83121915         47      2       0.234380
 94260854         43      2       0.233607
  3282970         48      2       0.233005
  2232001         48      2       0.232201
 31646401         47      2       0.232085
 94408492         45      2       0.231436
155816178         45      2       0.231317
 94408153         45      2       0.231065
126802668         45      2       0.230442
155829812         45      2       0.230328
 63691475         44      2       0.226390
105594296         44      2       0.226315
 94312679         43      2       0.223855
155816207         45      2       0.223457
128924055         45      2       0.223418
164687876         45      2       0.223238
155816211         45      2       0.222329
156160849         45      2       0.222125
155809660         45      2       0.221008
101028778         45      2       0.220498
 70782891         42      2       0.219945

================================================================================
SAVING RESULTS
================================================================================
✓ Results saved:
c:\Users\YASHIKA\Desktop\bit-trace\results\elliptic_unsupervised\elliptic_transaction_anomaly_scores.csv
c:\Users\YASHIKA\Desktop\bit-trace\results\elliptic_unsupervised\top_100_anomalous_transactions.csv
c:\Users\YASHIKA\Desktop\bit-trace\results\elliptic_unsupervised\temporal_anomaly_summary.csv
c:\Users\YASHIKA\Desktop\bit-trace\results\elliptic_unsupervised\class_anomaly_summary.csv

================================================================================
PIPELINE STATUS
================================================================================
✓ Elliptic++ transaction data loaded
✓ 13 previously selected features verified
✓ Temporal ordering preserved
✓ Median imputation performed
✓ Scaler fitted only on training period
✓ Temporal train/validation/test split
✓ Isolation Forest trained without labels
✓ Anomaly scores generated
✓ Class-wise evaluation performed AFTER training
✓ Top anomaly analysis completed
✓ Temporal anomaly analysis completed
✓ Test-set analysis completed
✓ Results exported

IMPORTANT:
Class labels were used ONLY for post-training evaluation.
They were NOT used to fit Isolation Forest.

Done.

In [38]:
# ============================================================
# BIT-TRACE — ELLIPTIC++ PIPELINE
# FIXED PATH + FEATURE LOADING
# ============================================================

import os
import numpy as np
import pandas as pd

print("=" * 80)
print("BIT-TRACE — ELLIPTIC++ DATA LOADING")
print("=" * 80)

# ------------------------------------------------------------
# 1. EXACT FILE PATHS
# ------------------------------------------------------------

FEATURE_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv"

CLASS_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv"

EDGELIST_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv"

# ------------------------------------------------------------
# 2. CHECK FILES
# ------------------------------------------------------------

print("\n[1] FILE CHECK")
print("-" * 80)

for name, path in [
    ("FEATURE", FEATURE_PATH),
    ("CLASS", CLASS_PATH),
    ("EDGELIST", EDGELIST_PATH)
]:
    exists = os.path.exists(path)
    print(f"{name:<10}: {exists}")
    if exists:
        print(f"Path       : {path}")
        print(f"Size       : {os.path.getsize(path) / (1024**2):.2f} MB")

if not os.path.exists(FEATURE_PATH):
    raise FileNotFoundError(FEATURE_PATH)

if not os.path.exists(CLASS_PATH):
    raise FileNotFoundError(CLASS_PATH)

# ------------------------------------------------------------
# 3. SELECTED FEATURES
# ------------------------------------------------------------

SELECTED_FEATURES = [
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_52",
    "Local_feature_59",
    "Aggregate_feature_21",
    "Local_feature_25",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_32",
    "Aggregate_feature_14",
    "Local_feature_22",
    "Local_feature_47"
]

print("\n[2] SELECTED FEATURES")
print("-" * 80)

for i, f in enumerate(SELECTED_FEATURES, 1):
    print(f"{i:2d}. {f}")

# ------------------------------------------------------------
# 4. READ CLASS DATA
# ------------------------------------------------------------

print("\n[3] LOADING CLASS DATA")
print("-" * 80)

classes = pd.read_csv(CLASS_PATH)

print("Shape:", classes.shape)
print("Columns:", classes.columns.tolist())

print("\nFirst rows:")
print(classes.head())

# Normalize column names
classes.columns = classes.columns.str.strip()

# Detect ID and class columns
id_candidates = ["txId", "txid", "tx_id", "transactionId"]

id_col = next(
    (c for c in id_candidates if c in classes.columns),
    None
)

if id_col is None:
    raise ValueError(
        f"Transaction ID column not found. Columns: {classes.columns.tolist()}"
    )

class_candidates = ["class", "Class", "label", "Label"]

class_col = next(
    (c for c in class_candidates if c in classes.columns),
    None
)

if class_col is None:
    raise ValueError(
        f"Class column not found. Columns: {classes.columns.tolist()}"
    )

# Rename consistently
classes = classes.rename(
    columns={
        id_col: "txId",
        class_col: "class"
    }
)

print("\nNormalized columns:", classes.columns.tolist())

print("\nClass distribution:")
print(classes["class"].value_counts(dropna=False))

# ------------------------------------------------------------
# 5. READ ONLY REQUIRED FEATURE COLUMNS
# ------------------------------------------------------------

print("\n[4] READING FEATURE HEADER")
print("-" * 80)

header = pd.read_csv(
    FEATURE_PATH,
    nrows=0
)

header.columns = header.columns.str.strip()

print("Total columns:", len(header.columns))

print("\nFirst 20 columns:")
print(header.columns[:20].tolist())

# Detect columns
feature_id_col = next(
    (c for c in ["txId", "txid", "tx_id"] if c in header.columns),
    None
)

time_col = next(
    (c for c in ["Time step", "time_step", "Time_step", "time step"] if c in header.columns),
    None
)

if feature_id_col is None:
    raise ValueError(
        f"txId column not found in feature file.\n"
        f"Available columns: {header.columns.tolist()[:30]}"
    )

if time_col is None:
    raise ValueError(
        f"Time step column not found.\n"
        f"Available columns: {header.columns.tolist()[:30]}"
    )

print("\nDetected ID column :", feature_id_col)
print("Detected time column:", time_col)

# Check selected features
missing = [
    f for f in SELECTED_FEATURES
    if f not in header.columns
]

if missing:
    print("\nMISSING FEATURES:")
    for f in missing:
        print(" -", f)

    raise ValueError(
        "Selected features do not match this feature file."
    )

print("\n✓ All 13 selected features found.")

# ------------------------------------------------------------
# 6. LOAD ONLY 15 REQUIRED COLUMNS
# ------------------------------------------------------------

required_columns = [
    feature_id_col,
    time_col
] + SELECTED_FEATURES

print("\n[5] LOADING REQUIRED COLUMNS")
print("-" * 80)

print("Columns to load:", len(required_columns))

data = pd.read_csv(
    FEATURE_PATH,
    usecols=required_columns
)

data.columns = data.columns.str.strip()

# Normalize ID/time names
data = data.rename(
    columns={
        feature_id_col: "txId",
        time_col: "Time step"
    }
)

print("Loaded shape:", data.shape)

# ------------------------------------------------------------
# 7. BASIC CLEANING
# ------------------------------------------------------------

print("\n[6] BASIC DATA CLEANING")
print("-" * 80)

print("Missing txId:", data["txId"].isna().sum())
print("Missing Time step:", data["Time step"].isna().sum())

# Remove duplicate transaction IDs if any
duplicate_ids = data["txId"].duplicated().sum()

print("Duplicate txId:", duplicate_ids)

if duplicate_ids > 0:
    print("Removing duplicate txId rows...")
    data = data.drop_duplicates(
        subset="txId",
        keep="first"
    ).reset_index(drop=True)

# ------------------------------------------------------------
# 8. NUMERIC CONVERSION
# ------------------------------------------------------------

for col in SELECTED_FEATURES:
    data[col] = pd.to_numeric(
        data[col],
        errors="coerce"
    )

data["Time step"] = pd.to_numeric(
    data["Time step"],
    errors="coerce"
)

# ------------------------------------------------------------
# 9. MERGE LABELS
# ------------------------------------------------------------

print("\n[7] MERGING FEATURES + CLASSES")
print("-" * 80)

data = data.merge(
    classes[["txId", "class"]],
    on="txId",
    how="inner",
    validate="one_to_one"
)

print("Merged shape:", data.shape)

print("\nMissing class labels:")
print(data["class"].isna().sum())

print("\nClass distribution:")
print(data["class"].value_counts())

# ------------------------------------------------------------
# 10. DATA QUALITY
# ------------------------------------------------------------

print("\n[8] DATA QUALITY")
print("-" * 80)

X_raw = data[SELECTED_FEATURES].copy()

nan_total = int(X_raw.isna().sum().sum())

inf_total = int(
    np.isinf(
        X_raw.to_numpy(dtype=np.float64)
    ).sum()
)

print("Total NaN:", nan_total)
print("Total Inf:", inf_total)

# Replace infinity with NaN
X_raw = X_raw.replace(
    [np.inf, -np.inf],
    np.nan
)

# ------------------------------------------------------------
# 11. MEDIAN IMPUTATION
# ------------------------------------------------------------

print("\n[9] MEDIAN IMPUTATION")
print("-" * 80)

medians = X_raw.median()

X = X_raw.fillna(medians)

print("Remaining NaN:", int(X.isna().sum().sum()))

# ------------------------------------------------------------
# 12. FINAL MATRIX
# ------------------------------------------------------------

X_all = X.to_numpy(dtype=np.float32)

y_all = data["class"].to_numpy()

time_steps = data["Time step"].to_numpy()

tx_ids = data["txId"].to_numpy()

print("\n[10] FINAL DATA")
print("-" * 80)

print("X shape       :", X_all.shape)
print("y shape       :", y_all.shape)
print("time shape    :", time_steps.shape)
print("txId shape    :", tx_ids.shape)

print("\nTime range:")
print("Minimum:", np.nanmin(time_steps))
print("Maximum:", np.nanmax(time_steps))

print("\nClass distribution:")
print(pd.Series(y_all).value_counts().sort_index())

# ------------------------------------------------------------
# 13. TEMPORAL SPLIT
# ------------------------------------------------------------

print("\n[11] TEMPORAL SPLIT")
print("-" * 80)

train_idx = np.where(time_steps <= 34)[0]

val_idx = np.where(
    (time_steps >= 35) &
    (time_steps <= 41)
)[0]

test_idx = np.where(time_steps >= 42)[0]

print("Train:", len(train_idx))
print("Validation:", len(val_idx))
print("Test:", len(test_idx))

# ------------------------------------------------------------
# 14. VERIFY SPLIT
# ------------------------------------------------------------

print("\nTrain time range:")
print(
    time_steps[train_idx].min(),
    "to",
    time_steps[train_idx].max()
)

print("Validation time range:")
print(
    time_steps[val_idx].min(),
    "to",
    time_steps[val_idx].max()
)

print("Test time range:")
print(
    time_steps[test_idx].min(),
    "to",
    time_steps[test_idx].max()
)

# ------------------------------------------------------------
# 15. FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("ELLIPTIC++ DATA PREPARATION COMPLETE")
print("=" * 80)

print("✓ Files loaded")
print("✓ 13 selected features loaded")
print("✓ Labels merged")
print("✓ NaN/Inf handled")
print("✓ X_all created")
print("✓ y_all created")
print("✓ time_steps created")
print("✓ train_idx created")
print("✓ val_idx created")
print("✓ test_idx created")

print("\nVariables now available:")
print("X_all")
print("y_all")
print("time_steps")
print("tx_ids")
print("data")
print("train_idx")
print("val_idx")
print("test_idx")

print("\nReady for Isolation Forest.")

================================================================================
BIT-TRACE — ELLIPTIC++ DATA LOADING
================================================================================

[1] FILE CHECK
--------------------------------------------------------------------------------
FEATURE   : True
Path       : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv
Size       : 662.60 MB
CLASS     : True
Path       : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv
Size       : 2.25 MB
EDGELIST  : True
Path       : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv
Size       : 4.26 MB

[2] SELECTED FEATURES
--------------------------------------------------------------------------------
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47

[3] LOADING CLASS DATA
--------------------------------------------------------------------------------
Shape: (203769, 2)
Columns: ['txId', 'class']

First rows:
    txId  class
0   3321      3
1  11108      3
2  51816      3
3  68869      2
4  89273      2

Normalized columns: ['txId', 'class']

Class distribution:
class
3    157205
2     42019
1      4545
Name: count, dtype: int64

[4] READING FEATURE HEADER
--------------------------------------------------------------------------------
Total columns: 184

First 20 columns:
['txId', 'Time step', 'Local_feature_1', 'Local_feature_2', 'Local_feature_3', 'Local_feature_4', 'Local_feature_5', 'Local_feature_6', 'Local_feature_7', 'Local_feature_8', 'Local_feature_9', 'Local_feature_10', 'Local_feature_11', 'Local_feature_12', 'Local_feature_13', 'Local_feature_14', 'Local_feature_15', 'Local_feature_16', 'Local_feature_17', 'Local_feature_18']

Detected ID column : txId
Detected time column: Time step

✓ All 13 selected features found.

[5] LOADING REQUIRED COLUMNS
--------------------------------------------------------------------------------
Columns to load: 15
Loaded shape: (203769, 15)

[6] BASIC DATA CLEANING
--------------------------------------------------------------------------------
Missing txId: 0
Missing Time step: 0
Duplicate txId: 0

[7] MERGING FEATURES + CLASSES
--------------------------------------------------------------------------------
Merged shape: (203769, 16)

Missing class labels:
0

Class distribution:
class
3    157205
2     42019
1      4545
Name: count, dtype: int64

[8] DATA QUALITY
--------------------------------------------------------------------------------
Total NaN: 0
Total Inf: 0

[9] MEDIAN IMPUTATION
--------------------------------------------------------------------------------
Remaining NaN: 0

[10] FINAL DATA
--------------------------------------------------------------------------------
X shape       : (203769, 13)
y shape       : (203769,)
time shape    : (203769,)
txId shape    : (203769,)

Time range:
Minimum: 1
Maximum: 49

Class distribution:
1      4545
2     42019
3    157205
Name: count, dtype: int64

[11] TEMPORAL SPLIT
--------------------------------------------------------------------------------
Train: 136265
Validation: 30680
Test: 36824

Train time range:
1 to 34
Validation time range:
35 to 41
Test time range:
42 to 49

================================================================================
ELLIPTIC++ DATA PREPARATION COMPLETE
================================================================================
✓ Files loaded
✓ 13 selected features loaded
✓ Labels merged
✓ NaN/Inf handled
✓ X_all created
✓ y_all created
✓ time_steps created
✓ train_idx created
✓ val_idx created
✓ test_idx created

Variables now available:
X_all
y_all
time_steps
tx_ids
data
train_idx
val_idx
test_idx

Ready for Isolation Forest.

In [39]:
# ============================================================
# BIT-TRACE — ELLIPTIC++ ISOLATION FOREST
# UNSUPERVISED ANOMALY DETECTION
# ============================================================

import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.metrics import roc_auc_score, average_precision_score

print("=" * 80)
print("BIT-TRACE — ELLIPTIC++ ISOLATION FOREST")
print("=" * 80)

# ------------------------------------------------------------
# 1. VERIFY INPUTS
# ------------------------------------------------------------

print("\n[1] INPUT VERIFICATION")
print("-" * 80)

print("X_all       :", X_all.shape)
print("y_all       :", y_all.shape)
print("time_steps  :", time_steps.shape)
print("train_idx   :", len(train_idx))
print("val_idx     :", len(val_idx))
print("test_idx    :", len(test_idx))

assert len(X_all) == len(y_all) == len(time_steps) == len(tx_ids)

# ------------------------------------------------------------
# 2. TEMPORAL DATA
# ------------------------------------------------------------

X_train = X_all[train_idx]
X_val   = X_all[val_idx]
X_test  = X_all[test_idx]

y_train = y_all.iloc[train_idx].to_numpy()
y_val   = y_all.iloc[val_idx].to_numpy()
y_test  = y_all.iloc[test_idx].to_numpy()

tx_train = tx_ids.iloc[train_idx].to_numpy()
tx_val   = tx_ids.iloc[val_idx].to_numpy()
tx_test  = tx_ids.iloc[test_idx].to_numpy()

time_train = time_steps[train_idx]
time_val   = time_steps[val_idx]
time_test  = time_steps[test_idx]

print("\n[2] TEMPORAL SPLIT")
print("-" * 80)

print(f"Train : {len(X_train):,} | time {time_train.min()}–{time_train.max()}")
print(f"Val   : {len(X_val):,} | time {time_val.min()}–{time_val.max()}")
print(f"Test  : {len(X_test):,} | time {time_test.min()}–{time_test.max()}")

# ------------------------------------------------------------
# 3. TRAINING LABELS ARE NOT USED
# ------------------------------------------------------------

print("\n[3] UNSUPERVISED TRAINING")
print("-" * 80)

print("Training labels available only for post-hoc evaluation.")
print("Isolation Forest will NOT use y_train.")

# ------------------------------------------------------------
# 4. TRAIN ISOLATION FOREST
# ------------------------------------------------------------

print("\n[4] TRAINING ISOLATION FOREST")
print("-" * 80)

iso_forest = IsolationForest(
    n_estimators=300,
    contamination="auto",
    max_samples="auto",
    max_features=1.0,
    bootstrap=False,
    random_state=42,
    n_jobs=-1
)

iso_forest.fit(X_train)

print("✓ Isolation Forest trained")
print("Trees:", iso_forest.n_estimators)

# ------------------------------------------------------------
# 5. GENERATE SCORES
# ------------------------------------------------------------
# sklearn:
# decision_function:
#   lower = more anomalous
#
# We convert it into an anomaly score where:
#   higher = more anomalous

print("\n[5] GENERATING ANOMALY SCORES")
print("-" * 80)

train_raw = iso_forest.decision_function(X_train)
val_raw   = iso_forest.decision_function(X_val)
test_raw  = iso_forest.decision_function(X_test)

train_score = -train_raw
val_score   = -val_raw
test_score  = -test_raw

print("✓ Scores generated")

# ------------------------------------------------------------
# 6. SCORE SUMMARY
# ------------------------------------------------------------

print("\n[6] SCORE DISTRIBUTION")
print("-" * 80)

score_summary = pd.DataFrame({
    "Split": ["Train", "Validation", "Test"],
    "Samples": [
        len(train_score),
        len(val_score),
        len(test_score)
    ],
    "Mean": [
        train_score.mean(),
        val_score.mean(),
        test_score.mean()
    ],
    "Std": [
        train_score.std(),
        val_score.std(),
        test_score.std()
    ],
    "Min": [
        train_score.min(),
        val_score.min(),
        test_score.min()
    ],
    "Median": [
        np.median(train_score),
        np.median(val_score),
        np.median(test_score)
    ],
    "Max": [
        train_score.max(),
        val_score.max(),
        test_score.max()
    ]
})

print(score_summary.to_string(index=False))

# ------------------------------------------------------------
# 7. CREATE EVALUATION DATAFRAME
# ------------------------------------------------------------

print("\n[7] CREATING EVALUATION DATA")
print("-" * 80)

train_eval = pd.DataFrame({
    "txId": tx_train,
    "Time step": time_train,
    "class": y_train,
    "anomaly_score": train_score
})

val_eval = pd.DataFrame({
    "txId": tx_val,
    "Time step": time_val,
    "class": y_val,
    "anomaly_score": val_score
})

test_eval = pd.DataFrame({
    "txId": tx_test,
    "Time step": time_test,
    "class": y_test,
    "anomaly_score": test_score
})

eval_df = pd.concat(
    [train_eval, val_eval, test_eval],
    ignore_index=True
)

print("Evaluation dataframe:", eval_df.shape)

# ------------------------------------------------------------
# 8. CLASS-WISE SCORE ANALYSIS
# ------------------------------------------------------------

print("\n[8] CLASS-WISE ANOMALY SCORES")
print("-" * 80)

class_stats = (
    eval_df
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(class_stats.to_string())

# ------------------------------------------------------------
# 9. CLASS-WISE QUANTILES
# ------------------------------------------------------------

print("\n[9] CLASS-WISE SCORE QUANTILES")
print("-" * 80)

quantiles = (
    eval_df
    .groupby("class")["anomaly_score"]
    .quantile(
        [0.01, 0.05, 0.10, 0.25, 0.50,
         0.75, 0.90, 0.95, 0.99]
    )
    .unstack()
)

quantiles.columns = [
    "Q01", "Q05", "Q10", "Q25",
    "Q50", "Q75", "Q90", "Q95", "Q99"
]

print(quantiles.to_string())

# ------------------------------------------------------------
# 10. TOP ANOMALOUS TRANSACTIONS
# ------------------------------------------------------------

print("\n[10] TOP 30 MOST ANOMALOUS TRANSACTIONS")
print("-" * 80)

top30 = (
    eval_df
    .sort_values("anomaly_score", ascending=False)
    .head(30)
)

print(top30[
    ["txId", "Time step", "class", "anomaly_score"]
].to_string(index=False))

# ------------------------------------------------------------
# 11. CLASS DISTRIBUTION AMONG TOP ANOMALIES
# ------------------------------------------------------------

print("\n[11] CLASS DISTRIBUTION AMONG TOP ANOMALIES")
print("-" * 80)

overall_class3_pct = (
    (eval_df["class"] == 3).mean() * 100
)

for k in [50, 100, 500, 1000, 5000]:

    top_k = (
        eval_df
        .nlargest(k, "anomaly_score")
    )

    counts = top_k["class"].value_counts().sort_index()

    class3_count = (top_k["class"] == 3).sum()
    class3_pct = class3_count / k * 100

    enrichment = class3_pct / overall_class3_pct

    print(f"\nTop {k:,} anomalies")
    print(counts.to_string())
    print(
        f"Class-3: {class3_pct:.2f}% | "
        f"Enrichment: {enrichment:.3f}x"
    )

# ------------------------------------------------------------
# 12. TEMPORAL ANALYSIS
# ------------------------------------------------------------

print("\n[12] TEMPORAL ANOMALY ANALYSIS")
print("-" * 80)

temporal_stats = (
    eval_df
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly_Score=("anomaly_score", "mean"),
        Median_Anomaly_Score=("anomaly_score", "median"),
        Class3_Count=("class", lambda x: (x == 3).sum())
    )
)

temporal_stats["Class3_%"] = (
    temporal_stats["Class3_Count"]
    / temporal_stats["Transactions"]
    * 100
)

# Higher score = more anomalous
most_anomalous_time = (
    temporal_stats
    .sort_values(
        "Mean_Anomaly_Score",
        ascending=False
    )
    .head(15)
)

print(most_anomalous_time.to_string())

# ------------------------------------------------------------
# 13. TEST SET ANALYSIS
# ------------------------------------------------------------

print("\n[13] TEST SET — FINAL UNSUPERVISED ANALYSIS")
print("-" * 80)

test_class_stats = (
    test_eval
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(test_class_stats.to_string())

# ------------------------------------------------------------
# 14. OPTIONAL POST-HOC BINARY CLASS-3 EVALUATION
# ------------------------------------------------------------
# IMPORTANT:
# These labels are NOT used to train the model.
#
# This only tells us whether anomaly scores align
# with the existing Class-3 labels.

print("\n[14] POST-HOC CLASS-3 EVALUATION")
print("-" * 80)

y_test_binary = (
    test_eval["class"].to_numpy() == 3
).astype(int)

test_scores_np = test_eval["anomaly_score"].to_numpy()

roc_auc = roc_auc_score(
    y_test_binary,
    test_scores_np
)

pr_auc = average_precision_score(
    y_test_binary,
    test_scores_np
)

print(f"Test ROC-AUC : {roc_auc:.4f}")
print(f"Test PR-AUC  : {pr_auc:.4f}")

# ------------------------------------------------------------
# 15. SAVE RESULTS
# ------------------------------------------------------------

print("\n[15] SAVING RESULTS")
print("-" * 80)

results_path = "ellipticpp_isolation_forest_results.csv"

eval_df.to_csv(
    results_path,
    index=False
)

print(f"✓ Results saved: {results_path}")

print("\n" + "=" * 80)
print("PIPELINE COMPLETE")
print("=" * 80)

print("""
✓ Elliptic++ loaded
✓ 13 selected features
✓ Temporal split preserved
✓ Isolation Forest trained unsupervised
✓ Anomaly scores generated
✓ Class-wise analysis completed
✓ Top anomaly analysis completed
✓ Temporal analysis completed
✓ Test-set analysis completed
✓ Post-hoc Class-3 evaluation completed
""")

================================================================================
BIT-TRACE — ELLIPTIC++ ISOLATION FOREST
================================================================================

[1] INPUT VERIFICATION
--------------------------------------------------------------------------------
X_all       : (203769, 13)
y_all       : (203769,)
time_steps  : (203769,)
train_idx   : 136265
val_idx     : 30680
test_idx    : 36824

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [40]:
# ============================================================
# BIT-TRACE — ELLIPTIC++ FINAL UNSUPERVISED PIPELINE
# ISOLATION FOREST + TEMPORAL + CLASS-WISE POST-HOC ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.metrics import roc_auc_score, average_precision_score

print("=" * 80)
print("BIT-TRACE — ELLIPTIC++ ISOLATION FOREST")
print("=" * 80)


# ============================================================
# 1. VERIFY EXISTING VARIABLES
# ============================================================

required = [
    "X_all",
    "y_all",
    "time_steps",
    "tx_ids",
    "train_idx",
    "val_idx",
    "test_idx"
]

missing = [v for v in required if v not in globals()]

if missing:
    raise NameError(
        "Missing variables: " + ", ".join(missing)
        + "\nRun your Elliptic++ data preparation cell first."
    )

print("\n[1] INPUTS VERIFIED")
print("-" * 80)

print("X_all      :", np.shape(X_all))
print("y_all      :", np.shape(y_all))
print("time_steps :", np.shape(time_steps))
print("tx_ids     :", np.shape(tx_ids))

print("Train      :", len(train_idx))
print("Validation :", len(val_idx))
print("Test       :", len(test_idx))


# ============================================================
# 2. CONVERT EVERYTHING TO SAFE NUMPY ARRAYS
# ============================================================

X_all_np = np.asarray(X_all, dtype=np.float32)
y_all_np = np.asarray(y_all)
time_np = np.asarray(time_steps)
tx_np = np.asarray(tx_ids)

train_idx = np.asarray(train_idx, dtype=int)
val_idx   = np.asarray(val_idx, dtype=int)
test_idx  = np.asarray(test_idx, dtype=int)

print("\n[2] ARRAY CONVERSION COMPLETE")
print("-" * 80)

print("X:", X_all_np.shape)
print("Features:", X_all_np.shape[1])


# ============================================================
# 3. TEMPORAL SPLIT
# ============================================================

X_train = X_all_np[train_idx]
X_val   = X_all_np[val_idx]
X_test  = X_all_np[test_idx]

y_train = y_all_np[train_idx]
y_val   = y_all_np[val_idx]
y_test  = y_all_np[test_idx]

tx_train = tx_np[train_idx]
tx_val   = tx_np[val_idx]
tx_test  = tx_np[test_idx]

time_train = time_np[train_idx]
time_val   = time_np[val_idx]
time_test  = time_np[test_idx]

print("\n[3] TEMPORAL SPLIT")
print("-" * 80)

print(
    f"Train      : {len(X_train):,} "
    f"(time {time_train.min()}–{time_train.max()})"
)

print(
    f"Validation : {len(X_val):,} "
    f"(time {time_val.min()}–{time_val.max()})"
)

print(
    f"Test       : {len(X_test):,} "
    f"(time {time_test.min()}–{time_test.max()})"
)


# ============================================================
# 4. DATA QUALITY
# ============================================================

print("\n[4] DATA QUALITY")
print("-" * 80)

print("NaN:", np.isnan(X_all_np).sum())
print("Inf:", np.isinf(X_all_np).sum())

if np.isnan(X_train).any() or np.isinf(X_train).any():
    raise ValueError("Train data contains NaN/Inf.")

if np.isnan(X_val).any() or np.isinf(X_val).any():
    raise ValueError("Validation data contains NaN/Inf.")

if np.isnan(X_test).any() or np.isinf(X_test).any():
    raise ValueError("Test data contains NaN/Inf.")

print("✓ No NaN/Inf")


# ============================================================
# 5. TRAIN ISOLATION FOREST
# ============================================================

print("\n[5] TRAINING ISOLATION FOREST")
print("-" * 80)

print("Training labels are NOT used.")

model = IsolationForest(
    n_estimators=300,
    contamination="auto",
    max_samples="auto",
    max_features=1.0,
    bootstrap=False,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train)

print("✓ Model trained")
print("Trees:", model.n_estimators)


# ============================================================
# 6. ANOMALY SCORES
# ============================================================

print("\n[6] GENERATING ANOMALY SCORES")
print("-" * 80)

# sklearn decision_function:
# lower = more anomalous
#
# We reverse sign:
# higher = more anomalous

train_score = -model.decision_function(X_train)
val_score   = -model.decision_function(X_val)
test_score  = -model.decision_function(X_test)

print("✓ Train scores:", len(train_score))
print("✓ Validation scores:", len(val_score))
print("✓ Test scores:", len(test_score))


# ============================================================
# 7. SCORE DISTRIBUTION
# ============================================================

print("\n[7] ANOMALY SCORE DISTRIBUTION")
print("=" * 80)

score_summary = pd.DataFrame({
    "Split": ["Train", "Validation", "Test"],
    "Samples": [
        len(train_score),
        len(val_score),
        len(test_score)
    ],
    "Mean_Score": [
        train_score.mean(),
        val_score.mean(),
        test_score.mean()
    ],
    "Std_Score": [
        train_score.std(),
        val_score.std(),
        test_score.std()
    ],
    "Min_Score": [
        train_score.min(),
        val_score.min(),
        test_score.min()
    ],
    "Median_Score": [
        np.median(train_score),
        np.median(val_score),
        np.median(test_score)
    ],
    "Max_Score": [
        train_score.max(),
        val_score.max(),
        test_score.max()
    ]
})

print(score_summary.to_string(index=False))


# ============================================================
# 8. CREATE EVALUATION DATA
# ============================================================

train_eval = pd.DataFrame({
    "txId": tx_train,
    "Time step": time_train,
    "class": y_train,
    "anomaly_score": train_score
})

val_eval = pd.DataFrame({
    "txId": tx_val,
    "Time step": time_val,
    "class": y_val,
    "anomaly_score": val_score
})

test_eval = pd.DataFrame({
    "txId": tx_test,
    "Time step": time_test,
    "class": y_test,
    "anomaly_score": test_score
})

eval_df = pd.concat(
    [train_eval, val_eval, test_eval],
    ignore_index=True
)

print("\n[8] EVALUATION DATA CREATED")
print("-" * 80)

print("Shape:", eval_df.shape)
print("Missing scores:", eval_df["anomaly_score"].isna().sum())


# ============================================================
# 9. CLASS-WISE ANOMALY ANALYSIS
# ============================================================

print("\n[9] CLASS-WISE ANOMALY SCORE ANALYSIS")
print("=" * 80)

class_stats = (
    eval_df
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(class_stats.to_string())


# ============================================================
# 10. CLASS-WISE QUANTILES
# ============================================================

print("\n[10] CLASS-WISE SCORE QUANTILES")
print("=" * 80)

quantiles = (
    eval_df
    .groupby("class")["anomaly_score"]
    .quantile(
        [0.01, 0.05, 0.10, 0.25,
         0.50, 0.75, 0.90, 0.95, 0.99]
    )
    .unstack()
)

quantiles.columns = [
    "Q01", "Q05", "Q10", "Q25",
    "Q50", "Q75", "Q90", "Q95", "Q99"
]

print(quantiles.to_string())


# ============================================================
# 11. TOP ANOMALIES
# ============================================================

print("\n[11] TOP 30 MOST ANOMALOUS TRANSACTIONS")
print("=" * 80)

top30 = (
    eval_df
    .nlargest(30, "anomaly_score")
)

print(
    top30[
        ["txId", "Time step", "class", "anomaly_score"]
    ].to_string(index=False)
)


# ============================================================
# 12. TOP-K CLASS DISTRIBUTION
# ============================================================

print("\n[12] CLASS DISTRIBUTION AMONG TOP ANOMALIES")
print("=" * 80)

overall_class3_pct = (
    (eval_df["class"] == 3).mean() * 100
)

for k in [50, 100, 500, 1000, 5000]:

    top_k = eval_df.nlargest(k, "anomaly_score")

    counts = (
        top_k["class"]
        .value_counts()
        .sort_index()
    )

    class3_count = (
        top_k["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / k * 100
    )

    enrichment = (
        class3_pct / overall_class3_pct
    )

    print(f"\nTop {k:,}")
    print(counts.to_string())

    print(
        f"Class-3 = {class3_pct:.2f}% | "
        f"Overall = {overall_class3_pct:.2f}% | "
        f"Enrichment = {enrichment:.3f}x"
    )


# ============================================================
# 13. TEMPORAL ANOMALY ANALYSIS
# ============================================================

print("\n[13] TEMPORAL ANOMALY ANALYSIS")
print("=" * 80)

temporal_stats = (
    eval_df
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly_Score=("anomaly_score", "mean"),
        Median_Anomaly_Score=("anomaly_score", "median"),
        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal_stats["Class3_%"] = (
    temporal_stats["Class3_Count"]
    / temporal_stats["Transactions"]
    * 100
)

# Highest anomaly score = most anomalous
most_anomalous_time = (
    temporal_stats
    .sort_values(
        "Mean_Anomaly_Score",
        ascending=False
    )
    .head(15)
)

print(
    most_anomalous_time.to_string()
)


# ============================================================
# 14. TEST SET — FINAL ANALYSIS
# ============================================================

print("\n[14] TEST SET — FINAL UNSUPERVISED ANALYSIS")
print("=" * 80)

test_class_stats = (
    test_eval
    .groupby("class")["anomaly_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(test_class_stats.to_string())


# ============================================================
# 15. POST-HOC CLASS-3 EVALUATION
# ============================================================
#
# IMPORTANT:
# Class labels are NOT used during model training.
#
# They are used ONLY here to check whether the
# unsupervised anomaly ranking aligns with Class 3.
# ============================================================

print("\n[15] POST-HOC CLASS-3 EVALUATION")
print("=" * 80)

y_test_binary = (
    test_eval["class"].to_numpy() == 3
).astype(int)

scores_test = (
    test_eval["anomaly_score"].to_numpy()
)

roc_auc = roc_auc_score(
    y_test_binary,
    scores_test
)

pr_auc = average_precision_score(
    y_test_binary,
    scores_test
)

print(f"Test ROC-AUC : {roc_auc:.4f}")
print(f"Test PR-AUC  : {pr_auc:.4f}")


# ============================================================
# 16. TOP CLASS-3 ENRICHMENT ON TEST ONLY
# ============================================================

print("\n[16] TEST-SET CLASS-3 ENRICHMENT")
print("=" * 80)

test_overall_class3 = (
    (test_eval["class"] == 3).mean() * 100
)

for k in [50, 100, 500, 1000, 5000]:

    k = min(k, len(test_eval))

    top_k = test_eval.nlargest(
        k,
        "anomaly_score"
    )

    class3_count = (
        top_k["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / k * 100
    )

    enrichment = (
        class3_pct / test_overall_class3
    )

    print(
        f"Top {k:5d}: "
        f"Class3 = {class3_pct:6.2f}% | "
        f"Enrichment = {enrichment:.3f}x"
    )


# ============================================================
# 17. SAVE RESULTS
# ============================================================

print("\n[17] SAVING RESULTS")
print("=" * 80)

output_file = "ellipticpp_isolation_forest_results.csv"

eval_df.to_csv(
    output_file,
    index=False
)

print("✓ Saved:", output_file)


# ============================================================
# 18. FINAL STATUS
# ============================================================

print("\n" + "=" * 80)
print("ELLIPTIC++ UNSUPERVISED PIPELINE COMPLETE")
print("=" * 80)

print("""
✓ 13 selected features
✓ Temporal split preserved
✓ Isolation Forest trained
✓ Labels NOT used during training
✓ Anomaly scores generated
✓ Class-wise analysis completed
✓ Top anomaly analysis completed
✓ Temporal analysis completed
✓ Test-set analysis completed
✓ ROC-AUC / PR-AUC calculated post-hoc
✓ Results saved
""")

================================================================================
BIT-TRACE — ELLIPTIC++ ISOLATION FOREST
================================================================================

[1] INPUTS VERIFIED
--------------------------------------------------------------------------------
X_all      : (203769, 13)
y_all      : (203769,)
time_steps : (203769,)
tx_ids     : (203769,)
Train      : 136265
Validation : 30680
Test       : 36824

[2] ARRAY CONVERSION COMPLETE
--------------------------------------------------------------------------------
X: (203769, 13)
Features: 13

[3] TEMPORAL SPLIT
--------------------------------------------------------------------------------
Train      : 136,265 (time 1–34)
Validation : 30,680 (time 35–41)
Test       : 36,824 (time 42–49)

[4] DATA QUALITY
--------------------------------------------------------------------------------
NaN: 0
Inf: 0
✓ No NaN/Inf

[5] TRAINING ISOLATION FOREST
--------------------------------------------------------------------------------
Training labels are NOT used.
✓ Model trained
Trees: 300

[6] GENERATING ANOMALY SCORES
--------------------------------------------------------------------------------
✓ Train scores: 136265
✓ Validation scores: 30680
✓ Test scores: 36824

[7] ANOMALY SCORE DISTRIBUTION
================================================================================
     Split  Samples  Mean_Score  Std_Score  Min_Score  Median_Score  Max_Score
     Train   136265   -0.127619   0.087435  -0.187823     -0.169255   0.268584
Validation    30680   -0.123678   0.088502  -0.187786     -0.169131   0.250759
      Test    36824   -0.121554   0.090663  -0.187823     -0.167228   0.255413

[8] EVALUATION DATA CREATED
--------------------------------------------------------------------------------
Shape: (203769, 4)
Missing scores: 0

[9] CLASS-WISE ANOMALY SCORE ANALYSIS
================================================================================
       Samples      Mean       Std       Min    Median       Max
class
1         4545 -0.161532  0.044583 -0.187823 -0.185225  0.118625
2        42019 -0.029228  0.115872 -0.187823 -0.037998  0.268584
3       157205 -0.150748  0.057363 -0.187823 -0.175425  0.216187

[10] CLASS-WISE SCORE QUANTILES
================================================================================
            Q01       Q05       Q10       Q25       Q50       Q75       Q90       Q95       Q99
class
1     -0.187691 -0.187644 -0.187574 -0.187369 -0.185225 -0.162070 -0.065279 -0.063153 -0.037687
2     -0.187203 -0.186252 -0.181549 -0.134047 -0.037998  0.061418  0.127582  0.168010  0.193703
3     -0.187644 -0.187465 -0.187062 -0.184912 -0.175425 -0.139999 -0.082084 -0.035455  0.094786

[11] TOP 30 MOST ANOMALOUS TRANSACTIONS
================================================================================
     txId  Time step  class  anomaly_score
 88142087         26      2       0.268584
180525719         31      2       0.266539
 72444066         30      2       0.264294
156795980         32      2       0.264040
164687671         45      2       0.255413
 12781680         41      2       0.250759
157243941         45      2       0.250538
 65381198         42      2       0.250082
 92713387         33      2       0.249938
 99332126         34      2       0.249938
 34717366         42      2       0.249913
 14182114         39      2       0.249743
 12663816         41      2       0.249688
   971497         42      2       0.249688
  7951587         40      2       0.249062
156303533         45      2       0.248697
 29140182         37      2       0.248217
 18918220         47      2       0.247999
164687321         45      2       0.247768
  8823943         41      2       0.247380
164687672         45      2       0.246926
 12661079         41      2       0.246195
  6060482         38      2       0.246177
 53450313         43      2       0.246027
 43396863         35      2       0.245617
164686469         45      2       0.244260
 92738855         43      2       0.243657
 28468985         44      2       0.242792
156307670         45      2       0.242549
 91882365         43      2       0.241810

[12] CLASS DISTRIBUTION AMONG TOP ANOMALIES
================================================================================

Top 50
class
2    50
Class-3 = 0.00% | Overall = 77.15% | Enrichment = 0.000x

Top 100
class
2    100
Class-3 = 0.00% | Overall = 77.15% | Enrichment = 0.000x

Top 500
class
2    494
3      6
Class-3 = 1.20% | Overall = 77.15% | Enrichment = 0.016x

Top 1,000
class
2    986
3     14
Class-3 = 1.40% | Overall = 77.15% | Enrichment = 0.018x

Top 5,000
class
2    3672
3    1328
Class-3 = 26.56% | Overall = 77.15% | Enrichment = 0.344x

[13] TEMPORAL ANOMALY ANALYSIS
================================================================================
           Transactions  Mean_Anomaly_Score  Median_Anomaly_Score  Class3_Count   Class3_%
Time step
39                 2760           -0.088478             -0.136673          1577  57.137681
19                 3506           -0.099765             -0.150355          2761  78.750713
12                 2047           -0.100996             -0.140822          1541  75.280899
40                 4481           -0.105550             -0.147707          3270  72.974782
8                  4457           -0.106747             -0.148987          3292  73.861342
23                 4165           -0.108480             -0.155479          2978  71.500600
22                 5894           -0.109970             -0.168526          4131  70.088225
29                 4275           -0.111515             -0.152155          3101  72.538012
45                 5598           -0.111788             -0.172544          4377  78.188639
17                 3385           -0.112482             -0.147142          2574  76.041359
43                 5063           -0.114409             -0.144474          3693  72.940944
27                 1089           -0.116354             -0.167246           883  81.083563
49                 2454           -0.116954             -0.160055          1978  80.603097
14                 2022           -0.117450             -0.145419          1605  79.376855
38                 2891           -0.118659             -0.160574          2135  73.849879

[14] TEST SET — FINAL UNSUPERVISED ANALYSIS
================================================================================
       Samples      Mean       Std       Min    Median       Max
class
1          408 -0.142143  0.044922 -0.187570 -0.164898  0.079297
2         8433 -0.048760  0.108555 -0.187748 -0.067687  0.255413
3        27983 -0.143191  0.071871 -0.187823 -0.176599  0.200976

[15] POST-HOC CLASS-3 EVALUATION
================================================================================
Test ROC-AUC : 0.2269
Test PR-AUC  : 0.6155

[16] TEST-SET CLASS-3 ENRICHMENT
================================================================================
Top    50: Class3 =   0.00% | Enrichment = 0.000x
Top   100: Class3 =   1.00% | Enrichment = 0.013x
Top   500: Class3 =   2.00% | Enrichment = 0.026x
Top  1000: Class3 =  41.10% | Enrichment = 0.541x
Top  5000: Class3 =  38.12% | Enrichment = 0.502x

[17] SAVING RESULTS
================================================================================
✓ Saved: ellipticpp_isolation_forest_results.csv

================================================================================
ELLIPTIC++ UNSUPERVISED PIPELINE COMPLETE
================================================================================

✓ 13 selected features
✓ Temporal split preserved
✓ Isolation Forest trained
✓ Labels NOT used during training
✓ Anomaly scores generated
✓ Class-wise analysis completed
✓ Top anomaly analysis completed
✓ Temporal analysis completed
✓ Test-set analysis completed
✓ ROC-AUC / PR-AUC calculated post-hoc
✓ Results saved

In [41]:
# =============================================================================
# BIT-TRACE — LABEL-INDEPENDENT UNSUPERVISED ANOMALY PIPELINE
# =============================================================================
# Pipeline:
#   1. Reuse existing loaded data OR reload automatically
#   2. Remove ID/time/label from feature candidates
#   3. Median imputation
#   4. Remove low-variance features
#   5. Remove highly correlated redundant features (|r| >= 0.90)
#   6. Temporal split: 1-34 / 35-41 / 42-49
#   7. Isolation Forest
#   8. LOF using a controlled training sample
#   9. Normalize model scores
#  10. Ensemble anomaly score
#  11. Post-hoc class evaluation ONLY
#  12. Temporal analysis
#  13. Save results
# =============================================================================

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor

# =============================================================================
# CONFIGURATION
# =============================================================================

RANDOM_STATE = 42

CORRELATION_THRESHOLD = 0.90
VARIANCE_THRESHOLD = 1e-8

# Isolation Forest
IF_N_ESTIMATORS = 300
IF_CONTAMINATION = "auto"
IF_MAX_SAMPLES = "auto"

# LOF
LOF_TRAIN_SAMPLE = 30000
LOF_NEIGHBORS = 35

# Ensemble weights
IF_WEIGHT = 0.60
LOF_WEIGHT = 0.40

# =============================================================================
# HEADER
# =============================================================================

print("=" * 90)
print("BIT-TRACE — LABEL-INDEPENDENT UNSUPERVISED ANOMALY PIPELINE")
print("=" * 90)

# =============================================================================
# 1. GET DATA
# =============================================================================

print("\n[1] PREPARING INPUT DATA")
print("-" * 90)

# -------------------------------------------------------------------------
# Reuse existing variables if available
# -------------------------------------------------------------------------

required_existing = [
    "data",
    "X_all",
    "time_steps",
    "tx_ids"
]

existing_ok = all(name in globals() for name in required_existing)

if existing_ok:
    print("✓ Existing loaded variables detected")
    print("✓ Reusing current notebook data")

else:
    print("Existing variables not complete.")
    print("Searching for Elliptic++ files...")

    possible_feature_paths = [
        r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv",
        r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\txs_features.csv"
    ]

    possible_class_paths = [
        r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv",
        r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\txs_classes.csv"
    ]

    feature_path = next(
        (p for p in possible_feature_paths if os.path.exists(p)),
        None
    )

    class_path = next(
        (p for p in possible_class_paths if os.path.exists(p)),
        None
    )

    if feature_path is None:
        raise FileNotFoundError(
            "txs_features.csv not found. "
            "Please set FEATURE_PATH manually."
        )

    if class_path is None:
        raise FileNotFoundError(
            "txs_classes.csv not found. "
            "Please set CLASS_PATH manually."
        )

    print("Feature file:", feature_path)
    print("Class file:", class_path)

    # ---------------------------------------------------------------------
    # Load class data
    # ---------------------------------------------------------------------

    classes = pd.read_csv(class_path)

    classes.columns = [
        str(c).strip() for c in classes.columns
    ]

    # Normalize names
    rename_map = {}

    for c in classes.columns:
        lc = c.lower().replace(" ", "").replace("_", "")

        if lc == "txid":
            rename_map[c] = "txId"

        elif lc == "class":
            rename_map[c] = "class"

    classes = classes.rename(columns=rename_map)

    # ---------------------------------------------------------------------
    # Read feature header first
    # ---------------------------------------------------------------------

    header = pd.read_csv(
        feature_path,
        nrows=0
    )

    feature_columns = list(header.columns)

    print("Total feature-file columns:", len(feature_columns))

    # Detect ID and time columns
    id_candidates = [
        c for c in feature_columns
        if str(c).lower() in ["txid", "tx_id", "transactionid"]
    ]

    time_candidates = [
        c for c in feature_columns
        if str(c).lower().replace("_", " ").strip()
        in ["time step", "timestep", "time"]
    ]

    if not id_candidates:
        raise ValueError("Could not detect txId column.")

    if not time_candidates:
        raise ValueError("Could not detect Time step column.")

    id_col = id_candidates[0]
    time_col = time_candidates[0]

    print("ID column  :", id_col)
    print("Time column:", time_col)

    # ---------------------------------------------------------------------
    # Load all numeric feature columns
    # ---------------------------------------------------------------------

    data = pd.read_csv(
        feature_path,
        usecols=feature_columns
    )

    # Normalize ID name
    if id_col != "txId":
        data = data.rename(columns={id_col: "txId"})
        id_col = "txId"

    if time_col != "Time step":
        data = data.rename(columns={time_col: "Time step"})
        time_col = "Time step"

    # ---------------------------------------------------------------------
    # Merge labels
    # ---------------------------------------------------------------------

    data = data.merge(
        classes[["txId", "class"]],
        on="txId",
        how="inner"
    )

    print("Loaded merged shape:", data.shape)

    # ---------------------------------------------------------------------
    # Create base arrays
    # ---------------------------------------------------------------------

    tx_ids = data["txId"].to_numpy()
    time_steps = pd.to_numeric(
        data["Time step"],
        errors="coerce"
    ).to_numpy()

# =============================================================================
# 2. BASIC DATA CHECK
# =============================================================================

print("\n[2] DATA CHECK")
print("-" * 90)

print("Rows:", len(data))

print(
    "Time range:",
    np.nanmin(time_steps),
    "to",
    np.nanmax(time_steps)
)

print("Missing txId:", pd.Series(tx_ids).isna().sum())
print("Missing time:", np.isnan(time_steps).sum())

if "class" in data.columns:
    print("\nPost-hoc class distribution:")
    print(data["class"].value_counts().sort_index())

# =============================================================================
# 3. IDENTIFY CANDIDATE FEATURES
# =============================================================================

print("\n[3] LABEL-INDEPENDENT FEATURE CANDIDATES")
print("-" * 90)

# IMPORTANT:
# class, txId and Time step are NOT feature candidates.
# Labels are completely excluded from feature selection.

exclude_columns = {
    "txId",
    "class",
    "Time step"
}

candidate_features = [
    c for c in data.columns
    if c not in exclude_columns
    and pd.api.types.is_numeric_dtype(data[c])
]

print("Candidate numeric features:", len(candidate_features))

# =============================================================================
# 4. NUMERIC MATRIX
# =============================================================================

X_raw = data[candidate_features].copy()

# Replace infinities
X_raw = X_raw.replace(
    [np.inf, -np.inf],
    np.nan
)

print("Raw feature matrix:", X_raw.shape)

# =============================================================================
# 5. MISSING VALUE HANDLING
# =============================================================================

print("\n[4] MEDIAN IMPUTATION")
print("-" * 90)

missing_before = int(X_raw.isna().sum().sum())

print("NaN before:", missing_before)

imputer = SimpleImputer(
    strategy="median"
)

X_imputed = imputer.fit_transform(X_raw)

print("NaN after:", np.isnan(X_imputed).sum())

# =============================================================================
# 6. LOW VARIANCE FILTER
# =============================================================================

print("\n[5] LOW-VARIANCE FILTER")
print("-" * 90)

variance_selector = VarianceThreshold(
    threshold=VARIANCE_THRESHOLD
)

X_variance = variance_selector.fit_transform(
    X_imputed
)

variance_features = [
    candidate_features[i]
    for i, keep in enumerate(
        variance_selector.get_support()
    )
    if keep
]

print("Before:", len(candidate_features))
print("After :", len(variance_features))
print("Removed:", len(candidate_features) - len(variance_features))

# =============================================================================
# 7. CORRELATION REDUNDANCY FILTER
# =============================================================================

print("\n[6] CORRELATION REDUNDANCY FILTER")
print("-" * 90)

X_var_df = pd.DataFrame(
    X_variance,
    columns=variance_features
)

print(
    "Calculating correlation matrix for",
    len(variance_features),
    "features..."
)

corr_matrix = X_var_df.corr(
    method="pearson"
).abs()

# Upper triangle
upper = corr_matrix.where(
    np.triu(
        np.ones(corr_matrix.shape),
        k=1
    ).astype(bool)
)

to_remove = [
    column
    for column in upper.columns
    if any(
        upper[column] >= CORRELATION_THRESHOLD
    )
]

selected_features = [
    f for f in variance_features
    if f not in to_remove
]

print("Before correlation filter:", len(variance_features))
print("Highly correlated removed :", len(to_remove))
print("Final selected features   :", len(selected_features))

print("\nSelected features:")

for i, f in enumerate(selected_features, 1):
    print(f"{i:2d}. {f}")

# =============================================================================
# 8. FINAL MATRIX
# =============================================================================

X_final = X_var_df[selected_features].to_numpy(
    dtype=np.float32
)

print("\nFinal X shape:", X_final.shape)

# =============================================================================
# 9. STANDARDIZATION
# =============================================================================

print("\n[7] STANDARDIZATION")
print("-" * 90)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(
    X_final
).astype(np.float32)

print("Scaled matrix:", X_scaled.shape)

print(
    "NaN:",
    np.isnan(X_scaled).sum(),
    "| Inf:",
    np.isinf(X_scaled).sum()
)

# =============================================================================
# 10. TEMPORAL SPLIT
# =============================================================================

print("\n[8] TEMPORAL SPLIT")
print("-" * 90)

train_idx = np.where(
    time_steps <= 34
)[0]

val_idx = np.where(
    (time_steps >= 35) &
    (time_steps <= 41)
)[0]

test_idx = np.where(
    time_steps >= 42
)[0]

print(
    f"Train      : {len(train_idx):,} "
    "(time 1–34)"
)

print(
    f"Validation : {len(val_idx):,} "
    "(time 35–41)"
)

print(
    f"Test       : {len(test_idx):,} "
    "(time 42–49)"
)

# =============================================================================
# 11. TEMPORAL DATA
# =============================================================================

X_train = X_scaled[train_idx]
X_val = X_scaled[val_idx]
X_test = X_scaled[test_idx]

print("\nTrain matrix:", X_train.shape)
print("Val matrix  :", X_val.shape)
print("Test matrix :", X_test.shape)

# =============================================================================
# 12. ISOLATION FOREST
# =============================================================================

print("\n[9] TRAINING ISOLATION FOREST")
print("-" * 90)

if_model = IsolationForest(
    n_estimators=IF_N_ESTIMATORS,
    contamination=IF_CONTAMINATION,
    max_samples=IF_MAX_SAMPLES,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

if_model.fit(X_train)

print("✓ Isolation Forest trained")
print("Trees:", IF_N_ESTIMATORS)

# -------------------------------------------------------------------------
# IMPORTANT:
# sklearn decision_function:
# higher = more normal
# lower  = more anomalous
#
# We reverse it so:
# higher anomaly score = more anomalous
# -------------------------------------------------------------------------

if_train = -if_model.decision_function(X_train)
if_val = -if_model.decision_function(X_val)
if_test = -if_model.decision_function(X_test)

print("IF train scores:", len(if_train))
print("IF val scores  :", len(if_val))
print("IF test scores :", len(if_test))

# =============================================================================
# 13. LOF
# =============================================================================

print("\n[10] TRAINING LOF")
print("-" * 90)

# LOF is computationally expensive.
# Use a representative training subset.

rng = np.random.RandomState(
    RANDOM_STATE
)

if len(X_train) > LOF_TRAIN_SAMPLE:

    lof_sample_idx = rng.choice(
        len(X_train),
        size=LOF_TRAIN_SAMPLE,
        replace=False
    )

    X_lof_train = X_train[
        lof_sample_idx
    ]

else:

    X_lof_train = X_train

print(
    "LOF training samples:",
    len(X_lof_train)
)

lof_model = LocalOutlierFactor(
    n_neighbors=LOF_NEIGHBORS,
    novelty=True,
    contamination="auto",
    n_jobs=-1
)

lof_model.fit(
    X_lof_train
)

print("✓ LOF trained")
print("Neighbors:", LOF_NEIGHBORS)

# Higher = more anomalous
lof_train = -lof_model.decision_function(X_train)
lof_val = -lof_model.decision_function(X_val)
lof_test = -lof_model.decision_function(X_test)

print("LOF train scores:", len(lof_train))
print("LOF val scores  :", len(lof_val))
print("LOF test scores :", len(lof_test))

# =============================================================================
# 14. SCORE NORMALIZATION
# =============================================================================

print("\n[11] NORMALIZING ANOMALY SCORES")
print("-" * 90)

# Use TRAIN statistics only.
# This prevents validation/test information leakage.

def robust_zscore(
    train_score,
    other_scores
):
    median = np.median(
        train_score
    )

    q1 = np.percentile(
        train_score,
        25
    )

    q3 = np.percentile(
        train_score,
        75
    )

    iqr = q3 - q1

    if iqr == 0:
        iqr = 1.0

    train_norm = (
        train_score - median
    ) / iqr

    other_norm = [
        (
            s - median
        ) / iqr
        for s in other_scores
    ]

    return (
        train_norm,
        *other_norm
    )

(
    if_train_n,
    if_val_n,
    if_test_n
) = robust_zscore(
    if_train,
    [if_val, if_test]
)

(
    lof_train_n,
    lof_val_n,
    lof_test_n
) = robust_zscore(
    lof_train,
    [lof_val, lof_test]
)

# =============================================================================
# 15. ENSEMBLE
# =============================================================================

print("\n[12] ENSEMBLE ANOMALY SCORE")
print("-" * 90)

ensemble_train = (
    IF_WEIGHT * if_train_n +
    LOF_WEIGHT * lof_train_n
)

ensemble_val = (
    IF_WEIGHT * if_val_n +
    LOF_WEIGHT * lof_val_n
)

ensemble_test = (
    IF_WEIGHT * if_test_n +
    LOF_WEIGHT * lof_test_n
)

print(
    "Weights:",
    f"Isolation Forest={IF_WEIGHT}",
    f"| LOF={LOF_WEIGHT}"
)

# =============================================================================
# 16. BUILD COMPLETE RESULTS DATAFRAME
# =============================================================================

print("\n[13] BUILDING RESULTS")
print("-" * 90)

results = pd.DataFrame({
    "txId": tx_ids,
    "Time step": time_steps,
    "class": data["class"].to_numpy(),
    "IF_score": np.nan,
    "LOF_score": np.nan,
    "ensemble_score": np.nan
})

results.loc[
    train_idx,
    "IF_score"
] = if_train

results.loc[
    val_idx,
    "IF_score"
] = if_val

results.loc[
    test_idx,
    "IF_score"
] = if_test

results.loc[
    train_idx,
    "LOF_score"
] = lof_train

results.loc[
    val_idx,
    "LOF_score"
] = lof_val

results.loc[
    test_idx,
    "LOF_score"
] = lof_test

results.loc[
    train_idx,
    "ensemble_score"
] = ensemble_train

results.loc[
    val_idx,
    "ensemble_score"
] = ensemble_val

results.loc[
    test_idx,
    "ensemble_score"
] = ensemble_test

print(
    "Results shape:",
    results.shape
)

# =============================================================================
# 17. SCORE DISTRIBUTION
# =============================================================================

print("\n[14] MODEL SCORE DISTRIBUTION")
print("=" * 90)

distribution = pd.DataFrame({
    "Split": [
        "Train",
        "Validation",
        "Test"
    ],
    "Samples": [
        len(ensemble_train),
        len(ensemble_val),
        len(ensemble_test)
    ],
    "IF_Mean": [
        np.mean(if_train),
        np.mean(if_val),
        np.mean(if_test)
    ],
    "IF_Std": [
        np.std(if_train),
        np.std(if_val),
        np.std(if_test)
    ],
    "LOF_Mean": [
        np.mean(lof_train),
        np.mean(lof_val),
        np.mean(lof_test)
    ],
    "LOF_Std": [
        np.std(lof_train),
        np.std(lof_val),
        np.std(lof_test)
    ],
    "Ensemble_Mean": [
        np.mean(ensemble_train),
        np.mean(ensemble_val),
        np.mean(ensemble_test)
    ],
    "Ensemble_Std": [
        np.std(ensemble_train),
        np.std(ensemble_val),
        np.std(ensemble_test)
    ]
})

print(
    distribution.to_string(
        index=False
    )
)

# =============================================================================
# 18. TOP ANOMALIES
# =============================================================================

print("\n[15] TOP ANOMALOUS TRANSACTIONS")
print("=" * 90)

test_results = results.loc[
    test_idx
].copy()

test_results = test_results.sort_values(
    "ensemble_score",
    ascending=False
)

print(
    test_results[
        [
            "txId",
            "Time step",
            "class",
            "IF_score",
            "LOF_score",
            "ensemble_score"
        ]
    ].head(30).to_string(
        index=False
    )
)

# =============================================================================
# 19. POST-HOC CLASS ANALYSIS
# =============================================================================
# IMPORTANT:
# Class labels were NOT used for model training or feature selection.
# They are used here ONLY to understand what the anomaly detector finds.

print("\n[16] POST-HOC CLASS ANALYSIS")
print("=" * 90)

overall_class3 = (
    results["class"].eq(3).mean()
)

print(
    f"Overall Class-3 percentage: "
    f"{overall_class3 * 100:.2f}%"
)

for k in [
    50,
    100,
    500,
    1000,
    5000
]:

    top = test_results.head(k)

    class3_count = (
        top["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / k
    )

    enrichment = (
        class3_pct /
        overall_class3
        if overall_class3 > 0
        else np.nan
    )

    print(
        f"Top {k:5d}: "
        f"Class-3 = {class3_pct*100:6.2f}% | "
        f"Enrichment = {enrichment:.3f}x"
    )

# =============================================================================
# 20. CLASS-WISE SCORE ANALYSIS
# =============================================================================

print("\n[17] CLASS-WISE ENSEMBLE SCORE ANALYSIS")
print("=" * 90)

class_analysis = (
    test_results
    .groupby("class")["ensemble_score"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(
    class_analysis.to_string()
)

# =============================================================================
# 21. CLASS-WISE QUANTILES
# =============================================================================

print("\n[18] CLASS-WISE QUANTILES")
print("=" * 90)

class_quantiles = (
    test_results
    .groupby("class")["ensemble_score"]
    .quantile(
        [
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
    .unstack()
)

class_quantiles.columns = [
    "Q01",
    "Q05",
    "Q10",
    "Q25",
    "Q50",
    "Q75",
    "Q90",
    "Q95",
    "Q99"
]

print(
    class_quantiles.to_string()
)

# =============================================================================
# 22. TEMPORAL ANALYSIS
# =============================================================================

print("\n[19] TEMPORAL ANOMALY ANALYSIS")
print("=" * 90)

temporal = (
    test_results
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly=("ensemble_score", "mean"),
        Median_Anomaly=("ensemble_score", "median"),
        Max_Anomaly=("ensemble_score", "max"),
        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"] /
    temporal["Transactions"] *
    100
)

# Sort by anomaly intensity
temporal_sorted = temporal.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print(
    temporal_sorted.head(15).to_string()
)

# =============================================================================
# 23. MODEL AGREEMENT
# =============================================================================

print("\n[20] MODEL AGREEMENT")
print("=" * 90)

# Top 1000 from each model

top_k = min(
    1000,
    len(test_results)
)

if_top = set(
    test_results
    .sort_values(
        "IF_score",
        ascending=False
    )
    .head(top_k)["txId"]
)

lof_top = set(
    test_results
    .sort_values(
        "LOF_score",
        ascending=False
    )
    .head(top_k)["txId"]
)

ensemble_top = set(
    test_results
    .sort_values(
        "ensemble_score",
        ascending=False
    )
    .head(top_k)["txId"]
)

if_lof_overlap = len(
    if_top & lof_top
)

if_ensemble_overlap = len(
    if_top & ensemble_top
)

lof_ensemble_overlap = len(
    lof_top & ensemble_top
)

all_three = len(
    if_top &
    lof_top &
    ensemble_top
)

print(
    f"Top {top_k} IF ∩ LOF:",
    if_lof_overlap
)

print(
    f"Top {top_k} IF ∩ Ensemble:",
    if_ensemble_overlap
)

print(
    f"Top {top_k} LOF ∩ Ensemble:",
    lof_ensemble_overlap
)

print(
    f"Top {top_k} common to all three:",
    all_three
)

# =============================================================================
# 24. FEATURE SUMMARY
# =============================================================================

print("\n[21] FINAL FEATURE SUMMARY")
print("=" * 90)

print(
    "Original numeric candidates:",
    len(candidate_features)
)

print(
    "After variance filtering:",
    len(variance_features)
)

print(
    "Removed by correlation:",
    len(to_remove)
)

print(
    "Final unsupervised features:",
    len(selected_features)
)

print("\nFinal features:")

for i, f in enumerate(
    selected_features,
    1
):
    print(
        f"{i:3d}. {f}"
    )

# =============================================================================
# 25. SAVE RESULTS
# =============================================================================

print("\n[22] SAVING RESULTS")
print("=" * 90)

results_file = (
    "ellipticpp_unsupervised_"
    "if_lof_ensemble_results.csv"
)

features_file = (
    "ellipticpp_unsupervised_"
    "selected_features.txt"
)

temporal_file = (
    "ellipticpp_unsupervised_"
    "temporal_analysis.csv"
)

results.to_csv(
    results_file,
    index=False
)

with open(
    features_file,
    "w",
    encoding="utf-8"
) as f:

    f.write(
        "BIT-TRACE LABEL-INDEPENDENT "
        "UNSUPERVISED FEATURE SET\n"
    )

    f.write(
        "=" * 70 + "\n"
    )

    for i, feature in enumerate(
        selected_features,
        1
    ):

        f.write(
            f"{i}. {feature}\n"
        )

temporal.to_csv(
    temporal_file
)

print("✓ Results saved:")
print(" ", results_file)
print(" ", features_file)
print(" ", temporal_file)

# =============================================================================
# 26. FINAL STATUS
# =============================================================================

print("\n")
print("=" * 90)
print("PIPELINE COMPLETE")
print("=" * 90)

print("✓ Label-independent feature selection")
print("✓ Median imputation")
print("✓ Low-variance filtering")
print("✓ Correlation redundancy filtering")
print("✓ Temporal split preserved")
print("✓ Isolation Forest")
print("✓ LOF")
print("✓ Ensemble anomaly score")
print("✓ Post-hoc class analysis")
print("✓ Temporal anomaly analysis")
print("✓ Model agreement analysis")
print("✓ Results exported")

print("\nIMPORTANT:")
print(
    "Class labels were NOT used for feature selection "
    "or model training."
)

print(
    "They were used only for post-hoc evaluation."
)

print("\nNEXT BIT-TRACE PHASE:")
print(
    "Use txs_edgelist.csv to generate graph/transaction-network "
    "features and combine them with this anomaly engine."
)

print("=" * 90)

==========================================================================================
BIT-TRACE — LABEL-INDEPENDENT UNSUPERVISED ANOMALY PIPELINE
==========================================================================================

[1] PREPARING INPUT DATA
------------------------------------------------------------------------------------------
✓ Existing loaded variables detected
✓ Reusing current notebook data

[2] DATA CHECK
------------------------------------------------------------------------------------------
Rows: 203769
Time range: 1 to 49
Missing txId: 0
Missing time: 0

Post-hoc class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[3] LABEL-INDEPENDENT FEATURE CANDIDATES
------------------------------------------------------------------------------------------
Candidate numeric features: 13
Raw feature matrix: (203769, 13)

[4] MEDIAN IMPUTATION
------------------------------------------------------------------------------------------
NaN before: 0
NaN after: 0

[5] LOW-VARIANCE FILTER
------------------------------------------------------------------------------------------
Before: 13
After : 13
Removed: 0

[6] CORRELATION REDUNDANCY FILTER
------------------------------------------------------------------------------------------
Calculating correlation matrix for 13 features...
Before correlation filter: 13
Highly correlated removed : 0
Final selected features   : 13

Selected features:
 1. Local_feature_22
 2. Local_feature_25
 3. Local_feature_47
 4. Local_feature_52
 5. Local_feature_53
 6. Local_feature_54
 7. Local_feature_59
 8. Local_feature_77
 9. Local_feature_89
10. Local_feature_90
11. Aggregate_feature_14
12. Aggregate_feature_21
13. Aggregate_feature_32

Final X shape: (203769, 13)

[7] STANDARDIZATION
------------------------------------------------------------------------------------------
Scaled matrix: (203769, 13)
NaN: 0 | Inf: 0

[8] TEMPORAL SPLIT
------------------------------------------------------------------------------------------
Train      : 136,265 (time 1–34)
Validation : 30,680 (time 35–41)
Test       : 36,824 (time 42–49)

Train matrix: (136265, 13)
Val matrix  : (30680, 13)
Test matrix : (36824, 13)

[9] TRAINING ISOLATION FOREST
------------------------------------------------------------------------------------------
✓ Isolation Forest trained
Trees: 300
IF train scores: 136265
IF val scores  : 30680
IF test scores : 36824

[10] TRAINING LOF
------------------------------------------------------------------------------------------
LOF training samples: 30000
✓ LOF trained
Neighbors: 35
LOF train scores: 136265
LOF val scores  : 30680
LOF test scores : 36824

[11] NORMALIZING ANOMALY SCORES
------------------------------------------------------------------------------------------

[12] ENSEMBLE ANOMALY SCORE
------------------------------------------------------------------------------------------
Weights: Isolation Forest=0.6 | LOF=0.4

[13] BUILDING RESULTS
------------------------------------------------------------------------------------------
Results shape: (203769, 6)

[14] MODEL SCORE DISTRIBUTION
==========================================================================================
     Split  Samples   IF_Mean   IF_Std  LOF_Mean   LOF_Std  Ensemble_Mean  Ensemble_Std
     Train   136265 -0.128006 0.087285  0.011819  6.550781       0.900000      8.498501
Validation    30680 -0.123841 0.087784  0.446517  7.948896       1.492002     10.338592
      Test    36824 -0.121768 0.090392  0.947241 13.444645       2.151236     17.421773

[15] TOP ANOMALOUS TRANSACTIONS
==========================================================================================
     txId  Time step  class  IF_score  LOF_score  ensemble_score
 94260854         43      2  0.234287 480.212006      619.576101
157243941         45      2  0.242643 462.422791      596.838303
164687671         45      2  0.245185 442.975220      571.925992
218135759         47      2  0.180700 435.803558      562.194369
 71765185         42      2  0.172069 415.241058      535.759469
218053350         47      2  0.187666 413.187988      533.257194
 94312679         43      2  0.226163 408.901398      528.081939
164687325         45      2  0.184281 399.694580      515.929262
 71460914         42      2  0.193561 394.047485      508.766417
 70777472         42      2  0.186428 383.033936      494.586665
155816203         45      2  0.185330 238.503510      309.276587
155816197         45      2  0.186235 237.355545      307.812352
155816200         45      2  0.186235 237.340927      307.793583
 48285886         46      2  0.186246 234.483002      304.129583
218054027         47      2  0.184388 234.483902      304.115239
164688873         45      2  0.183462 234.475388      304.096638
219922357         47      2  0.182692 234.477600      304.093063
218293512         47      2  0.182692 234.477127      304.092452
218275609         47      2  0.182692 234.477036      304.092330
218135738         47      2  0.182692 234.476959      304.092208
219415306         47      2  0.182692 234.476501      304.091628
218136481         47      2  0.182692 234.476318      304.091415
218293648         47      2  0.182692 234.476257      304.091354
195599243         46      2  0.182692 234.476257      304.091354
218293510         47      2  0.182692 234.476151      304.091201
218053353         47      2  0.182692 234.475616      304.090499
218053690         47      2  0.182692 234.475616      304.090499
218136485         47      2  0.182692 234.467850      304.080550
 73148377         47      2  0.181808 234.397156      303.982553
  7564652         47      2  0.181808 234.090042      303.588816

[16] POST-HOC CLASS ANALYSIS
==========================================================================================
Overall Class-3 percentage: 77.15%
Top    50: Class-3 =   0.00% | Enrichment = 0.000x
Top   100: Class-3 =   1.00% | Enrichment = 0.013x
Top   500: Class-3 =  62.80% | Enrichment = 0.814x
Top  1000: Class-3 =  57.40% | Enrichment = 0.744x
Top  5000: Class-3 =  53.26% | Enrichment = 0.690x

[17] CLASS-WISE ENSEMBLE SCORE ANALYSIS
==========================================================================================
       Samples      Mean        Std       Min    Median         Max
class
1          408  0.641146   1.034770 -0.276214  0.428022    9.295461
2         8433  6.042738  35.799768 -0.281061  1.770574  619.576101
3        27983  1.000505   2.699916 -0.301808  0.382149  126.619481

[18] CLASS-WISE QUANTILES
==========================================================================================
            Q01       Q05       Q10       Q25       Q50       Q75       Q90       Q95         Q99
class
1     -0.240660 -0.235890 -0.185447 -0.079843  0.428022  0.838737  1.990234  2.731280    3.969665
2     -0.232219 -0.126229  0.031680  0.718345  1.770574  2.569258  4.067535  5.957582  292.647646
3     -0.254793 -0.228730 -0.187781 -0.053665  0.382149  1.072832  2.424342  3.308514   14.594211

[19] TEMPORAL ANOMALY ANALYSIS
==========================================================================================
           Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly  Class3_Count   Class3_%
Time step
47                 5121      3.573302        0.574518   562.194369          4275  83.479789
45                 5598      3.048851        0.330680   596.838303          4377  78.188639
46                 3519      2.212447        0.833741   304.129583          2807  79.766979
49                 2454      2.194747        0.580581   302.537382          1978  80.603097
43                 5063      1.736661        0.762134   619.576101          3693  72.940944
42                 7140      1.713538        0.647268   535.759469          4986  69.831933
48                 2954      1.428204        0.385179   302.357103          2483  84.055518
44                 4975      1.092055        0.431125   126.619481          3384  68.020101

[20] MODEL AGREEMENT
==========================================================================================
Top 1000 IF ∩ LOF: 393
Top 1000 IF ∩ Ensemble: 466
Top 1000 LOF ∩ Ensemble: 910
Top 1000 common to all three: 393

[21] FINAL FEATURE SUMMARY
==========================================================================================
Original numeric candidates: 13
After variance filtering: 13
Removed by correlation: 0
Final unsupervised features: 13

Final features:
  1. Local_feature_22
  2. Local_feature_25
  3. Local_feature_47
  4. Local_feature_52
  5. Local_feature_53
  6. Local_feature_54
  7. Local_feature_59
  8. Local_feature_77
  9. Local_feature_89
 10. Local_feature_90
 11. Aggregate_feature_14
 12. Aggregate_feature_21
 13. Aggregate_feature_32

[22] SAVING RESULTS
==========================================================================================
✓ Results saved:
  ellipticpp_unsupervised_if_lof_ensemble_results.csv
  ellipticpp_unsupervised_selected_features.txt
  ellipticpp_unsupervised_temporal_analysis.csv


==========================================================================================
PIPELINE COMPLETE
==========================================================================================
✓ Label-independent feature selection
✓ Median imputation
✓ Low-variance filtering
✓ Correlation redundancy filtering
✓ Temporal split preserved
✓ Isolation Forest
✓ LOF
✓ Ensemble anomaly score
✓ Post-hoc class analysis
✓ Temporal anomaly analysis
✓ Model agreement analysis
✓ Results exported

IMPORTANT:
Class labels were NOT used for feature selection or model training.
They were used only for post-hoc evaluation.

NEXT BIT-TRACE PHASE:
Use txs_edgelist.csv to generate graph/transaction-network features and combine them with this anomaly engine.
==========================================================================================

In [42]:
# =============================================================================
# BIT-TRACE — ELLIPTIC++ GRAPH + BEHAVIORAL UNSUPERVISED ANOMALY ENGINE
# SINGLE OPTIMIZED PIPELINE
# =============================================================================

import os
import gc
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor

print("=" * 90)
print("BIT-TRACE — GRAPH + BEHAVIORAL UNSUPERVISED ANOMALY PIPELINE")
print("=" * 90)


# =============================================================================
# 1. FILE DISCOVERY
# =============================================================================

print("\n[1] LOCATING ELLIPTIC++ FILES")
print("-" * 90)

SEARCH_ROOT = r"C:\Users\YASHIKA\Desktop\bit-trace"

FEATURE_FILE = None
CLASS_FILE = None
EDGE_FILE = None

for root, dirs, files in os.walk(SEARCH_ROOT):

    for f in files:

        fl = f.lower()

        full = os.path.join(root, f)

        if fl == "txs_features.csv" and FEATURE_FILE is None:
            FEATURE_FILE = full

        elif fl == "txs_classes.csv" and CLASS_FILE is None:
            CLASS_FILE = full

        elif fl == "txs_edgelist.csv" and EDGE_FILE is None:
            EDGE_FILE = full


print("FEATURE :", FEATURE_FILE)
print("CLASS   :", CLASS_FILE)
print("EDGES   :", EDGE_FILE)

if EDGE_FILE is None:
    raise FileNotFoundError(
        "txs_edgelist.csv not found."
    )

if FEATURE_FILE is None:
    raise FileNotFoundError(
        "txs_features.csv not found."
    )

if CLASS_FILE is None:
    raise FileNotFoundError(
        "txs_classes.csv not found."
    )


# =============================================================================
# 2. SELECTED BEHAVIORAL FEATURES
# =============================================================================

BEHAVIOR_FEATURES = [
    "Local_feature_22",
    "Local_feature_25",
    "Local_feature_47",
    "Local_feature_52",
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_59",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_14",
    "Aggregate_feature_21",
    "Aggregate_feature_32"
]

print("\n[2] BEHAVIORAL FEATURES")
print("-" * 90)

for i, f in enumerate(BEHAVIOR_FEATURES, 1):
    print(f"{i:2d}. {f}")


# =============================================================================
# 3. LOAD ONLY REQUIRED TRANSACTION DATA
# =============================================================================

print("\n[3] LOADING TRANSACTION DATA")
print("-" * 90)

header = pd.read_csv(FEATURE_FILE, nrows=0)

cols = header.columns.tolist()

id_col = "txId"
time_col = "Time step"

required = [id_col, time_col] + BEHAVIOR_FEATURES

missing = [c for c in required if c not in cols]

if missing:
    raise ValueError(
        f"Missing transaction columns: {missing}"
    )

data = pd.read_csv(
    FEATURE_FILE,
    usecols=required,
    low_memory=False
)

data[id_col] = pd.to_numeric(
    data[id_col],
    errors="coerce"
).astype("Int64")

data[time_col] = pd.to_numeric(
    data[time_col],
    errors="coerce"
)

print("Transaction data:", data.shape)

print("Missing txId:", data[id_col].isna().sum())
print("Missing time:", data[time_col].isna().sum())


# =============================================================================
# 4. NUMERIC CLEANING
# =============================================================================

print("\n[4] CLEANING BEHAVIORAL FEATURES")
print("-" * 90)

X_behavior = data[BEHAVIOR_FEATURES].copy()

X_behavior = X_behavior.replace(
    [np.inf, -np.inf],
    np.nan
)

imputer = SimpleImputer(strategy="median")

X_behavior = imputer.fit_transform(X_behavior)

X_behavior = np.asarray(
    X_behavior,
    dtype=np.float32
)

print("Behavior matrix:", X_behavior.shape)
print("NaN:", np.isnan(X_behavior).sum())
print("Inf:", np.isinf(X_behavior).sum())


# =============================================================================
# 5. LOAD EDGE LIST
# =============================================================================

print("\n[5] LOADING TRANSACTION EDGE LIST")
print("-" * 90)

edge_header = pd.read_csv(
    EDGE_FILE,
    nrows=5
)

print("Edge columns detected:")
print(edge_header.columns.tolist())

# Re-read header only
eh = pd.read_csv(
    EDGE_FILE,
    nrows=0
)

edge_cols = eh.columns.tolist()

print("Number of edge columns:", len(edge_cols))


# =============================================================================
# 6. AUTOMATIC EDGE COLUMN DETECTION
# =============================================================================

def find_source_target(columns):

    lower_map = {
        c.lower().strip(): c
        for c in columns
    }

    source_candidates = [
        "txid1",
        "txid_1",
        "source",
        "src",
        "from",
        "source_txid",
        "tx1",
        "id1"
    ]

    target_candidates = [
        "txid2",
        "txid_2",
        "target",
        "dst",
        "to",
        "target_txid",
        "tx2",
        "id2"
    ]

    source = None
    target = None

    for c in source_candidates:
        if c in lower_map:
            source = lower_map[c]
            break

    for c in target_candidates:
        if c in lower_map:
            target = lower_map[c]
            break

    return source, target


SOURCE_COL, TARGET_COL = find_source_target(edge_cols)

print("\nDetected source:", SOURCE_COL)
print("Detected target:", TARGET_COL)


# =============================================================================
# 7. FALLBACK EDGE DETECTION
# =============================================================================

if SOURCE_COL is None or TARGET_COL is None:

    numeric_candidates = []

    sample_edges = pd.read_csv(
        EDGE_FILE,
        nrows=10000
    )

    for c in sample_edges.columns:

        converted = pd.to_numeric(
            sample_edges[c],
            errors="coerce"
        )

        valid_ratio = converted.notna().mean()

        if valid_ratio > 0.95:
            numeric_candidates.append(c)

    print(
        "Numeric edge candidates:",
        numeric_candidates
    )

    if len(numeric_candidates) >= 2:

        SOURCE_COL = numeric_candidates[0]
        TARGET_COL = numeric_candidates[1]

    else:

        raise ValueError(
            "Could not automatically detect source/target edge columns. "
            f"Columns found: {edge_cols}"
        )


print(
    f"Using edge columns: {SOURCE_COL} -> {TARGET_COL}"
)


# =============================================================================
# 8. LOAD EDGE LIST
# =============================================================================

print("\n[6] READING EDGE LIST")
print("-" * 90)

edges = pd.read_csv(
    EDGE_FILE,
    usecols=[SOURCE_COL, TARGET_COL],
    low_memory=False
)

edges.columns = ["source", "target"]

edges["source"] = pd.to_numeric(
    edges["source"],
    errors="coerce"
)

edges["target"] = pd.to_numeric(
    edges["target"],
    errors="coerce"
)

edges = edges.dropna(
    subset=["source", "target"]
)

edges["source"] = edges["source"].astype(np.int64)
edges["target"] = edges["target"].astype(np.int64)

print("Raw edges:", len(edges))


# =============================================================================
# 9. REMOVE SELF LOOPS
# =============================================================================

edges = edges[
    edges["source"] != edges["target"]
]

print("After self-loop removal:", len(edges))


# =============================================================================
# 10. REMOVE DUPLICATE EDGES
# =============================================================================

edges = edges.drop_duplicates()

print("Unique edges:", len(edges))


# =============================================================================
# 11. GRAPH FEATURE ENGINEERING
# =============================================================================

print("\n[7] GENERATING GRAPH FEATURES")
print("-" * 90)

tx_ids_array = data[id_col].to_numpy(
    dtype=np.int64
)

n = len(data)

tx_to_idx = pd.Series(
    np.arange(n, dtype=np.int32),
    index=tx_ids_array
)

source_idx = tx_to_idx.reindex(
    edges["source"]
).to_numpy()

target_idx = tx_to_idx.reindex(
    edges["target"]
).to_numpy()

valid = (
    ~pd.isna(source_idx)
    &
    ~pd.isna(target_idx)
)

source_idx = source_idx[valid].astype(np.int32)
target_idx = target_idx[valid].astype(np.int32)

print("Valid graph edges:", len(source_idx))


# =============================================================================
# 12. DEGREE FEATURES
# =============================================================================

print("\n[8] DEGREE FEATURES")
print("-" * 90)

in_degree = np.bincount(
    target_idx,
    minlength=n
).astype(np.float32)

out_degree = np.bincount(
    source_idx,
    minlength=n
).astype(np.float32)

total_degree = (
    in_degree +
    out_degree
)

print(
    "Mean total degree:",
    total_degree.mean()
)

print(
    "Maximum total degree:",
    total_degree.max()
)


# =============================================================================
# 13. RECIPROCAL / BIDIRECTIONAL CONNECTION
# =============================================================================

print("\n[9] RECIPROCAL EDGE FEATURES")
print("-" * 90)

# Encode directed edge pairs into a structured array.
# This avoids Python set of millions of tuples.

edge_pairs = np.empty(
    len(source_idx),
    dtype=[
        ("s", np.int32),
        ("t", np.int32)
    ]
)

edge_pairs["s"] = source_idx
edge_pairs["t"] = target_idx

reverse_pairs = np.empty(
    len(source_idx),
    dtype=[
        ("s", np.int32),
        ("t", np.int32)
    ]
)

reverse_pairs["s"] = target_idx
reverse_pairs["t"] = source_idx

reverse_exists = np.isin(
    reverse_pairs,
    edge_pairs
)

reciprocal_degree = np.zeros(
    n,
    dtype=np.float32
)

np.add.at(
    reciprocal_degree,
    source_idx[reverse_exists],
    1
)

np.add.at(
    reciprocal_degree,
    target_idx[reverse_exists],
    1
)

print(
    "Nodes with reciprocal connections:",
    np.count_nonzero(reciprocal_degree)
)


# =============================================================================
# 14. APPROXIMATE NEIGHBORHOOD FEATURES
# =============================================================================

print("\n[10] NEIGHBORHOOD FEATURES")
print("-" * 90)

# Neighbor count already represented by degree.
# Add edge participation and degree imbalance.

degree_imbalance = np.abs(
    in_degree -
    out_degree
)

in_out_ratio = (
    (in_degree + 1.0) /
    (out_degree + 1.0)
)

log_total_degree = np.log1p(
    total_degree
)

log_in_degree = np.log1p(
    in_degree
)

log_out_degree = np.log1p(
    out_degree
)

log_reciprocal = np.log1p(
    reciprocal_degree
)


# =============================================================================
# 15. GRAPH FEATURE MATRIX
# =============================================================================

graph_features = np.column_stack([
    in_degree,
    out_degree,
    total_degree,
    degree_imbalance,
    in_out_ratio,
    log_total_degree,
    log_in_degree,
    log_out_degree,
    reciprocal_degree,
    log_reciprocal
]).astype(np.float32)

GRAPH_FEATURE_NAMES = [
    "graph_in_degree",
    "graph_out_degree",
    "graph_total_degree",
    "graph_degree_imbalance",
    "graph_in_out_ratio",
    "graph_log_total_degree",
    "graph_log_in_degree",
    "graph_log_out_degree",
    "graph_reciprocal_degree",
    "graph_log_reciprocal_degree"
]

print(
    "Graph feature matrix:",
    graph_features.shape
)


# =============================================================================
# 16. COMBINE BEHAVIOR + GRAPH
# =============================================================================

print("\n[11] COMBINING BEHAVIORAL + GRAPH FEATURES")
print("-" * 90)

X_combined = np.column_stack([
    X_behavior,
    graph_features
]).astype(np.float32)

ALL_FEATURE_NAMES = (
    BEHAVIOR_FEATURES +
    GRAPH_FEATURE_NAMES
)

print("Behavior features:", len(BEHAVIOR_FEATURES))
print("Graph features   :", len(GRAPH_FEATURE_NAMES))
print("Total features   :", len(ALL_FEATURE_NAMES))
print("Final X shape     :", X_combined.shape)


# =============================================================================
# 17. CLEAN FINAL MATRIX
# =============================================================================

X_combined = np.nan_to_num(
    X_combined,
    nan=0.0,
    posinf=0.0,
    neginf=0.0
).astype(np.float32)


# =============================================================================
# 18. STANDARDIZATION
# =============================================================================

print("\n[12] STANDARDIZATION")
print("-" * 90)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(
    X_combined
).astype(np.float32)

print("Scaled:", X_scaled.shape)

del X_combined
gc.collect()


# =============================================================================
# 19. TEMPORAL SPLIT
# =============================================================================

print("\n[13] TEMPORAL SPLIT")
print("-" * 90)

time_steps = data[time_col].to_numpy(
    dtype=np.int16
)

train_idx = np.where(
    time_steps <= 34
)[0]

val_idx = np.where(
    (time_steps >= 35) &
    (time_steps <= 41)
)[0]

test_idx = np.where(
    time_steps >= 42
)[0]

print(
    "Train:",
    len(train_idx),
    "(1–34)"
)

print(
    "Validation:",
    len(val_idx),
    "(35–41)"
)

print(
    "Test:",
    len(test_idx),
    "(42–49)"
)


X_train = X_scaled[train_idx]
X_val = X_scaled[val_idx]
X_test = X_scaled[test_idx]


# =============================================================================
# 20. ISOLATION FOREST
# =============================================================================

print("\n[14] TRAINING ISOLATION FOREST")
print("-" * 90)

IF_MODEL = IsolationForest(
    n_estimators=300,
    contamination="auto",
    max_samples="auto",
    max_features=1.0,
    random_state=42,
    n_jobs=-1
)

IF_MODEL.fit(
    X_train
)

if_train = IF_MODEL.score_samples(X_train)
if_val = IF_MODEL.score_samples(X_val)
if_test = IF_MODEL.score_samples(X_test)

print("Isolation Forest complete.")


# =============================================================================
# 21. LOF
# =============================================================================

print("\n[15] TRAINING LOF")
print("-" * 90)

# Use bounded reference sample to keep runtime reasonable.
rng = np.random.default_rng(42)

LOF_SAMPLE_SIZE = min(
    30000,
    len(X_train)
)

lof_reference_idx = rng.choice(
    len(X_train),
    size=LOF_SAMPLE_SIZE,
    replace=False
)

X_lof_train = X_train[
    lof_reference_idx
]

LOF_MODEL = LocalOutlierFactor(
    n_neighbors=35,
    novelty=True,
    contamination="auto",
    n_jobs=-1
)

LOF_MODEL.fit(
    X_lof_train
)

lof_train = LOF_MODEL.score_samples(X_train)
lof_val = LOF_MODEL.score_samples(X_val)
lof_test = LOF_MODEL.score_samples(X_test)

print("LOF complete.")


# =============================================================================
# 22. SCORE NORMALIZATION
# =============================================================================

print("\n[16] NORMALIZING MODEL SCORES")
print("-" * 90)

def robust_normalize(train_score, score):

    median = np.median(
        train_score
    )

    q25, q75 = np.percentile(
        train_score,
        [25, 75]
    )

    iqr = q75 - q25

    if iqr == 0:
        iqr = 1.0

    return (
        score - median
    ) / iqr


if_train_n = robust_normalize(
    if_train,
    if_train
)

if_val_n = robust_normalize(
    if_train,
    if_val
)

if_test_n = robust_normalize(
    if_train,
    if_test
)

lof_train_n = robust_normalize(
    lof_train,
    lof_train
)

lof_val_n = robust_normalize(
    lof_train,
    lof_val
)

lof_test_n = robust_normalize(
    lof_train,
    lof_test
)


# =============================================================================
# 23. ANOMALY DIRECTION
# =============================================================================

# sklearn IsolationForest score_samples:
# lower = more abnormal.
#
# sklearn LOF score_samples:
# lower = more abnormal.
#
# Convert them so:
# HIGHER = MORE ANOMALOUS

if_train_anom = -if_train_n
if_val_anom = -if_val_n
if_test_anom = -if_test_n

lof_train_anom = -lof_train_n
lof_val_anom = -lof_val_n
lof_test_anom = -lof_test_n


# =============================================================================
# 24. ENSEMBLE
# =============================================================================

print("\n[17] BUILDING ENSEMBLE")
print("-" * 90)

W_IF = 0.60
W_LOF = 0.40

ensemble_train = (
    W_IF * if_train_anom +
    W_LOF * lof_train_anom
)

ensemble_val = (
    W_IF * if_val_anom +
    W_LOF * lof_val_anom
)

ensemble_test = (
    W_IF * if_test_anom +
    W_LOF * lof_test_anom
)

print(
    f"Weights: IF={W_IF} | LOF={W_LOF}"
)


# =============================================================================
# 25. CREATE FULL SCORE VECTOR
# =============================================================================

full_if = np.empty(
    len(data),
    dtype=np.float32
)

full_lof = np.empty(
    len(data),
    dtype=np.float32
)

full_ensemble = np.empty(
    len(data),
    dtype=np.float32
)

full_if[train_idx] = if_train_anom
full_if[val_idx] = if_val_anom
full_if[test_idx] = if_test_anom

full_lof[train_idx] = lof_train_anom
full_lof[val_idx] = lof_val_anom
full_lof[test_idx] = lof_test_anom

full_ensemble[train_idx] = ensemble_train
full_ensemble[val_idx] = ensemble_val
full_ensemble[test_idx] = ensemble_test


# =============================================================================
# 26. RESULTS DATAFRAME
# =============================================================================

print("\n[18] BUILDING RESULTS")
print("-" * 90)

results = pd.DataFrame({
    "txId": data[id_col].astype(np.int64),
    "Time step": data[time_col].astype(np.int16),
    "IF_anomaly": full_if,
    "LOF_anomaly": full_lof,
    "ensemble_anomaly": full_ensemble
})

results["split"] = "train"

results.loc[
    val_idx,
    "split"
] = "validation"

results.loc[
    test_idx,
    "split"
] = "test"


# =============================================================================
# 27. TOP ANOMALIES
# =============================================================================

print("\n[19] TOP ANOMALOUS TRANSACTIONS")
print("-" * 90)

top_n = min(
    100,
    len(results)
)

top_anomalies = results.nlargest(
    top_n,
    "ensemble_anomaly"
)

print(
    top_anomalies[
        [
            "txId",
            "Time step",
            "split",
            "IF_anomaly",
            "LOF_anomaly",
            "ensemble_anomaly"
        ]
    ].head(30).to_string(index=False)
)


# =============================================================================
# 28. TEMPORAL ANALYSIS
# =============================================================================

print("\n[20] TEMPORAL ANOMALY ANALYSIS")
print("-" * 90)

temporal = (
    results
    .groupby("Time step")
    .agg(
        Transactions=("txId", "size"),
        Mean_Anomaly=("ensemble_anomaly", "mean"),
        Median_Anomaly=("ensemble_anomaly", "median"),
        Max_Anomaly=("ensemble_anomaly", "max")
    )
    .sort_values(
        "Mean_Anomaly",
        ascending=False
    )
)

print(
    temporal.head(15).to_string()
)


# =============================================================================
# 29. GRAPH FEATURE SUMMARY
# =============================================================================

print("\n[21] GRAPH FEATURE SUMMARY")
print("-" * 90)

graph_summary = pd.DataFrame({
    "Feature": GRAPH_FEATURE_NAMES,
    "Mean": graph_features.mean(axis=0),
    "Std": graph_features.std(axis=0),
    "Min": graph_features.min(axis=0),
    "Median": np.median(graph_features, axis=0),
    "Max": graph_features.max(axis=0)
})

print(
    graph_summary.to_string(index=False)
)


# =============================================================================
# 30. SAVE GRAPH FEATURES
# =============================================================================

GRAPH_OUTPUT = (
    "ellipticpp_graph_features.csv"
)

graph_output = pd.DataFrame(
    graph_features,
    columns=GRAPH_FEATURE_NAMES
)

graph_output.insert(
    0,
    "txId",
    data[id_col].astype(np.int64).to_numpy()
)

graph_output.insert(
    1,
    "Time step",
    data[time_col].astype(np.int16).to_numpy()
)

graph_output.to_csv(
    GRAPH_OUTPUT,
    index=False
)


# =============================================================================
# 31. SAVE FINAL ANOMALY RESULTS
# =============================================================================

RESULT_OUTPUT = (
    "ellipticpp_graph_behavioral_anomaly_results.csv"
)

results.to_csv(
    RESULT_OUTPUT,
    index=False
)


# =============================================================================
# 32. SAVE FEATURE LIST
# =============================================================================

FEATURE_OUTPUT = (
    "ellipticpp_graph_behavioral_features.txt"
)

with open(
    FEATURE_OUTPUT,
    "w",
    encoding="utf-8"
) as f:

    f.write(
        "BIT-TRACE FINAL UNSUPERVISED FEATURES\n"
    )
    f.write("=" * 60 + "\n\n")

    f.write(
        "BEHAVIORAL FEATURES\n"
    )

    for x in BEHAVIOR_FEATURES:
        f.write(
            x + "\n"
        )

    f.write(
        "\nGRAPH FEATURES\n"
    )

    for x in GRAPH_FEATURE_NAMES:
        f.write(
            x + "\n"
        )


# =============================================================================
# 33. MEMORY CLEANUP
# =============================================================================

del X_train
del X_val
del X_test
del X_scaled
del X_lof_train

gc.collect()


# =============================================================================
# FINAL STATUS
# =============================================================================

print("\n")
print("=" * 90)
print("BIT-TRACE GRAPH + BEHAVIORAL PIPELINE COMPLETE")
print("=" * 90)

print(
    f"Behavioral features : {len(BEHAVIOR_FEATURES)}"
)

print(
    f"Graph features      : {len(GRAPH_FEATURE_NAMES)}"
)

print(
    f"Total features      : {len(ALL_FEATURE_NAMES)}"
)

print(
    f"Transactions        : {len(data):,}"
)

print(
    f"Graph edges         : {len(edges):,}"
)

print(
    f"Train               : {len(train_idx):,}"
)

print(
    f"Validation          : {len(val_idx):,}"
)

print(
    f"Test                : {len(test_idx):,}"
)

print("\nSaved files:")

print(
    "✓",
    GRAPH_OUTPUT
)

print(
    "✓",
    RESULT_OUTPUT
)

print(
    "✓",
    FEATURE_OUTPUT
)

print("\n")
print("NEXT PHASE:")
print(
    "Use the graph + behavioral anomaly score as the core"
)
print(
    "investigation signal, then add explainability / evidence"
)
print(
    "generation for the BIT-TRACE investigator dashboard."
)

print("=" * 90)

==========================================================================================
BIT-TRACE — GRAPH + BEHAVIORAL UNSUPERVISED ANOMALY PIPELINE
==========================================================================================

[1] LOCATING ELLIPTIC++ FILES
------------------------------------------------------------------------------------------
FEATURE : C:\Users\YASHIKA\Desktop\bit-trace\data\raw\elliptic-plus-plus\txs_features.csv
CLASS   : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv
EDGES   : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv

[2] BEHAVIORAL FEATURES
------------------------------------------------------------------------------------------
 1. Local_feature_22
 2. Local_feature_25
 3. Local_feature_47
 4. Local_feature_52
 5. Local_feature_53
 6. Local_feature_54
 7. Local_feature_59
 8. Local_feature_77
 9. Local_feature_89
10. Local_feature_90
11. Aggregate_feature_14
12. Aggregate_feature_21
13. Aggregate_feature_32

[3] LOADING TRANSACTION DATA
------------------------------------------------------------------------------------------
Transaction data: (203769, 15)
Missing txId: 0
Missing time: 0

[4] CLEANING BEHAVIORAL FEATURES
------------------------------------------------------------------------------------------
Behavior matrix: (203769, 13)
NaN: 0
Inf: 0

[5] LOADING TRANSACTION EDGE LIST
------------------------------------------------------------------------------------------
Edge columns detected:
['txId1', 'txId2']
Number of edge columns: 2

Detected source: txId1
Detected target: txId2
Using edge columns: txId1 -> txId2

[6] READING EDGE LIST
------------------------------------------------------------------------------------------
Raw edges: 234355
After self-loop removal: 234355
Unique edges: 234355

[7] GENERATING GRAPH FEATURES
------------------------------------------------------------------------------------------
Valid graph edges: 234355

[8] DEGREE FEATURES
------------------------------------------------------------------------------------------
Mean total degree: 2.3002026
Maximum total degree: 473.0

[9] RECIPROCAL EDGE FEATURES
------------------------------------------------------------------------------------------
Nodes with reciprocal connections: 0

[10] NEIGHBORHOOD FEATURES
------------------------------------------------------------------------------------------
Graph feature matrix: (203769, 10)

[11] COMBINING BEHAVIORAL + GRAPH FEATURES
------------------------------------------------------------------------------------------
Behavior features: 13
Graph features   : 10
Total features   : 23
Final X shape     : (203769, 23)

[12] STANDARDIZATION
------------------------------------------------------------------------------------------
Scaled: (203769, 23)

[13] TEMPORAL SPLIT
------------------------------------------------------------------------------------------
Train: 136265 (1–34)
Validation: 30680 (35–41)
Test: 36824 (42–49)

[14] TRAINING ISOLATION FOREST
------------------------------------------------------------------------------------------
Isolation Forest complete.

[15] TRAINING LOF
------------------------------------------------------------------------------------------
LOF complete.

[16] NORMALIZING MODEL SCORES
------------------------------------------------------------------------------------------

[17] BUILDING ENSEMBLE
------------------------------------------------------------------------------------------
Weights: IF=0.6 | LOF=0.4

[18] BUILDING RESULTS
------------------------------------------------------------------------------------------

[19] TOP ANOMALOUS TRANSACTIONS
------------------------------------------------------------------------------------------
     txId  Time step      split  IF_anomaly  LOF_anomaly  ensemble_anomaly
 94034375          7      train   -0.015924  1394.735107        557.884460
378195299         16      train    0.008720  1051.857178        420.748108
174780183          9      train    0.247391  1019.455627        407.930695
399702529         12      train    0.011468   977.949158        391.186554
 68460734         10      train    0.246884   860.731628        344.440796
208999710         20      train    0.253129   844.451050        337.932312
234435039         11      train    0.255829   744.239136        297.849152
 30179414         37 validation    0.022045   692.764648        277.119080
  3757070          1      train   -0.193871   550.270264        219.991791
339083170         13      train    0.267630   524.804749        210.082489
 94048122          7      train    0.250693   524.113770        209.795914
 94114483          7      train    0.014111   421.010132        168.412521
298741505         30      train    0.009067   418.248383        167.304794
211155347          2      train    0.558366   409.029480        163.946808
339102373         13      train   -0.183582   370.746399        148.188416
 87811705          4      train   -0.154769   369.524323        147.716858
109128912          2      train    0.204241   359.331696        143.855225
166888653          2      train    0.211963   350.062653        140.152237
 43123513         10      train    0.250342   349.278717        139.861694
346118591         12      train   -0.183582   344.532684        137.702927
243784831         15      train    0.022345   340.877625        136.364456
363389034         19      train    0.014111   336.467682        134.595535
312493838          2      train    0.182436   320.613831        128.354996
312506848          2      train    0.199729   314.973083        126.109062
156760432          2      train    0.153340   300.246307        120.190529
 92797015          2      train    0.166323   294.492371        117.896744
 86688776          4      train   -0.154769   291.449677        116.487007
137064109          2      train    0.157132   277.260620        110.998528
312493732          2      train    0.133190   270.433685        108.253380
 34123925          2      train    0.138736   269.088257        107.718544

[20] TEMPORAL ANOMALY ANALYSIS
------------------------------------------------------------------------------------------
           Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly
Time step
43                 5063      2.724170        0.912523    65.282608
2                  4544      1.832401        0.373431   163.946808
40                 4481      1.546992        0.756387    41.779682
39                 2760      1.516940        0.977554    80.259895
45                 5598      1.437229        0.398776    54.471413
46                 3519      1.405046        0.836679    35.390053
42                 7140      1.353905        0.708009    53.929455
41                 5342      1.344751        0.648749    37.963356
47                 5121      1.339648        0.541131    61.643951
19                 3506      1.200661        0.411680   134.595535
48                 2954      1.162728        0.350089    37.881035
12                 2047      1.152893        0.412061   391.186554
18                 1976      1.058937        0.211524    44.701809
36                 6393      1.051755        0.751481    39.424366
38                 2891      1.021769        0.587550    25.451906

[21] GRAPH FEATURE SUMMARY
------------------------------------------------------------------------------------------
                    Feature     Mean      Std      Min   Median        Max
            graph_in_degree 1.150101 3.909768 0.000000 1.000000 284.000000
           graph_out_degree 1.150101 1.893602 0.000000 1.000000 472.000000
         graph_total_degree 2.300203 4.329238 1.000000 2.000000 473.000000
     graph_degree_imbalance 1.150106 4.207942 0.000000 1.000000 471.000000
         graph_in_out_ratio 1.271300 3.316197 0.004228 1.000000 285.000000
     graph_log_total_degree 1.063617 0.393494 0.693147 1.098612   6.161207
        graph_log_in_degree 0.581222 0.466591 0.000000 0.693147   5.652489
       graph_log_out_degree 0.673280 0.400778 0.000000 0.693147   6.159095
    graph_reciprocal_degree 0.000000 0.000000 0.000000 0.000000   0.000000
graph_log_reciprocal_degree 0.000000 0.000000 0.000000 0.000000   0.000000


==========================================================================================
BIT-TRACE GRAPH + BEHAVIORAL PIPELINE COMPLETE
==========================================================================================
Behavioral features : 13
Graph features      : 10
Total features      : 23
Transactions        : 203,769
Graph edges         : 234,355
Train               : 136,265
Validation          : 30,680
Test                : 36,824

Saved files:
✓ ellipticpp_graph_features.csv
✓ ellipticpp_graph_behavioral_anomaly_results.csv
✓ ellipticpp_graph_behavioral_features.txt


NEXT PHASE:
Use the graph + behavioral anomaly score as the core
investigation signal, then add explainability / evidence
generation for the BIT-TRACE investigator dashboard.
==========================================================================================

In [43]:
# =============================================================================
# BIT-TRACE — EXPLAINABILITY + EVIDENCE GENERATION
# Uses already-generated Graph + Behavioral anomaly results
# Does NOT reload the 662 MB raw feature file
# =============================================================================

import os
import json
import numpy as np
import pandas as pd

from sklearn.preprocessing import RobustScaler

print("=" * 90)
print("BIT-TRACE — EXPLAINABILITY + EVIDENCE GENERATION")
print("=" * 90)

# =============================================================================
# 1. LOCATE SAVED FILES
# =============================================================================

BASE_DIR = r"C:\Users\YASHIKA\Desktop\bit-trace"

RESULT_FILE = os.path.join(
    BASE_DIR,
    "ellipticpp_graph_behavioral_anomaly_results.csv"
)

GRAPH_FILE = os.path.join(
    BASE_DIR,
    "ellipticpp_graph_features.csv"
)

# Also check src / current working directory
SEARCH_ROOTS = [
    BASE_DIR,
    os.path.join(BASE_DIR, "src"),
    os.path.join(BASE_DIR, "data"),
]

def find_file(filename):
    candidates = []

    for root in SEARCH_ROOTS:
        if not os.path.exists(root):
            continue

        for current_root, dirs, files in os.walk(root):
            if filename in files:
                candidates.append(
                    os.path.join(current_root, filename)
                )

    if candidates:
        # Prefer shortest path
        candidates.sort(key=len)
        return candidates[0]

    return None


if not os.path.exists(RESULT_FILE):
    RESULT_FILE = find_file(
        "ellipticpp_graph_behavioral_anomaly_results.csv"
    )

if not os.path.exists(GRAPH_FILE):
    GRAPH_FILE = find_file(
        "ellipticpp_graph_features.csv"
    )

print("\n[1] FILE CHECK")
print("-" * 90)

print("RESULT FILE:", RESULT_FILE)
print("GRAPH FILE :", GRAPH_FILE)

if RESULT_FILE is None or not os.path.exists(RESULT_FILE):
    raise FileNotFoundError(
        "ellipticpp_graph_behavioral_anomaly_results.csv not found."
    )

if GRAPH_FILE is None or not os.path.exists(GRAPH_FILE):
    raise FileNotFoundError(
        "ellipticpp_graph_features.csv not found."
    )

print("✓ Required files found")


# =============================================================================
# 2. LOAD ANOMALY RESULTS
# =============================================================================

print("\n[2] LOADING ANOMALY RESULTS")
print("-" * 90)

results = pd.read_csv(RESULT_FILE)

print("Shape:", results.shape)
print("Columns:")
print(results.columns.tolist())

# Normalize column names
results.columns = [
    str(c).strip()
    for c in results.columns
]

# Required columns
required_basic = [
    "txId",
    "Time step",
    "split",
]

missing = [
    c for c in required_basic
    if c not in results.columns
]

if missing:
    raise ValueError(
        f"Missing required columns in results file: {missing}"
    )

print("✓ Results loaded")


# =============================================================================
# 3. LOAD GRAPH FEATURES
# =============================================================================

print("\n[3] LOADING GRAPH FEATURES")
print("-" * 90)

graph = pd.read_csv(GRAPH_FILE)

print("Shape:", graph.shape)
print("Columns:")
print(graph.columns.tolist())

if "txId" not in graph.columns:
    raise ValueError(
        "txId column not found in graph feature file."
    )

print("✓ Graph features loaded")


# =============================================================================
# 4. MERGE GRAPH EVIDENCE
# =============================================================================

print("\n[4] MERGING GRAPH EVIDENCE")
print("-" * 90)

# Avoid duplicate columns
graph_cols = [
    c for c in graph.columns
    if c == "txId" or c.startswith("graph_")
]

graph_small = graph[graph_cols].copy()

# Ensure one row per txId
graph_small = graph_small.drop_duplicates(
    subset=["txId"]
)

before = len(results)

evidence = results.merge(
    graph_small,
    on="txId",
    how="left"
)

print("Rows before merge:", before)
print("Rows after merge :", len(evidence))

graph_feature_cols = [
    c for c in graph_small.columns
    if c.startswith("graph_")
]

for c in graph_feature_cols:
    print(
        f"{c}: missing = "
        f"{evidence[c].isna().sum()}"
    )

print("✓ Graph evidence attached")


# =============================================================================
# 5. IDENTIFY MODEL SCORES
# =============================================================================

print("\n[5] IDENTIFYING MODEL SCORES")
print("-" * 90)

print(
    "Available score columns:",
    [
        c for c in evidence.columns
        if "score" in c.lower()
        or "anomaly" in c.lower()
    ]
)

if "IF_anomaly" not in evidence.columns:
    raise ValueError(
        "IF_anomaly column not found."
    )

if "LOF_anomaly" not in evidence.columns:
    raise ValueError(
        "LOF_anomaly column not found."
    )

print("✓ IF and LOF scores found")


# =============================================================================
# 6. ROBUST SCORE NORMALIZATION
# =============================================================================
# IMPORTANT:
# LOF and Isolation Forest are on very different raw scales.
# We therefore normalize them before combining.
#
# We use percentile/rank-based normalization because it is robust
# to extreme LOF values.
# =============================================================================

print("\n[6] NORMALIZING IF + LOF SCORES")
print("-" * 90)

def percentile_score(series):
    """
    Converts a score into approximately [0,1]
    using percentile rank.
    Higher value = more anomalous.
    """
    s = pd.to_numeric(
        series,
        errors="coerce"
    )

    return s.rank(
        pct=True,
        method="average"
    )


# Determine anomaly direction.
#
# In the current saved output:
# IF_anomaly has larger values for stronger anomalies.
# LOF_anomaly has larger values for stronger anomalies.
#
# Therefore higher = more anomalous.

evidence["IF_normalized"] = percentile_score(
    evidence["IF_anomaly"]
)

evidence["LOF_normalized"] = percentile_score(
    evidence["LOF_anomaly"]
)

# Robust ensemble
evidence["ensemble_score"] = (
    0.60 * evidence["IF_normalized"]
    +
    0.40 * evidence["LOF_normalized"]
)

print(
    "IF normalized range:",
    round(evidence["IF_normalized"].min(), 4),
    "to",
    round(evidence["IF_normalized"].max(), 4)
)

print(
    "LOF normalized range:",
    round(evidence["LOF_normalized"].min(), 4),
    "to",
    round(evidence["LOF_normalized"].max(), 4)
)

print(
    "Ensemble range:",
    round(evidence["ensemble_score"].min(), 4),
    "to",
    round(evidence["ensemble_score"].max(), 4)
)

print("✓ Scores normalized")


# =============================================================================
# 7. ANOMALY PERCENTILE
# =============================================================================

print("\n[7] CALCULATING ANOMALY PERCENTILE")
print("-" * 90)

evidence["anomaly_percentile"] = (
    evidence["ensemble_score"]
    .rank(pct=True)
    * 100
)

evidence["anomaly_percentile"] = (
    evidence["anomaly_percentile"]
    .round(2)
)

# Higher percentile = more anomalous

print(
    evidence["anomaly_percentile"].describe()
)

print("✓ Percentile calculated")


# =============================================================================
# 8. INVESTIGATION PRIORITY
# =============================================================================

print("\n[8] ASSIGNING INVESTIGATION PRIORITY")
print("-" * 90)

def priority(p):
    if p >= 99.5:
        return "CRITICAL"
    elif p >= 99:
        return "HIGH"
    elif p >= 95:
        return "MEDIUM"
    else:
        return "LOW"

evidence["investigation_priority"] = (
    evidence["anomaly_percentile"]
    .apply(priority)
)

print(
    evidence["investigation_priority"]
    .value_counts()
)


# =============================================================================
# 9. GRAPH BEHAVIOR EVIDENCE
# =============================================================================

print("\n[9] GENERATING GRAPH EVIDENCE")
print("-" * 90)

graph_evidence_cols = [
    "graph_in_degree",
    "graph_out_degree",
    "graph_total_degree",
    "graph_degree_imbalance",
    "graph_in_out_ratio",
]

available_graph_evidence = [
    c for c in graph_evidence_cols
    if c in evidence.columns
]

print(
    "Graph evidence columns:",
    available_graph_evidence
)

# Calculate percentile for each graph feature
# so values are comparable.

for col in available_graph_evidence:

    numeric = pd.to_numeric(
        evidence[col],
        errors="coerce"
    )

    evidence[col + "_percentile"] = (
        numeric.rank(
            pct=True,
            method="average"
        ) * 100
    )

    evidence[col + "_percentile"] = (
        evidence[col + "_percentile"]
        .round(2)
    )

print("✓ Graph percentiles generated")


# =============================================================================
# 10. BEHAVIORAL EVIDENCE
# =============================================================================
# We use the already selected behavioral features.
#
# Since raw behavioral features are standardized in the pipeline,
# absolute magnitude can be used as a deviation signal.
# =============================================================================

print("\n[10] GENERATING BEHAVIORAL EVIDENCE")
print("-" * 90)

behavioral_features = [
    "Local_feature_22",
    "Local_feature_25",
    "Local_feature_47",
    "Local_feature_52",
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_59",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_14",
    "Aggregate_feature_21",
    "Aggregate_feature_32",
]

available_behavioral = [
    c for c in behavioral_features
    if c in evidence.columns
]

print(
    "Behavioral features available directly:",
    available_behavioral
)

# If behavioral values aren't present in the saved result file,
# don't fabricate them.
#
# Instead use the model outputs already available.

if len(available_behavioral) == 0:

    print(
        "NOTE: Raw behavioral feature columns are not present "
        "in the saved anomaly-result file."
    )

    print(
        "Behavioral evidence will therefore use the "
        "existing model-level anomaly signal."
    )

else:

    for col in available_behavioral:

        numeric = pd.to_numeric(
            evidence[col],
            errors="coerce"
        )

        evidence[
            col + "_abs_deviation"
        ] = numeric.abs()

    print("✓ Behavioral deviations generated")


# =============================================================================
# 11. GRAPH ANOMALY SCORE
# =============================================================================

print("\n[11] GRAPH ANOMALY SCORE")
print("-" * 90)

graph_score_components = []

for col in [
    "graph_total_degree_percentile",
    "graph_degree_imbalance_percentile",
    "graph_in_out_ratio_percentile",
]:

    if col in evidence.columns:
        graph_score_components.append(
            evidence[col] / 100.0
        )

if graph_score_components:

    evidence["graph_anomaly_score"] = (
        pd.concat(
            graph_score_components,
            axis=1
        ).mean(axis=1)
    )

else:

    evidence["graph_anomaly_score"] = np.nan

print(
    "Graph anomaly score available:",
    evidence["graph_anomaly_score"]
    .notna()
    .sum()
)

print("✓ Graph score generated")


# =============================================================================
# 12. FINAL INVESTIGATION SCORE
# =============================================================================
#
# This is NOT a trained classifier.
# It is an investigator prioritization signal.
#
# 70% model anomaly
# 30% graph abnormality
#
# If graph score unavailable, use ensemble score.
# =============================================================================

print("\n[12] BUILDING INVESTIGATION SCORE")
print("-" * 90)

if evidence["graph_anomaly_score"].notna().any():

    evidence["investigation_score"] = (
        0.70 * evidence["ensemble_score"]
        +
        0.30 * evidence["graph_anomaly_score"].fillna(
            evidence["ensemble_score"]
        )
    )

else:

    evidence["investigation_score"] = (
        evidence["ensemble_score"]
    )

evidence["investigation_score"] = (
    evidence["investigation_score"]
    .clip(0, 1)
)

print(
    evidence["investigation_score"].describe()
)

print("✓ Investigation score generated")


# =============================================================================
# 13. EVIDENCE REASON GENERATOR
# =============================================================================

print("\n[13] GENERATING HUMAN-READABLE EVIDENCE")
print("-" * 90)

def generate_reason(row):

    reasons = []

    # Model anomaly
    p = row.get(
        "anomaly_percentile",
        np.nan
    )

    if pd.notna(p):

        if p >= 99.5:
            reasons.append(
                "Extremely high ensemble anomaly score"
            )

        elif p >= 99:
            reasons.append(
                "Very high ensemble anomaly score"
            )

        elif p >= 95:
            reasons.append(
                "Elevated ensemble anomaly score"
            )

    # Graph structure
    total_degree = row.get(
        "graph_total_degree",
        np.nan
    )

    if pd.notna(total_degree):

        if total_degree >= 50:
            reasons.append(
                "Very high transaction connectivity"
            )

        elif total_degree >= 20:
            reasons.append(
                "Elevated transaction connectivity"
            )

    imbalance = row.get(
        "graph_degree_imbalance",
        np.nan
    )

    if pd.notna(imbalance):

        if imbalance >= 20:
            reasons.append(
                "Strong inbound/outbound degree imbalance"
            )

    ratio = row.get(
        "graph_in_out_ratio",
        np.nan
    )

    if pd.notna(ratio):

        if ratio >= 10 or ratio <= 0.1:
            reasons.append(
                "Highly asymmetric inbound/outbound activity"
            )

    if not reasons:
        reasons.append(
            "Behavioral/graph anomaly signal requires further investigation"
        )

    return "; ".join(reasons)


evidence["evidence_summary"] = (
    evidence.apply(
        generate_reason,
        axis=1
    )
)

print("✓ Evidence descriptions generated")


# =============================================================================
# 14. TOP INVESTIGATION CASES
# =============================================================================

print("\n[14] TOP INVESTIGATION CASES")
print("=" * 90)

top_cases = (
    evidence
    .sort_values(
        "investigation_score",
        ascending=False
    )
    .head(50)
)

display_cols = [
    "txId",
    "Time step",
    "split",
    "ensemble_score",
    "graph_anomaly_score",
    "investigation_score",
    "anomaly_percentile",
    "investigation_priority",
]

display_cols = [
    c for c in display_cols
    if c in top_cases.columns
]

print(
    top_cases[display_cols].to_string(
        index=False
    )
)


# =============================================================================
# 15. TOP CASE DETAILS
# =============================================================================

print("\n[15] TOP 10 CASE EVIDENCE")
print("=" * 90)

for _, row in top_cases.head(10).iterrows():

    print("\n" + "-" * 80)

    print(
        "Transaction ID:",
        row["txId"]
    )

    print(
        "Time step:",
        row["Time step"]
    )

    print(
        "Split:",
        row["split"]
    )

    print(
        "Investigation priority:",
        row["investigation_priority"]
    )

    print(
        "Investigation score:",
        round(
            row["investigation_score"],
            4
        )
    )

    print(
        "Anomaly percentile:",
        row["anomaly_percentile"],
        "%"
    )

    print(
        "Evidence:",
        row["evidence_summary"]
    )

    if "graph_total_degree" in row:
        print(
            "Total graph degree:",
            row["graph_total_degree"]
        )

    if "graph_in_degree" in row:
        print(
            "In degree:",
            row["graph_in_degree"]
        )

    if "graph_out_degree" in row:
        print(
            "Out degree:",
            row["graph_out_degree"]
        )


# =============================================================================
# 16. SAVE INVESTIGATOR CSV
# =============================================================================

print("\n[16] SAVING INVESTIGATOR DATA")
print("-" * 90)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "data",
    "processed"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

CSV_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "bittrace_investigator_evidence.csv"
)

evidence.to_csv(
    CSV_OUTPUT,
    index=False
)

print(
    "✓ Saved:",
    CSV_OUTPUT
)


# =============================================================================
# 17. SAVE TOP CASES
# =============================================================================

TOP_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "bittrace_top_investigation_cases.csv"
)

top_cases.to_csv(
    TOP_OUTPUT,
    index=False
)

print(
    "✓ Saved:",
    TOP_OUTPUT
)


# =============================================================================
# 18. JSON EVIDENCE FOR DASHBOARD/API
# =============================================================================

print("\n[18] BUILDING DASHBOARD JSON")
print("-" * 90)

json_cases = []

for _, row in top_cases.head(100).iterrows():

    case = {
        "txId": int(row["txId"])
        if pd.notna(row["txId"])
        else None,

        "time_step": int(row["Time step"])
        if pd.notna(row["Time step"])
        else None,

        "split": str(row["split"]),

        "ensemble_score": round(
            float(row["ensemble_score"]),
            6
        ),

        "investigation_score": round(
            float(row["investigation_score"]),
            6
        ),

        "anomaly_percentile": round(
            float(row["anomaly_percentile"]),
            2
        ),

        "priority": str(
            row["investigation_priority"]
        ),

        "evidence": str(
            row["evidence_summary"]
        ),
    }

    # Graph evidence
    for col in [
        "graph_in_degree",
        "graph_out_degree",
        "graph_total_degree",
        "graph_degree_imbalance",
        "graph_in_out_ratio",
    ]:

        if col in row and pd.notna(row[col]):

            case[col] = float(
                row[col]
            )

    json_cases.append(case)


JSON_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "bittrace_investigation_cases.json"
)

with open(
    JSON_OUTPUT,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        json_cases,
        f,
        indent=2
    )

print(
    "✓ Saved:",
    JSON_OUTPUT
)


# =============================================================================
# 19. SUMMARY
# =============================================================================

print("\n")
print("=" * 90)
print("BIT-TRACE — EXPLAINABILITY + EVIDENCE COMPLETE")
print("=" * 90)

print(
    "Transactions analysed:",
    len(evidence)
)

print(
    "Graph features:",
    len(graph_feature_cols)
)

print(
    "Top investigation cases:",
    len(top_cases)
)

print(
    "\nPriority distribution:"
)

print(
    evidence[
        "investigation_priority"
    ].value_counts()
)

print("\nGenerated files:")
print(
    "✓ bittrace_investigator_evidence.csv"
)
print(
    "✓ bittrace_top_investigation_cases.csv"
)
print(
    "✓ bittrace_investigation_cases.json"
)

print("\nNEXT PHASE:")
print(
    "Use these evidence records to build the "
    "BIT-TRACE Investigator Dashboard."
)

print(
    "\nIMPORTANT:"
)
print(
    "The anomaly score is an investigation-prioritization "
    "signal, not a proof that a transaction is illicit."
)

print("=" * 90)

==========================================================================================
BIT-TRACE — EXPLAINABILITY + EVIDENCE GENERATION
==========================================================================================

[1] FILE CHECK
------------------------------------------------------------------------------------------
RESULT FILE: C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_behavioral_anomaly_results.csv
GRAPH FILE : C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_features.csv
✓ Required files found

[2] LOADING ANOMALY RESULTS
------------------------------------------------------------------------------------------
Shape: (203769, 6)
Columns:
['txId', 'Time step', 'IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly', 'split']
✓ Results loaded

[3] LOADING GRAPH FEATURES
------------------------------------------------------------------------------------------
Shape: (203769, 12)
Columns:
['txId', 'Time step', 'graph_in_degree', 'graph_out_degree', 'graph_total_degree', 'graph_degree_imbalance', 'graph_in_out_ratio', 'graph_log_total_degree', 'graph_log_in_degree', 'graph_log_out_degree', 'graph_reciprocal_degree', 'graph_log_reciprocal_degree']
✓ Graph features loaded

[4] MERGING GRAPH EVIDENCE
------------------------------------------------------------------------------------------
Rows before merge: 203769
Rows after merge : 203769
graph_in_degree: missing = 0
graph_out_degree: missing = 0
graph_total_degree: missing = 0
graph_degree_imbalance: missing = 0
graph_in_out_ratio: missing = 0
graph_log_total_degree: missing = 0
graph_log_in_degree: missing = 0
graph_log_out_degree: missing = 0
graph_reciprocal_degree: missing = 0
graph_log_reciprocal_degree: missing = 0
✓ Graph evidence attached

[5] IDENTIFYING MODEL SCORES
------------------------------------------------------------------------------------------
Available score columns: ['IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly']
✓ IF and LOF scores found

[6] NORMALIZING IF + LOF SCORES
------------------------------------------------------------------------------------------
IF normalized range: 0.0 to 1.0
LOF normalized range: 0.0 to 1.0
Ensemble range: 0.004 to 0.9987
✓ Scores normalized

[7] CALCULATING ANOMALY PERCENTILE
------------------------------------------------------------------------------------------
count    203769.000000
mean         50.000248
std          28.867591
min           0.000000
25%          25.000000
50%          50.000000
75%          75.000000
max         100.000000
Name: anomaly_percentile, dtype: float64
✓ Percentile calculated

[8] ASSIGNING INVESTIGATION PRIORITY
------------------------------------------------------------------------------------------
investigation_priority
LOW         193570
MEDIUM        8151
CRITICAL      1030
HIGH          1018
Name: count, dtype: int64

[9] GENERATING GRAPH EVIDENCE
------------------------------------------------------------------------------------------
Graph evidence columns: ['graph_in_degree', 'graph_out_degree', 'graph_total_degree', 'graph_degree_imbalance', 'graph_in_out_ratio']
✓ Graph percentiles generated

[10] GENERATING BEHAVIORAL EVIDENCE
------------------------------------------------------------------------------------------
Behavioral features available directly: []
NOTE: Raw behavioral feature columns are not present in the saved anomaly-result file.
Behavioral evidence will therefore use the existing model-level anomaly signal.

[11] GRAPH ANOMALY SCORE
------------------------------------------------------------------------------------------
Graph anomaly score available: 203769
✓ Graph score generated

[12] BUILDING INVESTIGATION SCORE
------------------------------------------------------------------------------------------
count    203769.000000
mean          0.500006
std           0.173526
min           0.135950
25%           0.367023
50%           0.494728
75%           0.628730
max           0.997402
Name: investigation_score, dtype: float64
✓ Investigation score generated

[13] GENERATING HUMAN-READABLE EVIDENCE
------------------------------------------------------------------------------------------
✓ Evidence descriptions generated

[14] TOP INVESTIGATION CASES
==========================================================================================
     txId  Time step      split  ensemble_score  graph_anomaly_score  investigation_score  anomaly_percentile investigation_priority
 43388675         10      train        0.996289             1.000000             0.997402              100.00               CRITICAL
 68705820         10      train        0.995251             1.000000             0.996676               99.99               CRITICAL
 30699343         37 validation        0.994953             1.000000             0.996467               99.99               CRITICAL
328923500         31      train        0.998056             0.992000             0.996239              100.00               CRITICAL
225859042          5      train        0.994121             1.000000             0.995885               99.99               CRITICAL
279187194          4      train        0.994086             1.000000             0.995861               99.99               CRITICAL
149699871         39 validation        0.998689             0.988733             0.995702              100.00               CRITICAL
 96576418          7      train        0.993778             1.000000             0.995645               99.99               CRITICAL
196107869         46       test        0.992975             1.000000             0.995083               99.98               CRITICAL
 43397277         10      train        0.992773             1.000000             0.994941               99.98               CRITICAL
168218829         29      train        0.996141             0.992000             0.994899              100.00               CRITICAL
 68706499         10      train        0.992238             0.999933             0.994547               99.98               CRITICAL
234890810         11      train        0.991615             1.000000             0.994131               99.97               CRITICAL
106872764         44       test        0.997687             0.984800             0.993821              100.00               CRITICAL
106441957         44       test        0.997032             0.985933             0.993702              100.00               CRITICAL
 30179316         37 validation        0.990696             0.999933             0.993467               99.96               CRITICAL
225711361          5      train        0.990333             0.999900             0.993203               99.95               CRITICAL
269905668         25      train        0.990333             0.999900             0.993203               99.95               CRITICAL
339576494         13      train        0.995243             0.987833             0.993020               99.99               CRITICAL
 96365231         33      train        0.990023             0.999900             0.992986               99.95               CRITICAL
157929208         49       test        0.989559             0.999900             0.992661               99.93               CRITICAL
149158766         39 validation        0.989403             0.999900             0.992552               99.92               CRITICAL
 90716926          4      train        0.989396             0.999900             0.992547               99.92               CRITICAL
355110272         32      train        0.988659             0.999900             0.992031               99.90               CRITICAL
 99675435         21      train        0.988281             0.999900             0.991767               99.90               CRITICAL
  2881273          1      train        0.988056             0.999900             0.991609               99.89               CRITICAL
232438397          1      train        0.988050             0.999800             0.991575               99.89               CRITICAL
 57228978         40 validation        0.994273             0.984800             0.991431               99.99               CRITICAL
 30276715         37 validation        0.986327             0.999900             0.990399               99.87               CRITICAL
225702141          5      train        0.991584             0.986967             0.990199               99.97               CRITICAL
372745794         22      train        0.985966             0.999900             0.990147               99.86               CRITICAL
 94621528          7      train        0.985924             0.999900             0.990117               99.86               CRITICAL
121654821          6      train        0.985805             0.999700             0.989973               99.86               CRITICAL
230658142          1      train        0.985565             0.999900             0.989866               99.85               CRITICAL
347550863         12      train        0.984982             0.999833             0.989437               99.85               CRITICAL
116898498         38 validation        0.984693             0.999833             0.989235               99.85               CRITICAL
 22837784          4      train        0.984533             0.999833             0.989123               99.84               CRITICAL
 12806113         41 validation        0.984380             0.999833             0.989016               99.84               CRITICAL
  2268197         48       test        0.984265             0.999833             0.988935               99.84               CRITICAL
298985039         30      train        0.988756             0.989167             0.988879               99.90               CRITICAL
355174807         32      train        0.984143             0.999800             0.988840               99.84               CRITICAL
339175100         13      train        0.983968             0.999867             0.988738               99.83               CRITICAL
209837677         20      train        0.983930             0.999833             0.988701               99.83               CRITICAL
149569098         39 validation        0.983921             0.999800             0.988685               99.83               CRITICAL
 38688623         47       test        0.983731             0.996333             0.987511               99.82               CRITICAL
 70245040         36 validation        0.982199             0.999767             0.987470               99.77               CRITICAL
149691712         39 validation        0.982192             0.999767             0.987464               99.77               CRITICAL
106320422         44       test        0.981685             0.999667             0.987080               99.75               CRITICAL
332771446         23      train        0.980795             0.999800             0.986496               99.74               CRITICAL
 19170155         47       test        0.981973             0.996967             0.986471               99.75               CRITICAL

[15] TOP 10 CASE EVIDENCE
==========================================================================================

--------------------------------------------------------------------------------
Transaction ID: 43388675
Time step: 10
Split: train
Investigation priority: CRITICAL
Investigation score: 0.9974
Anomaly percentile: 100.0 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 284.0
In degree: 284.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 68705820
Time step: 10
Split: train
Investigation priority: CRITICAL
Investigation score: 0.9967
Anomaly percentile: 99.99 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 247.0
In degree: 247.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 30699343
Time step: 37
Split: validation
Investigation priority: CRITICAL
Investigation score: 0.9965
Anomaly percentile: 99.99 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 241.0
In degree: 241.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 328923500
Time step: 31
Split: train
Investigation priority: CRITICAL
Investigation score: 0.9962
Anomaly percentile: 100.0 %
Evidence: Extremely high ensemble anomaly score
Total graph degree: 15.0
In degree: 14.0
Out degree: 1.0

--------------------------------------------------------------------------------
Transaction ID: 225859042
Time step: 5
Split: train
Investigation priority: CRITICAL
Investigation score: 0.9959
Anomaly percentile: 99.99 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 212.0
In degree: 212.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 279187194
Time step: 4
Split: train
Investigation priority: CRITICAL
Investigation score: 0.9959
Anomaly percentile: 99.99 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 211.0
In degree: 211.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 149699871
Time step: 39
Split: validation
Investigation priority: CRITICAL
Investigation score: 0.9957
Anomaly percentile: 100.0 %
Evidence: Extremely high ensemble anomaly score; Highly asymmetric inbound/outbound activity
Total graph degree: 9.0
In degree: 9.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 96576418
Time step: 7
Split: train
Investigation priority: CRITICAL
Investigation score: 0.9956
Anomaly percentile: 99.99 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 239.0
In degree: 239.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 196107869
Time step: 46
Split: test
Investigation priority: CRITICAL
Investigation score: 0.9951
Anomaly percentile: 99.98 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 188.0
In degree: 188.0
Out degree: 0.0

--------------------------------------------------------------------------------
Transaction ID: 43397277
Time step: 10
Split: train
Investigation priority: CRITICAL
Investigation score: 0.9949
Anomaly percentile: 99.98 %
Evidence: Extremely high ensemble anomaly score; Very high transaction connectivity; Strong inbound/outbound degree imbalance; Highly asymmetric inbound/outbound activity
Total graph degree: 182.0
In degree: 182.0
Out degree: 0.0

[16] SAVING INVESTIGATOR DATA
------------------------------------------------------------------------------------------
✓ Saved: C:\Users\YASHIKA\Desktop\bit-trace\data\processed\bittrace_investigator_evidence.csv
✓ Saved: C:\Users\YASHIKA\Desktop\bit-trace\data\processed\bittrace_top_investigation_cases.csv

[18] BUILDING DASHBOARD JSON
------------------------------------------------------------------------------------------
✓ Saved: C:\Users\YASHIKA\Desktop\bit-trace\data\processed\bittrace_investigation_cases.json


==========================================================================================
BIT-TRACE — EXPLAINABILITY + EVIDENCE COMPLETE
==========================================================================================
Transactions analysed: 203769
Graph features: 10
Top investigation cases: 50

Priority distribution:
investigation_priority
LOW         193570
MEDIUM        8151
CRITICAL      1030
HIGH          1018
Name: count, dtype: int64

Generated files:
✓ bittrace_investigator_evidence.csv
✓ bittrace_top_investigation_cases.csv
✓ bittrace_investigation_cases.json

NEXT PHASE:
Use these evidence records to build the BIT-TRACE Investigator Dashboard.

IMPORTANT:
The anomaly score is an investigation-prioritization signal, not a proof that a transaction is illicit.
==========================================================================================

In [44]:
# =============================================================================
# BIT-TRACE — TRANSACTION-ONLY FINAL UNSUPERVISED ANOMALY PIPELINE
# Elliptic++ Transactions Dataset
#
# IMPORTANT:
# - Uses ONLY txs_features.csv + txs_classes.csv
# - Does NOT use P2P/network observations
# - Does NOT use txs_edgelist.csv
# - Labels are used ONLY for post-hoc evaluation
# =============================================================================

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import roc_auc_score, average_precision_score


# =============================================================================
# 0. CONFIGURATION
# =============================================================================

FEATURE_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv"
CLASS_PATH   = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv"

SELECTED_FEATURES = [
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_52",
    "Local_feature_59",
    "Aggregate_feature_21",
    "Local_feature_25",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_32",
    "Aggregate_feature_14",
    "Local_feature_22",
    "Local_feature_47"
]

TRAIN_END = 34
VAL_START = 35
VAL_END = 41
TEST_START = 42

N_ESTIMATORS = 300
CONTAMINATION = "auto"
RANDOM_STATE = 42

# Ensemble weights
IF_WEIGHT = 0.60
LOF_WEIGHT = 0.40

OUTPUT_DIR = os.path.join(
    os.path.dirname(os.path.dirname(FEATURE_PATH)),
    "BITTRACE_TRANSACTION_RESULTS"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def section(title, width=90):
    print("\n" + "=" * width)
    print(title)
    print("=" * width)


def minmax_normalize(x):
    """
    Converts any score array to [0,1].
    Higher = more anomalous.
    """
    x = np.asarray(x, dtype=float)

    lo = np.nanmin(x)
    hi = np.nanmax(x)

    if hi - lo < 1e-12:
        return np.zeros_like(x)

    return (x - lo) / (hi - lo)


def percentile_score(x):
    """
    Percentile/rank based score.
    Higher = more anomalous.
    """
    s = pd.Series(np.asarray(x))
    return s.rank(method="average", pct=True).to_numpy()


# =============================================================================
# 1. FILE CHECK
# =============================================================================

section("BIT-TRACE — TRANSACTION-ONLY UNSUPERVISED PIPELINE")

print("\n[1] FILE CHECK")
print("-" * 90)

if not os.path.exists(FEATURE_PATH):
    raise FileNotFoundError(f"Feature file not found:\n{FEATURE_PATH}")

if not os.path.exists(CLASS_PATH):
    raise FileNotFoundError(f"Class file not found:\n{CLASS_PATH}")

print("FEATURE:", FEATURE_PATH)
print("CLASS  :", CLASS_PATH)
print("✓ Required transaction files found")
print("✗ P2P / edgelist is NOT used")


# =============================================================================
# 2. LOAD CLASS DATA
# =============================================================================

print("\n[2] LOADING CLASS DATA")
print("-" * 90)

classes = pd.read_csv(CLASS_PATH)

classes.columns = [
    str(c).strip().replace(" ", "_")
    for c in classes.columns
]

# Handle possible naming variations
if "txId" not in classes.columns:
    candidates = [c for c in classes.columns if c.lower() == "txid"]
    if candidates:
        classes.rename(columns={candidates[0]: "txId"}, inplace=True)

if "class" not in classes.columns:
    candidates = [c for c in classes.columns if c.lower() == "class"]
    if candidates:
        classes.rename(columns={candidates[0]: "class"}, inplace=True)

classes["txId"] = pd.to_numeric(classes["txId"], errors="coerce")
classes["class"] = pd.to_numeric(classes["class"], errors="coerce")

classes = classes.dropna(subset=["txId", "class"]).copy()

classes["txId"] = classes["txId"].astype(np.int64)
classes["class"] = classes["class"].astype(int)

print("Shape:", classes.shape)
print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())


# =============================================================================
# 3. READ FEATURE HEADER
# =============================================================================

print("\n[3] READING FEATURE HEADER")
print("-" * 90)

header = pd.read_csv(FEATURE_PATH, nrows=0)

feature_columns = list(header.columns)

print("Total columns:", len(feature_columns))

# Detect ID
id_candidates = ["txId", "txid", "TxId", "transaction_id"]

id_col = None
for c in id_candidates:
    if c in feature_columns:
        id_col = c
        break

if id_col is None:
    raise ValueError("Could not detect txId column.")

# Detect time
time_candidates = [
    "Time step",
    "Time_step",
    "time_step",
    "TimeStep",
    "time"
]

time_col = None
for c in time_candidates:
    if c in feature_columns:
        time_col = c
        break

if time_col is None:
    raise ValueError("Could not detect Time step column.")

print("ID column  :", id_col)
print("Time column:", time_col)


# =============================================================================
# 4. VERIFY FEATURES
# =============================================================================

print("\n[4] VERIFYING SELECTED FEATURES")
print("-" * 90)

missing_features = [
    f for f in SELECTED_FEATURES
    if f not in feature_columns
]

if missing_features:
    raise ValueError(
        "Missing selected features:\n" +
        "\n".join(missing_features)
    )

print("Selected features:", len(SELECTED_FEATURES))

for i, f in enumerate(SELECTED_FEATURES, 1):
    print(f"{i:2d}. {f}")

print("✓ All selected features found")


# =============================================================================
# 5. LOAD ONLY REQUIRED TRANSACTION COLUMNS
# =============================================================================

print("\n[5] LOADING TRANSACTION FEATURES")
print("-" * 90)

usecols = [id_col, time_col] + SELECTED_FEATURES

data = pd.read_csv(
    FEATURE_PATH,
    usecols=usecols
)

print("Loaded shape:", data.shape)


# =============================================================================
# 6. NORMALIZE COLUMN NAMES
# =============================================================================

if id_col != "txId":
    data.rename(columns={id_col: "txId"}, inplace=True)

if time_col != "Time step":
    data.rename(columns={time_col: "Time step"}, inplace=True)

data["txId"] = pd.to_numeric(data["txId"], errors="coerce")
data["Time step"] = pd.to_numeric(data["Time step"], errors="coerce")

for f in SELECTED_FEATURES:
    data[f] = pd.to_numeric(data[f], errors="coerce")


# =============================================================================
# 7. DATA QUALITY
# =============================================================================

print("\n[6] DATA QUALITY")
print("-" * 90)

print("Rows:", len(data))
print("Missing txId:", data["txId"].isna().sum())
print("Missing Time step:", data["Time step"].isna().sum())
print("Duplicate txId:", data["txId"].duplicated().sum())

feature_nan = data[SELECTED_FEATURES].isna().sum().sum()
feature_inf = np.isinf(
    data[SELECTED_FEATURES].to_numpy(dtype=float)
).sum()

print("Feature NaN:", feature_nan)
print("Feature Inf:", feature_inf)


# =============================================================================
# 8. MERGE LABELS
# =============================================================================

print("\n[7] MERGING LABELS")
print("-" * 90)

data = data.merge(
    classes[["txId", "class"]],
    on="txId",
    how="inner",
    validate="one_to_one"
)

print("Merged shape:", data.shape)
print("Missing class:", data["class"].isna().sum())

print("\nClass distribution:")
print(data["class"].value_counts().sort_index())


# =============================================================================
# 9. CLEAN FEATURES
# =============================================================================

print("\n[8] CLEANING FEATURES")
print("-" * 90)

data[SELECTED_FEATURES] = (
    data[SELECTED_FEATURES]
    .replace([np.inf, -np.inf], np.nan)
)

# Median imputation
for f in SELECTED_FEATURES:
    med = data[f].median()

    if pd.isna(med):
        med = 0.0

    data[f] = data[f].fillna(med)

print(
    "Remaining NaN:",
    data[SELECTED_FEATURES].isna().sum().sum()
)

print(
    "Remaining Inf:",
    np.isinf(
        data[SELECTED_FEATURES].to_numpy(dtype=float)
    ).sum()
)


# =============================================================================
# 10. SORT TEMPORALLY
# =============================================================================

data = data.sort_values(
    ["Time step", "txId"]
).reset_index(drop=True)

X_all = data[SELECTED_FEATURES].to_numpy(dtype=np.float32)
y_all = data["class"].to_numpy(dtype=np.int8)
time_steps = data["Time step"].to_numpy(dtype=np.int16)
tx_ids = data["txId"].to_numpy(dtype=np.int64)

print("\n[9] FINAL DATA")
print("-" * 90)

print("X:", X_all.shape)
print("y:", y_all.shape)
print("Time:", time_steps.shape)

print(
    "Time range:",
    time_steps.min(),
    "to",
    time_steps.max()
)


# =============================================================================
# 11. TEMPORAL SPLIT
# =============================================================================

train_idx = np.where(time_steps <= TRAIN_END)[0]

val_idx = np.where(
    (time_steps >= VAL_START) &
    (time_steps <= VAL_END)
)[0]

test_idx = np.where(
    time_steps >= TEST_START
)[0]

print("\n[10] TEMPORAL SPLIT")
print("-" * 90)

print(
    f"Train      : {len(train_idx):,} "
    f"(time 1–{TRAIN_END})"
)

print(
    f"Validation : {len(val_idx):,} "
    f"(time {VAL_START}–{VAL_END})"
)

print(
    f"Test       : {len(test_idx):,} "
    f"(time {TEST_START}–{time_steps.max()})"
)


# =============================================================================
# 12. ROBUST SCALING
# =============================================================================

print("\n[11] ROBUST SCALING")
print("-" * 90)

# Fit scaler ONLY on training data
scaler = RobustScaler()

X_train = scaler.fit_transform(
    X_all[train_idx]
).astype(np.float32)

X_val = scaler.transform(
    X_all[val_idx]
).astype(np.float32)

X_test = scaler.transform(
    X_all[test_idx]
).astype(np.float32)

print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

print("✓ Scaler fitted only on training data")


# =============================================================================
# 13. ISOLATION FOREST
# =============================================================================

print("\n[12] TRAINING ISOLATION FOREST")
print("-" * 90)

iforest = IsolationForest(
    n_estimators=N_ESTIMATORS,
    contamination=CONTAMINATION,
    random_state=RANDOM_STATE,
    n_jobs=-1,
    max_samples="auto"
)

# NO LABELS USED
iforest.fit(X_train)

print("✓ Isolation Forest trained")
print("Trees:", N_ESTIMATORS)


# =============================================================================
# 14. ISOLATION FOREST SCORES
# =============================================================================

print("\n[13] GENERATING IF SCORES")
print("-" * 90)

# sklearn decision_function:
# higher = more normal
# therefore multiply by -1
if_train_raw = -iforest.decision_function(X_train)
if_val_raw = -iforest.decision_function(X_val)
if_test_raw = -iforest.decision_function(X_test)

print("Train:", len(if_train_raw))
print("Validation:", len(if_val_raw))
print("Test:", len(if_test_raw))


# =============================================================================
# 15. LOF
# =============================================================================

print("\n[14] TRAINING LOF")
print("-" * 90)

# IMPORTANT:
# LOF with novelty=True can score unseen validation/test data.
#
# n_neighbors=35 gives local behavioral context without being excessively
# expensive on this dataset.

lof = LocalOutlierFactor(
    n_neighbors=35,
    contamination="auto",
    novelty=True,
    n_jobs=-1
)

lof.fit(X_train)

print("✓ LOF trained")


# =============================================================================
# 16. LOF SCORES
# =============================================================================

print("\n[15] GENERATING LOF SCORES")
print("-" * 90)

# sklearn LOF decision_function:
# higher = more normal
# multiply by -1
lof_train_raw = -lof.decision_function(X_train)
lof_val_raw = -lof.decision_function(X_val)
lof_test_raw = -lof.decision_function(X_test)

print("Train:", len(lof_train_raw))
print("Validation:", len(lof_val_raw))
print("Test:", len(lof_test_raw))


# =============================================================================
# 17. SCORE NORMALIZATION
# =============================================================================

print("\n[16] NORMALIZING SCORES")
print("-" * 90)

# Normalize each model separately.
#
# IMPORTANT:
# We use TRAIN distribution to establish the scale.
# Then apply same scale to validation/test.

def train_based_minmax(train_scores, scores):
    lo = np.percentile(train_scores, 1)
    hi = np.percentile(train_scores, 99)

    if hi - lo < 1e-12:
        return np.zeros_like(scores)

    result = (scores - lo) / (hi - lo)

    return np.clip(result, 0, 1)


if_train = train_based_minmax(
    if_train_raw,
    if_train_raw
)

if_val = train_based_minmax(
    if_train_raw,
    if_val_raw
)

if_test = train_based_minmax(
    if_train_raw,
    if_test_raw
)

lof_train = train_based_minmax(
    lof_train_raw,
    lof_train_raw
)

lof_val = train_based_minmax(
    lof_train_raw,
    lof_val_raw
)

lof_test = train_based_minmax(
    lof_train_raw,
    lof_test_raw
)

print("✓ Scores normalized to approximately [0,1]")


# =============================================================================
# 18. ENSEMBLE
# =============================================================================

print("\n[17] BUILDING ENSEMBLE")
print("-" * 90)

print(
    f"Isolation Forest weight: {IF_WEIGHT}"
)

print(
    f"LOF weight            : {LOF_WEIGHT}"
)

ensemble_train = (
    IF_WEIGHT * if_train +
    LOF_WEIGHT * lof_train
)

ensemble_val = (
    IF_WEIGHT * if_val +
    LOF_WEIGHT * lof_val
)

ensemble_test = (
    IF_WEIGHT * if_test +
    LOF_WEIGHT * lof_test
)

print("✓ Ensemble generated")


# =============================================================================
# 19. CREATE FULL RESULT DATAFRAME
# =============================================================================

print("\n[18] BUILDING RESULT TABLE")
print("-" * 90)

results = data[
    ["txId", "Time step", "class"]
].copy()

results["split"] = "train"

results.loc[val_idx, "split"] = "validation"
results.loc[test_idx, "split"] = "test"

results["IF_anomaly"] = np.nan
results["LOF_anomaly"] = np.nan
results["ensemble_anomaly"] = np.nan

results.loc[train_idx, "IF_anomaly"] = if_train
results.loc[val_idx, "IF_anomaly"] = if_val
results.loc[test_idx, "IF_anomaly"] = if_test

results.loc[train_idx, "LOF_anomaly"] = lof_train
results.loc[val_idx, "LOF_anomaly"] = lof_val
results.loc[test_idx, "LOF_anomaly"] = lof_test

results.loc[train_idx, "ensemble_anomaly"] = ensemble_train
results.loc[val_idx, "ensemble_anomaly"] = ensemble_val
results.loc[test_idx, "ensemble_anomaly"] = ensemble_test


# =============================================================================
# 20. SCORE DISTRIBUTION
# =============================================================================

print("\n[19] SCORE DISTRIBUTION")
print("-" * 90)

score_summary = pd.DataFrame({
    "Split": ["Train", "Validation", "Test"],
    "Samples": [
        len(ensemble_train),
        len(ensemble_val),
        len(ensemble_test)
    ],
    "Mean": [
        ensemble_train.mean(),
        ensemble_val.mean(),
        ensemble_test.mean()
    ],
    "Std": [
        ensemble_train.std(),
        ensemble_val.std(),
        ensemble_test.std()
    ],
    "Min": [
        ensemble_train.min(),
        ensemble_val.min(),
        ensemble_test.min()
    ],
    "Median": [
        np.median(ensemble_train),
        np.median(ensemble_val),
        np.median(ensemble_test)
    ],
    "Max": [
        ensemble_train.max(),
        ensemble_val.max(),
        ensemble_test.max()
    ]
})

print(
    score_summary.to_string(index=False)
)


# =============================================================================
# 21. POST-HOC CLASS-3 EVALUATION
# =============================================================================

print("\n[20] POST-HOC CLASS-3 EVALUATION")
print("-" * 90)

test_labels = y_all[test_idx]

# Higher anomaly score = more anomalous.
# Class 3 is evaluated as a reference class only.

class3_binary = (
    test_labels == 3
).astype(int)

try:
    test_roc_auc = roc_auc_score(
        class3_binary,
        ensemble_test
    )

    test_pr_auc = average_precision_score(
        class3_binary,
        ensemble_test
    )

    print(
        f"Test ROC-AUC : {test_roc_auc:.4f}"
    )

    print(
        f"Test PR-AUC  : {test_pr_auc:.4f}"
    )

except Exception as e:
    print("Evaluation error:", e)


# =============================================================================
# 22. CLASS-WISE SCORE ANALYSIS
# =============================================================================

print("\n[21] CLASS-WISE TEST SCORE ANALYSIS")
print("-" * 90)

test_eval = results.iloc[test_idx].copy()

class_summary = (
    test_eval
    .groupby("class")["ensemble_anomaly"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(class_summary)


# =============================================================================
# 23. TOP ANOMALIES — TEST SET ONLY
# =============================================================================

print("\n[22] TOP 50 MOST ANOMALOUS TEST TRANSACTIONS")
print("-" * 90)

top_test = (
    test_eval
    .sort_values(
        "ensemble_anomaly",
        ascending=False
    )
    .head(50)
)

print(
    top_test[
        [
            "txId",
            "Time step",
            "class",
            "IF_anomaly",
            "LOF_anomaly",
            "ensemble_anomaly"
        ]
    ].to_string(index=False)
)


# =============================================================================
# 24. TOP-K CLASS-3 ENRICHMENT
# =============================================================================

print("\n[23] TOP-K CLASS-3 ENRICHMENT")
print("-" * 90)

overall_class3_pct = (
    (test_labels == 3).mean() * 100
)

print(
    f"Test-set Class-3 baseline: "
    f"{overall_class3_pct:.2f}%"
)

for k in [50, 100, 500, 1000, 5000]:

    k = min(k, len(test_eval))

    top_k = (
        test_eval
        .sort_values(
            "ensemble_anomaly",
            ascending=False
        )
        .head(k)
    )

    class3_count = (
        top_k["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / k * 100
    )

    enrichment = (
        class3_pct /
        overall_class3_pct
        if overall_class3_pct > 0
        else np.nan
    )

    print(
        f"Top {k:5d}: "
        f"Class-3 = {class3_count:5d} "
        f"({class3_pct:6.2f}%) | "
        f"Enrichment = {enrichment:.3f}x"
    )


# =============================================================================
# 25. TEMPORAL ANALYSIS
# =============================================================================

print("\n[24] TEMPORAL ANOMALY ANALYSIS — TEST")
print("-" * 90)

temporal = (
    test_eval
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly=("ensemble_anomaly", "mean"),
        Median_Anomaly=("ensemble_anomaly", "median"),
        Max_Anomaly=("ensemble_anomaly", "max"),
        Class3_Count=("class", lambda x: (x == 3).sum())
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"] /
    temporal["Transactions"] * 100
)

temporal = temporal.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print(
    temporal.head(15).to_string()
)


# =============================================================================
# 26. FEATURE STATISTICS
# =============================================================================

print("\n[25] FEATURE STATISTICS")
print("-" * 90)

feature_stats = pd.DataFrame({
    "Feature": SELECTED_FEATURES,
    "Train_Mean": X_all[train_idx].mean(axis=0),
    "Train_Std": X_all[train_idx].std(axis=0),
    "Train_Min": X_all[train_idx].min(axis=0),
    "Train_Median": np.median(
        X_all[train_idx],
        axis=0
    ),
    "Train_Max": X_all[train_idx].max(axis=0)
})

print(
    feature_stats.to_string(index=False)
)


# =============================================================================
# 27. TRANSACTION-LEVEL EVIDENCE
# =============================================================================

print("\n[26] GENERATING TRANSACTION-LEVEL EVIDENCE")
print("-" * 90)

# -------------------------------------------------------------------------
# Evidence idea:
#
# An anomalous transaction can be explained by identifying which selected
# behavioral features are most unusual relative to TRAIN behavior.
#
# We calculate robust deviation:
#
#   |x - train_median| / train_MAD
#
# Larger value = feature is farther from normal training behavior.
#
# This is NOT a supervised explanation.
# It does NOT use class labels.
# -------------------------------------------------------------------------

train_raw = X_all[train_idx].astype(np.float64)

train_median = np.median(
    train_raw,
    axis=0
)

q25 = np.percentile(
    train_raw,
    25,
    axis=0
)

q75 = np.percentile(
    train_raw,
    75,
    axis=0
)

iqr = q75 - q25

iqr[iqr < 1e-9] = 1.0


def feature_evidence_for_row(row):

    deviation = (
        np.abs(row - train_median) /
        iqr
    )

    order = np.argsort(
        deviation
    )[::-1]

    return [
        (
            SELECTED_FEATURES[i],
            float(deviation[i])
        )
        for i in order[:5]
    ]


# Only generate detailed evidence for TOP 500 test anomalies
# to keep runtime/output manageable.

top500 = (
    test_eval
    .sort_values(
        "ensemble_anomaly",
        ascending=False
    )
    .head(500)
)

evidence_records = []

for idx in top500.index:

    row_position = idx

    feature_values = X_all[
        row_position
    ].astype(np.float64)

    deviations = (
        np.abs(
            feature_values -
            train_median
        ) / iqr
    )

    order = np.argsort(
        deviations
    )[::-1]

    top_features = [
        SELECTED_FEATURES[i]
        for i in order[:5]
    ]

    top_deviations = [
        float(deviations[i])
        for i in order[:5]
    ]

    evidence_records.append({
        "txId":
            int(results.loc[idx, "txId"]),

        "Time step":
            int(results.loc[idx, "Time step"]),

        "class":
            int(results.loc[idx, "class"]),

        "ensemble_anomaly":
            float(results.loc[idx, "ensemble_anomaly"]),

        "evidence_feature_1":
            top_features[0],

        "evidence_strength_1":
            top_deviations[0],

        "evidence_feature_2":
            top_features[1],

        "evidence_strength_2":
            top_deviations[1],

        "evidence_feature_3":
            top_features[2],

        "evidence_strength_3":
            top_deviations[2],

        "evidence_feature_4":
            top_features[3],

        "evidence_strength_4":
            top_deviations[3],

        "evidence_feature_5":
            top_features[4],

        "evidence_strength_5":
            top_deviations[4]
    })


evidence_df = pd.DataFrame(
    evidence_records
)

print(
    "Evidence generated for:",
    len(evidence_df),
    "top test transactions"
)


# =============================================================================
# 28. COMBINE TOP ANOMALY + EVIDENCE
# =============================================================================

print("\n[27] BUILDING INVESTIGATION TABLE")
print("-" * 90)

investigation_df = top500.merge(
    evidence_df[
        [
            "txId",
            "evidence_feature_1",
            "evidence_strength_1",
            "evidence_feature_2",
            "evidence_strength_2",
            "evidence_feature_3",
            "evidence_strength_3",
            "evidence_feature_4",
            "evidence_strength_4",
            "evidence_feature_5",
            "evidence_strength_5"
        ]
    ],
    on="txId",
    how="left"
)

print(
    investigation_df.head(10).to_string(
        index=False
    )
)


# =============================================================================
# 29. SAVE MAIN RESULTS
# =============================================================================

print("\n[28] SAVING RESULTS")
print("-" * 90)

results_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_transaction_anomaly_results.csv"
)

top_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_top_test_anomalies.csv"
)

evidence_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_transaction_evidence.csv"
)

temporal_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_transaction_temporal_analysis.csv"
)

feature_stats_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_transaction_feature_statistics.csv"
)

summary_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_transaction_pipeline_summary.txt"
)

results.to_csv(
    results_path,
    index=False
)

top_test.to_csv(
    top_path,
    index=False
)

evidence_df.to_csv(
    evidence_path,
    index=False
)

temporal.to_csv(
    temporal_path
)

feature_stats.to_csv(
    feature_stats_path,
    index=False
)


# =============================================================================
# 30. SAVE SUMMARY
# =============================================================================

with open(
    summary_path,
    "w",
    encoding="utf-8"
) as f:

    f.write(
        "BIT-TRACE — TRANSACTION-ONLY UNSUPERVISED PIPELINE\n"
    )

    f.write(
        "=" * 70 + "\n\n"
    )

    f.write(
        "Dataset: Elliptic++ Transactions Dataset\n"
    )

    f.write(
        "P2P/network data used: NO\n"
    )

    f.write(
        "Edgelist used: NO\n\n"
    )

    f.write(
        f"Transactions: {len(data)}\n"
    )

    f.write(
        f"Selected features: {len(SELECTED_FEATURES)}\n"
    )

    f.write(
        f"Train samples: {len(train_idx)}\n"
    )

    f.write(
        f"Validation samples: {len(val_idx)}\n"
    )

    f.write(
        f"Test samples: {len(test_idx)}\n\n"
    )

    f.write(
        "Selected Features:\n"
    )

    for feature in SELECTED_FEATURES:
        f.write(
            f" - {feature}\n"
        )

    f.write("\n")

    f.write(
        f"Isolation Forest trees: {N_ESTIMATORS}\n"
    )

    f.write(
        f"IF weight: {IF_WEIGHT}\n"
    )

    f.write(
        f"LOF weight: {LOF_WEIGHT}\n\n"
    )

    try:
        f.write(
            f"Test ROC-AUC: {test_roc_auc:.6f}\n"
        )

        f.write(
            f"Test PR-AUC: {test_pr_auc:.6f}\n"
        )

    except:
        pass

    f.write("\n")
    f.write(
        "Labels were NOT used during model training.\n"
    )

    f.write(
        "Labels were used only for post-hoc evaluation.\n"
    )


# =============================================================================
# 31. FINAL STATUS
# =============================================================================

section("TRANSACTION-ONLY PIPELINE COMPLETE")

print("""
✓ Elliptic++ transaction features loaded
✓ 13 selected behavioral features used
✓ No P2P/network observations used
✓ No transaction edgelist used
✓ Missing/Inf values handled
✓ Temporal split preserved
✓ RobustScaler fitted only on training data
✓ Isolation Forest trained unsupervised
✓ LOF trained unsupervised
✓ IF + LOF ensemble generated
✓ Test anomaly ranking generated
✓ Class-3 evaluation performed post-hoc
✓ ROC-AUC / PR-AUC calculated
✓ Temporal anomaly analysis completed
✓ Feature-level anomaly evidence generated
✓ Investigation table generated
✓ Results saved

IMPORTANT:
Class labels were NOT used for model training.

OUTPUT DIRECTORY:
""")

print(OUTPUT_DIR)

print("\nFILES:")
print("1.", results_path)
print("2.", top_path)
print("3.", evidence_path)
print("4.", temporal_path)
print("5.", feature_stats_path)
print("6.", summary_path)

print("\nNext stage can use the saved investigation table")
print("for the BIT-TRACE investigator dashboard.")

==========================================================================================
BIT-TRACE — TRANSACTION-ONLY UNSUPERVISED PIPELINE
==========================================================================================

[1] FILE CHECK
------------------------------------------------------------------------------------------
FEATURE: C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv
CLASS  : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv
✓ Required transaction files found
✗ P2P / edgelist is NOT used

[2] LOADING CLASS DATA
------------------------------------------------------------------------------------------
Shape: (203769, 2)

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[3] READING FEATURE HEADER
------------------------------------------------------------------------------------------
Total columns: 184
ID column  : txId
Time column: Time step

[4] VERIFYING SELECTED FEATURES
------------------------------------------------------------------------------------------
Selected features: 13
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47
✓ All selected features found

[5] LOADING TRANSACTION FEATURES
------------------------------------------------------------------------------------------
Loaded shape: (203769, 15)

[6] DATA QUALITY
------------------------------------------------------------------------------------------
Rows: 203769
Missing txId: 0
Missing Time step: 0
Duplicate txId: 0
Feature NaN: 0
Feature Inf: 0

[7] MERGING LABELS
------------------------------------------------------------------------------------------
Merged shape: (203769, 16)
Missing class: 0

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[8] CLEANING FEATURES
------------------------------------------------------------------------------------------
Remaining NaN: 0
Remaining Inf: 0

[9] FINAL DATA
------------------------------------------------------------------------------------------
X: (203769, 13)
y: (203769,)
Time: (203769,)
Time range: 1 to 49

[10] TEMPORAL SPLIT
------------------------------------------------------------------------------------------
Train      : 136,265 (time 1–34)
Validation : 30,680 (time 35–41)
Test       : 36,824 (time 42–49)

[11] ROBUST SCALING
------------------------------------------------------------------------------------------
Train: (136265, 13)
Validation: (30680, 13)
Test: (36824, 13)
✓ Scaler fitted only on training data

[12] TRAINING ISOLATION FOREST
------------------------------------------------------------------------------------------
✓ Isolation Forest trained
Trees: 300

[13] GENERATING IF SCORES
------------------------------------------------------------------------------------------
Train: 136265
Validation: 30680
Test: 36824

[14] TRAINING LOF
------------------------------------------------------------------------------------------
✓ LOF trained

[15] GENERATING LOF SCORES
------------------------------------------------------------------------------------------
Train: 136265
Validation: 30680
Test: 36824

[16] NORMALIZING SCORES
------------------------------------------------------------------------------------------
✓ Scores normalized to approximately [0,1]

[17] BUILDING ENSEMBLE
------------------------------------------------------------------------------------------
Isolation Forest weight: 0.6
LOF weight            : 0.4
✓ Ensemble generated

[18] BUILDING RESULT TABLE
------------------------------------------------------------------------------------------

[19] SCORE DISTRIBUTION
------------------------------------------------------------------------------------------
     Split  Samples     Mean      Std      Min   Median  Max
     Train   136265 0.119556 0.162903 0.000000 0.046977  1.0
Validation    30680 0.153994 0.201526 0.000676 0.063005  1.0
      Test    36824 0.165575 0.218393 0.000341 0.064724  1.0

[20] POST-HOC CLASS-3 EVALUATION
------------------------------------------------------------------------------------------
Test ROC-AUC : 0.2392
Test PR-AUC  : 0.6319

[21] CLASS-WISE TEST SCORE ANALYSIS
------------------------------------------------------------------------------------------
       Samples      Mean       Std       Min    Median       Max
class
1          408  0.091630  0.075346  0.000341  0.076898  0.479875
2         8433  0.307741  0.258854  0.001457  0.231893  1.000000
3        27983  0.123810  0.185951  0.000376  0.046206  1.000000

[22] TOP 50 MOST ANOMALOUS TEST TRANSACTIONS
------------------------------------------------------------------------------------------
     txId  Time step  class  IF_anomaly  LOF_anomaly  ensemble_anomaly
 28468985         44      2         1.0          1.0               1.0
218079318         47      2         1.0          1.0               1.0
108353956         45      2         1.0          1.0               1.0
 83121915         47      2         1.0          1.0               1.0
 94381801         43      2         1.0          1.0               1.0
 73448313         42      2         1.0          1.0               1.0
  6244017         46      2         1.0          1.0               1.0
  6243976         46      2         1.0          1.0               1.0
 65381198         42      2         1.0          1.0               1.0
 60673519         47      2         1.0          1.0               1.0
  8180021         46      2         1.0          1.0               1.0
149843562         49      2         1.0          1.0               1.0
219436818         47      2         1.0          1.0               1.0
156066467         45      2         1.0          1.0               1.0
155840928         45      2         1.0          1.0               1.0
 41342269         42      2         1.0          1.0               1.0
219555853         47      2         1.0          1.0               1.0
155574391         45      2         1.0          1.0               1.0
155578200         45      2         1.0          1.0               1.0
 92738855         43      2         1.0          1.0               1.0
  8005107         42      2         1.0          1.0               1.0
 53450313         43      2         1.0          1.0               1.0
 73155694         42      2         1.0          1.0               1.0
 94408492         45      2         1.0          1.0               1.0
101028778         45      2         1.0          1.0               1.0
 39393441         47      2         1.0          1.0               1.0
157581531         49      2         1.0          1.0               1.0
 81789779         45      2         1.0          1.0               1.0
 66418920         46      2         1.0          1.0               1.0
 94149412         43      2         1.0          1.0               1.0
106300458         44      2         1.0          1.0               1.0
106872764         44      3         1.0          1.0               1.0
156313815         45      2         1.0          1.0               1.0
218287846         47      2         1.0          1.0               1.0
 94408153         45      2         1.0          1.0               1.0
101211541         47      2         1.0          1.0               1.0
 71822684         42      2         1.0          1.0               1.0
194350831         46      3         1.0          1.0               1.0
105594296         44      2         1.0          1.0               1.0
151742640         45      2         1.0          1.0               1.0
156160849         45      2         1.0          1.0               1.0
 91882365         43      2         1.0          1.0               1.0
157607791         49      2         1.0          1.0               1.0
218079030         47      2         1.0          1.0               1.0
194342266         46      2         1.0          1.0               1.0
194342283         46      2         1.0          1.0               1.0
174906625         46      2         1.0          1.0               1.0
218079391         47      2         1.0          1.0               1.0
106713427         44      2         1.0          1.0               1.0
 21456350         42      2         1.0          1.0               1.0

[23] TOP-K CLASS-3 ENRICHMENT
------------------------------------------------------------------------------------------
Test-set Class-3 baseline: 75.99%
Top    50: Class-3 =     2 (  4.00%) | Enrichment = 0.053x
Top   100: Class-3 =     4 (  4.00%) | Enrichment = 0.053x
Top   500: Class-3 =   348 ( 69.60%) | Enrichment = 0.916x
Top  1000: Class-3 =   392 ( 39.20%) | Enrichment = 0.516x
Top  5000: Class-3 =  2636 ( 52.72%) | Enrichment = 0.694x

[24] TEMPORAL ANOMALY ANALYSIS — TEST
------------------------------------------------------------------------------------------
           Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly  Class3_Count   Class3_%
Time step
45                 5598      0.190587        0.053288          1.0          4377  78.188639
49                 2454      0.178781        0.067878          1.0          1978  80.603097
43                 5063      0.170050        0.101809          1.0          3693  72.940944
47                 5121      0.168461        0.061768          1.0          4275  83.479789
42                 7140      0.168369        0.078325          1.0          4986  69.831933
48                 2954      0.148010        0.045998          1.0          2483  84.055518
44                 4975      0.145963        0.055050          1.0          3384  68.020101
46                 3519      0.142744        0.050892          1.0          2807  79.766979

[25] FEATURE STATISTICS
------------------------------------------------------------------------------------------
             Feature  Train_Mean  Train_Std  Train_Min  Train_Median  Train_Max
    Local_feature_53    0.039594   1.062847  -0.488366     -0.487512   6.508780
    Local_feature_54    0.039872   1.122492  -0.232553     -0.232553  15.543521
    Local_feature_52    0.024651   1.048381  -0.414036     -0.413863   7.999066
    Local_feature_59    0.034710   1.152575  -0.172895     -0.172864  14.878401
Aggregate_feature_21    0.015619   1.056232  -0.349933     -0.349933   8.502634
    Local_feature_25    0.019272   1.117571  -0.155662     -0.155654  21.548029
    Local_feature_77   -0.017208   0.938271  -0.264425     -0.263724  15.220632
    Local_feature_89    0.084872   1.054027  -0.761984     -0.449629   6.887737
    Local_feature_90    0.087371   1.077230  -0.694235     -0.447404   6.506444
Aggregate_feature_32    0.023704   1.168937  -0.145126     -0.143707  18.455158
Aggregate_feature_14   -0.144330   0.382258  -0.224985     -0.207530   8.223740
    Local_feature_22    0.002790   1.078768  -0.139732     -0.139727  25.474087
    Local_feature_47   -0.027076   0.871393  -0.243236     -0.243236  10.995787

[26] GENERATING TRANSACTION-LEVEL EVIDENCE
------------------------------------------------------------------------------------------
Evidence generated for: 500 top test transactions

[27] BUILDING INVESTIGATION TABLE
------------------------------------------------------------------------------------------
     txId  Time step  class split  IF_anomaly  LOF_anomaly  ensemble_anomaly   evidence_feature_1  evidence_strength_1   evidence_feature_2  evidence_strength_2 evidence_feature_3  evidence_strength_3   evidence_feature_4  evidence_strength_4   evidence_feature_5  evidence_strength_5
 28468985         44      2  test         1.0          1.0               1.0     Local_feature_22         46933.451202     Local_feature_25         40275.542090   Local_feature_59         10803.551578     Local_feature_47           731.558625     Local_feature_77           134.467410
218079318         47      2  test         1.0          1.0               1.0     Local_feature_22          7167.392931     Local_feature_25          4936.381948   Local_feature_47          2541.178162     Local_feature_59          1649.802295     Local_feature_77           486.189047
108353956         45      2  test         1.0          1.0               1.0     Local_feature_22         46933.451202     Local_feature_25         40275.542090   Local_feature_59         10803.551578     Local_feature_47           731.558625     Local_feature_77           134.467410
 83121915         47      2  test         1.0          1.0               1.0     Local_feature_22         79878.798758     Local_feature_25         55014.913944   Local_feature_59         18387.241237 Aggregate_feature_14           240.622035     Local_feature_47           212.236404
 94381801         43      2  test         1.0          1.0               1.0 Aggregate_feature_32          4330.007633     Local_feature_59           240.160386   Local_feature_25            83.388353     Local_feature_47            48.790288 Aggregate_feature_14            43.968502
 73448313         42      2  test         1.0          1.0               1.0     Local_feature_25          6690.746490     Local_feature_59          6638.445428   Local_feature_47           514.427052 Aggregate_feature_32            99.000177     Local_feature_77            86.828666
  6244017         46      2  test         1.0          1.0               1.0     Local_feature_59          6996.338905 Aggregate_feature_14           234.776596   Local_feature_47           222.386942     Local_feature_25           207.257198     Local_feature_77            97.311769
  6243976         46      2  test         1.0          1.0               1.0     Local_feature_22         46933.451202     Local_feature_25         44251.082951   Local_feature_59         10803.551578     Local_feature_47           731.558625 Aggregate_feature_14           230.962240
 65381198         42      2  test         1.0          1.0               1.0     Local_feature_22         46933.451202     Local_feature_25         40275.542090   Local_feature_59         10803.551578     Local_feature_47           731.558625 Aggregate_feature_14           174.612357
 60673519         47      2  test         1.0          1.0               1.0     Local_feature_22         79878.798758     Local_feature_25         55014.913944   Local_feature_59         18387.241237     Local_feature_47           212.236404     Local_feature_77           161.662090

[28] SAVING RESULTS
------------------------------------------------------------------------------------------

==========================================================================================
TRANSACTION-ONLY PIPELINE COMPLETE
==========================================================================================

✓ Elliptic++ transaction features loaded
✓ 13 selected behavioral features used
✓ No P2P/network observations used
✓ No transaction edgelist used
✓ Missing/Inf values handled
✓ Temporal split preserved
✓ RobustScaler fitted only on training data
✓ Isolation Forest trained unsupervised
✓ LOF trained unsupervised
✓ IF + LOF ensemble generated
✓ Test anomaly ranking generated
✓ Class-3 evaluation performed post-hoc
✓ ROC-AUC / PR-AUC calculated
✓ Temporal anomaly analysis completed
✓ Feature-level anomaly evidence generated
✓ Investigation table generated
✓ Results saved

IMPORTANT:
Class labels were NOT used for model training.

OUTPUT DIRECTORY:

C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\BITTRACE_TRANSACTION_RESULTS

FILES:
1. C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\BITTRACE_TRANSACTION_RESULTS\ellipticpp_transaction_anomaly_results.csv
2. C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\BITTRACE_TRANSACTION_RESULTS\ellipticpp_top_test_anomalies.csv
3. C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\BITTRACE_TRANSACTION_RESULTS\ellipticpp_transaction_evidence.csv
4. C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\BITTRACE_TRANSACTION_RESULTS\ellipticpp_transaction_temporal_analysis.csv
5. C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\BITTRACE_TRANSACTION_RESULTS\ellipticpp_transaction_feature_statistics.csv
6. C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\BITTRACE_TRANSACTION_RESULTS\ellipticpp_transaction_pipeline_summary.txt

Next stage can use the saved investigation table
for the BIT-TRACE investigator dashboard.

In [45]:
# =============================================================================
# BIT-TRACE — ELLIPTIC++ TRANSACTION-ONLY FINAL UNSUPERVISED PIPELINE
# =============================================================================
# Scope:
#   ONLY Elliptic++ Transactions Dataset
#   NO Bitcoin P2P/network dataset
#
# Pipeline:
#   Transaction features
#        ↓
#   Selected behavioral features (13)
#        +
#   Transaction graph features (10)
#        ↓
#   Robust preprocessing
#        ↓
#   Temporal split
#        ↓
#   Isolation Forest
#        +
#   LOF
#        ↓
#   Robust score normalization
#        ↓
#   Ensemble anomaly score
#        ↓
#   Temporal analysis
#        ↓
#   Post-hoc class evaluation
#        ↓
#   Feature-level explainability
#        ↓
#   Investigator evidence table
# =============================================================================

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import roc_auc_score, average_precision_score

print("=" * 95)
print("BIT-TRACE — ELLIPTIC++ TRANSACTION-ONLY FINAL PIPELINE")
print("=" * 95)


# =============================================================================
# 1. LOCATE FILES
# =============================================================================

print("\n[1] LOCATING ELLIPTIC++ FILES")
print("-" * 95)

SEARCH_ROOTS = [
    r"C:\Users\YASHIKA\Desktop\bit-trace",
    os.getcwd()
]

def find_file(filename):
    found = []

    for root in SEARCH_ROOTS:
        if not os.path.exists(root):
            continue

        for dirpath, dirnames, filenames in os.walk(root):
            if filename in filenames:
                found.append(os.path.join(dirpath, filename))

    if not found:
        return None

    # Prefer EllipticPlusPlus / raw dataset paths
    found.sort(
        key=lambda p: (
            "EllipticPlusPlus" not in p,
            "elliptic-plus-plus" not in p.lower(),
            len(p)
        )
    )

    return found[0]


FEATURE_PATH = find_file("txs_features.csv")
CLASS_PATH   = find_file("txs_classes.csv")
EDGE_PATH    = find_file("txs_edgelist.csv")

print("FEATURE:", FEATURE_PATH)
print("CLASS  :", CLASS_PATH)
print("EDGES  :", EDGE_PATH)

if FEATURE_PATH is None:
    raise FileNotFoundError("txs_features.csv not found")

if CLASS_PATH is None:
    raise FileNotFoundError("txs_classes.csv not found")

if EDGE_PATH is None:
    raise FileNotFoundError("txs_edgelist.csv not found")


# =============================================================================
# 2. SELECTED BEHAVIORAL FEATURES
# =============================================================================

BEHAVIOR_FEATURES = [
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_52",
    "Local_feature_59",
    "Aggregate_feature_21",
    "Local_feature_25",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_32",
    "Aggregate_feature_14",
    "Local_feature_22",
    "Local_feature_47"
]

print("\n[2] SELECTED BEHAVIORAL FEATURES")
print("-" * 95)

for i, f in enumerate(BEHAVIOR_FEATURES, 1):
    print(f"{i:2d}. {f}")


# =============================================================================
# 3. LOAD CLASS DATA
# =============================================================================

print("\n[3] LOADING CLASS DATA")
print("-" * 95)

classes = pd.read_csv(CLASS_PATH)

classes.columns = [
    str(c).strip().replace("\ufeff", "")
    for c in classes.columns
]

# Normalize column names
rename_map = {}

for c in classes.columns:
    cl = c.lower().replace(" ", "").replace("_", "")

    if cl == "txid":
        rename_map[c] = "txId"

    elif cl == "class":
        rename_map[c] = "class"

classes = classes.rename(columns=rename_map)

required_class_cols = {"txId", "class"}

if not required_class_cols.issubset(classes.columns):
    raise ValueError(
        f"Class file must contain {required_class_cols}, "
        f"found {classes.columns.tolist()}"
    )

classes["txId"] = pd.to_numeric(
    classes["txId"],
    errors="coerce"
)

classes["class"] = pd.to_numeric(
    classes["class"],
    errors="coerce"
)

classes = classes.dropna(
    subset=["txId", "class"]
)

classes["txId"] = classes["txId"].astype(np.int64)
classes["class"] = classes["class"].astype(int)

print("Shape:", classes.shape)
print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())


# =============================================================================
# 4. READ FEATURE HEADER
# =============================================================================

print("\n[4] READING FEATURE HEADER")
print("-" * 95)

header = pd.read_csv(
    FEATURE_PATH,
    nrows=0
)

feature_columns = header.columns.tolist()

print("Total columns:", len(feature_columns))

# Detect ID
id_candidates = [
    c for c in feature_columns
    if str(c).strip().lower() in [
        "txid",
        "tx_id",
        "transactionid",
        "transaction_id"
    ]
]

if not id_candidates:
    raise ValueError("Could not detect txId column")

TX_COL = id_candidates[0]

# Detect time
time_candidates = [
    c for c in feature_columns
    if "time" in str(c).lower()
]

if not time_candidates:
    raise ValueError("Could not detect Time step column")

TIME_COL = time_candidates[0]

print("ID column  :", TX_COL)
print("Time column:", TIME_COL)


# =============================================================================
# 5. VERIFY FEATURES
# =============================================================================

missing_features = [
    f for f in BEHAVIOR_FEATURES
    if f not in feature_columns
]

if missing_features:
    raise ValueError(
        "Missing behavioral features:\n"
        + "\n".join(missing_features)
    )

print("✓ All 13 behavioral features found")


# =============================================================================
# 6. LOAD ONLY REQUIRED TRANSACTION COLUMNS
# =============================================================================

print("\n[5] LOADING TRANSACTION FEATURES")
print("-" * 95)

LOAD_COLUMNS = [
    TX_COL,
    TIME_COL
] + BEHAVIOR_FEATURES

tx = pd.read_csv(
    FEATURE_PATH,
    usecols=LOAD_COLUMNS
)

tx = tx.rename(
    columns={
        TX_COL: "txId",
        TIME_COL: "Time step"
    }
)

tx["txId"] = pd.to_numeric(
    tx["txId"],
    errors="coerce"
)

tx["Time step"] = pd.to_numeric(
    tx["Time step"],
    errors="coerce"
)

for f in BEHAVIOR_FEATURES:
    tx[f] = pd.to_numeric(
        tx[f],
        errors="coerce"
    )

tx = tx.dropna(
    subset=["txId", "Time step"]
)

tx["txId"] = tx["txId"].astype(np.int64)

print("Transaction shape:", tx.shape)
print("Missing txId:", tx["txId"].isna().sum())
print("Missing time:", tx["Time step"].isna().sum())
print("Duplicate txId:", tx["txId"].duplicated().sum())


# =============================================================================
# 7. MERGE LABELS
# =============================================================================

print("\n[6] MERGING TRANSACTION CLASSES")
print("-" * 95)

data = tx.merge(
    classes,
    on="txId",
    how="inner",
    validate="one_to_one"
)

print("Merged shape:", data.shape)
print("Missing class:", data["class"].isna().sum())

print("\nClass distribution:")
print(data["class"].value_counts().sort_index())


# =============================================================================
# 8. CLEAN BEHAVIORAL FEATURES
# =============================================================================

print("\n[7] CLEANING BEHAVIORAL FEATURES")
print("-" * 95)

X_behavior = data[BEHAVIOR_FEATURES].copy()

X_behavior = X_behavior.replace(
    [np.inf, -np.inf],
    np.nan
)

print("NaN before:", X_behavior.isna().sum().sum())

# Median imputation
X_behavior = X_behavior.fillna(
    X_behavior.median()
)

print("NaN after :", X_behavior.isna().sum().sum())


# =============================================================================
# 9. LOAD TRANSACTION EDGES
# =============================================================================

print("\n[8] LOADING TRANSACTION GRAPH")
print("-" * 95)

edges = pd.read_csv(
    EDGE_PATH
)

edges.columns = [
    str(c).strip().replace("\ufeff", "")
    for c in edges.columns
]

print("Edge columns:", edges.columns.tolist())

# Detect source/target columns
edge_lower = {
    c.lower().replace(" ", "").replace("_", ""): c
    for c in edges.columns
}

source_candidates = [
    "txid1",
    "source",
    "from",
    "src"
]

target_candidates = [
    "txid2",
    "target",
    "to",
    "dst"
]

SOURCE_COL = None
TARGET_COL = None

for c in source_candidates:
    if c in edge_lower:
        SOURCE_COL = edge_lower[c]
        break

for c in target_candidates:
    if c in edge_lower:
        TARGET_COL = edge_lower[c]
        break

if SOURCE_COL is None or TARGET_COL is None:

    if len(edges.columns) >= 2:
        SOURCE_COL = edges.columns[0]
        TARGET_COL = edges.columns[1]

    else:
        raise ValueError(
            "Could not detect edge source/target columns"
        )

print("Source:", SOURCE_COL)
print("Target:", TARGET_COL)

edges = edges[
    [SOURCE_COL, TARGET_COL]
].copy()

edges.columns = [
    "source",
    "target"
]

edges["source"] = pd.to_numeric(
    edges["source"],
    errors="coerce"
)

edges["target"] = pd.to_numeric(
    edges["target"],
    errors="coerce"
)

edges = edges.dropna()

edges["source"] = edges["source"].astype(np.int64)
edges["target"] = edges["target"].astype(np.int64)

# Remove self loops
edges = edges[
    edges["source"] != edges["target"]
]

# Remove duplicate directed edges
edges = edges.drop_duplicates()

print("Valid edges:", len(edges))


# =============================================================================
# 10. BUILD TRANSACTION GRAPH FEATURES
# =============================================================================

print("\n[9] BUILDING TRANSACTION GRAPH FEATURES")
print("-" * 95)

tx_ids_set = set(
    data["txId"].values
)

# Only edges involving known transactions
edges_valid = edges[
    edges["source"].isin(tx_ids_set)
    &
    edges["target"].isin(tx_ids_set)
].copy()

print("Edges connected to transactions:", len(edges_valid))

# In degree
in_degree = (
    edges_valid
    .groupby("target")
    .size()
)

# Out degree
out_degree = (
    edges_valid
    .groupby("source")
    .size()
)

# Map to transactions
graph = pd.DataFrame({
    "txId": data["txId"]
})

graph["graph_in_degree"] = (
    graph["txId"]
    .map(in_degree)
    .fillna(0)
)

graph["graph_out_degree"] = (
    graph["txId"]
    .map(out_degree)
    .fillna(0)
)

graph["graph_total_degree"] = (
    graph["graph_in_degree"]
    +
    graph["graph_out_degree"]
)

graph["graph_degree_imbalance"] = (
    abs(
        graph["graph_in_degree"]
        -
        graph["graph_out_degree"]
    )
)

# Ratio
graph["graph_in_out_ratio"] = (
    (graph["graph_in_degree"] + 1.0)
    /
    (graph["graph_out_degree"] + 1.0)
)

# Log transforms
graph["graph_log_total_degree"] = np.log1p(
    graph["graph_total_degree"]
)

graph["graph_log_in_degree"] = np.log1p(
    graph["graph_in_degree"]
)

graph["graph_log_out_degree"] = np.log1p(
    graph["graph_out_degree"]
)


# Reciprocal edges
# Build set only once
edge_set = set(
    zip(
        edges_valid["source"].values,
        edges_valid["target"].values
    )
)

reciprocal_counts = {}

for s, t in zip(
    edges_valid["source"].values,
    edges_valid["target"].values
):

    if (t, s) in edge_set:

        reciprocal_counts[s] = (
            reciprocal_counts.get(s, 0) + 1
        )

        reciprocal_counts[t] = (
            reciprocal_counts.get(t, 0) + 1
        )

graph["graph_reciprocal_degree"] = (
    graph["txId"]
    .map(reciprocal_counts)
    .fillna(0)
)

graph["graph_log_reciprocal_degree"] = np.log1p(
    graph["graph_reciprocal_degree"]
)

GRAPH_FEATURES = [
    "graph_in_degree",
    "graph_out_degree",
    "graph_total_degree",
    "graph_degree_imbalance",
    "graph_in_out_ratio",
    "graph_log_total_degree",
    "graph_log_in_degree",
    "graph_log_out_degree",
    "graph_reciprocal_degree",
    "graph_log_reciprocal_degree"
]

print("Graph features:", len(GRAPH_FEATURES))

print(
    graph[GRAPH_FEATURES]
    .describe()
    .T[
        ["mean", "std", "min", "50%", "max"]
    ]
)


# =============================================================================
# 11. COMBINE BEHAVIOR + GRAPH
# =============================================================================

print("\n[10] COMBINING BEHAVIORAL + GRAPH FEATURES")
print("-" * 95)

# Ensure same row order
if not np.array_equal(
    graph["txId"].values,
    data["txId"].values
):
    raise ValueError(
        "Graph/data transaction order mismatch"
    )

X_combined = pd.concat(
    [
        X_behavior.reset_index(drop=True),
        graph[GRAPH_FEATURES].reset_index(drop=True)
    ],
    axis=1
)

ALL_FEATURES = (
    BEHAVIOR_FEATURES
    +
    GRAPH_FEATURES
)

print("Behavior features:", len(BEHAVIOR_FEATURES))
print("Graph features   :", len(GRAPH_FEATURES))
print("Total features   :", len(ALL_FEATURES))
print("Combined shape    :", X_combined.shape)


# =============================================================================
# 12. FINAL CLEANING
# =============================================================================

X_combined = X_combined.replace(
    [np.inf, -np.inf],
    np.nan
)

X_combined = X_combined.fillna(
    X_combined.median()
)

print(
    "Remaining NaN:",
    X_combined.isna().sum().sum()
)


# =============================================================================
# 13. TEMPORAL SPLIT
# =============================================================================

print("\n[11] TEMPORAL SPLIT")
print("-" * 95)

time_steps = data["Time step"].to_numpy()

train_idx = np.where(
    time_steps <= 34
)[0]

val_idx = np.where(
    (time_steps >= 35)
    &
    (time_steps <= 41)
)[0]

test_idx = np.where(
    time_steps >= 42
)[0]

print(
    f"Train      : {len(train_idx):,} "
    f"(time 1–34)"
)

print(
    f"Validation : {len(val_idx):,} "
    f"(time 35–41)"
)

print(
    f"Test       : {len(test_idx):,} "
    f"(time 42–49)"
)


# =============================================================================
# 14. ROBUST SCALING
# =============================================================================
# Fit scaler ONLY on training data to prevent temporal leakage.

print("\n[12] ROBUST SCALING")
print("-" * 95)

X_np = X_combined[
    ALL_FEATURES
].to_numpy(
    dtype=np.float32
)

scaler = RobustScaler()

X_train = scaler.fit_transform(
    X_np[train_idx]
)

X_val = scaler.transform(
    X_np[val_idx]
)

X_test = scaler.transform(
    X_np[test_idx]
)

print("Train:", X_train.shape)
print("Val  :", X_val.shape)
print("Test :", X_test.shape)


# =============================================================================
# 15. ISOLATION FOREST
# =============================================================================

print("\n[13] TRAINING ISOLATION FOREST")
print("-" * 95)

# Labels are NOT used here.

iso = IsolationForest(
    n_estimators=300,
    max_samples="auto",
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

iso.fit(
    X_train
)

print("✓ Isolation Forest trained")


# =============================================================================
# 16. IF ANOMALY SCORE
# =============================================================================
# sklearn decision_function:
# higher = more normal
#
# Therefore anomaly = negative decision_function.

if_train_raw = -iso.decision_function(X_train)
if_val_raw   = -iso.decision_function(X_val)
if_test_raw  = -iso.decision_function(X_test)

print("✓ IF scores generated")


# =============================================================================
# 17. LOF
# =============================================================================
# LOF does not support normal train/predict in the same way as IF.
# We fit LOF on training data and evaluate validation/test using
# novelty=True.
#
# n_neighbors=35 gives local neighborhood context while remaining
# computationally manageable for this dataset.

print("\n[14] TRAINING LOF")
print("-" * 95)

lof = LocalOutlierFactor(
    n_neighbors=35,
    contamination="auto",
    novelty=True,
    n_jobs=-1
)

lof.fit(X_train)

print("✓ LOF trained")

# LOF decision_function:
# higher = more normal
# Therefore anomaly = negative decision_function.

lof_train_raw = -lof.decision_function(X_train)
lof_val_raw   = -lof.decision_function(X_val)
lof_test_raw  = -lof.decision_function(X_test)

print("✓ LOF scores generated")


# =============================================================================
# 18. ROBUST SCORE NORMALIZATION
# =============================================================================
# IMPORTANT:
# Do NOT combine raw IF and LOF scores.
#
# LOF and IF have completely different numerical scales.
#
# We normalize each score using training quantiles.
# Higher normalized value = more anomalous.

print("\n[15] NORMALIZING ANOMALY SCORES")
print("-" * 95)

def robust_normalize(
    train_score,
    val_score,
    test_score
):

    q_low, q_high = np.quantile(
        train_score,
        [0.01, 0.99]
    )

    denominator = q_high - q_low

    if denominator <= 1e-12:
        denominator = 1.0

    def transform(x):
        z = (
            x - q_low
        ) / denominator

        return np.clip(
            z,
            0,
            1
        )

    return (
        transform(train_score),
        transform(val_score),
        transform(test_score)
    )


if_train, if_val, if_test = robust_normalize(
    if_train_raw,
    if_val_raw,
    if_test_raw
)

lof_train, lof_val, lof_test = robust_normalize(
    lof_train_raw,
    lof_val_raw,
    lof_test_raw
)

print("✓ IF normalized")
print("✓ LOF normalized")


# =============================================================================
# 19. ENSEMBLE
# =============================================================================
# Equal weighting avoids one model dominating because of scale.

print("\n[16] BUILDING ENSEMBLE")
print("-" * 95)

IF_WEIGHT = 0.60
LOF_WEIGHT = 0.40

ensemble_train = (
    IF_WEIGHT * if_train
    +
    LOF_WEIGHT * lof_train
)

ensemble_val = (
    IF_WEIGHT * if_val
    +
    LOF_WEIGHT * lof_val
)

ensemble_test = (
    IF_WEIGHT * if_test
    +
    LOF_WEIGHT * lof_test
)

print(
    f"Weights: IF={IF_WEIGHT} | LOF={LOF_WEIGHT}"
)

print(
    "Ensemble range:",
    float(ensemble_test.min()),
    "to",
    float(ensemble_test.max())
)


# =============================================================================
# 20. BUILD COMPLETE RESULTS TABLE
# =============================================================================

print("\n[17] BUILDING RESULTS TABLE")
print("-" * 95)

results = data[
    ["txId", "Time step", "class"]
].copy()

results["split"] = "train"

results.loc[
    val_idx,
    "split"
] = "validation"

results.loc[
    test_idx,
    "split"
] = "test"

results["IF_anomaly"] = np.nan
results["LOF_anomaly"] = np.nan
results["ensemble_anomaly"] = np.nan

results.loc[
    train_idx,
    "IF_anomaly"
] = if_train

results.loc[
    val_idx,
    "IF_anomaly"
] = if_val

results.loc[
    test_idx,
    "IF_anomaly"
] = if_test

results.loc[
    train_idx,
    "LOF_anomaly"
] = lof_train

results.loc[
    val_idx,
    "LOF_anomaly"
] = lof_val

results.loc[
    test_idx,
    "LOF_anomaly"
] = lof_test

results.loc[
    train_idx,
    "ensemble_anomaly"
] = ensemble_train

results.loc[
    val_idx,
    "ensemble_anomaly"
] = ensemble_val

results.loc[
    test_idx,
    "ensemble_anomaly"
] = ensemble_test


# =============================================================================
# 21. TOP ANOMALIES
# =============================================================================

print("\n[18] TOP 30 ANOMALOUS TRANSACTIONS")
print("-" * 95)

top30 = (
    results[
        results["split"] != "train"
    ]
    .sort_values(
        "ensemble_anomaly",
        ascending=False
    )
    .head(30)
)

print(
    top30[
        [
            "txId",
            "Time step",
            "split",
            "class",
            "IF_anomaly",
            "LOF_anomaly",
            "ensemble_anomaly"
        ]
    ].to_string(index=False)
)


# =============================================================================
# 22. TEMPORAL ANALYSIS
# =============================================================================

print("\n[19] TEMPORAL ANOMALY ANALYSIS")
print("-" * 95)

temporal = (
    results[
        results["split"] != "train"
    ]
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly=("ensemble_anomaly", "mean"),
        Median_Anomaly=("ensemble_anomaly", "median"),
        Max_Anomaly=("ensemble_anomaly", "max"),
        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"]
    /
    temporal["Transactions"]
    *
    100
)

temporal = temporal.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print(
    temporal.head(15).to_string()
)


# =============================================================================
# 23. POST-HOC CLASS-3 EVALUATION
# =============================================================================
# IMPORTANT:
# Class labels are used ONLY here for evaluation.
# They were never used for model training.

print("\n[20] POST-HOC CLASS-3 EVALUATION")
print("-" * 95)

test_results = results.loc[
    test_idx
].copy()

y_test_binary = (
    test_results["class"].values == 3
).astype(int)

score_test = (
    test_results["ensemble_anomaly"].values
)

try:

    roc = roc_auc_score(
        y_test_binary,
        score_test
    )

    pr = average_precision_score(
        y_test_binary,
        score_test
    )

    print(
        f"Test ROC-AUC : {roc:.4f}"
    )

    print(
        f"Test PR-AUC  : {pr:.4f}"
    )

except Exception as e:

    print(
        "Evaluation unavailable:",
        e
    )


# =============================================================================
# 24. TOP-K ENRICHMENT
# =============================================================================

print("\n[21] TEST-SET CLASS-3 ENRICHMENT")
print("-" * 95)

overall_class3 = (
    y_test_binary.mean()
)

print(
    f"Overall Test Class-3: "
    f"{overall_class3 * 100:.2f}%"
)

for k in [
    50,
    100,
    500,
    1000,
    5000
]:

    topk = test_results.sort_values(
        "ensemble_anomaly",
        ascending=False
    ).head(k)

    class3_pct = (
        (topk["class"] == 3)
        .mean()
    )

    enrichment = (
        class3_pct
        /
        overall_class3
        if overall_class3 > 0
        else np.nan
    )

    print(
        f"Top {k:5d}: "
        f"Class3 = {class3_pct * 100:6.2f}% | "
        f"Enrichment = {enrichment:.3f}x"
    )


# =============================================================================
# 25. FEATURE-LEVEL EXPLAINABILITY
# =============================================================================
# This is not SHAP.
#
# We calculate a practical transaction-level deviation:
#
# |scaled feature - training median|
#
# Larger value = more unusual relative to training behavior.
#
# This provides evidence for the investigator dashboard.

print("\n[22] GENERATING FEATURE-LEVEL EVIDENCE")
print("-" * 95)

train_median = np.median(
    X_train,
    axis=0
)

train_q75 = np.quantile(
    X_train,
    0.75,
    axis=0
)

train_q25 = np.quantile(
    X_train,
    0.25,
    axis=0
)

train_iqr = (
    train_q75
    -
    train_q25
)

train_iqr[
    train_iqr < 1e-6
] = 1.0

# Robust deviation:
# distance from train median in IQR units

def feature_deviation(X):

    return np.abs(
        X - train_median
    ) / train_iqr


test_deviation = feature_deviation(
    X_test
)

# top 5 evidence features
top_evidence_indices = np.argsort(
    test_deviation,
    axis=1
)[:, -5:][:, ::-1]

evidence_rows = []

test_txids = data.iloc[
    test_idx
]["txId"].values

test_times = data.iloc[
    test_idx
]["Time step"].values

test_classes = data.iloc[
    test_idx
]["class"].values

for i in range(
    len(test_idx)
):

    inds = top_evidence_indices[i]

    evidence = []

    for j in inds:

        evidence.append(
            (
                ALL_FEATURES[j],
                float(
                    test_deviation[i, j]
                )
            )
        )

    evidence_rows.append(
        evidence
    )


# =============================================================================
# 26. BUILD INVESTIGATOR EVIDENCE TABLE
# =============================================================================

evidence_df = pd.DataFrame({

    "txId": test_txids,

    "Time step": test_times,

    "class": test_classes,

    "ensemble_anomaly":
        ensemble_test,

    "IF_anomaly":
        if_test,

    "LOF_anomaly":
        lof_test,

    "evidence_1":
        [
            x[0][0]
            for x in evidence_rows
        ],

    "evidence_1_deviation":
        [
            x[0][1]
            for x in evidence_rows
        ],

    "evidence_2":
        [
            x[1][0]
            for x in evidence_rows
        ],

    "evidence_2_deviation":
        [
            x[1][1]
            for x in evidence_rows
        ],

    "evidence_3":
        [
            x[2][0]
            for x in evidence_rows
        ],

    "evidence_3_deviation":
        [
            x[2][1]
            for x in evidence_rows
        ],

    "evidence_4":
        [
            x[3][0]
            for x in evidence_rows
        ],

    "evidence_4_deviation":
        [
            x[3][1]
            for x in evidence_rows
        ],

    "evidence_5":
        [
            x[4][0]
            for x in evidence_rows
        ],

    "evidence_5_deviation":
        [
            x[4][1]
            for x in evidence_rows
        ]
})


# =============================================================================
# 27. RISK BANDS
# =============================================================================

# Thresholds are derived from TRAINING anomaly distribution,
# not from class labels.

q90 = np.quantile(
    ensemble_train,
    0.90
)

q95 = np.quantile(
    ensemble_train,
    0.95
)

q99 = np.quantile(
    ensemble_train,
    0.99
)

def risk_band(score):

    if score >= q99:
        return "EXTREME"

    elif score >= q95:
        return "HIGH"

    elif score >= q90:
        return "ELEVATED"

    else:
        return "NORMAL"


evidence_df["risk_band"] = (
    evidence_df[
        "ensemble_anomaly"
    ].apply(risk_band)
)


# =============================================================================
# 28. FINAL INVESTIGATION QUEUE
# =============================================================================

print("\n[23] FINAL INVESTIGATION QUEUE")
print("-" * 95)

investigation_queue = (
    evidence_df
    .sort_values(
        "ensemble_anomaly",
        ascending=False
    )
    .head(50)
)

print(
    investigation_queue[
        [
            "txId",
            "Time step",
            "ensemble_anomaly",
            "risk_band",
            "evidence_1",
            "evidence_2",
            "evidence_3"
        ]
    ].head(20).to_string(index=False)
)


# =============================================================================
# 29. SAVE OUTPUTS
# =============================================================================

print("\n[24] SAVING RESULTS")
print("-" * 95)

OUTPUT_DIR = os.path.join(
    os.path.dirname(FEATURE_PATH),
    "bit_trace_transaction_outputs"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

# Main anomaly results
results_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_transaction_anomaly_results.csv"
)

results.to_csv(
    results_path,
    index=False
)

# Graph features
graph_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_transaction_graph_features.csv"
)

graph.to_csv(
    graph_path,
    index=False
)

# Temporal analysis
temporal_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_temporal_anomaly_analysis.csv"
)

temporal.to_csv(
    temporal_path
)

# Investigator evidence
evidence_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_investigation_evidence.csv"
)

evidence_df.to_csv(
    evidence_path,
    index=False
)

# Top anomalies
top_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_top_investigation_queue.csv"
)

investigation_queue.to_csv(
    top_path,
    index=False
)

# Feature list
feature_info = pd.DataFrame({
    "feature": ALL_FEATURES,
    "type": (
        ["behavioral"] * len(BEHAVIOR_FEATURES)
        +
        ["graph"] * len(GRAPH_FEATURES)
    )
})

feature_info_path = os.path.join(
    OUTPUT_DIR,
    "ellipticpp_final_feature_list.csv"
)

feature_info.to_csv(
    feature_info_path,
    index=False
)

print("✓", results_path)
print("✓", graph_path)
print("✓", temporal_path)
print("✓", evidence_path)
print("✓", top_path)
print("✓", feature_info_path)


# =============================================================================
# 30. FINAL SUMMARY
# =============================================================================

print("\n")
print("=" * 95)
print("BIT-TRACE — TRANSACTION-ONLY PIPELINE COMPLETE")
print("=" * 95)

print(
    f"""
Transactions              : {len(data):,}
Transaction graph edges   : {len(edges_valid):,}

Behavioral features       : {len(BEHAVIOR_FEATURES)}
Graph features            : {len(GRAPH_FEATURES)}
Total ML features         : {len(ALL_FEATURES)}

Train transactions        : {len(train_idx):,}
Validation transactions   : {len(val_idx):,}
Test transactions         : {len(test_idx):,}

Models:
  ✓ Isolation Forest
  ✓ Local Outlier Factor
  ✓ Normalized ensemble

Labels used for training  : NO
Labels used for evaluation: YES (post-hoc only)

Outputs:
  ✓ anomaly scores
  ✓ temporal anomaly analysis
  ✓ graph features
  ✓ feature-level evidence
  ✓ investigation queue

P2P / network dataset     : NOT USED
"""
)

print("=" * 95)
print("NEXT MODULE: INVESTIGATOR DASHBOARD / EVIDENCE VISUALIZATION")
print("=" * 95)

===============================================================================================
BIT-TRACE — ELLIPTIC++ TRANSACTION-ONLY FINAL PIPELINE
===============================================================================================

[1] LOCATING ELLIPTIC++ FILES
-----------------------------------------------------------------------------------------------
FEATURE: C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_features.csv
CLASS  : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv
EDGES  : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv

[2] SELECTED BEHAVIORAL FEATURES
-----------------------------------------------------------------------------------------------
 1. Local_feature_53
 2. Local_feature_54
 3. Local_feature_52
 4. Local_feature_59
 5. Aggregate_feature_21
 6. Local_feature_25
 7. Local_feature_77
 8. Local_feature_89
 9. Local_feature_90
10. Aggregate_feature_32
11. Aggregate_feature_14
12. Local_feature_22
13. Local_feature_47

[3] LOADING CLASS DATA
-----------------------------------------------------------------------------------------------
Shape: (203769, 2)

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[4] READING FEATURE HEADER
-----------------------------------------------------------------------------------------------
Total columns: 184
ID column  : txId
Time column: Time step
✓ All 13 behavioral features found

[5] LOADING TRANSACTION FEATURES
-----------------------------------------------------------------------------------------------
Transaction shape: (203769, 15)
Missing txId: 0
Missing time: 0
Duplicate txId: 0

[6] MERGING TRANSACTION CLASSES
-----------------------------------------------------------------------------------------------
Merged shape: (203769, 16)
Missing class: 0

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[7] CLEANING BEHAVIORAL FEATURES
-----------------------------------------------------------------------------------------------
NaN before: 0
NaN after : 0

[8] LOADING TRANSACTION GRAPH
-----------------------------------------------------------------------------------------------
Edge columns: ['txId1', 'txId2']
Source: txId1
Target: txId2
Valid edges: 234355

[9] BUILDING TRANSACTION GRAPH FEATURES
-----------------------------------------------------------------------------------------------
Edges connected to transactions: 234355
Graph features: 10
                                 mean       std       min       50%  \
graph_in_degree              1.150101  3.911132  0.000000  1.000000
graph_out_degree             1.150101  1.894740  0.000000  1.000000
graph_total_degree           2.300203  4.328377  1.000000  2.000000
graph_degree_imbalance       1.150106  4.209083  0.000000  1.000000
graph_in_out_ratio           1.271243  3.315477  0.004228  1.000000
graph_log_total_degree       1.064729  0.393430  0.693147  1.098612
graph_log_in_degree          0.580863  0.467007  0.000000  0.693147
graph_log_out_degree         0.672920  0.400975  0.000000  0.693147
graph_reciprocal_degree      0.000000  0.000000  0.000000  0.000000
graph_log_reciprocal_degree  0.000000  0.000000  0.000000  0.000000

                                    max
graph_in_degree              284.000000
graph_out_degree             472.000000
graph_total_degree           473.000000
graph_degree_imbalance       471.000000
graph_in_out_ratio           285.000000
graph_log_total_degree         6.161207
graph_log_in_degree            5.652489
graph_log_out_degree           6.159095
graph_reciprocal_degree        0.000000
graph_log_reciprocal_degree    0.000000

[10] COMBINING BEHAVIORAL + GRAPH FEATURES
-----------------------------------------------------------------------------------------------
Behavior features: 13
Graph features   : 10
Total features   : 23
Combined shape    : (203769, 23)
Remaining NaN: 0

[11] TEMPORAL SPLIT
-----------------------------------------------------------------------------------------------
Train      : 136,265 (time 1–34)
Validation : 30,680 (time 35–41)
Test       : 36,824 (time 42–49)

[12] ROBUST SCALING
-----------------------------------------------------------------------------------------------
Train: (136265, 23)
Val  : (30680, 23)
Test : (36824, 23)

[13] TRAINING ISOLATION FOREST
-----------------------------------------------------------------------------------------------
✓ Isolation Forest trained
✓ IF scores generated

[14] TRAINING LOF
-----------------------------------------------------------------------------------------------
✓ LOF trained
✓ LOF scores generated

[15] NORMALIZING ANOMALY SCORES
-----------------------------------------------------------------------------------------------
✓ IF normalized
✓ LOF normalized

[16] BUILDING ENSEMBLE
-----------------------------------------------------------------------------------------------
Weights: IF=0.6 | LOF=0.4
Ensemble range: 0.0002247881532493906 to 1.0

[17] BUILDING RESULTS TABLE
-----------------------------------------------------------------------------------------------

[18] TOP 30 ANOMALOUS TRANSACTIONS
-----------------------------------------------------------------------------------------------
     txId  Time step      split  class  IF_anomaly  LOF_anomaly  ensemble_anomaly
 12780133         41 validation      2         1.0          1.0               1.0
 12780176         41 validation      2         1.0          1.0               1.0
 76509860         44       test      2         1.0          1.0               1.0
 41342269         42       test      2         1.0          1.0               1.0
 63691475         44       test      2         1.0          1.0               1.0
  3282970         48       test      2         1.0          1.0               1.0
  3286488         48       test      2         1.0          1.0               1.0
101211541         47       test      2         1.0          1.0               1.0
 50510808         44       test      2         1.0          1.0               1.0
 74045630         42       test      2         1.0          1.0               1.0
   646566         36 validation      2         1.0          1.0               1.0
 12781680         41 validation      2         1.0          1.0               1.0
156160849         45       test      2         1.0          1.0               1.0
 41927883         44       test      2         1.0          1.0               1.0
 73448434         42       test      2         1.0          1.0               1.0
 73448313         42       test      2         1.0          1.0               1.0
 34978872         42       test      2         1.0          1.0               1.0
106713427         44       test      2         1.0          1.0               1.0
 72748868         42       test      2         1.0          1.0               1.0
 72753731         42       test      2         1.0          1.0               1.0
 28468985         44       test      2         1.0          1.0               1.0
 34717366         42       test      2         1.0          1.0               1.0
 17500202         44       test      2         1.0          1.0               1.0
  9479179         48       test      2         1.0          1.0               1.0
 65381198         42       test      2         1.0          1.0               1.0
 62852493         42       test      2         1.0          1.0               1.0
  6060482         38 validation      2         1.0          1.0               1.0
 30908208         42       test      2         1.0          1.0               1.0
 94149412         43       test      2         1.0          1.0               1.0
 73405590         42       test      2         1.0          1.0               1.0

[19] TEMPORAL ANOMALY ANALYSIS
-----------------------------------------------------------------------------------------------
           Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly  Class3_Count   Class3_%
Time step
39                 2760      0.212335        0.115063          1.0          1577  57.137681
40                 4481      0.201236        0.105259          1.0          3270  72.974782
49                 2454      0.194373        0.098050          1.0          1978  80.603097
45                 5598      0.186105        0.084156          1.0          4377  78.188639
42                 7140      0.181263        0.105675          1.0          4986  69.831933
47                 5121      0.177058        0.088296          1.0          4275  83.479789
43                 5063      0.172180        0.126152          1.0          3693  72.940944
46                 3519      0.162769        0.091202          1.0          2807  79.766979
44                 4975      0.160571        0.080469          1.0          3384  68.020101
38                 2891      0.160263        0.093756          1.0          2135  73.849879
48                 2954      0.158677        0.075712          1.0          2483  84.055518
35                 5507      0.157474        0.084850          1.0          4166  75.649174
36                 6393      0.155284        0.074681          1.0          4685  73.283279
41                 5342      0.146711        0.080986          1.0          4210  78.809435
37                 3306      0.117213        0.059639          1.0          2808  84.936479

[20] POST-HOC CLASS-3 EVALUATION
-----------------------------------------------------------------------------------------------
Test ROC-AUC : 0.2449
Test PR-AUC  : 0.6245

[21] TEST-SET CLASS-3 ENRICHMENT
-----------------------------------------------------------------------------------------------
Overall Test Class-3: 75.99%
Top    50: Class3 =   2.00% | Enrichment = 0.026x
Top   100: Class3 =   7.00% | Enrichment = 0.092x
Top   500: Class3 =  16.60% | Enrichment = 0.218x
Top  1000: Class3 =  15.60% | Enrichment = 0.205x
Top  5000: Class3 =  51.58% | Enrichment = 0.679x

[22] GENERATING FEATURE-LEVEL EVIDENCE
-----------------------------------------------------------------------------------------------

[23] FINAL INVESTIGATION QUEUE
-----------------------------------------------------------------------------------------------
     txId  Time step  ensemble_anomaly risk_band       evidence_1           evidence_2           evidence_3
 39307276         47               1.0   EXTREME Local_feature_22     Local_feature_25     Local_feature_59
196089039         46               1.0   EXTREME Local_feature_59 Aggregate_feature_14 Aggregate_feature_32
196089283         46               1.0   EXTREME Local_feature_59 Aggregate_feature_14 Aggregate_feature_32
196089284         46               1.0   EXTREME Local_feature_59 Aggregate_feature_14     Local_feature_25
196260600         46               1.0   EXTREME Local_feature_59 Aggregate_feature_14 Aggregate_feature_32
 72748868         42               1.0   EXTREME Local_feature_59 Aggregate_feature_14   graph_in_out_ratio
 39393441         47               1.0   EXTREME Local_feature_22     Local_feature_25     Local_feature_59
 60673519         47               1.0   EXTREME Local_feature_22     Local_feature_25     Local_feature_59
 94267139         43               1.0   EXTREME Local_feature_59 Aggregate_feature_32 Aggregate_feature_14
106300458         44               1.0   EXTREME Local_feature_59     Local_feature_25     Local_feature_47
106302011         44               1.0   EXTREME Local_feature_59 Aggregate_feature_32   graph_in_out_ratio
 17500202         44               1.0   EXTREME Local_feature_22     Local_feature_25     Local_feature_47
 28468985         44               1.0   EXTREME Local_feature_22     Local_feature_25     Local_feature_59
 41927883         44               1.0   EXTREME Local_feature_59     Local_feature_77     Local_feature_25
 50510808         44               1.0   EXTREME Local_feature_59     Local_feature_25     Local_feature_47
 83121915         47               1.0   EXTREME Local_feature_22     Local_feature_25     Local_feature_59
 30908208         42               1.0   EXTREME Local_feature_22     Local_feature_59     Local_feature_25
106319919         44               1.0   EXTREME Local_feature_22     Local_feature_25     Local_feature_59
106320422         44               1.0   EXTREME Local_feature_59     Local_feature_25 Aggregate_feature_32
106343046         44               1.0   EXTREME Local_feature_59     Local_feature_25     Local_feature_77

[24] SAVING RESULTS
-----------------------------------------------------------------------------------------------
✓ C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\bit_trace_transaction_outputs\ellipticpp_transaction_anomaly_results.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\bit_trace_transaction_outputs\ellipticpp_transaction_graph_features.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\bit_trace_transaction_outputs\ellipticpp_temporal_anomaly_analysis.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\bit_trace_transaction_outputs\ellipticpp_investigation_evidence.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\bit_trace_transaction_outputs\ellipticpp_top_investigation_queue.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\bit_trace_transaction_outputs\ellipticpp_final_feature_list.csv


===============================================================================================
BIT-TRACE — TRANSACTION-ONLY PIPELINE COMPLETE
===============================================================================================

Transactions              : 203,769
Transaction graph edges   : 234,355

Behavioral features       : 13
Graph features            : 10
Total ML features         : 23

Train transactions        : 136,265
Validation transactions   : 30,680
Test transactions         : 36,824

Models:
  ✓ Isolation Forest
  ✓ Local Outlier Factor
  ✓ Normalized ensemble

Labels used for training  : NO
Labels used for evaluation: YES (post-hoc only)

Outputs:
  ✓ anomaly scores
  ✓ temporal anomaly analysis
  ✓ graph features
  ✓ feature-level evidence
  ✓ investigation queue

P2P / network dataset     : NOT USED

===============================================================================================
NEXT MODULE: INVESTIGATOR DASHBOARD / EVIDENCE VISUALIZATION
===============================================================================================

In [46]:
# =============================================================================
# BIT-TRACE — TRANSACTION-ONLY FINAL EVALUATION + EXPLAINABILITY
# Graph + Behavioral Unsupervised Anomaly Detection
# P2P DATA NOT USED
# =============================================================================

import os
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score, average_precision_score

print("=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY FINAL EVALUATION + EXPLAINABILITY")
print("=" * 100)

# =============================================================================
# 1. LOCATE SAVED RESULT FILE
# =============================================================================

possible_files = [
    r"C:\Users\YASHIKA\Desktop\bit-trace\ellipticpp_graph_behavioral_anomaly_results.csv",
    r"C:\Users\YASHIKA\Desktop\bit-trace\data\processed\ellipticpp_graph_behavioral_anomaly_results.csv",
    r"C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_behavioral_anomaly_results.csv",
]

result_path = None

for p in possible_files:
    if os.path.exists(p):
        result_path = p
        break

# Recursive fallback search
if result_path is None:
    for root, dirs, files in os.walk(
        r"C:\Users\YASHIKA\Desktop\bit-trace"
    ):
        if "ellipticpp_graph_behavioral_anomaly_results.csv" in files:
            result_path = os.path.join(
                root,
                "ellipticpp_graph_behavioral_anomaly_results.csv"
            )
            break

if result_path is None:
    raise FileNotFoundError(
        "ellipticpp_graph_behavioral_anomaly_results.csv not found."
    )

print("\n[1] RESULT FILE")
print("-" * 80)
print(result_path)

df = pd.read_csv(result_path)

print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist())


# =============================================================================
# 2. NORMALIZE COLUMN NAMES
# =============================================================================

df.columns = [str(c).strip() for c in df.columns]

# Find columns robustly
def find_col(candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None

tx_col = find_col(["txId", "txid", "TxId", "transaction_id"])
time_col = find_col(["Time step", "time_step", "Time_step", "time"])
class_col = find_col(["class", "Class", "label"])
score_col = find_col([
    "ensemble_anomaly",
    "Ensemble_Anomaly",
    "anomaly_score",
    "Anomaly_Score"
])

if tx_col is None:
    raise ValueError("Transaction ID column not found.")

if time_col is None:
    raise ValueError("Time step column not found.")

if class_col is None:
    raise ValueError("Class column not found.")

if score_col is None:
    raise ValueError(
        "Ensemble anomaly score column not found.\n"
        f"Available columns: {df.columns.tolist()}"
    )

print("\nDetected columns:")
print("txId       :", tx_col)
print("Time step  :", time_col)
print("Class      :", class_col)
print("Score      :", score_col)


# =============================================================================
# 3. BASIC VALIDATION
# =============================================================================

df = df.copy()

df[tx_col] = pd.to_numeric(df[tx_col], errors="coerce")
df[time_col] = pd.to_numeric(df[time_col], errors="coerce")
df[class_col] = pd.to_numeric(df[class_col], errors="coerce")
df[score_col] = pd.to_numeric(df[score_col], errors="coerce")

df = df.dropna(
    subset=[tx_col, time_col, class_col, score_col]
).copy()

print("\n[2] DATA VALIDATION")
print("-" * 80)

print("Rows:", len(df))
print("Missing scores:", df[score_col].isna().sum())
print("Time range:",
      int(df[time_col].min()),
      "to",
      int(df[time_col].max()))

print("\nClass distribution:")
print(df[class_col].value_counts().sort_index())


# =============================================================================
# 4. CREATE TEMPORAL SPLIT
# =============================================================================

df["split"] = np.select(
    [
        df[time_col] <= 34,
        (df[time_col] >= 35) & (df[time_col] <= 41),
        df[time_col] >= 42
    ],
    [
        "train",
        "validation",
        "test"
    ],
    default="unknown"
)

print("\n[3] TEMPORAL SPLIT")
print("-" * 80)

print(
    df["split"].value_counts()
)

test_df = df[df["split"] == "test"].copy()

if len(test_df) == 0:
    raise ValueError("No test samples found.")


# =============================================================================
# 5. IMPORTANT:
#    SCORE DIRECTION
# =============================================================================
#
# For this pipeline, larger ensemble_anomaly values represent stronger
# anomaly according to the generated ranking.
#
# Therefore:
# top anomalies = descending score
# =============================================================================

print("\n[4] SCORE DIRECTION")
print("-" * 80)

print(
    "Highest score:",
    test_df[score_col].max()
)

print(
    "Lowest score :",
    test_df[score_col].min()
)

print(
    "Top anomaly = highest ensemble anomaly score"
)


# =============================================================================
# 6. TEST CLASS-WISE ANALYSIS
# =============================================================================

print("\n" + "=" * 100)
print("TEST SET — CLASS-WISE ANOMALY ANALYSIS")
print("=" * 100)

class_summary = (
    test_df
    .groupby(class_col)[score_col]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(class_summary.to_string())


# =============================================================================
# 7. ROC-AUC + PR-AUC
# =============================================================================
#
# Class 3 = positive class.
#
# These are POST-HOC evaluations only.
# Labels are NOT used for unsupervised model training.
# =============================================================================

print("\n" + "=" * 100)
print("TEST SET — CLASS-3 POST-HOC EVALUATION")
print("=" * 100)

y_true = (test_df[class_col] == 3).astype(int)
scores = test_df[score_col].to_numpy()

if y_true.nunique() == 2:

    roc_auc = roc_auc_score(
        y_true,
        scores
    )

    pr_auc = average_precision_score(
        y_true,
        scores
    )

    print(f"Test ROC-AUC : {roc_auc:.4f}")
    print(f"Test PR-AUC  : {pr_auc:.4f}")

else:
    roc_auc = np.nan
    pr_auc = np.nan

    print("ROC-AUC / PR-AUC unavailable.")


# =============================================================================
# 8. TOP-K ANOMALY ANALYSIS
# =============================================================================

print("\n" + "=" * 100)
print("TOP-K ANOMALY ANALYSIS")
print("=" * 100)

overall_class3_pct = (
    (test_df[class_col] == 3).mean() * 100
)

print(
    f"Overall Test Class-3 percentage: "
    f"{overall_class3_pct:.2f}%"
)

topk_results = []

for k in [50, 100, 250, 500, 1000, 2500, 5000]:

    k = min(k, len(test_df))

    topk = (
        test_df
        .nlargest(k, score_col)
        .copy()
    )

    class3_count = (
        (topk[class_col] == 3).sum()
    )

    class3_pct = (
        class3_count / k * 100
    )

    enrichment = (
        class3_pct / overall_class3_pct
        if overall_class3_pct > 0
        else np.nan
    )

    topk_results.append({
        "Top_K": k,
        "Class3_Count": int(class3_count),
        "Class3_%": class3_pct,
        "Overall_Class3_%": overall_class3_pct,
        "Enrichment": enrichment
    })

topk_df = pd.DataFrame(topk_results)

print(topk_df.to_string(index=False))


# =============================================================================
# 9. TOP 100 MOST ANOMALOUS TRANSACTIONS
# =============================================================================

print("\n" + "=" * 100)
print("TOP 100 MOST ANOMALOUS TRANSACTIONS")
print("=" * 100)

top100 = (
    test_df
    .nlargest(100, score_col)
    [[
        tx_col,
        time_col,
        class_col,
        score_col
    ]]
    .copy()
)

print(
    top100.head(30).to_string(index=False)
)


# =============================================================================
# 10. ANOMALY THRESHOLDS
# =============================================================================
#
# Unsupervised thresholding:
# 99th percentile
# 99.5th percentile
# 99.9th percentile
# =============================================================================

print("\n" + "=" * 100)
print("UNSUPERVISED ANOMALY THRESHOLDS — TEST SET")
print("=" * 100)

threshold_rows = []

for pct in [95, 97, 99, 99.5, 99.9]:

    threshold = np.percentile(
        test_df[score_col],
        pct
    )

    flagged = (
        test_df[score_col] >= threshold
    )

    flagged_df = test_df[flagged]

    class3_count = (
        (flagged_df[class_col] == 3).sum()
    )

    class3_pct = (
        class3_count / len(flagged_df) * 100
        if len(flagged_df) > 0
        else 0
    )

    threshold_rows.append({
        "Percentile": pct,
        "Threshold": threshold,
        "Flagged": len(flagged_df),
        "Class3_Count": int(class3_count),
        "Class3_%": class3_pct
    })

threshold_df = pd.DataFrame(threshold_rows)

print(
    threshold_df.to_string(index=False)
)


# =============================================================================
# 11. TEMPORAL ANOMALY ANALYSIS
# =============================================================================

print("\n" + "=" * 100)
print("TEMPORAL ANOMALY ANALYSIS — TEST")
print("=" * 100)

temporal = (
    test_df
    .groupby(time_col)
    .agg(
        Transactions=(tx_col, "count"),
        Mean_Anomaly=(score_col, "mean"),
        Median_Anomaly=(score_col, "median"),
        Max_Anomaly=(score_col, "max")
    )
    .sort_values(
        "Mean_Anomaly",
        ascending=False
    )
)

print(
    temporal.head(15).to_string()
)


# =============================================================================
# 12. TEMPORAL CLASS-3 CONCENTRATION
# =============================================================================

temporal_class3 = (
    test_df
    .groupby(time_col)
    .agg(
        Transactions=(tx_col, "count"),
        Class3_Count=(class_col, lambda x: (x == 3).sum()),
        Mean_Anomaly=(score_col, "mean"),
        Max_Anomaly=(score_col, "max")
    )
)

temporal_class3["Class3_%"] = (
    temporal_class3["Class3_Count"]
    / temporal_class3["Transactions"]
    * 100
)

temporal_class3 = temporal_class3.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print("\nTop anomalous time steps:")
print(
    temporal_class3.head(15).to_string()
)


# =============================================================================
# 13. BEHAVIORAL FEATURE EXPLAINABILITY
# =============================================================================
#
# If original behavioral feature columns are present in saved results,
# calculate contribution using absolute standardized magnitude.
#
# If they are not present, reload ONLY the 13 selected features from
# txs_features.csv.
# =============================================================================

print("\n" + "=" * 100)
print("FEATURE-LEVEL EXPLAINABILITY")
print("=" * 100)

behavioral_features = [
    "Local_feature_22",
    "Local_feature_25",
    "Local_feature_47",
    "Local_feature_52",
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_59",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_14",
    "Aggregate_feature_21",
    "Aggregate_feature_32"
]

available_features = [
    f for f in behavioral_features
    if f in df.columns
]

print(
    "Behavioral features already available:",
    len(available_features)
)

# -------------------------------------------------------------------------
# If feature columns are not saved in anomaly results, load them directly.
# -------------------------------------------------------------------------

if len(available_features) < len(behavioral_features):

    feature_path = (
        r"C:\Users\YASHIKA\Desktop\bit-trace"
        r"\data\raw\elliptic-plus-plus"
        r"\txs_features.csv"
    )

    if not os.path.exists(feature_path):

        feature_path = (
            r"C:\Users\YASHIKA\Desktop\bit-trace"
            r"\EllipticPlusPlus\Transactions Dataset"
            r"\txs_features.csv"
        )

    if os.path.exists(feature_path):

        print("\nLoading only required behavioral features...")

        needed_cols = [
            "txId"
        ] + behavioral_features

        feature_data = pd.read_csv(
            feature_path,
            usecols=needed_cols
        )

        feature_data["txId"] = pd.to_numeric(
            feature_data["txId"],
            errors="coerce"
        )

        for f in behavioral_features:
            feature_data[f] = pd.to_numeric(
                feature_data[f],
                errors="coerce"
            )

        df = df.merge(
            feature_data,
            left_on=tx_col,
            right_on="txId",
            how="left",
            suffixes=("", "_feature")
        )

        # Avoid duplicate txId column confusion
        if "txId_feature" in df.columns:
            df.drop(
                columns=["txId_feature"],
                inplace=True
            )

        test_df = df[
            df["split"] == "test"
        ].copy()

        print(
            "Behavioral features loaded successfully."
        )

    else:
        print(
            "WARNING: txs_features.csv not found."
        )

        print(
            "Skipping feature-level contribution analysis."
        )


# =============================================================================
# 14. STANDARDIZED FEATURE CONTRIBUTION
# =============================================================================

available_features = [
    f for f in behavioral_features
    if f in test_df.columns
]

if len(available_features) > 0:

    feature_matrix = (
        test_df[available_features]
        .apply(pd.to_numeric, errors="coerce")
    )

    feature_matrix = feature_matrix.replace(
        [np.inf, -np.inf],
        np.nan
    )

    feature_matrix = feature_matrix.fillna(
        feature_matrix.median()
    )

    # Dataset features were already standardized in the previous pipeline.
    # We still calculate robust z-score here to make contribution comparable.
    means = feature_matrix.mean()
    stds = feature_matrix.std().replace(0, 1)

    z = (
        feature_matrix - means
    ) / stds

    abs_z = z.abs()

    feature_importance = (
        abs_z
        .mean()
        .sort_values(ascending=False)
        .reset_index()
    )

    feature_importance.columns = [
        "Feature",
        "Mean_Absolute_Deviation"
    ]

    print("\nGlobal behavioral feature contribution:")
    print(
        feature_importance.to_string(index=False)
    )

else:

    feature_importance = pd.DataFrame(
        columns=[
            "Feature",
            "Mean_Absolute_Deviation"
        ]
    )


# =============================================================================
# 15. TOP TRANSACTION EXPLANATIONS
# =============================================================================

print("\n" + "=" * 100)
print("TOP TRANSACTION EXPLANATIONS")
print("=" * 100)

if len(available_features) > 0:

    # Get top 100 anomalous test transactions
    explain_df = (
        test_df
        .nlargest(100, score_col)
        .copy()
    )

    explain_matrix = (
        explain_df[available_features]
        .apply(pd.to_numeric, errors="coerce")
    )

    explain_matrix = explain_matrix.replace(
        [np.inf, -np.inf],
        np.nan
    )

    explain_matrix = explain_matrix.fillna(
        feature_matrix[available_features].median()
    )

    global_means = (
        feature_matrix[available_features].mean()
    )

    global_stds = (
        feature_matrix[available_features]
        .std()
        .replace(0, 1)
    )

    explain_z = (
        explain_matrix - global_means
    ) / global_stds

    explain_abs = explain_z.abs()

    # Top 3 contributing features per transaction
    top_feature_names = []

    for idx in explain_abs.index:

        row = explain_abs.loc[idx]

        top_features = (
            row
            .sort_values(ascending=False)
            .head(3)
            .index
            .tolist()
        )

        top_feature_names.append(
            ", ".join(top_features)
        )

    explain_df["Top_Contributing_Features"] = (
        top_feature_names
    )

    evidence_df = explain_df[
        [
            tx_col,
            time_col,
            class_col,
            score_col,
            "Top_Contributing_Features"
        ]
    ].copy()

    print(
        evidence_df.head(30).to_string(index=False)
    )

else:

    evidence_df = pd.DataFrame()


# =============================================================================
# 16. FINAL INVESTIGATION PRIORITY TABLE
# =============================================================================

print("\n" + "=" * 100)
print("BIT-TRACE — FINAL INVESTIGATION PRIORITY")
print("=" * 100)

priority_df = (
    test_df
    .nlargest(500, score_col)
    .copy()
)

priority_df["Anomaly_Rank"] = (
    np.arange(1, len(priority_df) + 1)
)

priority_df["Class3_Flag"] = (
    priority_df[class_col] == 3
).astype(int)

priority_columns = [
    "Anomaly_Rank",
    tx_col,
    time_col,
    class_col,
    score_col,
    "Class3_Flag"
]

priority_columns = [
    c for c in priority_columns
    if c in priority_df.columns
]

priority_df = priority_df[
    priority_columns
]


# =============================================================================
# 17. SAVE ALL RESULTS
# =============================================================================

print("\n" + "=" * 100)
print("SAVING FINAL TRANSACTION-ONLY RESULTS")
print("=" * 100)

output_dir = (
    r"C:\Users\YASHIKA\Desktop\bit-trace"
)

files_saved = []

def save_csv(dataframe, filename):

    path = os.path.join(
        output_dir,
        filename
    )

    dataframe.to_csv(
        path,
        index=False
    )

    files_saved.append(path)

    print("✓", path)


save_csv(
    topk_df,
    "bittrace_transaction_topk_analysis.csv"
)

save_csv(
    threshold_df,
    "bittrace_transaction_threshold_analysis.csv"
)

save_csv(
    temporal_class3.reset_index(),
    "bittrace_transaction_temporal_analysis.csv"
)

save_csv(
    class_summary.reset_index(),
    "bittrace_transaction_class_summary.csv"
)

save_csv(
    priority_df,
    "bittrace_transaction_investigation_priority.csv"
)

if len(feature_importance) > 0:

    save_csv(
        feature_importance,
        "bittrace_transaction_feature_importance.csv"
    )

if len(evidence_df) > 0:

    save_csv(
        evidence_df,
        "bittrace_transaction_explainability.csv"
    )


# =============================================================================
# 18. FINAL SUMMARY
# =============================================================================

print("\n" + "=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY PIPELINE STATUS")
print("=" * 100)

print(f"""
Dataset
-------
Transactions             : {len(df):,}
Time steps               : {int(df[time_col].min())}–{int(df[time_col].max())}

Temporal split
-------------
Train                    : {(df["split"] == "train").sum():,}
Validation               : {(df["split"] == "validation").sum():,}
Test                     : {(df["split"] == "test").sum():,}

Models
------
Isolation Forest         : ✓
LOF                      : ✓
Ensemble                 : ✓
Graph features           : ✓
Behavioral features      : ✓

Post-hoc evaluation
-------------------
Class-3 ROC-AUC          : {roc_auc:.4f}
Class-3 PR-AUC           : {pr_auc:.4f}

Output
------
Top-K analysis           : ✓
Threshold analysis       : ✓
Temporal analysis        : ✓
Feature explainability   : {'✓' if len(feature_importance) > 0 else 'Not available'}
Investigation table      : ✓
""")

print("Saved files:")
for f in files_saved:
    print("✓", f)

print("\n" + "=" * 100)
print("TRANSACTION-ONLY ANALYSIS COMPLETE")
print("=" * 100)

print("""
Interpretation reminder:
The model is UNSUPERVISED.
Class labels are used only after scoring for evaluation/analysis.

The anomaly score should therefore be interpreted as:
"how unusual is this transaction according to the learned
behavioral + transaction-graph structure"

It should NOT automatically be interpreted as:
"this transaction is illicit."

Next stage after this:
investigator-facing evidence generation / dashboard integration.
P2P data is NOT used in this pipeline.
""")

====================================================================================================
BIT-TRACE — TRANSACTION-ONLY FINAL EVALUATION + EXPLAINABILITY
====================================================================================================

[1] RESULT FILE
--------------------------------------------------------------------------------
C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_behavioral_anomaly_results.csv
Shape: (203769, 6)
Columns:
['txId', 'Time step', 'IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly', 'split']

ValueError: Class column not found.

In [47]:
# =============================================================================
# BIT-TRACE — FINAL TRANSACTION-ONLY EVALUATION
# Uses SAVED anomaly results + txs_classes.csv
# Does NOT reload 662 MB feature file
# =============================================================================

import os
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score, average_precision_score

print("=" * 100)
print("BIT-TRACE — FINAL TRANSACTION-ONLY EVALUATION")
print("=" * 100)

# -------------------------------------------------------------------------
# PATHS
# -------------------------------------------------------------------------

RESULT_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_behavioral_anomaly_results.csv"

CLASS_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv"

OUTPUT_DIR = r"C:\Users\YASHIKA\Desktop\bit-trace"

# -------------------------------------------------------------------------
# 1. LOAD SAVED ANOMALY RESULTS
# -------------------------------------------------------------------------

print("\n[1] LOADING ANOMALY RESULTS")
print("-" * 80)

if not os.path.exists(RESULT_PATH):
    raise FileNotFoundError(RESULT_PATH)

results = pd.read_csv(RESULT_PATH)

print("Shape:", results.shape)
print("Columns:", results.columns.tolist())

# -------------------------------------------------------------------------
# 2. LOAD ONLY CLASS DATA
# -------------------------------------------------------------------------

print("\n[2] LOADING CLASS LABELS")
print("-" * 80)

if not os.path.exists(CLASS_PATH):
    raise FileNotFoundError(CLASS_PATH)

classes = pd.read_csv(CLASS_PATH)

classes.columns = [
    str(c).strip()
    for c in classes.columns
]

print("Shape:", classes.shape)
print("Columns:", classes.columns.tolist())

# Normalize names

if "txId" not in classes.columns:
    # try first column as transaction ID
    classes = classes.rename(
        columns={classes.columns[0]: "txId"}
    )

if "class" not in classes.columns:
    # try second column as class
    classes = classes.rename(
        columns={classes.columns[1]: "class"}
    )

classes["txId"] = pd.to_numeric(
    classes["txId"],
    errors="coerce"
)

classes["class"] = pd.to_numeric(
    classes["class"],
    errors="coerce"
)

classes = classes.dropna(
    subset=["txId", "class"]
)

print("\nClass distribution:")
print(
    classes["class"]
    .value_counts()
    .sort_index()
)

# -------------------------------------------------------------------------
# 3. MERGE LABELS
# -------------------------------------------------------------------------

print("\n[3] MERGING LABELS")
print("-" * 80)

results["txId"] = pd.to_numeric(
    results["txId"],
    errors="coerce"
)

results["Time step"] = pd.to_numeric(
    results["Time step"],
    errors="coerce"
)

results["ensemble_anomaly"] = pd.to_numeric(
    results["ensemble_anomaly"],
    errors="coerce"
)

results = results.dropna(
    subset=[
        "txId",
        "Time step",
        "ensemble_anomaly"
    ]
)

df = results.merge(
    classes[["txId", "class"]],
    on="txId",
    how="left"
)

print("Merged shape:", df.shape)
print(
    "Missing labels:",
    df["class"].isna().sum()
)

if df["class"].isna().sum() > 0:
    print("\nWARNING: Some transactions have no class label.")

df = df.dropna(
    subset=["class"]
).copy()

df["class"] = df["class"].astype(int)

print("\nFinal class distribution:")
print(
    df["class"]
    .value_counts()
    .sort_index()
)

# -------------------------------------------------------------------------
# 4. TEST SET
# -------------------------------------------------------------------------

print("\n[4] TEST SET")
print("-" * 80)

test_df = df[
    df["split"].astype(str).str.lower() == "test"
].copy()

if len(test_df) == 0:

    print(
        "Saved split column did not identify test rows."
    )

    # Recover from time steps
    test_df = df[
        df["Time step"] >= 42
    ].copy()

print("Test samples:", len(test_df))
print(
    "Test time:",
    test_df["Time step"].min(),
    "to",
    test_df["Time step"].max()
)

# -------------------------------------------------------------------------
# 5. CLASS-WISE SCORE ANALYSIS
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("CLASS-WISE ANOMALY SCORE ANALYSIS")
print("=" * 100)

class_summary = (
    test_df
    .groupby("class")["ensemble_anomaly"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(
    class_summary.to_string()
)

# -------------------------------------------------------------------------
# 6. CLASS-3 ROC-AUC / PR-AUC
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("CLASS-3 POST-HOC EVALUATION")
print("=" * 100)

y_true = (
    test_df["class"] == 3
).astype(int)

scores = test_df[
    "ensemble_anomaly"
].to_numpy()

roc_auc = roc_auc_score(
    y_true,
    scores
)

pr_auc = average_precision_score(
    y_true,
    scores
)

print(
    f"Test ROC-AUC : {roc_auc:.4f}"
)

print(
    f"Test PR-AUC  : {pr_auc:.4f}"
)

# -------------------------------------------------------------------------
# 7. TOP-K ANALYSIS
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TOP-K ANOMALY ANALYSIS")
print("=" * 100)

overall_class3_pct = (
    (test_df["class"] == 3).mean()
    * 100
)

print(
    f"Overall Test Class-3: "
    f"{overall_class3_pct:.2f}%"
)

topk_rows = []

for k in [50, 100, 250, 500, 1000, 2500, 5000]:

    k = min(k, len(test_df))

    topk = (
        test_df
        .nlargest(
            k,
            "ensemble_anomaly"
        )
    )

    c3 = (
        topk["class"] == 3
    ).sum()

    c3_pct = (
        c3 / k * 100
    )

    enrichment = (
        c3_pct /
        overall_class3_pct
    )

    topk_rows.append({
        "Top_K": k,
        "Class3_Count": int(c3),
        "Class3_%": c3_pct,
        "Enrichment": enrichment
    })

topk_df = pd.DataFrame(
    topk_rows
)

print(
    topk_df.to_string(index=False)
)

# -------------------------------------------------------------------------
# 8. TOP 100 ANOMALOUS TRANSACTIONS
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TOP 100 MOST ANOMALOUS TEST TRANSACTIONS")
print("=" * 100)

top100 = (
    test_df
    .nlargest(
        100,
        "ensemble_anomaly"
    )
    [
        [
            "txId",
            "Time step",
            "class",
            "IF_anomaly",
            "LOF_anomaly",
            "ensemble_anomaly"
        ]
    ]
)

print(
    top100.head(30).to_string(
        index=False
    )
)

# -------------------------------------------------------------------------
# 9. CLASS DISTRIBUTION OF TOP ANOMALIES
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("CLASS DISTRIBUTION AMONG TOP ANOMALIES")
print("=" * 100)

for k in [50, 100, 500, 1000, 5000]:

    k = min(
        k,
        len(test_df)
    )

    topk = (
        test_df
        .nlargest(
            k,
            "ensemble_anomaly"
        )
    )

    counts = (
        topk["class"]
        .value_counts()
        .sort_index()
    )

    print(f"\nTop {k}:")
    print(counts)

# -------------------------------------------------------------------------
# 10. TEMPORAL ANALYSIS
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TEMPORAL ANOMALY ANALYSIS")
print("=" * 100)

temporal = (
    test_df
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly=(
            "ensemble_anomaly",
            "mean"
        ),
        Median_Anomaly=(
            "ensemble_anomaly",
            "median"
        ),
        Max_Anomaly=(
            "ensemble_anomaly",
            "max"
        ),
        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"]
    /
    temporal["Transactions"]
    * 100
)

temporal = temporal.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print(
    temporal.head(15).to_string()
)

# -------------------------------------------------------------------------
# 11. ANOMALY THRESHOLDS
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("UNSUPERVISED ANOMALY THRESHOLDS")
print("=" * 100)

threshold_rows = []

for percentile in [
    95,
    97,
    99,
    99.5,
    99.9
]:

    threshold = np.percentile(
        test_df["ensemble_anomaly"],
        percentile
    )

    flagged = test_df[
        test_df["ensemble_anomaly"]
        >= threshold
    ]

    class3_count = (
        flagged["class"] == 3
    ).sum()

    class3_pct = (
        class3_count /
        len(flagged) * 100
        if len(flagged) > 0
        else 0
    )

    threshold_rows.append({
        "Percentile": percentile,
        "Threshold": threshold,
        "Flagged": len(flagged),
        "Class3_Count": int(
            class3_count
        ),
        "Class3_%": class3_pct
    })

threshold_df = pd.DataFrame(
    threshold_rows
)

print(
    threshold_df.to_string(
        index=False
    )
)

# -------------------------------------------------------------------------
# 12. SAVE RESULTS
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("SAVING FINAL RESULTS")
print("=" * 100)

outputs = {

    "bittrace_transaction_class_summary.csv":
        class_summary.reset_index(),

    "bittrace_transaction_topk_analysis.csv":
        topk_df,

    "bittrace_transaction_temporal_analysis.csv":
        temporal.reset_index(),

    "bittrace_transaction_threshold_analysis.csv":
        threshold_df,

    "bittrace_transaction_top100.csv":
        top100,

    "bittrace_transaction_final_evaluation.csv":
        test_df
}

for filename, data in outputs.items():

    path = os.path.join(
        OUTPUT_DIR,
        filename
    )

    data.to_csv(
        path,
        index=False
    )

    print("✓", path)

# -------------------------------------------------------------------------
# 13. FINAL STATUS
# -------------------------------------------------------------------------

print("\n" + "=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY EVALUATION COMPLETE")
print("=" * 100)

print(f"""
Transactions evaluated : {len(test_df):,}
Test time steps         : 42–49

Class-3 ROC-AUC         : {roc_auc:.4f}
Class-3 PR-AUC          : {pr_auc:.4f}

Isolation Forest        : ✓
LOF                     : ✓
Graph features          : ✓
Behavioral features     : ✓
Ensemble score          : ✓
Temporal evaluation     : ✓
Top-K analysis          : ✓
Threshold analysis      : ✓

P2P / network data      : NOT USED
""")

print("=" * 100)

====================================================================================================
BIT-TRACE — FINAL TRANSACTION-ONLY EVALUATION
====================================================================================================

[1] LOADING ANOMALY RESULTS
--------------------------------------------------------------------------------
Shape: (203769, 6)
Columns: ['txId', 'Time step', 'IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly', 'split']

[2] LOADING CLASS LABELS
--------------------------------------------------------------------------------
Shape: (203769, 2)
Columns: ['txId', 'class']

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[3] MERGING LABELS
--------------------------------------------------------------------------------
Merged shape: (203769, 7)
Missing labels: 0

Final class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[4] TEST SET
--------------------------------------------------------------------------------
Test samples: 36824
Test time: 42 to 49

====================================================================================================
CLASS-WISE ANOMALY SCORE ANALYSIS
====================================================================================================
       Samples      Mean       Std       Min    Median        Max
class
1          408  1.000417  2.481678 -0.423081  0.469885  36.514263
2         8433  2.565138  4.613926 -0.414446  1.533599  61.643950
3        27983  1.141037  2.990874 -0.442719  0.389322  73.344260

====================================================================================================
CLASS-3 POST-HOC EVALUATION
====================================================================================================
Test ROC-AUC : 0.2948
Test PR-AUC  : 0.6576

====================================================================================================
TOP-K ANOMALY ANALYSIS
====================================================================================================
Overall Test Class-3: 75.99%
 Top_K  Class3_Count  Class3_%  Enrichment
    50            22     44.00    0.579014
   100            40     40.00    0.526377
   250           101     40.40    0.531640
   500           296     59.20    0.779038
  1000           612     61.20    0.805356
  2500          1424     56.96    0.749560
  5000          2826     56.52    0.743770

====================================================================================================
TOP 100 MOST ANOMALOUS TEST TRANSACTIONS
====================================================================================================
     txId  Time step  class  IF_anomaly  LOF_anomaly  ensemble_anomaly
158275512         49      3    0.251841   182.982900         73.344260
 98649329         43      3    1.304740   161.249400         65.282610
218135759         47      2    3.981976   148.136920         61.643950
 94260854         43      2    5.145474   134.183140         56.760540
 95040255         43      3    1.088471   136.983690         55.446556
 98649322         43      3    1.088471   136.948760         55.432587
181949645         45      2   -0.021776   136.211200         54.471413
 73424761         42      2    0.180798   134.552430         53.929455
 71465831         42      2    0.284408   133.438390         53.545998
 95040590         43      3    1.109185   132.080720         53.497800
 98657139         43      3    1.068796   129.022280         52.250190
 98663815         43      3    1.068796   129.002150         52.242138
 98660044         43      3    1.068796   126.500946         51.241657
 94312679         43      2    4.965916   117.897290         50.138466
 98664197         43      3    1.014972   119.144950         48.266964
157243941         45      2    5.215061   112.173900         47.998596
 98655819         43      3    1.051694   117.078250         47.462315
 95040784         43      3    0.956192   113.974060         46.163338
218053350         47      2    4.273470   105.411440         44.728657
 91914187         43      3    0.944125   108.804200         44.088154
 98657151         43      2    1.266355   107.847260         43.898716
 71765185         42      2    4.068713   103.532030         43.854040
 71460914         42      2    4.324539   102.377846         43.545860
 94296853         43      2    2.074451   104.709496         43.128470
128924055         45      2    5.034715    99.942720         42.997917
 94297167         43      3    0.929103   103.089134         41.793114
106872764         44      3    5.648073    95.970730         41.777138
 70777472         42      2    4.292365    97.835785         41.709732
164687325         45      2    4.410872    95.719860         40.934464
 98653617         43      2    1.403343    94.144830         38.499940

====================================================================================================
CLASS DISTRIBUTION AMONG TOP ANOMALIES
====================================================================================================

Top 50:
class
1     1
2    27
3    22
Name: count, dtype: int64

Top 100:
class
1     1
2    59
3    40
Name: count, dtype: int64

Top 500:
class
1      3
2    201
3    296
Name: count, dtype: int64

Top 1000:
class
1      5
2    383
3    612
Name: count, dtype: int64

Top 5000:
class
1      28
2    2146
3    2826
Name: count, dtype: int64

====================================================================================================
TEMPORAL ANOMALY ANALYSIS
====================================================================================================
           Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly  Class3_Count   Class3_%
Time step
43                 5063      2.724170        0.912523    65.282610          3693  72.940944
45                 5598      1.437229        0.398776    54.471413          4377  78.188639
46                 3519      1.405046        0.836679    35.390053          2807  79.766979
42                 7140      1.353905        0.708009    53.929455          4986  69.831933
47                 5121      1.339648        0.541131    61.643950          4275  83.479789
48                 2954      1.162728        0.350089    37.881035          2483  84.055518
49                 2454      0.973691        0.453717    73.344260          1978  80.603097
44                 4975      0.972023        0.327959    41.777138          3384  68.020101

====================================================================================================
UNSUPERVISED ANOMALY THRESHOLDS
====================================================================================================
 Percentile  Threshold  Flagged  Class3_Count  Class3_%
       95.0   5.525621     1842          1101 59.771987
       97.0   7.977634     1105           687 62.171946
       99.0  19.381844      369           205 55.555556
       99.5  24.285947      185            85 45.945946
       99.9  36.452063       37            20 54.054054

====================================================================================================
SAVING FINAL RESULTS
====================================================================================================
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_class_summary.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_topk_analysis.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_temporal_analysis.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_threshold_analysis.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_top100.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_final_evaluation.csv

====================================================================================================
BIT-TRACE — TRANSACTION-ONLY EVALUATION COMPLETE
====================================================================================================

Transactions evaluated : 36,824
Test time steps         : 42–49

Class-3 ROC-AUC         : 0.2948
Class-3 PR-AUC          : 0.6576

Isolation Forest        : ✓
LOF                     : ✓
Graph features          : ✓
Behavioral features     : ✓
Ensemble score          : ✓
Temporal evaluation     : ✓
Top-K analysis          : ✓
Threshold analysis      : ✓

P2P / network data      : NOT USED

====================================================================================================

In [48]:
# =============================================================================
# BIT-TRACE — TRANSACTION-ONLY EXPLAINABILITY + EVIDENCE ENGINE
# =============================================================================
# Purpose:
#   Convert transaction anomaly scores into investigator-readable evidence.
#
# Uses:
#   - Elliptic++ transaction features
#   - Transaction graph features
#   - Existing IF + LOF ensemble results
#
# Does NOT use:
#   - P2P/network observations
#   - Network crawl data
#   - Class labels for scoring/training
#
# Output:
#   1. Transaction evidence for top anomalous transactions
#   2. Feature-level explanations
#   3. Temporal context
#   4. Investigation priority
#   5. Dashboard-ready CSV
# =============================================================================

import os
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

print("=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY EXPLAINABILITY + EVIDENCE ENGINE")
print("=" * 100)


# =============================================================================
# 1. PATHS
# =============================================================================

BASE = r"C:\Users\YASHIKA\Desktop\bit-trace"

FEATURE_PATH = (
    r"C:\Users\YASHIKA\Desktop\bit-trace"
    r"\data\raw\elliptic-plus-plus\txs_features.csv"
)

CLASS_PATH = (
    r"C:\Users\YASHIKA\Desktop\bit-trace"
    r"\EllipticPlusPlus\Transactions Dataset\txs_classes.csv"
)

EDGE_PATH = (
    r"C:\Users\YASHIKA\Desktop\bit-trace"
    r"\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv"
)

RESULT_PATH = os.path.join(
    BASE,
    "src",
    "ellipticpp_graph_behavioral_anomaly_results.csv"
)

FINAL_EVAL_PATH = os.path.join(
    BASE,
    "bittrace_transaction_final_evaluation.csv"
)

OUTPUT_DIR = os.path.join(BASE, "bittrace_evidence")

os.makedirs(OUTPUT_DIR, exist_ok=True)


# =============================================================================
# 2. SELECTED BEHAVIORAL FEATURES
# =============================================================================

BEHAVIOR_FEATURES = [
    "Local_feature_22",
    "Local_feature_25",
    "Local_feature_47",
    "Local_feature_52",
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_59",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_14",
    "Aggregate_feature_21",
    "Aggregate_feature_32",
]

print("\n[1] SELECTED BEHAVIORAL FEATURES")
print("-" * 80)

for i, f in enumerate(BEHAVIOR_FEATURES, 1):
    print(f"{i:2d}. {f}")


# =============================================================================
# 3. CHECK FILES
# =============================================================================

print("\n[2] FILE CHECK")
print("-" * 80)

required_files = {
    "Feature": FEATURE_PATH,
    "Class": CLASS_PATH,
    "Edge": EDGE_PATH,
    "Anomaly Results": RESULT_PATH,
}

for name, path in required_files.items():
    exists = os.path.exists(path)
    print(f"{name:<18}: {exists}")
    if exists:
        print(f"Path               : {path}")

if not os.path.exists(RESULT_PATH):
    raise FileNotFoundError(
        f"Anomaly result file not found:\n{RESULT_PATH}"
    )


# =============================================================================
# 4. LOAD EXISTING ANOMALY RESULTS
# =============================================================================

print("\n[3] LOADING EXISTING ANOMALY RESULTS")
print("-" * 80)

results = pd.read_csv(RESULT_PATH)

print("Shape:", results.shape)
print("Columns:", list(results.columns))

required_result_columns = [
    "txId",
    "Time step",
    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly",
    "split",
]

missing = [
    c for c in required_result_columns
    if c not in results.columns
]

if missing:
    raise ValueError(
        f"Missing columns in anomaly result file: {missing}"
    )

results["txId"] = pd.to_numeric(
    results["txId"], errors="coerce"
)

results["Time step"] = pd.to_numeric(
    results["Time step"], errors="coerce"
)

results = results.dropna(
    subset=["txId", "Time step", "ensemble_anomaly"]
).copy()

print("Clean result shape:", results.shape)


# =============================================================================
# 5. USE TEST SET ONLY
# =============================================================================

print("\n[4] SELECTING TEST SET")
print("-" * 80)

test_results = results[
    results["split"].astype(str).str.lower() == "test"
].copy()

if len(test_results) == 0:

    print("No explicit 'test' split found.")

    test_results = results[
        results["Time step"] >= 42
    ].copy()

print("Test transactions:", len(test_results))

print(
    "Test time range:",
    int(test_results["Time step"].min()),
    "to",
    int(test_results["Time step"].max())
)


# =============================================================================
# 6. LOAD TRANSACTION FEATURES
# =============================================================================

print("\n[5] LOADING TRANSACTION FEATURES")
print("-" * 80)

header = pd.read_csv(
    FEATURE_PATH,
    nrows=0
)

feature_columns = list(header.columns)

print("Total feature columns:", len(feature_columns))

required_columns = [
    "txId",
    "Time step",
] + BEHAVIOR_FEATURES

missing_features = [
    c for c in required_columns
    if c not in feature_columns
]

if missing_features:
    raise ValueError(
        f"Missing feature columns: {missing_features}"
    )

transaction_data = pd.read_csv(
    FEATURE_PATH,
    usecols=required_columns
)

print("Loaded shape:", transaction_data.shape)

transaction_data["txId"] = pd.to_numeric(
    transaction_data["txId"],
    errors="coerce"
)

transaction_data["Time step"] = pd.to_numeric(
    transaction_data["Time step"],
    errors="coerce"
)

for f in BEHAVIOR_FEATURES:
    transaction_data[f] = pd.to_numeric(
        transaction_data[f],
        errors="coerce"
    )


# =============================================================================
# 7. MERGE TEST RESULTS + FEATURES
# =============================================================================

print("\n[6] MERGING ANOMALY RESULTS + FEATURES")
print("-" * 80)

evidence = test_results.merge(
    transaction_data,
    on=["txId", "Time step"],
    how="left"
)

print("Merged shape:", evidence.shape)

missing_feature_rows = evidence[
    BEHAVIOR_FEATURES
].isna().any(axis=1).sum()

print(
    "Rows with missing behavioral features:",
    missing_feature_rows
)

if missing_feature_rows > 0:

    print("Applying median imputation...")

    for f in BEHAVIOR_FEATURES:

        median_value = transaction_data[f].median()

        evidence[f] = evidence[f].fillna(
            median_value
        )


# =============================================================================
# 8. LOAD GRAPH EDGE LIST
# =============================================================================

print("\n[7] LOADING TRANSACTION GRAPH")
print("-" * 80)

edges = pd.read_csv(EDGE_PATH)

print("Edge shape:", edges.shape)

edge_columns = list(edges.columns)

print("Edge columns:", edge_columns)

source_candidates = [
    "txId1",
    "source",
    "src",
    "from",
]

target_candidates = [
    "txId2",
    "target",
    "dst",
    "to",
]

source_col = next(
    (c for c in source_candidates if c in edge_columns),
    None
)

target_col = next(
    (c for c in target_candidates if c in edge_columns),
    None
)

if source_col is None or target_col is None:

    if len(edge_columns) >= 2:
        source_col = edge_columns[0]
        target_col = edge_columns[1]

    else:
        raise ValueError(
            "Could not identify graph edge columns."
        )

print("Source:", source_col)
print("Target:", target_col)


# =============================================================================
# 9. BUILD DEGREE FEATURES
# =============================================================================

print("\n[8] BUILDING GRAPH EVIDENCE")
print("-" * 80)

edges[source_col] = pd.to_numeric(
    edges[source_col],
    errors="coerce"
)

edges[target_col] = pd.to_numeric(
    edges[target_col],
    errors="coerce"
)

edges = edges.dropna(
    subset=[source_col, target_col]
).copy()

edges = edges[
    edges[source_col] != edges[target_col]
]

in_degree = (
    edges.groupby(target_col)
    .size()
)

out_degree = (
    edges.groupby(source_col)
    .size()
)

graph_evidence = pd.DataFrame({
    "txId": pd.Index(
        set(in_degree.index)
        .union(set(out_degree.index))
    )
})

graph_evidence["in_degree"] = (
    graph_evidence["txId"]
    .map(in_degree)
    .fillna(0)
)

graph_evidence["out_degree"] = (
    graph_evidence["txId"]
    .map(out_degree)
    .fillna(0)
)

graph_evidence["total_degree"] = (
    graph_evidence["in_degree"]
    + graph_evidence["out_degree"]
)

graph_evidence["degree_imbalance"] = (
    graph_evidence["in_degree"]
    - graph_evidence["out_degree"]
).abs()

graph_evidence["in_out_ratio"] = (
    (graph_evidence["in_degree"] + 1)
    /
    (graph_evidence["out_degree"] + 1)
)

print(
    "Graph nodes:",
    len(graph_evidence)
)


# =============================================================================
# 10. MERGE GRAPH FEATURES
# =============================================================================

evidence = evidence.merge(
    graph_evidence,
    on="txId",
    how="left"
)

GRAPH_FEATURES = [
    "in_degree",
    "out_degree",
    "total_degree",
    "degree_imbalance",
    "in_out_ratio",
]

for f in GRAPH_FEATURES:

    evidence[f] = evidence[f].fillna(0)


# =============================================================================
# 11. CREATE NORMAL BASELINE
# =============================================================================

print("\n[9] BUILDING NORMAL BEHAVIOR BASELINE")
print("-" * 80)

# Use training transactions from the original result set.
train_ids = set(
    results[
        results["split"].astype(str).str.lower() == "train"
    ]["txId"]
)

train_features = transaction_data[
    transaction_data["txId"].isin(train_ids)
].copy()

print("Training baseline transactions:", len(train_features))

if len(train_features) == 0:

    # Fallback
    train_features = transaction_data.copy()

    print(
        "Fallback baseline: complete transaction dataset"
    )


# =============================================================================
# 12. BEHAVIORAL Z-SCORES
# =============================================================================

behavior_stats = {}

for f in BEHAVIOR_FEATURES:

    mean_value = train_features[f].mean()

    std_value = train_features[f].std()

    if pd.isna(std_value) or std_value == 0:
        std_value = 1.0

    behavior_stats[f] = {
        "mean": mean_value,
        "std": std_value,
    }

    evidence[f"{f}_z"] = (
        evidence[f] - mean_value
    ) / std_value


# =============================================================================
# 13. GRAPH Z-SCORES
# =============================================================================

graph_stats = {}

for f in GRAPH_FEATURES:

    mean_value = train_features[f].mean() \
        if f in train_features.columns else evidence[f].mean()

    std_value = train_features[f].std() \
        if f in train_features.columns else evidence[f].std()

    if pd.isna(std_value) or std_value == 0:
        std_value = 1.0

    graph_stats[f] = {
        "mean": mean_value,
        "std": std_value,
    }

    evidence[f"{f}_z"] = (
        evidence[f] - mean_value
    ) / std_value


# =============================================================================
# 14. FEATURE DEVIATION
# =============================================================================

print("\n[10] CALCULATING FEATURE DEVIATIONS")
print("-" * 80)

ALL_EXPLAIN_FEATURES = (
    BEHAVIOR_FEATURES +
    GRAPH_FEATURES
)

Z_COLUMNS = [
    f"{f}_z"
    for f in ALL_EXPLAIN_FEATURES
]

evidence["max_feature_deviation"] = (
    evidence[Z_COLUMNS]
    .abs()
    .max(axis=1)
)

evidence["mean_feature_deviation"] = (
    evidence[Z_COLUMNS]
    .abs()
    .mean(axis=1)
)


# =============================================================================
# 15. TOP CONTRIBUTING FEATURES
# =============================================================================

def get_top_features(row, n=5):

    values = {}

    for feature in ALL_EXPLAIN_FEATURES:

        z_col = f"{feature}_z"

        value = row.get(z_col, np.nan)

        if pd.notna(value):
            values[feature] = abs(float(value))

    ranked = sorted(
        values.items(),
        key=lambda x: x[1],
        reverse=True
    )[:n]

    return ranked


top_feature_names = []
top_feature_scores = []

for _, row in evidence.iterrows():

    ranked = get_top_features(row, n=5)

    names = [
        x[0]
        for x in ranked
    ]

    scores = [
        round(x[1], 3)
        for x in ranked
    ]

    top_feature_names.append(
        " | ".join(names)
    )

    top_feature_scores.append(
        " | ".join(
            str(x)
            for x in scores
        )
    )

evidence["top_features"] = top_feature_names

evidence["top_feature_deviations"] = top_feature_scores


# =============================================================================
# 16. NORMALIZE ENSEMBLE SCORE
# =============================================================================

print("\n[11] NORMALIZING ANOMALY SCORE")
print("-" * 80)

score = evidence["ensemble_anomaly"]

score_min = score.min()
score_max = score.max()

if score_max == score_min:

    evidence["anomaly_percentile"] = 50.0

else:

    evidence["anomaly_percentile"] = (
        score.rank(pct=True) * 100
    )


# =============================================================================
# 17. INVESTIGATION LEVEL
# =============================================================================

def investigation_level(percentile):

    if percentile >= 99.5:
        return "CRITICAL"

    if percentile >= 99:
        return "HIGH"

    if percentile >= 95:
        return "MEDIUM"

    return "LOW"


evidence["investigation_level"] = (
    evidence["anomaly_percentile"]
    .apply(investigation_level)
)


# =============================================================================
# 18. TEMPORAL CONTEXT
# =============================================================================

print("\n[12] BUILDING TEMPORAL CONTEXT")
print("-" * 80)

temporal_stats = (
    evidence.groupby("Time step")
    .agg(
        temporal_mean_score=(
            "ensemble_anomaly",
            "mean"
        ),
        temporal_median_score=(
            "ensemble_anomaly",
            "median"
        ),
        temporal_transaction_count=(
            "txId",
            "count"
        ),
    )
    .reset_index()
)

evidence = evidence.merge(
    temporal_stats,
    on="Time step",
    how="left"
)

evidence["score_vs_time_mean"] = (
    evidence["ensemble_anomaly"]
    -
    evidence["temporal_mean_score"]
)


# =============================================================================
# 19. GRAPH EVIDENCE TEXT
# =============================================================================

def graph_reason(row):

    reasons = []

    total_degree = row["total_degree"]
    imbalance = row["degree_imbalance"]

    if total_degree >= 20:
        reasons.append(
            f"high transaction connectivity "
            f"(total degree={total_degree:.0f})"
        )

    if imbalance >= 10:
        reasons.append(
            f"strong in/out degree imbalance "
            f"(imbalance={imbalance:.0f})"
        )

    if row["in_out_ratio"] >= 5:
        reasons.append(
            "inbound connectivity substantially "
            "exceeds outbound connectivity"
        )

    if row["in_out_ratio"] <= 0.2:
        reasons.append(
            "outbound connectivity substantially "
            "exceeds inbound connectivity"
        )

    if len(reasons) == 0:
        reasons.append(
            "no extreme graph-degree pattern detected"
        )

    return "; ".join(reasons)


evidence["graph_evidence"] = (
    evidence.apply(
        graph_reason,
        axis=1
    )
)


# =============================================================================
# 20. BEHAVIORAL EVIDENCE TEXT
# =============================================================================

def behavioral_reason(row):

    ranked = get_top_features(
        row,
        n=3
    )

    reasons = []

    for feature, deviation in ranked:

        z = row[f"{feature}_z"]

        direction = (
            "above"
            if z > 0
            else "below"
        )

        reasons.append(
            f"{feature} {direction} training baseline "
            f"(abs-z={abs(z):.2f})"
        )

    if len(reasons) == 0:
        return "No strong behavioral deviation."

    return "; ".join(reasons)


evidence["behavioral_evidence"] = (
    evidence.apply(
        behavioral_reason,
        axis=1
    )
)


# =============================================================================
# 21. TEMPORAL EVIDENCE
# =============================================================================

def temporal_reason(row):

    diff = row["score_vs_time_mean"]

    if diff > 5:
        return (
            f"anomaly score substantially above "
            f"time-step {int(row['Time step'])} average"
        )

    if diff > 1:
        return (
            f"anomaly score above "
            f"time-step {int(row['Time step'])} average"
        )

    return (
        f"time-step {int(row['Time step'])} "
        f"has {int(row['temporal_transaction_count'])} "
        f"transactions in evaluation set"
    )


evidence["temporal_evidence"] = (
    evidence.apply(
        temporal_reason,
        axis=1
    )
)


# =============================================================================
# 22. FINAL EVIDENCE SUMMARY
# =============================================================================

def build_evidence(row):

    return (
        f"Anomaly percentile: "
        f"{row['anomaly_percentile']:.2f}%. "
        f"Behavioral evidence: "
        f"{row['behavioral_evidence']}. "
        f"Graph evidence: "
        f"{row['graph_evidence']}. "
        f"Temporal context: "
        f"{row['temporal_evidence']}."
    )


evidence["evidence_summary"] = (
    evidence.apply(
        build_evidence,
        axis=1
    )
)


# =============================================================================
# 23. INVESTIGATION PRIORITY SCORE
# =============================================================================

# This is NOT a probability of illicit activity.
# It is only an internal ranking signal for investigation UI.

evidence["investigation_priority"] = (
    0.60 * evidence["anomaly_percentile"]
    +
    0.25 * np.clip(
        evidence["max_feature_deviation"] * 10,
        0,
        100
    )
    +
    0.15 * np.clip(
        evidence["total_degree"],
        0,
        100
    )
)


# =============================================================================
# 24. SORT
# =============================================================================

evidence = evidence.sort_values(
    "investigation_priority",
    ascending=False
).reset_index(drop=True)


# =============================================================================
# 25. TOP 100 INVESTIGATION CASES
# =============================================================================

top100 = evidence.head(100).copy()

print("\n[13] TOP 20 INVESTIGATION CANDIDATES")
print("-" * 100)

display_columns = [
    "txId",
    "Time step",
    "ensemble_anomaly",
    "anomaly_percentile",
    "investigation_level",
    "top_features",
    "max_feature_deviation",
    "total_degree",
    "investigation_priority",
]

print(
    top100[
        display_columns
    ].head(20).to_string(
        index=False
    )
)


# =============================================================================
# 26. SUMMARY
# =============================================================================

print("\n[14] INVESTIGATION SUMMARY")
print("-" * 100)

print(
    "CRITICAL:",
    (evidence["investigation_level"] == "CRITICAL").sum()
)

print(
    "HIGH:",
    (evidence["investigation_level"] == "HIGH").sum()
)

print(
    "MEDIUM:",
    (evidence["investigation_level"] == "MEDIUM").sum()
)

print(
    "LOW:",
    (evidence["investigation_level"] == "LOW").sum()
)


# =============================================================================
# 27. DASHBOARD-READY COLUMNS
# =============================================================================

dashboard_columns = [
    "txId",
    "Time step",
    "split",

    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly",

    "anomaly_percentile",
    "investigation_level",
    "investigation_priority",

    "top_features",
    "top_feature_deviations",

    "max_feature_deviation",
    "mean_feature_deviation",

    "in_degree",
    "out_degree",
    "total_degree",
    "degree_imbalance",
    "in_out_ratio",

    "temporal_mean_score",
    "temporal_median_score",
    "score_vs_time_mean",

    "behavioral_evidence",
    "graph_evidence",
    "temporal_evidence",
    "evidence_summary",
]

dashboard_columns = [
    c for c in dashboard_columns
    if c in evidence.columns
]

dashboard = evidence[
    dashboard_columns
].copy()


# =============================================================================
# 28. SAVE RESULTS
# =============================================================================

print("\n[15] SAVING EXPLAINABILITY RESULTS")
print("-" * 100)

full_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_explainability_full.csv"
)

top100_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_top100_evidence.csv"
)

dashboard_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_dashboard_data.csv"
)

summary_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_evidence_summary.csv"
)

dashboard.to_csv(
    full_path,
    index=False
)

top100.to_csv(
    top100_path,
    index=False
)

dashboard.head(1000).to_csv(
    dashboard_path,
    index=False
)

summary = pd.DataFrame({
    "metric": [
        "Total test transactions",
        "Critical cases",
        "High cases",
        "Medium cases",
        "Low cases",
        "Top evidence transactions",
    ],
    "value": [
        len(evidence),
        (evidence["investigation_level"] == "CRITICAL").sum(),
        (evidence["investigation_level"] == "HIGH").sum(),
        (evidence["investigation_level"] == "MEDIUM").sum(),
        (evidence["investigation_level"] == "LOW").sum(),
        min(100, len(evidence)),
    ],
})

summary.to_csv(
    summary_path,
    index=False
)


# =============================================================================
# 29. FINAL OUTPUT
# =============================================================================

print("\n" + "=" * 100)
print("BIT-TRACE — TRANSACTION EXPLAINABILITY COMPLETE")
print("=" * 100)

print(
    "\nTransactions analyzed:",
    len(evidence)
)

print(
    "Behavioral features:",
    len(BEHAVIOR_FEATURES)
)

print(
    "Graph evidence features:",
    len(GRAPH_FEATURES)
)

print(
    "\nSaved:"
)

print("✓", full_path)
print("✓", top100_path)
print("✓", dashboard_path)
print("✓", summary_path)

print("\n" + "=" * 100)
print("NEXT STEP")
print("=" * 100)

print(
    """
Use bittrace_transaction_top100_evidence.csv
for the investigator dashboard.

Each transaction now contains:

  Transaction ID
        ↓
  Ensemble anomaly score
        ↓
  Anomaly percentile
        ↓
  Investigation level
        ↓
  Top deviating behavioral features
        ↓
  Graph evidence
        ↓
  Temporal context
        ↓
  Human-readable evidence summary

No P2P/network data was used.
Class labels are NOT used to generate anomaly scores.
"""
)

print("=" * 100)

====================================================================================================
BIT-TRACE — TRANSACTION-ONLY EXPLAINABILITY + EVIDENCE ENGINE
====================================================================================================

[1] SELECTED BEHAVIORAL FEATURES
--------------------------------------------------------------------------------
 1. Local_feature_22
 2. Local_feature_25
 3. Local_feature_47
 4. Local_feature_52
 5. Local_feature_53
 6. Local_feature_54
 7. Local_feature_59
 8. Local_feature_77
 9. Local_feature_89
10. Local_feature_90
11. Aggregate_feature_14
12. Aggregate_feature_21
13. Aggregate_feature_32

[2] FILE CHECK
--------------------------------------------------------------------------------
Feature           : True
Path               : C:\Users\YASHIKA\Desktop\bit-trace\data\raw\elliptic-plus-plus\txs_features.csv
Class             : True
Path               : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv
Edge              : True
Path               : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_edgelist.csv
Anomaly Results   : True
Path               : C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_behavioral_anomaly_results.csv

[3] LOADING EXISTING ANOMALY RESULTS
--------------------------------------------------------------------------------
Shape: (203769, 6)
Columns: ['txId', 'Time step', 'IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly', 'split']
Clean result shape: (203769, 6)

[4] SELECTING TEST SET
--------------------------------------------------------------------------------
Test transactions: 36824
Test time range: 42 to 49

[5] LOADING TRANSACTION FEATURES
--------------------------------------------------------------------------------
Total feature columns: 184
Loaded shape: (203769, 15)

[6] MERGING ANOMALY RESULTS + FEATURES
--------------------------------------------------------------------------------
Merged shape: (36824, 19)
Rows with missing behavioral features: 0

[7] LOADING TRANSACTION GRAPH
--------------------------------------------------------------------------------
Edge shape: (234355, 2)
Edge columns: ['txId1', 'txId2']
Source: txId1
Target: txId2

[8] BUILDING GRAPH EVIDENCE
--------------------------------------------------------------------------------
Graph nodes: 203769

[9] BUILDING NORMAL BEHAVIOR BASELINE
--------------------------------------------------------------------------------
Training baseline transactions: 136265

[10] CALCULATING FEATURE DEVIATIONS
--------------------------------------------------------------------------------

[11] NORMALIZING ANOMALY SCORE
--------------------------------------------------------------------------------

[12] BUILDING TEMPORAL CONTEXT
--------------------------------------------------------------------------------

[13] TOP 20 INVESTIGATION CANDIDATES
----------------------------------------------------------------------------------------------------
     txId  Time step  ensemble_anomaly  anomaly_percentile investigation_level                                                                           top_features  max_feature_deviation  total_degree  investigation_priority
     7952         48         15.203577           98.726374              MEDIUM     out_degree | degree_imbalance | total_degree | Local_feature_52 | Local_feature_53              59.057443         100.0               99.235824
196107869         46          9.909365           97.536932              MEDIUM      in_out_ratio | in_degree | degree_imbalance | total_degree | Aggregate_feature_14              60.330702         188.0               98.522159
157929208         49          8.269158           97.067130              MEDIUM      in_out_ratio | in_degree | degree_imbalance | total_degree | Aggregate_feature_14              48.761620         152.0               98.240278
 38688623         47          7.184318           96.730393              MEDIUM        total_degree | in_degree | degree_imbalance | Aggregate_feature_14 | out_degree              22.922250         113.0               98.038236
   143705         45         14.303149           98.598740              MEDIUM out_degree | degree_imbalance | total_degree | Aggregate_feature_14 | Local_feature_89              54.832817          92.0               97.959244
 19170155         47          6.953516           96.344775              MEDIUM        total_degree | in_degree | degree_imbalance | Aggregate_feature_14 | out_degree              21.887018         108.0               97.806865
 91934616         43          6.947904           96.339344              MEDIUM        total_degree | in_degree | degree_imbalance | Aggregate_feature_14 | out_degree              22.094064         109.0               97.803606
  2268197         48          6.902386           96.306756              MEDIUM      in_out_ratio | in_degree | degree_imbalance | total_degree | Aggregate_feature_14              38.799356         121.0               97.784054
106320422         44          6.805641           96.195416              MEDIUM      in_degree | degree_imbalance | total_degree | in_out_ratio | Aggregate_feature_14              26.182848         120.0               97.717250
 36364435         47          6.786779           96.181838              MEDIUM        total_degree | in_degree | degree_imbalance | Aggregate_feature_14 | out_degree              21.887018         108.0               97.709103
111575373         45          6.590064           96.086791              MEDIUM        in_degree | total_degree | degree_imbalance | Aggregate_feature_14 | out_degree              21.517468         106.0               97.652075
    45766         48          6.549230           96.056919              MEDIUM  in_degree | total_degree | degree_imbalance | Aggregate_feature_14 | Local_feature_53              21.517468         105.0               97.634152
 14950377         46          6.492446           96.005323              MEDIUM      in_degree | total_degree | Aggregate_feature_14 | degree_imbalance | in_out_ratio              21.295307         103.0               97.603194
 12172125         45          6.480698           95.997176              MEDIUM        total_degree | in_degree | degree_imbalance | Aggregate_feature_14 | out_degree              20.851785         103.0               97.598305
  2947436         46          6.311121           95.861395              MEDIUM      Aggregate_feature_14 | in_degree | total_degree | degree_imbalance | in_out_ratio              22.578920         100.0               97.516837
 73330801         42          6.215182           95.769064              MEDIUM      in_degree | degree_imbalance | total_degree | in_out_ratio | Aggregate_feature_14              22.850434         105.0               97.461438
 26181447         47          6.160671           95.709320              MEDIUM      in_degree | total_degree | degree_imbalance | Aggregate_feature_14 | in_out_ratio              21.295307         100.0               97.425592
 91882349         43          6.097903           95.657723              MEDIUM      in_degree | degree_imbalance | total_degree | in_out_ratio | Aggregate_feature_14              21.961790         101.0               97.394634
 19670253         45          6.317656           95.864110              MEDIUM        total_degree | in_degree | degree_imbalance | Aggregate_feature_14 | out_degree              20.023599          99.0               97.368466
155821494         45          5.883090           95.448620              MEDIUM      in_degree | degree_imbalance | total_degree | in_out_ratio | Aggregate_feature_21              24.627722         113.0               97.269172

[14] INVESTIGATION SUMMARY
----------------------------------------------------------------------------------------------------
CRITICAL: 185
HIGH: 184
MEDIUM: 1473
LOW: 34982

[15] SAVING EXPLAINABILITY RESULTS
----------------------------------------------------------------------------------------------------

====================================================================================================
BIT-TRACE — TRANSACTION EXPLAINABILITY COMPLETE
====================================================================================================

Transactions analyzed: 36824
Behavioral features: 13
Graph evidence features: 5

Saved:
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_evidence\bittrace_transaction_explainability_full.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_evidence\bittrace_transaction_top100_evidence.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_evidence\bittrace_transaction_dashboard_data.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_evidence\bittrace_transaction_evidence_summary.csv

====================================================================================================
NEXT STEP
====================================================================================================

Use bittrace_transaction_top100_evidence.csv
for the investigator dashboard.

Each transaction now contains:

  Transaction ID
        ↓
  Ensemble anomaly score
        ↓
  Anomaly percentile
        ↓
  Investigation level
        ↓
  Top deviating behavioral features
        ↓
  Graph evidence
        ↓
  Temporal context
        ↓
  Human-readable evidence summary

No P2P/network data was used.
Class labels are NOT used to generate anomaly scores.

====================================================================================================

In [49]:
# =============================================================================
# BIT-TRACE — LARGE-SCALE TRANSACTION-ONLY INVESTIGATION TEST
# =============================================================================
# Uses:
#   - Existing transaction anomaly results
#   - Elliptic++ transaction labels
#
# Does NOT use:
#   - P2P/network observations
#   - P2P IP/port data
#   - Any new ML training
#
# Purpose:
#   Test how BIT-TRACE prioritizes a large number of unseen transactions.
# =============================================================================

import os
import numpy as np
import pandas as pd

print("=" * 100)
print("BIT-TRACE — LARGE-SCALE TRANSACTION-ONLY INVESTIGATION TEST")
print("=" * 100)

# -----------------------------------------------------------------------------
# 1. PATHS
# -----------------------------------------------------------------------------

RESULT_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_behavioral_anomaly_results.csv"

CLASS_PATH = r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv"

OUTPUT_DIR = r"C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test"

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("\n[1] FILE CHECK")
print("-" * 80)

print("Anomaly results :", os.path.exists(RESULT_PATH))
print("Class labels    :", os.path.exists(CLASS_PATH))
print("Output folder   :", OUTPUT_DIR)

if not os.path.exists(RESULT_PATH):
    raise FileNotFoundError(
        f"Anomaly result file not found:\n{RESULT_PATH}"
    )

if not os.path.exists(CLASS_PATH):
    raise FileNotFoundError(
        f"Class file not found:\n{CLASS_PATH}"
    )

# -----------------------------------------------------------------------------
# 2. LOAD ANOMALY RESULTS
# -----------------------------------------------------------------------------

print("\n[2] LOADING TRANSACTION ANOMALY RESULTS")
print("-" * 80)

results = pd.read_csv(RESULT_PATH)

required_result_cols = [
    "txId",
    "Time step",
    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly",
    "split"
]

missing = [
    c for c in required_result_cols
    if c not in results.columns
]

if missing:
    raise ValueError(
        f"Missing columns in anomaly result file: {missing}"
    )

print("Shape:", results.shape)
print("Columns:", results.columns.tolist())

# Remove accidental duplicate txIds if any
before = len(results)

results = (
    results
    .drop_duplicates(subset=["txId"])
    .copy()
)

print("Duplicate txIds removed:", before - len(results))

# -----------------------------------------------------------------------------
# 3. LOAD CLASS LABELS
# -----------------------------------------------------------------------------

print("\n[3] LOADING TRANSACTION LABELS")
print("-" * 80)

classes = pd.read_csv(CLASS_PATH)

# Normalize column names
classes.columns = [
    str(c).strip()
    for c in classes.columns
]

# Handle possible variations
tx_col = None
class_col = None

for c in classes.columns:
    if c.lower() == "txid":
        tx_col = c
    if c.lower() == "class":
        class_col = c

if tx_col is None or class_col is None:
    raise ValueError(
        f"Could not detect txId/class columns. Found: {classes.columns.tolist()}"
    )

classes = classes.rename(
    columns={
        tx_col: "txId",
        class_col: "class"
    }
)

classes = classes[["txId", "class"]].copy()

print("Class shape:", classes.shape)

print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())

# -----------------------------------------------------------------------------
# 4. MERGE
# -----------------------------------------------------------------------------

print("\n[4] MERGING TRANSACTION RESULTS + LABELS")
print("-" * 80)

df = results.merge(
    classes,
    on="txId",
    how="left",
    validate="one_to_one"
)

missing_labels = df["class"].isna().sum()

print("Merged shape:", df.shape)
print("Missing labels:", missing_labels)

if missing_labels > 0:
    raise ValueError(
        f"{missing_labels} transactions have missing class labels."
    )

# -----------------------------------------------------------------------------
# 5. BASIC DATA VALIDATION
# -----------------------------------------------------------------------------

print("\n[5] DATA VALIDATION")
print("-" * 80)

print("Total transactions:", len(df))
print("Time range:",
      int(df["Time step"].min()),
      "to",
      int(df["Time step"].max()))

print("\nSplit distribution:")
print(df["split"].value_counts())

if df["ensemble_anomaly"].isna().any():
    raise ValueError("Missing ensemble anomaly scores found.")

print("\nAnomaly score statistics:")
print(
    df["ensemble_anomaly"]
    .describe()
    .to_string()
)

# -----------------------------------------------------------------------------
# 6. SELECT FINAL UNSEEN TEST SET
# -----------------------------------------------------------------------------

print("\n[6] SELECTING UNSEEN TEST SET")
print("-" * 80)

test_df = df[
    df["split"].astype(str).str.lower().eq("test")
].copy()

if len(test_df) == 0:
    raise ValueError(
        "No rows with split='test' found."
    )

test_df = test_df.sort_values(
    "ensemble_anomaly",
    ascending=False
).reset_index(drop=True)

print("Test transactions:", len(test_df))
print(
    "Test time:",
    int(test_df["Time step"].min()),
    "to",
    int(test_df["Time step"].max())
)

# -----------------------------------------------------------------------------
# 7. ANOMALY PERCENTILE
# -----------------------------------------------------------------------------

print("\n[7] CALCULATING ANOMALY PERCENTILES")
print("-" * 80)

# Highest score = highest anomaly percentile
test_df["anomaly_percentile"] = (
    test_df["ensemble_anomaly"]
    .rank(
        method="average",
        pct=True
    ) * 100
)

# -----------------------------------------------------------------------------
# 8. INVESTIGATION LEVEL
# -----------------------------------------------------------------------------

def investigation_level(percentile):
    if percentile >= 99.0:
        return "CRITICAL"
    elif percentile >= 95.0:
        return "HIGH"
    elif percentile >= 80.0:
        return "MEDIUM"
    else:
        return "LOW"

test_df["investigation_level"] = (
    test_df["anomaly_percentile"]
    .apply(investigation_level)
)

# -----------------------------------------------------------------------------
# 9. INVESTIGATION PRIORITY
# -----------------------------------------------------------------------------

# Priority is deliberately based only on anomaly percentile.
# No class labels are used for ranking.

test_df["investigation_priority"] = (
    test_df["anomaly_percentile"]
)

# -----------------------------------------------------------------------------
# 10. TOP-K ANALYSIS
# -----------------------------------------------------------------------------

print("\n[8] LARGE-SCALE TOP-K ANALYSIS")
print("-" * 80)

TOP_K_VALUES = [
    100,
    500,
    1000,
    5000,
    10000,
    20000
]

overall_class3_pct = (
    (test_df["class"] == 3).mean() * 100
)

topk_rows = []

for k in TOP_K_VALUES:

    k_actual = min(k, len(test_df))

    topk = test_df.head(k_actual)

    class3_count = (
        topk["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / k_actual * 100
    )

    enrichment = (
        class3_pct / overall_class3_pct
        if overall_class3_pct > 0
        else np.nan
    )

    topk_rows.append({
        "Top_K": k_actual,
        "Transactions": k_actual,
        "Class1_Count": int((topk["class"] == 1).sum()),
        "Class2_Count": int((topk["class"] == 2).sum()),
        "Class3_Count": int(class3_count),
        "Class1_%": (topk["class"] == 1).mean() * 100,
        "Class2_%": (topk["class"] == 2).mean() * 100,
        "Class3_%": class3_pct,
        "Overall_Test_Class3_%": overall_class3_pct,
        "Class3_Enrichment": enrichment,
        "Mean_Anomaly": topk["ensemble_anomaly"].mean(),
        "Median_Anomaly": topk["ensemble_anomaly"].median(),
        "Max_Anomaly": topk["ensemble_anomaly"].max()
    })

topk_df = pd.DataFrame(topk_rows)

print(
    topk_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# -----------------------------------------------------------------------------
# 11. INVESTIGATION LEVEL DISTRIBUTION
# -----------------------------------------------------------------------------

print("\n[9] INVESTIGATION LEVEL DISTRIBUTION")
print("-" * 80)

level_counts = (
    test_df["investigation_level"]
    .value_counts()
    .reindex(
        ["CRITICAL", "HIGH", "MEDIUM", "LOW"],
        fill_value=0
    )
)

level_pct = (
    level_counts / len(test_df) * 100
)

level_df = pd.DataFrame({
    "Count": level_counts,
    "Percentage": level_pct
})

print(level_df.to_string())

# -----------------------------------------------------------------------------
# 12. TEMPORAL DISTRIBUTION OF HIGH-PRIORITY TRANSACTIONS
# -----------------------------------------------------------------------------

print("\n[10] TEMPORAL INVESTIGATION ANALYSIS")
print("-" * 80)

high_priority = test_df[
    test_df["anomaly_percentile"] >= 95
].copy()

temporal = (
    high_priority
    .groupby("Time step")
    .agg(
        High_Priority_Transactions=("txId", "count"),
        Mean_Anomaly=("ensemble_anomaly", "mean"),
        Median_Anomaly=("ensemble_anomaly", "median"),
        Max_Anomaly=("ensemble_anomaly", "max"),
        Class1_Count=("class", lambda x: (x == 1).sum()),
        Class2_Count=("class", lambda x: (x == 2).sum()),
        Class3_Count=("class", lambda x: (x == 3).sum())
    )
    .reset_index()
)

temporal["Class3_%"] = (
    temporal["Class3_Count"]
    / temporal["High_Priority_Transactions"]
    * 100
)

temporal = temporal.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print(
    temporal.head(20).to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# -----------------------------------------------------------------------------
# 13. SCORE DISTRIBUTION BY INVESTIGATION LEVEL
# -----------------------------------------------------------------------------

print("\n[11] SCORE DISTRIBUTION BY INVESTIGATION LEVEL")
print("-" * 80)

level_scores = (
    test_df
    .groupby("investigation_level")["ensemble_anomaly"]
    .agg(
        Transactions="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
    .reindex(
        ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
    )
)

print(
    level_scores.to_string(
        float_format=lambda x: f"{x:.6f}"
    )
)

# -----------------------------------------------------------------------------
# 14. TOP 100 TRANSACTIONS
# -----------------------------------------------------------------------------

print("\n[12] TOP 100 TRANSACTIONS")
print("-" * 80)

top100 = test_df.head(100).copy()

display_columns = [
    "txId",
    "Time step",
    "ensemble_anomaly",
    "anomaly_percentile",
    "investigation_level",
    "investigation_priority",
    "class"
]

print(
    top100[display_columns]
    .head(30)
    .to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)

# -----------------------------------------------------------------------------
# 15. SAVE TOP-K REPORTS
# -----------------------------------------------------------------------------

print("\n[13] SAVING LARGE-SCALE REPORTS")
print("-" * 80)

# Full test ranking
full_test_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_test_full_ranking.csv"
)

test_df.to_csv(
    full_test_path,
    index=False
)

print("✓ Full test ranking:")
print(full_test_path)

# Top-K individual files
for k in TOP_K_VALUES:

    k_actual = min(k, len(test_df))

    path = os.path.join(
        OUTPUT_DIR,
        f"bittrace_transaction_top_{k_actual}.csv"
    )

    test_df.head(k_actual).to_csv(
        path,
        index=False
    )

    print(f"✓ Top {k_actual}: {path}")

# Summary
topk_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_large_scale_topk_summary.csv"
)

topk_df.to_csv(
    topk_path,
    index=False
)

print("✓ Top-K summary:")
print(topk_path)

# Investigation levels
level_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_investigation_levels.csv"
)

level_df.to_csv(
    level_path
)

print("✓ Investigation levels:")
print(level_path)

# Temporal analysis
temporal_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_high_priority_temporal.csv"
)

temporal.to_csv(
    temporal_path,
    index=False
)

print("✓ Temporal analysis:")
print(temporal_path)

# -----------------------------------------------------------------------------
# 16. FINAL SUMMARY
# -----------------------------------------------------------------------------

print("\n" + "=" * 100)
print("BIT-TRACE — LARGE-SCALE TRANSACTION TEST COMPLETE")
print("=" * 100)

print(f"""
Total transactions in dataset : {len(df):,}
Unseen test transactions      : {len(test_df):,}
Test time range               : {int(test_df['Time step'].min())}–{int(test_df['Time step'].max())}

Models already used:
  ✓ Isolation Forest
  ✓ LOF
  ✓ Ensemble anomaly score

Transaction evidence:
  ✓ Behavioral anomaly score
  ✓ Transaction graph features
  ✓ Temporal context
  ✓ Anomaly percentile
  ✓ Investigation priority

Large-scale rankings generated:
  ✓ Top 100
  ✓ Top 500
  ✓ Top 1,000
  ✓ Top 5,000
  ✓ Top 10,000
  ✓ Top 20,000

P2P / network data:
  ✗ NOT USED

Labels:
  ✗ NOT used to generate anomaly scores
  ✓ Used only for post-hoc evaluation
""")

print("=" * 100)
print("NEXT STEP:")
print("Use the Top-K CSVs to demonstrate transaction-scale investigation.")
print("After this is validated, P2P correlation can be added as a separate layer.")
print("=" * 100)

====================================================================================================
BIT-TRACE — LARGE-SCALE TRANSACTION-ONLY INVESTIGATION TEST
====================================================================================================

[1] FILE CHECK
--------------------------------------------------------------------------------
Anomaly results : True
Class labels    : True
Output folder   : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test

[2] LOADING TRANSACTION ANOMALY RESULTS
--------------------------------------------------------------------------------
Shape: (203769, 6)
Columns: ['txId', 'Time step', 'IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly', 'split']
Duplicate txIds removed: 0

[3] LOADING TRANSACTION LABELS
--------------------------------------------------------------------------------
Class shape: (203769, 2)

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[4] MERGING TRANSACTION RESULTS + LABELS
--------------------------------------------------------------------------------
Merged shape: (203769, 7)
Missing labels: 0

[5] DATA VALIDATION
--------------------------------------------------------------------------------
Total transactions: 203769
Time range: 1 to 49

Split distribution:
split
train         136265
test           36824
validation     30680
Name: count, dtype: int64

Anomaly score statistics:
count    203769.000000
mean          0.985615
std           3.980816
min          -0.449453
25%          -0.113149
50%           0.308550
75%           1.293419
max         557.884460

[6] SELECTING UNSEEN TEST SET
--------------------------------------------------------------------------------
Test transactions: 36824
Test time: 42 to 49

[7] CALCULATING ANOMALY PERCENTILES
--------------------------------------------------------------------------------

[8] LARGE-SCALE TOP-K ANALYSIS
--------------------------------------------------------------------------------
 Top_K  Transactions  Class1_Count  Class2_Count  Class3_Count  Class1_%  Class2_%  Class3_%  Overall_Test_Class3_%  Class3_Enrichment  Mean_Anomaly  Median_Anomaly  Max_Anomaly
   100           100             1            59            40    1.0000   59.0000   40.0000                75.9912             0.5264       39.0534         35.4714      73.3443
   500           500             3           201           296    0.6000   40.2000   59.2000                75.9912             0.7790       24.6387         21.3847      73.3443
  1000          1000             5           383           612    0.5000   38.3000   61.2000                75.9912             0.8054       18.1718         14.6051      73.3443
  5000          5000            28          2146          2826    0.5600   42.9200   56.5200                75.9912             0.7438        7.0394          4.3517      73.3443
 10000         10000            69          4293          5638    0.6900   42.9300   56.3800                75.9912             0.7419        4.4932          2.5098      73.3443
 20000         20000           210          6729         13061    1.0500   33.6450   65.3050                75.9912             0.8594        2.6986          1.5067      73.3443

[9] INVESTIGATION LEVEL DISTRIBUTION
--------------------------------------------------------------------------------
                     Count  Percentage
investigation_level
CRITICAL               369    1.002064
HIGH                  1473    4.000109
MEDIUM                5523   14.998371
LOW                  29459   79.999457

[10] TEMPORAL INVESTIGATION ANALYSIS
--------------------------------------------------------------------------------
 Time step  High_Priority_Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly  Class1_Count  Class2_Count  Class3_Count  Class3_%
        43                         592       15.2523         11.8954      65.2826             4           331           257   43.4122
        47                         195       13.6705          9.7974      61.6439             0            68           127   65.1282
        45                         340       12.6451          7.7708      54.4714             0           113           227   66.7647
        49                          42       11.5394          8.3124      73.3443             0            10            32   76.1905
        48                         113       11.2661          8.5887      37.8810             0            15            98   86.7257
        46                         131       11.1750          8.9275      35.3901             0            48            83   63.3588
        44                         160       11.0431         10.4163      41.7771             3            37           120   75.0000
        42                         269       10.7343          8.2276      53.9295             2           110           157   58.3643

[11] SCORE DISTRIBUTION BY INVESTIGATION LEVEL
--------------------------------------------------------------------------------
                     Transactions      Mean      Std       Min    Median       Max
investigation_level
CRITICAL                      369 27.415670 8.844565 19.391352 24.286024 73.344260
HIGH                         1473  9.337506 3.485680  5.525818  7.969795 19.350012
MEDIUM                       5523  2.994013 0.937143  1.967690  2.674037  5.524502
LOW                         29459  0.460408 0.627403 -0.442719  0.316581  1.967520

[12] TOP 100 TRANSACTIONS
--------------------------------------------------------------------------------
     txId  Time step  ensemble_anomaly  anomaly_percentile investigation_level  investigation_priority  class
158275512         49         73.344260          100.000000            CRITICAL              100.000000      3
 98649329         43         65.282610           99.997284            CRITICAL               99.997284      3
218135759         47         61.643950           99.994569            CRITICAL               99.994569      2
 94260854         43         56.760540           99.991853            CRITICAL               99.991853      2
 95040255         43         55.446556           99.989138            CRITICAL               99.989138      3
 98649322         43         55.432587           99.986422            CRITICAL               99.986422      3
181949645         45         54.471413           99.983706            CRITICAL               99.983706      2
 73424761         42         53.929455           99.980991            CRITICAL               99.980991      2
 71465831         42         53.545998           99.978275            CRITICAL               99.978275      2
 95040590         43         53.497800           99.975559            CRITICAL               99.975559      3
 98657139         43         52.250190           99.972844            CRITICAL               99.972844      3
 98663815         43         52.242138           99.970128            CRITICAL               99.970128      3
 98660044         43         51.241657           99.967413            CRITICAL               99.967413      3
 94312679         43         50.138466           99.964697            CRITICAL               99.964697      2
 98664197         43         48.266964           99.961981            CRITICAL               99.961981      3
157243941         45         47.998596           99.959266            CRITICAL               99.959266      2
 98655819         43         47.462315           99.956550            CRITICAL               99.956550      3
 95040784         43         46.163338           99.953834            CRITICAL               99.953834      3
218053350         47         44.728657           99.951119            CRITICAL               99.951119      2
 91914187         43         44.088154           99.948403            CRITICAL               99.948403      3
 98657151         43         43.898716           99.945688            CRITICAL               99.945688      2
 71765185         42         43.854040           99.942972            CRITICAL               99.942972      2
 71460914         42         43.545860           99.940256            CRITICAL               99.940256      2
 94296853         43         43.128470           99.937541            CRITICAL               99.937541      2
128924055         45         42.997917           99.934825            CRITICAL               99.934825      2
 94297167         43         41.793114           99.932109            CRITICAL               99.932109      3
106872764         44         41.777138           99.929394            CRITICAL               99.929394      3
 70777472         42         41.709732           99.926678            CRITICAL               99.926678      2
164687325         45         40.934464           99.923963            CRITICAL               99.923963      2
 98653617         43         38.499940           99.921247            CRITICAL               99.921247      2

[13] SAVING LARGE-SCALE REPORTS
--------------------------------------------------------------------------------
✓ Full test ranking:
C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_test_full_ranking.csv
✓ Top 100: C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_top_100.csv
✓ Top 500: C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_top_500.csv
✓ Top 1000: C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_top_1000.csv
✓ Top 5000: C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_top_5000.csv
✓ Top 10000: C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_top_10000.csv
✓ Top 20000: C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_top_20000.csv
✓ Top-K summary:
C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_large_scale_topk_summary.csv
✓ Investigation levels:
C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_investigation_levels.csv
✓ Temporal analysis:
C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\bittrace_transaction_high_priority_temporal.csv

====================================================================================================
BIT-TRACE — LARGE-SCALE TRANSACTION TEST COMPLETE
====================================================================================================

Total transactions in dataset : 203,769
Unseen test transactions      : 36,824
Test time range               : 42–49

Models already used:
  ✓ Isolation Forest
  ✓ LOF
  ✓ Ensemble anomaly score

Transaction evidence:
  ✓ Behavioral anomaly score
  ✓ Transaction graph features
  ✓ Temporal context
  ✓ Anomaly percentile
  ✓ Investigation priority

Large-scale rankings generated:
  ✓ Top 100
  ✓ Top 500
  ✓ Top 1,000
  ✓ Top 5,000
  ✓ Top 10,000
  ✓ Top 20,000

P2P / network data:
  ✗ NOT USED

Labels:
  ✗ NOT used to generate anomaly scores
  ✓ Used only for post-hoc evaluation

====================================================================================================
NEXT STEP:
Use the Top-K CSVs to demonstrate transaction-scale investigation.
After this is validated, P2P correlation can be added as a separate layer.
====================================================================================================

In [50]:
# =============================================================================
# BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE FINAL TEST
# Elliptic++ | Isolation Forest + LOF | NO P2P DATA
# =============================================================================

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, average_precision_score

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------

FEATURE_PATH = (
    r"C:\Users\YASHIKA\Desktop\bit-trace\data\raw"
    r"\elliptic-plus-plus\txs_features.csv"
)

CLASS_PATH = (
    r"C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus"
    r"\Transactions Dataset\txs_classes.csv"
)

OUTPUT_DIR = (
    r"C:\Users\YASHIKA\Desktop\bit-trace"
    r"transaction_final_test"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

BEHAVIORAL_FEATURES = [
    "Local_feature_22",
    "Local_feature_25",
    "Local_feature_47",
    "Local_feature_52",
    "Local_feature_53",
    "Local_feature_54",
    "Local_feature_59",
    "Local_feature_77",
    "Local_feature_89",
    "Local_feature_90",
    "Aggregate_feature_14",
    "Aggregate_feature_21",
    "Aggregate_feature_32"
]

RANDOM_STATE = 42

# Temporal split
TRAIN_START = 1
TRAIN_END   = 34

VAL_START = 35
VAL_END   = 41

TEST_START = 42
TEST_END   = 49

print("=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE FINAL TEST")
print("=" * 100)

# =============================================================================
# 1. FILE CHECK
# =============================================================================

print("\n[1] FILE CHECK")
print("-" * 100)

if not os.path.exists(FEATURE_PATH):
    raise FileNotFoundError(f"Feature file not found:\n{FEATURE_PATH}")

if not os.path.exists(CLASS_PATH):
    raise FileNotFoundError(f"Class file not found:\n{CLASS_PATH}")

print("FEATURE :", FEATURE_PATH)
print("CLASS   :", CLASS_PATH)

# =============================================================================
# 2. LOAD CLASS LABELS
# =============================================================================

print("\n[2] LOADING CLASS LABELS")
print("-" * 100)

classes = pd.read_csv(CLASS_PATH)

classes.columns = [str(c).strip() for c in classes.columns]

if "txId" not in classes.columns:
    raise ValueError(f"txId not found in class file: {classes.columns.tolist()}")

if "class" not in classes.columns:
    raise ValueError(f"class not found in class file: {classes.columns.tolist()}")

classes["txId"] = pd.to_numeric(classes["txId"], errors="coerce")
classes["class"] = pd.to_numeric(classes["class"], errors="coerce")

classes = classes.dropna(subset=["txId", "class"]).copy()

classes["txId"] = classes["txId"].astype(np.int64)
classes["class"] = classes["class"].astype(int)

print("Shape:", classes.shape)
print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())

# =============================================================================
# 3. READ FEATURE HEADER
# =============================================================================

print("\n[3] READING FEATURE HEADER")
print("-" * 100)

header = pd.read_csv(FEATURE_PATH, nrows=0)

header.columns = [str(c).strip() for c in header.columns]

print("Total columns:", len(header.columns))

required = ["txId", "Time step"] + BEHAVIORAL_FEATURES

missing = [c for c in required if c not in header.columns]

if missing:
    raise ValueError(
        "Missing required columns:\n" + "\n".join(missing)
    )

print("✓ All required transaction features found")

# =============================================================================
# 4. LOAD ONLY REQUIRED TRANSACTION FEATURES
# =============================================================================

print("\n[4] LOADING TRANSACTION FEATURES")
print("-" * 100)

data = pd.read_csv(
    FEATURE_PATH,
    usecols=required,
    low_memory=False
)

data.columns = [str(c).strip() for c in data.columns]

print("Loaded shape:", data.shape)

# =============================================================================
# 5. DATA CLEANING
# =============================================================================

print("\n[5] CLEANING TRANSACTION DATA")
print("-" * 100)

data["txId"] = pd.to_numeric(data["txId"], errors="coerce")
data["Time step"] = pd.to_numeric(data["Time step"], errors="coerce")

for col in BEHAVIORAL_FEATURES:
    data[col] = pd.to_numeric(data[col], errors="coerce")

data = data.dropna(subset=["txId", "Time step"]).copy()

data["txId"] = data["txId"].astype(np.int64)
data["Time step"] = data["Time step"].astype(int)

# Replace infinities
data[BEHAVIORAL_FEATURES] = (
    data[BEHAVIORAL_FEATURES]
    .replace([np.inf, -np.inf], np.nan)
)

# Median imputation
for col in BEHAVIORAL_FEATURES:
    median_value = data[col].median()

    if pd.isna(median_value):
        median_value = 0.0

    data[col] = data[col].fillna(median_value)

print("Rows:", len(data))
print("NaN:", data[BEHAVIORAL_FEATURES].isna().sum().sum())
print("Inf:", np.isinf(data[BEHAVIORAL_FEATURES].to_numpy()).sum())

# =============================================================================
# 6. MERGE LABELS
# =============================================================================

print("\n[6] MERGING CLASS LABELS")
print("-" * 100)

data = data.merge(
    classes[["txId", "class"]],
    on="txId",
    how="inner",
    validate="one_to_one"
)

print("Merged shape:", data.shape)
print("Missing labels:", data["class"].isna().sum())

print("\nFinal class distribution:")
print(data["class"].value_counts().sort_index())

# =============================================================================
# 7. SORT TEMPORALLY
# =============================================================================

print("\n[7] TEMPORAL ORDERING")
print("-" * 100)

data = data.sort_values(
    ["Time step", "txId"]
).reset_index(drop=True)

print("Time range:",
      data["Time step"].min(),
      "to",
      data["Time step"].max())

# =============================================================================
# 8. TEMPORAL SPLIT
# =============================================================================

print("\n[8] TEMPORAL SPLIT")
print("-" * 100)

train_mask = (
    (data["Time step"] >= TRAIN_START) &
    (data["Time step"] <= TRAIN_END)
)

val_mask = (
    (data["Time step"] >= VAL_START) &
    (data["Time step"] <= VAL_END)
)

test_mask = (
    (data["Time step"] >= TEST_START) &
    (data["Time step"] <= TEST_END)
)

train_idx = np.where(train_mask.to_numpy())[0]
val_idx   = np.where(val_mask.to_numpy())[0]
test_idx  = np.where(test_mask.to_numpy())[0]

print(
    f"Train      : {len(train_idx):,} "
    f"(time {TRAIN_START}–{TRAIN_END})"
)

print(
    f"Validation : {len(val_idx):,} "
    f"(time {VAL_START}–{VAL_END})"
)

print(
    f"Test       : {len(test_idx):,} "
    f"(time {TEST_START}–{TEST_END})"
)

# =============================================================================
# 9. CREATE FEATURE MATRICES
# =============================================================================

print("\n[9] BUILDING FEATURE MATRICES")
print("-" * 100)

X = data[BEHAVIORAL_FEATURES].to_numpy(dtype=np.float32)

X_train = X[train_idx]
X_val   = X[val_idx]
X_test  = X[test_idx]

print("X:", X.shape)
print("Features:", X.shape[1])

# =============================================================================
# 10. STANDARDIZATION
# =============================================================================

print("\n[10] STANDARDIZATION")
print("-" * 100)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

print("✓ Scaler fitted ONLY on training data")

# =============================================================================
# 11. ISOLATION FOREST
# =============================================================================

print("\n[11] TRAINING ISOLATION FOREST")
print("-" * 100)

iso = IsolationForest(
    n_estimators=300,
    contamination="auto",
    max_samples="auto",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

iso.fit(X_train_scaled)

print("✓ Isolation Forest trained")
print("Trees:", 300)

# sklearn decision_function:
# higher = more normal
#
# For anomaly ranking:
# anomaly = -decision_function
#
# Therefore higher anomaly score = more anomalous.

if_train = -iso.decision_function(X_train_scaled)
if_val   = -iso.decision_function(X_val_scaled)
if_test  = -iso.decision_function(X_test_scaled)

# =============================================================================
# 12. LOF
# =============================================================================

print("\n[12] TRAINING LOF")
print("-" * 100)

# LOF is computationally expensive.
# It is trained only on the training set.
#
# n_neighbors=35 gives a reasonable local neighborhood.

lof = LocalOutlierFactor(
    n_neighbors=35,
    contamination="auto",
    novelty=True,
    n_jobs=-1
)

lof.fit(X_train_scaled)

print("✓ LOF trained")

lof_train_raw = -lof.decision_function(X_train_scaled)
lof_val_raw   = -lof.decision_function(X_val_scaled)
lof_test_raw  = -lof.decision_function(X_test_scaled)

# =============================================================================
# 13. ROBUST SCORE NORMALIZATION
# =============================================================================

print("\n[13] NORMALIZING MODEL SCORES")
print("-" * 100)

def robust_normalize(train_score, other_scores):
    """
    Normalize scores using training-set median and IQR.
    This avoids letting extreme outliers dominate the ensemble.
    """

    train_score = np.asarray(train_score, dtype=np.float64)

    q25, q75 = np.percentile(train_score, [25, 75])
    iqr = q75 - q25

    if iqr <= 1e-12:
        iqr = np.std(train_score)

    if iqr <= 1e-12:
        iqr = 1.0

    median = np.median(train_score)

    train_norm = (train_score - median) / iqr

    normalized = []

    for score in other_scores:
        score = np.asarray(score, dtype=np.float64)
        normalized.append((score - median) / iqr)

    return train_norm, normalized


if_train_norm, [if_val_norm, if_test_norm] = robust_normalize(
    if_train,
    [if_val, if_test]
)

lof_train_norm, [lof_val_norm, lof_test_norm] = robust_normalize(
    lof_train_raw,
    [lof_val_raw, lof_test_raw]
)

# =============================================================================
# 14. ENSEMBLE
# =============================================================================

print("\n[14] BUILDING ENSEMBLE")
print("-" * 100)

IF_WEIGHT = 0.60
LOF_WEIGHT = 0.40

ensemble_train = (
    IF_WEIGHT * if_train_norm +
    LOF_WEIGHT * lof_train_norm
)

ensemble_val = (
    IF_WEIGHT * if_val_norm +
    LOF_WEIGHT * lof_val_norm
)

ensemble_test = (
    IF_WEIGHT * if_test_norm +
    LOF_WEIGHT * lof_test_norm
)

print(f"Isolation Forest weight : {IF_WEIGHT}")
print(f"LOF weight              : {LOF_WEIGHT}")

# =============================================================================
# 15. BUILD COMPLETE RESULTS
# =============================================================================

print("\n[15] BUILDING FINAL RESULTS")
print("-" * 100)

results = data[
    ["txId", "Time step", "class"]
].copy()

results["split"] = "train"

results.loc[val_idx, "split"] = "validation"
results.loc[test_idx, "split"] = "test"

results["IF_anomaly"] = np.nan
results["LOF_anomaly"] = np.nan
results["ensemble_anomaly"] = np.nan

results.loc[train_idx, "IF_anomaly"] = if_train_norm
results.loc[val_idx, "IF_anomaly"]   = if_val_norm
results.loc[test_idx, "IF_anomaly"]  = if_test_norm

results.loc[train_idx, "LOF_anomaly"] = lof_train_norm
results.loc[val_idx, "LOF_anomaly"]   = lof_val_norm
results.loc[test_idx, "LOF_anomaly"]  = lof_test_norm

results.loc[train_idx, "ensemble_anomaly"] = ensemble_train
results.loc[val_idx, "ensemble_anomaly"]   = ensemble_val
results.loc[test_idx, "ensemble_anomaly"]  = ensemble_test

# =============================================================================
# 16. TEST SET
# =============================================================================

test_results = results[
    results["split"] == "test"
].copy()

test_results = test_results.sort_values(
    "ensemble_anomaly",
    ascending=False
).reset_index(drop=True)

print("\nTest transactions:", len(test_results))

# =============================================================================
# 17. CLASS-WISE ANALYSIS
# =============================================================================

print("\n" + "=" * 100)
print("CLASS-WISE TEST ANOMALY ANALYSIS")
print("=" * 100)

class_summary = (
    test_results
    .groupby("class")["ensemble_anomaly"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(class_summary)

# =============================================================================
# 18. POST-HOC CLASS-3 EVALUATION
# =============================================================================

print("\n" + "=" * 100)
print("POST-HOC CLASS-3 EVALUATION")
print("=" * 100)

y_test_class3 = (
    test_results["class"].to_numpy() == 3
).astype(int)

score_test = test_results[
    "ensemble_anomaly"
].to_numpy()

if len(np.unique(y_test_class3)) == 2:

    roc_auc = roc_auc_score(
        y_test_class3,
        score_test
    )

    pr_auc = average_precision_score(
        y_test_class3,
        score_test
    )

    print(f"Class-3 ROC-AUC : {roc_auc:.4f}")
    print(f"Class-3 PR-AUC  : {pr_auc:.4f}")

else:

    roc_auc = np.nan
    pr_auc = np.nan

    print("ROC-AUC/PR-AUC unavailable.")

# =============================================================================
# 19. TOP-K ANALYSIS
# =============================================================================

print("\n" + "=" * 100)
print("TOP-K ANOMALY ANALYSIS")
print("=" * 100)

overall_class3_pct = (
    y_test_class3.mean() * 100
)

top_k_values = [
    50,
    100,
    250,
    500,
    1000,
    2500,
    5000,
    10000
]

topk_rows = []

for k in top_k_values:

    k = min(k, len(test_results))

    top = test_results.iloc[:k]

    class3_count = (
        (top["class"] == 3).sum()
    )

    class3_pct = (
        class3_count / k * 100
    )

    enrichment = (
        class3_pct / overall_class3_pct
    )

    topk_rows.append({
        "Top_K": k,
        "Class3_Count": int(class3_count),
        "Class3_%": class3_pct,
        "Overall_Class3_%": overall_class3_pct,
        "Enrichment": enrichment
    })

topk_df = pd.DataFrame(topk_rows)

print(topk_df.to_string(index=False))

# =============================================================================
# 20. TOP 100
# =============================================================================

print("\n" + "=" * 100)
print("TOP 100 MOST ANOMALOUS TRANSACTIONS")
print("=" * 100)

top100 = test_results.head(100).copy()

print(
    top100[
        [
            "txId",
            "Time step",
            "class",
            "IF_anomaly",
            "LOF_anomaly",
            "ensemble_anomaly"
        ]
    ].to_string(index=False)
)

# =============================================================================
# 21. TEMPORAL ANALYSIS
# =============================================================================

print("\n" + "=" * 100)
print("TEMPORAL ANOMALY ANALYSIS")
print("=" * 100)

temporal = (
    test_results
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly=("ensemble_anomaly", "mean"),
        Median_Anomaly=("ensemble_anomaly", "median"),
        Max_Anomaly=("ensemble_anomaly", "max"),
        Class3_Count=("class", lambda x: (x == 3).sum())
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"] /
    temporal["Transactions"] * 100
)

temporal = temporal.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print(temporal)

# =============================================================================
# 22. UNSUPERVISED THRESHOLDS
# =============================================================================

print("\n" + "=" * 100)
print("UNSUPERVISED ANOMALY THRESHOLDS")
print("=" * 100)

threshold_rows = []

for percentile in [
    90,
    95,
    97,
    98,
    99,
    99.5,
    99.9
]:

    threshold = np.percentile(
        score_test,
        percentile
    )

    flagged = test_results[
        test_results["ensemble_anomaly"] >= threshold
    ]

    class3_count = (
        flagged["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / len(flagged) * 100
        if len(flagged) > 0
        else 0
    )

    threshold_rows.append({
        "Percentile": percentile,
        "Threshold": threshold,
        "Flagged": len(flagged),
        "Class3_Count": int(class3_count),
        "Class3_%": class3_pct
    })

threshold_df = pd.DataFrame(threshold_rows)

print(threshold_df.to_string(index=False))

# =============================================================================
# 23. MODEL SCORE DISTRIBUTION
# =============================================================================

print("\n" + "=" * 100)
print("MODEL SCORE DISTRIBUTION")
print("=" * 100)

score_distribution = pd.DataFrame({
    "Model": [
        "Isolation Forest",
        "LOF",
        "Ensemble"
    ],
    "Mean": [
        np.mean(if_test_norm),
        np.mean(lof_test_norm),
        np.mean(ensemble_test)
    ],
    "Std": [
        np.std(if_test_norm),
        np.std(lof_test_norm),
        np.std(ensemble_test)
    ],
    "Min": [
        np.min(if_test_norm),
        np.min(lof_test_norm),
        np.min(ensemble_test)
    ],
    "Median": [
        np.median(if_test_norm),
        np.median(lof_test_norm),
        np.median(ensemble_test)
    ],
    "Max": [
        np.max(if_test_norm),
        np.max(lof_test_norm),
        np.max(ensemble_test)
    ]
})

print(score_distribution.to_string(index=False))

# =============================================================================
# 24. SAVE COMPLETE RESULT
# =============================================================================

print("\n" + "=" * 100)
print("SAVING FINAL TRANSACTION RESULTS")
print("=" * 100)

full_results_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_large_scale_results.csv"
)

top100_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_top100.csv"
)

topk_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_topk.csv"
)

temporal_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_temporal.csv"
)

threshold_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_thresholds.csv"
)

class_summary_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_class_summary.csv"
)

score_distribution_path = os.path.join(
    OUTPUT_DIR,
    "bittrace_transaction_score_distribution.csv"
)

results.to_csv(
    full_results_path,
    index=False
)

top100.to_csv(
    top100_path,
    index=False
)

topk_df.to_csv(
    topk_path,
    index=False
)

temporal.to_csv(
    temporal_path
)

threshold_df.to_csv(
    threshold_path,
    index=False
)

class_summary.to_csv(
    class_summary_path
)

score_distribution.to_csv(
    score_distribution_path,
    index=False
)

print("✓", full_results_path)
print("✓", top100_path)
print("✓", topk_path)
print("✓", temporal_path)
print("✓", threshold_path)
print("✓", class_summary_path)
print("✓", score_distribution_path)

# =============================================================================
# 25. FINAL SUMMARY
# =============================================================================

print("\n" + "=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE TEST COMPLETE")
print("=" * 100)

print(f"""
Transactions loaded       : {len(data):,}
Features used              : {len(BEHAVIORAL_FEATURES)}
Training transactions     : {len(train_idx):,}
Validation transactions   : {len(val_idx):,}
Test transactions         : {len(test_idx):,}

Training time             : {TRAIN_START}–{TRAIN_END}
Validation time           : {VAL_START}–{VAL_END}
Test time                 : {TEST_START}–{TEST_END}

Isolation Forest          : ✓
LOF                       : ✓
Ensemble                  : ✓
Temporal split            : ✓
Top-K analysis            : ✓
Threshold analysis        : ✓
Temporal analysis         : ✓
Post-hoc evaluation       : ✓

Class-3 ROC-AUC            : {roc_auc:.4f}
Class-3 PR-AUC             : {pr_auc:.4f}

P2P / network data        : NOT USED
Labels during training    : NOT USED
""")

print("=" * 100)
print("IMPORTANT:")
print("The class labels are used ONLY for post-hoc evaluation.")
print("They are NOT used to train Isolation Forest or LOF.")
print("=" * 100)

====================================================================================================
BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE FINAL TEST
====================================================================================================

[1] FILE CHECK
----------------------------------------------------------------------------------------------------
FEATURE : C:\Users\YASHIKA\Desktop\bit-trace\data\raw\elliptic-plus-plus\txs_features.csv
CLASS   : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv

[2] LOADING CLASS LABELS
----------------------------------------------------------------------------------------------------
Shape: (203769, 2)

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[3] READING FEATURE HEADER
----------------------------------------------------------------------------------------------------
Total columns: 184
✓ All required transaction features found

[4] LOADING TRANSACTION FEATURES
----------------------------------------------------------------------------------------------------
Loaded shape: (203769, 15)

[5] CLEANING TRANSACTION DATA
----------------------------------------------------------------------------------------------------
Rows: 203769
NaN: 0
Inf: 0

[6] MERGING CLASS LABELS
----------------------------------------------------------------------------------------------------
Merged shape: (203769, 16)
Missing labels: 0

Final class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[7] TEMPORAL ORDERING
----------------------------------------------------------------------------------------------------
Time range: 1 to 49

[8] TEMPORAL SPLIT
----------------------------------------------------------------------------------------------------
Train      : 136,265 (time 1–34)
Validation : 30,680 (time 35–41)
Test       : 36,824 (time 42–49)

[9] BUILDING FEATURE MATRICES
----------------------------------------------------------------------------------------------------
X: (203769, 13)
Features: 13

[10] STANDARDIZATION
----------------------------------------------------------------------------------------------------
✓ Scaler fitted ONLY on training data

[11] TRAINING ISOLATION FOREST
----------------------------------------------------------------------------------------------------
✓ Isolation Forest trained
Trees: 300

[12] TRAINING LOF
----------------------------------------------------------------------------------------------------
✓ LOF trained

[13] NORMALIZING MODEL SCORES
----------------------------------------------------------------------------------------------------

[14] BUILDING ENSEMBLE
----------------------------------------------------------------------------------------------------
Isolation Forest weight : 0.6
LOF weight              : 0.4

[15] BUILDING FINAL RESULTS
----------------------------------------------------------------------------------------------------

Test transactions: 36824

====================================================================================================
CLASS-WISE TEST ANOMALY ANALYSIS
====================================================================================================
       Samples       Mean         Std       Min    Median           Max
class
1          408   0.998433    2.697072 -0.287230  0.541476     33.571585
2         8433  34.781004  729.131998 -0.314507  1.102545  27744.364960
3        27983  10.280635  364.683330 -0.324809  0.423839  45738.357340

====================================================================================================
POST-HOC CLASS-3 EVALUATION
====================================================================================================
Class-3 ROC-AUC : 0.3175
Class-3 PR-AUC  : 0.6716

====================================================================================================
TOP-K ANOMALY ANALYSIS
====================================================================================================
 Top_K  Class3_Count  Class3_%  Overall_Class3_%  Enrichment
    50            24     48.00         75.991201    0.631652
   100            70     70.00         75.991201    0.921159
   250           148     59.20         75.991201    0.779038
   500           241     48.20         75.991201    0.634284
  1000           620     62.00         75.991201    0.815884
  2500          1587     63.48         75.991201    0.835360
  5000          2945     58.90         75.991201    0.775090
 10000          6245     62.45         75.991201    0.821806

====================================================================================================
TOP 100 MOST ANOMALOUS TRANSACTIONS
====================================================================================================
     txId  Time step  class  IF_anomaly   LOF_anomaly  ensemble_anomaly
 94664385         43      3    0.083890 114345.767514      45738.357340
  6069276         48      3    2.346352  75568.866610      30228.954455
 66435614         46      2    3.644349  69355.445876      27744.364960
 66435532         46      2    3.657703  69284.650848      27716.054961
218099491         47      2    3.489501  66607.102987      26644.934896
218039532         47      2    3.452060  66482.680513      26595.143441
195422450         46      2    3.514814  66455.437986      26584.284083
 94664391         43      3    0.090469  47460.176925      18984.125052
106319916         44      3    0.060552  29913.631468      11965.488919
 71481196         42      2    2.853914  27048.628988      10821.163943
155586773         45      2    3.511960  26367.797612      10549.226221
158405236         49      2    3.347816  24968.713086       9989.493924
 94190966         43      2    3.576529  21750.705100       8702.427957
155803971         45      2    3.705468  20984.031952       8395.836062
 94311363         43      2    3.668972  19291.302195       7718.722261
157581697         49      2    3.442745  19079.958213       7634.048932
158397925         49      2    3.363174  18752.657724       7503.080994
  3331946         48      2    3.543551  15891.828349       6358.857470
  3388162         48      2    3.511886  15050.000672       6022.107400
 92074742         43      2    3.550337  12894.205912       5159.812567
  4691966         48      3    0.109761  10754.548254       4301.885158
106446312         44      2    2.547224   9250.730469       3701.820522
155829839         45      2    4.951450   9016.911016       3609.735277
 72027995         42      2    3.646947   6494.732379       2600.081120
218400353         47      3    0.457303   5896.078633       2358.705835
158345837         49      2    4.939172   5367.093824       2149.801033
155816192         45      2    4.939172   5367.067748       2149.790602
156307149         45      2    4.937029   5366.026162       2149.372682
155813484         45      2    4.943203   5304.211374       2124.650472
164964361         45      2    4.938916   5299.981288       2122.955865
155813492         45      2    4.943531   5261.844359       2107.703862
 79693333         47      3    0.447981   5139.319145       2055.996447
219567373         47      2    0.474497   5135.359476       2054.428488
218400373         47      3    0.483030   5131.486726       2052.884508
219567446         47      3    0.451257   4971.424810       1988.840678
 72023201         42      3    0.505140   4669.457514       1868.086089
 79693306         47      3    0.406962   4526.011724       1810.648867
 79693335         47      3    0.406962   4468.654462       1787.705962
219567097         47      3    0.390794   4319.993498       1728.231875
 81959794         47      3    0.381329   4274.021735       1709.837491
 72021941         42      3    0.354953   4232.132294       1693.065890
219567433         47      3    0.333649   4159.370469       1663.948377
 94199247         43      3    0.334754   4075.226525       1630.291463
218400369         47      3    0.343417   4059.032443       1623.819027
 73100209         42      3    0.333649   4058.901097       1623.760629
 73100397         42      3    0.333649   4058.712772       1623.685298
 79693337         47      3    0.343417   4044.367179       1617.952922
 94369571         43      3    0.334754   3944.159049       1577.864472
 94369566         43      3    0.334754   3944.159049       1577.864472
 99553989         43      3    0.334754   3943.441238       1577.577348
218400386         47      2    0.313866   3831.698156       1532.867582
218400359         47      3    0.313866   3831.698156       1532.867582
 79693336         47      3    0.313866   3827.708789       1531.271835
 81959803         47      3    0.313866   3827.708789       1531.271835
 79693310         47      3    0.313866   3827.058824       1531.011849
 79693318         47      3    0.313866   3827.038543       1531.003736
 79693314         47      3    0.313866   3827.026953       1530.999101
 79693315         47      3    0.313866   3827.026953       1530.999101
 72021948         42      3    0.313866   3826.510023       1530.792329
 72021952         42      3    0.313866   3826.510023       1530.792329
 72023198         42      3    0.313866   3826.241056       1530.684742
219478728         47      3    0.320270   3785.443421       1514.369531
107210876         44      3    0.320270   3774.892592       1510.149199
219478734         47      3    0.320270   3764.084143       1505.825819
 79693323         47      3    0.284366   3742.013331       1496.975952
 79693334         47      3    0.284366   3742.013331       1496.975952
218400387         47      3    0.283272   3742.012848       1496.975103
218400365         47      3    0.283272   3742.012848       1496.975103
 81959804         47      3    0.284366   3741.979771       1496.962528
218400393         47      3    0.283272   3741.979771       1496.961872
219567474         47      3    0.284366   3741.180835       1496.642953
219567432         47      3    0.284366   3741.180835       1496.642953
219478736         47      3    0.283272   3741.180835       1496.642297
218400377         47      3    0.323098   3730.281120       1492.306307
 81959789         47      3    0.324200   3724.293086       1489.911754
 79693311         47      3    0.324200   3706.068948       1482.622099
 94199420         43      3    0.324200   3700.592773       1480.431630
218400418         47      3    0.311569   3649.136385       1459.841496
 73376850         42      3    0.312669   3649.034496       1459.801400
 79693307         47      3    0.312669   3648.411331       1459.552134
 73099992         42      3    0.311569   3632.572411       1453.215906
 73103603         42      3    0.311569   3632.572411       1453.215906
 71990378         42      3    0.311569   3632.347144       1453.125799
 73103383         42      3    0.311569   3632.307306       1453.109864
 72023092         42      3    0.311569   3630.513141       1452.392198
 81959799         47      3    0.295903   3630.316124       1452.303991
 72021937         42      3    0.311569   3630.228963       1452.278527
218400364         47      3    0.312669   3618.319049       1447.515221
219567453         47      3    0.312669   3617.586510       1447.222206
218400379         47      3    0.311569   3616.407060       1446.749766
218400362         47      3    0.312669   3611.895934       1444.945975
 71990363         42      3    0.312669   3600.942378       1440.564553
 94367092         43      3    0.284726   3594.396851       1437.929576
 94367094         43      3    0.284726   3594.285062       1437.884861
 94369709         43      3    0.283632   3594.283372       1437.883528
 94369705         43      3    0.283632   3594.229048       1437.861798
 94199152         43      3    0.284726   3593.962494       1437.755833
 94200503         43      2    0.312669   3583.346958       1433.526385
 94367111         43      2    0.312669   3583.054088       1433.409237
 94645492         43      2    0.312669   3582.918879       1433.355153

====================================================================================================
TEMPORAL ANOMALY ANALYSIS
====================================================================================================
           Transactions  Mean_Anomaly  Median_Anomaly   Max_Anomaly  \
Time step
47                 5121     28.103392        0.613901  26644.934896
46                 3519     25.018779        0.553391  27744.364960
43                 5063     24.052059        0.738561  45738.357340
48                 2954     17.501327        0.479013  30228.954455
49                 2454     13.224096        0.609404   9989.493924
45                 5598     10.651049        0.485135  10549.226221
42                 7140      6.981488        0.685484  10821.163943
44                 4975      6.842452        0.392008  11965.488919

           Class3_Count   Class3_%
Time step
47                 4275  83.479789
46                 2807  79.766979
43                 3693  72.940944
48                 2483  84.055518
49                 1978  80.603097
45                 4377  78.188639
42                 4986  69.831933
44                 3384  68.020101

====================================================================================================
UNSUPERVISED ANOMALY THRESHOLDS
====================================================================================================
 Percentile   Threshold  Flagged  Class3_Count  Class3_%
       90.0    3.151111     3683          2233 60.629921
       95.0    5.533998     1842          1176 63.843648
       97.0    9.796651     1105           695 62.895928
       98.0   11.859749      737           396 53.731343
       99.0   29.643092      369           190 51.490515
       99.5  240.356845      185           140 75.675676
       99.9 1791.766856       37            11 29.729730

====================================================================================================
MODEL SCORE DISTRIBUTION
====================================================================================================
           Model      Mean         Std       Min   Median           Max
Isolation Forest  0.648509    1.273773 -0.261848 0.012529      5.853333
             LOF 38.498680 1180.247073 -0.512223 0.648270 114345.767514
        Ensemble 15.788578  472.125253 -0.324809 0.596950  45738.357340

====================================================================================================
SAVING FINAL TRANSACTION RESULTS
====================================================================================================
✓ C:\Users\YASHIKA\Desktop\bit-tracetransaction_final_test\bittrace_transaction_large_scale_results.csv
✓ C:\Users\YASHIKA\Desktop\bit-tracetransaction_final_test\bittrace_transaction_top100.csv
✓ C:\Users\YASHIKA\Desktop\bit-tracetransaction_final_test\bittrace_transaction_topk.csv
✓ C:\Users\YASHIKA\Desktop\bit-tracetransaction_final_test\bittrace_transaction_temporal.csv
✓ C:\Users\YASHIKA\Desktop\bit-tracetransaction_final_test\bittrace_transaction_thresholds.csv
✓ C:\Users\YASHIKA\Desktop\bit-tracetransaction_final_test\bittrace_transaction_class_summary.csv
✓ C:\Users\YASHIKA\Desktop\bit-tracetransaction_final_test\bittrace_transaction_score_distribution.csv

====================================================================================================
BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE TEST COMPLETE
====================================================================================================

Transactions loaded       : 203,769
Features used              : 13
Training transactions     : 136,265
Validation transactions   : 30,680
Test transactions         : 36,824

Training time             : 1–34
Validation time           : 35–41
Test time                 : 42–49

Isolation Forest          : ✓
LOF                       : ✓
Ensemble                  : ✓
Temporal split            : ✓
Top-K analysis            : ✓
Threshold analysis        : ✓
Temporal analysis         : ✓
Post-hoc evaluation       : ✓

Class-3 ROC-AUC            : 0.3175
Class-3 PR-AUC             : 0.6716

P2P / network data        : NOT USED
Labels during training    : NOT USED

====================================================================================================
IMPORTANT:
The class labels are used ONLY for post-hoc evaluation.
They are NOT used to train Isolation Forest or LOF.
====================================================================================================

In [51]:
# =============================================================================
# BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE FINAL TEST
# 203,769 TRANSACTIONS
# =============================================================================

import os
import numpy as np
import pandas as pd

from pathlib import Path

print("=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE FINAL TEST")
print("=" * 100)

# -----------------------------------------------------------------------------
# 1. PATHS
# -----------------------------------------------------------------------------

BASE = Path(r"C:\Users\YASHIKA\Desktop\bit-trace")

RESULT_PATH = BASE / "src" / "ellipticpp_graph_behavioral_anomaly_results.csv"
CLASS_PATH = (
    BASE
    / "EllipticPlusPlus"
    / "Transactions Dataset"
    / "txs_classes.csv"
)

FEATURE_PATH = (
    BASE
    / "data"
    / "raw"
    / "elliptic-plus-plus"
    / "txs_features.csv"
)

OUTPUT_DIR = BASE / "bittrace_transaction_stress_test"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# -----------------------------------------------------------------------------
# 2. FILE CHECK
# -----------------------------------------------------------------------------

print("\n[1] FILE CHECK")
print("-" * 100)

for name, path in {
    "Anomaly results": RESULT_PATH,
    "Class labels": CLASS_PATH,
    "Feature data": FEATURE_PATH
}.items():

    print(f"{name:20}: {path.exists()}")

    if path.exists():
        print(f"Path                : {path}")

# -----------------------------------------------------------------------------
# 3. LOAD EXISTING ANOMALY RESULTS
# -----------------------------------------------------------------------------

print("\n[2] LOADING ANOMALY RESULTS")
print("-" * 100)

results = pd.read_csv(RESULT_PATH)

print("Shape:", results.shape)
print("Columns:", results.columns.tolist())

required_result_cols = [
    "txId",
    "Time step",
    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly",
    "split"
]

missing = [
    c for c in required_result_cols
    if c not in results.columns
]

if missing:
    raise ValueError(f"Missing result columns: {missing}")

results = results.drop_duplicates("txId").copy()

print("Clean shape:", results.shape)

# -----------------------------------------------------------------------------
# 4. LOAD LABELS
# -----------------------------------------------------------------------------

print("\n[3] LOADING CLASS LABELS")
print("-" * 100)

classes = pd.read_csv(CLASS_PATH)

classes.columns = [
    str(c).strip()
    for c in classes.columns
]

print("Shape:", classes.shape)
print("Columns:", classes.columns.tolist())

classes = classes[["txId", "class"]].drop_duplicates("txId")

print("\nClass distribution:")
print(classes["class"].value_counts().sort_index())

# -----------------------------------------------------------------------------
# 5. MERGE
# -----------------------------------------------------------------------------

print("\n[4] MERGING RESULTS + LABELS")
print("-" * 100)

df = results.merge(
    classes,
    on="txId",
    how="left",
    validate="one_to_one"
)

print("Merged shape:", df.shape)
print("Missing labels:", df["class"].isna().sum())

if df["class"].isna().any():
    raise ValueError("Some transactions have missing class labels.")

# -----------------------------------------------------------------------------
# 6. VERIFY ALL 203K TRANSACTIONS
# -----------------------------------------------------------------------------

print("\n[5] FULL DATASET VERIFICATION")
print("-" * 100)

print("Total transactions:", len(df))

print(
    "Unique transactions:",
    df["txId"].nunique()
)

print(
    "Time range:",
    df["Time step"].min(),
    "to",
    df["Time step"].max()
)

print("\nSplit distribution:")
print(df["split"].value_counts())

print("\nClass distribution:")
print(df["class"].value_counts().sort_index())

# -----------------------------------------------------------------------------
# 7. CHECK SCORE QUALITY
# -----------------------------------------------------------------------------

print("\n[6] SCORE QUALITY CHECK")
print("-" * 100)

score_cols = [
    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly"
]

for col in score_cols:

    print(f"\n{col}")

    print(
        "NaN:",
        df[col].isna().sum()
    )

    print(
        "Inf:",
        np.isinf(df[col].to_numpy()).sum()
    )

    print(
        "Min:",
        df[col].min()
    )

    print(
        "Median:",
        df[col].median()
    )

    print(
        "Max:",
        df[col].max()
    )

# -----------------------------------------------------------------------------
# 8. GLOBAL ANOMALY PERCENTILE
# -----------------------------------------------------------------------------

print("\n[7] CALCULATING GLOBAL ANOMALY PERCENTILE")
print("-" * 100)

df["anomaly_percentile"] = (
    df["ensemble_anomaly"]
    .rank(pct=True) * 100
)

# -----------------------------------------------------------------------------
# 9. INVESTIGATION LEVEL
# -----------------------------------------------------------------------------

def investigation_level(p):

    if p >= 99.5:
        return "CRITICAL"

    elif p >= 99:
        return "HIGH"

    elif p >= 95:
        return "MEDIUM"

    else:
        return "LOW"


df["investigation_level"] = (
    df["anomaly_percentile"]
    .apply(investigation_level)
)

print(
    df["investigation_level"]
    .value_counts()
)

# -----------------------------------------------------------------------------
# 10. FULL DATASET TOP ANOMALIES
# -----------------------------------------------------------------------------

print("\n[8] TOP ANOMALOUS TRANSACTIONS — FULL DATASET")
print("-" * 100)

top100 = (
    df
    .sort_values(
        "ensemble_anomaly",
        ascending=False
    )
    .head(100)
)

display_cols = [
    "txId",
    "Time step",
    "class",
    "split",
    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly",
    "anomaly_percentile",
    "investigation_level"
]

print(
    top100[display_cols]
    .head(30)
    .to_string(index=False)
)

# -----------------------------------------------------------------------------
# 11. TOP-K DISTRIBUTION
# -----------------------------------------------------------------------------

print("\n[9] TOP-K ANALYSIS — FULL 203K DATASET")
print("-" * 100)

overall_class3 = (
    (df["class"] == 3).mean() * 100
)

topk_values = [
    50,
    100,
    250,
    500,
    1000,
    2500,
    5000,
    10000,
    25000
]

topk_rows = []

for k in topk_values:

    subset = (
        df
        .sort_values(
            "ensemble_anomaly",
            ascending=False
        )
        .head(k)
    )

    class3_count = (
        subset["class"] == 3
    ).sum()

    class3_percentage = (
        class3_count / k * 100
    )

    enrichment = (
        class3_percentage /
        overall_class3
    )

    topk_rows.append({

        "Top_K": k,

        "Samples": k,

        "Class1_Count":
            (subset["class"] == 1).sum(),

        "Class2_Count":
            (subset["class"] == 2).sum(),

        "Class3_Count":
            class3_count,

        "Class3_%":
            class3_percentage,

        "Overall_Class3_%":
            overall_class3,

        "Enrichment":
            enrichment
    })


topk_df = pd.DataFrame(topk_rows)

print(
    topk_df.to_string(index=False)
)

# -----------------------------------------------------------------------------
# 12. SCORE THRESHOLD ANALYSIS
# -----------------------------------------------------------------------------

print("\n[10] UNSUPERVISED THRESHOLD ANALYSIS")
print("-" * 100)

percentiles = [
    90,
    95,
    97,
    98,
    99,
    99.5,
    99.9
]

threshold_rows = []

for p in percentiles:

    threshold = np.percentile(
        df["ensemble_anomaly"],
        p
    )

    flagged = df[
        df["ensemble_anomaly"] >= threshold
    ]

    class3_count = (
        flagged["class"] == 3
    ).sum()

    threshold_rows.append({

        "Percentile": p,

        "Threshold":
            threshold,

        "Flagged":
            len(flagged),

        "Flagged_%":
            len(flagged) / len(df) * 100,

        "Class1_Count":
            (flagged["class"] == 1).sum(),

        "Class2_Count":
            (flagged["class"] == 2).sum(),

        "Class3_Count":
            class3_count,

        "Class3_%":
            class3_count / len(flagged) * 100
            if len(flagged) else 0
    })


threshold_df = pd.DataFrame(threshold_rows)

print(
    threshold_df.to_string(index=False)
)

# -----------------------------------------------------------------------------
# 13. TEMPORAL ANALYSIS
# -----------------------------------------------------------------------------

print("\n[11] TEMPORAL STRESS TEST")
print("-" * 100)

temporal = (
    df
    .groupby("Time step")
    .agg(

        Transactions=(
            "txId",
            "count"
        ),

        Mean_Anomaly=(
            "ensemble_anomaly",
            "mean"
        ),

        Median_Anomaly=(
            "ensemble_anomaly",
            "median"
        ),

        Max_Anomaly=(
            "ensemble_anomaly",
            "max"
        ),

        Std_Anomaly=(
            "ensemble_anomaly",
            "std"
        ),

        Class3_Count=(
            "class",
            lambda x: (x == 3).sum()
        )
    )
)

temporal["Class3_%"] = (
    temporal["Class3_Count"] /
    temporal["Transactions"] *
    100
)

temporal = (
    temporal
    .sort_values(
        "Mean_Anomaly",
        ascending=False
    )
)

print(
    temporal.head(20).to_string()
)

# -----------------------------------------------------------------------------
# 14. SPLIT-WISE ANALYSIS
# -----------------------------------------------------------------------------

print("\n[12] TRAIN / VALIDATION / TEST ANALYSIS")
print("-" * 100)

split_summary = (
    df
    .groupby("split")
    .agg(

        Transactions=(
            "txId",
            "count"
        ),

        Mean_Anomaly=(
            "ensemble_anomaly",
            "mean"
        ),

        Median_Anomaly=(
            "ensemble_anomaly",
            "median"
        ),

        Max_Anomaly=(
            "ensemble_anomaly",
            "max"
        ),

        P95=(
            "ensemble_anomaly",
            lambda x: np.percentile(x, 95)
        ),

        P99=(
            "ensemble_anomaly",
            lambda x: np.percentile(x, 99)
        )
    )
)

print(
    split_summary.to_string()
)

# -----------------------------------------------------------------------------
# 15. HIGH PRIORITY INVESTIGATION QUEUE
# -----------------------------------------------------------------------------

print("\n[13] INVESTIGATION QUEUE")
print("-" * 100)

investigation_queue = (
    df[
        df["investigation_level"]
        .isin(["CRITICAL", "HIGH"])
    ]
    .sort_values(
        "ensemble_anomaly",
        ascending=False
    )
    .copy()
)

print(
    "CRITICAL + HIGH:",
    len(investigation_queue)
)

print(
    "\nDistribution:"
)

print(
    investigation_queue[
        "investigation_level"
    ].value_counts()
)

# -----------------------------------------------------------------------------
# 16. TRANSACTION SUMMARY
# -----------------------------------------------------------------------------

print("\n[14] FINAL TRANSACTION SUMMARY")
print("-" * 100)

summary = {

    "total_transactions":
        len(df),

    "unique_transactions":
        df["txId"].nunique(),

    "time_steps":
        df["Time step"].nunique(),

    "min_time":
        df["Time step"].min(),

    "max_time":
        df["Time step"].max(),

    "critical":
        (
            df["investigation_level"]
            == "CRITICAL"
        ).sum(),

    "high":
        (
            df["investigation_level"]
            == "HIGH"
        ).sum(),

    "medium":
        (
            df["investigation_level"]
            == "MEDIUM"
        ).sum(),

    "low":
        (
            df["investigation_level"]
            == "LOW"
        ).sum()
}

for key, value in summary.items():

    print(
        f"{key:25}: {value}"
    )

# -----------------------------------------------------------------------------
# 17. SAVE FULL STRESS TEST RESULTS
# -----------------------------------------------------------------------------

print("\n[15] SAVING RESULTS")
print("-" * 100)

full_path = (
    OUTPUT_DIR /
    "bittrace_transaction_full_stress_test.csv"
)

topk_path = (
    OUTPUT_DIR /
    "bittrace_transaction_large_scale_topk.csv"
)

threshold_path = (
    OUTPUT_DIR /
    "bittrace_transaction_large_scale_thresholds.csv"
)

temporal_path = (
    OUTPUT_DIR /
    "bittrace_transaction_large_scale_temporal.csv"
)

split_path = (
    OUTPUT_DIR /
    "bittrace_transaction_large_scale_split_summary.csv"
)

queue_path = (
    OUTPUT_DIR /
    "bittrace_transaction_investigation_queue.csv"
)

summary_path = (
    OUTPUT_DIR /
    "bittrace_transaction_large_scale_summary.csv"
)

df.to_csv(
    full_path,
    index=False
)

topk_df.to_csv(
    topk_path,
    index=False
)

threshold_df.to_csv(
    threshold_path,
    index=False
)

temporal.to_csv(
    temporal_path
)

split_summary.to_csv(
    split_path
)

investigation_queue.to_csv(
    queue_path,
    index=False
)

pd.DataFrame(
    [summary]
).to_csv(
    summary_path,
    index=False
)

print("✓ Full results     :", full_path)
print("✓ Top-K analysis   :", topk_path)
print("✓ Thresholds       :", threshold_path)
print("✓ Temporal         :", temporal_path)
print("✓ Split summary    :", split_path)
print("✓ Investigation    :", queue_path)
print("✓ Summary          :", summary_path)

# -----------------------------------------------------------------------------
# 18. FINAL STATUS
# -----------------------------------------------------------------------------

print("\n")
print("=" * 100)
print("BIT-TRACE — LARGE-SCALE TRANSACTION TEST COMPLETE")
print("=" * 100)

print(f"""
Transactions tested       : {len(df):,}
Unique transactions       : {df['txId'].nunique():,}
Time steps                : {df['Time step'].min()}–{df['Time step'].max()}

Models already used:
✓ Isolation Forest
✓ LOF
✓ Ensemble anomaly score

Features:
✓ Behavioral features
✓ Graph transaction features
✓ Temporal information

Testing:
✓ Full 203K transaction dataset
✓ Top-K anomaly ranking
✓ Threshold testing
✓ Temporal stress testing
✓ Investigation queue generation

P2P / network data:
✗ NOT USED

Labels:
✗ NOT USED FOR MODEL TRAINING
✓ Used only for post-hoc evaluation

Next:
Use the generated investigation queue
and dashboard data for transaction-level investigation.
""")

print("=" * 100)

====================================================================================================
BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE FINAL TEST
====================================================================================================

[1] FILE CHECK
----------------------------------------------------------------------------------------------------
Anomaly results     : True
Path                : C:\Users\YASHIKA\Desktop\bit-trace\src\ellipticpp_graph_behavioral_anomaly_results.csv
Class labels        : True
Path                : C:\Users\YASHIKA\Desktop\bit-trace\EllipticPlusPlus\Transactions Dataset\txs_classes.csv
Feature data        : True
Path                : C:\Users\YASHIKA\Desktop\bit-trace\data\raw\elliptic-plus-plus\txs_features.csv

[2] LOADING ANOMALY RESULTS
----------------------------------------------------------------------------------------------------
Shape: (203769, 6)
Columns: ['txId', 'Time step', 'IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly', 'split']
Clean shape: (203769, 6)

[3] LOADING CLASS LABELS
----------------------------------------------------------------------------------------------------
Shape: (203769, 2)
Columns: ['txId', 'class']

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[4] MERGING RESULTS + LABELS
----------------------------------------------------------------------------------------------------
Merged shape: (203769, 7)
Missing labels: 0

[5] FULL DATASET VERIFICATION
----------------------------------------------------------------------------------------------------
Total transactions: 203769
Unique transactions: 203769
Time range: 1 to 49

Split distribution:
split
train         136265
test           36824
validation     30680
Name: count, dtype: int64

Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[6] SCORE QUALITY CHECK
----------------------------------------------------------------------------------------------------

IF_anomaly
NaN: 0
Inf: 0
Min: -0.4917506
Median: 0.02256561
Max: 6.932095

LOF_anomaly
NaN: 0
Inf: 0
Min: -0.5230763
Median: 0.1584635
Max: 1394.7351

ensemble_anomaly
NaN: 0
Inf: 0
Min: -0.44945288
Median: 0.30855015
Max: 557.88446

[7] CALCULATING GLOBAL ANOMALY PERCENTILE
----------------------------------------------------------------------------------------------------
investigation_level
LOW         193580
MEDIUM        8151
CRITICAL      1019
HIGH          1019
Name: count, dtype: int64

[8] TOP ANOMALOUS TRANSACTIONS — FULL DATASET
----------------------------------------------------------------------------------------------------
     txId  Time step  class      split  IF_anomaly  LOF_anomaly  ensemble_anomaly  anomaly_percentile investigation_level
 94034375          7      3      train   -0.015924   1394.73510        557.884460          100.000000            CRITICAL
378195299         16      3      train    0.008720   1051.85720        420.748100           99.999509            CRITICAL
174780183          9      3      train    0.247391   1019.45560        407.930700           99.999018            CRITICAL
399702529         12      2      train    0.011468    977.94916        391.186550           99.998528            CRITICAL
 68460734         10      3      train    0.246884    860.73160        344.440800           99.998037            CRITICAL
208999710         20      3      train    0.253129    844.45105        337.932300           99.997546            CRITICAL
234435039         11      3      train    0.255829    744.23914        297.849150           99.997055            CRITICAL
 30179414         37      3 validation    0.022045    692.76465        277.119080           99.996565            CRITICAL
  3757070          1      2      train   -0.193871    550.27026        219.991790           99.996074            CRITICAL
339083170         13      3      train    0.267630    524.80475        210.082490           99.995583            CRITICAL
 94048122          7      3      train    0.250693    524.11380        209.795910           99.995092            CRITICAL
 94114483          7      3      train    0.014111    421.01013        168.412520           99.994602            CRITICAL
298741505         30      3      train    0.009067    418.24838        167.304800           99.994111            CRITICAL
211155347          2      3      train    0.558366    409.02948        163.946810           99.993620            CRITICAL
339102373         13      2      train   -0.183582    370.74640        148.188420           99.993129            CRITICAL
 87811705          4      3      train   -0.154769    369.52432        147.716860           99.992639            CRITICAL
109128912          2      3      train    0.204241    359.33170        143.855220           99.992148            CRITICAL
166888653          2      3      train    0.211963    350.06265        140.152240           99.991657            CRITICAL
 43123513         10      3      train    0.250342    349.27872        139.861700           99.991166            CRITICAL
346118591         12      3      train   -0.183582    344.53268        137.702930           99.990676            CRITICAL
243784831         15      3      train    0.022345    340.87762        136.364460           99.990185            CRITICAL
363389034         19      3      train    0.014111    336.46768        134.595540           99.989694            CRITICAL
312493838          2      3      train    0.182436    320.61383        128.355000           99.989203            CRITICAL
312506848          2      3      train    0.199729    314.97308        126.109060           99.988713            CRITICAL
156760432          2      3      train    0.153340    300.24630        120.190530           99.988222            CRITICAL
 92797015          2      3      train    0.166323    294.49237        117.896740           99.987731            CRITICAL
 86688776          4      3      train   -0.154769    291.44968        116.487010           99.987240            CRITICAL
137064109          2      3      train    0.157132    277.26062        110.998530           99.986750            CRITICAL
312493732          2      3      train    0.133190    270.43370        108.253380           99.986259            CRITICAL
 34123925          2      3      train    0.138736    269.08826        107.718544           99.985768            CRITICAL

[9] TOP-K ANALYSIS — FULL 203K DATASET
----------------------------------------------------------------------------------------------------
 Top_K  Samples  Class1_Count  Class2_Count  Class3_Count  Class3_%  Overall_Class3_%  Enrichment
    50       50             0             5            45    90.000         77.148634    1.166579
   100      100             0            14            86    86.000         77.148634    1.114731
   250      250             1            75           174    69.600         77.148634    0.902155
   500      500             1           143           356    71.200         77.148634    0.922894
  1000     1000             5           333           662    66.200         77.148634    0.858084
  2500     2500            40           742          1718    68.720         77.148634    0.890748
  5000     5000            82          1745          3173    63.460         77.148634    0.822568
 10000    10000           164          3926          5910    59.100         77.148634    0.766054
 25000    25000           335         12341         12324    49.296         77.148634    0.638974

[10] UNSUPERVISED THRESHOLD ANALYSIS
----------------------------------------------------------------------------------------------------
 Percentile  Threshold  Flagged  Flagged_%  Class1_Count  Class2_Count  Class3_Count  Class3_%
       90.0   2.403457    20377  10.000049           295          9514         10568 51.862394
       95.0   3.360375    10189   5.000270           164          3994          6031 59.191285
       97.0   4.660987     6114   3.000456           101          2290          3723 60.893032
       98.0   6.113536     4076   2.000304            70          1295          2711 66.511286
       99.0  10.109173     2038   1.000152            22           630          1386 68.007851
       99.5  17.429212     1019   0.500076             6           336           677 66.437684
       99.9  36.439441      204   0.100113             1            40           163 79.901961

[11] TEMPORAL STRESS TEST
----------------------------------------------------------------------------------------------------
           Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly  Std_Anomaly  Class3_Count   Class3_%
Time step
43                 5063      2.724170        0.912523    65.282610     5.844665          3693  72.940944
2                  4544      1.832401        0.373431   163.946810     9.219565          3427  75.418134
40                 4481      1.546992        0.756387    41.779682     2.697246          3270  72.974782
39                 2760      1.516940        0.977554    80.259895     2.792338          1577  57.137681
45                 5598      1.437229        0.398776    54.471413     3.744304          4377  78.188639
46                 3519      1.405046        0.836679    35.390053     2.518564          2807  79.766979
42                 7140      1.353905        0.708009    53.929455     2.540389          4986  69.831933
41                 5342      1.344750        0.648749    37.963356     2.448712          4210  78.809435
47                 5121      1.339648        0.541131    61.643950     3.266835          4275  83.479789
19                 3506      1.200661        0.411680   134.595540     4.239695          2761  78.750713
48                 2954      1.162728        0.350089    37.881035     2.661740          2483  84.055518
12                 2047      1.152893        0.412061   391.186550     9.350988          1541  75.280899
18                 1976      1.058937        0.211524    44.701810     3.802187          1587  80.313765
36                 6393      1.051755        0.751481    39.424366     1.837160          4685  73.283279
38                 2891      1.021769        0.587550    25.451906     1.797473          2135  73.849879
20                 4291      1.017819        0.297871   337.932300     5.925500          3391  79.025868
28                 1653      1.010849        0.258080    37.098850     2.306043          1369  82.819117
37                 3306      0.989164        0.420335   277.119080     5.477728          2808  84.936479
49                 2454      0.973691        0.453717    73.344260     2.237875          1978  80.603097
44                 4975      0.972023        0.327959    41.777138     2.357396          3384  68.020101

[12] TRAIN / VALIDATION / TEST ANALYSIS
----------------------------------------------------------------------------------------------------
            Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly       P95        P99
split
test               36824      1.465610        0.554552     73.34426  5.525621  19.381844
train             136265      0.811824        0.190110    557.88446  2.866686   7.116031
validation         30680      1.181386        0.620491    277.11908  4.234723   9.784349

[13] INVESTIGATION QUEUE
----------------------------------------------------------------------------------------------------
CRITICAL + HIGH: 2038

Distribution:
investigation_level
CRITICAL    1019
HIGH        1019
Name: count, dtype: int64

[14] FINAL TRANSACTION SUMMARY
----------------------------------------------------------------------------------------------------
total_transactions       : 203769
unique_transactions      : 203769
time_steps               : 49
min_time                 : 1
max_time                 : 49
critical                 : 1019
high                     : 1019
medium                   : 8151
low                      : 193580

[15] SAVING RESULTS
----------------------------------------------------------------------------------------------------
✓ Full results     : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_stress_test\bittrace_transaction_full_stress_test.csv
✓ Top-K analysis   : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_stress_test\bittrace_transaction_large_scale_topk.csv
✓ Thresholds       : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_stress_test\bittrace_transaction_large_scale_thresholds.csv
✓ Temporal         : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_stress_test\bittrace_transaction_large_scale_temporal.csv
✓ Split summary    : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_stress_test\bittrace_transaction_large_scale_split_summary.csv
✓ Investigation    : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_stress_test\bittrace_transaction_investigation_queue.csv
✓ Summary          : C:\Users\YASHIKA\Desktop\bit-trace\bittrace_transaction_stress_test\bittrace_transaction_large_scale_summary.csv


====================================================================================================
BIT-TRACE — LARGE-SCALE TRANSACTION TEST COMPLETE
====================================================================================================

Transactions tested       : 203,769
Unique transactions       : 203,769
Time steps                : 1–49

Models already used:
✓ Isolation Forest
✓ LOF
✓ Ensemble anomaly score

Features:
✓ Behavioral features
✓ Graph transaction features
✓ Temporal information

Testing:
✓ Full 203K transaction dataset
✓ Top-K anomaly ranking
✓ Threshold testing
✓ Temporal stress testing
✓ Investigation queue generation

P2P / network data:
✗ NOT USED

Labels:
✗ NOT USED FOR MODEL TRAINING
✓ Used only for post-hoc evaluation

Next:
Use the generated investigation queue
and dashboard data for transaction-level investigation.

====================================================================================================

In [52]:
# =============================================================================
# BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE TEST / STRESS EVALUATION
# =============================================================================

import os
import time
import gc
import numpy as np
import pandas as pd

from sklearn.metrics import roc_auc_score, average_precision_score

print("=" * 100)
print("BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE TEST")
print("=" * 100)

# -----------------------------------------------------------------------------
# 1. PATHS
# -----------------------------------------------------------------------------

BASE = r"C:\Users\YASHIKA\Desktop\bit-trace"

ANOMALY_PATH = os.path.join(
    BASE,
    "src",
    "ellipticpp_graph_behavioral_anomaly_results.csv"
)

CLASS_PATH = os.path.join(
    BASE,
    "EllipticPlusPlus",
    "Transactions Dataset",
    "txs_classes.csv"
)

OUTPUT_DIR = os.path.join(
    BASE,
    "bittrace_large_scale_test"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("\n[1] FILE CHECK")
print("-" * 80)

print("Anomaly results:", os.path.exists(ANOMALY_PATH))
print("Class labels   :", os.path.exists(CLASS_PATH))

if not os.path.exists(ANOMALY_PATH):
    raise FileNotFoundError(ANOMALY_PATH)

if not os.path.exists(CLASS_PATH):
    raise FileNotFoundError(CLASS_PATH)


# -----------------------------------------------------------------------------
# 2. LOAD EXISTING ANOMALY RESULTS
# -----------------------------------------------------------------------------

print("\n[2] LOADING EXISTING TRANSACTION RESULTS")
print("-" * 80)

start_time = time.perf_counter()

results = pd.read_csv(ANOMALY_PATH)

print("Shape:", results.shape)
print("Columns:", list(results.columns))

required_result_cols = [
    "txId",
    "Time step",
    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly",
    "split"
]

missing = [
    c for c in required_result_cols
    if c not in results.columns
]

if missing:
    raise ValueError(f"Missing columns in anomaly results: {missing}")

print("✓ Required columns verified")


# -----------------------------------------------------------------------------
# 3. LOAD CLASS LABELS
# -----------------------------------------------------------------------------

print("\n[3] LOADING CLASS LABELS")
print("-" * 80)

classes = pd.read_csv(CLASS_PATH)

classes.columns = [
    str(c).strip()
    for c in classes.columns
]

print("Shape:", classes.shape)
print("Columns:", list(classes.columns))

if "txId" not in classes.columns or "class" not in classes.columns:
    raise ValueError(
        "Class file must contain txId and class columns."
    )

classes = classes[["txId", "class"]].copy()

classes["txId"] = pd.to_numeric(
    classes["txId"],
    errors="coerce"
)

classes["class"] = pd.to_numeric(
    classes["class"],
    errors="coerce"
)

classes = classes.dropna(
    subset=["txId", "class"]
)

classes["txId"] = classes["txId"].astype(np.int64)
classes["class"] = classes["class"].astype(np.int8)

print("Class distribution:")
print(classes["class"].value_counts().sort_index())


# -----------------------------------------------------------------------------
# 4. MERGE
# -----------------------------------------------------------------------------

print("\n[4] MERGING RESULTS + LABELS")
print("-" * 80)

df = results.merge(
    classes,
    on="txId",
    how="left",
    validate="one_to_one"
)

missing_labels = df["class"].isna().sum()

print("Merged shape:", df.shape)
print("Missing labels:", missing_labels)

if missing_labels > 0:
    raise ValueError(
        f"{missing_labels} transactions have no class label."
    )

df["class"] = df["class"].astype(np.int8)

print("✓ Labels successfully attached")


# -----------------------------------------------------------------------------
# 5. SELECT TEST SET ONLY
# -----------------------------------------------------------------------------

print("\n[5] SELECTING FULL TEST SET")
print("-" * 80)

test_df = df[
    df["split"].astype(str).str.lower().eq("test")
].copy()

if len(test_df) == 0:
    raise ValueError(
        "No rows found with split='test'."
    )

test_df = test_df.sort_values(
    "ensemble_anomaly",
    ascending=False
).reset_index(drop=True)

print("Test transactions:", len(test_df))
print(
    "Test time range:",
    test_df["Time step"].min(),
    "to",
    test_df["Time step"].max()
)

print("\nTest class distribution:")
print(test_df["class"].value_counts().sort_index())


# -----------------------------------------------------------------------------
# 6. VERIFY ALL TEST TRANSACTIONS
# -----------------------------------------------------------------------------

print("\n[6] DATA QUALITY CHECK")
print("-" * 80)

score_cols = [
    "IF_anomaly",
    "LOF_anomaly",
    "ensemble_anomaly"
]

for col in score_cols:
    nan_count = test_df[col].isna().sum()
    inf_count = np.isinf(
        test_df[col].to_numpy(dtype=float)
    ).sum()

    print(
        f"{col:20s} | NaN={nan_count:,} | Inf={inf_count:,}"
    )

if test_df[score_cols].isna().any().any():
    raise ValueError("Missing anomaly scores detected.")

if np.isinf(
    test_df[score_cols]
    .to_numpy(dtype=float)
).any():
    raise ValueError("Infinite anomaly scores detected.")

print("✓ All test scores valid")


# -----------------------------------------------------------------------------
# 7. BASIC LARGE-SCALE STATISTICS
# -----------------------------------------------------------------------------

print("\n[7] LARGE-SCALE SCORE STATISTICS")
print("-" * 80)

stats = test_df[score_cols].describe().T

print(stats.to_string())


# -----------------------------------------------------------------------------
# 8. CLASS-WISE ANALYSIS
# -----------------------------------------------------------------------------

print("\n[8] CLASS-WISE TEST ANALYSIS")
print("-" * 80)

class_summary = (
    test_df
    .groupby("class")["ensemble_anomaly"]
    .agg(
        Samples="count",
        Mean="mean",
        Std="std",
        Min="min",
        Median="median",
        Max="max"
    )
)

print(class_summary.to_string())


# -----------------------------------------------------------------------------
# 9. CLASS-3 POST-HOC METRICS
# -----------------------------------------------------------------------------

print("\n[9] CLASS-3 POST-HOC EVALUATION")
print("-" * 80)

y_true = (
    test_df["class"].to_numpy() == 3
).astype(np.int8)

scores = test_df[
    "ensemble_anomaly"
].to_numpy(dtype=np.float64)

try:
    roc_auc = roc_auc_score(
        y_true,
        scores
    )

    pr_auc = average_precision_score(
        y_true,
        scores
    )

    print(f"ROC-AUC : {roc_auc:.4f}")
    print(f"PR-AUC  : {pr_auc:.4f}")

except Exception as e:
    roc_auc = np.nan
    pr_auc = np.nan

    print("Metric calculation failed:", e)


# -----------------------------------------------------------------------------
# 10. TOP-K ANALYSIS
# -----------------------------------------------------------------------------

print("\n[10] TOP-K LARGE-SCALE ANALYSIS")
print("-" * 80)

overall_class3_pct = (
    y_true.mean() * 100
)

top_k_values = [
    50,
    100,
    250,
    500,
    1000,
    2500,
    5000,
    10000,
    15000,
    20000
]

top_k_values = [
    k for k in top_k_values
    if k <= len(test_df)
]

topk_rows = []

for k in top_k_values:

    topk = test_df.head(k)

    class3_count = (
        (topk["class"] == 3)
        .sum()
    )

    class3_pct = (
        class3_count / k * 100
    )

    enrichment = (
        class3_pct /
        overall_class3_pct
    )

    topk_rows.append({
        "Top_K": k,
        "Transactions": k,
        "Class3_Count": int(class3_count),
        "Class3_%": class3_pct,
        "Overall_Class3_%": overall_class3_pct,
        "Enrichment": enrichment
    })

topk_df = pd.DataFrame(topk_rows)

print(
    topk_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# -----------------------------------------------------------------------------
# 11. UNSUPERVISED THRESHOLD ANALYSIS
# -----------------------------------------------------------------------------

print("\n[11] THRESHOLD / ALERT-VOLUME ANALYSIS")
print("-" * 80)

percentiles = [
    90,
    92,
    95,
    97,
    98,
    99,
    99.5,
    99.9
]

threshold_rows = []

for p in percentiles:

    threshold = np.percentile(
        scores,
        p
    )

    flagged = test_df[
        test_df["ensemble_anomaly"] >= threshold
    ]

    flagged_count = len(flagged)

    class3_count = (
        flagged["class"] == 3
    ).sum()

    class3_pct = (
        class3_count / flagged_count * 100
        if flagged_count > 0
        else 0
    )

    alert_rate = (
        flagged_count /
        len(test_df) * 100
    )

    threshold_rows.append({
        "Percentile": p,
        "Threshold": threshold,
        "Flagged": flagged_count,
        "Alert_Rate_%": alert_rate,
        "Class3_Count": int(class3_count),
        "Class3_%": class3_pct
    })

threshold_df = pd.DataFrame(
    threshold_rows
)

print(
    threshold_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# -----------------------------------------------------------------------------
# 12. TEMPORAL SCALABILITY ANALYSIS
# -----------------------------------------------------------------------------

print("\n[12] TEMPORAL TEST ANALYSIS")
print("-" * 80)

temporal_df = (
    test_df
    .groupby("Time step")
    .agg(
        Transactions=("txId", "count"),
        Mean_Anomaly=("ensemble_anomaly", "mean"),
        Median_Anomaly=("ensemble_anomaly", "median"),
        Max_Anomaly=("ensemble_anomaly", "max"),
        Class3_Count=("class", lambda x: (x == 3).sum())
    )
)

temporal_df["Class3_%"] = (
    temporal_df["Class3_Count"] /
    temporal_df["Transactions"] *
    100
)

temporal_df = temporal_df.sort_values(
    "Mean_Anomaly",
    ascending=False
)

print(
    temporal_df.to_string(
        float_format=lambda x: f"{x:.4f}"
    )
)


# -----------------------------------------------------------------------------
# 13. TOP 1000 TRANSACTIONS
# -----------------------------------------------------------------------------

print("\n[13] SAVING TOP SUSPICIOUS TRANSACTIONS")
print("-" * 80)

top1000 = test_df.head(
    min(1000, len(test_df))
).copy()

top1000_path = os.path.join(
    OUTPUT_DIR,
    "transaction_test_top1000.csv"
)

top1000.to_csv(
    top1000_path,
    index=False
)

print("✓", top1000_path)


# -----------------------------------------------------------------------------
# 14. SAVE ALL TEST TRANSACTIONS
# -----------------------------------------------------------------------------

all_test_path = os.path.join(
    OUTPUT_DIR,
    "transaction_test_all_36824.csv"
)

test_df.to_csv(
    all_test_path,
    index=False
)

print("✓", all_test_path)


# -----------------------------------------------------------------------------
# 15. SAVE TOP-K RESULTS
# -----------------------------------------------------------------------------

topk_path = os.path.join(
    OUTPUT_DIR,
    "transaction_test_topk_analysis.csv"
)

topk_df.to_csv(
    topk_path,
    index=False
)

print("✓", topk_path)


# -----------------------------------------------------------------------------
# 16. SAVE THRESHOLD RESULTS
# -----------------------------------------------------------------------------

threshold_path = os.path.join(
    OUTPUT_DIR,
    "transaction_test_threshold_analysis.csv"
)

threshold_df.to_csv(
    threshold_path,
    index=False
)

print("✓", threshold_path)


# -----------------------------------------------------------------------------
# 17. SAVE TEMPORAL RESULTS
# -----------------------------------------------------------------------------

temporal_path = os.path.join(
    OUTPUT_DIR,
    "transaction_test_temporal_analysis.csv"
)

temporal_df.to_csv(
    temporal_path
)

print("✓", temporal_path)


# -----------------------------------------------------------------------------
# 18. SAVE SUMMARY
# -----------------------------------------------------------------------------

elapsed = time.perf_counter() - start_time

summary = pd.DataFrame([{
    "Total_Test_Transactions": len(test_df),
    "Test_Time_Start": test_df["Time step"].min(),
    "Test_Time_End": test_df["Time step"].max(),
    "Class1_Count": int((test_df["class"] == 1).sum()),
    "Class2_Count": int((test_df["class"] == 2).sum()),
    "Class3_Count": int((test_df["class"] == 3).sum()),
    "Class3_Percentage": overall_class3_pct,
    "ROC_AUC_Class3": roc_auc,
    "PR_AUC_Class3": pr_auc,
    "Processing_Time_Seconds": elapsed
}])

summary_path = os.path.join(
    OUTPUT_DIR,
    "transaction_test_summary.csv"
)

summary.to_csv(
    summary_path,
    index=False
)

print("✓", summary_path)


# -----------------------------------------------------------------------------
# 19. FINAL REPORT
# -----------------------------------------------------------------------------

print("\n")
print("=" * 100)
print("BIT-TRACE — LARGE-SCALE TRANSACTION TEST COMPLETE")
print("=" * 100)

print(f"""
Transactions evaluated : {len(test_df):,}
Test time steps         : {test_df["Time step"].min()}–{test_df["Time step"].max()}

Class distribution:
  Class 1 : {(test_df["class"] == 1).sum():,}
  Class 2 : {(test_df["class"] == 2).sum():,}
  Class 3 : {(test_df["class"] == 3).sum():,}

Class-3 percentage      : {overall_class3_pct:.2f}%

ROC-AUC                 : {roc_auc:.4f}
PR-AUC                  : {pr_auc:.4f}

Processing time         : {elapsed:.2f} seconds

P2P / network data      : NOT USED
Transaction data        : USED
Graph transaction edges : USED
Behavioral features    : USED
Isolation Forest        : USED
LOF                     : USED
Ensemble                : USED

Outputs saved to:
{OUTPUT_DIR}
""")

print("=" * 100)

# Memory cleanup
gc.collect()

print("✓ Large-scale transaction-only test finished.")

====================================================================================================
BIT-TRACE — TRANSACTION-ONLY LARGE-SCALE TEST
====================================================================================================

[1] FILE CHECK
--------------------------------------------------------------------------------
Anomaly results: True
Class labels   : True

[2] LOADING EXISTING TRANSACTION RESULTS
--------------------------------------------------------------------------------
Shape: (203769, 6)
Columns: ['txId', 'Time step', 'IF_anomaly', 'LOF_anomaly', 'ensemble_anomaly', 'split']
✓ Required columns verified

[3] LOADING CLASS LABELS
--------------------------------------------------------------------------------
Shape: (203769, 2)
Columns: ['txId', 'class']
Class distribution:
class
1      4545
2     42019
3    157205
Name: count, dtype: int64

[4] MERGING RESULTS + LABELS
--------------------------------------------------------------------------------
Merged shape: (203769, 7)
Missing labels: 0
✓ Labels successfully attached

[5] SELECTING FULL TEST SET
--------------------------------------------------------------------------------
Test transactions: 36824
Test time range: 42 to 49

Test class distribution:
class
1      408
2     8433
3    27983
Name: count, dtype: int64

[6] DATA QUALITY CHECK
--------------------------------------------------------------------------------
IF_anomaly           | NaN=0 | Inf=0
LOF_anomaly          | NaN=0 | Inf=0
ensemble_anomaly     | NaN=0 | Inf=0
✓ All test scores valid

[7] LARGE-SCALE SCORE STATISTICS
--------------------------------------------------------------------------------
                    count      mean       std       min       25%       50%       75%         max
IF_anomaly        36824.0  0.580348  1.246904 -0.491169 -0.197767  0.070659  0.962363    6.932095
LOF_anomaly       36824.0  2.793503  8.104299 -0.436947 -0.034838  0.655908  2.425184  182.982900
ensemble_anomaly  36824.0  1.465610  3.478470 -0.442719  0.003511  0.554552  1.633087   73.344260

[8] CLASS-WISE TEST ANALYSIS
--------------------------------------------------------------------------------
       Samples      Mean       Std       Min    Median        Max
class
1          408  1.000417  2.481678 -0.423081  0.469885  36.514263
2         8433  2.565138  4.613926 -0.414446  1.533599  61.643950
3        27983  1.141037  2.990874 -0.442719  0.389322  73.344260

[9] CLASS-3 POST-HOC EVALUATION
--------------------------------------------------------------------------------
ROC-AUC : 0.2948
PR-AUC  : 0.6576

[10] TOP-K LARGE-SCALE ANALYSIS
--------------------------------------------------------------------------------
 Top_K  Transactions  Class3_Count  Class3_%  Overall_Class3_%  Enrichment
    50            50            22   44.0000           75.9912      0.5790
   100           100            40   40.0000           75.9912      0.5264
   250           250           101   40.4000           75.9912      0.5316
   500           500           296   59.2000           75.9912      0.7790
  1000          1000           612   61.2000           75.9912      0.8054
  2500          2500          1424   56.9600           75.9912      0.7496
  5000          5000          2826   56.5200           75.9912      0.7438
 10000         10000          5638   56.3800           75.9912      0.7419
 15000         15000          9050   60.3333           75.9912      0.7940
 20000         20000         13061   65.3050           75.9912      0.8594

[11] THRESHOLD / ALERT-VOLUME ANALYSIS
--------------------------------------------------------------------------------
 Percentile  Threshold  Flagged  Alert_Rate_%  Class3_Count  Class3_%
    90.0000     3.1830     3683       10.0016          2113   57.3717
    92.0000     3.8770     2946        8.0002          1704   57.8411
    95.0000     5.5256     1842        5.0022          1101   59.7720
    97.0000     7.9776     1105        3.0008           687   62.1719
    98.0000    11.8947      737        2.0014           445   60.3799
    99.0000    19.3818      369        1.0021           205   55.5556
    99.5000    24.2859      185        0.5024            85   45.9459
    99.9000    36.4521       37        0.1005            20   54.0541

[12] TEMPORAL TEST ANALYSIS
--------------------------------------------------------------------------------
           Transactions  Mean_Anomaly  Median_Anomaly  Max_Anomaly  Class3_Count  Class3_%
Time step
43                 5063        2.7242          0.9125      65.2826          3693   72.9409
45                 5598        1.4372          0.3988      54.4714          4377   78.1886
46                 3519        1.4050          0.8367      35.3901          2807   79.7670
42                 7140        1.3539          0.7080      53.9295          4986   69.8319
47                 5121        1.3396          0.5411      61.6439          4275   83.4798
48                 2954        1.1627          0.3501      37.8810          2483   84.0555
49                 2454        0.9737          0.4537      73.3443          1978   80.6031
44                 4975        0.9720          0.3280      41.7771          3384   68.0201

[13] SAVING TOP SUSPICIOUS TRANSACTIONS
--------------------------------------------------------------------------------
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\transaction_test_top1000.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\transaction_test_all_36824.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\transaction_test_topk_analysis.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\transaction_test_threshold_analysis.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\transaction_test_temporal_analysis.csv
✓ C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test\transaction_test_summary.csv


====================================================================================================
BIT-TRACE — LARGE-SCALE TRANSACTION TEST COMPLETE
====================================================================================================

Transactions evaluated : 36,824
Test time steps         : 42–49

Class distribution:
  Class 1 : 408
  Class 2 : 8,433
  Class 3 : 27,983

Class-3 percentage      : 75.99%

ROC-AUC                 : 0.2948
PR-AUC                  : 0.6576

Processing time         : 0.57 seconds

P2P / network data      : NOT USED
Transaction data        : USED
Graph transaction edges : USED
Behavioral features    : USED
Isolation Forest        : USED
LOF                     : USED
Ensemble                : USED

Outputs saved to:
C:\Users\YASHIKA\Desktop\bit-trace\bittrace_large_scale_test

====================================================================================================
✓ Large-scale transaction-only test finished.