In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

p2p_folder = "/content/drive/MyDrive/Bitcoin P2P Dataset"

print(os.listdir(p2p_folder))

['dataset.zip', 'processed']

In [ ]:
import glob
import os

zip_files = glob.glob(
    "/content/drive/MyDrive/Bitcoin P2P Dataset/*.zip"
)

for f in zip_files:
    size_gb = os.path.getsize(f) / (1024**3)
    print(f)
    print(f"Size: {size_gb:.2f} GB")

/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip
Size: 33.91 GB

In [ ]:
ZIP_PATH = zip_files[0]

print(ZIP_PATH)

/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip

In [ ]:
import zipfile

with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    files = z.namelist()

print("Number of files:", len(files))

for f in files:
    print(f)

Number of files: 38340
dataset_2020/
dataset_2020/crawl/
dataset_2020/crawl/20200215/
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:02:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv
dataset_2020/crawl/20200215/20200215-19:22:40.json
dataset_2020/crawl/20200215/20200215-09:46:51.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:43:00.csv
dataset_2020/crawl/20200215/20200215-14:54:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:23:21.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:50:50.csv
dataset_2020/crawl/20200215/20200215-02:38:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:02:30.csv
dataset_2020/crawl/20200215/20200215-10:39:11.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:50:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:22:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:03:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:14:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:14:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:34:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:11:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:46:40.csv
dataset_2020/crawl/20200215/20200215-19:38:40.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:34:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:26:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:26:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:31:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:22:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-11:39:11.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:22:30.csv
dataset_2020/crawl/20200215/20200215-03:42:30.json
dataset_2020/crawl/20200215/20200215-04:10:30.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-11:35:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-05:02:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-19:30:40.csv
dataset_2020/crawl/20200215/20200215-01:15:11.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-13:19:01.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:47:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:58:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:31:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:15:00.csv
dataset_2020/crawl/20200215/20200215-17:18:40.json
dataset_2020/crawl/20200215/20200215-02:11:00.json
dataset_2020/crawl/20200215/20200215-04:18:40.json
dataset_2020/crawl/20200215/20200215-12:39:01.json
dataset_2020/crawl/20200215/20200215-07:54:41.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:59:20.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:38:40.csv
dataset_2020/crawl/20200215/20200215-17:10:40.json
dataset_2020/crawl/20200215/20200215-14:43:11.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:06:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:10:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:06:50.csv
dataset_2020/crawl/20200215/20200215-13:26:50.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:07:00.csv
dataset_2020/crawl/20200215/20200215-11:15:00.json
dataset_2020/crawl/20200215/20200215-01:03:20.json
dataset_2020/crawl/20200215/20200215-13:35:00.json
dataset_2020/crawl/20200215/20200215-13:06:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:03:00.csv
dataset_2020/crawl/20200215/20200215-20:50:40.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:38:40.csv
dataset_2020/crawl/20200215/20200215-01:59:00.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:14:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:43:01.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:31:01.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-16:30:40.csv
dataset_2020/crawl/20200215/20200215-09:10:50.json
dataset_2020/crawl/20200215/20200215-08:26:30.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:10:41.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:18:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-21:30:41.csv
dataset_2020/crawl/20200215/20200215-00:43:11.json
dataset_2020/crawl/20200215/20200215-02:03:00.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-22:54:41.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:34:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:55:00.csv
dataset_2020/crawl/20200215/20200215-13:55:10.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:03:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:26:30.csv
dataset_2020/crawl/20200215/20200215-20:58:50.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:22:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:58:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:23:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:06:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:15:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:18:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:58:50.csv
dataset_2020/crawl/20200215/20200215-13:51:00.json
dataset_2020/crawl/20200215/20200215-01:47:10.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:26:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:06:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:59:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:22:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:31:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:11:20.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:10:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:38:50.csv
dataset_2020/crawl/20200215/20200215-10:47:11.json
dataset_2020/crawl/20200215/20200215-15:47:00.json
dataset_2020/crawl/20200215/20200215-20:46:41.json
dataset_2020/crawl/20200215/20200215-10:27:00.json
dataset_2020/crawl/20200215/20200215-03:15:00.json
dataset_2020/crawl/20200215/20200215-00:47:20.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:03:10.csv
dataset_2020/crawl/20200215/20200215-14:47:10.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:15:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:38:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:22:20.csv
dataset_2020/crawl/20200215/20200215-15:26:40.json
dataset_2020/crawl/20200215/20200215-20:22:50.json
dataset_2020/crawl/20200215/20200215-17:42:40.json
dataset_2020/crawl/20200215/20200215-05:30:30.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:35:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:03:20.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-22:34:41.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:06:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:34:31.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:18:41.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:42:41.csv
dataset_2020/crawl/20200215/20200215-15:18:50.json
dataset_2020/crawl/20200215/20200215-14:27:01.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:22:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:34:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:11:30.csv
dataset_2020/crawl/20200215/20200215-07:46:40.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:54:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-13:47:00.csv
dataset_2020/crawl/20200215/20200215-22:30:41.json
dataset_2020/crawl/20200215/20200215-12:59:10.json
dataset_2020/crawl/20200215/20200215-22:34:41.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:59:20.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:34:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:30:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:02:41.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:42:50.csv
dataset_2020/crawl/20200215/20200215-00:51:10.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:02:50.csv
dataset_2020/crawl/20200215/20200215-09:27:00.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:38:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-19:18:40.csv
dataset_2020/crawl/20200215/20200215-03:34:30.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-16:18:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:14:31.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:22:42.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:39:01.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-21:42:42.csv
dataset_2020/crawl/20200215/20200215-07:02:30.json
dataset_2020/crawl/20200215/20200215-23:42:42.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:06:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:07:00.csv
dataset_2020/crawl/20200215/20200215-01:55:00.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:46:50.csv
dataset_2020/crawl/20200215/20200215-19:06:51.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-19:18:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:42:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:03:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:30:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:10:50.csv
dataset_2020/crawl/20200215/20200215-06:43:01.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:46:51.csv
dataset_2020/crawl/20200215/20200215-23:46:41.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:10:40.csv
dataset_2020/crawl/20200215/20200215-21:30:41.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:06:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-19:58:40.csv
dataset_2020/crawl/20200215/20200215-06:14:41.json
dataset_2020/crawl/20200215/20200215-00:23:21.json
dataset_2020/crawl/20200215/20200215-23:30:51.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:30:41.csv
dataset_2020/crawl/20200215/20200215-21:02:41.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:58:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-16:26:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:39:20.csv
dataset_2020/crawl/20200215/20200215-22:14:51.json
dataset_2020/crawl/20200215/20200215-22:18:42.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-05:14:31.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:55:11.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:39:11.csv
dataset_2020/crawl/20200215/20200215-17:58:41.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:18:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-07:06:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-21:26:42.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:27:20.csv
dataset_2020/crawl/20200215/20200215-18:58:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:10:41.csv
dataset_2020/crawl/20200215/20200215-06:55:00.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:23:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:43:01.csv
dataset_2020/crawl/20200215/20200215-07:34:40.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:54:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:51:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-07:58:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:43:21.csv
dataset_2020/crawl/20200215/20200215-20:34:31.json
dataset_2020/crawl/20200215/20200215-08:34:31.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:15:10.csv
dataset_2020/crawl/20200215/20200215-00:19:30.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:26:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:46:51.csv
dataset_2020/crawl/20200215/20200215-17:46:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:46:41.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:11:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:19:20.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:14:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:18:40.csv
dataset_2020/crawl/20200215/20200215-05:10:30.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:07:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:06:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:47:10.csv
dataset_2020/crawl/20200215/20200215-02:14:50.json
dataset_2020/crawl/20200215/20200215-06:22:30.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:46:41.csv
dataset_2020/crawl/20200215/20200215-21:42:42.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-21:18:41.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:27:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:43:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-15:34:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:14:41.csv
dataset_2020/crawl/20200215/20200215-10:35:01.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-13:15:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:50:20.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:02:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:15:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:58:41.csv
dataset_2020/crawl/20200215/20200215-07:10:40.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:02:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-05:26:30.csv
dataset_2020/crawl/20200215/20200215-03:06:50.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:30:31.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-07:42:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:54:41.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:46:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:15:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-13:23:10.csv
dataset_2020/crawl/20200215/20200215-04:50:41.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:27:20.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:27:00.csv
dataset_2020/crawl/20200215/20200215-00:35:20.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:06:30.csv
dataset_2020/crawl/20200215/20200215-03:50:30.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:51:10.csv
dataset_2020/crawl/20200215/20200215-12:23:01.json
dataset_2020/crawl/20200215/20200215-06:46:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:50:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-23:38:41.csv
dataset_2020/crawl/20200215/20200215-02:34:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:34:40.csv
dataset_2020/crawl/20200215/20200215-04:38:30.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-22:38:41.csv
dataset_2020/crawl/20200215/20200215-15:30:51.json
dataset_2020/crawl/20200215/20200215-21:22:52.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-19:22:40.csv
dataset_2020/crawl/20200215/20200215-00:31:10.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:50:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:31:10.csv
dataset_2020/crawl/20200215/20200215-09:58:51.json
dataset_2020/crawl/20200215/20200215-05:50:20.json
dataset_2020/crawl/20200215/20200215-13:43:00.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-04:02:31.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:02:40.csv
dataset_2020/crawl/20200215/20200215-19:02:40.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:38:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:58:40.csv
dataset_2020/crawl/20200215/20200215-03:22:40.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-15:38:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:34:31.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:18:31.csv
dataset_2020/crawl/20200215/20200215-21:58:42.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-23:50:41.csv
dataset_2020/crawl/20200215/20200215-14:35:10.json
dataset_2020/crawl/20200215/20200215-19:54:40.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-19:46:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-13:23:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-23:22:42.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:47:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:06:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-16:42:40.csv
dataset_2020/crawl/20200215/20200215-08:10:40.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-21:46:41.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-15:26:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:23:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:14:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:22:40.csv
dataset_2020/crawl/20200215/20200215-22:46:41.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:35:20.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:11:10.csv
dataset_2020/crawl/20200215/20200215-19:14:51.json
dataset_2020/crawl/20200215/20200215-16:46:30.json
dataset_2020/crawl/20200215/20200215-21:26:42.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-19:54:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:58:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:14:41.csv
dataset_2020/crawl/20200215/20200215-21:46:41.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-11:55:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-13:43:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:07:10.csv
dataset_2020/crawl/20200215/20200215-23:22:42.json
dataset_2020/crawl/20200215/20200215-21:54:51.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:06:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-16:10:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:42:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-23:18:41.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:10:30.csv
dataset_2020/crawl/20200215/20200215-04:22:40.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:55:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-21:26:42.csv
dataset_2020/crawl/20200215/20200215-13:47:00.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:50:40.csv
dataset_2020/crawl/20200215/20200215-03:30:40.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:26:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:34:31.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:27:00.csv

In [ ]:
import zipfile

with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    for info in z.infolist():
        print(
            f"{info.filename:60} "
            f"{info.file_size / (1024**3):8.3f} GB"
        )

dataset_2020/                                                   0.000 GB
dataset_2020/crawl/                                             0.000 GB
dataset_2020/crawl/20200215/                                    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:02:30.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-19:22:40.json              0.001 GB
dataset_2020/crawl/20200215/20200215-09:46:51.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:43:00.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-14:54:50.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:23:21.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:50:50.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-02:38:50.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:02:30.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-10:39:11.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:50:50.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:22:40.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:03:00.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:14:50.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:14:40.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:34:40.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:11:00.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:46:40.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-19:38:40.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:34:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:26:50.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:26:40.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:31:10.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:22:50.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-11:39:11.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:22:30.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-03:42:30.json              0.001 GB
dataset_2020/crawl/20200215/20200215-04:10:30.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-11:35:00.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-05:02:30.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-19:30:40.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-01:15:11.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-13:19:01.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:47:10.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:58:30.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:31:00.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:15:00.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-17:18:40.json              0.001 GB
dataset_2020/crawl/20200215/20200215-02:11:00.json              0.001 GB
dataset_2020/crawl/20200215/20200215-04:18:40.json              0.001 GB
dataset_2020/crawl/20200215/20200215-12:39:01.json              0.001 GB
dataset_2020/crawl/20200215/20200215-07:54:41.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:59:20.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:38:40.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-17:10:40.json              0.001 GB
dataset_2020/crawl/20200215/20200215-14:43:11.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:06:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:10:40.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:06:50.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-13:26:50.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:07:00.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-11:15:00.json              0.001 GB
dataset_2020/crawl/20200215/20200215-01:03:20.json              0.001 GB
dataset_2020/crawl/20200215/20200215-13:35:00.json              0.001 GB
dataset_2020/crawl/20200215/20200215-13:06:50.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:03:00.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-20:50:40.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:38:40.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-01:59:00.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:14:50.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:43:01.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:31:01.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-16:30:40.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-09:10:50.json              0.001 GB
dataset_2020/crawl/20200215/20200215-08:26:30.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:10:41.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:18:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-21:30:41.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-00:43:11.json              0.001 GB
dataset_2020/crawl/20200215/20200215-02:03:00.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-22:54:41.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:34:40.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:55:00.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-13:55:10.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:03:00.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:26:30.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-20:58:50.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:22:50.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:58:30.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:23:10.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:06:50.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:15:00.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:18:40.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:58:50.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-13:51:00.json              0.001 GB
dataset_2020/crawl/20200215/20200215-01:47:10.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:26:30.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:06:50.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:59:10.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:22:40.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:31:10.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:11:20.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:10:40.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:38:50.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-10:47:11.json              0.001 GB
dataset_2020/crawl/20200215/20200215-15:47:00.json              0.001 GB
dataset_2020/crawl/20200215/20200215-20:46:41.json              0.001 GB
dataset_2020/crawl/20200215/20200215-10:27:00.json              0.001 GB
dataset_2020/crawl/20200215/20200215-03:15:00.json              0.001 GB
dataset_2020/crawl/20200215/20200215-00:47:20.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:03:10.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-14:47:10.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:15:00.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:38:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:22:20.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-15:26:40.json              0.001 GB
dataset_2020/crawl/20200215/20200215-20:22:50.json              0.001 GB
dataset_2020/crawl/20200215/20200215-17:42:40.json              0.001 GB
dataset_2020/crawl/20200215/20200215-05:30:30.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:35:10.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:03:20.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-22:34:41.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:06:50.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:34:31.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:18:41.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:42:41.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-15:18:50.json              0.001 GB
dataset_2020/crawl/20200215/20200215-14:27:01.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:22:40.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:34:30.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:11:30.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-07:46:40.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:54:40.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-13:47:00.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-22:30:41.json              0.001 GB
dataset_2020/crawl/20200215/20200215-12:59:10.json              0.001 GB
dataset_2020/crawl/20200215/20200215-22:34:41.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:59:20.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:34:30.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:30:50.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:02:41.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:42:50.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-00:51:10.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:02:50.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-09:27:00.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:38:30.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-19:18:40.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-03:34:30.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-16:18:40.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:14:31.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:22:42.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:39:01.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-21:42:42.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-07:02:30.json              0.001 GB
dataset_2020/crawl/20200215/20200215-23:42:42.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:06:30.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:07:00.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-01:55:00.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:46:50.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-19:06:51.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-19:18:40.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:42:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:03:00.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:30:50.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:10:50.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-06:43:01.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:46:51.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-23:46:41.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:10:40.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-21:30:41.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:06:50.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-19:58:40.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-06:14:41.json              0.001 GB
dataset_2020/crawl/20200215/20200215-00:23:21.json              0.001 GB
dataset_2020/crawl/20200215/20200215-23:30:51.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:30:41.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-21:02:41.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:58:50.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-16:26:40.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:39:20.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-22:14:51.json              0.001 GB
dataset_2020/crawl/20200215/20200215-22:18:42.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-05:14:31.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:55:11.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:39:11.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-17:58:41.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:18:40.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-07:06:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-21:26:42.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:27:20.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-18:58:50.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:10:41.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-06:55:00.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:23:00.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:43:01.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-07:34:40.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:54:40.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:51:10.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-07:58:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:43:21.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-20:34:31.json              0.001 GB
dataset_2020/crawl/20200215/20200215-08:34:31.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:15:10.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-00:19:30.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:26:50.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:46:51.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-17:46:50.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-22:46:41.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:11:00.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:19:20.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:14:40.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:18:40.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-05:10:30.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:07:10.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-09:06:50.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:47:10.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-02:14:50.json              0.001 GB
dataset_2020/crawl/20200215/20200215-06:22:30.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:46:41.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-21:42:42.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-21:18:41.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:27:10.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:43:00.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-15:34:50.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:14:41.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-10:35:01.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-13:15:00.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:50:20.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:02:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:15:00.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-23:58:41.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-07:10:40.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:02:40.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-05:26:30.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-03:06:50.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:30:31.csv    0.000 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-07:42:30.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:54:41.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:46:40.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:15:00.csv    0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-13:23:10.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-04:50:41.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:27:20.csv    0.000 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:27:00.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-00:35:20.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:06:30.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-03:50:30.json              0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:51:10.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-12:23:01.json              0.001 GB
dataset_2020/crawl/20200215/20200215-06:46:50.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:50:30.csv    0.001 GB
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-23:38:41.csv    0.000 GB
dataset_2020/crawl/20200215/20200215-02:34:50.json              0.001 GB
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:34:40.csv    0.001 GB
dataset_2020/crawl/20200215/20200215-04:38:30.json              0.001 GB

In [ ]:
import zipfile
from collections import Counter
from pathlib import PurePosixPath

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    names = z.namelist()

print("Total files:", len(names))

# File extensions
extensions = Counter(
    PurePosixPath(name).suffix.lower()
    for name in names
    if not name.endswith("/")
)

print("\nFile types:")
for ext, count in extensions.most_common():
    print(f"{ext or '[no extension]':10} {count:,}")

Total files: 38340

File types:
.csv       18,962
.json      18,841
.bz2       481

In [ ]:
from collections import Counter

top_dirs = Counter()

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    for name in z.namelist():
        parts = name.split("/")
        if len(parts) >= 2:
            top_dirs[parts[0]] += 1

print("Top-level directories:")
for directory, count in top_dirs.items():
    print(f"{directory:30} {count:,}")

Top-level directories:
dataset_2020                   38,340

In [ ]:
with zipfile.ZipFile(ZIP_PATH, "r") as z:
    for name in z.namelist():
        if name.count("/") <= 2:
            print(name)

dataset_2020/
dataset_2020/crawl/
dataset_2020/export/

In [ ]:
from collections import Counter
import zipfile

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    crawl_files = []
    export_files = []

    for name in z.namelist():
        if name.endswith("/"):
            continue

        if name.startswith("dataset_2020/crawl/"):
            crawl_files.append(name)

        elif name.startswith("dataset_2020/export/"):
            export_files.append(name)

print("Crawl files :", len(crawl_files))
print("Export files:", len(export_files))

print("\nCrawl examples:")
for x in crawl_files[:20]:
    print(x)

print("\nExport examples:")
for x in export_files[:20]:
    print(x)

Crawl files : 28924
Export files: 9360

Crawl examples:
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:02:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv
dataset_2020/crawl/20200215/20200215-19:22:40.json
dataset_2020/crawl/20200215/20200215-09:46:51.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:43:00.csv
dataset_2020/crawl/20200215/20200215-14:54:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:23:21.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:50:50.csv
dataset_2020/crawl/20200215/20200215-02:38:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:02:30.csv
dataset_2020/crawl/20200215/20200215-10:39:11.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:50:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:22:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:03:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:14:50.csv

Export examples:
dataset_2020/export/20200207/20200207-16:07:21.json
dataset_2020/export/20200207/20200207-02:11:36.json
dataset_2020/export/20200207/20200207-05:11:20.json
dataset_2020/export/20200207/20200207-09:39:05.json
dataset_2020/export/20200207/20200207-13:11:47.json
dataset_2020/export/20200207/20200207-21:23:49.json
dataset_2020/export/20200207/20200207-03:03:39.json
dataset_2020/export/20200207/20200207-02:15:37.json
dataset_2020/export/20200207/20200207-21:51:36.json
dataset_2020/export/20200207/20200207-20:43:39.json
dataset_2020/export/20200207/20200207-17:35:32.json
dataset_2020/export/20200207/20200207-22:51:51.json
dataset_2020/export/20200207/20200207-00:23:40.json
dataset_2020/export/20200207/20200207-23:19:38.json
dataset_2020/export/20200207/20200207-09:10:58.json
dataset_2020/export/20200207/20200207-06:23:17.json
dataset_2020/export/20200207/20200207-18:11:21.json
dataset_2020/export/20200207/20200207-12:03:30.json
dataset_2020/export/20200207/20200207-19:35:32.json
dataset_2020/export/20200207/20200207-21:59:48.json

In [ ]:
from collections import Counter
from pathlib import PurePosixPath
import zipfile

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    crawl_ext = Counter()
    export_ext = Counter()

    for name in z.namelist():

        if name.endswith("/"):
            continue

        ext = PurePosixPath(name).suffix.lower()

        if name.startswith("dataset_2020/crawl/"):
            crawl_ext[ext] += 1

        elif name.startswith("dataset_2020/export/"):
            export_ext[ext] += 1

print("CRAWL:")
for ext, count in crawl_ext.most_common():
    print(f"{ext or '[no extension]':10} {count:,}")

print("\nEXPORT:")
for ext, count in export_ext.most_common():
    print(f"{ext or '[no extension]':10} {count:,}")

CRAWL:
.csv       18,962
.json      9,481
.bz2       481

EXPORT:
.json      9,360

In [ ]:
import zipfile

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    crawl_sizes = []
    export_sizes = []

    for info in z.infolist():

        if info.is_dir():
            continue

        if info.filename.startswith("dataset_2020/crawl/"):
            crawl_sizes.append((info.file_size, info.filename))

        elif info.filename.startswith("dataset_2020/export/"):
            export_sizes.append((info.file_size, info.filename))

print("CRAWL total uncompressed:",
      sum(x[0] for x in crawl_sizes) / (1024**3), "GB")

print("EXPORT total uncompressed:",
      sum(x[0] for x in export_sizes) / (1024**3), "GB")

print("\nLargest CRAWL files:")
for size, name in sorted(crawl_sizes, reverse=True)[:20]:
    print(f"{size/(1024**2):10.2f} MB  {name}")

print("\nLargest EXPORT files:")
for size, name in sorted(export_sizes, reverse=True)[:20]:
    print(f"{size/(1024**2):10.2f} MB  {name}")

CRAWL total uncompressed: 35.031557420268655 GB
EXPORT total uncompressed: 19.09837471321225 GB

Largest CRAWL files:
    211.07 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-06:10:28.pickle.bz2
    205.57 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-05:43:45.pickle.bz2
    188.34 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-02:59:48.pickle.bz2
    187.93 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-04:23:20.pickle.bz2
    178.04 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-15:19:08.pickle.bz2
    177.40 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-01:37:53.pickle.bz2
    176.01 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-18:07:24.pickle.bz2
    172.75 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-15:55:08.pickle.bz2
    172.00 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-00:02:19.pickle.bz2
    171.71 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-09:54:00.pickle.bz2
    170.33 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-10:06:55.pickle.bz2
    169.20 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-04:09:45.pickle.bz2
    168.69 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-13:42:43.pickle.bz2
    167.80 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-11:19:26.pickle.bz2
    167.40 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-06:46:24.pickle.bz2
    166.24 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-20:23:55.pickle.bz2
    165.82 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-11:32:01.pickle.bz2
    164.31 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-21:21:46.pickle.bz2
    163.88 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-19:10:04.pickle.bz2
    162.96 MB  dataset_2020/crawl/20200709/nodes_per_getADDR_20200709-19:22:49.pickle.bz2

Largest EXPORT files:
      2.19 MB  dataset_2020/export/20200210/20200210-02:03:32.json
      2.19 MB  dataset_2020/export/20200209/20200209-23:19:26.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:11:25.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:39:53.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:47:55.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:07:34.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:23:38.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:27:39.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:19:47.json
      2.18 MB  dataset_2020/export/20200210/20200210-01:59:21.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:43:44.json
      2.18 MB  dataset_2020/export/20200210/20200210-20:39:46.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:51:26.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:35:42.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:59:38.json
      2.18 MB  dataset_2020/export/20200210/20200210-02:15:36.json
      2.18 MB  dataset_2020/export/20200209/20200209-21:15:21.json
      2.18 MB  dataset_2020/export/20200210/20200210-01:55:20.json
      2.18 MB  dataset_2020/export/20200210/20200210-03:15:43.json
      2.18 MB  dataset_2020/export/20200209/20200209-23:11:14.json

In [ ]:
import zipfile
from collections import Counter
from pathlib import PurePosixPath

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    crawl_csvs = [
        name for name in z.namelist()
        if name.startswith("dataset_2020/crawl/")
        and name.lower().endswith(".csv")
    ]

print("Total crawl CSV files:", len(crawl_csvs))

# File-name patterns
patterns = Counter()

for name in crawl_csvs:
    filename = PurePosixPath(name).name

    if filename.startswith("nodes_per_getADDR"):
        patterns["nodes_per_getADDR"] += 1
    elif filename.startswith("up_nodes_per_seconds"):
        patterns["up_nodes_per_seconds"] += 1
    else:
        patterns["other"] += 1

print("\nCSV categories:")
for k, v in patterns.items():
    print(f"{k:25} {v:,}")

print("\nExample nodes_per_getADDR:")
for x in [f for f in crawl_csvs if "nodes_per_getADDR" in f][:10]:
    print(x)

print("\nExample up_nodes_per_seconds:")
for x in [f for f in crawl_csvs if "up_nodes_per_seconds" in f][:10]:
    print(x)

Total crawl CSV files: 18962

CSV categories:
nodes_per_getADDR         9,481
up_nodes_per_seconds      9,481

Example nodes_per_getADDR:
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:02:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:43:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:23:21.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:02:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:34:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:46:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:26:50.csv

Example up_nodes_per_seconds:
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:50:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:50:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:22:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:03:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:14:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:14:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:11:00.csv

In [ ]:
import zipfile

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    sample_file = next(
        name for name in z.namelist()
        if name.startswith("dataset_2020/crawl/")
        and "nodes_per_getADDR" in name
        and name.lower().endswith(".csv")
    )

    print("Selected file:")
    print(sample_file)

    with z.open(sample_file) as f:

        # Read raw bytes from the beginning
        raw = f.read(10000)

print("\nFirst 10,000 bytes preview:\n")
print(raw.decode("utf-8", errors="replace"))

Selected file:
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv

First 10,000 bytes preview:

1,9307dbb2274694ae6954bbf2144a15e9cfb2006161b38c4194be195f9602f331-192.81.210.0-8333-1037,233,220,208,233
2,a7dbb134085d885f8cc5d50d7b2683e95e06a4873fc26dc431984b21c7a27b81-134.209.254.0-8333-1037,265,132,-1,265
3,ade1db93214bcb4a242f177f703bfea173c3caa4449c59f1fe02408518507d21-134.209.230.0-8333-1037,-1,-1,-1
4,e776487445f0166d3a31de569332da087a57a126f9431743f6789c000139de50-54.254.233.0-8333-1037,317,317,317
5,19ef04f5c60c33afa8206b01fad7862c450ed1258499e9a31409fb1b42f403d5-54.245.199.0-8333-1037,333,166,333,-1
6,c26a27a5799c6dd5f4364a38668c2d57240c77c5add9e362bd3bff68eb3e1219-34.222.156.0-8333-1037,-1,-1,-1
7,c2b990ea8fad9df3d6b54c985ac4252cc1146037fba13bf363a6612324aadb80-13.229.122.0-8333-1037,-1,-1,-1
8,69adac5843c8acf1986614a0115acc7053468303c3b50afcd2dd2d95317a46ea-46.101.132.0-8333-1037,-1,-1,-1
9,7df313e1ec6560109dccc5ccecd3c8c1ee0012254fd640e4a15d54a92a0e9bc4-47.254.152.0-8333-1037,-1,-1,-1,-1
10,2de8a7f629f79a8779f8ee394cc30d0cd20d228f4c1c0a38592da65abf05a9be-88.198.68.0-8333-1033,-1,-1,-1,-1
11,d86671939820d9b2e93beeb25ad47977b63692e524a93482c205ad35b6648896-178.84.168.0-8333-1037,-1,-1,-1
12,c13e5fe4a3e332013a2fac40032b82ebb385135acda6157589bda1540475f288-73.38.249.0-8333-1037,-1,-1,-1
13,5ce162e726231a36c027c3ef971ada0c1481ce39dbce1ee04406c752d19358a7-73.92.253.0-8333-1037,-1,-1,-1
14,8998d95bc4c4c52cccbf05e12531784f7cd1257115319fa72695f3403692437a-193.70.32.0-8333-13,-1,-1,-1
15,af3ddf58f91b6e74e31af412bbb133c4cd6643962328b575076a5027fdb207b1-138.201.204.0-8333-1036,-1,-1,-1,-1
16,67bd9b11bbbcab70d8604de19f5985e5773e573a114b23a1e56aabdf77bdab7e-190.2.150.0-8333-13,-1,-1,-1,-1
17,ec844a3ff4f5bb48f7f6a628b37442e807ffe5ebe706a713448d5e4ab592ecfc-94.102.57.0-8333-1037,-1,-1,-1,-1
18,a5cd1c693a26e3553138e28b98b4b4ebc997d201d8f396422c1eaa59425468d2-217.160.185.0-8333-1037,-1,-1,-1,-1
19,e3095ea4b27d54ff7351c1fd185cbe74a8717a96d695574aa73fced8a7c412ab-45.63.59.0-8333-1032,-1,-1,-1
20,f8bc5ccfabfe1da90d12cecf2ca71d1db1d8abf9f1d945056990acacc9b3dce8-78.46.128.0-8333-13,-1,-1,-1,-1
21,fe6aacc7650b9177e880306d2349f76b9a18512de9aad54abfb8504868b62340-159.69.167.0-8333-1033,-1,-1,-1,-1,-1
22,f231d776a72e5bcfbcd4d5b7727186513478e1988fe841716d32cc92fe6a4668-188.193.141.0-8333-1037,-1,-1,-1
23,655ea54b96a964741cfe84984a3714c17d35550da5b39ca3f45e1296f2b63da3-52.90.231.0-8333-1033,-1,-1,-1,-1
24,401e62e688c55e310185b240963c304fffd2a837754edb3c79c77a41b3e8fc31-178.162.210.0-8333-1037,-1,-1,-1
25,5b2e004967d6224714a21c043976b1c3fdec40286be8a331b94690f531ce0201-78.46.85.0-8333-1037,-1,-1,-1
26,4023b2370756941d4859e5e2cd9ddc90214d4a00d7334e252ae8f5cae1b460d3-185.107.15.0-8333-1037,-1,-1,-1
27,d1af70cd8c9468c5443fa54cdafbb9ce1767a2a7329cb2f11e7194082e7138ee-92.118.149.0-8333-1037,-1,-1,-1
28,8a74eb27bb8ca7a5849e42c4234173a5bdc766ccbecd5ff276d371bdccaa6a70-84.28.199.0-8333-1037,-1,-1,-1
29,554f40b42d8be122a493886593c21dea99840fa4e41db001b774dc1732b7df2c-188.40.136.0-8333-1037,-1,-1,-1,-1
30,1e77ab6c0b8d10c331da8f43c8a33e93d71f2f9511e6b8792d5aac117f5513f4-158.174.131.0-8333-1037,-1,-1,-1
31,bf322eb2ff445a89332497e3f3a7e97cd4012279c8eb660111e4cbaabdfc4bed-5.9.67.0-8333-13,132,66,-1,132
32,2f2f01fbc10db3ca02a48551b710579250530d8437407542502c3ce9dbf1da5f-169.48.163.0-8333-13,-1,-1,-1
33,e83eda77d85dc06835d4dee1221fc8f585fcf22ef5ebf0df7810bef81288f286-192.207.12.0-8333-1037,-1,-1,-1
34,ecdc6f603b6fcbd2c1357dfe61efa6c999330e30b0bfe9fcff214e2ea32b4443-213.174.156.0-8333-1037,142,70,-1,142
35,a783232337296c7c9508dcb81a855712dc542de189ebdd21a9ff8b997fa458ac-205.196.146.0-8333-1037,-1,-1,-1
36,6e2c0d1deb8efed748424d0b5183840a22bad7d6389d3dd71f02146e3b28e16d-13.209.125.0-8333-1037,-1,-1,-1
37,f5baf36e41a339787a1fbec23560d1f35aa0a354b2554177204ff0e552e83061-173.254.210.0-8333-1033,-1,-1,-1,-1
38,a02f3fe5fd639d0e81137b77d882e6a832e3d8129adada7a718f924d08568f7c-47.52.201.0-8333-1037,-1,-1,-1
39,80963744e19a466a50ed99d05a84445457af8c98af337c7249b587dc5b2d3324-5.39.80.0-8333-1033,-1,-1,-1,-1
40,1c2c3db8e3c6536753e70d69f03fb46e31c5b471057043c6fbe622e2d2342f19-104.156.227.0-8333-13,-1,-1,-1,-1,-1
41,a192533d555773706d33ac3effa6f014395feef84ea6511e3720b966f7426e45-52.74.250.0-8333-1037,-1,-1,-1
42,390cb791de3450a486f83e78a71e77816814833428a309e79bedca2c7233a9fb-100.11.88.0-8333-1037,-1,-1,-1
43,8b3f4e0ed83710550b6e4eb86fbd62fb6e97897e8c166af0032cb7468068c3a4-54.178.155.0-8333-13,-1,-1,-1
44,5abd6e2a29cf766519c8e0447881b6fa74640317fdf914b09015a41e9c33a1e8-173.75.1.0-8333-1037,-1,-1,-1
45,13ce66e217bf1621cfb240b5acc63d05d580d12a01b017ed39275b427dda73f0-96.126.123.0-8333-1033,72,36,72,-1
46,ecab7afc05a074c4cdf2723138d3fdd52c32ec48106fe147b8ac9625dbe83f62-37.187.127.0-8333-1037,-1,-1,-1,-1
47,eb9bebdc6bac34155e778fdec4d539b40f7ac6be7064bc52dcbd6daa480518a8-121.254.175.0-8333-1037,-1,-1,-1,-1
48,ae497e41ea03d07ccd6ac8aaaf3781e48d2463cec902492f40520b73c2733dfa-194.109.20.0-8333-13,-1,-1,-1,-1
49,c2c447904c2a0c783c639909afe0230c55b917959c45cd058e3ed2d02b180933-140.82.31.0-8333-1036,-1,-1,-1,-1
50,ce0cd712425c31defbfd7c03e0f953b5918c734c6828c87018fb36bdb2304aab-206.189.109.0-8333-1036,-1,-1,-1,-1
51,cad5716d97285fc330e8c8b491366085f9ce178c7f6914c8e510be12fe202d0f-85.215.9.0-8333-1037,-1,-1,-1
52,c67f9126b0dd4933d6b52e8540af7fd588664d3d756f90167e11be375cd25822-210.209.72.0-8333-13,-1,-1,-1
53,02e997ea7501c81607f25abe2aa4e8c5526ea6092ad74e22fa05a33a71c8fff4-18.219.57.0-8333-1033,109,109,109
54,0056d0131f9608b6c2a8094eaa7fa45b30fe64f3023321b795015b04a4146f0f-173.249.3.0-8333-1037,-1,-1,-1
55,8ed73872495f6a2b78986291d8bdf4745db55aeeda330cacb048e25312f5c96f-47.91.89.0-8333-13,-1,-1,-1,-1
56,906565d5f6a74ed066b2a306ebae5505124246af21f9129c5e27aab39f8d9c59-78.129.236.0-8333-1036,-1,-1,-1,-1
57,7ac34bb9e90df16c747c2ab51551f63c4a629e3575cb20820947e4e842504fe3-176.9.51.0-8333-1037,-1,-1,-1,-1,-1
58,4c0a53e8804a7cbbf8d9c04adf272d77fd89443a7f2a4d64ee8050fd05d999f9-88.99.107.0-8333-1036,-1,-1,-1,-1,-1
59,8f37d822e5289f97fdd82a20266a28ad378ffe3e2cd18cabc3f666d1517ce5ce-94.228.214.0-8333-1037,-1,-1,-1
60,d86b4f20bffa8b35ecb94ddeb3c0438ceed1b83c1ece024947c5f24b8132595a-18.222.229.0-8333-1037,-1,-1,-1
61,8571d328e34fdd9c96b577abcf54a4e64eb8b483af60901e5c5c49c67cbaed3a-108.219.81.0-8333-1037,-1,-1,-1
62,b9faeeeff823bc3f61f2e8c6a68ca3cbb2e7f3aa9fa8b813978aa9c83c4a4e94-82.181.198.0-8333-1033,-1,-1,-1,-1
63,18cd620d1714d3d86a30b6434b70341a0509e3c63f636a243cd6d4aaa60d8e57-47.103.94.0-8333-1037,-1,-1,-1
64,ccde4f89e015291dcfa4ad065667ece6ffdd71419299727b60a92646bd6ba52f-87.233.181.0-8333-1036,-1,-1,-1,-1
65,261a1648050173f999c8595e53f6b9ccecb080cfdccb59333f5bdb73585b2859-82.64.45.0-8333-1037,-1,-1,-1
66,4b5730096c656cc4ea011d5e8c5b1005b83cdd0af668d9835276447f157bc89d-51.254.79.0-8333-1033,-1,-1,-1
67,bb0588f9bd479f02448dad954615fb840916b02e61dfc910debaf8ee9223ff87-104.57.178.0-8333-1037,-1,-1,-1,-1,-1
68,42c7fc621fae157cc6614ad1e873b6c198d4a490b0703a3c256af7e91794e4cf-13.229.62.0-8333-13,-1,-1,-1,-1,-1
69,e7bd6310ba0103307c67c561b5e6eeca94b59d48260d2c78161bd4b10292f544-185.88.29.0-8333-1037,-1,-1,-1,-1
70,6b93ec23e397ebd93cc90810e9cbbffa99fc07c90eae63ff71d4a0f17e55b091-136.33.238.0-8333-1037,-1,-1,-1
71,55212150f955ef6984853dc1ceffd37dfcde93cbb0162e8f639c3dfdf6a230f7-51.68.28.0-8333-1037,-1,-1,-1
72,6e6a6899d41da32eea72b0be79c25c47403a2399669d9a9c23774d4064a1e0ef-211.110.66.0-8333-1037,-1,-1,-1,-1
73,bc5d64456137dae75d79965d067f8d6ccba28577f2d7d950582a48c14b62bbf5-85.75.70.0-8333-1037,-1,-1,-1
74,8a5eeeda716a10d9bfa26a8ad9d6ecbfe2edae8d8d4153e929997224c84daafe-46.87.9.0-8333-1037,-1,-1,-1
75,f8dee595cdb05c6f99fd909112aed4ebdf45b3fd1d7ce6b08d12e952a7c37423-192.241.137.0-8333-1037,-1,-1,-1
76,4336d41a5101a42d70607fa9c2f3969cac05facb24968500ffecb1b96c317dad-195.0.203.0-8333-1037,-1,-1,-1,-1
77,23aa4b143067a4e6ee67c37b32485f122105e169ecf82eb6924d88fb832153d3-88.95.65.0-8333-1037,-1,-1,-1
78,47354ea54ae758a123e8e977570f2f275c489df8ac37e0be7ac3a26a01ad013d-90.145.218.0-8333-1037,118,118,118
79,f982f1f969d3b2b7c7a1a28fdb732b77ff456279e05881742197c8590ea64114-95.143.151.0-8333-1037,-1,-1,-1
80,18016841b13ff0ab25ae35f82986d571b60d39919ee8bc807fed7f5001dd06d3-188.93.104.0-8333-1,285,282,278,285
81,8fda121069a5f56c07819db1f6cfa731af075ce2eedb637bd26c3dfed3d0049a-128.197.128.0-8333-1037,-1,-1,-1
82,d9940950320a9f1324e5ec3055957e6658f767c864f106264e8697bf9e7efd9c-82.217.245.0-8333-1037,117,114,110,117
83,85ab5c1df280477cf4cbcbd92c082b5d3c2afb517d3465074aa6b12393d5f7c1-82.14.155.0-8333-1033,-1,-1,-1,-1
84,2da93ae2a875c72e9e19c2fdd07316cdad34c6709e0e74b72d3884c5bf2874f9-185.85.3.0-8333-1033,-1,-1,-1,-1
85,26802f6e24d103f8f3dcb034a84c96ed53662a1bb019d5c22087215e5ed34c9e-164.68.116.0-8333-1033,137,68,-1,137
86,5dfbb2a9c7d82d40fcbe5262e917fe4bbc97abef79926c1cf9a7880771115a8d-195.201.87.0-8333-1037,-1,-1,-1
87,c81d1f11eb8f39e72cff371b6c85da4bc500099e32f97d1dbe0dfa3ec4778a79-134.209.127.0-8333-1033,-1,-1,-1,-1,-1
88,1d2b37315106e00fbc055c0fa499932f1b038c4c9bc73c8dba05b8d568b57747-185.19.28.0-8333-1033,-1,-1,-1,-1
89,c2c5962ac806d84a1942d4cb48cc4350e6c9e9c7443bb99f720835b6da702044-52.7.233.0-8333-33,-1,-1,-1,-1
90,405a4a1b553b27468789ac04f6eeae1b06c6c1a06a1817d39eaa7d91fc8bbaec-159.89.121.0-8333-1033,-1,-1,-1,-1
91,b2ade840a4ae8795bd46a09b18722bb3f52a5769938e46169a21619bcad336b7-138.197.162.0-8333-1037,-1,-1,-1
92,c99a8bb837a400e0dfa2df002a02cda9e283af8231461cdd4985d73195f94182-88.88.13.0-8333-1037,-1,-1,-1
93,3f8ca1454ba1def8616d93b73e46f67e56d5317792c5912e4fb0a5eb07bfb7bb-46.229.165.0-8333-1037,-1,-1,-1,-1
94,04fef40b16fb1b814d9c879d3812f7d886c28dba1c536674243dd1342c90e450-34.219.221.0-8333-1037,-1,-1,-1,-1
95,a6af3f72068e3afe0d32e76fc9787b6d4b033ab4650665b256448a556c389d47-73.89.35.0-8333-1037,-1,-1,-1
96,243465d5ea5e59fef2b864170ede935004fd860d9b99117ceb74df8d86b91be2-18.210.164.0-8333-9,24,24,24
97,b5211e54cab6e3406b6d8f13afc4f6a9387d3ca4176c9907979038489b5bd6c6-31.186.25.0-8333-1037,-1,-1,-1
98,a562c6436649a7b4322d37cc452161e8a6a502579c8b7706e3ada686253ed751-63.141.234.0-8333-1037,-1,-1,-1,-1
99,deca1217f1b1f138c6ddf8e10a42527e6c586ea6ade4da9f13e2ddd7e4dcb097-194.36.91.0-8333-1037

In [ ]:
import zipfile

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    with z.open(sample_file) as f:

        for i in range(30):
            line = f.readline()

            if not line:
                break

            decoded = line.decode("utf-8", errors="replace").rstrip("\r\n")

            print(
                f"Line {i+1:02d} | "
                f"commas={decoded.count(',')} | "
                f"tabs={decoded.count(chr(9))} | "
                f"semicolons={decoded.count(';')} | "
                f"{decoded[:300]}"
            )

Line 01 | commas=5 | tabs=0 | semicolons=0 | 1,9307dbb2274694ae6954bbf2144a15e9cfb2006161b38c4194be195f9602f331-192.81.210.0-8333-1037,233,220,208,233
Line 02 | commas=5 | tabs=0 | semicolons=0 | 2,a7dbb134085d885f8cc5d50d7b2683e95e06a4873fc26dc431984b21c7a27b81-134.209.254.0-8333-1037,265,132,-1,265
Line 03 | commas=4 | tabs=0 | semicolons=0 | 3,ade1db93214bcb4a242f177f703bfea173c3caa4449c59f1fe02408518507d21-134.209.230.0-8333-1037,-1,-1,-1
Line 04 | commas=4 | tabs=0 | semicolons=0 | 4,e776487445f0166d3a31de569332da087a57a126f9431743f6789c000139de50-54.254.233.0-8333-1037,317,317,317
Line 05 | commas=5 | tabs=0 | semicolons=0 | 5,19ef04f5c60c33afa8206b01fad7862c450ed1258499e9a31409fb1b42f403d5-54.245.199.0-8333-1037,333,166,333,-1
Line 06 | commas=4 | tabs=0 | semicolons=0 | 6,c26a27a5799c6dd5f4364a38668c2d57240c77c5add9e362bd3bff68eb3e1219-34.222.156.0-8333-1037,-1,-1,-1
Line 07 | commas=4 | tabs=0 | semicolons=0 | 7,c2b990ea8fad9df3d6b54c985ac4252cc1146037fba13bf363a6612324aadb80-13.229.122.0-8333-1037,-1,-1,-1
Line 08 | commas=4 | tabs=0 | semicolons=0 | 8,69adac5843c8acf1986614a0115acc7053468303c3b50afcd2dd2d95317a46ea-46.101.132.0-8333-1037,-1,-1,-1
Line 09 | commas=5 | tabs=0 | semicolons=0 | 9,7df313e1ec6560109dccc5ccecd3c8c1ee0012254fd640e4a15d54a92a0e9bc4-47.254.152.0-8333-1037,-1,-1,-1,-1
Line 10 | commas=5 | tabs=0 | semicolons=0 | 10,2de8a7f629f79a8779f8ee394cc30d0cd20d228f4c1c0a38592da65abf05a9be-88.198.68.0-8333-1033,-1,-1,-1,-1
Line 11 | commas=4 | tabs=0 | semicolons=0 | 11,d86671939820d9b2e93beeb25ad47977b63692e524a93482c205ad35b6648896-178.84.168.0-8333-1037,-1,-1,-1
Line 12 | commas=4 | tabs=0 | semicolons=0 | 12,c13e5fe4a3e332013a2fac40032b82ebb385135acda6157589bda1540475f288-73.38.249.0-8333-1037,-1,-1,-1
Line 13 | commas=4 | tabs=0 | semicolons=0 | 13,5ce162e726231a36c027c3ef971ada0c1481ce39dbce1ee04406c752d19358a7-73.92.253.0-8333-1037,-1,-1,-1
Line 14 | commas=4 | tabs=0 | semicolons=0 | 14,8998d95bc4c4c52cccbf05e12531784f7cd1257115319fa72695f3403692437a-193.70.32.0-8333-13,-1,-1,-1
Line 15 | commas=5 | tabs=0 | semicolons=0 | 15,af3ddf58f91b6e74e31af412bbb133c4cd6643962328b575076a5027fdb207b1-138.201.204.0-8333-1036,-1,-1,-1,-1
Line 16 | commas=5 | tabs=0 | semicolons=0 | 16,67bd9b11bbbcab70d8604de19f5985e5773e573a114b23a1e56aabdf77bdab7e-190.2.150.0-8333-13,-1,-1,-1,-1
Line 17 | commas=5 | tabs=0 | semicolons=0 | 17,ec844a3ff4f5bb48f7f6a628b37442e807ffe5ebe706a713448d5e4ab592ecfc-94.102.57.0-8333-1037,-1,-1,-1,-1
Line 18 | commas=5 | tabs=0 | semicolons=0 | 18,a5cd1c693a26e3553138e28b98b4b4ebc997d201d8f396422c1eaa59425468d2-217.160.185.0-8333-1037,-1,-1,-1,-1
Line 19 | commas=4 | tabs=0 | semicolons=0 | 19,e3095ea4b27d54ff7351c1fd185cbe74a8717a96d695574aa73fced8a7c412ab-45.63.59.0-8333-1032,-1,-1,-1
Line 20 | commas=5 | tabs=0 | semicolons=0 | 20,f8bc5ccfabfe1da90d12cecf2ca71d1db1d8abf9f1d945056990acacc9b3dce8-78.46.128.0-8333-13,-1,-1,-1,-1
Line 21 | commas=6 | tabs=0 | semicolons=0 | 21,fe6aacc7650b9177e880306d2349f76b9a18512de9aad54abfb8504868b62340-159.69.167.0-8333-1033,-1,-1,-1,-1,-1
Line 22 | commas=4 | tabs=0 | semicolons=0 | 22,f231d776a72e5bcfbcd4d5b7727186513478e1988fe841716d32cc92fe6a4668-188.193.141.0-8333-1037,-1,-1,-1
Line 23 | commas=5 | tabs=0 | semicolons=0 | 23,655ea54b96a964741cfe84984a3714c17d35550da5b39ca3f45e1296f2b63da3-52.90.231.0-8333-1033,-1,-1,-1,-1
Line 24 | commas=4 | tabs=0 | semicolons=0 | 24,401e62e688c55e310185b240963c304fffd2a837754edb3c79c77a41b3e8fc31-178.162.210.0-8333-1037,-1,-1,-1
Line 25 | commas=4 | tabs=0 | semicolons=0 | 25,5b2e004967d6224714a21c043976b1c3fdec40286be8a331b94690f531ce0201-78.46.85.0-8333-1037,-1,-1,-1
Line 26 | commas=4 | tabs=0 | semicolons=0 | 26,4023b2370756941d4859e5e2cd9ddc90214d4a00d7334e252ae8f5cae1b460d3-185.107.15.0-8333-1037,-1,-1,-1
Line 27 | commas=4 | tabs=0 | semicolons=0 | 27,d1af70cd8c9468c5443fa54cdafbb9ce1767a2a7329cb2f11e7194082e7138ee-92.118.149.0-8333-1037,-1,-1,-1
Line 28 | commas=4 | tabs=0 | semicolons=0 | 28,8a74eb27bb8ca7a5849e42c4234173a5bdc766ccbecd5ff276d371bdccaa6a70-84.28.199.0-8333-1037,-1,-1,-1
Line 29 | commas=5 | tabs=0 | semicolons=0 | 29,554f40b42d8be122a493886593c21dea99840fa4e41db001b774dc1732b7df2c-188.40.136.0-8333-1037,-1,-1,-1,-1
Line 30 | commas=4 | tabs=0 | semicolons=0 | 30,1e77ab6c0b8d10c331da8f43c8a33e93d71f2f9511e6b8792d5aac117f5513f4-158.174.131.0-8333-1037,-1,-1,-1

In [ ]:
import zipfile
from collections import Counter

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    with z.open(sample_file) as f:

        field_counts = Counter()
        total_lines = 0

        for raw_line in f:

            line = raw_line.decode("utf-8", errors="replace").rstrip("\r\n")

            if not line:
                continue

            fields = line.split(",")

            field_counts[len(fields)] += 1
            total_lines += 1

print("Total rows:", total_lines)

print("\nField-count distribution:")

for fields, count in sorted(field_counts.items()):
    percentage = count / total_lines * 100

    print(
        f"{fields} fields : "
        f"{count:,} rows "
        f"({percentage:.2f}%)"
    )

Total rows: 7299

Field-count distribution:
5 fields : 4,720 rows (64.67%)
6 fields : 2,212 rows (30.31%)
7 fields : 338 rows (4.63%)
8 fields : 26 rows (0.36%)
9 fields : 3 rows (0.04%)

In [ ]:
import zipfile

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    with z.open(sample_file) as f:

        examples = {}

        for raw_line in f:

            line = raw_line.decode(
                "utf-8",
                errors="replace"
            ).rstrip("\r\n")

            if not line:
                continue

            fields = line.split(",")

            n = len(fields)

            if n not in examples:
                examples[n] = fields

            if len(examples) >= 10:
                break

print("Examples by number of fields:\n")

for n in sorted(examples):

    print("=" * 70)
    print(f"{n} FIELDS")
    print("=" * 70)

    for i, field in enumerate(examples[n]):
        print(f"[{i}] {field}")

Examples by number of fields:

======================================================================
5 FIELDS
======================================================================
[0] 3
[1] ade1db93214bcb4a242f177f703bfea173c3caa4449c59f1fe02408518507d21-134.209.230.0-8333-1037
[2] -1
[3] -1
[4] -1
======================================================================
6 FIELDS
======================================================================
[0] 1
[1] 9307dbb2274694ae6954bbf2144a15e9cfb2006161b38c4194be195f9602f331-192.81.210.0-8333-1037
[2] 233
[3] 220
[4] 208
[5] 233
======================================================================
7 FIELDS
======================================================================
[0] 21
[1] fe6aacc7650b9177e880306d2349f76b9a18512de9aad54abfb8504868b62340-159.69.167.0-8333-1033
[2] -1
[3] -1
[4] -1
[5] -1
[6] -1
======================================================================
8 FIELDS
======================================================================
[0] 564
[1] 148effb1c7c1cd213ff69ba7f8f2548d5dd923dac7722a26a20976d8ed1fbe77-93.115.26.0-20013-13
[2] 95
[3] 46
[4] 95
[5] 89
[6] -1
[7] -1
======================================================================
9 FIELDS
======================================================================
[0] 1910
[1] 70e6892bf7320bff3e0d58b7bcb6a19d5e9ac73c6558567b4a023e3cb3ef5e99-95.217.32.0-8333-1033
[2] 138
[3] 79
[4] -1
[5] -1
[6] 138
[7] 127
[8] 131

In [ ]:
import zipfile
import json

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    json_files = [
        name for name in z.namelist()
        if name.startswith("dataset_2020/crawl/20200215/")
        and name.lower().endswith(".json")
    ]

print("JSON files on 20200215:", len(json_files))

for name in json_files[:10]:
    print(name)

JSON files on 20200215: 360
dataset_2020/crawl/20200215/20200215-19:22:40.json
dataset_2020/crawl/20200215/20200215-09:46:51.json
dataset_2020/crawl/20200215/20200215-14:54:50.json
dataset_2020/crawl/20200215/20200215-02:38:50.json
dataset_2020/crawl/20200215/20200215-10:39:11.json
dataset_2020/crawl/20200215/20200215-19:38:40.json
dataset_2020/crawl/20200215/20200215-03:42:30.json
dataset_2020/crawl/20200215/20200215-04:10:30.json
dataset_2020/crawl/20200215/20200215-01:15:11.json
dataset_2020/crawl/20200215/20200215-17:18:40.json

In [ ]:
with zipfile.ZipFile(ZIP_PATH, "r") as z:

    json_file = json_files[0]

    print("Inspecting:")
    print(json_file)

    with z.open(json_file) as f:
        data = json.load(f)

print("\nTop-level type:", type(data))

if isinstance(data, dict):

    print("\nTop-level keys:")
    for key in data:
        print("-", key)

elif isinstance(data, list):

    print("\nList length:", len(data))

    if len(data) > 0:
        print("\nFirst element:")
        print(data[0])

Inspecting:
dataset_2020/crawl/20200215/20200215-19:22:40.json

Top-level type: <class 'list'>

List length: 7378

First element:
[['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617525]

In [ ]:
with zipfile.ZipFile(ZIP_PATH, "r") as z:

    json_file = json_files[0]

    print("Inspecting:")
    print(json_file)

    with z.open(json_file) as f:
        data = json.load(f)

print("\nTop-level type:", type(data))

if isinstance(data, dict):

    print("\nTop-level keys:")
    for key in data:
        print("-", key)

elif isinstance(data, list):

    print("\nList length:", len(data))

    if len(data) > 0:
        print("\nFirst element:")
        print(data[0])

Inspecting:
dataset_2020/crawl/20200215/20200215-19:22:40.json

Top-level type: <class 'list'>

List length: 7378

First element:
[['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617525]

In [ ]:
import zipfile
import json
from collections import Counter

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    json_files = [
        name for name in z.namelist()
        if name.startswith("dataset_2020/crawl/")
        and name.lower().endswith(".json")
    ]

    # Select several snapshots from different dates
    selected = json_files[:10]

    print("Inspecting", len(selected), "JSON snapshots\n")

    for json_file in selected:

        with z.open(json_file) as f:
            data = json.load(f)

        print("=" * 80)
        print(json_file)
        print("Records:", len(data))

        if data:
            print("First record:", data[0])
            print("Record length:", len(data[0]))

            # Check structure of first 100 records
            lengths = Counter(
                len(record)
                for record in data[:100]
            )

            print("Record-length distribution:", dict(lengths))

Inspecting 10 JSON snapshots

================================================================================
dataset_2020/crawl/20200215/20200215-19:22:40.json
Records: 7378
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617525]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-09:46:51.json
Records: 7327
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617462]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-14:54:50.json
Records: 7378
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617497]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-02:38:50.json
Records: 7304
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617426]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-10:39:11.json
Records: 7350
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617468]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-19:38:40.json
Records: 7369
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617527]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-03:42:30.json
Records: 7291
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617433]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-04:10:30.json
Records: 7222
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617437]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-01:15:11.json
Records: 7314
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617414]
Record length: 4
Record-length distribution: {4: 100}
================================================================================
dataset_2020/crawl/20200215/20200215-17:18:40.json
Records: 7374
First record: [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617509]
Record length: 4
Record-length distribution: {4: 100}

In [ ]:
import zipfile
import json

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    json_file = selected[0]

    with z.open(json_file) as f:
        data = json.load(f)

    valid = 0
    invalid = 0

    for record in data:

        try:
            node_info, port, service, height = record

            node_id, ip = node_info

            valid += 1

        except Exception:
            invalid += 1

    print("Total records:", len(data))
    print("Valid structure:", valid)
    print("Invalid structure:", invalid)

Total records: 7378
Valid structure: 7378
Invalid structure: 0

In [ ]:
import zipfile
import json

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    json_file = selected[0]

    with z.open(json_file) as f:
        data = json.load(f)

    for i, record in enumerate(data[:20]):

        node_info, port, service, height = record
        node_id, ip = node_info

        print(
            f"{i:02d} | "
            f"node_id={type(node_id).__name__:<8} | "
            f"ip={type(ip).__name__:<8} | "
            f"port={type(port).__name__:<8} | "
            f"service={type(service).__name__:<8} | "
            f"height={type(height).__name__:<8}"
        )

00 | node_id=str      | ip=str      | port=int      | service=int      | height=int
01 | node_id=str      | ip=str      | port=int      | service=int      | height=int
02 | node_id=str      | ip=str      | port=int      | service=int      | height=int
03 | node_id=str      | ip=str      | port=int      | service=int      | height=int
04 | node_id=str      | ip=str      | port=int      | service=int      | height=int
05 | node_id=str      | ip=str      | port=int      | service=int      | height=int
06 | node_id=str      | ip=str      | port=int      | service=int      | height=int
07 | node_id=str      | ip=str      | port=int      | service=int      | height=int
08 | node_id=str      | ip=str      | port=int      | service=int      | height=int
09 | node_id=str      | ip=str      | port=int      | service=int      | height=int
10 | node_id=str      | ip=str      | port=int      | service=int      | height=int
11 | node_id=str      | ip=str      | port=int      | service=int      | height=int
12 | node_id=str      | ip=str      | port=int      | service=int      | height=int
13 | node_id=str      | ip=str      | port=int      | service=int      | height=int
14 | node_id=str      | ip=str      | port=int      | service=int      | height=int
15 | node_id=str      | ip=str      | port=int      | service=int      | height=int
16 | node_id=str      | ip=str      | port=int      | service=int      | height=int
17 | node_id=str      | ip=str      | port=int      | service=int      | height=int
18 | node_id=str      | ip=str      | port=int      | service=int      | height=int
19 | node_id=str      | ip=str      | port=int      | service=int      | height=int

In [ ]:
import zipfile
import json

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    # Use the first snapshot
    first_file = selected[0]

    with z.open(first_file) as f:
        first_data = json.load(f)

    target_node = first_data[0][0][0]

    print("Target node:")
    print(target_node)

    print("\nSearching across snapshots...\n")

    for json_file in selected:

        with z.open(json_file) as f:
            data = json.load(f)

        matches = [
            record for record in data
            if record[0][0] == target_node
        ]

        print(
            json_file,
            "→",
            len(matches),
            "observation(s)"
        )

        if matches:
            print("   ", matches[0])

Target node:
bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f

Searching across snapshots...

dataset_2020/crawl/20200215/20200215-19:22:40.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617525]
dataset_2020/crawl/20200215/20200215-09:46:51.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617462]
dataset_2020/crawl/20200215/20200215-14:54:50.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617497]
dataset_2020/crawl/20200215/20200215-02:38:50.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617426]
dataset_2020/crawl/20200215/20200215-10:39:11.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617468]
dataset_2020/crawl/20200215/20200215-19:38:40.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617527]
dataset_2020/crawl/20200215/20200215-03:42:30.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617433]
dataset_2020/crawl/20200215/20200215-04:10:30.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617437]
dataset_2020/crawl/20200215/20200215-01:15:11.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617414]
dataset_2020/crawl/20200215/20200215-17:18:40.json → 1 observation(s)
    [['bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '85.25.134.0'], 8333, 1037, 617509]

In [ ]:
import zipfile
from collections import Counter
from pathlib import PurePosixPath

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    crawl_jsons = [
        name for name in z.namelist()
        if name.startswith("dataset_2020/crawl/")
        and name.lower().endswith(".json")
    ]

date_counts = Counter()

for name in crawl_jsons:
    parts = PurePosixPath(name).parts

    # dataset_2020 / crawl / YYYYMMDD / file.json
    if len(parts) >= 4:
        date_counts[parts[2]] += 1

print("Total crawl JSON snapshots:", len(crawl_jsons))

print("\nSnapshots by date:")
for date, count in sorted(date_counts.items()):
    print(f"{date}: {count:,}")

Total crawl JSON snapshots: 9481

Snapshots by date:
20200207: 360
20200208: 360
20200209: 360
20200210: 360
20200211: 360
20200212: 360
20200213: 360
20200214: 360
20200215: 360
20200216: 360
20200217: 360
20200218: 360
20200219: 360
20200220: 360
20200221: 360
20200222: 360
20200223: 360
20200224: 360
20200225: 360
20200226: 360
20200227: 360
20200228: 360
20200229: 360
20200301: 360
20200302: 360
20200607: 360
20200709: 121

In [ ]:
from datetime import datetime
from pathlib import PurePosixPath

timestamps = []

for name in crawl_jsons:

    filename = PurePosixPath(name).stem

    try:
        dt = datetime.strptime(
            filename,
            "%Y%m%d-%H:%M:%S"
        )
        timestamps.append(dt)

    except ValueError:
        pass

print("Valid timestamp files:", len(timestamps))

print("Earliest:", min(timestamps))
print("Latest  :", max(timestamps))

Valid timestamp files: 9481
Earliest: 2020-02-07 00:03:07
Latest  : 2020-07-09 23:48:52

In [ ]:
import zipfile
import json
import statistics

# Use a sample of 30 JSON snapshots
sample_files = crawl_jsons[:30]

record_counts = []

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for name in sample_files:

        with z.open(name) as f:
            data = json.load(f)

        record_counts.append(len(data))

print("Snapshots inspected:", len(record_counts))

print("Minimum records:", min(record_counts))
print("Maximum records:", max(record_counts))
print("Mean records:", statistics.mean(record_counts))
print("Median records:", statistics.median(record_counts))

Snapshots inspected: 30
Minimum records: 7197
Maximum records: 7430
Mean records: 7318.6
Median records: 7329.5

In [ ]:
import zipfile
import json

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    test_files = crawl_jsons[:10]

    for name in test_files:

        with z.open(name) as f:
            data = json.load(f)

        node_ids = [
            record[0][0]
            for record in data
        ]

        duplicates = len(node_ids) - len(set(node_ids))

        print(
            name,
            "records =", len(node_ids),
            "duplicate node IDs =", duplicates
        )

dataset_2020/crawl/20200215/20200215-19:22:40.json records = 7378 duplicate node IDs = 65
dataset_2020/crawl/20200215/20200215-09:46:51.json records = 7327 duplicate node IDs = 63
dataset_2020/crawl/20200215/20200215-14:54:50.json records = 7378 duplicate node IDs = 66
dataset_2020/crawl/20200215/20200215-02:38:50.json records = 7304 duplicate node IDs = 62
dataset_2020/crawl/20200215/20200215-10:39:11.json records = 7350 duplicate node IDs = 64
dataset_2020/crawl/20200215/20200215-19:38:40.json records = 7369 duplicate node IDs = 66
dataset_2020/crawl/20200215/20200215-03:42:30.json records = 7291 duplicate node IDs = 64
dataset_2020/crawl/20200215/20200215-04:10:30.json records = 7222 duplicate node IDs = 61
dataset_2020/crawl/20200215/20200215-01:15:11.json records = 7314 duplicate node IDs = 63
dataset_2020/crawl/20200215/20200215-17:18:40.json records = 7374 duplicate node IDs = 62

In [ ]:
import zipfile
import json
from collections import Counter

service_counter = Counter()

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for name in crawl_jsons[:30]:

        with z.open(name) as f:
            data = json.load(f)

        for record in data:

            service = record[2]

            service_counter[service] += 1

print("Unique service values:", len(service_counter))

print("\nMost common service values:")

for service, count in service_counter.most_common(20):

    print(
        f"{service:8} "
        f"{count:,}"
    )

Unique service values: 24

Most common service values:
    1037 105,522
    1033 46,812
    1036 32,612
      13 15,772
    1032 6,366
      12 5,570
       5 3,186
       1 1,072
      77 702
      21 352
      37 332
       9 302
       4 272
      20 180
    1101 114
      23 90
     141 89
    1097 60
      33 30
      53 30

In [ ]:
import zipfile
import json
from collections import Counter

port_counter = Counter()

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for name in crawl_jsons[:30]:

        with z.open(name) as f:
            data = json.load(f)

        for record in data:

            port = record[1]

            port_counter[port] += 1

print("Unique ports:", len(port_counter))

print("\nMost common ports:")

for port, count in port_counter.most_common(20):

    print(
        f"{port:8} "
        f"{count:,}"
    )

Unique ports: 181

Most common ports:
    8333 207,378
    8433 1,410
    8335 614
    8334 495
    8885 479
    9333 353
    8444 347
   20008 328
    6333 270
   48333 270
    8446 270
   18333 256
   33333 210
    9595 201
    8332 193
    5001 179
    8339 167
   48533 150
    9001 150
   28833 150

In [ ]:
import zipfile
import json
import statistics

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for name in crawl_jsons[:10]:

        with z.open(name) as f:
            data = json.load(f)

        heights = [
            record[3]
            for record in data
            if isinstance(record[3], int) and record[3] >= 0
        ]

        print(
            name,
            "\n  records:",
            len(data),
            "\n  valid heights:",
            len(heights),
            "\n  min:",
            min(heights) if heights else None,
            "\n  max:",
            max(heights) if heights else None,
            "\n  median:",
            statistics.median(heights) if heights else None
        )

dataset_2020/crawl/20200215/20200215-19:22:40.json
  records: 7378
  valid heights: 7378
  min: 0
  max: 3222663
  median: 617525.0
dataset_2020/crawl/20200215/20200215-09:46:51.json
  records: 7327
  valid heights: 7327
  min: 0
  max: 3219289
  median: 617462
dataset_2020/crawl/20200215/20200215-14:54:50.json
  records: 7378
  valid heights: 7378
  min: 0
  max: 3221101
  median: 617497.0
dataset_2020/crawl/20200215/20200215-02:38:50.json
  records: 7304
  valid heights: 7304
  min: 0
  max: 3216758
  median: 617426.0
dataset_2020/crawl/20200215/20200215-10:39:11.json
  records: 7350
  valid heights: 7350
  min: 0
  max: 3219593
  median: 617468.0
dataset_2020/crawl/20200215/20200215-19:38:40.json
  records: 7369
  valid heights: 7369
  min: 0
  max: 3222782
  median: 617527
dataset_2020/crawl/20200215/20200215-03:42:30.json
  records: 7291
  valid heights: 7291
  min: 0
  max: 3217134
  median: 617433
dataset_2020/crawl/20200215/20200215-04:10:30.json
  records: 7222
  valid heights: 7222
  min: 0
  max: 3217303
  median: 617437.0
dataset_2020/crawl/20200215/20200215-01:15:11.json
  records: 7314
  valid heights: 7314
  min: 0
  max: 3216274
  median: 617414.0
dataset_2020/crawl/20200215/20200215-17:18:40.json
  records: 7374
  valid heights: 7374
  min: 0
  max: 3221945
  median: 617509.0

In [ ]:
import zipfile
import json
from collections import defaultdict

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    test_file = "dataset_2020/crawl/20200215/20200215-19:22:40.json"

    with z.open(test_file) as f:
        data = json.load(f)

node_records = defaultdict(list)

for record in data:

    node_info, port, service, height = record

    node_id, ip = node_info

    node_records[node_id].append({
        "ip": ip,
        "port": port,
        "service": service,
        "height": height
    })

duplicates = {
    node_id: records
    for node_id, records in node_records.items()
    if len(records) > 1
}

print("Total records:", len(data))
print("Unique node IDs:", len(node_records))
print("Duplicate node IDs:", len(duplicates))

print("\nFirst 10 duplicate examples:\n")

for node_id, records in list(duplicates.items())[:10]:

    print("NODE:", node_id)

    for r in records:
        print("   ", r)

    print()

Total records: 7378
Unique node IDs: 7313
Duplicate node IDs: 60

First 10 duplicate examples:

NODE: 7022b3ab2151ed59d4682775bf6591ebdf7bb6019d46be77c907822746496759
    {'ip': '93.115.26.0', 'port': 20013, 'service': 13, 'height': 617526}
    {'ip': '93.115.26.0', 'port': 20004, 'service': 1037, 'height': 617525}

NODE: 9063a1a91092a1a57fb09c52d8f20fd4512485bf8915b0daef1253832f06ca73
    {'ip': '207.148.126.0', 'port': 8333, 'service': 1036, 'height': 617525}
    {'ip': '207.148.126.0', 'port': 8336, 'service': 1036, 'height': 617525}

NODE: 6c30720075293ab76d38f586284edf9b7698781bceb5e156705d3246465b58c8
    {'ip': '35.186.181.0', 'port': 38333, 'service': 1037, 'height': 617525}
    {'ip': '35.186.181.0', 'port': 8333, 'service': 1037, 'height': 617526}

NODE: 417827a8c50f06e783c07f9ba0c5239ecf692acaf205d88d8e034fb901c9f7ca
    {'ip': '95.174.66.0', 'port': 8335, 'service': 1036, 'height': 617525}
    {'ip': '95.174.66.0', 'port': 8333, 'service': 1037, 'height': 617525}

NODE: aaa07b6ffc50cfd29c1f6eaa614dd016a0711ef2077d724fa0473a109cc64926
    {'ip': '136.144.215.0', 'port': 10100, 'service': 13, 'height': 617525}
    {'ip': '136.144.215.0', 'port': 8333, 'service': 1037, 'height': 617526}

NODE: 1e80113fa3d98fb1dec76993bdb77ebd3c19391e6e438937a1b9fe86818205ac
    {'ip': '71.67.65.0', 'port': 12501, 'service': 1037, 'height': 617525}
    {'ip': '71.67.65.0', 'port': 12503, 'service': 1037, 'height': 617523}

NODE: 4f68fc40d504e37eaa366df942a5100ad363e7b170d205992026b01e9cbc04d5
    {'ip': '5.79.123.0', 'port': 8333, 'service': 1037, 'height': 617525}
    {'ip': '5.79.123.0', 'port': 10444, 'service': 13, 'height': 617525}

NODE: 4c84ec3f168059e8c91626c836ca6a8b80f71d669bc5315e0568134ff484ffe4
    {'ip': '107.180.71.0', 'port': 8333, 'service': 1037, 'height': 617525}
    {'ip': '107.180.71.0', 'port': 8393, 'service': 1037, 'height': 617525}

NODE: f051ce011ff54e9445fe094107921e14be2adc1f07cc028f0c8fae8da30fd0f2
    {'ip': '78.35.247.0', 'port': 8333, 'service': 1037, 'height': 617525}
    {'ip': '78.35.247.0', 'port': 8334, 'service': 1037, 'height': 617525}

NODE: 2d8dafabc4815012a5f145af1ccab703e75385922cb81ae86d7680e990b2a50f
    {'ip': '94.23.248.0', 'port': 8333, 'service': 1037, 'height': 617525}
    {'ip': '94.23.248.0', 'port': 8433, 'service': 1037, 'height': 617525}
    {'ip': '94.23.248.0', 'port': 8335, 'service': 1037, 'height': 617526}

In [ ]:
import zipfile
import json
import numpy as np

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    test_file = "dataset_2020/crawl/20200215/20200215-19:22:40.json"

    with z.open(test_file) as f:
        data = json.load(f)

heights = np.array([
    record[3]
    for record in data
    if isinstance(record[3], int)
])

print("Total heights:", len(heights))

print("\nPercentiles:")

for p in [0, 1, 5, 25, 50, 75, 95, 99, 99.5, 99.9, 100]:

    print(
        f"{p:6.1f}% : "
        f"{np.percentile(heights, p):,.0f}"
    )

print("\nThreshold counts:")

for threshold in [0, 500000, 600000, 617000, 618000, 700000, 1000000, 2000000, 3000000]:

    print(
        f"> {threshold:,}: "
        f"{np.sum(heights > threshold):,}"
    )

Total heights: 7378

Percentiles:
   0.0% : 0
   1.0% : 531,473
   5.0% : 617,525
  25.0% : 617,525
  50.0% : 617,525
  75.0% : 617,525
  95.0% : 617,526
  99.0% : 617,526
  99.5% : 629,157
  99.9% : 1,080,165
 100.0% : 3,222,663

Threshold counts:
> 0: 7,377
> 500,000: 7,317
> 600,000: 7,285
> 617,000: 7,270
> 618,000: 41
> 700,000: 34
> 1,000,000: 8
> 2,000,000: 2
> 3,000,000: 2

In [ ]:
abnormal = []

for record in data:

    node_info, port, service, height = record

    node_id, ip = node_info

    if height > 1000000:

        abnormal.append({
            "node_id": node_id,
            "ip": ip,
            "port": port,
            "service": service,
            "height": height
        })

print("Abnormal records:", len(abnormal))

for row in abnormal[:30]:
    print(row)

Abnormal records: 8
{'node_id': 'ff38831907ae5a2154afc3320bf9fb2b800ff94bdede34b9e6c69b4fb6afd696', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168224}
{'node_id': 'fbf127f8b0e9f008550d1bbd228a38a037f6ac6a5c9b93c8bbc7be809ecd70dc', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3222663}
{'node_id': 'b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f49f79c11977016ec7c', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168224}
{'node_id': 'b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f49f79c11977016ec7c', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'node_id': '7b1b77df0b0e8ec05478b24fbaa18dd0db8eb4354be8a0bd26ab476442537f04', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3222660}
{'node_id': 'dbb799ffebb8e545ef10ca3f270f38a3750761e46a22a18af7e3895ab49c7a05', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'node_id': '407d0dff709c59b28592f5a88bce5b922b56d64cfb4dd21a56de61a62e078d1c', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1605657}
{'node_id': '81014a7a2079567542257c365550184d8bc9ad58a48b8ac167942f99d3400c7e', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196553}

In [ ]:
from collections import Counter

height_counter = Counter(
    record[3]
    for record in data
)

print("Most common heights:\n")

for height, count in height_counter.most_common(20):

    print(
        f"height={height:,} "
        f"count={count:,}"
    )

Most common heights:

height=617,525 count=5,868
height=617,526 count=1,157
height=617,521 count=100
height=617,523 count=34
height=617,518 count=28
height=617,522 count=15
height=863,751 count=15
height=617,520 count=9
height=145,105 count=9
height=789,156 count=9
height=565,799 count=9
height=617,524 count=8
height=530,361 count=6
height=629,157 count=5
height=67,897 count=5
height=206,089 count=5
height=103,064 count=4
height=610,819 count=3
height=67,898 count=3
height=357,561 count=3

In [ ]:
import zipfile
import json
from collections import defaultdict

# First identify abnormal node IDs from our test snapshot
abnormal_nodes = set()

for record in data:

    node_info, port, service, height = record
    node_id, ip = node_info

    if height > 1_000_000:
        abnormal_nodes.add(node_id)

print("Abnormal node IDs:", len(abnormal_nodes))

print("\nNodes:")
for node in abnormal_nodes:
    print(node)

Abnormal node IDs: 7

Nodes:
fbf127f8b0e9f008550d1bbd228a38a037f6ac6a5c9b93c8bbc7be809ecd70dc
407d0dff709c59b28592f5a88bce5b922b56d64cfb4dd21a56de61a62e078d1c
ff38831907ae5a2154afc3320bf9fb2b800ff94bdede34b9e6c69b4fb6afd696
7b1b77df0b0e8ec05478b24fbaa18dd0db8eb4354be8a0bd26ab476442537f04
81014a7a2079567542257c365550184d8bc9ad58a48b8ac167942f99d3400c7e
dbb799ffebb8e545ef10ca3f270f38a3750761e46a22a18af7e3895ab49c7a05
b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f49f79c11977016ec7c

In [ ]:
import zipfile
import json
from collections import defaultdict

node_history = defaultdict(list)

# Use 30 snapshots for the initial investigation
test_snapshots = crawl_jsons[:30]

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for json_file in test_snapshots:

        with z.open(json_file) as f:
            snapshot = json.load(f)

        for record in snapshot:

            node_info, port, service, height = record
            node_id, ip = node_info

            if node_id in abnormal_nodes:

                node_history[node_id].append({
                    "timestamp": json_file.split("/")[-1][:-5],
                    "ip": ip,
                    "port": port,
                    "service": service,
                    "height": height
                })

for node_id, history in node_history.items():

    print("\n" + "=" * 80)
    print("NODE:", node_id)
    print("Observations:", len(history))

    for row in history[:20]:
        print(row)

================================================================================
NODE: ff38831907ae5a2154afc3320bf9fb2b800ff94bdede34b9e6c69b4fb6afd696
Observations: 30
{'timestamp': '20200215-19:22:40', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168224}
{'timestamp': '20200215-09:46:51', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168218}
{'timestamp': '20200215-14:54:50', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168220}
{'timestamp': '20200215-02:38:50', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168210}
{'timestamp': '20200215-10:39:11', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168218}
{'timestamp': '20200215-19:38:40', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168224}
{'timestamp': '20200215-03:42:30', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168212}
{'timestamp': '20200215-04:10:30', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168212}
{'timestamp': '20200215-01:15:11', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168210}
{'timestamp': '20200215-17:18:40', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168221}
{'timestamp': '20200215-02:11:00', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168210}
{'timestamp': '20200215-04:18:40', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168213}
{'timestamp': '20200215-12:39:01', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168219}
{'timestamp': '20200215-07:54:41', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168215}
{'timestamp': '20200215-17:10:40', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168221}
{'timestamp': '20200215-14:43:11', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168220}
{'timestamp': '20200215-13:26:50', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168220}
{'timestamp': '20200215-11:15:00', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168218}
{'timestamp': '20200215-01:03:20', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168210}
{'timestamp': '20200215-13:35:00', 'ip': '188.254.215.0', 'port': 12333, 'service': 5, 'height': 1168220}

================================================================================
NODE: fbf127f8b0e9f008550d1bbd228a38a037f6ac6a5c9b93c8bbc7be809ecd70dc
Observations: 30
{'timestamp': '20200215-19:22:40', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3222663}
{'timestamp': '20200215-09:46:51', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3219279}
{'timestamp': '20200215-14:54:50', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3221099}
{'timestamp': '20200215-02:38:50', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3216753}
{'timestamp': '20200215-10:39:11', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3219583}
{'timestamp': '20200215-19:38:40', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3222771}
{'timestamp': '20200215-03:42:30', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3217125}
{'timestamp': '20200215-04:10:30', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3217301}
{'timestamp': '20200215-01:15:11', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3216262}
{'timestamp': '20200215-17:18:40', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3221938}
{'timestamp': '20200215-02:11:00', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3216581}
{'timestamp': '20200215-04:18:40', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3217346}
{'timestamp': '20200215-12:39:01', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3220293}
{'timestamp': '20200215-07:54:41', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3218619}
{'timestamp': '20200215-17:10:40', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3221895}
{'timestamp': '20200215-14:43:11', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3221026}
{'timestamp': '20200215-13:26:50', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3220577}
{'timestamp': '20200215-11:15:00', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3219788}
{'timestamp': '20200215-01:03:20', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3216190}
{'timestamp': '20200215-13:35:00', 'ip': '47.112.122.0', 'port': 8999, 'service': 5, 'height': 3220637}

================================================================================
NODE: b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f49f79c11977016ec7c
Observations: 60
{'timestamp': '20200215-19:22:40', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168224}
{'timestamp': '20200215-19:22:40', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'timestamp': '20200215-09:46:51', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168218}
{'timestamp': '20200215-09:46:51', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196474}
{'timestamp': '20200215-14:54:50', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168220}
{'timestamp': '20200215-14:54:50', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196520}
{'timestamp': '20200215-02:38:50', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168210}
{'timestamp': '20200215-02:38:50', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196430}
{'timestamp': '20200215-10:39:11', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168218}
{'timestamp': '20200215-10:39:11', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196488}
{'timestamp': '20200215-19:38:40', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168224}
{'timestamp': '20200215-19:38:40', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'timestamp': '20200215-03:42:30', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168212}
{'timestamp': '20200215-03:42:30', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-04:10:30', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168212}
{'timestamp': '20200215-04:10:30', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-01:15:11', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168210}
{'timestamp': '20200215-01:15:11', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196418}
{'timestamp': '20200215-17:18:40', 'ip': '62.210.5.0', 'port': 12333, 'service': 5, 'height': 1168221}
{'timestamp': '20200215-17:18:40', 'ip': '62.210.5.0', 'port': 11080, 'service': 5, 'height': 1196536}

================================================================================
NODE: 7b1b77df0b0e8ec05478b24fbaa18dd0db8eb4354be8a0bd26ab476442537f04
Observations: 30
{'timestamp': '20200215-19:22:40', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3222660}
{'timestamp': '20200215-09:46:51', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3219289}
{'timestamp': '20200215-14:54:50', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3221101}
{'timestamp': '20200215-02:38:50', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3216758}
{'timestamp': '20200215-10:39:11', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3219593}
{'timestamp': '20200215-19:38:40', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3222782}
{'timestamp': '20200215-03:42:30', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3217134}
{'timestamp': '20200215-04:10:30', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3217303}
{'timestamp': '20200215-01:15:11', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3216274}
{'timestamp': '20200215-17:18:40', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3221945}
{'timestamp': '20200215-02:11:00', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3216591}
{'timestamp': '20200215-04:18:40', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3217346}
{'timestamp': '20200215-12:39:01', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3220304}
{'timestamp': '20200215-07:54:41', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3218624}
{'timestamp': '20200215-17:10:40', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3221886}
{'timestamp': '20200215-14:43:11', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3221028}
{'timestamp': '20200215-13:26:50', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3220577}
{'timestamp': '20200215-11:15:00', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3219788}
{'timestamp': '20200215-01:03:20', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3216196}
{'timestamp': '20200215-13:35:00', 'ip': '47.92.101.0', 'port': 8999, 'service': 5, 'height': 3220638}

================================================================================
NODE: dbb799ffebb8e545ef10ca3f270f38a3750761e46a22a18af7e3895ab49c7a05
Observations: 30
{'timestamp': '20200215-19:22:40', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'timestamp': '20200215-09:46:51', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196474}
{'timestamp': '20200215-14:54:50', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196520}
{'timestamp': '20200215-02:38:50', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196428}
{'timestamp': '20200215-10:39:11', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196488}
{'timestamp': '20200215-19:38:40', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'timestamp': '20200215-03:42:30', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-04:10:30', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-01:15:11', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196418}
{'timestamp': '20200215-17:18:40', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196536}
{'timestamp': '20200215-02:11:00', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196422}
{'timestamp': '20200215-04:18:40', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-12:39:01', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196504}
{'timestamp': '20200215-07:54:41', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196460}
{'timestamp': '20200215-17:10:40', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196535}
{'timestamp': '20200215-14:43:11', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196520}
{'timestamp': '20200215-13:26:50', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196513}
{'timestamp': '20200215-11:15:00', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196497}
{'timestamp': '20200215-01:03:20', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196417}
{'timestamp': '20200215-13:35:00', 'ip': '91.121.221.0', 'port': 11080, 'service': 5, 'height': 1196513}

================================================================================
NODE: 407d0dff709c59b28592f5a88bce5b922b56d64cfb4dd21a56de61a62e078d1c
Observations: 30
{'timestamp': '20200215-19:22:40', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1605657}
{'timestamp': '20200215-09:46:51', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1604536}
{'timestamp': '20200215-14:54:50', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1605139}
{'timestamp': '20200215-02:38:50', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1603702}
{'timestamp': '20200215-10:39:11', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1604633}
{'timestamp': '20200215-19:38:40', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1605683}
{'timestamp': '20200215-03:42:30', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1603822}
{'timestamp': '20200215-04:10:30', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1603883}
{'timestamp': '20200215-01:15:11', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1603537}
{'timestamp': '20200215-17:18:40', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1605409}
{'timestamp': '20200215-02:11:00', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1603645}
{'timestamp': '20200215-04:18:40', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1603903}
{'timestamp': '20200215-12:39:01', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1604874}
{'timestamp': '20200215-07:54:41', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1604320}
{'timestamp': '20200215-17:10:40', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1605392}
{'timestamp': '20200215-14:43:11', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1605103}
{'timestamp': '20200215-13:26:50', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1604942}
{'timestamp': '20200215-11:15:00', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1604719}
{'timestamp': '20200215-01:03:20', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1603523}
{'timestamp': '20200215-13:35:00', 'ip': '47.75.96.0', 'port': 12900, 'service': 1, 'height': 1604969}

================================================================================
NODE: 81014a7a2079567542257c365550184d8bc9ad58a48b8ac167942f99d3400c7e
Observations: 30
{'timestamp': '20200215-19:22:40', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'timestamp': '20200215-09:46:51', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196474}
{'timestamp': '20200215-14:54:50', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196520}
{'timestamp': '20200215-02:38:50', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196428}
{'timestamp': '20200215-10:39:11', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196488}
{'timestamp': '20200215-19:38:40', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196553}
{'timestamp': '20200215-03:42:30', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-04:10:30', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-01:15:11', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196418}
{'timestamp': '20200215-17:18:40', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196536}
{'timestamp': '20200215-02:11:00', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196422}
{'timestamp': '20200215-04:18:40', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196441}
{'timestamp': '20200215-12:39:01', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196504}
{'timestamp': '20200215-07:54:41', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196460}
{'timestamp': '20200215-17:10:40', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196535}
{'timestamp': '20200215-14:43:11', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196520}
{'timestamp': '20200215-13:26:50', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196513}
{'timestamp': '20200215-11:15:00', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196497}
{'timestamp': '20200215-01:03:20', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196417}
{'timestamp': '20200215-13:35:00', 'ip': '85.15.179.0', 'port': 11080, 'service': 5, 'height': 1196513}

In [ ]:
import zipfile
import json
import statistics

duplicate_counts = []
record_counts = []

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for json_file in crawl_jsons[:30]:

        with z.open(json_file) as f:
            snapshot = json.load(f)

        node_ids = [
            record[0][0]
            for record in snapshot
        ]

        duplicates = len(node_ids) - len(set(node_ids))

        duplicate_counts.append(duplicates)
        record_counts.append(len(snapshot))

print("Snapshots:", len(duplicate_counts))

print("Duplicate node IDs:")
print("  min   :", min(duplicate_counts))
print("  max   :", max(duplicate_counts))
print("  mean  :", statistics.mean(duplicate_counts))
print("  median:", statistics.median(duplicate_counts))

print("\nDuplicate percentage:")
for records, duplicates in zip(record_counts[:10], duplicate_counts[:10]):

    print(
        f"{duplicates}/{records} = "
        f"{duplicates / records * 100:.2f}%"
    )

Snapshots: 30
Duplicate node IDs:
  min   : 61
  max   : 66
  mean  : 63.36666666666667
  median: 63.0

Duplicate percentage:
65/7378 = 0.88%
63/7327 = 0.86%
66/7378 = 0.89%
62/7304 = 0.85%
64/7350 = 0.87%
66/7369 = 0.90%
64/7291 = 0.88%
61/7222 = 0.84%
63/7314 = 0.86%
62/7374 = 0.84%

In [ ]:
import zipfile
import json
import numpy as np

reference_results = []

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for json_file in crawl_jsons[:30]:

        with z.open(json_file) as f:
            snapshot = json.load(f)

        heights = np.array([
            record[3]
            for record in snapshot
            if isinstance(record[3], int)
            and record[3] > 0
        ])

        reference_height = int(np.median(heights))

        reference_results.append(
            (json_file, reference_height)
        )

for filename, height in reference_results[:30]:

    print(
        filename,
        "→ reference height:",
        height
    )

dataset_2020/crawl/20200215/20200215-19:22:40.json → reference height: 617525
dataset_2020/crawl/20200215/20200215-09:46:51.json → reference height: 617462
dataset_2020/crawl/20200215/20200215-14:54:50.json → reference height: 617497
dataset_2020/crawl/20200215/20200215-02:38:50.json → reference height: 617426
dataset_2020/crawl/20200215/20200215-10:39:11.json → reference height: 617468
dataset_2020/crawl/20200215/20200215-19:38:40.json → reference height: 617527
dataset_2020/crawl/20200215/20200215-03:42:30.json → reference height: 617433
dataset_2020/crawl/20200215/20200215-04:10:30.json → reference height: 617437
dataset_2020/crawl/20200215/20200215-01:15:11.json → reference height: 617414
dataset_2020/crawl/20200215/20200215-17:18:40.json → reference height: 617509
dataset_2020/crawl/20200215/20200215-02:11:00.json → reference height: 617425
dataset_2020/crawl/20200215/20200215-04:18:40.json → reference height: 617438
dataset_2020/crawl/20200215/20200215-12:39:01.json → reference height: 617487
dataset_2020/crawl/20200215/20200215-07:54:41.json → reference height: 617452
dataset_2020/crawl/20200215/20200215-17:10:40.json → reference height: 617509
dataset_2020/crawl/20200215/20200215-14:43:11.json → reference height: 617494
dataset_2020/crawl/20200215/20200215-13:26:50.json → reference height: 617490
dataset_2020/crawl/20200215/20200215-11:15:00.json → reference height: 617472
dataset_2020/crawl/20200215/20200215-01:03:20.json → reference height: 617414
dataset_2020/crawl/20200215/20200215-13:35:00.json → reference height: 617490
dataset_2020/crawl/20200215/20200215-13:06:50.json → reference height: 617488
dataset_2020/crawl/20200215/20200215-20:50:40.json → reference height: 617535
dataset_2020/crawl/20200215/20200215-01:59:00.json → reference height: 617424
dataset_2020/crawl/20200215/20200215-09:10:50.json → reference height: 617458
dataset_2020/crawl/20200215/20200215-08:26:30.json → reference height: 617456
dataset_2020/crawl/20200215/20200215-00:43:11.json → reference height: 617411
dataset_2020/crawl/20200215/20200215-02:03:00.json → reference height: 617425
dataset_2020/crawl/20200215/20200215-13:55:10.json → reference height: 617490
dataset_2020/crawl/20200215/20200215-20:58:50.json → reference height: 617537
dataset_2020/crawl/20200215/20200215-13:51:00.json → reference height: 617490

investigation is done and
Extraction of p2p dataset pipeline

In [ ]:
import os

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

os.makedirs(PROCESSED_DIR, exist_ok=True)

print("Processed directory:")
print(PROCESSED_DIR)

Processed directory:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed

In [ ]:
from datetime import datetime
from pathlib import PurePosixPath

def snapshot_datetime(path):
    filename = PurePosixPath(path).stem
    return datetime.strptime(filename, "%Y%m%d-%H:%M:%S")

crawl_jsons_sorted = sorted(
    crawl_jsons,
    key=snapshot_datetime
)

print("First 10 snapshots:")

for x in crawl_jsons_sorted[:10]:
    print(x)

print("\nLast 10 snapshots:")

for x in crawl_jsons_sorted[-10:]:
    print(x)

First 10 snapshots:
dataset_2020/crawl/20200207/20200207-00:03:07.json
dataset_2020/crawl/20200207/20200207-00:07:07.json
dataset_2020/crawl/20200207/20200207-00:11:17.json
dataset_2020/crawl/20200207/20200207-00:14:57.json
dataset_2020/crawl/20200207/20200207-00:19:07.json
dataset_2020/crawl/20200207/20200207-00:22:57.json
dataset_2020/crawl/20200207/20200207-00:27:07.json
dataset_2020/crawl/20200207/20200207-00:31:07.json
dataset_2020/crawl/20200207/20200207-00:35:07.json
dataset_2020/crawl/20200207/20200207-00:39:07.json

Last 10 snapshots:
dataset_2020/crawl/20200709/20200709-22:06:56.json
dataset_2020/crawl/20200709/20200709-22:18:07.json
dataset_2020/crawl/20200709/20200709-22:28:49.json
dataset_2020/crawl/20200709/20200709-22:39:50.json
dataset_2020/crawl/20200709/20200709-22:51:21.json
dataset_2020/crawl/20200709/20200709-23:03:04.json
dataset_2020/crawl/20200709/20200709-23:14:26.json
dataset_2020/crawl/20200709/20200709-23:25:29.json
dataset_2020/crawl/20200709/20200709-23:37:00.json
dataset_2020/crawl/20200709/20200709-23:48:52.json

In [ ]:
PILOT_DATE = "20200215"

pilot_files = [
    name
    for name in crawl_jsons_sorted
    if f"/{PILOT_DATE}/" in name
]

print("Pilot snapshots:", len(pilot_files))

print("\nFirst:")
print(pilot_files[0])

print("\nLast:")
print(pilot_files[-1])

Pilot snapshots: 360

First:
dataset_2020/crawl/20200215/20200215-00:03:21.json

Last:
dataset_2020/crawl/20200215/20200215-23:58:41.json

In [ ]:
import pyarrow as pa
import pyarrow.parquet as pq

print("PyArrow:", pa.__version__)

PyArrow: 23.0.1

In [ ]:
import zipfile
import json
import pandas as pd

pilot_output = os.path.join(
    PROCESSED_DIR,
    "p2p_observations_20200215.parquet"
)

rows = []

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for i, json_file in enumerate(pilot_files, start=1):

        timestamp = snapshot_datetime(json_file)

        with z.open(json_file) as f:
            snapshot = json.load(f)

        for record in snapshot:

            node_info, port, service, height = record
            node_id, ip = node_info

            rows.append({
                "timestamp": timestamp,
                "node_id": node_id,
                "ip": ip,
                "port": port,
                "service": service,
                "reported_height": height
            })

        if i % 50 == 0:
            print(
                f"Processed {i}/{len(pilot_files)} snapshots | "
                f"rows={len(rows):,}"
            )

pilot_df = pd.DataFrame(rows)

pilot_df.to_parquet(
    pilot_output,
    index=False
)

print("\nFinished.")
print("Rows:", len(pilot_df))
print("Output:", pilot_output)
print("Size MB:", os.path.getsize(pilot_output) / (1024**2))

Processed 50/360 snapshots | rows=364,333
Processed 100/360 snapshots | rows=728,055
Processed 150/360 snapshots | rows=1,093,447
Processed 200/360 snapshots | rows=1,460,064
Processed 250/360 snapshots | rows=1,828,099
Processed 300/360 snapshots | rows=2,195,756
Processed 350/360 snapshots | rows=2,563,403

Finished.
Rows: 2636768
Output: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_observations_20200215.parquet
Size MB: 12.518689155578613

In [ ]:
pilot_check = pd.read_parquet(pilot_output)

print("Shape:", pilot_check.shape)

print("\nColumns:")
print(pilot_check.columns.tolist())

print("\nDtypes:")
print(pilot_check.dtypes)

print("\nMissing values:")
print(pilot_check.isna().sum())

print("\nFirst rows:")
display(pilot_check.head())

print("\nUnique nodes:")
print(pilot_check["node_id"].nunique())

print("\nUnique IPs:")
print(pilot_check["ip"].nunique())

print("\nUnique ports:")
print(pilot_check["port"].nunique())

Shape: (2636768, 6)

Columns:
['timestamp', 'node_id', 'ip', 'port', 'service', 'reported_height']

Dtypes:
timestamp          datetime64[ns]
node_id                    object
ip                         object
port                        int64
service                     int64
reported_height             int64
dtype: object

Missing values:
timestamp          0
node_id            0
ip                 0
port               0
service            0
reported_height    0
dtype: int64

First rows:

,timestamp,node_id,ip,port,service,reported_height
0,2020-02-15 00:03:21,bf4cbf26150152d044c036ae4c716b563b5399af67c75d...,85.25.134.0,8333,1037,617408
1,2020-02-15 00:03:21,d8ca90b44e9fd28f3f1e72ef331466466f92120adfd3ad...,206.189.138.0,8333,1036,617408
2,2020-02-15 00:03:21,9d0a653318adfa5575afd01b0ecec499dddc6391791bef...,68.36.95.0,8333,1037,617408
3,2020-02-15 00:03:21,9edf44d735ff2dc2e381ca9d832a86b5b4def4d1924e46...,176.191.182.0,8333,1033,617408
4,2020-02-15 00:03:21,1c8aefb4c740454e82d217fc8dcf4e7426f19f0393fc83...,202.186.228.0,8333,1033,617408

Unique nodes:
8753

Unique IPs:
8081

Unique ports:
182

In [ ]:
pilot_check = pd.read_parquet(pilot_output)

print("Shape:", pilot_check.shape)

print("\nColumns:")
print(pilot_check.columns.tolist())

print("\nDtypes:")
print(pilot_check.dtypes)

print("\nMissing values:")
print(pilot_check.isna().sum())

print("\nFirst rows:")
display(pilot_check.head())

print("\nUnique nodes:")
print(pilot_check["node_id"].nunique())

print("\nUnique IPs:")
print(pilot_check["ip"].nunique())

print("\nUnique ports:")
print(pilot_check["port"].nunique())

Shape: (2636768, 6)

Columns:
['timestamp', 'node_id', 'ip', 'port', 'service', 'reported_height']

Dtypes:
timestamp          datetime64[ns]
node_id                    object
ip                         object
port                        int64
service                     int64
reported_height             int64
dtype: object

Missing values:
timestamp          0
node_id            0
ip                 0
port               0
service            0
reported_height    0
dtype: int64

First rows:

,timestamp,node_id,ip,port,service,reported_height
0,2020-02-15 00:03:21,bf4cbf26150152d044c036ae4c716b563b5399af67c75d...,85.25.134.0,8333,1037,617408
1,2020-02-15 00:03:21,d8ca90b44e9fd28f3f1e72ef331466466f92120adfd3ad...,206.189.138.0,8333,1036,617408
2,2020-02-15 00:03:21,9d0a653318adfa5575afd01b0ecec499dddc6391791bef...,68.36.95.0,8333,1037,617408
3,2020-02-15 00:03:21,9edf44d735ff2dc2e381ca9d832a86b5b4def4d1924e46...,176.191.182.0,8333,1033,617408
4,2020-02-15 00:03:21,1c8aefb4c740454e82d217fc8dcf4e7426f19f0393fc83...,202.186.228.0,8333,1033,617408

Unique nodes:
8753

Unique IPs:
8081

Unique ports:
182

In [ ]:
duplicate_rows = (
    pilot_check
    .groupby(["timestamp", "node_id"])
    .size()
    .reset_index(name="count")
)

duplicate_rows = duplicate_rows[
    duplicate_rows["count"] > 1
]

print(
    "Timestamp + node_id groups with multiple observations:",
    len(duplicate_rows)
)

display(duplicate_rows.head(10))

Timestamp + node_id groups with multiple observations: 21053

,timestamp,node_id,count
218,2020-02-15 00:03:21,0765826ae5db55bcec2b08342d3e37b4f85d948b3b9ea7...,2
397,2020-02-15 00:03:21,0e392ed227f42bab094d25e30710779d7b067c0b32dd64...,2
642,2020-02-15 00:03:21,16ff89d2a7befde50f5882d18ba36622a3b806f12c9a9e...,2
647,2020-02-15 00:03:21,171c10876973a312c48cf405c954b46744adcec6f6e034...,2
769,2020-02-15 00:03:21,1bb2fe18304f64ec695404bf9606bf74141104d4152dfa...,2
847,2020-02-15 00:03:21,1e80113fa3d98fb1dec76993bdb77ebd3c19391e6e4389...,2
1081,2020-02-15 00:03:21,27a745eed9138857c6aa43b21236ee564a588e91c55cc7...,2
1097,2020-02-15 00:03:21,287ce5149b712ec81ef70da6f838a5a2c3e8271ce1dba3...,2
1233,2020-02-15 00:03:21,2d8dafabc4815012a5f145af1ccab703e75385922cb81a...,3
1447,2020-02-15 00:03:21,3599d097595c5cda45ea923aec127b7b327c356a69998d...,2

In [ ]:
snapshot_reference = (
    pilot_check[
        pilot_check["reported_height"] > 0
    ]
    .groupby("timestamp")["reported_height"]
    .median()
    .rename("reference_height")
    .reset_index()
)

snapshot_reference["reference_height"] = (
    snapshot_reference["reference_height"]
    .round()
    .astype("int64")
)

display(snapshot_reference.head())

            timestamp  reference_height
0 2020-02-15 00:03:21            617408
1 2020-02-15 00:07:20            617409
2 2020-02-15 00:11:20            617409
3 2020-02-15 00:15:10            617409
4 2020-02-15 00:19:30            617410

In [ ]:
pilot_features = pilot_check.merge(
    snapshot_reference,
    on="timestamp",
    how="left"
)

pilot_features["height_deviation"] = (
    pilot_features["reported_height"]
    - pilot_features["reference_height"]
)

pilot_features["absolute_height_deviation"] = (
    pilot_features["height_deviation"]
    .abs()
)

pilot_features["height_ahead"] = (
    pilot_features["height_deviation"] > 0
).astype("int8")

pilot_features["height_behind"] = (
    pilot_features["height_deviation"] < 0
).astype("int8")

display(
    pilot_features[
        [
            "timestamp",
            "node_id",
            "port",
            "reported_height",
            "reference_height",
            "height_deviation",
            "absolute_height_deviation"
        ]
    ].head(20)
)

,timestamp,node_id,port,reported_height,reference_height,height_deviation,absolute_height_deviation
0,2020-02-15 00:03:21,bf4cbf26150152d044c036ae4c716b563b5399af67c75d...,8333,617408,617408,0,0
1,2020-02-15 00:03:21,d8ca90b44e9fd28f3f1e72ef331466466f92120adfd3ad...,8333,617408,617408,0,0
2,2020-02-15 00:03:21,9d0a653318adfa5575afd01b0ecec499dddc6391791bef...,8333,617408,617408,0,0
3,2020-02-15 00:03:21,9edf44d735ff2dc2e381ca9d832a86b5b4def4d1924e46...,8333,617408,617408,0,0
4,2020-02-15 00:03:21,1c8aefb4c740454e82d217fc8dcf4e7426f19f0393fc83...,8333,617408,617408,0,0
5,2020-02-15 00:03:21,2bdf6b6029e1b75e1edbdd27d6b129843eb22b4ca70418...,8333,617408,617408,0,0
6,2020-02-15 00:03:21,e459aeba62753812bd4938641f6a24af9eb3cd092851da...,8333,617408,617408,0,0
7,2020-02-15 00:03:21,4de7ff0b8c19c5cf6a840466e7061462e12e9fd57e3c58...,8333,617408,617408,0,0
8,2020-02-15 00:03:21,079b7b072d0eaca0b2a93e9b1a73ee14cad192934e9b39...,8333,617408,617408,0,0
9,2020-02-15 00:03:21,226cbde6ec758db65412d59d0859debbe411925f5b7a2c...,20000,617408,617408,0,0
10,2020-02-15 00:03:21,e9e59dd6d12c2eed0f2a8cd1c26fd3f8c938a1681ed1f5...,8333,617408,617408,0,0
11,2020-02-15 00:03:21,e9662e63d1e93099b9f012286f9e49f154ee064026e2d9...,8333,617408,617408,0,0
12,2020-02-15 00:03:21,e58a6e14a912985c5f13f5491b5ace8bfa5dc8703ee777...,8333,617408,617408,0,0
13,2020-02-15 00:03:21,eb7685fb64276bd6beec66da75df756852c93b56d34c08...,8333,617408,617408,0,0
14,2020-02-15 00:03:21,bdb3b09a7001b22a679a967161dcd0d79eb9c49114a72b...,8333,617408,617408,0,0
15,2020-02-15 00:03:21,5619698291a9e5faf35afed736d896ef62e7ba2dee41f8...,9333,617408,617408,0,0
16,2020-02-15 00:03:21,41a1e8ce09c2c2b0175dce820efa812a0f30bc32dcf986...,8333,617408,617408,0,0
17,2020-02-15 00:03:21,f14f214ac4e12d26ff51f0571ebbcd84d9d5f71cab8981...,8333,617408,617408,0,0
18,2020-02-15 00:03:21,ec6c78b81c6737f01447da8d138e03b3b1ab20d4d36ab8...,8333,617405,617408,-3,3
19,2020-02-15 00:03:21,3cd174d56898ed0bb9295a393a82e71ac8790c42efb498...,8333,617408,617408,0,0

Full P2P extraction

In [ ]:
import os

OBS_DIR = os.path.join(
    PROCESSED_DIR,
    "observations"
)

META_DIR = os.path.join(
    PROCESSED_DIR,
    "metadata"
)

os.makedirs(OBS_DIR, exist_ok=True)
os.makedirs(META_DIR, exist_ok=True)

print("Observation directory:")
print(OBS_DIR)

print("\nMetadata directory:")
print(META_DIR)

Observation directory:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/observations

Metadata directory:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/metadata

In [ ]:
from collections import Counter
from pathlib import PurePosixPath

date_counts = Counter()

for name in crawl_jsons_sorted:

    parts = PurePosixPath(name).parts

    date = parts[2]

    date_counts[date] += 1

print("Dates:", len(date_counts))

for date, count in sorted(date_counts.items()):
    print(date, "→", count, "snapshots")

Dates: 27
20200207 → 360 snapshots
20200208 → 360 snapshots
20200209 → 360 snapshots
20200210 → 360 snapshots
20200211 → 360 snapshots
20200212 → 360 snapshots
20200213 → 360 snapshots
20200214 → 360 snapshots
20200215 → 360 snapshots
20200216 → 360 snapshots
20200217 → 360 snapshots
20200218 → 360 snapshots
20200219 → 360 snapshots
20200220 → 360 snapshots
20200221 → 360 snapshots
20200222 → 360 snapshots
20200223 → 360 snapshots
20200224 → 360 snapshots
20200225 → 360 snapshots
20200226 → 360 snapshots
20200227 → 360 snapshots
20200228 → 360 snapshots
20200229 → 360 snapshots
20200301 → 360 snapshots
20200302 → 360 snapshots
20200607 → 360 snapshots
20200709 → 121 snapshots

In [ ]:
import zipfile
import json
import os
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

# ---------------------------------------------------------
# Output schema
# ---------------------------------------------------------

schema = pa.schema([
    ("timestamp", pa.timestamp("ns")),
    ("node_id", pa.string()),
    ("ip", pa.string()),
    ("port", pa.int64()),
    ("service", pa.int64()),
    ("reported_height", pa.int64()),
])

# ---------------------------------------------------------
# Group snapshots by date
# ---------------------------------------------------------

snapshots_by_date = {}

for name in crawl_jsons_sorted:

    parts = name.split("/")
    date = parts[2]

    snapshots_by_date.setdefault(date, []).append(name)

print("Dates to process:", len(snapshots_by_date))
print("Total snapshots:",
      sum(len(v) for v in snapshots_by_date.values()))

# ---------------------------------------------------------
# Process ZIP
# ---------------------------------------------------------

metadata_rows = []

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    for date_index, (date, files) in enumerate(
        sorted(snapshots_by_date.items()),
        start=1
    ):

        output_file = os.path.join(
            OBS_DIR,
            f"p2p_observations_{date}.parquet"
        )

        print("\n" + "=" * 80)
        print(
            f"[{date_index}/{len(snapshots_by_date)}] "
            f"Processing {date}"
        )
        print("Snapshots:", len(files))
        print("=" * 80)

        writer = None
        total_rows = 0

        try:

            for i, json_file in enumerate(files, start=1):

                timestamp = snapshot_datetime(json_file)

                with z.open(json_file) as f:
                    snapshot = json.load(f)

                rows = []

                heights = []

                for record in snapshot:

                    node_info, port, service, height = record

                    node_id, ip = node_info

                    rows.append({
                        "timestamp": timestamp,
                        "node_id": node_id,
                        "ip": ip,
                        "port": port,
                        "service": service,
                        "reported_height": height
                    })

                    if isinstance(height, int) and height > 0:
                        heights.append(height)

                # -----------------------------------------
                # Calculate snapshot reference height
                # -----------------------------------------

                reference_height = (
                    int(pd.Series(heights).median())
                    if heights
                    else None
                )

                node_ids = [
                    row["node_id"]
                    for row in rows
                ]

                unique_nodes = len(set(node_ids))

                duplicate_nodes = (
                    len(node_ids) - unique_nodes
                )

                # -----------------------------------------
                # Record metadata
                # -----------------------------------------

                metadata_rows.append({
                    "timestamp": timestamp,
                    "date": date,
                    "snapshot_file": json_file,
                    "record_count": len(rows),
                    "unique_node_count": unique_nodes,
                    "duplicate_node_records": duplicate_nodes,
                    "reference_height": reference_height
                })

                # -----------------------------------------
                # Convert only this snapshot to Arrow
                # -----------------------------------------

                df = pd.DataFrame(rows)

                table = pa.Table.from_pandas(
                    df,
                    schema=schema,
                    preserve_index=False
                )

                if writer is None:

                    writer = pq.ParquetWriter(
                        output_file,
                        schema,
                        compression="snappy"
                    )

                writer.write_table(table)

                total_rows += len(df)

                # Explicitly release snapshot objects
                del rows
                del df
                del table
                del snapshot

                if i % 50 == 0 or i == len(files):

                    print(
                        f"  {i:3d}/{len(files)} snapshots | "
                        f"rows={total_rows:,}"
                    )

        finally:

            if writer is not None:
                writer.close()

        print(
            f"Finished {date}: "
            f"{total_rows:,} rows"
        )

        print(
            f"File size: "
            f"{os.path.getsize(output_file) / (1024**2):.2f} MB"
        )

# ---------------------------------------------------------
# Save snapshot metadata
# ---------------------------------------------------------

metadata_df = pd.DataFrame(metadata_rows)

metadata_file = os.path.join(
    META_DIR,
    "p2p_snapshot_metadata.parquet"
)

metadata_df.to_parquet(
    metadata_file,
    index=False
)

print("\n" + "=" * 80)
print("FULL EXTRACTION COMPLETE")
print("=" * 80)

print("Total snapshots:", len(metadata_df))

print(
    "Total observations:",
    metadata_df["record_count"].sum()
)

print(
    "Metadata file:",
    metadata_file
)

Dates to process: 27
Total snapshots: 9481

================================================================================
[1/27] Processing 20200207
Snapshots: 360
================================================================================
   50/360 snapshots | rows=368,428
  100/360 snapshots | rows=731,019
  150/360 snapshots | rows=1,093,077
  200/360 snapshots | rows=1,455,580
  250/360 snapshots | rows=1,822,692
  300/360 snapshots | rows=2,190,846
  350/360 snapshots | rows=2,559,874
  360/360 snapshots | rows=2,633,401
Finished 20200207: 2,633,401 rows
File size: 194.98 MB

================================================================================
[2/27] Processing 20200208
Snapshots: 360
================================================================================
   50/360 snapshots | rows=364,686
  100/360 snapshots | rows=727,669
  150/360 snapshots | rows=1,092,857
  200/360 snapshots | rows=1,459,538
  250/360 snapshots | rows=1,826,554
  300/360 snapshots | rows=2,194,417
  350/360 snapshots | rows=2,562,622
  360/360 snapshots | rows=2,636,369
Finished 20200208: 2,636,369 rows
File size: 194.77 MB

================================================================================
[3/27] Processing 20200209
Snapshots: 360
================================================================================
   50/360 snapshots | rows=366,651
  100/360 snapshots | rows=733,374
  150/360 snapshots | rows=1,099,624
  200/360 snapshots | rows=1,466,640
  250/360 snapshots | rows=1,834,647
  300/360 snapshots | rows=2,203,754
  350/360 snapshots | rows=2,572,864
  360/360 snapshots | rows=2,646,914
Finished 20200209: 2,646,914 rows
File size: 195.55 MB

================================================================================
[4/27] Processing 20200210
Snapshots: 360
================================================================================
   50/360 snapshots | rows=370,356
  100/360 snapshots | rows=738,485
  150/360 snapshots | rows=1,105,363
  200/360 snapshots | rows=1,473,673
  250/360 snapshots | rows=1,842,927
  300/360 snapshots | rows=2,211,999
  350/360 snapshots | rows=2,582,796
  360/360 snapshots | rows=2,656,680
Finished 20200210: 2,656,680 rows
File size: 196.46 MB

================================================================================
[5/27] Processing 20200211
Snapshots: 360
================================================================================
   50/360 snapshots | rows=368,498
  100/360 snapshots | rows=735,071
  150/360 snapshots | rows=1,101,204
  200/360 snapshots | rows=1,462,550
  250/360 snapshots | rows=1,828,703
  300/360 snapshots | rows=2,196,781
  350/360 snapshots | rows=2,565,451
  360/360 snapshots | rows=2,638,981
Finished 20200211: 2,638,981 rows
File size: 194.49 MB

================================================================================
[6/27] Processing 20200212
Snapshots: 360
================================================================================
   50/360 snapshots | rows=364,976
  100/360 snapshots | rows=729,954
  150/360 snapshots | rows=1,095,278
  200/360 snapshots | rows=1,462,497
  250/360 snapshots | rows=1,829,735
  300/360 snapshots | rows=2,197,106
  350/360 snapshots | rows=2,565,114
  360/360 snapshots | rows=2,638,569
Finished 20200212: 2,638,569 rows
File size: 194.44 MB

================================================================================
[7/27] Processing 20200213
Snapshots: 360
================================================================================
   50/360 snapshots | rows=365,984
  100/360 snapshots | rows=732,325
  150/360 snapshots | rows=1,097,412
  200/360 snapshots | rows=1,463,047
  250/360 snapshots | rows=1,828,725
  300/360 snapshots | rows=2,194,751
  350/360 snapshots | rows=2,560,837
  360/360 snapshots | rows=2,633,697
Finished 20200213: 2,633,697 rows
File size: 194.56 MB

================================================================================
[8/27] Processing 20200214
Snapshots: 360
================================================================================
   50/360 snapshots | rows=364,304
  100/360 snapshots | rows=729,514
  150/360 snapshots | rows=1,093,158
  200/360 snapshots | rows=1,456,375
  250/360 snapshots | rows=1,820,107
  300/360 snapshots | rows=2,185,547
  350/360 snapshots | rows=2,552,015
  360/360 snapshots | rows=2,625,180
Finished 20200214: 2,625,180 rows
File size: 193.62 MB

================================================================================
[9/27] Processing 20200215
Snapshots: 360
================================================================================
   50/360 snapshots | rows=364,333
  100/360 snapshots | rows=728,055
  150/360 snapshots | rows=1,093,447
  200/360 snapshots | rows=1,460,064
  250/360 snapshots | rows=1,828,099
  300/360 snapshots | rows=2,195,756
  350/360 snapshots | rows=2,563,403
  360/360 snapshots | rows=2,636,768
Finished 20200215: 2,636,768 rows
File size: 194.58 MB

================================================================================
[10/27] Processing 20200216
Snapshots: 360
================================================================================
   50/360 snapshots | rows=365,361
  100/360 snapshots | rows=729,134
  150/360 snapshots | rows=1,093,136
  200/360 snapshots | rows=1,458,933
  250/360 snapshots | rows=1,824,808
  300/360 snapshots | rows=2,191,661
  350/360 snapshots | rows=2,559,579
  360/360 snapshots | rows=2,632,923
Finished 20200216: 2,632,923 rows
File size: 194.19 MB

================================================================================
[11/27] Processing 20200217
Snapshots: 360
================================================================================
   50/360 snapshots | rows=364,951
  100/360 snapshots | rows=728,457
  150/360 snapshots | rows=1,091,552
  200/360 snapshots | rows=1,456,333
  250/360 snapshots | rows=1,819,877
  300/360 snapshots | rows=2,184,557
  350/360 snapshots | rows=2,550,601
  360/360 snapshots | rows=2,623,639
Finished 20200217: 2,623,639 rows
File size: 194.13 MB

================================================================================
[12/27] Processing 20200218
Snapshots: 360
================================================================================
   50/360 snapshots | rows=364,498
  100/360 snapshots | rows=727,396
  150/360 snapshots | rows=1,091,742
  200/360 snapshots | rows=1,458,482
  250/360 snapshots | rows=1,824,778
  300/360 snapshots | rows=2,191,073
  350/360 snapshots | rows=2,557,090
  360/360 snapshots | rows=2,629,960
Finished 20200218: 2,629,960 rows
File size: 194.35 MB

================================================================================
[13/27] Processing 20200219
Snapshots: 360
================================================================================
   50/360 snapshots | rows=363,636
  100/360 snapshots | rows=728,718
  150/360 snapshots | rows=1,092,719
  200/360 snapshots | rows=1,457,388
  250/360 snapshots | rows=1,822,832
  300/360 snapshots | rows=2,188,854
  350/360 snapshots | rows=2,555,315
  360/360 snapshots | rows=2,628,659
Finished 20200219: 2,628,659 rows
File size: 194.30 MB

================================================================================
[14/27] Processing 20200220
Snapshots: 360
================================================================================
   50/360 snapshots | rows=365,696
  100/360 snapshots | rows=731,487
  150/360 snapshots | rows=1,097,909
  200/360 snapshots | rows=1,464,587
  250/360 snapshots | rows=1,830,851
  300/360 snapshots | rows=2,197,317
  350/360 snapshots | rows=2,563,610
  360/360 snapshots | rows=2,636,588
Finished 20200220: 2,636,588 rows
File size: 194.96 MB

================================================================================
[15/27] Processing 20200221
Snapshots: 360
================================================================================
   50/360 snapshots | rows=363,856
  100/360 snapshots | rows=728,608
  150/360 snapshots | rows=1,092,673
  200/360 snapshots | rows=1,449,464
  250/360 snapshots | rows=1,808,620
  300/360 snapshots | rows=2,171,347
  350/360 snapshots | rows=2,537,284
  360/360 snapshots | rows=2,610,245
Finished 20200221: 2,610,245 rows
File size: 192.95 MB

================================================================================
[16/27] Processing 20200222
Snapshots: 360
================================================================================
   50/360 snapshots | rows=365,114
  100/360 snapshots | rows=728,261
  150/360 snapshots | rows=1,092,575
  200/360 snapshots | rows=1,459,686
  250/360 snapshots | rows=1,827,429
  300/360 snapshots | rows=2,195,959
  350/360 snapshots | rows=2,564,763
  360/360 snapshots | rows=2,638,409
Finished 20200222: 2,638,409 rows
File size: 195.24 MB

================================================================================
[17/27] Processing 20200223
Snapshots: 360
================================================================================
   50/360 snapshots | rows=366,448
  100/360 snapshots | rows=732,057
  150/360 snapshots | rows=1,097,971
  200/360 snapshots | rows=1,464,179
  250/360 snapshots | rows=1,832,844
  300/360 snapshots | rows=2,202,616
  350/360 snapshots | rows=2,573,649
  360/360 snapshots | rows=2,647,621
Finished 20200223: 2,647,621 rows
File size: 195.84 MB

================================================================================
[18/27] Processing 20200224
Snapshots: 360
================================================================================
   50/360 snapshots | rows=368,486
  100/360 snapshots | rows=735,686
  150/360 snapshots | rows=1,102,358
  200/360 snapshots | rows=1,470,394
  250/360 snapshots | rows=1,838,454
  300/360 snapshots | rows=2,207,198
  350/360 snapshots | rows=2,575,795
  360/360 snapshots | rows=2,649,541
Finished 20200224: 2,649,541 rows
File size: 195.97 MB

================================================================================
[19/27] Processing 20200225
Snapshots: 360
================================================================================
   50/360 snapshots | rows=367,497
  100/360 snapshots | rows=734,782
  150/360 snapshots | rows=1,101,594
  200/360 snapshots | rows=1,469,338
  250/360 snapshots | rows=1,836,962
  300/360 snapshots | rows=2,205,062
  350/360 snapshots | rows=2,572,700
  360/360 snapshots | rows=2,645,666
Finished 20200225: 2,645,666 rows
File size: 195.81 MB

================================================================================
[20/27] Processing 20200226
Snapshots: 360
================================================================================
   50/360 snapshots | rows=365,296
  100/360 snapshots | rows=730,948
  150/360 snapshots | rows=1,096,129
  200/360 snapshots | rows=1,462,109
  250/360 snapshots | rows=1,829,009
  300/360 snapshots | rows=2,196,242
  350/360 snapshots | rows=2,562,987
  360/360 snapshots | rows=2,636,177
Finished 20200226: 2,636,177 rows
File size: 195.12 MB

================================================================================
[21/27] Processing 20200227
Snapshots: 360
================================================================================
   50/360 snapshots | rows=357,149
  100/360 snapshots | rows=713,115
  150/360 snapshots | rows=1,068,938
  200/360 snapshots | rows=1,426,264
  250/360 snapshots | rows=1,784,460
  300/360 snapshots | rows=2,142,710
  350/360 snapshots | rows=2,498,962
  360/360 snapshots | rows=2,567,514
Finished 20200227: 2,567,514 rows
File size: 190.24 MB

================================================================================
[22/27] Processing 20200228
Snapshots: 360
================================================================================
   50/360 snapshots | rows=341,282
  100/360 snapshots | rows=682,055
  150/360 snapshots | rows=1,022,457
  200/360 snapshots | rows=1,364,232
  250/360 snapshots | rows=1,704,674
  300/360 snapshots | rows=2,045,298
  350/360 snapshots | rows=2,386,131
  360/360 snapshots | rows=2,454,232
Finished 20200228: 2,454,232 rows
File size: 180.95 MB

================================================================================
[23/27] Processing 20200229
Snapshots: 360
================================================================================
   50/360 snapshots | rows=339,952
  100/360 snapshots | rows=678,912
  150/360 snapshots | rows=1,018,956
  200/360 snapshots | rows=1,360,807
  250/360 snapshots | rows=1,703,947
  300/360 snapshots | rows=2,045,704
  350/360 snapshots | rows=2,386,673
  360/360 snapshots | rows=2,454,851
Finished 20200229: 2,454,851 rows
File size: 181.38 MB

================================================================================
[24/27] Processing 20200301
Snapshots: 360
================================================================================
   50/360 snapshots | rows=338,795
  100/360 snapshots | rows=676,337
  150/360 snapshots | rows=1,013,782
  200/360 snapshots | rows=1,352,331
  250/360 snapshots | rows=1,692,475
  300/360 snapshots | rows=2,034,353
  350/360 snapshots | rows=2,374,992
  360/360 snapshots | rows=2,442,849
Finished 20200301: 2,442,849 rows
File size: 180.70 MB

================================================================================
[25/27] Processing 20200302
Snapshots: 360
================================================================================
   50/360 snapshots | rows=337,396
  100/360 snapshots | rows=674,470
  150/360 snapshots | rows=1,012,274
  200/360 snapshots | rows=1,349,594
  250/360 snapshots | rows=1,686,862
  300/360 snapshots | rows=2,024,586
  350/360 snapshots | rows=2,362,276
  360/360 snapshots | rows=2,429,506
Finished 20200302: 2,429,506 rows
File size: 179.73 MB

================================================================================
[26/27] Processing 20200607
Snapshots: 360
================================================================================
   50/360 snapshots | rows=316,099
  100/360 snapshots | rows=630,193
  150/360 snapshots | rows=945,349
  200/360 snapshots | rows=1,260,786
  250/360 snapshots | rows=1,577,174
  300/360 snapshots | rows=1,894,501
  350/360 snapshots | rows=2,212,988
  360/360 snapshots | rows=2,276,546
Finished 20200607: 2,276,546 rows
File size: 168.79 MB

================================================================================
[27/27] Processing 20200709
Snapshots: 121
================================================================================
   50/121 snapshots | rows=317,441
  100/121 snapshots | rows=635,954
  121/121 snapshots | rows=768,871
Finished 20200709: 768,871 rows
File size: 56.92 MB

================================================================================
FULL EXTRACTION COMPLETE
================================================================================
Total snapshots: 9481
Total observations: 68120356
Metadata file: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/metadata/p2p_snapshot_metadata.parquet

In [ ]:
import glob
import os
import pandas as pd

observation_files = sorted(
    glob.glob(
        os.path.join(
            OBS_DIR,
            "p2p_observations_*.parquet"
        )
    )
)

print("Observation files:", len(observation_files))

total_rows = 0

for file in observation_files:

    df_info = pd.read_parquet(
        file,
        columns=["timestamp"]
    )

    rows = len(df_info)

    total_rows += rows

    print(
        os.path.basename(file),
        "→",
        f"{rows:,}",
        "rows |",
        f"{os.path.getsize(file)/(1024**2):.2f} MB"
    )

print("\nTOTAL ROWS:", f"{total_rows:,}")

Observation files: 27
p2p_observations_20200207.parquet → 2,633,401 rows | 194.98 MB
p2p_observations_20200208.parquet → 2,636,369 rows | 194.77 MB
p2p_observations_20200209.parquet → 2,646,914 rows | 195.55 MB
p2p_observations_20200210.parquet → 2,656,680 rows | 196.46 MB
p2p_observations_20200211.parquet → 2,638,981 rows | 194.49 MB
p2p_observations_20200212.parquet → 2,638,569 rows | 194.44 MB
p2p_observations_20200213.parquet → 2,633,697 rows | 194.56 MB
p2p_observations_20200214.parquet → 2,625,180 rows | 193.62 MB
p2p_observations_20200215.parquet → 2,636,768 rows | 194.58 MB
p2p_observations_20200216.parquet → 2,632,923 rows | 194.19 MB
p2p_observations_20200217.parquet → 2,623,639 rows | 194.13 MB
p2p_observations_20200218.parquet → 2,629,960 rows | 194.35 MB
p2p_observations_20200219.parquet → 2,628,659 rows | 194.30 MB
p2p_observations_20200220.parquet → 2,636,588 rows | 194.96 MB
p2p_observations_20200221.parquet → 2,610,245 rows | 192.95 MB
p2p_observations_20200222.parquet → 2,638,409 rows | 195.24 MB
p2p_observations_20200223.parquet → 2,647,621 rows | 195.84 MB
p2p_observations_20200224.parquet → 2,649,541 rows | 195.97 MB
p2p_observations_20200225.parquet → 2,645,666 rows | 195.81 MB
p2p_observations_20200226.parquet → 2,636,177 rows | 195.12 MB
p2p_observations_20200227.parquet → 2,567,514 rows | 190.24 MB
p2p_observations_20200228.parquet → 2,454,232 rows | 180.95 MB
p2p_observations_20200229.parquet → 2,454,851 rows | 181.38 MB
p2p_observations_20200301.parquet → 2,442,849 rows | 180.70 MB
p2p_observations_20200302.parquet → 2,429,506 rows | 179.73 MB
p2p_observations_20200607.parquet → 2,276,546 rows | 168.79 MB
p2p_observations_20200709.parquet → 768,871 rows | 56.92 MB

TOTAL ROWS: 68,120,356

In [ ]:
metadata_check = pd.read_parquet(
    metadata_file
)

print("Metadata shape:")
print(metadata_check.shape)

print("\nColumns:")
print(metadata_check.columns.tolist())

print("\nMissing values:")
print(metadata_check.isna().sum())

print("\nReference height sample:")
display(
    metadata_check[
        [
            "timestamp",
            "record_count",
            "unique_node_count",
            "duplicate_node_records",
            "reference_height"
        ]
    ].head(20)
)

Metadata shape:
(9481, 7)

Columns:
['timestamp', 'date', 'snapshot_file', 'record_count', 'unique_node_count', 'duplicate_node_records', 'reference_height']

Missing values:
timestamp                 0
date                      0
snapshot_file             0
record_count              0
unique_node_count         0
duplicate_node_records    0
reference_height          0
dtype: int64

Reference height sample:

,timestamp,record_count,unique_node_count,duplicate_node_records,reference_height
0,2020-02-07 00:03:07,7399,7336,63,616294
1,2020-02-07 00:07:07,7368,7306,62,616294
2,2020-02-07 00:11:17,7426,7363,63,616294
3,2020-02-07 00:14:57,7351,7288,63,616294
4,2020-02-07 00:19:07,7389,7327,62,616294
5,2020-02-07 00:22:57,7365,7301,64,616294
6,2020-02-07 00:27:07,7400,7336,64,616294
7,2020-02-07 00:31:07,7422,7357,65,616294
8,2020-02-07 00:35:07,7396,7331,65,616294
9,2020-02-07 00:39:07,7387,7322,65,616294
10,2020-02-07 00:43:07,7423,7357,66,616294
11,2020-02-07 00:47:07,7399,7335,64,616294
12,2020-02-07 00:51:17,7423,7357,66,616294
13,2020-02-07 00:55:08,7402,7335,67,616294
14,2020-02-07 00:59:17,7413,7349,64,616295
15,2020-02-07 01:03:07,7341,7277,64,616295
16,2020-02-07 01:07:17,7385,7319,66,616295
17,2020-02-07 01:11:17,7355,7291,64,616296
18,2020-02-07 01:15:07,7379,7312,67,616296
19,2020-02-07 01:19:08,7388,7322,66,616296

In [ ]:
expected_snapshots = len(crawl_jsons_sorted)

actual_snapshots = len(metadata_check)

print("Expected snapshots:", expected_snapshots)
print("Actual snapshots  :", actual_snapshots)

if expected_snapshots == actual_snapshots:
    print("✅ Snapshot count matches")
else:
    print("❌ Snapshot count mismatch")

Expected snapshots: 9481
Actual snapshots  : 9481
✅ Snapshot count matches

In [ ]:
print(
    "\nExpected dates:",
    len(date_counts)
)

print(
    "Extracted dates:",
    metadata_check["date"].nunique()
)

print(
    "\nTotal records:",
    metadata_check["record_count"].sum()
)

print(
    "Average records/snapshot:",
    metadata_check["record_count"].mean()
)

Expected dates: 27
Extracted dates: 27

Total records: 68120356
Average records/snapshot: 7184.933656787259

In [ ]:
import os
import glob
import pandas as pd

observation_files = sorted(
    glob.glob(
        os.path.join(
            OBS_DIR,
            "p2p_observations_*.parquet"
        )
    )
)

print("Observation files:", len(observation_files))

metadata = pd.read_parquet(metadata_file)

expected_rows = int(metadata["record_count"].sum())
expected_snapshots = len(metadata)

actual_rows = 0
results = []

for file in observation_files:

    df = pd.read_parquet(
        file,
        columns=["timestamp"]
    )

    rows = len(df)
    actual_rows += rows

    results.append({
        "file": os.path.basename(file),
        "rows": rows
    })

print("\nExpected snapshots:", expected_snapshots)
print("Metadata snapshots:", len(metadata))

print("\nExpected observations:",
      f"{expected_rows:,}")

print("Actual observations:",
      f"{actual_rows:,}")

print("\nDifference:",
      actual_rows - expected_rows)

if (
    expected_snapshots == 9481
    and actual_rows == expected_rows
):
    print("\n✅ FULL DATASET INTEGRITY CHECK PASSED")
else:
    print("\n❌ INTEGRITY CHECK FAILED")

display(pd.DataFrame(results))

Observation files: 27

Expected snapshots: 9481
Metadata snapshots: 9481

Expected observations: 68,120,356
Actual observations: 68,120,356

Difference: 0

✅ FULL DATASET INTEGRITY CHECK PASSED

                                 file     rows
0   p2p_observations_20200207.parquet  2633401
1   p2p_observations_20200208.parquet  2636369
2   p2p_observations_20200209.parquet  2646914
3   p2p_observations_20200210.parquet  2656680
4   p2p_observations_20200211.parquet  2638981
5   p2p_observations_20200212.parquet  2638569
6   p2p_observations_20200213.parquet  2633697
7   p2p_observations_20200214.parquet  2625180
8   p2p_observations_20200215.parquet  2636768
9   p2p_observations_20200216.parquet  2632923
10  p2p_observations_20200217.parquet  2623639
11  p2p_observations_20200218.parquet  2629960
12  p2p_observations_20200219.parquet  2628659
13  p2p_observations_20200220.parquet  2636588
14  p2p_observations_20200221.parquet  2610245
15  p2p_observations_20200222.parquet  2638409
16  p2p_observations_20200223.parquet  2647621
17  p2p_observations_20200224.parquet  2649541
18  p2p_observations_20200225.parquet  2645666
19  p2p_observations_20200226.parquet  2636177
20  p2p_observations_20200227.parquet  2567514
21  p2p_observations_20200228.parquet  2454232
22  p2p_observations_20200229.parquet  2454851
23  p2p_observations_20200301.parquet  2442849
24  p2p_observations_20200302.parquet  2429506
25  p2p_observations_20200607.parquet  2276546
26  p2p_observations_20200709.parquet   768871

In [ ]:
import pandas as pd
import glob
import os

files = sorted(
    glob.glob(
        os.path.join(
            OBS_DIR,
            "p2p_observations_*.parquet"
        )
    )
)

temporal_results = []

for file in files:

    df = pd.read_parquet(
        file,
        columns=["timestamp"]
    )

    temporal_results.append({
        "file": os.path.basename(file),
        "rows": len(df),
        "first_timestamp": df["timestamp"].min(),
        "last_timestamp": df["timestamp"].max()
    })

temporal_df = pd.DataFrame(temporal_results)

display(temporal_df)

,file,rows,first_timestamp,last_timestamp
0,p2p_observations_20200207.parquet,2633401,2020-02-07 00:03:07,2020-02-07 23:58:57
1,p2p_observations_20200208.parquet,2636369,2020-02-08 00:02:57,2020-02-08 23:59:07
2,p2p_observations_20200209.parquet,2646914,2020-02-09 00:03:07,2020-02-09 23:58:17
3,p2p_observations_20200210.parquet,2656680,2020-02-10 00:02:27,2020-02-10 23:58:57
4,p2p_observations_20200211.parquet,2638981,2020-02-11 00:02:57,2020-02-11 23:59:09
5,p2p_observations_20200212.parquet,2638569,2020-02-12 00:03:18,2020-02-12 23:58:59
6,p2p_observations_20200213.parquet,2633697,2020-02-13 00:03:09,2020-02-13 23:58:40
7,p2p_observations_20200214.parquet,2625180,2020-02-14 00:02:30,2020-02-14 23:59:20
8,p2p_observations_20200215.parquet,2636768,2020-02-15 00:03:21,2020-02-15 23:58:41
9,p2p_observations_20200216.parquet,2632923,2020-02-16 00:02:51,2020-02-16 23:59:01
10,p2p_observations_20200217.parquet,2623639,2020-02-17 00:03:21,2020-02-17 23:58:22
11,p2p_observations_20200218.parquet,2629960,2020-02-18 00:02:41,2020-02-18 23:59:02
12,p2p_observations_20200219.parquet,2628659,2020-02-19 00:03:02,2020-02-19 23:58:42
13,p2p_observations_20200220.parquet,2636588,2020-02-20 00:02:53,2020-02-20 23:58:54
14,p2p_observations_20200221.parquet,2610245,2020-02-21 00:02:44,2020-02-21 23:58:43
15,p2p_observations_20200222.parquet,2638409,2020-02-22 00:02:43,2020-02-22 23:58:54
16,p2p_observations_20200223.parquet,2647621,2020-02-23 00:02:43,2020-02-23 23:58:23
17,p2p_observations_20200224.parquet,2649541,2020-02-24 00:02:24,2020-02-24 23:58:43
18,p2p_observations_20200225.parquet,2645666,2020-02-25 00:02:44,2020-02-25 23:58:13
19,p2p_observations_20200226.parquet,2636177,2020-02-26 00:02:13,2020-02-26 23:58:53
20,p2p_observations_20200227.parquet,2567514,2020-02-27 00:02:43,2020-02-27 23:58:34
21,p2p_observations_20200228.parquet,2454232,2020-02-28 00:02:54,2020-02-28 23:58:14
22,p2p_observations_20200229.parquet,2454851,2020-02-29 00:02:24,2020-02-29 23:58:35
23,p2p_observations_20200301.parquet,2442849,2020-03-01 00:02:25,2020-03-01 23:58:25
24,p2p_observations_20200302.parquet,2429506,2020-03-02 00:02:26,2020-03-02 23:58:36
25,p2p_observations_20200607.parquet,2276546,2020-06-07 00:00:50,2020-06-07 23:57:10
26,p2p_observations_20200709.parquet,768871,2020-07-09 00:02:19,2020-07-09 23:48:52

In [ ]:
print("Overall first observation:")
print(temporal_df["first_timestamp"].min())

print("\nOverall last observation:")
print(temporal_df["last_timestamp"].max())

Overall first observation:
2020-02-07 00:03:07

Overall last observation:
2020-07-09 23:48:52

In [ ]:
import pyarrow.parquet as pq

expected_columns = [
    "timestamp",
    "node_id",
    "ip",
    "port",
    "service",
    "reported_height"
]

schema_results = []

for file in observation_files:

    df = pd.read_parquet(file)

    schema_results.append({
        "file": os.path.basename(file),
        "columns_ok": list(df.columns) == expected_columns,
        "missing_values": int(df.isna().sum().sum()),
        "rows": len(df)
    })

schema_df = pd.DataFrame(schema_results)

display(schema_df)

print(
    "\nAll columns correct:",
    schema_df["columns_ok"].all()
)

print(
    "Total missing values:",
    schema_df["missing_values"].sum()
)

                                 file  columns_ok  missing_values     rows
0   p2p_observations_20200207.parquet        True               0  2633401
1   p2p_observations_20200208.parquet        True               0  2636369
2   p2p_observations_20200209.parquet        True               0  2646914
3   p2p_observations_20200210.parquet        True               0  2656680
4   p2p_observations_20200211.parquet        True               0  2638981
5   p2p_observations_20200212.parquet        True               0  2638569
6   p2p_observations_20200213.parquet        True               0  2633697
7   p2p_observations_20200214.parquet        True               0  2625180
8   p2p_observations_20200215.parquet        True               0  2636768
9   p2p_observations_20200216.parquet        True               0  2632923
10  p2p_observations_20200217.parquet        True               0  2623639
11  p2p_observations_20200218.parquet        True               0  2629960
12  p2p_observations_20200219.parquet        True               0  2628659
13  p2p_observations_20200220.parquet        True               0  2636588
14  p2p_observations_20200221.parquet        True               0  2610245
15  p2p_observations_20200222.parquet        True               0  2638409
16  p2p_observations_20200223.parquet        True               0  2647621
17  p2p_observations_20200224.parquet        True               0  2649541
18  p2p_observations_20200225.parquet        True               0  2645666
19  p2p_observations_20200226.parquet        True               0  2636177
20  p2p_observations_20200227.parquet        True               0  2567514
21  p2p_observations_20200228.parquet        True               0  2454232
22  p2p_observations_20200229.parquet        True               0  2454851
23  p2p_observations_20200301.parquet        True               0  2442849
24  p2p_observations_20200302.parquet        True               0  2429506
25  p2p_observations_20200607.parquet        True               0  2276546
26  p2p_observations_20200709.parquet        True               0   768871

All columns correct: True
Total missing values: 0

In [ ]:
from collections import Counter

global_ports = Counter()
global_services = Counter()

total_rows = 0
unique_nodes = set()
unique_ips = set()

for file in observation_files:

    print(
        "Processing:",
        os.path.basename(file)
    )

    df = pd.read_parquet(
        file,
        columns=[
            "node_id",
            "ip",
            "port",
            "service"
        ]
    )

    total_rows += len(df)

    unique_nodes.update(
        df["node_id"].unique()
    )

    unique_ips.update(
        df["ip"].unique()
    )

    global_ports.update(
        df["port"].value_counts().to_dict()
    )

    global_services.update(
        df["service"].value_counts().to_dict()
    )

print("\n" + "=" * 70)
print("GLOBAL DATASET STATISTICS")
print("=" * 70)

print("Total observations:", f"{total_rows:,}")
print("Unique nodes:", f"{len(unique_nodes):,}")
print("Unique IPs:", f"{len(unique_ips):,}")
print("Unique ports:", f"{len(global_ports):,}")
print("Unique services:", f"{len(global_services):,}")

print("\nTop ports:")

for port, count in global_ports.most_common(20):
    print(f"{port:8} {count:,}")

print("\nTop services:")

for service, count in global_services.most_common(20):
    print(f"{service:8} {count:,}")

Processing: p2p_observations_20200207.parquet
Processing: p2p_observations_20200208.parquet
Processing: p2p_observations_20200209.parquet
Processing: p2p_observations_20200210.parquet
Processing: p2p_observations_20200211.parquet
Processing: p2p_observations_20200212.parquet
Processing: p2p_observations_20200213.parquet
Processing: p2p_observations_20200214.parquet
Processing: p2p_observations_20200215.parquet
Processing: p2p_observations_20200216.parquet
Processing: p2p_observations_20200217.parquet
Processing: p2p_observations_20200218.parquet
Processing: p2p_observations_20200219.parquet
Processing: p2p_observations_20200220.parquet
Processing: p2p_observations_20200221.parquet
Processing: p2p_observations_20200222.parquet
Processing: p2p_observations_20200223.parquet
Processing: p2p_observations_20200224.parquet
Processing: p2p_observations_20200225.parquet
Processing: p2p_observations_20200226.parquet
Processing: p2p_observations_20200227.parquet
Processing: p2p_observations_20200228.parquet
Processing: p2p_observations_20200229.parquet
Processing: p2p_observations_20200301.parquet
Processing: p2p_observations_20200302.parquet
Processing: p2p_observations_20200607.parquet
Processing: p2p_observations_20200709.parquet

======================================================================
GLOBAL DATASET STATISTICS
======================================================================
Total observations: 68,120,356
Unique nodes: 21,122
Unique IPs: 18,378
Unique ports: 275
Unique services: 27

Top ports:
    8333 64,315,685
    8433 440,455
    8335 189,299
    8334 153,581
    8885 148,019
    9333 117,058
    8444 102,372
   20008 101,117
   18333 84,905
   48333 82,117
    8446 80,864
    6333 77,104
    8332 74,559
   33333 63,634
    9595 57,723
    5001 57,445
   28833 51,746
    8339 51,579
    9001 47,751
   48533 42,892

Top services:
    1037 32,378,892
    1033 15,761,107
    1036 9,138,849
      13 4,811,851
    1032 2,151,045
      12 1,730,495
       5 971,421
       1 344,930
      77 209,125
      21 110,258
      37 107,159
       9 106,332
       4 70,553
      20 50,934
    1101 35,738
     141 28,359
      23 27,490
    1097 19,436
      73 18,018
      53 10,657

In [ ]:
node_counts = {}

for file in observation_files:

    print("Processing:", os.path.basename(file))

    df = pd.read_parquet(
        file,
        columns=["node_id"]
    )

    counts = df["node_id"].value_counts()

    for node_id, count in counts.items():

        node_counts[node_id] = (
            node_counts.get(node_id, 0)
            + int(count)
        )

print("Unique nodes:", len(node_counts))

node_frequency = pd.Series(
    node_counts,
    name="observation_count"
)

print("\nNode observation statistics:")
print(
    node_frequency.describe(
        percentiles=[
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.95,
            0.99
        ]
    )
)

Processing: p2p_observations_20200207.parquet
Processing: p2p_observations_20200208.parquet
Processing: p2p_observations_20200209.parquet
Processing: p2p_observations_20200210.parquet
Processing: p2p_observations_20200211.parquet
Processing: p2p_observations_20200212.parquet
Processing: p2p_observations_20200213.parquet
Processing: p2p_observations_20200214.parquet
Processing: p2p_observations_20200215.parquet
Processing: p2p_observations_20200216.parquet
Processing: p2p_observations_20200217.parquet
Processing: p2p_observations_20200218.parquet
Processing: p2p_observations_20200219.parquet
Processing: p2p_observations_20200220.parquet
Processing: p2p_observations_20200221.parquet
Processing: p2p_observations_20200222.parquet
Processing: p2p_observations_20200223.parquet
Processing: p2p_observations_20200224.parquet
Processing: p2p_observations_20200225.parquet
Processing: p2p_observations_20200226.parquet
Processing: p2p_observations_20200227.parquet
Processing: p2p_observations_20200228.parquet
Processing: p2p_observations_20200229.parquet
Processing: p2p_observations_20200301.parquet
Processing: p2p_observations_20200302.parquet
Processing: p2p_observations_20200607.parquet
Processing: p2p_observations_20200709.parquet
Unique nodes: 21122

Node observation statistics:
count    21122.000000
mean      3225.090238
std       3942.663012
min          1.000000
1%           1.000000
5%           7.000000
25%        129.250000
50%        481.000000
75%       7711.750000
95%       9475.000000
99%       9481.000000
max      28442.000000
Name: observation_count, dtype: float64

In [ ]:
node_frequency_df = (
    node_frequency
    .reset_index()
    .rename(
        columns={
            "index": "node_id"
        }
    )
)

node_frequency_file = os.path.join(
    PROCESSED_DIR,
    "node_observation_frequency.parquet"
)

node_frequency_df.to_parquet(
    node_frequency_file,
    index=False
)

print(
    "Saved:",
    node_frequency_file
)

print(
    "Rows:",
    len(node_frequency_df)
)

Saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/node_observation_frequency.parquet
Rows: 21122

the actual P2P feature-engineering phase

In [ ]:
import duckdb

print("DuckDB version:", duckdb.__version__)

DuckDB version: 1.3.2

In [ ]:
import duckdb
import os

con = duckdb.connect()

observation_glob = os.path.join(
    OBS_DIR,
    "p2p_observations_*.parquet"
)

query = f"""
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT node_id) AS unique_nodes,
    COUNT(DISTINCT ip) AS unique_ips,
    COUNT(DISTINCT port) AS unique_ports,
    COUNT(DISTINCT service) AS unique_services
FROM read_parquet('{observation_glob}')
"""

result = con.execute(query).fetchdf()

display(result)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  unique_nodes  unique_ips  unique_ports  unique_services
0    68120356         21122       18378           275               27

In [ ]:
metadata_glob = os.path.join(
    META_DIR,
    "p2p_snapshot_metadata.parquet"
)

query = f"""
SELECT
    o.timestamp,
    o.node_id,
    o.ip,
    o.port,
    o.service,
    o.reported_height,
    m.reference_height,

    o.reported_height - m.reference_height
        AS height_deviation,

    ABS(
        o.reported_height - m.reference_height
    )
        AS absolute_height_deviation

FROM read_parquet('{observation_glob}') o

LEFT JOIN read_parquet('{metadata_glob}') m
    ON o.timestamp = m.timestamp

LIMIT 10
"""

test_features = con.execute(query).fetchdf()

display(test_features)

,timestamp,node_id,ip,port,service,reported_height,reference_height,height_deviation,absolute_height_deviation
0,2020-02-07 00:03:07,24c7c31d5c1dee3296b30228b104de3032fdc03d835d00...,178.143.56.0,8333,1033,616294,616294,0,0
1,2020-02-07 00:03:07,bf4cbf26150152d044c036ae4c716b563b5399af67c75d...,85.25.134.0,8333,1037,616294,616294,0,0
2,2020-02-07 00:03:07,9d0a653318adfa5575afd01b0ecec499dddc6391791bef...,68.36.95.0,8333,1037,616294,616294,0,0
3,2020-02-07 00:03:07,9edf44d735ff2dc2e381ca9d832a86b5b4def4d1924e46...,176.191.182.0,8333,1033,616294,616294,0,0
4,2020-02-07 00:03:07,9024597a521af001f29bf5810b299e2a477ece0019b511...,111.90.158.0,8333,1037,616294,616294,0,0
5,2020-02-07 00:03:07,2bdf6b6029e1b75e1edbdd27d6b129843eb22b4ca70418...,1.255.226.0,8333,1037,616294,616294,0,0
6,2020-02-07 00:03:07,e459aeba62753812bd4938641f6a24af9eb3cd092851da...,23.175.0.0,8333,1033,616294,616294,0,0
7,2020-02-07 00:03:07,4de7ff0b8c19c5cf6a840466e7061462e12e9fd57e3c58...,54.82.229.0,8333,1033,616294,616294,0,0
8,2020-02-07 00:03:07,f3b8f0099ca9086a350d3e938834a946c398ffd95ad533...,176.9.73.0,8333,1033,616294,616294,0,0
9,2020-02-07 00:03:07,079b7b072d0eaca0b2a93e9b1a73ee14cad192934e9b39...,13.53.88.0,8333,1033,616294,616294,0,0

In [ ]:
metadata_glob = os.path.join(
    META_DIR,
    "p2p_snapshot_metadata.parquet"
)

query = f"""
SELECT
    o.timestamp,
    o.node_id,
    o.ip,
    o.port,
    o.service,
    o.reported_height,
    m.reference_height,

    o.reported_height - m.reference_height
        AS height_deviation,

    ABS(
        o.reported_height - m.reference_height
    )
        AS absolute_height_deviation

FROM read_parquet('{observation_glob}') o

LEFT JOIN read_parquet('{metadata_glob}') m
    ON o.timestamp = m.timestamp

LIMIT 10
"""

test_features = con.execute(query).fetchdf()

display(test_features)

,timestamp,node_id,ip,port,service,reported_height,reference_height,height_deviation,absolute_height_deviation
0,2020-02-07 00:03:07,24c7c31d5c1dee3296b30228b104de3032fdc03d835d00...,178.143.56.0,8333,1033,616294,616294,0,0
1,2020-02-07 00:03:07,bf4cbf26150152d044c036ae4c716b563b5399af67c75d...,85.25.134.0,8333,1037,616294,616294,0,0
2,2020-02-07 00:03:07,9d0a653318adfa5575afd01b0ecec499dddc6391791bef...,68.36.95.0,8333,1037,616294,616294,0,0
3,2020-02-07 00:03:07,9edf44d735ff2dc2e381ca9d832a86b5b4def4d1924e46...,176.191.182.0,8333,1033,616294,616294,0,0
4,2020-02-07 00:03:07,9024597a521af001f29bf5810b299e2a477ece0019b511...,111.90.158.0,8333,1037,616294,616294,0,0
5,2020-02-07 00:03:07,2bdf6b6029e1b75e1edbdd27d6b129843eb22b4ca70418...,1.255.226.0,8333,1037,616294,616294,0,0
6,2020-02-07 00:03:07,e459aeba62753812bd4938641f6a24af9eb3cd092851da...,23.175.0.0,8333,1033,616294,616294,0,0
7,2020-02-07 00:03:07,4de7ff0b8c19c5cf6a840466e7061462e12e9fd57e3c58...,54.82.229.0,8333,1033,616294,616294,0,0
8,2020-02-07 00:03:07,f3b8f0099ca9086a350d3e938834a946c398ffd95ad533...,176.9.73.0,8333,1033,616294,616294,0,0
9,2020-02-07 00:03:07,079b7b072d0eaca0b2a93e9b1a73ee14cad192934e9b39...,13.53.88.0,8333,1033,616294,616294,0,0

In [ ]:
print(
    "Missing reference heights:",
    test_features["reference_height"].isna().sum()
)

Missing reference heights: 0

In [ ]:
feature_output = os.path.join(
    PROCESSED_DIR,
    "p2p_peer_features_v1.parquet"
)

query = f"""
WITH observations AS (

    SELECT
        o.timestamp,
        o.node_id,
        o.ip,
        o.port,
        o.service,
        o.reported_height,

        m.reference_height,

        o.reported_height - m.reference_height
            AS height_deviation,

        ABS(
            o.reported_height - m.reference_height
        )
            AS absolute_height_deviation

    FROM read_parquet('{observation_glob}') o

    LEFT JOIN read_parquet('{metadata_glob}') m
        ON o.timestamp = m.timestamp
)

SELECT

    node_id,

    -- ---------------------------------------------
    -- Activity
    -- ---------------------------------------------

    COUNT(*) AS observation_count,

    COUNT(DISTINCT DATE(timestamp))
        AS active_days,

    COUNT(
        DISTINCT DATE_TRUNC('hour', timestamp)
    )
        AS active_hours,

    COUNT(DISTINCT timestamp)
        AS active_snapshots,

    MIN(timestamp)
        AS first_observed,

    MAX(timestamp)
        AS last_observed,

    DATE_DIFF(
        'second',
        MIN(timestamp),
        MAX(timestamp)
    )
        AS observation_span_seconds,

    -- ---------------------------------------------
    -- Endpoint behaviour
    -- ---------------------------------------------

    COUNT(DISTINCT ip)
        AS unique_ips,

    COUNT(DISTINCT port)
        AS unique_ports,

    COUNT(DISTINCT service)
        AS unique_services,

    COUNT(
        DISTINCT CAST(ip AS VARCHAR)
        || ':'
        || CAST(port AS VARCHAR)
    )
        AS unique_endpoints,

    -- ---------------------------------------------
    -- Port behaviour
    -- ---------------------------------------------

    COUNT(
        CASE
            WHEN port != 8333 THEN 1
        END
    )
        AS non_default_port_observations,

    COUNT(DISTINCT
        CASE
            WHEN port != 8333 THEN port
        END
    )
        AS non_default_ports,

    -- ---------------------------------------------
    -- Service behaviour
    -- ---------------------------------------------

    COUNT(
        CASE
            WHEN service != 1037 THEN 1
        END
    )
        AS non_1037_service_observations,

    -- ---------------------------------------------
    -- Height behaviour
    -- ---------------------------------------------

    AVG(reported_height)
        AS mean_reported_height,

    MIN(reported_height)
        AS min_reported_height,

    MAX(reported_height)
        AS max_reported_height,

    AVG(height_deviation)
        AS mean_height_deviation,

    AVG(absolute_height_deviation)
        AS mean_absolute_height_deviation,

    MAX(absolute_height_deviation)
        AS max_absolute_height_deviation,

    COUNT(
        CASE
            WHEN absolute_height_deviation > 100 THEN 1
        END
    )
        AS height_deviation_over_100,

    COUNT(
        CASE
            WHEN absolute_height_deviation > 1000 THEN 1
        END
    )
        AS height_deviation_over_1000,

    COUNT(
        CASE
            WHEN absolute_height_deviation > 10000 THEN 1
        END
    )
        AS height_deviation_over_10000

FROM observations

GROUP BY node_id
"""

print("Building P2P peer feature table...")

con.execute(
    f"""
    COPY (
        {query}
    )
    TO '{feature_output}'
    (FORMAT PARQUET, COMPRESSION ZSTD)
    """
)

print("\n✅ Feature table created:")
print(feature_output)

Building P2P peer feature table...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

recovery

In [ ]:
# ===== RECOVER AFTER COLAB RESTART =====

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import duckdb

# Existing processed dataset locations
PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
OBS_DIR = os.path.join(PROCESSED_DIR, "observations")
META_DIR = os.path.join(PROCESSED_DIR, "metadata")

# Existing Parquet files
observation_glob = os.path.join(
    OBS_DIR,
    "p2p_observations_*.parquet"
)

metadata_glob = os.path.join(
    META_DIR,
    "p2p_snapshot_metadata.parquet"
)

# New DuckDB connection
con = duckdb.connect()

# Check everything
print("✅ Drive mounted")
print("✅ DuckDB connected")
print("✅ Observation files:", len(
    [f for f in os.listdir(OBS_DIR) if f.endswith(".parquet")]
))
print("✅ Metadata exists:", os.path.exists(
    metadata_glob
))
print("✅ Processed directory:", PROCESSED_DIR)

Mounted at /content/drive
✅ Drive mounted
✅ DuckDB connected
✅ Observation files: 27
✅ Metadata exists: True
✅ Processed directory: /content/drive/MyDrive/Bitcoin P2P Dataset/processed

In [ ]:
DUCKDB_TMP = "/content/duckdb_tmp"
os.makedirs(DUCKDB_TMP, exist_ok=True)

con.execute("SET memory_limit='7GB'")
con.execute("SET threads=2")
con.execute("SET preserve_insertion_order=false")
con.execute(f"SET temp_directory='{DUCKDB_TMP}'")

print("✅ DuckDB RAM-safe configuration applied")

✅ DuckDB RAM-safe configuration applied

In [ ]:
import os
import duckdb

# Local Colab disk ko DuckDB temporary storage ke liye use karo
DUCKDB_TMP = "/content/duckdb_tmp"
os.makedirs(DUCKDB_TMP, exist_ok=True)

# RAM usage limit
con.execute("SET memory_limit='7GB'")
con.execute("SET threads=2")
con.execute("SET preserve_insertion_order=false")
con.execute(f"SET temp_directory='{DUCKDB_TMP}'")

print("✅ DuckDB configured")
print("RAM limit: 7 GB")
print("Threads: 2")
print("Temp directory:", DUCKDB_TMP)

✅ DuckDB configured
RAM limit: 7 GB
Threads: 2
Temp directory: /content/duckdb_tmp

p2p 1 feature table

In [ ]:
feature_output = os.path.join(
    PROCESSED_DIR,
    "p2p_peer_features_v1.parquet"
)

query = f"""
WITH observations AS (
    SELECT
        o.timestamp,
        o.node_id,
        o.ip,
        o.port,
        o.service,
        o.reported_height,
        m.reference_height,
        o.reported_height - m.reference_height AS height_deviation,
        ABS(o.reported_height - m.reference_height) AS absolute_height_deviation
    FROM read_parquet('{observation_glob}') o
    LEFT JOIN read_parquet('{metadata_glob}') m
        ON o.timestamp = m.timestamp
)

SELECT
    node_id,

    COUNT(*) AS observation_count,

    COUNT(DISTINCT DATE(timestamp)) AS active_days,

    COUNT(DISTINCT DATE_TRUNC('hour', timestamp)) AS active_hours,

    COUNT(DISTINCT timestamp) AS active_snapshots,

    MIN(timestamp) AS first_observed,
    MAX(timestamp) AS last_observed,

    DATE_DIFF(
        'second',
        MIN(timestamp),
        MAX(timestamp)
    ) AS observation_span_seconds,

    COUNT(DISTINCT ip) AS unique_ips,
    COUNT(DISTINCT port) AS unique_ports,
    COUNT(DISTINCT service) AS unique_services,

    COUNT(
        DISTINCT CAST(ip AS VARCHAR) || ':' || CAST(port AS VARCHAR)
    ) AS unique_endpoints,

    COUNT(CASE WHEN port != 8333 THEN 1 END)
        AS non_default_port_observations,

    COUNT(DISTINCT CASE
        WHEN port != 8333 THEN port
    END) AS non_default_ports,

    COUNT(CASE WHEN service != 1037 THEN 1 END)
        AS non_1037_service_observations,

    AVG(reported_height) AS mean_reported_height,
    MIN(reported_height) AS min_reported_height,
    MAX(reported_height) AS max_reported_height,

    AVG(height_deviation) AS mean_height_deviation,
    AVG(absolute_height_deviation)
        AS mean_absolute_height_deviation,

    MAX(absolute_height_deviation)
        AS max_absolute_height_deviation,

    COUNT(CASE
        WHEN absolute_height_deviation > 100
        THEN 1
    END) AS height_deviation_over_100,

    COUNT(CASE
        WHEN absolute_height_deviation > 1000
        THEN 1
    END) AS height_deviation_over_1000,

    COUNT(CASE
        WHEN absolute_height_deviation > 10000
        THEN 1
    END) AS height_deviation_over_10000

FROM observations
GROUP BY node_id
"""

print("Building P2P peer feature table...")
print("⚠️ DuckDB may use temporary disk space to keep RAM below the limit.")

con.execute(
    f"""
    COPY (
        {query}
    )
    TO '{feature_output}'
    (FORMAT PARQUET, COMPRESSION ZSTD)
    """
)

print("\n✅ Feature table created:")
print(feature_output)

Building P2P peer feature table...
⚠️ DuckDB may use temporary disk space to keep RAM below the limit.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
features = pd.read_parquet(feature_output)

print("Shape:", features.shape)

print("\nColumns:")
for col in features.columns:
    print("-", col)

print("\nMissing values:")
print(features.isna().sum())

print("\nFirst 5 rows:")
display(features.head())

In [ ]:
numeric_features = features.select_dtypes(
    include="number"
)

display(
    numeric_features.describe().T
)

,count,mean,std,min,25%,50%,75%,max
observation_count,21122.0,3.225090e+03,3.942663e+03,1.0,129.250000,481.000000,7.711750e+03,2.844200e+04
active_days,21122.0,1.092775e+01,1.105798e+01,1.0,1.000000,3.000000,2.500000e+01,2.700000e+01
active_hours,21122.0,2.329555e+02,2.655178e+02,1.0,20.000000,48.000000,5.727500e+02,6.480000e+02
active_snapshots,21122.0,3.196516e+03,3.866395e+03,1.0,129.000000,481.000000,7.696250e+03,9.481000e+03
observation_span_seconds,21122.0,3.710308e+06,5.258281e+06,0.0,85253.000000,831585.500000,2.850482e+06,1.330474e+07
unique_ips,21122.0,1.000000e+00,0.000000e+00,1.0,1.000000,1.000000,1.000000e+00,1.000000e+00
unique_ports,21122.0,1.010037e+00,1.382817e-01,1.0,1.000000,1.000000,1.000000e+00,1.000000e+01
unique_services,21122.0,1.048196e+00,2.241235e-01,1.0,1.000000,1.000000,1.000000e+00,5.000000e+00
unique_endpoints,21122.0,1.010037e+00,1.382817e-01,1.0,1.000000,1.000000,1.000000e+00,1.000000e+01
non_default_port_observations,21122.0,1.801283e+02,1.293450e+03,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04
non_default_ports,21122.0,4.350914e-02,2.404381e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+01
non_1037_service_observations,21122.0,1.692144e+03,3.237232e+03,0.0,0.000000,55.000000,5.180000e+02,2.844200e+04
mean_reported_height,21122.0,6.160555e+05,5.793963e+04,0.0,617760.375269,618769.016203,6.195752e+05,3.289972e+06
min_reported_height,21122.0,6.057023e+05,9.185759e+04,0.0,616294.000000,616751.000000,6.192058e+05,3.147539e+06
max_reported_height,21122.0,6.227271e+05,6.028597e+04,0.0,618400.000000,619901.000000,6.385130e+05,4.186981e+06
mean_height_deviation,21122.0,-5.768662e+03,5.754966e+04,-638439.5,-0.051332,-0.010709,6.568324e-03,2.671309e+06
mean_absolute_height_deviation,21122.0,7.959452e+03,5.728776e+04,0.0,0.047354,0.057143,1.386593e-01,2.671309e+06
max_absolute_height_deviation,21122.0,1.748621e+04,9.499197e+04,0.0,1.000000,2.000000,4.000000e+00,3.553367e+06
height_deviation_over_100,21122.0,6.756713e+01,7.167846e+02,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04
height_deviation_over_1000,21122.0,6.612925e+01,7.134404e+02,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04
height_deviation_over_10000,21122.0,6.169340e+01,6.919240e+02,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04

feature-quality check

In [ ]:
# ============================================================
# STEP 51 — P2P-1 FEATURE QUALITY ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

# Load peer feature table
peer_features = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_features_v1.parquet"
    )
)

# Numeric columns only
numeric_features = peer_features.select_dtypes(
    include=[np.number]
).copy()

print("Shape:", numeric_features.shape)

# ------------------------------------------------------------
# 1. Constant / zero-variance features
# ------------------------------------------------------------

variance = numeric_features.var()

constant_features = variance[
    variance == 0
].index.tolist()

print("\n=== CONSTANT FEATURES ===")
print(constant_features)

# ------------------------------------------------------------
# 2. Near-zero variance features
# ------------------------------------------------------------

n = len(numeric_features)

near_zero_features = []

for col in numeric_features.columns:

    value_counts = (
        numeric_features[col]
        .value_counts(normalize=True, dropna=False)
    )

    if len(value_counts) > 0:

        dominant_fraction = value_counts.iloc[0]

        if dominant_fraction >= 0.995:
            near_zero_features.append(
                (col, dominant_fraction)
            )

print("\n=== NEAR-ZERO VARIANCE FEATURES ===")

for col, fraction in near_zero_features:
    print(
        f"{col}: {fraction*100:.3f}% same value"
    )

# ------------------------------------------------------------
# 3. Skewness
# ------------------------------------------------------------

skewness = numeric_features.skew(
    numeric_only=True
).sort_values(
    key=lambda x: x.abs(),
    ascending=False
)

print("\n=== MOST SKEWED FEATURES ===")
print(skewness.head(15))

# ------------------------------------------------------------
# 4. Extreme value counts
# ------------------------------------------------------------

print("\n=== EXTREME / HIGH-VALUE FEATURES ===")

for col in [
    "observation_count",
    "unique_ports",
    "unique_services",
    "non_default_port_observations",
    "non_1037_service_observations",
    "max_absolute_height_deviation",
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000"
]:

    if col in numeric_features.columns:

        q99 = numeric_features[col].quantile(0.99)
        maximum = numeric_features[col].max()

        print(
            f"{col}: "
            f"99th percentile={q99:.4f}, "
            f"max={maximum:.4f}"
        )

# ------------------------------------------------------------
# 5. Highly correlated feature pairs
# ------------------------------------------------------------

corr = numeric_features.corr()

high_corr_pairs = []

columns = corr.columns

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):

        value = corr.iloc[i, j]

        if abs(value) >= 0.95:

            high_corr_pairs.append(
                (
                    columns[i],
                    columns[j],
                    value
                )
            )

print("\n=== HIGH CORRELATION PAIRS | |r| >= 0.95 ===")

for a, b, r in sorted(
    high_corr_pairs,
    key=lambda x: abs(x[2]),
    reverse=True
):
    print(
        f"{a} <-> {b}: r={r:.4f}"
    )

print("\n✅ Step 51 complete")

Shape: (21122, 21)

=== CONSTANT FEATURES ===
['unique_ips']

=== NEAR-ZERO VARIANCE FEATURES ===
unique_ips: 100.000% same value

=== MOST SKEWED FEATURES ===
unique_ports                      27.538313
unique_endpoints                  27.538313
max_reported_height               17.101684
height_deviation_over_10000       15.732609
mean_absolute_height_deviation    15.450161
height_deviation_over_1000        15.059490
height_deviation_over_100         14.943163
non_default_ports                 10.450951
max_absolute_height_deviation      9.542620
non_default_port_observations      8.610054
mean_height_deviation              5.431548
mean_reported_height               5.273337
unique_services                    4.989253
min_reported_height               -2.674618
non_1037_service_observations      1.810334
dtype: float64

=== EXTREME / HIGH-VALUE FEATURES ===
observation_count: 99th percentile=9481.0000, max=28442.0000
unique_ports: 99th percentile=1.0000, max=10.0000
unique_services: 99th percentile=2.0000, max=5.0000
non_default_port_observations: 99th percentile=9139.9600, max=28442.0000
non_1037_service_observations: 99th percentile=9481.0000, max=28442.0000
max_absolute_height_deviation: 99th percentile=606892.4000, max=3553367.0000
height_deviation_over_100: 99th percentile=1059.7100, max=28442.0000
height_deviation_over_1000: 99th percentile=994.5900, max=28442.0000
height_deviation_over_10000: 99th percentile=822.9500, max=28442.0000

=== HIGH CORRELATION PAIRS | |r| >= 0.95 ===
unique_ports <-> unique_endpoints: r=1.0000
height_deviation_over_100 <-> height_deviation_over_1000: r=0.9984
mean_reported_height <-> mean_height_deviation: r=0.9924
observation_count <-> active_snapshots: r=0.9911
height_deviation_over_1000 <-> height_deviation_over_10000: r=0.9780
active_hours <-> active_snapshots: r=0.9750
height_deviation_over_100 <-> height_deviation_over_10000: r=0.9739
active_days <-> active_hours: r=0.9705
observation_count <-> active_hours: r=0.9661
mean_reported_height <-> max_reported_height: r=0.9508

✅ Step 51 complete

In [ ]:
# ============================================================
# STEP 52 — CLEAN P2P-1 FEATURE SET
# ============================================================

peer_features = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_features_v1.parquet"
    )
)

# Features retained for P2P-1 baseline
p2p1_features = [
    "node_id",

    # Activity / persistence
    "observation_count",
    "active_days",
    "active_hours",
    "observation_span_seconds",

    # Endpoint behavior
    "unique_ports",
    "unique_services",
    "non_default_port_observations",
    "non_default_ports",
    "non_1037_service_observations",

    # Height behavior
    "min_reported_height",
    "max_reported_height",
    "mean_height_deviation",
    "mean_absolute_height_deviation",
    "max_absolute_height_deviation",

    # Height deviation indicators
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000"
]

p2p1 = peer_features[p2p1_features].copy()

# ------------------------------------------------------------
# Remove features identified as redundant/constant
# ------------------------------------------------------------

# unique_ips was constant and is already excluded.
#
# active_snapshots was highly redundant with observation_count.
# unique_endpoints was perfectly correlated with unique_ports.
# mean_reported_height was highly correlated with mean_height_deviation.
#
# Keep all three height threshold counts for now.
# We will evaluate their redundancy again after transformations.

p2p1_output = os.path.join(
    PROCESSED_DIR,
    "p2p_peer_features_p2p1_clean.parquet"
)

p2p1.to_parquet(
    p2p1_output,
    index=False
)

print("✅ Clean P2P-1 feature table created")
print("Shape:", p2p1.shape)
print("\nFeatures:")
for i, col in enumerate(p2p1.columns, 1):
    print(f"{i:2}. {col}")

print("\nSaved to:")
print(p2p1_output)

✅ Clean P2P-1 feature table created
Shape: (21122, 18)

Features:
 1. node_id
 2. observation_count
 3. active_days
 4. active_hours
 5. observation_span_seconds
 6. unique_ports
 7. unique_services
 8. non_default_port_observations
 9. non_default_ports
10. non_1037_service_observations
11. min_reported_height
12. max_reported_height
13. mean_height_deviation
14. mean_absolute_height_deviation
15. max_absolute_height_deviation
16. height_deviation_over_100
17. height_deviation_over_1000
18. height_deviation_over_10000

Saved to:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_peer_features_p2p1_clean.parquet

In [ ]:
# ============================================================
# STEP 53 — CHECK CLEAN P2P-1 FEATURES
# ============================================================

numeric_p2p1 = p2p1.select_dtypes(
    include=[np.number]
)

print("Shape:", p2p1.shape)

print("\n=== Missing values ===")
print(
    p2p1.isna().sum()
)

print("\n=== Numeric summary ===")
display(
    numeric_p2p1.describe().T
)

print("\n=== Correlations among height-threshold features ===")

threshold_cols = [
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000"
]

display(
    numeric_p2p1[threshold_cols].corr()
)

print("\n=== Non-zero counts ===")

for col in threshold_cols:
    print(
        f"{col}:",
        (numeric_p2p1[col] > 0).sum(),
        "/",
        len(numeric_p2p1)
    )

Shape: (21122, 18)

=== Missing values ===
node_id                           0
observation_count                 0
active_days                       0
active_hours                      0
observation_span_seconds          0
unique_ports                      0
unique_services                   0
non_default_port_observations     0
non_default_ports                 0
non_1037_service_observations     0
min_reported_height               0
max_reported_height               0
mean_height_deviation             0
mean_absolute_height_deviation    0
max_absolute_height_deviation     0
height_deviation_over_100         0
height_deviation_over_1000        0
height_deviation_over_10000       0
dtype: int64

=== Numeric summary ===

,count,mean,std,min,25%,50%,75%,max
observation_count,21122.0,3.225090e+03,3.942663e+03,1.0,129.250000,481.000000,7.711750e+03,2.844200e+04
active_days,21122.0,1.092775e+01,1.105798e+01,1.0,1.000000,3.000000,2.500000e+01,2.700000e+01
active_hours,21122.0,2.329555e+02,2.655178e+02,1.0,20.000000,48.000000,5.727500e+02,6.480000e+02
observation_span_seconds,21122.0,3.710308e+06,5.258281e+06,0.0,85253.000000,831585.500000,2.850482e+06,1.330474e+07
unique_ports,21122.0,1.010037e+00,1.382817e-01,1.0,1.000000,1.000000,1.000000e+00,1.000000e+01
unique_services,21122.0,1.048196e+00,2.241235e-01,1.0,1.000000,1.000000,1.000000e+00,5.000000e+00
non_default_port_observations,21122.0,1.801283e+02,1.293450e+03,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04
non_default_ports,21122.0,4.350914e-02,2.404381e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+01
non_1037_service_observations,21122.0,1.692144e+03,3.237232e+03,0.0,0.000000,55.000000,5.180000e+02,2.844200e+04
min_reported_height,21122.0,6.057023e+05,9.185759e+04,0.0,616294.000000,616751.000000,6.192058e+05,3.147539e+06
max_reported_height,21122.0,6.227271e+05,6.028597e+04,0.0,618400.000000,619901.000000,6.385130e+05,4.186981e+06
mean_height_deviation,21122.0,-5.768662e+03,5.754966e+04,-638439.5,-0.051332,-0.010709,6.568324e-03,2.671309e+06
mean_absolute_height_deviation,21122.0,7.959452e+03,5.728776e+04,0.0,0.047354,0.057143,1.386593e-01,2.671309e+06
max_absolute_height_deviation,21122.0,1.748621e+04,9.499197e+04,0.0,1.000000,2.000000,4.000000e+00,3.553367e+06
height_deviation_over_100,21122.0,6.756713e+01,7.167846e+02,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04
height_deviation_over_1000,21122.0,6.612925e+01,7.134404e+02,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04
height_deviation_over_10000,21122.0,6.169340e+01,6.919240e+02,0.0,0.000000,0.000000,0.000000e+00,2.844200e+04

=== Correlations among height-threshold features ===

,height_deviation_over_100,height_deviation_over_1000,height_deviation_over_10000
height_deviation_over_100,1.000000,0.998433,0.973906
height_deviation_over_1000,0.998433,1.000000,0.977997
height_deviation_over_10000,0.973906,0.977997,1.000000

=== Non-zero counts ===
height_deviation_over_100: 2431 / 21122
height_deviation_over_1000: 1418 / 21122
height_deviation_over_10000: 1096 / 21122

P2P-2 Temporal Features

In [ ]:
# ============================================================
# STEP 54A — FRESH DUCKDB CONNECTION FOR TEMPORAL FEATURES
# ============================================================

import duckdb
import os

DUCKDB_TMP = "/content/duckdb_tmp"
os.makedirs(DUCKDB_TMP, exist_ok=True)

# Fresh connection
con_temporal = duckdb.connect()

# Configure BEFORE doing any query
con_temporal.execute("SET memory_limit='7GB'")
con_temporal.execute("SET threads=2")
con_temporal.execute("SET preserve_insertion_order=false")
con_temporal.execute(
    f"SET temp_directory='{DUCKDB_TMP}'"
)

print("✅ Fresh DuckDB connection created")
print("✅ RAM limit: 7 GB")
print("✅ Threads: 2")
print("✅ Temporary directory configured")

✅ Fresh DuckDB connection created
✅ RAM limit: 7 GB
✅ Threads: 2
✅ Temporary directory configured

In [ ]:
# ============================================================
# STEP 54C — CORRECTED LIGHTWEIGHT TEMPORAL AGGREGATION
# ============================================================

temporal_basic_output = os.path.join(
    PROCESSED_DIR,
    "p2p_peer_temporal_basic_v1.parquet"
)

con_temporal.execute("SET memory_limit='5GB'")
con_temporal.execute("SET threads=1")
con_temporal.execute("SET preserve_insertion_order=false")

print("Building lightweight temporal features...")
print("RAM limit: 5 GB")
print("Threads: 1")

query_basic = f"""
WITH hourly_counts AS (

    SELECT
        node_id,
        DATE_TRUNC('hour', timestamp) AS hour_bucket,
        COUNT(*) AS observations_in_hour

    FROM read_parquet('{observation_glob}')

    GROUP BY
        node_id,
        DATE_TRUNC('hour', timestamp)
),

hourly_stats AS (

    SELECT
        node_id,

        COUNT(*) AS active_hours,

        AVG(observations_in_hour)
            AS mean_observations_per_hour,

        MEDIAN(observations_in_hour)
            AS median_observations_per_hour,

        MAX(observations_in_hour)
            AS max_observations_per_hour,

        STDDEV_SAMP(observations_in_hour)
            AS hourly_activity_std,

        VAR_SAMP(observations_in_hour)
            AS hourly_activity_variance

    FROM hourly_counts

    GROUP BY node_id
),

daily_counts AS (

    SELECT
        node_id,
        DATE(timestamp) AS day_bucket,
        COUNT(*) AS observations_in_day

    FROM read_parquet('{observation_glob}')

    GROUP BY
        node_id,
        DATE(timestamp)
),

daily_stats AS (

    SELECT
        node_id,

        COUNT(*) AS active_days,

        AVG(observations_in_day)
            AS mean_observations_per_day,

        MEDIAN(observations_in_day)
            AS median_observations_per_day,

        MAX(observations_in_day)
            AS max_observations_per_day,

        STDDEV_SAMP(observations_in_day)
            AS daily_activity_std

    FROM daily_counts

    GROUP BY node_id
)

SELECT
    h.node_id,

    h.active_hours,
    h.mean_observations_per_hour,
    h.median_observations_per_hour,
    h.max_observations_per_hour,
    h.hourly_activity_std,
    h.hourly_activity_variance,

    d.active_days,
    d.mean_observations_per_day,
    d.median_observations_per_day,
    d.max_observations_per_day,
    d.daily_activity_std

FROM hourly_stats h

LEFT JOIN daily_stats d
    ON h.node_id = d.node_id
"""

con_temporal.execute(
    f"""
    COPY (
        {query_basic}
    )
    TO '{temporal_basic_output}'
    (FORMAT PARQUET, COMPRESSION ZSTD)
    """
)

print("\n✅ Basic temporal features created:")
print(temporal_basic_output)

Building lightweight temporal features...
RAM limit: 5 GB
Threads: 1

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Basic temporal features created:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_peer_temporal_basic_v1.parquet

In [ ]:
# ============================================================
# STEP 55 — INSPECT BASIC TEMPORAL FEATURES
# ============================================================

temporal_basic = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_temporal_basic_v1.parquet"
    )
)

print("Shape:", temporal_basic.shape)

print("\nColumns:")
for col in temporal_basic.columns:
    print("-", col)

print("\nMissing values:")
print(
    temporal_basic.isna().sum()
)

print("\nFirst 5 rows:")
display(
    temporal_basic.head()
)

print("\nNumeric summary:")
display(
    temporal_basic.select_dtypes(
        include=[np.number]
    ).describe().T
)

Shape: (21122, 12)

Columns:
- node_id
- active_hours
- mean_observations_per_hour
- median_observations_per_hour
- max_observations_per_hour
- hourly_activity_std
- hourly_activity_variance
- active_days
- mean_observations_per_day
- median_observations_per_day
- max_observations_per_day
- daily_activity_std

Missing values:
node_id                            0
active_hours                       0
mean_observations_per_hour         0
median_observations_per_hour       0
max_observations_per_hour          0
hourly_activity_std              907
hourly_activity_variance         907
active_days                        0
mean_observations_per_day          0
median_observations_per_day        0
max_observations_per_day           0
daily_activity_std              5673
dtype: int64

First 5 rows:

,node_id,active_hours,mean_observations_per_hour,median_observations_per_hour,max_observations_per_hour,hourly_activity_std,hourly_activity_variance,active_days,mean_observations_per_day,median_observations_per_day,max_observations_per_day,daily_activity_std
0,24c7c31d5c1dee3296b30228b104de3032fdc03d835d00...,67,14.313433,15.0,15,2.600751,6.763908,4,239.750000,246.5,359,136.521976
1,bf4cbf26150152d044c036ae4c716b563b5399af67c75d...,600,14.995000,15.0,15,0.122474,0.015000,25,359.880000,360.0,360,0.600000
2,9d0a653318adfa5575afd01b0ecec499dddc6391791bef...,516,14.426357,15.0,15,2.290632,5.246993,25,297.760000,360.0,360,125.283771
3,9edf44d735ff2dc2e381ca9d832a86b5b4def4d1924e46...,648,14.621914,15.0,15,1.883126,3.546165,27,350.925926,360.0,360,45.953928
4,9024597a521af001f29bf5810b299e2a477ece0019b511...,177,14.909605,15.0,15,0.668078,0.446328,8,329.875000,360.0,360,82.393546

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
active_hours,21122.0,232.955497,265.517794,1.0,20.000000,48.000000,572.750000,648.000000
mean_observations_per_hour,21122.0,11.711393,4.570953,1.0,9.918269,14.280000,14.708333,75.000000
median_observations_per_hour,21122.0,12.126835,4.893171,1.0,10.000000,15.000000,15.000000,75.000000
max_observations_per_hour,21122.0,13.350109,4.115525,1.0,15.000000,15.000000,15.000000,75.000000
hourly_activity_std,20215.0,2.164051,1.747083,0.0,0.674855,1.895497,3.049590,15.101650
hourly_activity_variance,20215.0,7.735263,11.023536,0.0,0.455429,3.592907,9.300000,228.059840
active_days,21122.0,10.927753,11.057981,1.0,1.000000,3.000000,25.000000,27.000000
mean_observations_per_day,21122.0,212.808548,133.970541,1.0,90.500000,237.000000,347.439375,1800.000000
median_observations_per_day,21122.0,219.073407,141.082570,1.0,86.500000,239.500000,360.000000,1800.000000
max_observations_per_day,21122.0,250.463782,141.864979,1.0,120.000000,353.000000,360.000000,1800.000000
daily_activity_std,15449.0,73.458612,62.342160,0.0,25.455844,47.571030,117.850793,506.995562

In [ ]:
# ============================================================
# STEP 56 — TEMPORAL BURST / VARIABILITY FEATURES
# ============================================================

burst_output = os.path.join(
    PROCESSED_DIR,
    "p2p_peer_burst_features_v1.parquet"
)

temporal_basic = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_temporal_basic_v1.parquet"
    )
)

burst = temporal_basic[
    [
        "node_id",
        "mean_observations_per_hour",
        "max_observations_per_hour",
        "hourly_activity_std",
        "mean_observations_per_day",
        "max_observations_per_day",
        "daily_activity_std"
    ]
].copy()

# ------------------------------------------------------------
# Burst ratios
# ------------------------------------------------------------

burst["hourly_burst_ratio"] = (
    burst["max_observations_per_hour"]
    /
    burst["mean_observations_per_hour"]
)

burst["daily_burst_ratio"] = (
    burst["max_observations_per_day"]
    /
    burst["mean_observations_per_day"]
)

# ------------------------------------------------------------
# Coefficient of variation
# ------------------------------------------------------------

burst["hourly_activity_cv"] = (
    burst["hourly_activity_std"]
    /
    burst["mean_observations_per_hour"]
)

burst["daily_activity_cv"] = (
    burst["daily_activity_std"]
    /
    burst["mean_observations_per_day"]
)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

burst.to_parquet(
    burst_output,
    index=False
)

print("✅ Burst/variability feature table created")
print("Shape:", burst.shape)

print("\nColumns:")
for col in burst.columns:
    print("-", col)

print("\nMissing values:")
print(
    burst.isna().sum()
)

print("\nSummary:")
display(
    burst.select_dtypes(
        include=[np.number]
    ).describe().T
)

print("\nSaved to:")
print(burst_output)

✅ Burst/variability feature table created
Shape: (21122, 11)

Columns:
- node_id
- mean_observations_per_hour
- max_observations_per_hour
- hourly_activity_std
- mean_observations_per_day
- max_observations_per_day
- daily_activity_std
- hourly_burst_ratio
- daily_burst_ratio
- hourly_activity_cv
- daily_activity_cv

Missing values:
node_id                          0
mean_observations_per_hour       0
max_observations_per_hour        0
hourly_activity_std            907
mean_observations_per_day        0
max_observations_per_day         0
daily_activity_std            5673
hourly_burst_ratio               0
daily_burst_ratio                0
hourly_activity_cv             907
daily_activity_cv             5673
dtype: int64

Summary:

,count,mean,std,min,25%,50%,75%,max
mean_observations_per_hour,21122.0,11.711393,4.570953,1.0,9.918269,14.280000,14.708333,75.000000
max_observations_per_hour,21122.0,13.350109,4.115525,1.0,15.000000,15.000000,15.000000,75.000000
hourly_activity_std,20215.0,2.164051,1.747083,0.0,0.674855,1.895497,3.049590,15.101650
mean_observations_per_day,21122.0,212.808548,133.970541,1.0,90.500000,237.000000,347.439375,1800.000000
max_observations_per_day,21122.0,250.463782,141.864979,1.0,120.000000,353.000000,360.000000,1800.000000
daily_activity_std,15449.0,73.458612,62.342160,0.0,25.455844,47.571030,117.850793,506.995562
hourly_burst_ratio,21122.0,1.290641,0.766508,1.0,1.010668,1.044568,1.219831,10.713043
daily_burst_ratio,21122.0,1.288041,0.563549,1.0,1.000000,1.038078,1.496881,13.248848
hourly_activity_cv,20215.0,0.230367,0.235223,0.0,0.055804,0.139232,0.345757,1.478237
daily_activity_cv,15449.0,0.417737,0.381423,0.0,0.130968,0.257053,0.702697,3.226338

Saved to:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_peer_burst_features_v1.parquet

Merge P2P-1 + P2P-2

In [ ]:
# ============================================================
# STEP 57 — MERGE P2P-1 + P2P-2 FEATURES
# ============================================================

p2p1 = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_features_p2p1_clean.parquet"
    )
)

temporal = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_temporal_basic_v1.parquet"
    )
)

burst = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_burst_features_v1.parquet"
    )
)

print("P2P-1 shape:", p2p1.shape)
print("Temporal shape:", temporal.shape)
print("Burst shape:", burst.shape)

# ------------------------------------------------------------
# Avoid duplicate columns during merge
# ------------------------------------------------------------

temporal_to_merge = temporal.drop(
    columns=["active_hours", "active_days"],
    errors="ignore"
)

burst_to_merge = burst.drop(
    columns=[
        "mean_observations_per_hour",
        "max_observations_per_hour",
        "hourly_activity_std",
        "mean_observations_per_day",
        "max_observations_per_day",
        "daily_activity_std"
    ],
    errors="ignore"
)

# ------------------------------------------------------------
# Merge
# ------------------------------------------------------------

p2p_features_v2 = (
    p2p1
    .merge(
        temporal_to_merge,
        on="node_id",
        how="left",
        validate="one_to_one"
    )
    .merge(
        burst_to_merge,
        on="node_id",
        how="left",
        validate="one_to_one"
    )
)

p2p2_output = os.path.join(
    PROCESSED_DIR,
    "p2p_peer_features_v2_temporal.parquet"
)

p2p_features_v2.to_parquet(
    p2p2_output,
    index=False
)

print("\n✅ P2P-1 + P2P-2 merged")

print("Final shape:", p2p_features_v2.shape)

print("\nMissing values:")
print(
    p2p_features_v2.isna().sum()
)

print("\nSaved to:")
print(p2p2_output)

P2P-1 shape: (21122, 18)
Temporal shape: (21122, 12)
Burst shape: (21122, 11)

✅ P2P-1 + P2P-2 merged
Final shape: (21122, 31)

Missing values:
node_id                              0
observation_count                    0
active_days                          0
active_hours                         0
observation_span_seconds             0
unique_ports                         0
unique_services                      0
non_default_port_observations        0
non_default_ports                    0
non_1037_service_observations        0
min_reported_height                  0
max_reported_height                  0
mean_height_deviation                0
mean_absolute_height_deviation       0
max_absolute_height_deviation        0
height_deviation_over_100            0
height_deviation_over_1000           0
height_deviation_over_10000          0
mean_observations_per_hour           0
median_observations_per_hour         0
max_observations_per_hour            0
hourly_activity_std                907
hourly_activity_variance           907
mean_observations_per_day            0
median_observations_per_day          0
max_observations_per_day             0
daily_activity_std                5673
hourly_burst_ratio                   0
daily_burst_ratio                    0
hourly_activity_cv                 907
daily_activity_cv                 5673
dtype: int64

Saved to:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_peer_features_v2_temporal.parquet

recovery

In [ ]:
# ============================================================
# RECOVERY AFTER COLAB DISCONNECT
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import pandas as pd
import duckdb

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
OBS_DIR = os.path.join(PROCESSED_DIR, "observations")
META_DIR = os.path.join(PROCESSED_DIR, "metadata")

observation_glob = os.path.join(
    OBS_DIR,
    "p2p_observations_*.parquet"
)

metadata_glob = os.path.join(
    META_DIR,
    "p2p_snapshot_metadata.parquet"
)

print("✅ Drive mounted")
print("✅ Processed directory exists:",
      os.path.exists(PROCESSED_DIR))

print("✅ P2P-2 merged feature file exists:",
      os.path.exists(
          os.path.join(
              PROCESSED_DIR,
              "p2p_peer_features_v2_temporal.parquet"
          )
      ))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Drive mounted
✅ Processed directory exists: True
✅ P2P-2 merged feature file exists: True

In [ ]:
# ============================================================
# STEP 58 — P2P-2 FEATURE QUALITY CHECK
# ============================================================

p2p_features_v2 = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_features_v2_temporal.parquet"
    )
)

print("Shape:", p2p_features_v2.shape)

numeric_v2 = p2p_features_v2.select_dtypes(
    include=[np.number]
).copy()

print("\nNumeric feature count:", numeric_v2.shape[1])

print("\n=== MISSING VALUES ===")

missing = numeric_v2.isna().sum()

print(
    missing[missing > 0]
)

print("\n=== CONSTANT FEATURES ===")

variance = numeric_v2.var()

constant = variance[
    variance == 0
].index.tolist()

print(constant)

print("\n=== MOST SKEWED FEATURES ===")

skewness = numeric_v2.skew(
    numeric_only=True
).sort_values(
    key=lambda x: x.abs(),
    ascending=False
)

display(
    skewness.head(15)
)

print("\n=== HIGH CORRELATION PAIRS | |r| >= 0.95 ===")

corr = numeric_v2.corr()

columns = corr.columns

high_corr = []

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):

        r = corr.iloc[i, j]

        if abs(r) >= 0.95:
            high_corr.append(
                (
                    columns[i],
                    columns[j],
                    r
                )
            )

for a, b, r in sorted(
    high_corr,
    key=lambda x: abs(x[2]),
    reverse=True
):
    print(
        f"{a} <-> {b}: r={r:.4f}"
    )

print("\n✅ Step 58 complete")

Shape: (21122, 31)

Numeric feature count: 30

=== MISSING VALUES ===
hourly_activity_std          907
hourly_activity_variance     907
daily_activity_std          5673
hourly_activity_cv           907
daily_activity_cv           5673
dtype: int64

=== CONSTANT FEATURES ===
[]

=== MOST SKEWED FEATURES ===

unique_ports                      27.538313
max_reported_height               17.101684
height_deviation_over_10000       15.732609
mean_absolute_height_deviation    15.450161
height_deviation_over_1000        15.059490
height_deviation_over_100         14.943163
non_default_ports                 10.450951
max_absolute_height_deviation      9.542620
non_default_port_observations      8.610054
daily_burst_ratio                  5.903496
hourly_burst_ratio                 5.777790
mean_height_deviation              5.431548
unique_services                    4.989253
hourly_activity_variance           3.293552
min_reported_height               -2.674618
dtype: float64

=== HIGH CORRELATION PAIRS | |r| >= 0.95 ===
height_deviation_over_100 <-> height_deviation_over_1000: r=0.9984
mean_observations_per_day <-> median_observations_per_day: r=0.9921
mean_observations_per_hour <-> median_observations_per_hour: r=0.9832
height_deviation_over_1000 <-> height_deviation_over_10000: r=0.9780
height_deviation_over_100 <-> height_deviation_over_10000: r=0.9739
active_days <-> active_hours: r=0.9705
observation_count <-> active_hours: r=0.9661

✅ Step 58 complete

final P2P-2 ML matrix

In [ ]:
# ============================================================
# STEP 59 — FINAL P2P-2 ML FEATURE MATRIX
# ============================================================

from sklearn.preprocessing import StandardScaler

p2p_features_v2 = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_peer_features_v2_temporal.parquet"
    )
)

# ------------------------------------------------------------
# 1. Keep node IDs separately
# ------------------------------------------------------------

node_ids = p2p_features_v2["node_id"].copy()

# ------------------------------------------------------------
# 2. Select final feature columns
# ------------------------------------------------------------

final_features = [
    # Activity
    "observation_count",
    "active_days",
    "active_hours",
    "observation_span_seconds",

    # Endpoint behavior
    "unique_ports",
    "unique_services",
    "non_default_port_observations",
    "non_default_ports",
    "non_1037_service_observations",

    # Height behavior
    "min_reported_height",
    "max_reported_height",
    "mean_height_deviation",
    "mean_absolute_height_deviation",
    "max_absolute_height_deviation",

    # Height severity
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000",

    # Temporal intensity
    "mean_observations_per_hour",
    "max_observations_per_hour",
    "hourly_activity_std",
    "hourly_activity_variance",

    "mean_observations_per_day",
    "max_observations_per_day",
    "daily_activity_std",

    # Burst behavior
    "hourly_burst_ratio",
    "daily_burst_ratio",
    "hourly_activity_cv",
    "daily_activity_cv"
]

X = p2p_features_v2[
    final_features
].copy()

# ------------------------------------------------------------
# 3. Handle mathematically undefined variability
# ------------------------------------------------------------

variability_cols = [
    "hourly_activity_std",
    "hourly_activity_variance",
    "daily_activity_std",
    "hourly_activity_cv",
    "daily_activity_cv"
]

for col in variability_cols:
    X[col] = X[col].fillna(0)

# ------------------------------------------------------------
# 4. Remove highly redundant central-tendency features
# ------------------------------------------------------------

# Median versions are strongly correlated with their means.
# They are excluded from the final ML matrix.
#
# They remain available in the original Parquet table.

# ------------------------------------------------------------
# 5. Log-transform strongly right-skewed non-negative features
# ------------------------------------------------------------

log_features = [
    "observation_count",
    "observation_span_seconds",
    "unique_ports",
    "unique_services",
    "non_default_port_observations",
    "non_default_ports",
    "non_1037_service_observations",
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000",
    "max_absolute_height_deviation",
    "max_observations_per_hour",
    "max_observations_per_day",
    "hourly_burst_ratio",
    "daily_burst_ratio"
]

for col in log_features:
    X[col] = np.log1p(
        np.clip(X[col], a_min=0, a_max=None)
    )

# ------------------------------------------------------------
# 6. Clean infinite values
# ------------------------------------------------------------

X = X.replace(
    [np.inf, -np.inf],
    np.nan
)

X = X.fillna(0)

# ------------------------------------------------------------
# 7. Standardization
# ------------------------------------------------------------

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

# Restore node IDs
X_scaled.insert(
    0,
    "node_id",
    node_ids.values
)

# ------------------------------------------------------------
# 8. Save final ML matrix
# ------------------------------------------------------------

ml_output = os.path.join(
    PROCESSED_DIR,
    "p2p_ml_matrix_v2.parquet"
)

X_scaled.to_parquet(
    ml_output,
    index=False
)

print("✅ Final P2P-2 ML matrix created")

print("\nShape:", X_scaled.shape)

print("\nNumeric features:")
print(X.columns.tolist())

print("\nMissing values:")
print(
    X_scaled.isna().sum().sum()
)

print("\nSaved to:")
print(ml_output)

✅ Final P2P-2 ML matrix created

Shape: (21122, 29)

Numeric features:
['observation_count', 'active_days', 'active_hours', 'observation_span_seconds', 'unique_ports', 'unique_services', 'non_default_port_observations', 'non_default_ports', 'non_1037_service_observations', 'min_reported_height', 'max_reported_height', 'mean_height_deviation', 'mean_absolute_height_deviation', 'max_absolute_height_deviation', 'height_deviation_over_100', 'height_deviation_over_1000', 'height_deviation_over_10000', 'mean_observations_per_hour', 'max_observations_per_hour', 'hourly_activity_std', 'hourly_activity_variance', 'mean_observations_per_day', 'max_observations_per_day', 'daily_activity_std', 'hourly_burst_ratio', 'daily_burst_ratio', 'hourly_activity_cv', 'daily_activity_cv']

Missing values:
0

Saved to:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_ml_matrix_v2.parquet

Isolation Forest Baseline    we'll inspect:
- anomaly-score distribution
- top anomalous peers
- which features characterize those peers
- anomaly-score stability
- later, temporal/cross-period consistency

In [ ]:
# ============================================================
# STEP 60 — P2P-2 ISOLATION FOREST BASELINE
# ============================================================

from sklearn.ensemble import IsolationForest
import pandas as pd
import numpy as np
import os

# ------------------------------------------------------------
# Load final ML matrix
# ------------------------------------------------------------

ml_matrix = pd.read_parquet(
    os.path.join(
        PROCESSED_DIR,
        "p2p_ml_matrix_v2.parquet"
    )
)

node_ids = ml_matrix["node_id"].copy()

X = ml_matrix.drop(
    columns=["node_id"]
)

print("ML matrix shape:", X.shape)

# ------------------------------------------------------------
# Isolation Forest
# ------------------------------------------------------------

iso_forest = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42,
    n_jobs=1
)

print("\nTraining Isolation Forest...")

iso_forest.fit(X)

print("✅ Isolation Forest trained")

# ------------------------------------------------------------
# Anomaly scores
# ------------------------------------------------------------

# sklearn's decision_function:
# higher = more normal
#
# We invert it so:
# higher anomaly_score = more anomalous

anomaly_score = -iso_forest.decision_function(X)

predicted_label = iso_forest.predict(X)

results = pd.DataFrame({
    "node_id": node_ids,
    "anomaly_score": anomaly_score,
    "isolation_prediction": predicted_label
})

# ------------------------------------------------------------
# Rank anomalies
# ------------------------------------------------------------

results = results.sort_values(
    "anomaly_score",
    ascending=False
).reset_index(drop=True)

results["anomaly_rank"] = (
    np.arange(len(results)) + 1
)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

iso_output = os.path.join(
    PROCESSED_DIR,
    "p2p_isolation_forest_v1_scores.parquet"
)

results.to_parquet(
    iso_output,
    index=False
)

print("\n✅ Isolation Forest results saved:")
print(iso_output)

print("\nScore statistics:")
print(
    results["anomaly_score"].describe()
)

print("\nTop 20 anomalous peers:")
display(
    results.head(20)
)

ML matrix shape: (21122, 28)

Training Isolation Forest...
✅ Isolation Forest trained

✅ Isolation Forest results saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_isolation_forest_v1_scores.parquet

Score statistics:
count    21122.000000
mean        -0.079335
std          0.062784
min         -0.137515
25%         -0.117892
50%         -0.104624
75%         -0.059701
max          0.266486
Name: anomaly_score, dtype: float64

Top 20 anomalous peers:

,node_id,anomaly_score,isolation_prediction,anomaly_rank
0,0765826ae5db55bcec2b08342d3e37b4f85d948b3b9ea7...,0.266486,-1,1
1,e6380090f67e11df401ea9d470fd6af62ac66019e5e51f...,0.264070,-1,2
2,9122d54c53a8a51eb71f04e30d28561127396260b8724b...,0.253473,-1,3
3,b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f...,0.249874,-1,4
4,486a521b068be7a374309bfcdfce43c52acef263dedd25...,0.240039,-1,5
5,5783adfd7ac5119222de46f13e0806288f8c22e626e2dd...,0.237619,-1,6
6,33631f44f2a8515fb0d905dff8d83e6a37d5fc74e3ffd3...,0.237033,-1,7
7,26cba5622694236990f3c292ffd8ea156638fc364ce0aa...,0.235899,-1,8
8,eb4e3a3785b71509f17cc44e0ab92fa07031e4a9e35595...,0.234138,-1,9
9,c7a10ac7d2313c2db3d8adae43e423640472c340d6b752...,0.231913,-1,10
10,d074e0931ee80f4b20d480481e36c34a5cf7ec90139556...,0.229275,-1,11
11,16c845af314d9a821d91365354c1a2c8dc3121b76403d1...,0.228166,-1,12
12,0b880c4b88f180557db90dda70096350c6bf4d194749c3...,0.227217,-1,13
13,7ab9faf2427b274f7946752e8bee56551ade2523ba3417...,0.223252,-1,14
14,3710c1bc50adc62e932cf92981f58588226deb9470825d...,0.221748,-1,15
15,54464674c03244f107048dea8956cc95167a9c9bf783c3...,0.217356,-1,16
16,4cbe5e3dc346a3ac4483a9f0eed7685f89ff34c8d7959e...,0.217022,-1,17
17,eef81c91c9773cb9e9ad0c80e447446dd5081d3c2d0234...,0.216663,-1,18
18,9513d65df6873844595a9eca732c78242bafb4b980bfaf...,0.216307,-1,19
19,1638a08e80706ba7162ec9c997223a7790b0081cf98220...,0.216286,-1,20

What the output tells us
- 21,122 peers analyzed.
- 28 ML features used.
- Isolation Forest trained successfully with 300 trees.
- Scores saved to:
  p2p_isolation_forest_v1_scores.parquet
- isolation_prediction = -1 means Isolation Forest classified those peers as outliers under its internal decision threshold.
- Highest anomaly score: 0.266486
- Median score: -0.104624

Explain WHY the top peers are anomalous

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

# Load ML matrix
ml_matrix = pd.read_parquet(
    f"{PROCESSED_DIR}/p2p_ml_matrix_v2.parquet"
)

# Load Isolation Forest results
scores = pd.read_parquet(
    f"{PROCESSED_DIR}/p2p_isolation_forest_v1_scores.parquet"
)

print("ML matrix:", ml_matrix.shape)
print("Scores:", scores.shape)

# Merge
df = ml_matrix.merge(
    scores[["node_id", "anomaly_score", "anomaly_rank"]],
    on="node_id",
    how="inner"
)

print("Merged:", df.shape)

# Numeric feature columns
feature_cols = [
    c for c in ml_matrix.columns
    if c != "node_id"
]

# Calculate robust percentile for every feature
percentile_df = df[feature_cols].rank(
    pct=True
)

# Explain top 20
top20 = df.sort_values(
    "anomaly_score",
    ascending=False
).head(20)

explanations = []

for _, row in top20.iterrows():

    node = row["node_id"]
    score = row["anomaly_score"]
    rank = row["anomaly_rank"]

    reasons = []

    for feature in feature_cols:

        percentile = percentile_df.loc[row.name, feature]

        if percentile >= 0.99:
            reasons.append(
                f"{feature}=very_high"
            )
        elif percentile <= 0.01:
            reasons.append(
                f"{feature}=very_low"
            )

    explanations.append({
        "node_id": node,
        "anomaly_score": score,
        "anomaly_rank": rank,
        "extreme_features": reasons[:10]
    })

explanation_df = pd.DataFrame(explanations)

print("\nTop 20 anomaly explanations:")
display(explanation_df)

ML matrix: (21122, 29)
Scores: (21122, 4)
Merged: (21122, 31)

Top 20 anomaly explanations:

,node_id,anomaly_score,anomaly_rank,extreme_features
0,0765826ae5db55bcec2b08342d3e37b4f85d948b3b9ea7...,0.266486,1,"[observation_count=very_high, unique_ports=ver..."
1,e6380090f67e11df401ea9d470fd6af62ac66019e5e51f...,0.264070,2,"[observation_count=very_high, unique_ports=ver..."
2,9122d54c53a8a51eb71f04e30d28561127396260b8724b...,0.253473,3,"[observation_count=very_high, unique_ports=ver..."
3,b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f...,0.249874,4,"[observation_count=very_high, unique_ports=ver..."
4,486a521b068be7a374309bfcdfce43c52acef263dedd25...,0.240039,5,"[observation_count=very_high, unique_ports=ver..."
5,5783adfd7ac5119222de46f13e0806288f8c22e626e2dd...,0.237619,6,"[observation_count=very_high, unique_ports=ver..."
6,33631f44f2a8515fb0d905dff8d83e6a37d5fc74e3ffd3...,0.237033,7,"[observation_count=very_high, unique_ports=ver..."
7,26cba5622694236990f3c292ffd8ea156638fc364ce0aa...,0.235899,8,"[observation_count=very_high, unique_ports=ver..."
8,eb4e3a3785b71509f17cc44e0ab92fa07031e4a9e35595...,0.234138,9,"[observation_count=very_high, unique_ports=ver..."
9,c7a10ac7d2313c2db3d8adae43e423640472c340d6b752...,0.231913,10,"[unique_ports=very_high, min_reported_height=v..."
10,d074e0931ee80f4b20d480481e36c34a5cf7ec90139556...,0.229275,11,"[observation_count=very_high, unique_ports=ver..."
11,16c845af314d9a821d91365354c1a2c8dc3121b76403d1...,0.228166,12,"[unique_ports=very_high, max_reported_height=v..."
12,0b880c4b88f180557db90dda70096350c6bf4d194749c3...,0.227217,13,"[unique_ports=very_high, unique_services=very_..."
13,7ab9faf2427b274f7946752e8bee56551ade2523ba3417...,0.223252,14,"[observation_count=very_high, unique_ports=ver..."
14,3710c1bc50adc62e932cf92981f58588226deb9470825d...,0.221748,15,"[observation_count=very_high, unique_ports=ver..."
15,54464674c03244f107048dea8956cc95167a9c9bf783c3...,0.217356,16,"[observation_count=very_high, unique_ports=ver..."
16,4cbe5e3dc346a3ac4483a9f0eed7685f89ff34c8d7959e...,0.217022,17,"[min_reported_height=very_low, max_reported_he..."
17,eef81c91c9773cb9e9ad0c80e447446dd5081d3c2d0234...,0.216663,18,"[non_default_port_observations=very_high, max_..."
18,9513d65df6873844595a9eca732c78242bafb4b980bfaf...,0.216307,19,"[min_reported_height=very_low, max_reported_he..."
19,1638a08e80706ba7162ec9c997223a7790b0081cf98220...,0.216286,20,"[max_reported_height=very_low, mean_height_dev..."

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

# Load data
ml_matrix = pd.read_parquet(
    f"{PROCESSED_DIR}/p2p_ml_matrix_v2.parquet"
)

scores = pd.read_parquet(
    f"{PROCESSED_DIR}/p2p_isolation_forest_v1_scores.parquet"
)

df = ml_matrix.merge(
    scores[["node_id", "anomaly_score", "anomaly_rank"]],
    on="node_id",
    how="inner"
)

# ---------------------------------------------------------
# Population percentile for each feature
# ---------------------------------------------------------

feature_cols = [
    c for c in ml_matrix.columns
    if c != "node_id"
]

percentiles = df[feature_cols].rank(pct=True)

# ---------------------------------------------------------
# Feature -> BIT-TRACE reason-code mapping
# ---------------------------------------------------------

reason_map = {
    "observation_count": "HIGH_OBSERVATION_ACTIVITY",
    "active_days": "HIGH_TEMPORAL_PERSISTENCE",
    "active_hours": "HIGH_TEMPORAL_PERSISTENCE",
    "observation_span_seconds": "LONG_OBSERVATION_SPAN",

    "unique_ports": "HIGH_PORT_DIVERSITY",
    "unique_services": "HIGH_SERVICE_DIVERSITY",

    "non_default_port_observations":
        "HIGH_NON_DEFAULT_PORT_ACTIVITY",

    "non_default_ports":
        "HIGH_NON_DEFAULT_PORT_DIVERSITY",

    "non_1037_service_observations":
        "HIGH_NON_DEFAULT_SERVICE_ACTIVITY",

    "min_reported_height":
        "UNUSUAL_LOW_REPORTED_HEIGHT",

    "max_reported_height":
        "UNUSUAL_HIGH_REPORTED_HEIGHT",

    "mean_height_deviation":
        "UNUSUAL_MEAN_HEIGHT_DEVIATION",

    "mean_absolute_height_deviation":
        "HIGH_HEIGHT_DEVIATION",

    "max_absolute_height_deviation":
        "EXTREME_HEIGHT_DEVIATION",

    "height_deviation_over_100":
        "FREQUENT_HEIGHT_DEVIATION",

    "height_deviation_over_1000":
        "LARGE_HEIGHT_DEVIATION",

    "height_deviation_over_10000":
        "EXTREME_HEIGHT_DEVIATION",

    "mean_observations_per_hour":
        "HIGH_HOURLY_ACTIVITY",

    "max_observations_per_hour":
        "HIGH_HOURLY_BURST",

    "hourly_activity_std":
        "HIGH_HOURLY_ACTIVITY_VARIABILITY",

    "hourly_activity_variance":
        "HIGH_HOURLY_ACTIVITY_VARIABILITY",

    "mean_observations_per_day":
        "HIGH_DAILY_ACTIVITY",

    "max_observations_per_day":
        "HIGH_DAILY_BURST",

    "daily_activity_std":
        "HIGH_DAILY_ACTIVITY_VARIABILITY",

    "hourly_burst_ratio":
        "HIGH_HOURLY_BURST",

    "daily_burst_ratio":
        "HIGH_DAILY_BURST",

    "hourly_activity_cv":
        "HIGH_HOURLY_ACTIVITY_VARIABILITY",

    "daily_activity_cv":
        "HIGH_DAILY_ACTIVITY_VARIABILITY",
}

# ---------------------------------------------------------
# Generate reason codes
# ---------------------------------------------------------

reason_rows = []

for idx, row in df.iterrows():

    reasons = []

    for feature in feature_cols:

        percentile = percentiles.loc[idx, feature]

        # Extreme upper-tail behavior
        if percentile >= 0.99:
            if feature in reason_map:
                reasons.append(reason_map[feature])

        # Extreme lower-tail behavior
        elif percentile <= 0.01:

            # Only use lower-tail reason codes where
            # low values are actually meaningful.
            if feature == "min_reported_height":
                reasons.append("UNUSUAL_LOW_REPORTED_HEIGHT")

            elif feature == "max_reported_height":
                reasons.append("UNUSUAL_LOW_REPORTED_HEIGHT")

            elif feature == "mean_height_deviation":
                reasons.append("UNUSUAL_NEGATIVE_HEIGHT_DEVIATION")

            elif feature == "mean_absolute_height_deviation":
                reasons.append("LOW_HEIGHT_VARIABILITY")

    # Remove duplicate reason codes while preserving order
    reasons = list(dict.fromkeys(reasons))

    reason_rows.append({
        "node_id": row["node_id"],
        "anomaly_score": row["anomaly_score"],
        "anomaly_rank": row["anomaly_rank"],
        "reason_codes": reasons
    })

reason_df = pd.DataFrame(reason_rows)

# ---------------------------------------------------------
# Save explainability layer
# ---------------------------------------------------------

output_path = (
    f"{PROCESSED_DIR}/p2p_isolation_forest_v1_explanations.parquet"
)

reason_df.to_parquet(
    output_path,
    index=False
)

print("✅ Reason-code layer created")
print("Shape:", reason_df.shape)
print("Saved:", output_path)

print("\nTop 20 explainable anomalies:")
display(
    reason_df
    .sort_values("anomaly_score", ascending=False)
    .head(20)
)

✅ Reason-code layer created
Shape: (21122, 4)
Saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_isolation_forest_v1_explanations.parquet

Top 20 explainable anomalies:

,node_id,anomaly_score,anomaly_rank,reason_codes
12316,0765826ae5db55bcec2b08342d3e37b4f85d948b3b9ea7...,0.266486,1,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
682,e6380090f67e11df401ea9d470fd6af62ac66019e5e51f...,0.264070,2,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
10863,9122d54c53a8a51eb71f04e30d28561127396260b8724b...,0.253473,3,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
11561,b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f...,0.249874,4,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
13274,486a521b068be7a374309bfcdfce43c52acef263dedd25...,0.240039,5,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
12000,5783adfd7ac5119222de46f13e0806288f8c22e626e2dd...,0.237619,6,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
13315,33631f44f2a8515fb0d905dff8d83e6a37d5fc74e3ffd3...,0.237033,7,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
11165,26cba5622694236990f3c292ffd8ea156638fc364ce0aa...,0.235899,8,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
5400,eb4e3a3785b71509f17cc44e0ab92fa07031e4a9e35595...,0.234138,9,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
16171,c7a10ac7d2313c2db3d8adae43e423640472c340d6b752...,0.231913,10,"[HIGH_PORT_DIVERSITY, UNUSUAL_LOW_REPORTED_HEI..."
3063,d074e0931ee80f4b20d480481e36c34a5cf7ec90139556...,0.229275,11,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
15804,16c845af314d9a821d91365354c1a2c8dc3121b76403d1...,0.228166,12,"[HIGH_PORT_DIVERSITY, UNUSUAL_HIGH_REPORTED_HE..."
10848,0b880c4b88f180557db90dda70096350c6bf4d194749c3...,0.227217,13,"[HIGH_PORT_DIVERSITY, HIGH_SERVICE_DIVERSITY, ..."
12771,7ab9faf2427b274f7946752e8bee56551ade2523ba3417...,0.223252,14,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
11049,3710c1bc50adc62e932cf92981f58588226deb9470825d...,0.221748,15,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
1948,54464674c03244f107048dea8956cc95167a9c9bf783c3...,0.217356,16,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
1355,4cbe5e3dc346a3ac4483a9f0eed7685f89ff34c8d7959e...,0.217022,17,"[UNUSUAL_LOW_REPORTED_HEIGHT, UNUSUAL_NEGATIVE..."
12767,eef81c91c9773cb9e9ad0c80e447446dd5081d3c2d0234...,0.216663,18,"[HIGH_NON_DEFAULT_PORT_ACTIVITY, UNUSUAL_LOW_R..."
2890,9513d65df6873844595a9eca732c78242bafb4b980bfaf...,0.216307,19,"[UNUSUAL_LOW_REPORTED_HEIGHT, UNUSUAL_NEGATIVE..."
18743,1638a08e80706ba7162ec9c997223a7790b0081cf98220...,0.216286,20,"[UNUSUAL_LOW_REPORTED_HEIGHT, UNUSUAL_NEGATIVE..."

In [ ]:
import pandas as pd
import numpy as np
from collections import Counter

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

# ---------------------------------------------------------
# Load existing results
# ---------------------------------------------------------

scores = pd.read_parquet(
    f"{PROCESSED_DIR}/p2p_isolation_forest_v1_scores.parquet"
)

explanations = pd.read_parquet(
    f"{PROCESSED_DIR}/p2p_isolation_forest_v1_explanations.parquet"
)

print("Scores shape:", scores.shape)
print("Explanations shape:", explanations.shape)

# ---------------------------------------------------------
# 1. Isolation Forest prediction distribution
# ---------------------------------------------------------

prediction_counts = scores["isolation_prediction"].value_counts()

print("\n=== Isolation Forest Prediction Distribution ===")
print(prediction_counts)

total_peers = len(scores)
outliers = (scores["isolation_prediction"] == -1).sum()
normal = (scores["isolation_prediction"] == 1).sum()

print(f"\nTotal peers: {total_peers:,}")
print(f"Outliers (-1): {outliers:,}")
print(f"Normal (+1): {normal:,}")
print(f"Outlier percentage: {(outliers / total_peers) * 100:.2f}%")

# ---------------------------------------------------------
# 2. Anomaly score distribution
# ---------------------------------------------------------

print("\n=== Anomaly Score Distribution ===")
print(
    scores["anomaly_score"]
    .describe(
        percentiles=[
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
)

# ---------------------------------------------------------
# 3. Score thresholds
# ---------------------------------------------------------

print("\n=== High Score Counts ===")

for threshold in [0, 0.05, 0.10, 0.15, 0.20, 0.25]:

    count = (
        scores["anomaly_score"] >= threshold
    ).sum()

    percentage = (
        count / total_peers
    ) * 100

    print(
        f"Score >= {threshold:.2f}: "
        f"{count:,} peers ({percentage:.2f}%)"
    )

# ---------------------------------------------------------
# 4. Reason-code frequency
# ---------------------------------------------------------

print("\n=== Reason Code Frequency ===")

reason_counter = Counter()

for reasons in explanations["reason_codes"]:

    if isinstance(reasons, list):

        for reason in reasons:
            reason_counter[reason] += 1

reason_frequency = pd.DataFrame(
    reason_counter.items(),
    columns=["reason_code", "peer_count"]
).sort_values(
    "peer_count",
    ascending=False
)

reason_frequency["percentage"] = (
    reason_frequency["peer_count"]
    / total_peers
) * 100

display(reason_frequency)

# ---------------------------------------------------------
# 5. Top reason-code combinations
# ---------------------------------------------------------

print("\n=== Top Reason-Code Combinations ===")

explanations["reason_combination"] = (
    explanations["reason_codes"]
    .apply(
        lambda x: " + ".join(sorted(set(x)))
        if isinstance(x, list) and len(x) > 0
        else "NO_REASON_CODE"
    )
)

combination_counts = (
    explanations["reason_combination"]
    .value_counts()
    .head(20)
    .reset_index()
)

combination_counts.columns = [
    "reason_combination",
    "peer_count"
]

display(combination_counts)

# ---------------------------------------------------------
# 6. Top 20 anomaly candidates
# ---------------------------------------------------------

print("\n=== Top 20 Anomaly Candidates ===")

top20 = (
    explanations
    .sort_values(
        "anomaly_score",
        ascending=False
    )
    .head(20)
)

display(
    top20[
        [
            "node_id",
            "anomaly_score",
            "anomaly_rank",
            "reason_codes"
        ]
    ]
)

# ---------------------------------------------------------
# 7. Save Step 64 summary
# ---------------------------------------------------------

summary_path = (
    f"{PROCESSED_DIR}/p2p_anomaly_population_summary.parquet"
)

summary_df = pd.DataFrame({
    "metric": [
        "total_peers",
        "outliers",
        "normal",
        "outlier_percentage",
        "mean_anomaly_score",
        "median_anomaly_score",
        "max_anomaly_score",
        "min_anomaly_score"
    ],
    "value": [
        total_peers,
        outliers,
        normal,
        (outliers / total_peers) * 100,
        scores["anomaly_score"].mean(),
        scores["anomaly_score"].median(),
        scores["anomaly_score"].max(),
        scores["anomaly_score"].min()
    ]
})

summary_df.to_parquet(
    summary_path,
    index=False
)

print(
    "\n✅ Step 64 analysis complete"
)

print(
    "Saved:",
    summary_path
)

Scores shape: (21122, 4)
Explanations shape: (21122, 4)

=== Isolation Forest Prediction Distribution ===
isolation_prediction
 1    19073
-1     2049
Name: count, dtype: int64

Total peers: 21,122
Outliers (-1): 2,049
Normal (+1): 19,073
Outlier percentage: 9.70%

=== Anomaly Score Distribution ===
count    21122.000000
mean        -0.079335
std          0.062784
min         -0.137515
1%          -0.137032
5%          -0.135694
10%         -0.128546
25%         -0.117892
50%         -0.104624
75%         -0.059701
90%         -0.001900
95%          0.062643
99%          0.155709
max          0.266486
Name: anomaly_score, dtype: float64

=== High Score Counts ===
Score >= 0.00: 2,049 peers (9.70%)
Score >= 0.05: 1,174 peers (5.56%)
Score >= 0.10: 740 peers (3.50%)
Score >= 0.15: 259 peers (1.23%)
Score >= 0.20: 46 peers (0.22%)
Score >= 0.25: 3 peers (0.01%)

=== Reason Code Frequency ===

Empty DataFrame
Columns: [reason_code, peer_count, percentage]
Index: []

=== Top Reason-Code Combinations ===

  reason_combination  peer_count
0     NO_REASON_CODE       21122

=== Top 20 Anomaly Candidates ===

,node_id,anomaly_score,anomaly_rank,reason_codes
12316,0765826ae5db55bcec2b08342d3e37b4f85d948b3b9ea7...,0.266486,1,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
682,e6380090f67e11df401ea9d470fd6af62ac66019e5e51f...,0.264070,2,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
10863,9122d54c53a8a51eb71f04e30d28561127396260b8724b...,0.253473,3,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
11561,b0576f20db5b073b7fdcc113416c8c5cee1cff1e87786f...,0.249874,4,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
13274,486a521b068be7a374309bfcdfce43c52acef263dedd25...,0.240039,5,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
12000,5783adfd7ac5119222de46f13e0806288f8c22e626e2dd...,0.237619,6,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
13315,33631f44f2a8515fb0d905dff8d83e6a37d5fc74e3ffd3...,0.237033,7,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
11165,26cba5622694236990f3c292ffd8ea156638fc364ce0aa...,0.235899,8,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
5400,eb4e3a3785b71509f17cc44e0ab92fa07031e4a9e35595...,0.234138,9,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
16171,c7a10ac7d2313c2db3d8adae43e423640472c340d6b752...,0.231913,10,"[HIGH_PORT_DIVERSITY, UNUSUAL_LOW_REPORTED_HEI..."
3063,d074e0931ee80f4b20d480481e36c34a5cf7ec90139556...,0.229275,11,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
15804,16c845af314d9a821d91365354c1a2c8dc3121b76403d1...,0.228166,12,"[HIGH_PORT_DIVERSITY, UNUSUAL_HIGH_REPORTED_HE..."
10848,0b880c4b88f180557db90dda70096350c6bf4d194749c3...,0.227217,13,"[HIGH_PORT_DIVERSITY, HIGH_SERVICE_DIVERSITY, ..."
12771,7ab9faf2427b274f7946752e8bee56551ade2523ba3417...,0.223252,14,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
11049,3710c1bc50adc62e932cf92981f58588226deb9470825d...,0.221748,15,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
1948,54464674c03244f107048dea8956cc95167a9c9bf783c3...,0.217356,16,"[HIGH_OBSERVATION_ACTIVITY, HIGH_PORT_DIVERSIT..."
1355,4cbe5e3dc346a3ac4483a9f0eed7685f89ff34c8d7959e...,0.217022,17,"[UNUSUAL_LOW_REPORTED_HEIGHT, UNUSUAL_NEGATIVE..."
12767,eef81c91c9773cb9e9ad0c80e447446dd5081d3c2d0234...,0.216663,18,"[HIGH_NON_DEFAULT_PORT_ACTIVITY, UNUSUAL_LOW_R..."
2890,9513d65df6873844595a9eca732c78242bafb4b980bfaf...,0.216307,19,"[UNUSUAL_LOW_REPORTED_HEIGHT, UNUSUAL_NEGATIVE..."
18743,1638a08e80706ba7162ec9c997223a7790b0081cf98220...,0.216286,20,"[UNUSUAL_LOW_REPORTED_HEIGHT, UNUSUAL_NEGATIVE..."

✅ Step 64 analysis complete
Saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_anomaly_population_summary.parquet

In [ ]:
import os
import glob
import pandas as pd

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

# ---------------------------------------------------------
# Locate original dataset
# ---------------------------------------------------------

DATASET_ROOT = "/content/drive/MyDrive/Bitcoin P2P Dataset"

csv_files = glob.glob(
    os.path.join(
        DATASET_ROOT,
        "**",
        "*.csv"
    ),
    recursive=True
)

print("CSV files found:", len(csv_files))

# Show first 20 paths
for path in csv_files[:20]:
    print(path)

# ---------------------------------------------------------
# Inspect first CSV files WITHOUT assuming schema
# ---------------------------------------------------------

print("\n=== RAW CSV INSPECTION ===")

for path in csv_files[:5]:

    print("\n----------------------------------------")
    print("FILE:", os.path.basename(path))
    print("----------------------------------------")

    try:

        with open(
            path,
            "r",
            encoding="utf-8",
            errors="replace"
        ) as f:

            for i in range(8):

                line = f.readline()

                if not line:
                    break

                print(
                    f"{i+1}:",
                    line.rstrip()[:500]
                )

    except Exception as e:

        print("ERROR:", e)

CSV files found: 0

=== RAW CSV INSPECTION ===

In [ ]:
import os
import glob

print("Searching Google Drive for Bitcoin P2P files...\n")

patterns = [
    "/content/drive/MyDrive/**/*.zip",
    "/content/drive/MyDrive/**/*.csv",
    "/content/drive/MyDrive/**/*.json",
    "/content/drive/MyDrive/**/*.bz2"
]

for pattern in patterns:

    files = glob.glob(
        pattern,
        recursive=True
    )

    print("=" * 70)
    print(pattern)
    print("Found:", len(files))

    for f in files[:20]:
        print(f)

Searching Google Drive for Bitcoin P2P files...

======================================================================
/content/drive/MyDrive/**/*.zip
Found: 1
/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip
======================================================================
/content/drive/MyDrive/**/*.csv
Found: 1
/content/drive/MyDrive/Dataset/ml/dataset/flights.csv
======================================================================
/content/drive/MyDrive/**/*.json
Found: 1
/content/drive/MyDrive/JARVIS/yg.json
======================================================================
/content/drive/MyDrive/**/*.bz2
Found: 0

In [ ]:
import zipfile
import os

ZIP_PATH = "/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip"

print("Opening ZIP...")
print("Size (GB):", round(os.path.getsize(ZIP_PATH) / (1024**3), 2))

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    names = z.namelist()

    print("\nTotal files:", len(names))

    # -----------------------------------------------------
    # File type counts
    # -----------------------------------------------------

    extensions = {}

    for name in names:

        ext = os.path.splitext(name)[1].lower()

        extensions[ext] = extensions.get(ext, 0) + 1

    print("\n=== File extensions ===")

    for ext, count in sorted(
        extensions.items(),
        key=lambda x: x[1],
        reverse=True
    ):
        print(f"{ext or '[no extension]'}: {count}")

    # -----------------------------------------------------
    # Directory counts
    # -----------------------------------------------------

    print("\n=== Top-level directories ===")

    top_dirs = {}

    for name in names:

        parts = name.split("/")

        if len(parts) > 1:

            top = parts[0]

            top_dirs[top] = top_dirs.get(top, 0) + 1

    for directory, count in top_dirs.items():

        print(
            f"{directory}: {count} files"
        )

    # -----------------------------------------------------
    # Search for discovery-related filenames
    # -----------------------------------------------------

    keywords = [
        "addr",
        "getaddr",
        "crawl",
        "discovery",
        "peer",
        "export"
    ]

    print("\n=== Potential discovery-related files ===")

    matches = []

    for name in names:

        lower = name.lower()

        if any(
            keyword in lower
            for keyword in keywords
        ):
            matches.append(name)

    print("Potential matches:", len(matches))

    for name in matches[:100]:

        print(name)

Opening ZIP...
Size (GB): 33.91

Total files: 38340

=== File extensions ===
.csv: 18962
.json: 18841
.bz2: 481
[no extension]: 56

=== Top-level directories ===
dataset_2020: 38340 files

=== Potential discovery-related files ===
Potential matches: 38339
dataset_2020/crawl/
dataset_2020/crawl/20200215/
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:02:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv
dataset_2020/crawl/20200215/20200215-19:22:40.json
dataset_2020/crawl/20200215/20200215-09:46:51.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:43:00.csv
dataset_2020/crawl/20200215/20200215-14:54:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:23:21.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:50:50.csv
dataset_2020/crawl/20200215/20200215-02:38:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:02:30.csv
dataset_2020/crawl/20200215/20200215-10:39:11.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:50:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:22:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:03:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:14:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:14:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:34:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:11:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:46:40.csv
dataset_2020/crawl/20200215/20200215-19:38:40.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:34:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:26:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:26:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:31:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:22:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-11:39:11.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-06:22:30.csv
dataset_2020/crawl/20200215/20200215-03:42:30.json
dataset_2020/crawl/20200215/20200215-04:10:30.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-11:35:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-05:02:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-19:30:40.csv
dataset_2020/crawl/20200215/20200215-01:15:11.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-13:19:01.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:47:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:58:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-10:31:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:15:00.csv
dataset_2020/crawl/20200215/20200215-17:18:40.json
dataset_2020/crawl/20200215/20200215-02:11:00.json
dataset_2020/crawl/20200215/20200215-04:18:40.json
dataset_2020/crawl/20200215/20200215-12:39:01.json
dataset_2020/crawl/20200215/20200215-07:54:41.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:59:20.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-03:38:40.csv
dataset_2020/crawl/20200215/20200215-17:10:40.json
dataset_2020/crawl/20200215/20200215-14:43:11.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:06:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:10:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:06:50.csv
dataset_2020/crawl/20200215/20200215-13:26:50.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:07:00.csv
dataset_2020/crawl/20200215/20200215-11:15:00.json
dataset_2020/crawl/20200215/20200215-01:03:20.json
dataset_2020/crawl/20200215/20200215-13:35:00.json
dataset_2020/crawl/20200215/20200215-13:06:50.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:03:00.csv
dataset_2020/crawl/20200215/20200215-20:50:40.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:38:40.csv
dataset_2020/crawl/20200215/20200215-01:59:00.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:14:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:43:01.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:31:01.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-16:30:40.csv
dataset_2020/crawl/20200215/20200215-09:10:50.json
dataset_2020/crawl/20200215/20200215-08:26:30.json
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:10:41.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-06:18:30.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-21:30:41.csv
dataset_2020/crawl/20200215/20200215-00:43:11.json
dataset_2020/crawl/20200215/20200215-02:03:00.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-22:54:41.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:34:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:55:00.csv
dataset_2020/crawl/20200215/20200215-13:55:10.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-03:03:00.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-08:26:30.csv
dataset_2020/crawl/20200215/20200215-20:58:50.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:22:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-04:58:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-01:23:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:06:50.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-11:15:00.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-20:18:40.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:58:50.csv
dataset_2020/crawl/20200215/20200215-13:51:00.json
dataset_2020/crawl/20200215/20200215-01:47:10.json
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:26:30.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:06:50.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-12:59:10.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-18:22:40.csv
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-14:31:10.csv
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-00:11:20.csv

In [ ]:
import zipfile
import os
import pandas as pd
from io import BytesIO

ZIP_PATH = "/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip"

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    names = z.namelist()

    # ---------------------------------------------------------
    # Find discovery files
    # ---------------------------------------------------------

    getaddr_files = [
        n for n in names
        if "/nodes_per_getADDR_" in n
        and n.lower().endswith(".csv")
    ]

    up_nodes_files = [
        n for n in names
        if "/up_nodes_per_seconds_" in n
        and n.lower().endswith(".csv")
    ]

    print("nodes_per_getADDR files:", len(getaddr_files))
    print("up_nodes_per_seconds files:", len(up_nodes_files))

    # ---------------------------------------------------------
    # Inspect representative files
    # ---------------------------------------------------------

    samples = (
        getaddr_files[:3]
        + up_nodes_files[:3]
    )

    for path in samples:

        print("\n" + "=" * 80)
        print("FILE:")
        print(path)
        print("=" * 80)

        raw = z.read(path)

        print("Size:", len(raw), "bytes")

        # Show raw content first
        text = raw.decode(
            "utf-8",
            errors="replace"
        )

        print("\n--- RAW CONTENT ---")
        print(text[:2000])

        # -----------------------------------------------------
        # Try pandas parsing
        # -----------------------------------------------------

        print("\n--- PANDAS PARSE ---")

        try:

            from io import StringIO

            df = pd.read_csv(
                StringIO(text),
                header=None
            )

            print("Shape:", df.shape)
            print("Columns:", list(df.columns))

            display(df.head(10))

        except Exception as e:

            print("Pandas parse error:", e)

nodes_per_getADDR files: 9481
up_nodes_per_seconds files: 9481

================================================================================
FILE:
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv
================================================================================
Size: 751591 bytes

--- RAW CONTENT ---
1,9307dbb2274694ae6954bbf2144a15e9cfb2006161b38c4194be195f9602f331-192.81.210.0-8333-1037,233,220,208,233
2,a7dbb134085d885f8cc5d50d7b2683e95e06a4873fc26dc431984b21c7a27b81-134.209.254.0-8333-1037,265,132,-1,265
3,ade1db93214bcb4a242f177f703bfea173c3caa4449c59f1fe02408518507d21-134.209.230.0-8333-1037,-1,-1,-1
4,e776487445f0166d3a31de569332da087a57a126f9431743f6789c000139de50-54.254.233.0-8333-1037,317,317,317
5,19ef04f5c60c33afa8206b01fad7862c450ed1258499e9a31409fb1b42f403d5-54.245.199.0-8333-1037,333,166,333,-1
6,c26a27a5799c6dd5f4364a38668c2d57240c77c5add9e362bd3bff68eb3e1219-34.222.156.0-8333-1037,-1,-1,-1
7,c2b990ea8fad9df3d6b54c985ac4252cc1146037fba13bf363a6612324aadb80-13.229.122.0-8333-1037,-1,-1,-1
8,69adac5843c8acf1986614a0115acc7053468303c3b50afcd2dd2d95317a46ea-46.101.132.0-8333-1037,-1,-1,-1
9,7df313e1ec6560109dccc5ccecd3c8c1ee0012254fd640e4a15d54a92a0e9bc4-47.254.152.0-8333-1037,-1,-1,-1,-1
10,2de8a7f629f79a8779f8ee394cc30d0cd20d228f4c1c0a38592da65abf05a9be-88.198.68.0-8333-1033,-1,-1,-1,-1
11,d86671939820d9b2e93beeb25ad47977b63692e524a93482c205ad35b6648896-178.84.168.0-8333-1037,-1,-1,-1
12,c13e5fe4a3e332013a2fac40032b82ebb385135acda6157589bda1540475f288-73.38.249.0-8333-1037,-1,-1,-1
13,5ce162e726231a36c027c3ef971ada0c1481ce39dbce1ee04406c752d19358a7-73.92.253.0-8333-1037,-1,-1,-1
14,8998d95bc4c4c52cccbf05e12531784f7cd1257115319fa72695f3403692437a-193.70.32.0-8333-13,-1,-1,-1
15,af3ddf58f91b6e74e31af412bbb133c4cd6643962328b575076a5027fdb207b1-138.201.204.0-8333-1036,-1,-1,-1,-1
16,67bd9b11bbbcab70d8604de19f5985e5773e573a114b23a1e56aabdf77bdab7e-190.2.150.0-8333-13,-1,-1,-1,-1
17,ec844a3ff4f5bb48f7f6a628b37442e807ffe5ebe706a713448d5e4ab592ecfc-94.102.57.0-8333-1037,-1,-1,-1,-1
18,a5cd1c693a26e3553138e28b98b4b4ebc997d201d8f396422c1eaa59425468d2-217.160.185.0-8333-1037,-1,-1,-1,-1
19,e3095ea4b27d54ff7351c1fd185cbe74a8717a96d695574aa73fced8a7c412ab-45.63.59.0-8333-1032,-1,-1,-1
20,f8bc5ccfabfe1da90d12cecf2ca71d1db1d8abf9f1d945056990acacc9b3dce8-78.46.128

--- PANDAS PARSE ---
Pandas parse error: Error tokenizing data. C error: Expected 6 fields in line 21, saw 7


================================================================================
FILE:
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv
================================================================================
Size: 751879 bytes

--- RAW CONTENT ---
1,b1506da7ee3098c74c0c5058eb2f2f814bc1256f02c025c258234727ce2f2ab5-34.212.212.0-8333-1037,195,128,-1,195,190
2,32d177b7bd153fd6dab279c4f09f591c8a957415515a924d8528f6416359bb9f-116.202.97.0-8333-1037,203,188,173,203
3,a64f3269dc5e30f8497d54788dc224070bcbc2cd58237303d227e44abd31b1d3-104.199.165.0-8333-1037,221,220,221,219
4,f6d19a13a0f080e4b35bd6510e99fd326c55a6dc2ddbf34b1e5915c85bb4aac6-35.185.131.0-8333-1037,213,106,-1,213
5,716655df4e3246431b756f0a3d687e9f01b0d1b81fc328bd8f32da82e71b0139-35.185.172.0-8333-1037,214,106,-1,214
6,ed357f454cfcaa476d9919398d5d3ebdd9b92768c62bb8b8a7831ce742867854-18.141.58.0-8333-1037,204,134,-1,204,198
7,64d7e05f812e8cbae373610b39815d147b5edda0d2c7bbe31f66b183867f27a8-188.241.48.0-8333-1037,-1,-1,-1
8,9056c9b0eda5bb80f64964545645ca66e99aa5adc287361208442d2d45efea5d-96.255.84.0-8333-1033,-1,-1,-1,-1
9,d16db821ff0e85241a81e2a19c2b15328c3f79f61c278780c15fa544ba340fdf-84.27.10.0-8333-1037,-1,-1,-1
10,84b1a2beabe976dd965f590d05c0cb55cf49d5340c468120e3eebf682708f2cb-164.52.44.0-8333-13,-1,-1,-1,-1
11,adb01f7a22949a584a6ba0f323e6ebbc7680c71becad29855d3a8da59cdb73ea-75.40.139.0-8333-1033,-1,-1,-1,-1
12,7eb0d31bba94ebfeb0073d79b96f1cb5d550fdec84804239a41831e6f1840eb7-190.85.201.0-8333-1033,-1,-1,-1,-1
13,365d12e4f8c777d5d0de74ab12e7fe9317aeda25216e59ab91ea945bbccbf28a-45.50.46.0-8333-1037,-1,-1,-1,-1
14,21a0e9ee1d94173645639906c0409e1d58b0dcb50bdadee161cb72feefa92ea5-152.208.33.0-8333-1037,-1,-1,-1
15,be3b68600450f105aa5b6acade888bd68007c6d7f526b774ad110cc80396abc2-37.187.130.0-8333-1037,-1,-1,-1,-1
16,1e4d805b953a4bee3cfa191a148cadb049a00c42d892c8ec1963ccd0ad780bb0-13.250.54.0-8333-13,-1,-1,-1,-1
17,0e5db983873086e4ce68c4aa3d01eacae90911689019f4163eb5c29d6f086b30-37.221.198.0-8333-1037,-1,-1,-1,-1
18,65359fdec70303e218db1a301fca011cc6f344da01666690ffbab5e47076c6da-142.4.211.0-8333-13,-1,-1,-1,-1
19,580baf0baca6b73af2bec1a95ee02128f0e3ca9b8bd3d15c54e66e8a23135abc-2.56.99.0-8333-1033,-1,-1,-1,-1
20,71b7cf28925d99c11e89572b272a37363c170f3f49b6f87f

--- PANDAS PARSE ---
Pandas parse error: Error tokenizing data. C error: Expected 7 fields in line 116, saw 8


================================================================================
FILE:
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv
================================================================================
Size: 753638 bytes

--- RAW CONTENT ---
1,363ed4c2b71ebe3a3f9f14d450ad2647f392328c6adedea74c4184b4f5cb779f-159.69.94.0-8333-1037,-1,-1,-1
2,cf014d9e68b6eeec6502efc7a3ee15f6edd70641b82ef318badd67ff73a0701a-52.25.248.0-8333-1037,289,144,289,-1
3,3df0cc91af1984b06465f979ac44fa30cb13e404bbe02da5b9e800985c818693-116.202.97.0-8333-1037,-1,-1,-1
4,547c107cf735e614e962757f9c46697efdc517c2477c57b3319f3b526f03eea1-52.77.239.0-8333-1037,280,93,-1,-1,280
5,4f71d7c5860bc2fe66757a02607eb9b010f0ca653d42372e6014c4a206ee6ea3-136.49.241.0-8333-1032,-1,-1,-1,-1
6,fc7ff7db8a355ce45a389fec918ee1f229d11735dacce79ed4fd471bfd3baa8f-159.89.155.0-8333-1033,-1,-1,-1
7,a783232337296c7c9508dcb81a855712dc542de189ebdd21a9ff8b997fa458ac-205.196.146.0-8333-1037,-1,-1,-1
8,d9ffffdfb8c3d0b8a99cb8777624b54a38adfbc415f55bb5acfd48344327613f-52.50.254.0-8333-1037,-1,-1,-1
9,2d58d64c32b2fb4d424dd56a204df172d90824bfb8d28568caf72b57bfeccdb7-185.26.28.0-8333-1037,-1,-1,-1
10,51a08b4db178317761d3e9ff98942ba4289f34ed3c8e042597d1358042f78947-82.62.67.0-8333-1037,-1,-1,-1
11,8b7524f6fa7898f1a15ca0c08760b9dc87a04fb9dbd50408b4577989f499b483-72.65.246.0-8333-9,0,0,0,0
12,e225c9c333c1dd3fe4a75e11c5fae048231b6ae4a26c914ee4d48993ed10e1c0-35.158.121.0-8333-1037,-1,-1,-1
13,962f4cb4d7da405c652b6ea2db2d89953eb2c2297a17c20112916eecab6eabe1-37.223.120.0-8333-1033,74,74,74
14,600973a40df70079470398ded8ef507527ebc6dce5a6dc7fca9244d8d31c6ee1-83.198.101.0-8333-1033,-1,-1,-1
15,ece1d8c61366821c95ee34e70981f09e374d08688e07a13dc61e188704f56d10-81.204.48.0-8333-1037,-1,-1,-1
16,da2009d288103f511d42743ba00cbde5d4c3f9ed27156c2353c7f1228639c7ff-47.75.253.0-8333-1033,-1,-1,-1,-1
17,cf06c2d29336cd96b3e9ca0b1fa831883e88c5d32a7122965675c0971417b359-149.56.66.0-8333-1033,-1,-1,-1
18,0cb31301a7a13406df920108ca7494bb890d45a34c268c1c7139d024a34d778e-167.114.210.0-8333-9,252,252,251,252
19,3c2f40173029dbbb47448187e464068f9d33f2a719cfab88adc10046814a21c0-47.95.2.0-8333-1037,-1,-1,-1,-1
20,fd258dd545a4d3533b4951daf4e35aa6c89e0a088c9cdb21967c4c6157d506c3-109.242.253.0-8333-1033,80,80,

--- PANDAS PARSE ---
Pandas parse error: Error tokenizing data. C error: Expected 5 fields in line 2, saw 6


================================================================================
FILE:
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv
================================================================================
Size: 250 bytes

--- RAW CONTENT ---
0,16
5,473
10,328
15,312
20,1099
25,473
30,330
35,383
40,452
45,261
50,273
55,349
60,224
65,205
70,278
75,177
80,150
85,226
90,143
95,142
100,167
105,135
110,120
115,127
120,112
125,85
130,112
135,74
140,53
145,42
150,8
155,0
160,2
165,0
170,0
175,1


--- PANDAS PARSE ---
Shape: (36, 2)
Columns: [0, 1]

    0     1
0   0    16
1   5   473
2  10   328
3  15   312
4  20  1099
5  25   473
6  30   330
7  35   383
8  40   452
9  45   261

================================================================================
FILE:
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv
================================================================================
Size: 204 bytes

--- RAW CONTENT ---
0,356
5,474
10,340
15,1084
20,649
25,329
30,354
35,544
40,315
45,256
50,392
55,273
60,201
65,239
70,224
75,187
80,190
85,185
90,91
95,81
100,97
105,241
110,88
115,65
120,56
125,15
130,3
135,1
140,2
145,1


--- PANDAS PARSE ---
Shape: (30, 2)
Columns: [0, 1]

    0     1
0   0   356
1   5   474
2  10   340
3  15  1084
4  20   649
5  25   329
6  30   354
7  35   544
8  40   315
9  45   256

================================================================================
FILE:
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv
================================================================================
Size: 224 bytes

--- RAW CONTENT ---
0,122
5,105
10,399
15,487
20,370
25,814
30,456
35,284
40,410
45,417
50,265
55,273
60,347
65,253
70,225
75,288
80,193
85,186
90,208
95,184
100,159
105,193
110,137
115,114
120,135
125,97
130,83
135,77
140,42
145,4
150,1
155,1


--- PANDAS PARSE ---
Shape: (32, 2)
Columns: [0, 1]

    0    1
0   0  122
1   5  105
2  10  399
3  15  487
4  20  370
5  25  814
6  30  456
7  35  284
8  40  410
9  45  417

In [ ]:
import zipfile
import os
import pandas as pd
from io import StringIO

ZIP_PATH = "/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip"

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    names = z.namelist()

    getaddr_files = [
        n for n in names
        if "/nodes_per_getADDR_" in n
        and n.endswith(".csv")
    ]

    up_files = [
        n for n in names
        if "/up_nodes_per_seconds_" in n
        and n.endswith(".csv")
    ]

    print("nodes_per_getADDR files:", len(getaddr_files))
    print("up_nodes_per_seconds files:", len(up_files))

    # ---------------------------------------------------------
    # Inspect multiple files from each family
    # ---------------------------------------------------------

    for label, files in [
        ("nodes_per_getADDR", getaddr_files),
        ("up_nodes_per_seconds", up_files)
    ]:

        print("\n" + "=" * 80)
        print(label)
        print("=" * 80)

        for path in files[:5]:

            raw = z.read(path)

            text = raw.decode(
                "utf-8",
                errors="replace"
            ).strip()

            print("\nFILE:", path)
            print("Bytes:", len(raw))
            print("First 500 characters:")
            print(text[:500])

            try:

                df = pd.read_csv(
                    StringIO(text),
                    header=None
                )

                print(
                    "Shape:",
                    df.shape
                )

                print(
                    "Column count:",
                    len(df.columns)
                )

                print(
                    "First rows:"
                )

                display(
                    df.head(10)
                )

                print(
                    "Column dtypes:"
                )

                print(
                    df.dtypes
                )

            except Exception as e:

                print(
                    "Parse error:",
                    e
                )

nodes_per_getADDR files: 9481
up_nodes_per_seconds files: 9481

================================================================================
nodes_per_getADDR
================================================================================

FILE: dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv
Bytes: 751591
First 500 characters:
1,9307dbb2274694ae6954bbf2144a15e9cfb2006161b38c4194be195f9602f331-192.81.210.0-8333-1037,233,220,208,233
2,a7dbb134085d885f8cc5d50d7b2683e95e06a4873fc26dc431984b21c7a27b81-134.209.254.0-8333-1037,265,132,-1,265
3,ade1db93214bcb4a242f177f703bfea173c3caa4449c59f1fe02408518507d21-134.209.230.0-8333-1037,-1,-1,-1
4,e776487445f0166d3a31de569332da087a57a126f9431743f6789c000139de50-54.254.233.0-8333-1037,317,317,317
5,19ef04f5c60c33afa8206b01fad7862c450ed1258499e9a31409fb1b42f403d5-54.245.199.0-8333-1
Parse error: Error tokenizing data. C error: Expected 6 fields in line 21, saw 7


FILE: dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv
Bytes: 751879
First 500 characters:
1,b1506da7ee3098c74c0c5058eb2f2f814bc1256f02c025c258234727ce2f2ab5-34.212.212.0-8333-1037,195,128,-1,195,190
2,32d177b7bd153fd6dab279c4f09f591c8a957415515a924d8528f6416359bb9f-116.202.97.0-8333-1037,203,188,173,203
3,a64f3269dc5e30f8497d54788dc224070bcbc2cd58237303d227e44abd31b1d3-104.199.165.0-8333-1037,221,220,221,219
4,f6d19a13a0f080e4b35bd6510e99fd326c55a6dc2ddbf34b1e5915c85bb4aac6-35.185.131.0-8333-1037,213,106,-1,213
5,716655df4e3246431b756f0a3d687e9f01b0d1b81fc328bd8f32da82e71b0139-35.185
Parse error: Error tokenizing data. C error: Expected 7 fields in line 116, saw 8


FILE: dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv
Bytes: 753638
First 500 characters:
1,363ed4c2b71ebe3a3f9f14d450ad2647f392328c6adedea74c4184b4f5cb779f-159.69.94.0-8333-1037,-1,-1,-1
2,cf014d9e68b6eeec6502efc7a3ee15f6edd70641b82ef318badd67ff73a0701a-52.25.248.0-8333-1037,289,144,289,-1
3,3df0cc91af1984b06465f979ac44fa30cb13e404bbe02da5b9e800985c818693-116.202.97.0-8333-1037,-1,-1,-1
4,547c107cf735e614e962757f9c46697efdc517c2477c57b3319f3b526f03eea1-52.77.239.0-8333-1037,280,93,-1,-1,280
5,4f71d7c5860bc2fe66757a02607eb9b010f0ca653d42372e6014c4a206ee6ea3-136.49.241.0-8333-1032,-1,
Parse error: Error tokenizing data. C error: Expected 5 fields in line 2, saw 6


FILE: dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:02:30.csv
Bytes: 746218
First 500 characters:
1,2adb1ebb914cc11898b6e4d2ffbe1934379059c5e37f3eacec4e126177e9afe7-18.236.80.0-8333-1037,216,208,201,216
2,ee9d019b8a9ff2fb80bc45e289d71bbffac2028bf149da07f08b5b0fdd35031d-95.188.127.0-8333-1033,-1,-1,-1
3,1c77ef08373cc69ff2a9d1a1dcd793895807fa16aa836d61948de661c05a000f-159.69.21.0-8333-1037,196,196,196
4,f7e87e99709a7de8654945775c5bf564d5e366750250e97d3ea45d6da4821351-188.138.88.0-8333-1033,-1,-1,-1
5,bc4490f6f806d12514edbb4e430c915ee5d70e015d4493abc0ac3f08197d5a65-158.69.79.0-8333-1037,-1,-1,-
Parse error: Error tokenizing data. C error: Expected 6 fields in line 22, saw 7


FILE: dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:43:00.csv
Bytes: 756652
First 500 characters:
1,8b5195bba36b96fedf9f4812e9b359bae8655b5044214043e6b9dee81d9688d5-71.15.195.0-8333-1037,109,109,109
2,89c0cd0eb8b1a3a56e0da71baed47a8f5fd4b11599549850402f3a60d6c77895-138.68.87.0-8333-1037,229,214,199,229
3,1f5eecefe6c500566ecdb9981309b71466ad61fa70642ca909db775ecf2b46ec-13.250.37.0-8333-1037,-1,-1,-1,-1
4,0ee1830b36f94447cd109decb4ddcdc552c18954d5b50ca3c0ec2a627e625029-116.203.114.0-8333-1037,223,214,223,205
5,618e2571520a26940233b21137d99696167f445439a02067c5ec4afcb4e693c0-116.203.182.0-8333-
Parse error: Error tokenizing data. C error: Expected 5 fields in line 2, saw 6


================================================================================
up_nodes_per_seconds
================================================================================

FILE: dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv
Bytes: 250
First 500 characters:
0,16
5,473
10,328
15,312
20,1099
25,473
30,330
35,383
40,452
45,261
50,273
55,349
60,224
65,205
70,278
75,177
80,150
85,226
90,143
95,142
100,167
105,135
110,120
115,127
120,112
125,85
130,112
135,74
140,53
145,42
150,8
155,0
160,2
165,0
170,0
175,1
Shape: (36, 2)
Column count: 2
First rows:

    0     1
0   0    16
1   5   473
2  10   328
3  15   312
4  20  1099
5  25   473
6  30   330
7  35   383
8  40   452
9  45   261

Column dtypes:
0    int64
1    int64
dtype: object

FILE: dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv
Bytes: 204
First 500 characters:
0,356
5,474
10,340
15,1084
20,649
25,329
30,354
35,544
40,315
45,256
50,392
55,273
60,201
65,239
70,224
75,187
80,190
85,185
90,91
95,81
100,97
105,241
110,88
115,65
120,56
125,15
130,3
135,1
140,2
145,1
Shape: (30, 2)
Column count: 2
First rows:

    0     1
0   0   356
1   5   474
2  10   340
3  15  1084
4  20   649
5  25   329
6  30   354
7  35   544
8  40   315
9  45   256

Column dtypes:
0    int64
1    int64
dtype: object

FILE: dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv
Bytes: 224
First 500 characters:
0,122
5,105
10,399
15,487
20,370
25,814
30,456
35,284
40,410
45,417
50,265
55,273
60,347
65,253
70,225
75,288
80,193
85,186
90,208
95,184
100,159
105,193
110,137
115,114
120,135
125,97
130,83
135,77
140,42
145,4
150,1
155,1
Shape: (32, 2)
Column count: 2
First rows:

    0    1
0   0  122
1   5  105
2  10  399
3  15  487
4  20  370
5  25  814
6  30  456
7  35  284
8  40  410
9  45  417

Column dtypes:
0    int64
1    int64
dtype: object

FILE: dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:50:50.csv
Bytes: 205
First 500 characters:
0,373
5,408
10,324
15,831
20,670
25,389
30,406
35,447
40,357
45,272
50,367
55,307
60,236
65,281
70,288
75,191
80,199
85,215
90,162
95,148
100,147
105,120
110,87
115,78
120,43
125,6
130,2
135,2
140,1
145,0
Shape: (30, 2)
Column count: 2
First rows:

    0    1
0   0  373
1   5  408
2  10  324
3  15  831
4  20  670
5  25  389
6  30  406
7  35  447
8  40  357
9  45  272

Column dtypes:
0    int64
1    int64
dtype: object

FILE: dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:50:50.csv
Bytes: 208
First 500 characters:
0,9
5,565
10,434
15,335
20,1237
25,523
30,290
35,332
40,537
45,245
50,224
55,392
60,204
65,216
70,255
75,213
80,154
85,194
90,170
95,127
100,167
105,142
110,101
115,108
120,81
125,52
130,55
135,6
140,2
145,4
Shape: (30, 2)
Column count: 2
First rows:

    0     1
0   0     9
1   5   565
2  10   434
3  15   335
4  20  1237
5  25   523
6  30   290
7  35   332
8  40   537
9  45   245

Column dtypes:
0    int64
1    int64
dtype: object

In [ ]:
import zipfile
import os
import pandas as pd
import numpy as np
from collections import Counter

ZIP_PATH = "/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip"
PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

# ---------------------------------------------------------
# Safe CSV parser for variable-width discovery files
# ---------------------------------------------------------

def parse_variable_csv(raw_bytes):

    text = raw_bytes.decode(
        "utf-8",
        errors="replace"
    )

    rows = []

    for line in text.splitlines():

        line = line.strip()

        if not line:
            continue

        parts = line.split(",")

        rows.append(parts)

    return rows


# ---------------------------------------------------------
# Process discovery files
# ---------------------------------------------------------

getaddr_profiles = []
up_profiles = []

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    names = z.namelist()

    getaddr_files = [
        n for n in names
        if "/nodes_per_getADDR_" in n
        and n.endswith(".csv")
    ]

    up_files = [
        n for n in names
        if "/up_nodes_per_seconds_" in n
        and n.endswith(".csv")
    ]

    print("getADDR files:", len(getaddr_files))
    print("up-node files:", len(up_files))

    # -----------------------------------------------------
    # A. nodes_per_getADDR
    # -----------------------------------------------------

    for i, path in enumerate(getaddr_files):

        raw = z.read(path)

        rows = parse_variable_csv(raw)

        row_widths = []

        numeric_values = []

        peer_count = 0

        for row in rows:

            if len(row) < 2:
                continue

            peer_count += 1

            # First field = row index
            # Second field = node endpoint
            numeric = []

            for value in row[2:]:

                try:
                    numeric.append(
                        float(value)
                    )
                except:
                    pass

            row_widths.append(
                len(numeric)
            )

            numeric_values.extend(
                numeric
            )

        if numeric_values:

            arr = np.array(
                numeric_values,
                dtype=float
            )

            valid = arr[arr >= 0]

            profile = {
                "file": path,
                "timestamp": os.path.basename(path)
                    .replace("nodes_per_getADDR_", "")
                    .replace(".csv", ""),
                "peer_rows": peer_count,
                "min_numeric_fields": min(row_widths),
                "max_numeric_fields": max(row_widths),
                "mean_numeric_fields": np.mean(row_widths),
                "total_numeric_values": len(arr),
                "valid_numeric_values": len(valid),
                "missing_numeric_values": int(
                    np.sum(arr < 0)
                ),
                "mean_valid_value": (
                    np.mean(valid)
                    if len(valid) > 0
                    else np.nan
                ),
                "median_valid_value": (
                    np.median(valid)
                    if len(valid) > 0
                    else np.nan
                ),
                "max_valid_value": (
                    np.max(valid)
                    if len(valid) > 0
                    else np.nan
                )
            }

        else:

            profile = {
                "file": path,
                "timestamp": os.path.basename(path)
                    .replace("nodes_per_getADDR_", "")
                    .replace(".csv", ""),
                "peer_rows": peer_count,
                "min_numeric_fields": 0,
                "max_numeric_fields": 0,
                "mean_numeric_fields": 0,
                "total_numeric_values": 0,
                "valid_numeric_values": 0,
                "missing_numeric_values": 0,
                "mean_valid_value": np.nan,
                "median_valid_value": np.nan,
                "max_valid_value": np.nan
            }

        getaddr_profiles.append(profile)

        if (i + 1) % 500 == 0:
            print(
                f"Processed getADDR: {i+1}/{len(getaddr_files)}"
            )

    # -----------------------------------------------------
    # B. up_nodes_per_seconds
    # -----------------------------------------------------

    for i, path in enumerate(up_files):

        raw = z.read(path)

        rows = parse_variable_csv(raw)

        seconds = []
        up_nodes = []

        for row in rows:

            if len(row) < 2:
                continue

            try:

                sec = float(row[0])
                nodes = float(row[1])

                seconds.append(sec)
                up_nodes.append(nodes)

            except:
                continue

        if up_nodes:

            arr = np.array(
                up_nodes,
                dtype=float
            )

            profile = {
                "file": path,
                "timestamp": os.path.basename(path)
                    .replace("up_nodes_per_seconds_", "")
                    .replace(".csv", ""),
                "time_points": len(seconds),
                "duration_seconds": (
                    max(seconds) - min(seconds)
                    if seconds
                    else 0
                ),
                "mean_up_nodes": np.mean(arr),
                "median_up_nodes": np.median(arr),
                "max_up_nodes": np.max(arr),
                "min_up_nodes": np.min(arr),
                "std_up_nodes": (
                    np.std(arr)
                    if len(arr) > 1
                    else 0
                )
            }

        else:

            profile = {
                "file": path,
                "timestamp": os.path.basename(path)
                    .replace("up_nodes_per_seconds_", "")
                    .replace(".csv", ""),
                "time_points": 0,
                "duration_seconds": 0,
                "mean_up_nodes": np.nan,
                "median_up_nodes": np.nan,
                "max_up_nodes": np.nan,
                "min_up_nodes": np.nan,
                "std_up_nodes": np.nan
            }

        up_profiles.append(profile)

        if (i + 1) % 500 == 0:
            print(
                f"Processed up-nodes: {i+1}/{len(up_files)}"
            )


# ---------------------------------------------------------
# Convert to DataFrames
# ---------------------------------------------------------

getaddr_df = pd.DataFrame(
    getaddr_profiles
)

up_df = pd.DataFrame(
    up_profiles
)

print("\n=== getADDR profile ===")
print(getaddr_df.shape)
display(getaddr_df.head())

print("\n=== up_nodes profile ===")
print(up_df.shape)
display(up_df.head())

# ---------------------------------------------------------
# Schema statistics
# ---------------------------------------------------------

print("\n=== getADDR numeric-field distribution ===")

print(
    getaddr_df[
        [
            "min_numeric_fields",
            "max_numeric_fields",
            "mean_numeric_fields"
        ]
    ].describe()
)

print("\n=== getADDR peer-row distribution ===")

print(
    getaddr_df["peer_rows"].describe()
)

print("\n=== up-node statistics ===")

print(
    up_df[
        [
            "time_points",
            "duration_seconds",
            "mean_up_nodes",
            "max_up_nodes",
            "std_up_nodes"
        ]
    ].describe()
)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------

getaddr_path = (
    f"{PROCESSED_DIR}/p2p3_getaddr_profile_v1.parquet"
)

up_path = (
    f"{PROCESSED_DIR}/p2p3_up_nodes_profile_v1.parquet"
)

getaddr_df.to_parquet(
    getaddr_path,
    index=False
)

up_df.to_parquet(
    up_path,
    index=False
)

print("\n✅ Step 65E complete")

print(
    "getADDR profile saved:",
    getaddr_path
)

print(
    "up-node profile saved:",
    up_path
)

getADDR files: 9481
up-node files: 9481
Processed getADDR: 500/9481
Processed getADDR: 1000/9481
Processed getADDR: 1500/9481
Processed getADDR: 2000/9481
Processed getADDR: 2500/9481
Processed getADDR: 3000/9481
Processed getADDR: 3500/9481
Processed getADDR: 4000/9481
Processed getADDR: 4500/9481
Processed getADDR: 5000/9481
Processed getADDR: 5500/9481
Processed getADDR: 6000/9481
Processed getADDR: 6500/9481
Processed getADDR: 7000/9481
Processed getADDR: 7500/9481
Processed getADDR: 8000/9481
Processed getADDR: 8500/9481
Processed getADDR: 9000/9481
Processed up-nodes: 500/9481
Processed up-nodes: 1000/9481
Processed up-nodes: 1500/9481
Processed up-nodes: 2000/9481
Processed up-nodes: 2500/9481
Processed up-nodes: 3000/9481
Processed up-nodes: 3500/9481
Processed up-nodes: 4000/9481
Processed up-nodes: 4500/9481
Processed up-nodes: 5000/9481
Processed up-nodes: 5500/9481
Processed up-nodes: 6000/9481
Processed up-nodes: 6500/9481
Processed up-nodes: 7000/9481
Processed up-nodes: 7500/9481
Processed up-nodes: 8000/9481
Processed up-nodes: 8500/9481
Processed up-nodes: 9000/9481

=== getADDR profile ===
(9481, 12)

,file,timestamp,peer_rows,min_numeric_fields,max_numeric_fields,mean_numeric_fields,total_numeric_values,valid_numeric_values,missing_numeric_values,mean_valid_value,median_valid_value,max_valid_value
0,dataset_2020/crawl/20200215/nodes_per_getADDR_...,20200215-00:31:10,7299,3,7,3.408001,24875,9171,15704,109.511722,107.0,943.0
1,dataset_2020/crawl/20200215/nodes_per_getADDR_...,20200215-08:06:30,7311,3,6,3.389687,24782,9491,15291,99.202086,98.0,927.0
2,dataset_2020/crawl/20200215/nodes_per_getADDR_...,20200215-01:11:30,7322,3,6,3.406993,24946,9126,15820,106.409818,101.0,950.0
3,dataset_2020/crawl/20200215/nodes_per_getADDR_...,20200215-08:02:30,7258,3,7,3.389363,24600,9301,15299,98.814966,97.0,979.0
4,dataset_2020/crawl/20200215/nodes_per_getADDR_...,20200215-12:43:00,7353,3,7,3.405685,25042,9467,15575,100.927643,99.0,945.0

=== up_nodes profile ===
(9481, 9)

,file,timestamp,time_points,duration_seconds,mean_up_nodes,median_up_nodes,max_up_nodes,min_up_nodes,std_up_nodes
0,dataset_2020/crawl/20200215/up_nodes_per_secon...,20200215-10:43:21,36,175.0,203.666667,146.5,1099.0,0.0,205.857286
1,dataset_2020/crawl/20200215/up_nodes_per_secon...,20200215-15:14:50,30,145.0,244.433333,212.5,1084.0,1.0,226.859381
2,dataset_2020/crawl/20200215/up_nodes_per_secon...,20200215-10:23:00,32,155.0,229.031250,193.0,814.0,1.0,169.744382
3,dataset_2020/crawl/20200215/up_nodes_per_secon...,20200215-09:50:50,30,145.0,245.233333,225.5,831.0,0.0,194.233310
4,dataset_2020/crawl/20200215/up_nodes_per_secon...,20200215-14:50:50,30,145.0,245.800000,199.0,1237.0,2.0,241.172469

=== getADDR numeric-field distribution ===
       min_numeric_fields  max_numeric_fields  mean_numeric_fields
count              9481.0         9481.000000          9481.000000
mean                  3.0            6.795908             3.423735
std                   0.0            0.491927             0.038127
min                   3.0            6.000000             3.319835
25%                   3.0            7.000000             3.405641
50%                   3.0            7.000000             3.418320
75%                   3.0            7.000000             3.433952
max                   3.0           10.000000             3.855323

=== getADDR peer-row distribution ===
count    9481.000000
mean     7184.939036
std       281.197787
min      5506.000000
25%      7192.000000
50%      7308.000000
75%      7347.000000
max      7623.000000
Name: peer_rows, dtype: float64

=== up-node statistics ===
       time_points  duration_seconds  mean_up_nodes  max_up_nodes  \
count  9481.000000       9481.000000    9481.000000   9481.000000
mean     31.418627        152.093134     238.809076    965.936399
std      12.722523         63.612617      41.113054    262.806707
min      22.000000        105.000000       0.000000    157.000000
25%      28.000000        135.000000     225.500000    749.000000
50%      30.000000        145.000000     243.166667    946.000000
75%      32.000000        155.000000     261.428571   1171.000000
max     169.000000        840.000000     336.545455   1654.000000

       std_up_nodes
count   9481.000000
mean     222.326639
std       79.042456
min      112.094391
25%      187.710141
50%      213.166993
75%      242.390337
max     1531.890490

✅ Step 65E complete
getADDR profile saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_getaddr_profile_v1.parquet
up-node profile saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_up_nodes_profile_v1.parquet

Build P2P-3 discovery features

In [ ]:
from google.colab import drive
import os

drive.mount('/content/drive')

ZIP_PATH = "/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip"
PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

print("ZIP exists:", os.path.exists(ZIP_PATH))
print("Processed directory exists:", os.path.exists(PROCESSED_DIR))

if os.path.exists(ZIP_PATH):
    size_gb = os.path.getsize(ZIP_PATH) / (1024**3)
    print(f"ZIP size: {size_gb:.2f} GB")

if os.path.exists(PROCESSED_DIR):
    print("\nProcessed files:")
    for f in os.listdir(PROCESSED_DIR):
        print(f)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ZIP exists: True
Processed directory exists: True
ZIP size: 33.91 GB

Processed files:
p2p_observations_20200215.parquet
observations
metadata
node_observation_frequency.parquet
p2p_peer_features_v1.parquet
p2p_peer_features_p2p1_clean.parquet
p2p_peer_temporal_features_v1.parquet
p2p_peer_temporal_basic_v1.parquet
p2p_peer_intervals_v1.parquet
p2p_peer_burst_features_v1.parquet
p2p_peer_features_v2_temporal.parquet
tmp_p2p_peer_features_v1.parquet
p2p_ml_matrix_v2.parquet
p2p_isolation_forest_v1_scores.parquet
p2p_isolation_forest_v1_explanations.parquet
p2p_anomaly_population_summary.parquet
p2p3_getaddr_profile_v1.parquet
p2p3_up_nodes_profile_v1.parquet

In [ ]:
import zipfile
import os
import numpy as np
import pandas as pd
from collections import defaultdict

ZIP_PATH = "/content/drive/MyDrive/Bitcoin P2P Dataset/dataset.zip"
PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

OUTPUT_PATH = (
    f"{PROCESSED_DIR}/p2p3_peer_getaddr_features_v1.parquet"
)

# ---------------------------------------------------------
# Node-level running aggregates
# ---------------------------------------------------------

stats = defaultdict(lambda: {
    "observation_count": 0,
    "active_snapshots": set(),

    "sum_mean_value": 0.0,
    "count_mean_value": 0,

    "valid_value_count": 0,
    "missing_value_count": 0,

    "max_value": np.nan,

    "sum_std_value": 0.0,
    "count_std_value": 0,

    # For an approximate median later
    "sample_values": []
})


def parse_node_id(endpoint):
    """
    Observed endpoint format:
    node_id-IP-port-service
    """
    parts = endpoint.split("-")

    if len(parts) < 4:
        return None

    return parts[0]


# ---------------------------------------------------------
# Process ZIP incrementally
# ---------------------------------------------------------

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    getaddr_files = [
        n for n in z.namelist()
        if "/nodes_per_getADDR_" in n
        and n.endswith(".csv")
    ]

    getaddr_files.sort()

    print("getADDR files:", len(getaddr_files))
    print("Starting RAM-safe aggregation...\n")

    for i, path in enumerate(getaddr_files):

        filename = os.path.basename(path)

        timestamp = (
            filename
            .replace("nodes_per_getADDR_", "")
            .replace(".csv", "")
        )

        # Read ONE file only
        with z.open(path) as f:

            for raw_line in f:

                try:
                    line = raw_line.decode(
                        "utf-8",
                        errors="replace"
                    ).strip()

                except Exception:
                    continue

                if not line:
                    continue

                parts = line.split(",")

                if len(parts) < 3:
                    continue

                endpoint = parts[1]

                node_id = parse_node_id(endpoint)

                if node_id is None:
                    continue

                # -------------------------------------------------
                # Parse numeric fields
                # -------------------------------------------------

                valid_values = []
                missing_count = 0

                for value in parts[2:]:

                    try:
                        v = float(value)

                    except (ValueError, TypeError):
                        continue

                    if v < 0:
                        missing_count += 1
                    else:
                        valid_values.append(v)

                if not valid_values and missing_count == 0:
                    continue

                s = stats[node_id]

                s["observation_count"] += 1
                s["active_snapshots"].add(timestamp)

                # -------------------------------------------------
                # Valid values
                # -------------------------------------------------

                if valid_values:

                    arr = np.asarray(
                        valid_values,
                        dtype=np.float64
                    )

                    mean_value = float(np.mean(arr))
                    std_value = (
                        float(np.std(arr))
                        if len(arr) > 1
                        else 0.0
                    )

                    s["sum_mean_value"] += mean_value
                    s["count_mean_value"] += 1

                    s["sum_std_value"] += std_value
                    s["count_std_value"] += 1

                    s["valid_value_count"] += len(arr)

                    current_max = float(np.max(arr))

                    if (
                        np.isnan(s["max_value"])
                        or current_max > s["max_value"]
                    ):
                        s["max_value"] = current_max

                    # Keep only a bounded sample for median
                    if len(s["sample_values"]) < 100:
                        remaining = 100 - len(s["sample_values"])
                        s["sample_values"].extend(
                            arr[:remaining].tolist()
                        )

                s["missing_value_count"] += missing_count

        # ---------------------------------------------------------
        # Progress
        # ---------------------------------------------------------

        if (i + 1) % 250 == 0:

            print(
                f"Processed "
                f"{i + 1}/{len(getaddr_files)} files | "
                f"Unique nodes: {len(stats):,}"
            )


# ---------------------------------------------------------
# Build final peer-level DataFrame
# ---------------------------------------------------------

rows = []

for node_id, s in stats.items():

    total_measurements = (
        s["valid_value_count"]
        +
        s["missing_value_count"]
    )

    if s["sample_values"]:

        median_value = float(
            np.median(
                np.asarray(
                    s["sample_values"],
                    dtype=np.float64
                )
            )
        )

    else:
        median_value = np.nan

    rows.append({

        "node_id": node_id,

        "getaddr_observation_count":
            s["observation_count"],

        "getaddr_active_snapshots":
            len(s["active_snapshots"]),

        "getaddr_mean_value":
            (
                s["sum_mean_value"]
                /
                s["count_mean_value"]
                if s["count_mean_value"] > 0
                else np.nan
            ),

        "getaddr_median_value":
            median_value,

        "getaddr_max_value":
            s["max_value"],

        "getaddr_std_value":
            (
                s["sum_std_value"]
                /
                s["count_std_value"]
                if s["count_std_value"] > 0
                else 0.0
            ),

        "getaddr_valid_value_count":
            s["valid_value_count"],

        "getaddr_missing_value_count":
            s["missing_value_count"],

        "getaddr_missing_ratio":
            (
                s["missing_value_count"]
                /
                total_measurements
                if total_measurements > 0
                else 0.0
            )
    })


peer_getaddr = pd.DataFrame(rows)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------

peer_getaddr.to_parquet(
    OUTPUT_PATH,
    index=False
)

print("\n========================================")
print("✅ Step 66A complete")
print("========================================")

print(
    "Peer feature shape:",
    peer_getaddr.shape
)

print(
    "Missing values:",
    int(peer_getaddr.isna().sum().sum())
)

print(
    "Saved:",
    OUTPUT_PATH
)

display(peer_getaddr.head(20))

getADDR files: 9481
Starting RAM-safe aggregation...

Processed 250/9481 files | Unique nodes: 8,640
Processed 500/9481 files | Unique nodes: 9,029
Processed 750/9481 files | Unique nodes: 9,347
Processed 1000/9481 files | Unique nodes: 9,656
Processed 1250/9481 files | Unique nodes: 9,975
Processed 1500/9481 files | Unique nodes: 10,253
Processed 1750/9481 files | Unique nodes: 10,531
Processed 2000/9481 files | Unique nodes: 10,823
Processed 2250/9481 files | Unique nodes: 11,084
Processed 2500/9481 files | Unique nodes: 11,315
Processed 2750/9481 files | Unique nodes: 11,568
Processed 3000/9481 files | Unique nodes: 11,827
Processed 3250/9481 files | Unique nodes: 12,055
Processed 3500/9481 files | Unique nodes: 12,284
Processed 3750/9481 files | Unique nodes: 12,521
Processed 4000/9481 files | Unique nodes: 12,720
Processed 4250/9481 files | Unique nodes: 12,968
Processed 4500/9481 files | Unique nodes: 13,184
Processed 4750/9481 files | Unique nodes: 13,427
Processed 5000/9481 files | Unique nodes: 13,654
Processed 5250/9481 files | Unique nodes: 13,891
Processed 5500/9481 files | Unique nodes: 14,115
Processed 5750/9481 files | Unique nodes: 14,282
Processed 6000/9481 files | Unique nodes: 14,482
Processed 6250/9481 files | Unique nodes: 14,696
Processed 6500/9481 files | Unique nodes: 14,882
Processed 6750/9481 files | Unique nodes: 15,096
Processed 7000/9481 files | Unique nodes: 15,326
Processed 7250/9481 files | Unique nodes: 15,509
Processed 7500/9481 files | Unique nodes: 15,716
Processed 7750/9481 files | Unique nodes: 15,938
Processed 8000/9481 files | Unique nodes: 16,144
Processed 8250/9481 files | Unique nodes: 16,324
Processed 8500/9481 files | Unique nodes: 16,533
Processed 8750/9481 files | Unique nodes: 16,750
Processed 9000/9481 files | Unique nodes: 16,900
Processed 9250/9481 files | Unique nodes: 19,517

========================================
✅ Step 66A complete
========================================
Peer feature shape: (21122, 10)
Missing values: 1239
Saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_peer_getaddr_features_v1.parquet

,node_id,getaddr_observation_count,getaddr_active_snapshots,getaddr_mean_value,getaddr_median_value,getaddr_max_value,getaddr_std_value,getaddr_valid_value_count,getaddr_missing_value_count,getaddr_missing_ratio
0,2a7ac073bef1272aacbe3c16668d6d9466f88cfee94c01...,4329,4329,223.679334,212.5,997.0,17.124895,13813,2927,0.174851
1,b141633ee4e4ce80692e270fa31172865f299bd35ac3c2...,4235,4235,220.301345,201.0,997.0,14.684792,12897,2727,0.174539
2,fd2d5f314c69bb98de5f5b3054412c19a6f79e02e25023...,8995,8995,82.789760,86.0,132.0,14.272339,4308,27961,0.866497
3,3c966da36d5210a10f0e83f88f8cc6bfa43c5335c9e79b...,9473,9473,116.744380,119.0,993.0,12.086269,3208,28478,0.898757
4,023e70ef58ac7635b36b83728117302c17db9486e6f2e6...,9469,9469,120.502340,105.0,997.0,34.182827,6704,36283,0.844046
5,510b7747cdb4868b554b2f75810382a1abdfeaab6dd97c...,8906,8906,102.198436,111.0,154.0,0.469556,4164,22630,0.844592
6,eed25f6c8ada1cd6f7b9c96ba23788189b89d3b108b12f...,9458,9458,121.533200,122.0,996.0,32.029307,8767,32313,0.786587
7,cd5388a16af9ccb3af585ad082327da05b04fd4bcc56fc...,6628,6628,105.563502,104.0,155.0,5.802088,2410,18765,0.886187
8,f9bad19d1e7c7fa82d7ca949b4a466e010ea972e2d2dec...,9236,9236,129.723522,118.0,992.0,0.211860,1540,26212,0.944509
9,ac83914c8111fb114faffc5a51880fc758f74958e4d34a...,8395,8395,92.974986,64.5,996.0,14.735695,15612,15456,0.497489
10,30c4bc63ce63a682491cdd43b84be51ebe5ee32fdc8cdf...,9351,9351,107.744703,131.0,939.0,14.395193,14466,18523,0.561490
11,97b5bf7251099899be14434da535d885e93af189f84de5...,9457,9457,102.993371,103.5,996.0,16.371688,8359,25591,0.753785
12,c2a3d4678f36b704499c8d6f1df89b5b8e16a6f5010616...,8822,8822,117.870543,123.0,181.0,0.133747,5160,21337,0.805261
13,cb69573f1c4c0740ed2e913aa0b992ecc93193bc8289eb...,8998,8998,91.632527,95.0,162.0,26.519120,7295,33737,0.822212
14,aec6e741f81996ed15dea8aef771b46f090cad6abd2f14...,7922,7922,109.967372,114.0,994.0,15.370646,8115,20069,0.712071
15,607993bdbb84f05148ee2cd7b4904b3787d817e6078977...,8876,8876,104.808678,104.0,146.0,0.249087,3339,23377,0.875019
16,e3baf20ecb9465305149c5063b7f95f0ccbdbf3591f63c...,9381,9381,124.032774,123.0,993.0,3.760058,2505,26002,0.912127
17,bab26f9a6fc2abcc862a112f12cf8f0151e3773c408d59...,1731,1731,72.674180,71.5,129.0,10.390321,3049,3178,0.510358
18,fe8621a996ef9e2d5049f9eaf84421d4ab7ebc44c46836...,7093,7093,71.544722,70.0,131.0,13.910223,5039,21339,0.808970
19,c1f78c7bf23733ccb07742fffe61dd426c28d24eb8cde0...,9475,9475,104.860531,109.0,996.0,27.211212,12132,29631,0.709504

In [ ]:
import pandas as pd
import numpy as np
import os

GETADDR_PATH = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed/"
    "p2p3_peer_getaddr_features_v1.parquet"
)

df = pd.read_parquet(GETADDR_PATH)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nDtypes:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate node IDs:")
print(df["node_id"].duplicated().sum())

print("\nNumeric summary:")
display(df.describe().T)

print("\nMissing-ratio summary:")
display(
    df["getaddr_missing_ratio"].describe()
)

print("\nTop 10 by getADDR observation count:")
display(
    df.sort_values(
        "getaddr_observation_count",
        ascending=False
    ).head(10)
)

Shape: (21122, 10)

Columns:
['node_id', 'getaddr_observation_count', 'getaddr_active_snapshots', 'getaddr_mean_value', 'getaddr_median_value', 'getaddr_max_value', 'getaddr_std_value', 'getaddr_valid_value_count', 'getaddr_missing_value_count', 'getaddr_missing_ratio']

Dtypes:
node_id                         object
getaddr_observation_count        int64
getaddr_active_snapshots         int64
getaddr_mean_value             float64
getaddr_median_value           float64
getaddr_max_value              float64
getaddr_std_value              float64
getaddr_valid_value_count        int64
getaddr_missing_value_count      int64
getaddr_missing_ratio          float64
dtype: object

Missing values:
node_id                          0
getaddr_observation_count        0
getaddr_active_snapshots         0
getaddr_mean_value             413
getaddr_median_value           413
getaddr_max_value              413
getaddr_std_value                0
getaddr_valid_value_count        0
getaddr_missing_value_count      0
getaddr_missing_ratio            0
dtype: int64

Duplicate node IDs:
0

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
getaddr_observation_count,21122.0,3225.092652,3942.663890,1.0,129.250000,481.000000,7711.750000,28442.000000
getaddr_active_snapshots,21122.0,3196.518654,3866.396277,1.0,129.000000,481.000000,7696.250000,9481.000000
getaddr_mean_value,20709.0,169.433828,245.202398,0.0,61.389262,89.000000,118.082757,2499.548387
getaddr_median_value,20709.0,150.717804,246.810625,0.0,56.000000,78.000000,110.500000,2500.000000
getaddr_max_value,20709.0,418.433628,425.070410,0.0,90.000000,150.000000,994.000000,2509.000000
getaddr_std_value,21122.0,8.046353,17.089201,0.0,0.000000,0.212195,12.460583,231.931024
getaddr_valid_value_count,21122.0,4202.351435,6018.845967,0.0,183.000000,639.000000,7336.500000,56460.000000
getaddr_missing_value_count,21122.0,6837.244153,9133.878731,0.0,226.250000,882.500000,14903.500000,58616.000000
getaddr_missing_ratio,21122.0,0.594520,0.157333,0.0,0.525004,0.589074,0.627907,1.000000

Missing-ratio summary:

count    21122.000000
mean         0.594520
std          0.157333
min          0.000000
25%          0.525004
50%          0.589074
75%          0.627907
max          1.000000
Name: getaddr_missing_ratio, dtype: float64

Top 10 by getADDR observation count:

,node_id,getaddr_observation_count,getaddr_active_snapshots,getaddr_mean_value,getaddr_median_value,getaddr_max_value,getaddr_std_value,getaddr_valid_value_count,getaddr_missing_value_count,getaddr_missing_ratio
4379,169edae71b08296937e2b3ca7307aee718a53c4c379091...,28442,9481,86.742543,60.0,998.0,0.212961,35180,50284,0.588365
1136,761ed63b1b957cbdb3179c6d83785773a9fd897693cd2f...,28442,9481,176.308812,129.0,1001.0,2.729338,35370,50363,0.587440
1797,695a85a1a910a0a34a72b673c2805ced69fdd7497b7eee...,28442,9481,115.073274,91.0,998.0,19.307077,51377,54984,0.516956
2345,6ae322138ccf86a19811196441304f51f8e53f2dfabc03...,28298,9481,100.570582,70.0,996.0,0.970505,26511,58616,0.688571
1927,5b92307f407f3166be6e9411d531a4bc8a729d8aae8842...,27358,9480,84.577111,58.0,998.0,2.315027,35256,48406,0.578590
4831,91f225e8f0709964d34b6d2120e9cbe76d2a3d8c416adf...,19442,9481,95.155680,69.0,997.0,15.205335,36543,35649,0.493808
3281,66e3f19e8ee2767dee56a2f2cc322adece28b817e62bbc...,18962,9481,107.175651,102.0,997.0,24.970249,43341,38094,0.467784
1421,8d098f0ae598685d9d49f1022a23196b3260e59c9198b1...,18961,9481,151.330433,85.0,999.0,34.560564,40394,43560,0.518856
1042,9ebff9e6ed18b3632dc3acbf0411b1101076dac66e4197...,18961,9481,89.795576,76.0,943.0,15.866016,37054,35854,0.491770
3669,5c7026d0176ac018b57da166549506568e39c0c844c66d...,18961,9481,94.615280,65.0,998.0,15.273601,28319,40607,0.589139

In [ ]:
import pandas as pd
import numpy as np

GETADDR_PATH = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed/"
    "p2p3_peer_getaddr_features_v1.parquet"
)

df = pd.read_parquet(GETADDR_PATH)

numeric_cols = df.select_dtypes(
    include=[np.number]
).columns.tolist()

# ---------------------------------------------------------
# 1. Constant / near-constant features
# ---------------------------------------------------------

quality = []

for col in numeric_cols:

    s = df[col]

    quality.append({
        "feature": col,
        "missing": int(s.isna().sum()),
        "unique": int(s.nunique()),
        "mean": float(s.mean()),
        "std": float(s.std()),
        "min": float(s.min()),
        "max": float(s.max()),
        "skew": float(s.skew())
    })

quality_df = pd.DataFrame(quality)

print("=== FEATURE QUALITY ===")
display(
    quality_df.sort_values(
        "skew",
        key=lambda x: x.abs(),
        ascending=False
    )
)

# ---------------------------------------------------------
# 2. Highly correlated features
# ---------------------------------------------------------

corr = df[numeric_cols].corr()

pairs = []

for i in range(len(numeric_cols)):

    for j in range(i + 1, len(numeric_cols)):

        value = corr.iloc[i, j]

        if abs(value) >= 0.90:

            pairs.append({
                "feature_1": numeric_cols[i],
                "feature_2": numeric_cols[j],
                "correlation": value
            })

corr_df = pd.DataFrame(pairs)

print("\n=== HIGH CORRELATIONS (|r| >= 0.90) ===")

if len(corr_df) > 0:
    display(
        corr_df.sort_values(
            "correlation",
            key=lambda x: x.abs(),
            ascending=False
        )
    )
else:
    print("No correlations >= 0.90")

# ---------------------------------------------------------
# 3. Extreme missing-ratio groups
# ---------------------------------------------------------

print("\n=== MISSING-RATIO DISTRIBUTION ===")

display(
    df["getaddr_missing_ratio"].describe(
        percentiles=[
            .01, .05, .10,
            .25, .50, .75,
            .90, .95, .99
        ]
    )
)

print("\n=== PEERS WITH 100% MISSING GETADDR VALUES ===")

print(
    (
        df["getaddr_missing_ratio"] == 1.0
    ).sum()
)

# ---------------------------------------------------------
# 4. Zero-valid-value peers
# ---------------------------------------------------------

print("\n=== PEERS WITH ZERO VALID VALUES ===")

print(
    (
        df["getaddr_valid_value_count"] == 0
    ).sum()
)

=== FEATURE QUALITY ===

,feature,missing,unique,mean,std,min,max,skew
5,getaddr_std_value,0,14488,8.046353,17.089201,0.0,231.931024,4.870551
3,getaddr_median_value,413,755,150.717804,246.810625,0.0,2500.000000,3.316184
2,getaddr_mean_value,413,19508,169.433828,245.202398,0.0,2499.548387,2.985274
6,getaddr_valid_value_count,0,8003,4202.351435,6018.845967,0.0,56460.000000,1.693363
7,getaddr_missing_value_count,0,8773,6837.244153,9133.878731,0.0,58616.000000,1.190077
0,getaddr_observation_count,0,4658,3225.092652,3942.663890,1.0,28442.000000,0.843251
1,getaddr_active_snapshots,0,4586,3196.518654,3866.396277,1.0,9481.000000,0.722594
4,getaddr_max_value,413,610,418.433628,425.070410,0.0,2509.000000,0.704264
8,getaddr_missing_ratio,0,15985,0.594520,0.157333,0.0,1.000000,-0.277944

=== HIGH CORRELATIONS (|r| >= 0.90) ===

                   feature_1                    feature_2  correlation
0  getaddr_observation_count     getaddr_active_snapshots     0.991147
3         getaddr_mean_value         getaddr_median_value     0.961782
1  getaddr_observation_count  getaddr_missing_value_count     0.948335
2   getaddr_active_snapshots  getaddr_missing_value_count     0.943958

=== MISSING-RATIO DISTRIBUTION ===

count    21122.000000
mean         0.594520
std          0.157333
min          0.000000
1%           0.000000
5%           0.395387
10%          0.480769
25%          0.525004
50%          0.589074
75%          0.627907
90%          0.810283
95%          0.907438
99%          1.000000
max          1.000000
Name: getaddr_missing_ratio, dtype: float64

=== PEERS WITH 100% MISSING GETADDR VALUES ===
413

=== PEERS WITH ZERO VALID VALUES ===
413

In [ ]:
import pandas as pd
import numpy as np

GETADDR_PATH = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed/"
    "p2p3_peer_getaddr_features_v1.parquet"
)

OUTPUT_PATH = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed/"
    "p2p3_peer_getaddr_features_clean_v1.parquet"
)

df = pd.read_parquet(GETADDR_PATH)

# ---------------------------------------------------------
# Select P2P-3 getADDR features
# ---------------------------------------------------------

keep_cols = [
    "node_id",
    "getaddr_observation_count",
    "getaddr_mean_value",
    "getaddr_max_value",
    "getaddr_std_value",
    "getaddr_valid_value_count",
    "getaddr_missing_ratio"
]

clean = df[keep_cols].copy()

# ---------------------------------------------------------
# Preserve missingness explicitly
# ---------------------------------------------------------

value_cols = [
    "getaddr_mean_value",
    "getaddr_max_value"
]

for col in value_cols:
    clean[col] = clean[col].fillna(0.0)

# ---------------------------------------------------------
# Validation
# ---------------------------------------------------------

print("Shape:", clean.shape)

print("\nColumns:")
print(clean.columns.tolist())

print("\nMissing values:")
print(clean.isna().sum())

print("\nDuplicate node IDs:")
print(clean["node_id"].duplicated().sum())

print("\nSummary:")
display(clean.describe().T)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------

clean.to_parquet(
    OUTPUT_PATH,
    index=False
)

print("\n✅ Step 66D complete")
print("Saved:", OUTPUT_PATH)

Shape: (21122, 7)

Columns:
['node_id', 'getaddr_observation_count', 'getaddr_mean_value', 'getaddr_max_value', 'getaddr_std_value', 'getaddr_valid_value_count', 'getaddr_missing_ratio']

Missing values:
node_id                      0
getaddr_observation_count    0
getaddr_mean_value           0
getaddr_max_value            0
getaddr_std_value            0
getaddr_valid_value_count    0
getaddr_missing_ratio        0
dtype: int64

Duplicate node IDs:
0

Summary:

,count,mean,std,min,25%,50%,75%,max
getaddr_observation_count,21122.0,3225.092652,3942.663890,1.0,129.250000,481.000000,7711.750000,28442.000000
getaddr_mean_value,21122.0,166.120876,243.924012,0.0,60.483420,87.505484,117.131571,2499.548387
getaddr_max_value,21122.0,410.251965,424.862853,0.0,88.000000,147.000000,994.000000,2509.000000
getaddr_std_value,21122.0,8.046353,17.089201,0.0,0.000000,0.212195,12.460583,231.931024
getaddr_valid_value_count,21122.0,4202.351435,6018.845967,0.0,183.000000,639.000000,7336.500000,56460.000000
getaddr_missing_ratio,21122.0,0.594520,0.157333,0.0,0.525004,0.589074,0.627907,1.000000

✅ Step 66D complete
Saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_peer_getaddr_features_clean_v1.parquet

In [ ]:
import pandas as pd
import os

PROCESSED_DIR = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
)

P2P_BASE = (
    f"{PROCESSED_DIR}/p2p_peer_features_v2_temporal.parquet"
)

GETADDR = (
    f"{PROCESSED_DIR}/p2p3_peer_getaddr_features_clean_v1.parquet"
)

OUTPUT = (
    f"{PROCESSED_DIR}/p2p_peer_features_v3_p2p3.parquet"
)

# ---------------------------------------------------------
# Load existing P2P-1 + P2P-2 feature table
# ---------------------------------------------------------

base = pd.read_parquet(P2P_BASE)

print("Base shape:", base.shape)

# ---------------------------------------------------------
# Load clean P2P-3 features
# ---------------------------------------------------------

getaddr = pd.read_parquet(GETADDR)

print("P2P-3 shape:", getaddr.shape)

# ---------------------------------------------------------
# Merge on node_id
# ---------------------------------------------------------

merged = base.merge(
    getaddr,
    on="node_id",
    how="left",
    validate="one_to_one"
)

print("\nMerged shape:", merged.shape)

# ---------------------------------------------------------
# Validation
# ---------------------------------------------------------

print("\nMissing values:")
print(
    merged.isna().sum()
    .sort_values(ascending=False)
    .head(20)
)

print(
    "\nDuplicate node IDs:",
    merged["node_id"].duplicated().sum()
)

print(
    "Base nodes:",
    base["node_id"].nunique()
)

print(
    "Merged nodes:",
    merged["node_id"].nunique()
)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------

merged.to_parquet(
    OUTPUT,
    index=False
)

print("\n✅ Step 66E complete")
print("Saved:", OUTPUT)

Base shape: (21122, 31)
P2P-3 shape: (21122, 7)

Merged shape: (21122, 37)

Missing values:
getaddr_std_value                21122
getaddr_observation_count        21122
getaddr_mean_value               21122
getaddr_missing_ratio            21122
getaddr_valid_value_count        21122
getaddr_max_value                21122
daily_activity_cv                 5673
daily_activity_std                5673
hourly_activity_variance           907
hourly_activity_std                907
hourly_activity_cv                 907
node_id                              0
observation_count                    0
observation_span_seconds             0
active_hours                         0
active_days                          0
unique_ports                         0
non_1037_service_observations        0
unique_services                      0
non_default_port_observations        0
dtype: int64

Duplicate node IDs: 0
Base nodes: 21122
Merged nodes: 21122

✅ Step 66E complete
Saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_peer_features_v3_p2p3.parquet

In [ ]:
import pandas as pd

PROCESSED_DIR = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
)

BASE_PATH = (
    f"{PROCESSED_DIR}/p2p_peer_features_v2_temporal.parquet"
)

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_peer_getaddr_features_clean_v1.parquet"
)

base = pd.read_parquet(BASE_PATH)
getaddr = pd.read_parquet(GETADDR_PATH)

base_ids = set(base["node_id"].astype(str))
getaddr_ids = set(getaddr["node_id"].astype(str))

intersection = base_ids & getaddr_ids

print("Base unique IDs:", len(base_ids))
print("getADDR unique IDs:", len(getaddr_ids))
print("Matching IDs:", len(intersection))

print(
    "Base IDs not in getADDR:",
    len(base_ids - getaddr_ids)
)

print(
    "getADDR IDs not in Base:",
    len(getaddr_ids - base_ids)
)

print("\nBase sample IDs:")
print(base["node_id"].head(5).tolist())

print("\ngetADDR sample IDs:")
print(getaddr["node_id"].head(5).tolist())

# ---------------------------------------------------------
# Check string lengths
# ---------------------------------------------------------

print("\nBase ID lengths:")
print(
    base["node_id"]
    .astype(str)
    .str.len()
    .value_counts()
    .sort_index()
)

print("\ngetADDR ID lengths:")
print(
    getaddr["node_id"]
    .astype(str)
    .str.len()
    .value_counts()
    .sort_index()
)

Base unique IDs: 21122
getADDR unique IDs: 21122
Matching IDs: 0
Base IDs not in getADDR: 21122
getADDR IDs not in Base: 21122

Base sample IDs:
['24c7c31d5c1dee3296b30228b104de3032fdc03d835d0038e461647feb320651', 'bf4cbf26150152d044c036ae4c716b563b5399af67c75d1b53aaf0718114ea2f', '9edf44d735ff2dc2e381ca9d832a86b5b4def4d1924e46d09800f817a5b7ce0e', 'e459aeba62753812bd4938641f6a24af9eb3cd092851da03ee9af56b4a3c6d3b', 'e9662e63d1e93099b9f012286f9e49f154ee064026e2d93eda650e5e03998c5a']

getADDR sample IDs:
['2a7ac073bef1272aacbe3c16668d6d9466f88cfee94c013924614fcddd3ad3f7', 'b141633ee4e4ce80692e270fa31172865f299bd35ac3c29d9d9ba1224e84028e', 'fd2d5f314c69bb98de5f5b3054412c19a6f79e02e250231106178154e41d17c6', '3c966da36d5210a10f0e83f88f8cc6bfa43c5335c9e79b1b16cb8c8d12fb9177', '023e70ef58ac7635b36b83728117302c17db9486e6f2e631557127e892488dd8']

Base ID lengths:
node_id
64    21122
Name: count, dtype: int64

getADDR ID lengths:
node_id
64    21122
Name: count, dtype: int64

In [ ]:
import os
import pandas as pd

PROCESSED_DIR = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
)

OBS_DIR = os.path.join(
    PROCESSED_DIR,
    "observations"
)

print("Observation directory exists:", os.path.exists(OBS_DIR))

print("\nObservation files:")
obs_files = sorted(os.listdir(OBS_DIR))

for f in obs_files[:10]:
    print(f)

print("\nTotal observation files:", len(obs_files))

# ---------------------------------------------------------
# Load only node_id column from first observation Parquet
# ---------------------------------------------------------

first_obs = os.path.join(
    OBS_DIR,
    obs_files[0]
)

print("\nTesting file:")
print(first_obs)

obs = pd.read_parquet(
    first_obs,
    columns=["node_id"]
)

obs_ids = set(
    obs["node_id"].astype(str)
)

# ---------------------------------------------------------
# Load getADDR IDs
# ---------------------------------------------------------

GETADDR_PATH = (
    f"{PROCESSED_DIR}/"
    "p2p3_peer_getaddr_features_clean_v1.parquet"
)

getaddr = pd.read_parquet(
    GETADDR_PATH,
    columns=["node_id"]
)

getaddr_ids = set(
    getaddr["node_id"].astype(str)
)

# ---------------------------------------------------------
# Compare
# ---------------------------------------------------------

matching = obs_ids & getaddr_ids

print("\n================================")
print("ID OVERLAP CHECK")
print("================================")

print("Observation IDs:", len(obs_ids))
print("getADDR IDs:", len(getaddr_ids))
print("Matching IDs:", len(matching))

print(
    "getADDR IDs not in observation:",
    len(getaddr_ids - obs_ids)
)

print(
    "Observation IDs not in getADDR:",
    len(obs_ids - getaddr_ids)
)

print("\nObservation sample:")
print(list(obs_ids)[:5])

print("\ngetADDR sample:")
print(list(getaddr_ids)[:5])

Observation directory exists: True

Observation files:
p2p_observations_20200207.parquet
p2p_observations_20200208.parquet
p2p_observations_20200209.parquet
p2p_observations_20200210.parquet
p2p_observations_20200211.parquet
p2p_observations_20200212.parquet
p2p_observations_20200213.parquet
p2p_observations_20200214.parquet
p2p_observations_20200215.parquet
p2p_observations_20200216.parquet

Total observation files: 27

Testing file:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/observations/p2p_observations_20200207.parquet

================================
ID OVERLAP CHECK
================================
Observation IDs: 8805
getADDR IDs: 21122
Matching IDs: 0
getADDR IDs not in observation: 21122
Observation IDs not in getADDR: 8805

Observation sample:
['797fdb68a7edeae93684a1b4fba7c17bbec3df2d86e08801e6131e24cfb99816', '764151bf2e1344c5aaaef6008b9113388b19a90a5f2ea36e0c0a98d1f3ea6dd5', 'f15685342310cb14e8c37ad7ef73c55343a3be8bab36dbc784495cb06653e5fa', '32691f5833c3cc4a396c07e460d6f73043393a442323271dbab5eee8d4a9fbca', '2954db983c6ceac99b601c25022e06f58963d0b43d5565e1b3be1a2422fd7231']

getADDR sample:
['4509fcced10c631e85d53610abe0a675ad19a4772ad119daeb3d7be4f7a648e2', '7ca546fd7250b35da5e721106378ca3cfa6094b71cf5275b05534b73d0979760', '804e4f7f4858728daf1cb2281c040addcb5055deba808e3293565c5abcf8620f', 'c11ed45bbde2df7dc2d215faf90be1f2030685aa67e6bbdda8eb897c6277147c', 'fd258dd545a4d3533b4951daf4e35aa6c89e0a088c9cdb21967c4c6157d506c3']

In [ ]:
import os
import pandas as pd

PROCESSED_DIR = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
)

files_to_check = [
    "p2p_peer_features_v2_temporal.parquet",
    "p2p_ml_matrix_v2.parquet",
    "p2p_isolation_forest_v1_scores.parquet",
    "p2p_isolation_forest_v1_explanations.parquet",
    "p2p_anomaly_population_summary.parquet",
    "p2p3_getaddr_profile_v1.parquet",
    "p2p3_up_nodes_profile_v1.parquet",
    "p2p3_peer_getaddr_features_v1.parquet",
    "p2p3_peer_getaddr_features_clean_v1.parquet",
]

print("=== BIT-TRACE P2P STATE CHECK ===\n")

for filename in files_to_check:

    path = os.path.join(
        PROCESSED_DIR,
        filename
    )

    if os.path.exists(path):

        size_mb = os.path.getsize(path) / (1024 ** 2)

        print(
            f"✅ {filename:<50} "
            f"{size_mb:.2f} MB"
        )

    else:

        print(
            f"❌ MISSING: {filename}"
        )

print("\n=== P2P-3 CLEAN FEATURE CHECK ===")

path = os.path.join(
    PROCESSED_DIR,
    "p2p3_peer_getaddr_features_clean_v1.parquet"
)

df = pd.read_parquet(path)

print("Shape:", df.shape)
print("Missing values:", int(df.isna().sum().sum()))
print("Unique nodes:", df["node_id"].nunique())

=== BIT-TRACE P2P STATE CHECK ===

❌ MISSING: p2p_peer_features_v2_temporal.parquet
❌ MISSING: p2p_ml_matrix_v2.parquet
❌ MISSING: p2p_isolation_forest_v1_scores.parquet
❌ MISSING: p2p_isolation_forest_v1_explanations.parquet
❌ MISSING: p2p_anomaly_population_summary.parquet
❌ MISSING: p2p3_getaddr_profile_v1.parquet
❌ MISSING: p2p3_up_nodes_profile_v1.parquet
❌ MISSING: p2p3_peer_getaddr_features_v1.parquet
❌ MISSING: p2p3_peer_getaddr_features_clean_v1.parquet

=== P2P-3 CLEAN FEATURE CHECK ===

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_peer_getaddr_features_clean_v1.parquet'

In [ ]:
import os

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"

print("Base exists:", os.path.exists(BASE))
print("\nContents of Bitcoin P2P Dataset:\n")

for root, dirs, files in os.walk(BASE):
    level = root.replace(BASE, "").count(os.sep)

    if level > 2:
        continue

    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

    for f in files[:20]:
        print(f"{indent}  {f}")

print("\nSearching specifically for our P2P artifacts...\n")

targets = [
    "p2p_peer_features_v2_temporal.parquet",
    "p2p_ml_matrix_v2.parquet",
    "p2p_isolation_forest_v1_scores.parquet",
    "p2p_isolation_forest_v1_explanations.parquet",
    "p2p_anomaly_population_summary.parquet",
    "p2p3_getaddr_profile_v1.parquet",
    "p2p3_up_nodes_profile_v1.parquet",
    "p2p3_peer_getaddr_features_v1.parquet",
    "p2p3_peer_getaddr_features_clean_v1.parquet",
]

found = []

for root, dirs, files in os.walk(BASE):
    for target in targets:
        if target in files:
            path = os.path.join(root, target)
            found.append(path)

for path in found:
    print("✅", path)

print("\nFound:", len(found), "/", len(targets))

Base exists: False

Contents of Bitcoin P2P Dataset:


Searching specifically for our P2P artifacts...


Found: 0 / 9

In [ ]:
import os

DRIVE_ROOT = "/content/drive/MyDrive"

print("MyDrive exists:", os.path.exists(DRIVE_ROOT))

if os.path.exists(DRIVE_ROOT):
    print("\nTop-level MyDrive contents:\n")

    for item in sorted(os.listdir(DRIVE_ROOT)):
        path = os.path.join(DRIVE_ROOT, item)

        if os.path.isdir(path):
            print("[DIR] ", item)
        else:
            print("[FILE]", item)

MyDrive exists: False

In [ ]:
from google.colab import drive
import os

drive.mount(
    "/content/drive",
    force_remount=True
)

print("\n=== DRIVE CHECK ===")

print(
    "Drive exists:",
    os.path.exists("/content/drive")
)

print(
    "MyDrive exists:",
    os.path.exists("/content/drive/MyDrive")
)

if os.path.exists("/content/drive/MyDrive"):
    print("\nMyDrive contents:")

    for item in sorted(
        os.listdir("/content/drive/MyDrive")
    ):
        print(item)

Mounted at /content/drive

=== DRIVE CHECK ===
Drive exists: True
MyDrive exists: True

MyDrive contents:
Bitcoin P2P Dataset
Colab Notebooks
Copy of DSA patterns Cheat Sheet.gsheet
Dataset
FINAL _Flood_Monitoring_System_Research_Paper.docx
IMG-20260213-WA0037.jpg
IMG-20260213-WA0038.jpg
IMG-20260213-WA0040.jpg
IMG-20260306-WA0003.jpg
IMG_20260117_203710.jpg
JARVIS
Maanya-Saxena_Resume (2) (1).pdf
Maanya-Saxena_Resume (2) (2).pdf
Maanya-Saxena_Resume (2).pdf
Maanya-Saxena_Resume-1 (1).pdf
Maanya-Saxena_Resume-1.pdf
Maanya-Saxena_Resume.pdf
Video
deepfake_detector_v1.pth
fee for reserch paper.jpeg
maanya resume.pdf
maanya saxena cs1 2027.pdf
maanya saxena id.jpeg
resume[1][1] (1).pdf
resume[1][1].docx
resume[1][1].pdf

In [ ]:
import os

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"
PROCESSED_DIR = os.path.join(BASE, "processed")

print("Dataset folder exists:", os.path.exists(BASE))
print("Processed folder exists:", os.path.exists(PROCESSED_DIR))

if os.path.exists(PROCESSED_DIR):

    print("\nProcessed artifacts:\n")

    for f in sorted(os.listdir(PROCESSED_DIR)):
        print(f)

else:
    print("\n❌ Processed folder not found.")

    print("\nDataset folder contents:")
    for item in os.listdir(BASE):
        print(item)

Dataset folder exists: True
Processed folder exists: True

Processed artifacts:

metadata
node_observation_frequency.parquet
observations
p2p3_getaddr_profile_v1.parquet
p2p3_peer_getaddr_features_clean_v1.parquet
p2p3_peer_getaddr_features_v1.parquet
p2p3_up_nodes_profile_v1.parquet
p2p_anomaly_population_summary.parquet
p2p_isolation_forest_v1_explanations.parquet
p2p_isolation_forest_v1_scores.parquet
p2p_ml_matrix_v2.parquet
p2p_observations_20200215.parquet
p2p_peer_burst_features_v1.parquet
p2p_peer_features_p2p1_clean.parquet
p2p_peer_features_v1.parquet
p2p_peer_features_v2_temporal.parquet
p2p_peer_features_v3_p2p3.parquet
p2p_peer_intervals_v1.parquet
p2p_peer_temporal_basic_v1.parquet
p2p_peer_temporal_features_v1.parquet
tmp_p2p_peer_features_v1.parquet

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
)

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_getaddr_profile_v1.parquet"
)

UPNODES_PATH = (
    f"{PROCESSED_DIR}/p2p3_up_nodes_profile_v1.parquet"
)

getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

print("=== P2P-3 SNAPSHOT-LEVEL DATA ===")

print("\ngetADDR shape:", getaddr.shape)
print("up-nodes shape:", upnodes.shape)

print("\ngetADDR columns:")
print(getaddr.columns.tolist())

print("\nup-nodes columns:")
print(upnodes.columns.tolist())

print("\n=== getADDR SUMMARY ===")
display(getaddr.describe().T)

print("\n=== UP-NODES SUMMARY ===")
display(upnodes.describe().T)

print("\n=== GETADDR MISSING VALUES ===")
print(getaddr.isna().sum())

print("\n=== UPNODES MISSING VALUES ===")
print(upnodes.isna().sum())

=== P2P-3 SNAPSHOT-LEVEL DATA ===

getADDR shape: (9481, 12)
up-nodes shape: (9481, 9)

getADDR columns:
['file', 'timestamp', 'peer_rows', 'min_numeric_fields', 'max_numeric_fields', 'mean_numeric_fields', 'total_numeric_values', 'valid_numeric_values', 'missing_numeric_values', 'mean_valid_value', 'median_valid_value', 'max_valid_value']

up-nodes columns:
['file', 'timestamp', 'time_points', 'duration_seconds', 'mean_up_nodes', 'median_up_nodes', 'max_up_nodes', 'min_up_nodes', 'std_up_nodes']

=== getADDR SUMMARY ===

,count,mean,std,min,25%,50%,75%,max
peer_rows,9481.0,7184.939036,281.197787,5506.000000,7192.000000,7308.000000,7347.000000,7623.000000
min_numeric_fields,9481.0,3.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000
max_numeric_fields,9481.0,6.795908,0.491927,6.000000,7.000000,7.000000,7.000000,10.000000
mean_numeric_fields,9481.0,3.423735,0.038127,3.319835,3.405641,3.418320,3.433952,3.855323
total_numeric_values,9481.0,24594.276764,875.174040,18434.000000,24574.000000,24944.000000,25125.000000,25954.000000
valid_numeric_values,9481.0,9362.099673,484.935385,6374.000000,9083.000000,9333.000000,9618.000000,13749.000000
missing_numeric_values,9481.0,15232.177091,965.868241,10556.000000,14810.000000,15620.000000,15906.000000,16826.000000
mean_valid_value,9481.0,111.339469,90.631902,81.817194,96.479992,100.746898,105.908796,913.586907
median_valid_value,9481.0,109.264529,100.140930,80.000000,93.000000,97.000000,103.000000,988.000000
max_valid_value,9481.0,1073.754773,272.574674,770.000000,940.000000,954.000000,1090.000000,2509.000000

=== UP-NODES SUMMARY ===

,count,mean,std,min,25%,50%,75%,max
time_points,9481.0,31.418627,12.722523,22.000000,28.000000,30.000000,32.000000,169.000000
duration_seconds,9481.0,152.093134,63.612617,105.000000,135.000000,145.000000,155.000000,840.000000
mean_up_nodes,9481.0,238.809076,41.113054,0.000000,225.500000,243.166667,261.428571,336.545455
median_up_nodes,9481.0,203.695285,38.842018,26.000000,180.500000,203.500000,227.500000,360.500000
max_up_nodes,9481.0,965.936399,262.806707,157.000000,749.000000,946.000000,1171.000000,1654.000000
min_up_nodes,9481.0,-101.749183,808.331192,-7468.000000,0.000000,0.000000,0.000000,8.000000
std_up_nodes,9481.0,222.326639,79.042456,112.094391,187.710141,213.166993,242.390337,1531.890490

=== GETADDR MISSING VALUES ===
file                      0
timestamp                 0
peer_rows                 0
min_numeric_fields        0
max_numeric_fields        0
mean_numeric_fields       0
total_numeric_values      0
valid_numeric_values      0
missing_numeric_values    0
mean_valid_value          0
median_valid_value        0
max_valid_value           0
dtype: int64

=== UPNODES MISSING VALUES ===
file                0
timestamp           0
time_points         0
duration_seconds    0
mean_up_nodes       0
median_up_nodes     0
max_up_nodes        0
min_up_nodes        0
std_up_nodes        0
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
)

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_getaddr_profile_v1.parquet"
)

UPNODES_PATH = (
    f"{PROCESSED_DIR}/p2p3_up_nodes_profile_v1.parquet"
)

OUTPUT_PATH = (
    f"{PROCESSED_DIR}/p2p3_snapshot_features_v1.parquet"
)

# ---------------------------------------------------------
# Load
# ---------------------------------------------------------

getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

# ---------------------------------------------------------
# Merge snapshot-level data
# ---------------------------------------------------------

df = getaddr.merge(
    upnodes,
    on=["file", "timestamp"],
    how="inner",
    validate="one_to_one"
)

print("Merged snapshot shape:", df.shape)

# ---------------------------------------------------------
# Derived getADDR features
# ---------------------------------------------------------

df["getaddr_valid_ratio"] = np.where(
    df["total_numeric_values"] > 0,
    df["valid_numeric_values"]
    / df["total_numeric_values"],
    0.0
)

df["getaddr_missing_ratio"] = np.where(
    df["total_numeric_values"] > 0,
    df["missing_numeric_values"]
    / df["total_numeric_values"],
    0.0
)

df["getaddr_values_per_peer"] = np.where(
    df["peer_rows"] > 0,
    df["total_numeric_values"]
    / df["peer_rows"],
    0.0
)

# ---------------------------------------------------------
# Derived up-node features
# ---------------------------------------------------------

df["up_nodes_range"] = (
    df["max_up_nodes"]
    -
    df["median_up_nodes"]
)

df["up_nodes_variability_ratio"] = np.where(
    df["mean_up_nodes"] > 0,
    df["std_up_nodes"]
    / df["mean_up_nodes"],
    0.0
)

# min_up_nodes contains extreme negative values.
# Preserve the raw column for auditing but create a
# non-negative bounded version for ML use.

df["min_up_nodes_clipped"] = (
    df["min_up_nodes"]
    .clip(lower=0)
)

# ---------------------------------------------------------
# Validation
# ---------------------------------------------------------

print("\nFeature shape:", df.shape)

print("\nMissing values:")
print(
    df.isna().sum()
    .sort_values(ascending=False)
    .head(20)
)

print("\nDuplicate snapshots:")

print(
    df.duplicated(
        subset=["file", "timestamp"]
    ).sum()
)

print("\nDerived feature summary:")

derived_cols = [
    "getaddr_valid_ratio",
    "getaddr_missing_ratio",
    "getaddr_values_per_peer",
    "up_nodes_range",
    "up_nodes_variability_ratio",
    "min_up_nodes_clipped"
]

display(
    df[derived_cols].describe().T
)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------

df.to_parquet(
    OUTPUT_PATH,
    index=False
)

print("\n✅ Step 69 complete")
print("Saved:", OUTPUT_PATH)

Merged snapshot shape: (0, 19)

Feature shape: (0, 25)

Missing values:
file                      0
timestamp                 0
peer_rows                 0
min_numeric_fields        0
max_numeric_fields        0
mean_numeric_fields       0
total_numeric_values      0
valid_numeric_values      0
missing_numeric_values    0
mean_valid_value          0
median_valid_value        0
max_valid_value           0
time_points               0
duration_seconds          0
mean_up_nodes             0
median_up_nodes           0
max_up_nodes              0
min_up_nodes              0
std_up_nodes              0
getaddr_valid_ratio       0
dtype: int64

Duplicate snapshots:
0

Derived feature summary:

                            count  mean  std  min  25%  50%  75%  max
getaddr_valid_ratio           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
getaddr_missing_ratio         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
getaddr_values_per_peer       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
up_nodes_range                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
up_nodes_variability_ratio    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
min_up_nodes_clipped          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

✅ Step 69 complete
Saved: /content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_snapshot_features_v1.parquet

In [ ]:
import pandas as pd

PROCESSED_DIR = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"
)

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_getaddr_profile_v1.parquet"
)

UPNODES_PATH = (
    f"{PROCESSED_DIR}/p2p3_up_nodes_profile_v1.parquet"
)

getaddr = pd.read_parquet(
    GETADDR_PATH,
    columns=["file", "timestamp"]
)

upnodes = pd.read_parquet(
    UPNODES_PATH,
    columns=["file", "timestamp"]
)

print("=== GETADDR ===")
print(getaddr.head(10).to_string(index=False))

print("\n=== UPNODES ===")
print(upnodes.head(10).to_string(index=False))

print("\n=== DTYPES ===")
print("getADDR:")
print(getaddr.dtypes)

print("\nup-nodes:")
print(upnodes.dtypes)

print("\n=== EXACT OVERLAP ===")

getaddr_keys = set(
    zip(
        getaddr["file"].astype(str),
        getaddr["timestamp"].astype(str)
    )
)

upnodes_keys = set(
    zip(
        upnodes["file"].astype(str),
        upnodes["timestamp"].astype(str)
    )
)

print("getADDR keys:", len(getaddr_keys))
print("up-node keys:", len(upnodes_keys))
print("matching keys:", len(getaddr_keys & upnodes_keys))

print("\n=== FILE OVERLAP ONLY ===")

getaddr_files = set(
    getaddr["file"].astype(str)
)

upnodes_files = set(
    upnodes["file"].astype(str)
)

print("getADDR files:", len(getaddr_files))
print("up-node files:", len(upnodes_files))
print("matching files:", len(getaddr_files & upnodes_files))

print("\nSample getADDR file:")
print(next(iter(getaddr_files)))

print("\nSample up-node file:")
print(next(iter(upnodes_files)))

=== GETADDR ===
                                                               file         timestamp
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:31:10.csv 20200215-00:31:10
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:06:30.csv 20200215-08:06:30
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-01:11:30.csv 20200215-01:11:30
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-08:02:30.csv 20200215-08:02:30
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-12:43:00.csv 20200215-12:43:00
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-00:23:21.csv 20200215-00:23:21
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-05:02:30.csv 20200215-05:02:30
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-17:34:40.csv 20200215-17:34:40
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-07:46:40.csv 20200215-07:46:40
dataset_2020/crawl/20200215/nodes_per_getADDR_20200215-02:26:50.csv 20200215-02:26:50

=== UPNODES ===
                                                                  file         timestamp
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:43:21.csv 20200215-10:43:21
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-15:14:50.csv 20200215-15:14:50
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:23:00.csv 20200215-10:23:00
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-09:50:50.csv 20200215-09:50:50
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-14:50:50.csv 20200215-14:50:50
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-18:22:40.csv 20200215-18:22:40
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-02:03:00.csv 20200215-02:03:00
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-20:14:50.csv 20200215-20:14:50
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-17:14:40.csv 20200215-17:14:40
dataset_2020/crawl/20200215/up_nodes_per_seconds_20200215-10:11:00.csv 20200215-10:11:00

=== DTYPES ===
getADDR:
file         object
timestamp    object
dtype: object

up-nodes:
file         object
timestamp    object
dtype: object

=== EXACT OVERLAP ===
getADDR keys: 9481
up-node keys: 9481
matching keys: 0

=== FILE OVERLAP ONLY ===
getADDR files: 9481
up-node files: 9481
matching files: 0

Sample getADDR file:
dataset_2020/crawl/20200228/nodes_per_getADDR_20200228-02:18:55.csv

Sample up-node file:
dataset_2020/crawl/20200301/up_nodes_per_seconds_20200301-04:42:05.csv

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

GETADDR_PATH = f"{PROCESSED_DIR}/p2p3_getaddr_profile_v1.parquet"
UPNODES_PATH = f"{PROCESSED_DIR}/p2p3_up_nodes_profile_v1.parquet"

# Load snapshot profiles
getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

# Parse timestamps
getaddr["timestamp"] = pd.to_datetime(getaddr["timestamp"])
upnodes["timestamp"] = pd.to_datetime(upnodes["timestamp"])

# Add date/hour
for df in [getaddr, upnodes]:
    df["date"] = df["timestamp"].dt.date
    df["hour"] = df["timestamp"].dt.hour

# ---------------------------------------------------------
# GETADDR DAILY FEATURES
# ---------------------------------------------------------
getaddr_daily = (
    getaddr
    .groupby("date")
    .agg(
        getaddr_snapshots=("timestamp", "count"),
        getaddr_peer_rows_mean=("peer_rows", "mean"),
        getaddr_peer_rows_std=("peer_rows", "std"),
        getaddr_peer_rows_min=("peer_rows", "min"),
        getaddr_peer_rows_max=("peer_rows", "max"),
        getaddr_valid_values_mean=("valid_numeric_values", "mean"),
        getaddr_missing_values_mean=("missing_numeric_values", "mean"),
        getaddr_missing_ratio_mean=(
            "missing_numeric_values",
            lambda x: np.nan
        ),
        getaddr_mean_value_mean=("mean_valid_value", "mean"),
        getaddr_max_value_max=("max_valid_value", "max"),
    )
    .reset_index()
)

# Calculate missing ratio correctly from totals
daily_missing = (
    getaddr
    .groupby("date")
    .agg(
        total_numeric_values=("total_numeric_values", "sum"),
        total_missing_values=("missing_numeric_values", "sum"),
    )
    .reset_index()
)

getaddr_daily = getaddr_daily.drop(
    columns=["getaddr_missing_ratio_mean"]
)

getaddr_daily = getaddr_daily.merge(
    daily_missing,
    on="date",
    how="left"
)

getaddr_daily["getaddr_missing_ratio"] = np.where(
    getaddr_daily["total_numeric_values"] > 0,
    getaddr_daily["total_missing_values"] /
    getaddr_daily["total_numeric_values"],
    0
)

# ---------------------------------------------------------
# UP-NODES DAILY FEATURES
# ---------------------------------------------------------
upnodes_daily = (
    upnodes
    .groupby("date")
    .agg(
        upnodes_snapshots=("timestamp", "count"),
        upnodes_mean_mean=("mean_up_nodes", "mean"),
        upnodes_mean_std=("mean_up_nodes", "std"),
        upnodes_mean_min=("mean_up_nodes", "min"),
        upnodes_mean_max=("mean_up_nodes", "max"),
        upnodes_max_mean=("max_up_nodes", "mean"),
        upnodes_max_max=("max_up_nodes", "max"),
        upnodes_std_mean=("std_up_nodes", "mean"),
        upnodes_std_max=("std_up_nodes", "max"),
    )
    .reset_index()
)

# ---------------------------------------------------------
# SAVE INDEPENDENT DAILY FEATURES
# ---------------------------------------------------------
getaddr_daily_path = (
    f"{PROCESSED_DIR}/p2p3_getaddr_daily_features_v1.parquet"
)

upnodes_daily_path = (
    f"{PROCESSED_DIR}/p2p3_upnodes_daily_features_v1.parquet"
)

getaddr_daily.to_parquet(
    getaddr_daily_path,
    index=False
)

upnodes_daily.to_parquet(
    upnodes_daily_path,
    index=False
)

print("=== GETADDR DAILY ===")
print("Shape:", getaddr_daily.shape)
print(getaddr_daily.head().to_string(index=False))

print("\n=== UP-NODES DAILY ===")
print("Shape:", upnodes_daily.shape)
print(upnodes_daily.head().to_string(index=False))

print("\nSaved:")
print(getaddr_daily_path)
print(upnodes_daily_path)

=== GETADDR DAILY ===
Shape: (27, 13)
      date  getaddr_snapshots  getaddr_peer_rows_mean  getaddr_peer_rows_std  getaddr_peer_rows_min  getaddr_peer_rows_max  getaddr_valid_values_mean  getaddr_missing_values_mean  getaddr_mean_value_mean  getaddr_max_value_max  total_numeric_values  total_missing_values  getaddr_missing_ratio
2020-02-07                360             7315.002778              99.629886                   6405                   7527                9252.027778                 15592.894444                99.244206                 1030.0               8944172               5613442               0.627609
2020-02-08                360             7323.250000              71.671012                   6641                   7429                9196.358333                 15706.330556                98.142292                 1098.0               8964968               5654279               0.630708
2020-02-09                360             7352.538889              48.460116                   7261                   7623                9339.191667                 15662.058333                96.917793                 1073.0               9000450               5638341               0.626451
2020-02-10                360             7379.672222              47.281923                   7202                   7597                9396.058333                 15703.033333               102.591638                 1073.0               9035673               5653092               0.625641
2020-02-11                360             7330.508333             150.701147                   5506                   7454                9360.105556                 15669.152778               100.306057                 1047.0               9010533               5640895               0.626033

=== UP-NODES DAILY ===
Shape: (27, 10)
      date  upnodes_snapshots  upnodes_mean_mean  upnodes_mean_std  upnodes_mean_min  upnodes_mean_max  upnodes_max_mean  upnodes_max_max  upnodes_std_mean  upnodes_std_max
2020-02-07                360         241.079124         33.006083          0.000000        330.863636        954.744444           1557.0        216.022286      1518.548965
2020-02-08                360         253.923170         37.712019          0.000000        336.545455        993.844444           1574.0        228.198306      1531.890490
2020-02-09                360         250.309106         30.755639          0.032258        307.583333       1019.411111           1654.0        227.007980      1377.634848
2020-02-10                360         239.943585         20.354201        202.861111        307.208333        984.408333           1648.0        211.382425       337.922482
2020-02-11                360         240.921144         48.147885          0.000000        308.541667       1011.708333           1603.0        249.984245      1358.852872

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_getaddr_daily_features_v1.parquet
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_upnodes_daily_features_v1.parquet

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

GETADDR_PATH = f"{PROCESSED_DIR}/p2p3_getaddr_daily_features_v1.parquet"
UPNODES_PATH = f"{PROCESSED_DIR}/p2p3_upnodes_daily_features_v1.parquet"

getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

# ---------------------------------------------------------
# GETADDR TEMPORAL FEATURES
# ---------------------------------------------------------
getaddr = getaddr.sort_values("date").reset_index(drop=True)

getaddr["getaddr_snapshot_rate"] = (
    getaddr["getaddr_snapshots"] /
    getaddr["getaddr_snapshots"].median()
)

getaddr["getaddr_peer_row_change"] = (
    getaddr["getaddr_peer_rows_mean"].diff()
)

getaddr["getaddr_peer_row_change_pct"] = (
    getaddr["getaddr_peer_rows_mean"].pct_change()
)

getaddr["getaddr_valid_value_change"] = (
    getaddr["getaddr_valid_values_mean"].diff()
)

getaddr["getaddr_missing_ratio_change"] = (
    getaddr["getaddr_missing_ratio"].diff()
)

# Robust z-score using median/MAD
def robust_z(series):
    median = series.median()
    mad = np.median(np.abs(series - median))

    if mad == 0:
        return pd.Series(np.zeros(len(series)), index=series.index)

    return 0.6745 * (series - median) / mad

getaddr["getaddr_peer_row_robust_z"] = robust_z(
    getaddr["getaddr_peer_rows_mean"]
)

getaddr["getaddr_missing_ratio_robust_z"] = robust_z(
    getaddr["getaddr_missing_ratio"]
)

# ---------------------------------------------------------
# UP-NODES TEMPORAL FEATURES
# ---------------------------------------------------------
upnodes = upnodes.sort_values("date").reset_index(drop=True)

upnodes["upnodes_mean_change"] = (
    upnodes["upnodes_mean_mean"].diff()
)

upnodes["upnodes_mean_change_pct"] = (
    upnodes["upnodes_mean_mean"].pct_change()
)

upnodes["upnodes_max_change"] = (
    upnodes["upnodes_max_mean"].diff()
)

upnodes["upnodes_std_change"] = (
    upnodes["upnodes_std_mean"].diff()
)

upnodes["upnodes_mean_robust_z"] = robust_z(
    upnodes["upnodes_mean_mean"]
)

upnodes["upnodes_max_robust_z"] = robust_z(
    upnodes["upnodes_max_mean"]
)

upnodes["upnodes_variability_ratio"] = np.where(
    upnodes["upnodes_mean_mean"] > 0,
    upnodes["upnodes_mean_std"] /
    upnodes["upnodes_mean_mean"],
    0
)

# ---------------------------------------------------------
# SAVE
# ---------------------------------------------------------
GETADDR_OUT = (
    f"{PROCESSED_DIR}/p2p3_getaddr_temporal_features_v1.parquet"
)

UPNODES_OUT = (
    f"{PROCESSED_DIR}/p2p3_upnodes_temporal_features_v1.parquet"
)

getaddr.to_parquet(GETADDR_OUT, index=False)
upnodes.to_parquet(UPNODES_OUT, index=False)

print("=== GETADDR TEMPORAL ===")
print("Shape:", getaddr.shape)
print(
    getaddr[
        [
            "date",
            "getaddr_peer_rows_mean",
            "getaddr_peer_row_change",
            "getaddr_peer_row_change_pct",
            "getaddr_peer_row_robust_z",
            "getaddr_missing_ratio",
            "getaddr_missing_ratio_robust_z"
        ]
    ].head(10).to_string(index=False)
)

print("\n=== UP-NODES TEMPORAL ===")
print("Shape:", upnodes.shape)
print(
    upnodes[
        [
            "date",
            "upnodes_mean_mean",
            "upnodes_mean_change",
            "upnodes_mean_change_pct",
            "upnodes_max_change",
            "upnodes_mean_robust_z",
            "upnodes_variability_ratio"
        ]
    ].head(10).to_string(index=False)
)

print("\nSaved:")
print(GETADDR_OUT)
print(UPNODES_OUT)

=== GETADDR TEMPORAL ===
Shape: (27, 20)
      date  getaddr_peer_rows_mean  getaddr_peer_row_change  getaddr_peer_row_change_pct  getaddr_peer_row_robust_z  getaddr_missing_ratio  getaddr_missing_ratio_robust_z
2020-02-07             7315.002778                      NaN                          NaN                   0.000000               0.627609                        0.302141
2020-02-08             7323.250000                 8.247222                     0.001127                   0.205183               0.630708                        0.778113
2020-02-09             7352.538889                29.288889                     0.003999                   0.933865               0.626451                        0.124319
2020-02-10             7379.672222                27.133333                     0.003690                   1.608917               0.625641                        0.000000
2020-02-11             7330.508333               -49.163889                    -0.006662                   0.385764               0.626033                        0.060192
2020-02-12             7329.358333                -1.150000                    -0.000157                   0.357153               0.629519                        0.595407
2020-02-13             7315.825000               -13.533333                    -0.001846                   0.020456               0.626093                        0.069384
2020-02-14             7292.166667               -23.658333                    -0.003234                  -0.568142               0.621542                       -0.629585
2020-02-15             7324.355556                32.188889                     0.004414                   0.232689               0.623233                       -0.369846
2020-02-16             7313.675000               -10.680556                    -0.001458                  -0.033034               0.622465                       -0.487881

=== UP-NODES TEMPORAL ===
Shape: (27, 17)
      date  upnodes_mean_mean  upnodes_mean_change  upnodes_mean_change_pct  upnodes_max_change  upnodes_mean_robust_z  upnodes_variability_ratio
2020-02-07         241.079124                  NaN                      NaN                 NaN              -0.192453                   0.136910
2020-02-08         253.923170            12.844046                 0.053277           39.100000               1.152002                   0.148517
2020-02-09         250.309106            -3.614064                -0.014233           25.566667               0.773699                   0.122871
2020-02-10         239.943585           -10.365521                -0.041411          -35.002778              -0.311316                   0.084829
2020-02-11         240.921144             0.977560                 0.004074           27.300000              -0.208989                   0.199849
2020-02-12         244.014486             3.093342                 0.012840          -12.575000               0.114807                   0.080930
2020-02-13         256.370011            12.355525                 0.050634          -10.741667               1.408126                   0.073976
2020-02-14         240.823873           -15.546138                -0.060639          -17.905556              -0.219171                   0.140359
2020-02-15         248.073453             7.249580                 0.030103           14.641667               0.539681                   0.095249
2020-02-16         249.373720             1.300267                 0.005241           20.788889               0.675787                   0.109452

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_getaddr_temporal_features_v1.parquet
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_upnodes_temporal_features_v1.parquet

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_getaddr_temporal_features_v1.parquet"
)

UPNODES_PATH = (
    f"{PROCESSED_DIR}/p2p3_upnodes_temporal_features_v1.parquet"
)

getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

# Numeric-only matrices
getaddr_num = getaddr.select_dtypes(include=[np.number])
upnodes_num = upnodes.select_dtypes(include=[np.number])

# ---------------------------------------------------------
# BASIC QUALITY
# ---------------------------------------------------------
print("=== GETADDR QUALITY ===")
print("Shape:", getaddr.shape)
print("\nMissing values:")
print(getaddr.isna().sum()[getaddr.isna().sum() > 0])

print("\nConstant features:")
getaddr_constants = [
    c for c in getaddr_num.columns
    if getaddr_num[c].nunique(dropna=True) <= 1
]
print(getaddr_constants)

print("\nSkewed features:")
getaddr_skew = (
    getaddr_num
    .replace([np.inf, -np.inf], np.nan)
    .skew()
    .sort_values(key=lambda x: x.abs(), ascending=False)
)
print(getaddr_skew.head(15).to_string())

print("\n=== UPNODES QUALITY ===")
print("Shape:", upnodes.shape)
print("\nMissing values:")
print(upnodes.isna().sum()[upnodes.isna().sum() > 0])

print("\nConstant features:")
upnodes_constants = [
    c for c in upnodes_num.columns
    if upnodes_num[c].nunique(dropna=True) <= 1
]
print(upnodes_constants)

print("\nSkewed features:")
upnodes_skew = (
    upnodes_num
    .replace([np.inf, -np.inf], np.nan)
    .skew()
    .sort_values(key=lambda x: x.abs(), ascending=False)
)
print(upnodes_skew.head(15).to_string())

# ---------------------------------------------------------
# HIGH CORRELATIONS
# ---------------------------------------------------------
def high_correlations(df, threshold=0.90):
    numeric = (
        df.select_dtypes(include=[np.number])
        .replace([np.inf, -np.inf], np.nan)
    )

    corr = numeric.corr()

    pairs = []

    cols = corr.columns

    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            value = corr.iloc[i, j]

            if pd.notna(value) and abs(value) >= threshold:
                pairs.append(
                    (
                        cols[i],
                        cols[j],
                        round(float(value), 4)
                    )
                )

    return sorted(
        pairs,
        key=lambda x: abs(x[2]),
        reverse=True
    )

print("\n=== GETADDR HIGH CORRELATIONS >= 0.90 ===")
getaddr_corr = high_correlations(getaddr)
for row in getaddr_corr[:20]:
    print(row)

print("\n=== UPNODES HIGH CORRELATIONS >= 0.90 ===")
upnodes_corr = high_correlations(upnodes)
for row in upnodes_corr[:20]:
    print(row)

=== GETADDR QUALITY ===
Shape: (27, 20)

Missing values:
getaddr_peer_row_change         1
getaddr_peer_row_change_pct     1
getaddr_valid_value_change      1
getaddr_missing_ratio_change    1
dtype: int64

Constant features:
[]

Skewed features:
getaddr_snapshots                -5.196152
getaddr_snapshot_rate            -5.196152
getaddr_mean_value_mean           5.193962
total_numeric_values             -4.706482
total_missing_values             -4.104738
getaddr_peer_row_change_pct      -2.684028
getaddr_peer_rows_std             2.581159
getaddr_peer_row_change          -2.575192
getaddr_peer_rows_mean           -1.805068
getaddr_peer_row_robust_z        -1.805068
getaddr_peer_rows_max            -1.717746
getaddr_missing_ratio            -1.502330
getaddr_missing_ratio_robust_z   -1.502330
getaddr_valid_value_change        1.498138
getaddr_missing_values_mean      -1.275254

=== UPNODES QUALITY ===
Shape: (27, 17)

Missing values:
upnodes_mean_change        1
upnodes_mean_change_pct    1
upnodes_max_change         1
upnodes_std_change         1
dtype: int64

Constant features:
[]

Skewed features:
upnodes_snapshots           -5.196152
upnodes_variability_ratio    5.161330
upnodes_std_mean             4.695511
upnodes_std_change           4.646542
upnodes_mean_robust_z       -4.532493
upnodes_mean_mean           -4.532493
upnodes_mean_change_pct     -4.438186
upnodes_max_robust_z        -4.226909
upnodes_max_mean            -4.226909
upnodes_mean_max            -4.200401
upnodes_mean_change         -4.041188
upnodes_max_max             -3.484152
upnodes_max_change          -3.319468
upnodes_mean_std            -0.193398
upnodes_mean_min             0.128718

=== GETADDR HIGH CORRELATIONS >= 0.90 ===
('getaddr_snapshots', 'getaddr_snapshot_rate', 1.0)
('getaddr_peer_rows_mean', 'getaddr_peer_row_robust_z', 1.0)
('getaddr_missing_ratio', 'getaddr_missing_ratio_robust_z', 1.0)
('getaddr_snapshots', 'getaddr_mean_value_mean', -0.9999)
('getaddr_mean_value_mean', 'getaddr_snapshot_rate', -0.9999)
('getaddr_peer_row_change', 'getaddr_peer_row_change_pct', 0.9994)
('getaddr_peer_rows_mean', 'getaddr_peer_rows_max', 0.9895)
('getaddr_peer_rows_max', 'getaddr_peer_row_robust_z', 0.9895)
('total_numeric_values', 'total_missing_values', 0.9854)
('getaddr_mean_value_mean', 'total_numeric_values', -0.969)
('getaddr_snapshots', 'total_numeric_values', 0.968)
('total_numeric_values', 'getaddr_snapshot_rate', 0.968)
('getaddr_valid_value_change', 'getaddr_missing_ratio_change', -0.9517)
('getaddr_peer_rows_mean', 'getaddr_missing_values_mean', 0.9369)
('getaddr_missing_values_mean', 'getaddr_peer_row_robust_z', 0.9369)
('getaddr_mean_value_mean', 'total_missing_values', -0.9251)
('getaddr_snapshots', 'total_missing_values', 0.9245)
('total_missing_values', 'getaddr_snapshot_rate', 0.9245)
('getaddr_missing_values_mean', 'getaddr_missing_ratio', 0.9215)
('getaddr_missing_values_mean', 'getaddr_missing_ratio_robust_z', 0.9215)

=== UPNODES HIGH CORRELATIONS >= 0.90 ===
('upnodes_mean_mean', 'upnodes_mean_robust_z', 1.0)
('upnodes_max_mean', 'upnodes_max_robust_z', 1.0)
('upnodes_snapshots', 'upnodes_variability_ratio', -0.9979)
('upnodes_mean_change', 'upnodes_mean_change_pct', 0.9956)
('upnodes_std_mean', 'upnodes_std_change', 0.9914)
('upnodes_mean_mean', 'upnodes_mean_change_pct', 0.9846)
('upnodes_mean_change_pct', 'upnodes_mean_robust_z', 0.9846)
('upnodes_mean_mean', 'upnodes_max_mean', 0.9813)
('upnodes_mean_mean', 'upnodes_max_robust_z', 0.9813)
('upnodes_max_mean', 'upnodes_mean_robust_z', 0.9813)
('upnodes_mean_robust_z', 'upnodes_max_robust_z', 0.9813)
('upnodes_std_change', 'upnodes_variability_ratio', 0.9795)
('upnodes_std_mean', 'upnodes_variability_ratio', 0.9769)
('upnodes_max_mean', 'upnodes_mean_change_pct', 0.9749)
('upnodes_mean_change_pct', 'upnodes_max_robust_z', 0.9749)
('upnodes_mean_mean', 'upnodes_mean_change', 0.9748)
('upnodes_mean_change', 'upnodes_mean_robust_z', 0.9748)
('upnodes_mean_mean', 'upnodes_mean_max', 0.9736)
('upnodes_mean_max', 'upnodes_mean_robust_z', 0.9736)
('upnodes_snapshots', 'upnodes_std_change', -0.9727)

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_getaddr_temporal_features_v1.parquet"
)

UPNODES_PATH = (
    f"{PROCESSED_DIR}/p2p3_upnodes_temporal_features_v1.parquet"
)

getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

# =========================================================
# GETADDR COMPACT FEATURES
# =========================================================

getaddr_clean = getaddr[
    [
        "date",
        "getaddr_snapshots",
        "getaddr_peer_rows_mean",
        "getaddr_peer_rows_std",
        "getaddr_peer_rows_min",
        "getaddr_peer_rows_max",
        "getaddr_valid_values_mean",
        "getaddr_missing_values_mean",
        "getaddr_mean_value_mean",
        "getaddr_max_value_max",
        "getaddr_missing_ratio",
        "getaddr_peer_row_change_pct",
        "getaddr_valid_value_change",
        "getaddr_missing_ratio_change",
    ]
].copy()

# =========================================================
# UP-NODES COMPACT FEATURES
# =========================================================

upnodes_clean = upnodes[
    [
        "date",
        "upnodes_snapshots",
        "upnodes_mean_mean",
        "upnodes_mean_std",
        "upnodes_mean_min",
        "upnodes_mean_max",
        "upnodes_max_mean",
        "upnodes_std_mean",
        "upnodes_std_max",
        "upnodes_mean_change_pct",
        "upnodes_max_change",
        "upnodes_std_change",
    ]
].copy()

# =========================================================
# CLEAN NUMERIC NaN / INF
# =========================================================

for df in [getaddr_clean, upnodes_clean]:
    numeric_cols = df.select_dtypes(include=[np.number]).columns

    df[numeric_cols] = (
        df[numeric_cols]
        .replace([np.inf, -np.inf], np.nan)
    )

    # First-day change features have no previous day.
    # Use 0 because there is no observed change available.
    change_cols = [
        c for c in numeric_cols
        if "change" in c
    ]

    df[change_cols] = df[change_cols].fillna(0)

# =========================================================
# SAVE
# =========================================================

GETADDR_OUT = (
    f"{PROCESSED_DIR}/p2p3_getaddr_features_clean_v1.parquet"
)

UPNODES_OUT = (
    f"{PROCESSED_DIR}/p2p3_upnodes_features_clean_v1.parquet"
)

getaddr_clean.to_parquet(
    GETADDR_OUT,
    index=False
)

upnodes_clean.to_parquet(
    UPNODES_OUT,
    index=False
)

print("=== CLEAN GETADDR ===")
print("Shape:", getaddr_clean.shape)
print("Columns:")
for c in getaddr_clean.columns:
    print(" -", c)

print("\nMissing values:")
print(
    getaddr_clean.isna().sum()[
        getaddr_clean.isna().sum() > 0
    ]
)

print("\n=== CLEAN UP-NODES ===")
print("Shape:", upnodes_clean.shape)
print("Columns:")
for c in upnodes_clean.columns:
    print(" -", c)

print("\nMissing values:")
print(
    upnodes_clean.isna().sum()[
        upnodes_clean.isna().sum() > 0
    ]
)

print("\nSaved:")
print(GETADDR_OUT)
print(UPNODES_OUT)

=== CLEAN GETADDR ===
Shape: (27, 14)
Columns:
 - date
 - getaddr_snapshots
 - getaddr_peer_rows_mean
 - getaddr_peer_rows_std
 - getaddr_peer_rows_min
 - getaddr_peer_rows_max
 - getaddr_valid_values_mean
 - getaddr_missing_values_mean
 - getaddr_mean_value_mean
 - getaddr_max_value_max
 - getaddr_missing_ratio
 - getaddr_peer_row_change_pct
 - getaddr_valid_value_change
 - getaddr_missing_ratio_change

Missing values:
Series([], dtype: int64)

=== CLEAN UP-NODES ===
Shape: (27, 12)
Columns:
 - date
 - upnodes_snapshots
 - upnodes_mean_mean
 - upnodes_mean_std
 - upnodes_mean_min
 - upnodes_mean_max
 - upnodes_max_mean
 - upnodes_std_mean
 - upnodes_std_max
 - upnodes_mean_change_pct
 - upnodes_max_change
 - upnodes_std_change

Missing values:
Series([], dtype: int64)

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_getaddr_features_clean_v1.parquet
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_upnodes_features_clean_v1.parquet

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_getaddr_features_clean_v1.parquet"
)

UPNODES_PATH = (
    f"{PROCESSED_DIR}/p2p3_upnodes_features_clean_v1.parquet"
)

getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

# ---------------------------------------------------------
# Robust z-score
# ---------------------------------------------------------
def robust_z(series):
    median = series.median()
    mad = np.median(np.abs(series - median))

    if mad == 0:
        return pd.Series(
            np.zeros(len(series)),
            index=series.index
        )

    return 0.6745 * (series - median) / mad


# ---------------------------------------------------------
# Features suitable for temporal screening
# ---------------------------------------------------------
getaddr_features = [
    "getaddr_peer_rows_mean",
    "getaddr_peer_rows_std",
    "getaddr_valid_values_mean",
    "getaddr_missing_ratio",
    "getaddr_peer_row_change_pct",
    "getaddr_valid_value_change",
]

upnodes_features = [
    "upnodes_mean_mean",
    "upnodes_mean_std",
    "upnodes_max_mean",
    "upnodes_std_mean",
    "upnodes_mean_change_pct",
    "upnodes_max_change",
    "upnodes_std_change",
]

# ---------------------------------------------------------
# Calculate robust z-scores
# ---------------------------------------------------------
for col in getaddr_features:
    getaddr[f"rz_{col}"] = robust_z(getaddr[col])

for col in upnodes_features:
    upnodes[f"rz_{col}"] = robust_z(upnodes[col])

getaddr_rz_cols = [
    f"rz_{c}" for c in getaddr_features
]

upnodes_rz_cols = [
    f"rz_{c}" for c in upnodes_features
]

# ---------------------------------------------------------
# Count extreme deviations
# Threshold = |robust z| >= 3
# ---------------------------------------------------------
getaddr["extreme_feature_count"] = (
    getaddr[getaddr_rz_cols].abs() >= 3
).sum(axis=1)

upnodes["extreme_feature_count"] = (
    upnodes[upnodes_rz_cols].abs() >= 3
).sum(axis=1)

# Maximum absolute deviation
getaddr["max_abs_robust_z"] = (
    getaddr[getaddr_rz_cols].abs().max(axis=1)
)

upnodes["max_abs_robust_z"] = (
    upnodes[upnodes_rz_cols].abs().max(axis=1)
)

# ---------------------------------------------------------
# Sort unusual historical days
# ---------------------------------------------------------
getaddr_top = getaddr.sort_values(
    ["extreme_feature_count", "max_abs_robust_z"],
    ascending=False
)

upnodes_top = upnodes.sort_values(
    ["extreme_feature_count", "max_abs_robust_z"],
    ascending=False
)

print("=== GETADDR TEMPORAL SCREENING ===")
print(
    getaddr_top[
        [
            "date",
            "extreme_feature_count",
            "max_abs_robust_z",
            "getaddr_peer_rows_mean",
            "getaddr_peer_rows_std",
            "getaddr_missing_ratio",
            "getaddr_peer_row_change_pct"
        ]
    ].head(10).to_string(index=False)
)

print("\n=== UP-NODES TEMPORAL SCREENING ===")
print(
    upnodes_top[
        [
            "date",
            "extreme_feature_count",
            "max_abs_robust_z",
            "upnodes_mean_mean",
            "upnodes_mean_std",
            "upnodes_max_mean",
            "upnodes_std_mean",
            "upnodes_mean_change_pct"
        ]
    ].head(10).to_string(index=False)
)

print("\n=== EXTREME DAY COUNTS ===")
print(
    "GetADDR days with >=1 extreme feature:",
    int((getaddr["extreme_feature_count"] >= 1).sum())
)

print(
    "GetADDR days with >=2 extreme features:",
    int((getaddr["extreme_feature_count"] >= 2).sum())
)

print(
    "Up-nodes days with >=1 extreme feature:",
    int((upnodes["extreme_feature_count"] >= 1).sum())
)

print(
    "Up-nodes days with >=2 extreme features:",
    int((upnodes["extreme_feature_count"] >= 2).sum())
)

# ---------------------------------------------------------
# Save screening results
# ---------------------------------------------------------
GETADDR_OUT = (
    f"{PROCESSED_DIR}/p2p3_getaddr_temporal_screening_v1.parquet"
)

UPNODES_OUT = (
    f"{PROCESSED_DIR}/p2p3_upnodes_temporal_screening_v1.parquet"
)

getaddr.to_parquet(GETADDR_OUT, index=False)
upnodes.to_parquet(UPNODES_OUT, index=False)

print("\nSaved:")
print(GETADDR_OUT)
print(UPNODES_OUT)

=== GETADDR TEMPORAL SCREENING ===
      date  extreme_feature_count  max_abs_robust_z  getaddr_peer_rows_mean  getaddr_peer_rows_std  getaddr_missing_ratio  getaddr_peer_row_change_pct
2020-06-07                      4         24.661406             6323.752778              38.283541               0.621249                    -0.062958
2020-07-09                      4         23.900453             6354.338843              33.151559               0.563780                     0.004837
2020-02-28                      3         12.382120             6817.311111              40.544661               0.581762                    -0.044122
2020-03-02                      2         14.090830             6748.630556              29.193708               0.581144                    -0.005464
2020-03-01                      2         13.168438             6785.705556              43.345370               0.583873                    -0.004887
2020-02-29                      2         12.339273             6819.033333              40.781898               0.581367                     0.000253
2020-02-27                      2          4.905136             7131.988889              75.341376               0.606478                    -0.026046
2020-02-11                      1         10.197906             7330.508333             150.701147               0.626033                    -0.006662
2020-02-07                      1          5.258578             7315.002778              99.629886               0.627609                     0.000000
2020-02-21                      1          4.019787             7250.683333              86.821141               0.639916                    -0.009992

=== UP-NODES TEMPORAL SCREENING ===
      date  extreme_feature_count  max_abs_robust_z  upnodes_mean_mean  upnodes_mean_std  upnodes_max_mean  upnodes_std_mean  upnodes_mean_change_pct
2020-07-09                      7         36.773825           0.001824          0.004106        299.289256        543.161682                -0.999990
2020-06-07                      6          8.613788         183.935649         16.949362        723.294444        157.675174                -0.239447
2020-02-11                      3          3.706254         240.921144         48.147885       1011.708333        249.984245                 0.004074
2020-02-12                      0          2.845199         244.014486         19.748004        999.133333        216.207850                 0.012840
2020-02-24                      0          2.802431         236.973401         20.618681        957.786111        211.120279                -0.104072
2020-02-23                      0          2.259199         264.500603         35.751848       1017.838889        240.030406                 0.050655
2020-02-08                      0          2.096495         253.923170         37.712019        993.844444        228.198306                 0.053277
2020-02-26                      0          1.914980         226.533958         23.590304        952.144444        208.471458                -0.069825
2020-02-14                      0          1.676941         240.823873         33.801832        970.486111        217.130408                -0.060639
2020-02-21                      0          1.606668         258.266754         23.143949        998.450000        231.528438                 0.035713

=== EXTREME DAY COUNTS ===
GetADDR days with >=1 extreme feature: 10
GetADDR days with >=2 extreme features: 7
Up-nodes days with >=1 extreme feature: 3
Up-nodes days with >=2 extreme features: 3

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_getaddr_temporal_screening_v1.parquet
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p3_upnodes_temporal_screening_v1.parquet

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

GETADDR_PATH = (
    f"{PROCESSED_DIR}/p2p3_getaddr_features_clean_v1.parquet"
)

UPNODES_PATH = (
    f"{PROCESSED_DIR}/p2p3_upnodes_features_clean_v1.parquet"
)

getaddr = pd.read_parquet(GETADDR_PATH)
upnodes = pd.read_parquet(UPNODES_PATH)

getaddr["date"] = pd.to_datetime(getaddr["date"])
upnodes["date"] = pd.to_datetime(upnodes["date"])

# ---------------------------------------------------------
# Assign historical observation periods
# ---------------------------------------------------------

def period_label(date):
    if date <= pd.Timestamp("2020-03-02"):
        return "2020-02-07_to_2020-03-02"
    elif date == pd.Timestamp("2020-06-07"):
        return "2020-06-07"
    elif date == pd.Timestamp("2020-07-09"):
        return "2020-07-09"
    return "OTHER"

getaddr["period"] = getaddr["date"].apply(period_label)
upnodes["period"] = upnodes["date"].apply(period_label)

# ---------------------------------------------------------
# Selected stable features
# ---------------------------------------------------------

getaddr_features = [
    "getaddr_peer_rows_mean",
    "getaddr_peer_rows_std",
    "getaddr_valid_values_mean",
    "getaddr_missing_ratio",
    "getaddr_mean_value_mean",
    "getaddr_max_value_max",
]

upnodes_features = [
    "upnodes_mean_mean",
    "upnodes_mean_std",
    "upnodes_max_mean",
    "upnodes_std_mean",
]

# ---------------------------------------------------------
# Period summaries
# ---------------------------------------------------------

print("=== GETADDR PERIOD SUMMARY ===")

getaddr_summary = (
    getaddr
    .groupby("period")[getaddr_features]
    .agg(["count", "mean", "median", "std", "min", "max"])
)

print(getaddr_summary.to_string())

print("\n=== UP-NODES PERIOD SUMMARY ===")

upnodes_summary = (
    upnodes
    .groupby("period")[upnodes_features]
    .agg(["count", "mean", "median", "std", "min", "max"])
)

print(upnodes_summary.to_string())

# ---------------------------------------------------------
# Relative change of isolated periods from Feb-Mar baseline
# ---------------------------------------------------------

baseline_getaddr = getaddr[
    getaddr["period"] == "2020-02-07_to_2020-03-02"
][getaddr_features].median()

baseline_upnodes = upnodes[
    upnodes["period"] == "2020-02-07_to_2020-03-02"
][upnodes_features].median()

print("\n=== GETADDR MEDIAN RELATIVE TO FEB-MAR BASELINE ===")

for period in ["2020-06-07", "2020-07-09"]:
    row = (
        getaddr[getaddr["period"] == period]
        [getaddr_features]
        .iloc[0]
    )

    print(f"\n{period}")

    for feature in getaddr_features:
        base = baseline_getaddr[feature]

        if base != 0:
            change = (row[feature] - base) / abs(base)
        else:
            change = np.nan

        print(
            f"{feature}: "
            f"{change * 100:.2f}%"
        )

print("\n=== UP-NODES MEDIAN RELATIVE TO FEB-MAR BASELINE ===")

for period in ["2020-06-07", "2020-07-09"]:
    row = (
        upnodes[upnodes["period"] == period]
        [upnodes_features]
        .iloc[0]
    )

    print(f"\n{period}")

    for feature in upnodes_features:
        base = baseline_upnodes[feature]

        if base != 0:
            change = (row[feature] - base) / abs(base)
        else:
            change = np.nan

        print(
            f"{feature}: "
            f"{change * 100:.2f}%"
        )

=== GETADDR PERIOD SUMMARY ===
                         getaddr_peer_rows_mean                                                                 getaddr_peer_rows_std                                                         getaddr_valid_values_mean                                                                     getaddr_missing_ratio                                                   getaddr_mean_value_mean                                                           getaddr_max_value_max
                                          count         mean       median         std          min          max                 count       mean     median        std        min         max                     count          mean        median         std           min           max                 count      mean    median       std       min       max                   count        mean      median       std         min         max                 count     mean  median         std     min     max
period
2020-02-07_to_2020-03-02                     25  7230.553444  7315.825000  200.700416  6748.630556  7379.672222                    25  53.533181  47.281923  26.402889  29.193708  150.701147                        25   9392.253222   9387.744444  195.932016   8950.044444   9762.397222                    25  0.619537  0.626033  0.017813  0.581144  0.639916                      25  100.862999  100.449865  2.383457   96.917793  105.959328                    25  1438.44  1380.0  472.271292   979.0  2508.0
2020-06-07                                    1  6323.752778  6323.752778         NaN  6323.752778  6323.752778                     1  38.283541  38.283541        NaN  38.283541   38.283541                         1   8315.216667   8315.216667         NaN   8315.216667   8315.216667                     1  0.621249  0.621249       NaN  0.621249  0.621249                       1  106.098428  106.098428       NaN  106.098428  106.098428                     1  1998.00  1998.0         NaN  1998.0  1998.0
2020-07-09                                    1  6354.338843  6354.338843         NaN  6354.338843  6354.338843                     1  33.151559  33.151559        NaN  33.151559   33.151559                         1  10233.966942  10233.966942         NaN  10233.966942  10233.966942                     1  0.563780  0.563780       NaN  0.563780  0.563780                       1  906.174231  906.174231       NaN  906.174231  906.174231                     1  2509.00  2509.0         NaN  2509.0  2509.0

=== UP-NODES PERIOD SUMMARY ===
                         upnodes_mean_mean                                                           upnodes_mean_std                                                       upnodes_max_mean                                                             upnodes_std_mean
                                     count        mean      median       std         min         max            count       mean     median       std        min        max            count        mean      median        std         min          max            count        mean      median       std         min         max
period
2020-02-07_to_2020-03-02                25  244.214644  243.539182  9.092133  226.533958  264.500603               25  27.001237  24.422852  6.945723  18.965249  48.147885               25  984.604778  986.336111  21.397038  952.144444  1019.411111               25  220.599249  221.273695  9.894794  208.471458  249.984245
2020-06-07                               1  183.935649  183.935649       NaN  183.935649  183.935649                1  16.949362  16.949362       NaN  16.949362  16.949362                1  723.294444  723.294444        NaN  723.294444   723.294444                1  157.675174  157.675174       NaN  157.675174  157.675174
2020-07-09                               1    0.001824    0.001824       NaN    0.001824    0.001824                1   0.004106   0.004106       NaN   0.004106   0.004106                1  299.289256  299.289256        NaN  299.289256   299.289256                1  543.161682  543.161682       NaN  543.161682  543.161682

=== GETADDR MEDIAN RELATIVE TO FEB-MAR BASELINE ===

2020-06-07
getaddr_peer_rows_mean: -13.56%
getaddr_peer_rows_std: -19.03%
getaddr_valid_values_mean: -11.42%
getaddr_missing_ratio: -0.76%
getaddr_mean_value_mean: 5.62%
getaddr_max_value_max: 44.78%

2020-07-09
getaddr_peer_rows_mean: -13.14%
getaddr_peer_rows_std: -29.89%
getaddr_valid_values_mean: 9.01%
getaddr_missing_ratio: -9.94%
getaddr_mean_value_mean: 802.12%
getaddr_max_value_max: 81.81%

=== UP-NODES MEDIAN RELATIVE TO FEB-MAR BASELINE ===

2020-06-07
upnodes_mean_mean: -24.47%
upnodes_mean_std: -30.60%
upnodes_max_mean: -26.67%
upnodes_std_mean: -28.74%

2020-07-09
upnodes_mean_mean: -100.00%
upnodes_mean_std: -99.98%
upnodes_max_mean: -69.66%
upnodes_std_mean: 145.47%

In [ ]:
import numpy as np

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

P2P1_PATH = (
    f"{PROCESSED_DIR}/p2p_peer_features_p2p1_clean.parquet"
)

P2P2_PATH = (
    f"{PROCESSED_DIR}/p2p_ml_matrix_v2.parquet"
)

# =========================================================
# LOAD P2P-1
# =========================================================

p2p1 = pd.read_parquet(P2P1_PATH)

print("P2P-1 shape:", p2p1.shape)

# node_id + numeric features
p2p1_numeric = p2p1.select_dtypes(
    include=[np.number]
).copy()

p2p1_numeric = (
    p2p1_numeric
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

# Log-transform strongly skewed non-negative count features
P2P1_LOG_FEATURES = [
    "observation_count",
    "observation_span_seconds",
    "unique_ports",
    "unique_services",
    "non_default_port_observations",
    "non_default_ports",
    "non_1037_service_observations",
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000",
    "max_absolute_height_deviation",
]

for col in P2P1_LOG_FEATURES:
    if col in p2p1_numeric.columns:
        p2p1_numeric[col] = np.log1p(
            p2p1_numeric[col].clip(lower=0)
        )

p2p1_scaler = StandardScaler()

X_p2p1 = p2p1_scaler.fit_transform(
    p2p1_numeric
)

# =========================================================
# P2P-1 ISOLATION FOREST
# =========================================================

if_p2p1 = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42,
    n_jobs=1
)

if_p2p1.fit(X_p2p1)

p2p1_scores = -if_p2p1.decision_function(X_p2p1)

p2p1_result = pd.DataFrame({
    "node_id": p2p1["node_id"].astype(str),
    "p2p1_score": p2p1_scores
})

# =========================================================
# LOAD EXISTING P2P-2 SCORES
# =========================================================

P2P2_SCORE_PATH = (
    f"{PROCESSED_DIR}/p2p_isolation_forest_v1_scores.parquet"
)

p2p2_scores = pd.read_parquet(P2P2_SCORE_PATH)

# Normalize node ID
p2p2_scores["node_id"] = (
    p2p2_scores["node_id"].astype(str)
)

# Find score column
score_candidates = [
    c for c in p2p2_scores.columns
    if "score" in c.lower()
]

print("\nP2P-2 score columns:", score_candidates)

p2p2_score_col = score_candidates[0]

p2p2_result = p2p2_scores[
    ["node_id", p2p2_score_col]
].copy()

p2p2_result = p2p2_result.rename(
    columns={p2p2_score_col: "p2p2_score"}
)

# =========================================================
# MERGE
# =========================================================

comparison = p2p1_result.merge(
    p2p2_result,
    on="node_id",
    how="inner"
)

print("\nComparison shape:", comparison.shape)

# =========================================================
# SCORE CORRELATION
# =========================================================

score_corr = comparison[
    ["p2p1_score", "p2p2_score"]
].corr().iloc[0, 1]

print("\n=== SCORE COMPARISON ===")
print(
    "P2P-1 mean score:",
    round(comparison["p2p1_score"].mean(), 6)
)

print(
    "P2P-2 mean score:",
    round(comparison["p2p2_score"].mean(), 6)
)

print(
    "P2P-1 std:",
    round(comparison["p2p1_score"].std(), 6)
)

print(
    "P2P-2 std:",
    round(comparison["p2p2_score"].std(), 6)
)

print(
    "Score correlation:",
    round(score_corr, 4)
)

# =========================================================
# TOP-K OVERLAP
# =========================================================

print("\n=== TOP-K OVERLAP ===")

for k in [100, 500, 1000, 2049]:

    k = min(k, len(comparison))

    top_p2p1 = set(
        comparison
        .nlargest(k, "p2p1_score")["node_id"]
    )

    top_p2p2 = set(
        comparison
        .nlargest(k, "p2p2_score")["node_id"]
    )

    overlap = len(top_p2p1 & top_p2p2)

    print(
        f"K={k}: "
        f"overlap={overlap}, "
        f"overlap_rate={overlap/k:.4f}"
    )

# =========================================================
# RANK CORRELATION
# =========================================================

comparison["p2p1_rank"] = (
    comparison["p2p1_score"]
    .rank(method="average", ascending=False)
)

comparison["p2p2_rank"] = (
    comparison["p2p2_score"]
    .rank(method="average", ascending=False)
)

rank_corr = comparison[
    ["p2p1_rank", "p2p2_rank"]
].corr().iloc[0, 1]

print("\nRank correlation:", round(rank_corr, 4))

# =========================================================
# P2P-1 TOP ANOMALIES THAT DISAPPEAR FROM P2P-2 TOP-K
# =========================================================

K = min(1000, len(comparison))

top1 = set(
    comparison
    .nlargest(K, "p2p1_score")["node_id"]
)

top2 = set(
    comparison
    .nlargest(K, "p2p2_score")["node_id"]
)

lost_from_topk = top1 - top2

print(
    f"\nP2P-1 top-{K} nodes not present in P2P-2 top-{K}:",
    len(lost_from_topk)
)

# =========================================================
# SAVE
# =========================================================

OUT_PATH = (
    f"{PROCESSED_DIR}/p2p1_vs_p2p2_ablation_v1.parquet"
)

comparison.to_parquet(
    OUT_PATH,
    index=False
)

print("\nSaved:")
print(OUT_PATH)

P2P-1 shape: (21122, 18)

P2P-2 score columns: ['anomaly_score']

Comparison shape: (21122, 3)

=== SCORE COMPARISON ===
P2P-1 mean score: -0.090294
P2P-2 mean score: -0.079335
P2P-1 std: 0.074931
P2P-2 std: 0.062784
Score correlation: 0.8712

=== TOP-K OVERLAP ===
K=100: overlap=64, overlap_rate=0.6400
K=500: overlap=410, overlap_rate=0.8200
K=1000: overlap=907, overlap_rate=0.9070
K=2049: overlap=1439, overlap_rate=0.7023

Rank correlation: 0.5417

P2P-1 top-1000 nodes not present in P2P-2 top-1000: 93

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p1_vs_p2p2_ablation_v1.parquet

In [ ]:
import pandas as pd
import numpy as np

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

FEATURE_PATH = (
    f"{PROCESSED_DIR}/p2p_ml_matrix_v2.parquet"
)

df = pd.read_parquet(FEATURE_PATH)

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

# =========================================================
# IDENTIFY NODE ID + FEATURES
# =========================================================

NODE_COL = "node_id"

feature_cols = [
    c for c in df.columns
    if c != NODE_COL
]

X = df[feature_cols].copy()

X = (
    X
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

# =========================================================
# LOG TRANSFORM
# Same configuration used for P2P-2
# =========================================================

LOG_FEATURES = [
    "observation_count",
    "observation_span_seconds",
    "unique_ports",
    "unique_services",
    "non_default_port_observations",
    "non_default_ports",
    "non_1037_service_observations",
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000",
    "max_absolute_height_deviation",
    "max_observations_per_hour",
    "max_observations_per_day",
    "hourly_burst_ratio",
    "daily_burst_ratio",
]

for col in LOG_FEATURES:
    if col in X.columns:
        X[col] = np.log1p(
            X[col].clip(lower=0)
        )

# =========================================================
# CREATE NODE-LEVEL TEMPORAL SPLIT
# =========================================================

# We need observation dates for each node.
# Load the normalized observations incrementally.

OBS_DIR = f"{PROCESSED_DIR}/observations"

import glob

observation_files = sorted(
    glob.glob(f"{OBS_DIR}/p2p_observations_*.parquet")
)

print("\nObservation files:", len(observation_files))

# ---------------------------------------------------------
# Find first and last observation date per node
# ---------------------------------------------------------

node_dates = []

for path in observation_files:

    part = pd.read_parquet(
        path,
        columns=["node_id", "timestamp"]
    )

    part["timestamp"] = pd.to_datetime(
        part["timestamp"]
    )

    grouped = (
        part
        .groupby("node_id")["timestamp"]
        .agg(["min", "max"])
        .reset_index()
    )

    node_dates.append(grouped)

node_dates = pd.concat(
    node_dates,
    ignore_index=True
)

# Combine repeated node records
node_dates = (
    node_dates
    .groupby("node_id")
    .agg(
        first_observed=("min", "min"),
        last_observed=("max", "max")
    )
    .reset_index()
)

node_dates["node_id"] = (
    node_dates["node_id"].astype(str)
)

df[NODE_COL] = df[NODE_COL].astype(str)

df = df.merge(
    node_dates,
    on=NODE_COL,
    how="left"
)

print("\nMerged shape:", df.shape)

print(
    "Missing first_observed:",
    df["first_observed"].isna().sum()
)

# =========================================================
# TEMPORAL HOLDOUT
# =========================================================

TRAIN_END = pd.Timestamp("2020-02-25")

train_mask = (
    df["first_observed"] <= TRAIN_END
)

test_mask = (
    df["first_observed"] > TRAIN_END
)

print("\n=== TEMPORAL SPLIT ===")
print("Train nodes:", train_mask.sum())
print("Test nodes :", test_mask.sum())

# =========================================================
# BUILD MATRICES
# =========================================================

X_train = X.loc[train_mask].copy()
X_test = X.loc[test_mask].copy()

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

# =========================================================
# SCALE USING TRAIN ONLY
# =========================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)

# =========================================================
# TRAIN ISOLATION FOREST
# =========================================================

model = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42,
    n_jobs=1
)

model.fit(X_train_scaled)

# =========================================================
# SCORE TRAIN + TEST
# =========================================================

train_scores = -model.decision_function(
    X_train_scaled
)

test_scores = -model.decision_function(
    X_test_scaled
)

print("\n=== SCORE DISTRIBUTION ===")

print(
    "Train mean:",
    round(train_scores.mean(), 6)
)

print(
    "Train std:",
    round(train_scores.std(), 6)
)

print(
    "Test mean:",
    round(test_scores.mean(), 6)
)

print(
    "Test std:",
    round(test_scores.std(), 6)
)

print(
    "Train 95th percentile:",
    round(np.percentile(train_scores, 95), 6)
)

print(
    "Test 95th percentile:",
    round(np.percentile(test_scores, 95), 6)
)

# =========================================================
# TOP-K HOLDOUT
# =========================================================

test_results = df.loc[
    test_mask,
    ["node_id", "first_observed", "last_observed"]
].copy()

test_results["anomaly_score"] = test_scores

print("\n=== TOP 20 HOLDOUT CANDIDATES ===")

print(
    test_results
    .nlargest(20, "anomaly_score")
    .to_string(index=False)
)

# =========================================================
# SAVE HOLDOUT RESULTS
# =========================================================

OUT_PATH = (
    f"{PROCESSED_DIR}/p2p_temporal_holdout_v1.parquet"
)

test_results.to_parquet(
    OUT_PATH,
    index=False
)

print("\nSaved:")
print(OUT_PATH)

Dataset shape: (21122, 29)
Columns: ['node_id', 'observation_count', 'active_days', 'active_hours', 'observation_span_seconds', 'unique_ports', 'unique_services', 'non_default_port_observations', 'non_default_ports', 'non_1037_service_observations', 'min_reported_height', 'max_reported_height', 'mean_height_deviation', 'mean_absolute_height_deviation', 'max_absolute_height_deviation', 'height_deviation_over_100', 'height_deviation_over_1000', 'height_deviation_over_10000', 'mean_observations_per_hour', 'max_observations_per_hour', 'hourly_activity_std', 'hourly_activity_variance', 'mean_observations_per_day', 'max_observations_per_day', 'daily_activity_std', 'hourly_burst_ratio', 'daily_burst_ratio', 'hourly_activity_cv', 'daily_activity_cv']

Observation files: 27

Merged shape: (21122, 31)
Missing first_observed: 0

=== TEMPORAL SPLIT ===
Train nodes: 14871
Test nodes : 6251
X_train: (14871, 28)
X_test : (6251, 28)

=== SCORE DISTRIBUTION ===
Train mean: -0.073471
Train std: 0.070062
Test mean: -0.035899
Test std: 0.054913
Train 95th percentile: 0.08612
Test 95th percentile: 0.072051

=== TOP 20 HOLDOUT CANDIDATES ===
                                                         node_id      first_observed       last_observed  anomaly_score
4bd2028478f1b968a8146a5e12124a76b129b12c75a0bdea98df02dc6b48d272 2020-06-07 00:00:50 2020-07-09 23:48:52       0.218920
6f7346021cef2ae517fe7a246d71f40b0840a63fc442f39ccf0488ec64a14daf 2020-07-09 00:02:19 2020-07-09 23:48:52       0.216420
54f1e97e745d43bc47ee8cd7155b0866cc7402b75cb30434cea9e246c2ab21a4 2020-06-07 00:00:50 2020-07-09 23:48:52       0.216167
4bff7ba88978add64b4108fdf62e47040e028fc6b45b3f67432e9052188e59e3 2020-06-07 00:00:50 2020-06-07 23:57:10       0.212128
83f76f18924eab6c39fef82e6551e82fd0415a458dada8a9cef31f915b8aaf7b 2020-03-02 19:46:26 2020-03-02 21:02:15       0.209801
9e800520846bac1b72de84db6fa3a51700ef2b06a7669c105f30a3ad9f08ca96 2020-07-09 00:02:19 2020-07-09 23:48:52       0.208757
e834c32836a3b6ba7935df56594e1796b795eb1758e30fe87e9321c5b6d3808e 2020-07-09 00:02:19 2020-07-09 23:48:52       0.205830
d7b27e465bdd39c2aa0fee75b91a9d89856477634abc322eb2a710e6610323af 2020-02-27 14:54:45 2020-02-29 14:26:55       0.205761
764778c0edaa31797e38fa16ca23e77da3ae542a503419ee3206f3053fdc6711 2020-02-28 12:54:35 2020-02-28 16:18:24       0.197492
766fd7fa630f5e115a56b5af8a5d096bdbba8ea3ea499593702af6321b28da71 2020-03-01 18:50:16 2020-03-01 20:46:16       0.197145
6a681ea58c47c39f2f892f2f9977db7ea2b7634ec83018989f43caf48c7b7fdf 2020-06-07 00:00:50 2020-06-07 23:57:10       0.193961
361c3b1c83a0be4786afbd662c776ecab4e8ba5d92b7a0e655407366a9511976 2020-06-07 00:00:50 2020-07-09 23:48:52       0.192301
4aefe0fbc7bf46c438cdcbe63a1366a723c58452fd31206b9b7c4a5bc60f1e97 2020-02-29 01:34:25 2020-03-01 19:06:25       0.191140
2ce30489f94b1ef563f45122dae19d497fa0139e442a5a7a4ecae54878098999 2020-06-07 10:04:40 2020-06-07 15:53:10       0.190119
ae15c4406ff05c4c19cb3935b4f2b3b4ea56ef025ac197485291aaf839874ca7 2020-07-09 00:02:19 2020-07-09 23:37:00       0.189191
b26ef664aac18813262c9777f120975e7406a4ef2db5ac24007a15495b2a1938 2020-06-07 00:00:50 2020-06-07 23:57:10       0.188899
80bdf25ec1d5754bc1821bd6c67dfd1919b90fff7ddf3057558c017a3650a3be 2020-02-25 11:50:33 2020-02-27 01:18:53       0.188619
b79320415fdf3e7ed9156a99a66a0cab4f1e49e4e7f7d239fff3db8fcc7b2699 2020-02-25 11:50:33 2020-03-02 23:58:36       0.188178
0dc04402dc5d0812237d7987e96143100a7145a21be478215f3ef7e90521a266 2020-02-25 13:18:23 2020-02-26 11:54:43       0.187760
070033c4f2667f0559dd9e87003b8c7607544bbe81b3304d3a999aaf7ef6e876 2020-02-29 07:22:25 2020-03-02 17:42:15       0.187099

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_temporal_holdout_v1.parquet

In [ ]:
import pandas as pd
import numpy as np

PROCESSED_DIR = "/content/drive/MyDrive/Bitcoin P2P Dataset/processed"

HOLDOUT_PATH = (
    f"{PROCESSED_DIR}/p2p_temporal_holdout_v1.parquet"
)

RESULTS_PATH = (
    f"{PROCESSED_DIR}/p2p_isolation_forest_v1_scores.parquet"
)

holdout = pd.read_parquet(HOLDOUT_PATH)

# Existing full-dataset P2P-2 scores
full_scores = pd.read_parquet(RESULTS_PATH)

score_col = [
    c for c in full_scores.columns
    if "score" in c.lower()
][0]

full_score_values = full_scores[score_col].astype(float)

# ---------------------------------------------------------
# TRAIN REFERENCE THRESHOLDS
# ---------------------------------------------------------
# Reconstruct the same temporal train split from Step 80.
# We use the stored holdout first_observed to separate
# later nodes. For the training reference, use all nodes
# not present in holdout.

holdout_nodes = set(
    holdout["node_id"].astype(str)
)

full_scores["node_id"] = (
    full_scores["node_id"].astype(str)
)

train_reference = full_scores[
    ~full_scores["node_id"].isin(holdout_nodes)
][score_col].astype(float)

threshold_95 = np.percentile(
    train_reference,
    95
)

threshold_99 = np.percentile(
    train_reference,
    99
)

print("=== TRAIN REFERENCE ===")
print("Training reference nodes:", len(train_reference))
print("95th percentile:", round(threshold_95, 6))
print("99th percentile:", round(threshold_99, 6))

# ---------------------------------------------------------
# HOLDOUT THRESHOLD COUNTS
# ---------------------------------------------------------

holdout["period"] = "Feb-Mar"

holdout.loc[
    holdout["first_observed"] >= pd.Timestamp("2020-06-07"),
    "period"
] = "Jun-Jul"

print("\n=== HOLDOUT THRESHOLD ANALYSIS ===")

for threshold_name, threshold in [
    ("95th", threshold_95),
    ("99th", threshold_99)
]:

    count = (
        holdout["anomaly_score"] >= threshold
    ).sum()

    rate = count / len(holdout)

    print(
        f"{threshold_name} threshold: "
        f"{count} / {len(holdout)} "
        f"({rate:.2%})"
    )

# ---------------------------------------------------------
# TOP-K
# ---------------------------------------------------------

print("\n=== TOP-K HOLDOUT CANDIDATES ===")

for k in [100, 500, 1000]:

    k = min(k, len(holdout))

    top = holdout.nlargest(
        k,
        "anomaly_score"
    )

    period_counts = (
        top["period"]
        .value_counts()
        .to_dict()
    )

    print(
        f"Top-{k}:",
        period_counts
    )

# ---------------------------------------------------------
# SCORE DISTRIBUTION
# ---------------------------------------------------------

print("\n=== HOLDOUT SCORE DISTRIBUTION ===")

percentiles = [50, 75, 90, 95, 99, 99.5]

for p in percentiles:

    value = np.percentile(
        holdout["anomaly_score"],
        p
    )

    print(
        f"{p}th percentile:",
        round(value, 6)
    )

# ---------------------------------------------------------
# PERIOD-LEVEL SCORE SUMMARY
# ---------------------------------------------------------

print("\n=== PERIOD SCORE SUMMARY ===")

period_summary = (
    holdout
    .groupby("period")["anomaly_score"]
    .agg(
        count="count",
        mean="mean",
        median="median",
        std="std",
        min="min",
        max="max"
    )
)

print(
    period_summary.to_string()
)

# ---------------------------------------------------------
# SAVE EVALUATION SUMMARY
# ---------------------------------------------------------

summary_rows = [
    {
        "metric": "train_reference_nodes",
        "value": len(train_reference)
    },
    {
        "metric": "holdout_nodes",
        "value": len(holdout)
    },
    {
        "metric": "train_95_threshold",
        "value": threshold_95
    },
    {
        "metric": "train_99_threshold",
        "value": threshold_99
    },
    {
        "metric": "holdout_above_train_95",
        "value": int(
            (holdout["anomaly_score"] >= threshold_95).sum()
        )
    },
    {
        "metric": "holdout_above_train_99",
        "value": int(
            (holdout["anomaly_score"] >= threshold_99).sum()
        )
    }
]

summary = pd.DataFrame(summary_rows)

OUT_PATH = (
    f"{PROCESSED_DIR}/p2p_temporal_evaluation_v1.parquet"
)

summary.to_parquet(
    OUT_PATH,
    index=False
)

print("\nSaved:")
print(OUT_PATH)

=== TRAIN REFERENCE ===
Training reference nodes: 14871
95th percentile: 0.071116
99th percentile: 0.161929

=== HOLDOUT THRESHOLD ANALYSIS ===
95th threshold: 320 / 6251 (5.12%)
99th threshold: 71 / 6251 (1.14%)

=== TOP-K HOLDOUT CANDIDATES ===
Top-100: {'Jun-Jul': 61, 'Feb-Mar': 39}
Top-500: {'Jun-Jul': 330, 'Feb-Mar': 170}
Top-1000: {'Jun-Jul': 810, 'Feb-Mar': 190}

=== HOLDOUT SCORE DISTRIBUTION ===
50th percentile: -0.051392
75th percentile: 0.006639
90th percentile: 0.011764
95th percentile: 0.072051
99th percentile: 0.164146
99.5th percentile: 0.177653

=== PERIOD SCORE SUMMARY ===
         count      mean    median       std       min       max
period
Feb-Mar   2029 -0.056667 -0.076942  0.059118 -0.111087  0.209801
Jun-Jul   4222 -0.025919 -0.044171  0.049795 -0.099277  0.218920

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_temporal_evaluation_v1.parquet

In [ ]:
# ============================================================
# STEP 82 — FINAL TRAIN-ONLY P2P-2 ISOLATION FOREST
# ============================================================

import os
import json
import joblib
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"
PROCESSED = os.path.join(BASE, "processed")

ML_PATH = os.path.join(PROCESSED, "p2p_ml_matrix_v2.parquet")
OUT_MODEL = os.path.join(PROCESSED, "p2p_final_isolation_forest_v1.joblib")
OUT_SCALER = os.path.join(PROCESSED, "p2p_final_scaler_v1.joblib")
OUT_CONFIG = os.path.join(PROCESSED, "p2p_final_feature_config_v1.json")
OUT_SCORES = os.path.join(PROCESSED, "p2p_final_train_holdout_scores_v1.parquet")
OUT_METADATA = os.path.join(PROCESSED, "p2p_final_model_metadata_v1.json")

# ------------------------------------------------------------
# LOAD FEATURE MATRIX
# ------------------------------------------------------------

df = pd.read_parquet(ML_PATH)

print("Loaded:", df.shape)

NODE_COL = "node_id"

feature_cols = [c for c in df.columns if c != NODE_COL]

print("Feature count:", len(feature_cols))
print("Features:")
for i, c in enumerate(feature_cols, 1):
    print(f"{i:02d}. {c}")

# ------------------------------------------------------------
# TEMPORAL SPLIT
# Same split used in Step 80
# ------------------------------------------------------------

# Load first/last observation timestamps from normalized P2P data
obs_dir = os.path.join(PROCESSED, "observations")

files = sorted([
    os.path.join(obs_dir, f)
    for f in os.listdir(obs_dir)
    if f.endswith(".parquet")
])

print("\nObservation files:", len(files))

first_seen_parts = []

for path in files:
    tmp = pd.read_parquet(
        path,
        columns=["timestamp", "node_id"]
    )

    tmp["timestamp"] = pd.to_datetime(
        tmp["timestamp"],
        errors="coerce"
    )

    g = (
        tmp.groupby("node_id", sort=False)["timestamp"]
        .agg(["min", "max"])
        .reset_index()
    )

    g.columns = ["node_id", "first_observed", "last_observed"]

    first_seen_parts.append(g)

    del tmp, g

node_times = pd.concat(
    first_seen_parts,
    ignore_index=True
)

# Consolidate because a node can occur in multiple files
node_times = (
    node_times
    .groupby("node_id", as_index=False)
    .agg(
        first_observed=("first_observed", "min"),
        last_observed=("last_observed", "max")
    )
)

print("Node time table:", node_times.shape)

# ------------------------------------------------------------
# MERGE
# ------------------------------------------------------------

data = df.merge(
    node_times,
    on="node_id",
    how="left",
    validate="one_to_one"
)

assert data["first_observed"].notna().all()

# Same cutoff used in Step 80
TRAIN_END = pd.Timestamp("2020-02-25")

train_mask = data["first_observed"] <= TRAIN_END
test_mask = ~train_mask

train = data.loc[train_mask].copy()
holdout = data.loc[test_mask].copy()

print("\n================================================")
print("TEMPORAL SPLIT")
print("================================================")
print("Train:", len(train))
print("Holdout:", len(holdout))
print("Total:", len(data))

assert len(train) == 14871
assert len(holdout) == 6251

# ------------------------------------------------------------
# FEATURES
# ------------------------------------------------------------

X_train = train[feature_cols].copy()
X_holdout = holdout[feature_cols].copy()

# ------------------------------------------------------------
# LOG TRANSFORM
# Same transformation used in Step 80
# ------------------------------------------------------------

log_features = [
    "observation_count",
    "observation_span_seconds",
    "unique_ports",
    "unique_services",
    "non_default_port_observations",
    "non_default_ports",
    "non_1037_service_observations",
    "height_deviation_over_100",
    "height_deviation_over_1000",
    "height_deviation_over_10000",
    "max_absolute_height_deviation",
    "max_observations_per_hour",
    "max_observations_per_day",
    "hourly_burst_ratio",
    "daily_burst_ratio"
]

print("\nLog-transform features:", len(log_features))

for col in log_features:
    X_train[col] = np.log1p(
        np.clip(X_train[col].astype(float), 0, None)
    )

    X_holdout[col] = np.log1p(
        np.clip(X_holdout[col].astype(float), 0, None)
    )

# ------------------------------------------------------------
# FILL UNDEFINED TEMPORAL VARIABILITY VALUES
# ------------------------------------------------------------

for col in feature_cols:
    if X_train[col].isna().any():
        median_value = X_train[col].median()

        X_train[col] = X_train[col].fillna(median_value)
        X_holdout[col] = X_holdout[col].fillna(median_value)

# ------------------------------------------------------------
# STANDARD SCALER
# FIT ONLY ON TRAIN
# ------------------------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_holdout_scaled = scaler.transform(X_holdout)

print("\nScaled train:", X_train_scaled.shape)
print("Scaled holdout:", X_holdout_scaled.shape)

# ------------------------------------------------------------
# FINAL ISOLATION FOREST
# ------------------------------------------------------------

model = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42,
    n_jobs=1
)

print("\nTraining Isolation Forest...")

model.fit(X_train_scaled)

print("Training complete.")

# ------------------------------------------------------------
# ANOMALY SCORES
#
# sklearn decision_function:
#   larger = more normal
#
# We invert it:
#   larger = more anomalous
# ------------------------------------------------------------

train_scores = -model.decision_function(
    X_train_scaled
)

holdout_scores = -model.decision_function(
    X_holdout_scaled
)

# ------------------------------------------------------------
# PREDICTIONS
# ------------------------------------------------------------

train_predictions = model.predict(X_train_scaled)
holdout_predictions = model.predict(X_holdout_scaled)

# ------------------------------------------------------------
# THRESHOLDS FROM TRAIN ONLY
# ------------------------------------------------------------

threshold_95 = np.percentile(
    train_scores,
    95
)

threshold_99 = np.percentile(
    train_scores,
    99
)

print("\n================================================")
print("TRAIN REFERENCE")
print("================================================")

print("95th percentile:", round(threshold_95, 6))
print("99th percentile:", round(threshold_99, 6))

# ------------------------------------------------------------
# HOLDOUT THRESHOLD RESULTS
# ------------------------------------------------------------

holdout_above_95 = holdout_scores >= threshold_95
holdout_above_99 = holdout_scores >= threshold_99

print("\n================================================")
print("HOLDOUT RESULTS")
print("================================================")

print(
    "Above train 95th:",
    int(holdout_above_95.sum()),
    "/",
    len(holdout),
    f"({holdout_above_95.mean()*100:.2f}%)"
)

print(
    "Above train 99th:",
    int(holdout_above_99.sum()),
    "/",
    len(holdout),
    f"({holdout_above_99.mean()*100:.2f}%)"
)

# ------------------------------------------------------------
# SCORE DISTRIBUTION
# ------------------------------------------------------------

print("\n================================================")
print("SCORE DISTRIBUTION")
print("================================================")

for q in [50, 75, 90, 95, 99, 99.5, 99.9]:
    print(
        f"{q:>5.1f}th percentile:",
        f"{np.percentile(holdout_scores, q):.6f}"
    )

# ------------------------------------------------------------
# SAVE TRAIN + HOLDOUT SCORES
# ------------------------------------------------------------

train_result = pd.DataFrame({
    "node_id": train[NODE_COL].values,
    "first_observed": train["first_observed"].values,
    "last_observed": train["last_observed"].values,
    "dataset_split": "train",
    "anomaly_score": train_scores,
    "model_prediction": train_predictions,
    "above_train_95_threshold": train_scores >= threshold_95,
    "above_train_99_threshold": train_scores >= threshold_99
})

holdout_result = pd.DataFrame({
    "node_id": holdout[NODE_COL].values,
    "first_observed": holdout["first_observed"].values,
    "last_observed": holdout["last_observed"].values,
    "dataset_split": "holdout",
    "anomaly_score": holdout_scores,
    "model_prediction": holdout_predictions,
    "above_train_95_threshold": holdout_above_95,
    "above_train_99_threshold": holdout_above_99
})

scores_output = pd.concat(
    [train_result, holdout_result],
    ignore_index=True
)

scores_output.to_parquet(
    OUT_SCORES,
    index=False
)

# ------------------------------------------------------------
# SAVE MODEL
# ------------------------------------------------------------

joblib.dump(
    model,
    OUT_MODEL
)

joblib.dump(
    scaler,
    OUT_SCALER
)

# ------------------------------------------------------------
# SAVE FEATURE CONFIGURATION
# ------------------------------------------------------------

feature_config = {
    "model_name": "BIT-TRACE P2P-2 Isolation Forest",
    "version": "v1",
    "node_identifier": NODE_COL,
    "feature_count": len(feature_cols),
    "features": feature_cols,
    "log1p_features": log_features,
    "scaler": "StandardScaler",
    "model": "IsolationForest",
    "n_estimators": 300,
    "contamination": "auto",
    "random_state": 42,
    "n_jobs": 1,
    "train_cutoff": "2020-02-25",
    "train_nodes": int(len(train)),
    "holdout_nodes": int(len(holdout)),
    "score_definition": "-IsolationForest.decision_function(X)",
    "higher_score_means": "more_anomalous",
    "thresholds": {
        "train_95_percentile": float(threshold_95),
        "train_99_percentile": float(threshold_99)
    }
}

with open(
    OUT_CONFIG,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        feature_config,
        f,
        indent=2
    )

# ------------------------------------------------------------
# MODEL METADATA
# ------------------------------------------------------------

metadata = {
    "model": "Isolation Forest",
    "branch": "P2P",
    "feature_set": "P2P-2",
    "dataset": "Bitcoin P2P historical crawler observations",
    "dataset_period": "2020-02-07 to 2020-07-09",
    "training_split": {
        "rule": "first_observed <= 2020-02-25",
        "nodes": int(len(train))
    },
    "holdout_split": {
        "rule": "first_observed > 2020-02-25",
        "nodes": int(len(holdout))
    },
    "parameters": {
        "n_estimators": 300,
        "contamination": "auto",
        "random_state": 42
    },
    "preprocessing": {
        "log1p_feature_count": len(log_features),
        "scaler": "StandardScaler",
        "fit_only_on_training_data": True
    },
    "results": {
        "train_95_threshold": float(threshold_95),
        "train_99_threshold": float(threshold_99),
        "holdout_above_95_count": int(holdout_above_95.sum()),
        "holdout_above_95_rate": float(holdout_above_95.mean()),
        "holdout_above_99_count": int(holdout_above_99.sum()),
        "holdout_above_99_rate": float(holdout_above_99.mean())
    },
    "evaluation_note": (
        "The real P2P dataset has no verified anomaly labels. "
        "Therefore conventional classification accuracy is not reported. "
        "Evaluation uses temporal holdout scoring, threshold exceedance, "
        "score distributions, ranking stability, and period analysis."
    )
}

with open(
    OUT_METADATA,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        metadata,
        f,
        indent=2
    )

# ------------------------------------------------------------
# VERIFY ARTIFACTS
# ------------------------------------------------------------

print("\n================================================")
print("SAVED ARTIFACTS")
print("================================================")

for path in [
    OUT_MODEL,
    OUT_SCALER,
    OUT_CONFIG,
    OUT_SCORES,
    OUT_METADATA
]:
    print(
        os.path.basename(path),
        "->",
        f"{os.path.getsize(path) / 1024**2:.2f} MB"
    )

print("\n================================================")
print("STEP 82 COMPLETE")
print("================================================")

Loaded: (21122, 29)
Feature count: 28
Features:
01. observation_count
02. active_days
03. active_hours
04. observation_span_seconds
05. unique_ports
06. unique_services
07. non_default_port_observations
08. non_default_ports
09. non_1037_service_observations
10. min_reported_height
11. max_reported_height
12. mean_height_deviation
13. mean_absolute_height_deviation
14. max_absolute_height_deviation
15. height_deviation_over_100
16. height_deviation_over_1000
17. height_deviation_over_10000
18. mean_observations_per_hour
19. max_observations_per_hour
20. hourly_activity_std
21. hourly_activity_variance
22. mean_observations_per_day
23. max_observations_per_day
24. daily_activity_std
25. hourly_burst_ratio
26. daily_burst_ratio
27. hourly_activity_cv
28. daily_activity_cv

Observation files: 27
Node time table: (21122, 3)

================================================
TEMPORAL SPLIT
================================================
Train: 14871
Holdout: 6251
Total: 21122

Log-transform features: 15

Scaled train: (14871, 28)
Scaled holdout: (6251, 28)

Training Isolation Forest...
Training complete.

================================================
TRAIN REFERENCE
================================================
95th percentile: 0.08612
99th percentile: 0.172871

================================================
HOLDOUT RESULTS
================================================
Above train 95th: 269 / 6251 (4.30%)
Above train 99th: 46 / 6251 (0.74%)

================================================
SCORE DISTRIBUTION
================================================
 50.0th percentile: -0.051392
 75.0th percentile: 0.006639
 90.0th percentile: 0.011764
 95.0th percentile: 0.072051
 99.0th percentile: 0.164146
 99.5th percentile: 0.177653
 99.9th percentile: 0.205813

================================================
SAVED ARTIFACTS
================================================
p2p_final_isolation_forest_v1.joblib -> 2.87 MB
p2p_final_scaler_v1.joblib -> 0.00 MB
p2p_final_feature_config_v1.json -> 0.00 MB
p2p_final_train_holdout_scores_v1.parquet -> 1.67 MB
p2p_final_model_metadata_v1.json -> 0.00 MB

================================================
STEP 82 COMPLETE
================================================

In [ ]:
# ============================================================
# STEP 83 — FINAL MODEL REPRODUCIBILITY TEST
# ============================================================

import os
import json
import joblib
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"
PROCESSED = os.path.join(BASE, "processed")

MODEL_PATH = os.path.join(
    PROCESSED,
    "p2p_final_isolation_forest_v1.joblib"
)

SCALER_PATH = os.path.join(
    PROCESSED,
    "p2p_final_scaler_v1.joblib"
)

CONFIG_PATH = os.path.join(
    PROCESSED,
    "p2p_final_feature_config_v1.json"
)

SCORES_PATH = os.path.join(
    PROCESSED,
    "p2p_final_train_holdout_scores_v1.parquet"
)

REPRO_PATH = os.path.join(
    PROCESSED,
    "p2p_final_reproducibility_v1.json"
)

# ------------------------------------------------------------
# LOAD ARTIFACTS
# ------------------------------------------------------------

print("Loading saved model...")

model = joblib.load(MODEL_PATH)
scaler = joblib.load(SCALER_PATH)

with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    config = json.load(f)

saved_scores = pd.read_parquet(SCORES_PATH)

print("Model loaded.")
print("Scaler loaded.")
print("Saved score table:", saved_scores.shape)

# ------------------------------------------------------------
# LOAD FEATURE MATRIX
# ------------------------------------------------------------

ML_PATH = os.path.join(
    PROCESSED,
    "p2p_ml_matrix_v2.parquet"
)

df = pd.read_parquet(ML_PATH)

NODE_COL = config["node_identifier"]
feature_cols = config["features"]

print("\nFeature count:", len(feature_cols))

assert len(feature_cols) == 28

# ------------------------------------------------------------
# RECREATE TEMPORAL SPLIT
# ------------------------------------------------------------

obs_dir = os.path.join(
    PROCESSED,
    "observations"
)

obs_files = sorted([
    os.path.join(obs_dir, f)
    for f in os.listdir(obs_dir)
    if f.endswith(".parquet")
])

first_seen_parts = []

for path in obs_files:

    tmp = pd.read_parquet(
        path,
        columns=["timestamp", "node_id"]
    )

    tmp["timestamp"] = pd.to_datetime(
        tmp["timestamp"],
        errors="coerce"
    )

    g = (
        tmp.groupby("node_id")["timestamp"]
        .min()
        .reset_index()
    )

    g.columns = [
        "node_id",
        "first_observed"
    ]

    first_seen_parts.append(g)

    del tmp, g

first_seen = pd.concat(
    first_seen_parts,
    ignore_index=True
)

first_seen = (
    first_seen
    .groupby("node_id", as_index=False)
    .first()
)

data = df.merge(
    first_seen,
    on="node_id",
    how="left",
    validate="one_to_one"
)

TRAIN_END = pd.Timestamp("2020-02-25")

holdout = data[
    data["first_observed"] > TRAIN_END
].copy()

print("Holdout nodes:", len(holdout))

assert len(holdout) == 6251

# ------------------------------------------------------------
# PREPROCESS EXACTLY AS TRAINING
# ------------------------------------------------------------

X_holdout = holdout[feature_cols].copy()

log_features = config["log1p_features"]

for col in log_features:
    X_holdout[col] = np.log1p(
        np.clip(
            X_holdout[col].astype(float),
            0,
            None
        )
    )

# Fill missing using scaler-training compatible values.
# These features had no problematic missing values in the
# final ML matrix, but keep the safeguard.

for col in feature_cols:

    if X_holdout[col].isna().any():

        # Use scaler center as an approximate standardized-space
        # fallback converted back to original space is unnecessary
        # here because final matrix should be complete.
        X_holdout[col] = X_holdout[col].fillna(
            X_holdout[col].median()
        )

# ------------------------------------------------------------
# TRANSFORM USING SAVED SCALER
# ------------------------------------------------------------

X_holdout_scaled = scaler.transform(
    X_holdout
)

# ------------------------------------------------------------
# REGENERATE SCORES
# ------------------------------------------------------------

reproduced_scores = -model.decision_function(
    X_holdout_scaled
)

# ------------------------------------------------------------
# GET ORIGINAL HOLDOUT SCORES
# ------------------------------------------------------------

original = saved_scores[
    saved_scores["dataset_split"] == "holdout"
].copy()

original = (
    original
    .sort_values("node_id")
    .reset_index(drop=True)
)

reproduced = pd.DataFrame({
    "node_id": holdout["node_id"].values,
    "reproduced_score": reproduced_scores
})

reproduced = (
    reproduced
    .sort_values("node_id")
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# COMPARE
# ------------------------------------------------------------

comparison = original[
    ["node_id", "anomaly_score"]
].copy()

comparison = comparison.merge(
    reproduced,
    on="node_id",
    how="inner",
    validate="one_to_one"
)

comparison["absolute_difference"] = (
    comparison["anomaly_score"]
    - comparison["reproduced_score"]
).abs()

max_difference = comparison[
    "absolute_difference"
].max()

mean_difference = comparison[
    "absolute_difference"
].mean()

exact_matches = (
    comparison["absolute_difference"] == 0
).sum()

total = len(comparison)

print("\n================================================")
print("REPRODUCIBILITY RESULT")
print("================================================")

print("Compared scores:", total)
print("Exact matches:", exact_matches)
print("Maximum absolute difference:", max_difference)
print("Mean absolute difference:", mean_difference)

# Floating-point tolerance
PASS_TOLERANCE = 1e-10

passed = max_difference <= PASS_TOLERANCE

print("\nTolerance:", PASS_TOLERANCE)
print("STATUS:", "PASS" if passed else "FAIL")

# ------------------------------------------------------------
# SAVE RESULT
# ------------------------------------------------------------

repro_result = {
    "model": "BIT-TRACE P2P-2 Isolation Forest",
    "holdout_nodes": int(total),
    "exact_matches": int(exact_matches),
    "max_absolute_difference": float(max_difference),
    "mean_absolute_difference": float(mean_difference),
    "tolerance": PASS_TOLERANCE,
    "status": "PASS" if passed else "FAIL"
}

with open(
    REPRO_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        repro_result,
        f,
        indent=2
    )

print("\nSaved:")
print(REPRO_PATH)

print("\n================================================")
print("STEP 83 COMPLETE")
print("================================================")

Loading saved model...
Model loaded.
Scaler loaded.
Saved score table: (21122, 8)

Feature count: 28
Holdout nodes: 6251

================================================
REPRODUCIBILITY RESULT
================================================
Compared scores: 6251
Exact matches: 6251
Maximum absolute difference: 0.0
Mean absolute difference: 0.0

Tolerance: 1e-10
STATUS: PASS

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_final_reproducibility_v1.json

================================================
STEP 83 COMPLETE
================================================

In [ ]:
# ============================================================
# STEP 84 — FINAL MODEL EVALUATION + TESTING REPORT
# ============================================================

import os
import json
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"
PROCESSED = os.path.join(BASE, "processed")

SCORES_PATH = os.path.join(
    PROCESSED,
    "p2p_final_train_holdout_scores_v1.parquet"
)

REPRO_PATH = os.path.join(
    PROCESSED,
    "p2p_final_reproducibility_v1.json"
)

OUT_EVAL = os.path.join(
    PROCESSED,
    "p2p_final_evaluation_report_v1.json"
)

OUT_TOPK = os.path.join(
    PROCESSED,
    "p2p_final_topk_evaluation_v1.parquet"
)

# ------------------------------------------------------------
# LOAD
# ------------------------------------------------------------

scores = pd.read_parquet(SCORES_PATH)

train = scores[
    scores["dataset_split"] == "train"
].copy()

holdout = scores[
    scores["dataset_split"] == "holdout"
].copy()

print("Train:", len(train))
print("Holdout:", len(holdout))

# ------------------------------------------------------------
# THRESHOLDS
# ------------------------------------------------------------

train_scores = train["anomaly_score"].values
holdout_scores = holdout["anomaly_score"].values

threshold_95 = np.percentile(
    train_scores,
    95
)

threshold_99 = np.percentile(
    train_scores,
    99
)

# ------------------------------------------------------------
# HOLDOUT THRESHOLD TEST
# ------------------------------------------------------------

above_95 = holdout_scores >= threshold_95
above_99 = holdout_scores >= threshold_99

# ------------------------------------------------------------
# SCORE DISTRIBUTION
# ------------------------------------------------------------

percentiles = {}

for q in [
    50,
    75,
    90,
    95,
    99,
    99.5,
    99.9
]:
    percentiles[str(q)] = float(
        np.percentile(
            holdout_scores,
            q
        )
    )

# ------------------------------------------------------------
# TOP-K CANDIDATES
# ------------------------------------------------------------

holdout_ranked = holdout.sort_values(
    "anomaly_score",
    ascending=False
).reset_index(drop=True)

topk_results = []

for k in [100, 500, 1000]:

    k_actual = min(k, len(holdout_ranked))

    topk = holdout_ranked.iloc[:k_actual]

    dates = pd.to_datetime(
        topk["first_observed"]
    )

    jun_jul = (
        (dates.dt.month == 6) |
        (dates.dt.month == 7)
    )

    feb_mar = (
        (dates.dt.month == 2) |
        (dates.dt.month == 3)
    )

    topk_results.append({
        "k": k_actual,
        "jun_jul_count": int(jun_jul.sum()),
        "feb_mar_count": int(feb_mar.sum()),
        "jun_jul_pct": float(
            jun_jul.mean() * 100
        ),
        "feb_mar_pct": float(
            feb_mar.mean() * 100
        ),
        "mean_score": float(
            topk["anomaly_score"].mean()
        ),
        "max_score": float(
            topk["anomaly_score"].max()
        )
    })

topk_df = pd.DataFrame(topk_results)

topk_df.to_parquet(
    OUT_TOPK,
    index=False
)

# ------------------------------------------------------------
# PERIOD ANALYSIS
# ------------------------------------------------------------

holdout["period"] = np.where(
    pd.to_datetime(
        holdout["first_observed"]
    ).dt.month.isin([6, 7]),
    "Jun-Jul",
    "Feb-Mar"
)

period_summary = (
    holdout
    .groupby("period")["anomaly_score"]
    .agg(
        count="count",
        mean="mean",
        median="median",
        std="std",
        min="min",
        max="max"
    )
    .reset_index()
)

print("\n================================================")
print("FINAL TESTING RESULTS")
print("================================================")

print("\nDataset:")
print("Total nodes:", len(scores))
print("Training nodes:", len(train))
print("Holdout nodes:", len(holdout))

print("\nThresholds:")
print(
    "Train 95th:",
    round(threshold_95, 6)
)

print(
    "Train 99th:",
    round(threshold_99, 6)
)

print("\nHoldout threshold testing:")

print(
    f">=95th: {above_95.sum()} / {len(holdout)} "
    f"({above_95.mean()*100:.2f}%)"
)

print(
    f">=99th: {above_99.sum()} / {len(holdout)} "
    f"({above_99.mean()*100:.2f}%)"
)

print("\nScore percentiles:")

for q, value in percentiles.items():
    print(
        f"{q}th: {value:.6f}"
    )

print("\nTop-K evaluation:")

print(topk_df.to_string(index=False))

print("\nPeriod analysis:")

print(
    period_summary.to_string(
        index=False
    )
)

# ------------------------------------------------------------
# REPRODUCIBILITY
# ------------------------------------------------------------

with open(
    REPRO_PATH,
    "r",
    encoding="utf-8"
) as f:
    repro = json.load(f)

# ------------------------------------------------------------
# FINAL REPORT
# ------------------------------------------------------------

evaluation_report = {

    "model": {
        "name": "BIT-TRACE P2P-2 Isolation Forest",
        "algorithm": "Isolation Forest",
        "n_estimators": 300,
        "random_state": 42,
        "feature_count": 28
    },

    "dataset": {
        "total_nodes": int(len(scores)),
        "training_nodes": int(len(train)),
        "holdout_nodes": int(len(holdout)),
        "training_rule": "first_observed <= 2020-02-25",
        "holdout_rule": "first_observed > 2020-02-25"
    },

    "threshold_testing": {
        "train_95_threshold": float(threshold_95),
        "train_99_threshold": float(threshold_99),

        "holdout_above_95_count": int(
            above_95.sum()
        ),

        "holdout_above_95_rate": float(
            above_95.mean()
        ),

        "holdout_above_99_count": int(
            above_99.sum()
        ),

        "holdout_above_99_rate": float(
            above_99.mean()
        )
    },

    "holdout_score_percentiles": percentiles,

    "top_k": topk_results,

    "period_analysis": (
        period_summary
        .replace({np.nan: None})
        .to_dict(orient="records")
    ),

    "reproducibility": repro,

    "ground_truth": {
        "available": False,
        "note": (
            "The historical Bitcoin P2P dataset does not provide "
            "verified anomaly labels."
        )
    },

    "classification_metrics": {
        "accuracy": None,
        "precision": None,
        "recall": None,
        "f1": None,
        "roc_auc": None,
        "pr_auc": None,
        "reason": (
            "Ground-truth anomaly labels are unavailable. "
            "Reporting these metrics would not be statistically valid."
        )
    },

    "evaluation_method": [
        "Temporal holdout testing",
        "Train-derived anomaly thresholds",
        "Holdout score distribution",
        "Top-K candidate analysis",
        "Period/regime analysis",
        "Model reproducibility test"
    ]
}

with open(
    OUT_EVAL,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        evaluation_report,
        f,
        indent=2
    )

print("\nSaved:")
print(OUT_EVAL)
print(OUT_TOPK)

print("\n================================================")
print("STEP 84 COMPLETE")
print("================================================")

Train: 14871
Holdout: 6251

================================================
FINAL TESTING RESULTS
================================================

Dataset:
Total nodes: 21122
Training nodes: 14871
Holdout nodes: 6251

Thresholds:
Train 95th: 0.08612
Train 99th: 0.172871

Holdout threshold testing:
>=95th: 269 / 6251 (4.30%)
>=99th: 46 / 6251 (0.74%)

Score percentiles:
50th: -0.051392
75th: 0.006639
90th: 0.011764
95th: 0.072051
99th: 0.164146
99.5th: 0.177653
99.9th: 0.205813

Top-K evaluation:
   k  jun_jul_count  feb_mar_count  jun_jul_pct  feb_mar_pct  mean_score  max_score
 100             61             39         61.0         39.0    0.173390    0.21892
 500            330            170         66.0         34.0    0.099233    0.21892
1000            810            190         81.0         19.0    0.055465    0.21892

Period analysis:
 period  count      mean    median      std       min      max
Feb-Mar   2029 -0.056667 -0.076942 0.059118 -0.111087 0.209801
Jun-Jul   4222 -0.025919 -0.044171 0.049795 -0.099277 0.218920

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_final_evaluation_report_v1.json
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_final_topk_evaluation_v1.parquet

================================================
STEP 84 COMPLETE
================================================

In [ ]:
# ============================================================
# STEP 85 — FINAL P2P EXPLAINABLE ANOMALY CANDIDATES
# ============================================================

import os
import json
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"
PROCESSED = os.path.join(BASE, "processed")

ML_PATH = os.path.join(
    PROCESSED,
    "p2p_ml_matrix_v2.parquet"
)

SCORES_PATH = os.path.join(
    PROCESSED,
    "p2p_final_train_holdout_scores_v1.parquet"
)

OUT_PATH = os.path.join(
    PROCESSED,
    "p2p_final_explainable_candidates_v1.parquet"
)

# ------------------------------------------------------------
# LOAD
# ------------------------------------------------------------

features = pd.read_parquet(ML_PATH)
scores = pd.read_parquet(SCORES_PATH)

holdout_scores = scores[
    scores["dataset_split"] == "holdout"
].copy()

print("Feature matrix:", features.shape)
print("Holdout scores:", holdout_scores.shape)

# ------------------------------------------------------------
# MERGE
# ------------------------------------------------------------

holdout = holdout_scores.merge(
    features,
    on="node_id",
    how="inner",
    validate="one_to_one"
)

print("Merged holdout:", holdout.shape)

# ------------------------------------------------------------
# TRAIN REFERENCE
# ------------------------------------------------------------

train_scores = scores[
    scores["dataset_split"] == "train"
]["anomaly_score"].values

threshold_95 = np.percentile(
    train_scores,
    95
)

threshold_99 = np.percentile(
    train_scores,
    99
)

# ------------------------------------------------------------
# FEATURE → REASON CODE
# ------------------------------------------------------------

reason_map = {

    "observation_count":
        "HIGH_OBSERVATION_ACTIVITY",

    "active_days":
        "HIGH_TEMPORAL_PERSISTENCE",

    "active_hours":
        "HIGH_TEMPORAL_ACTIVITY",

    "observation_span_seconds":
        "LONG_OBSERVATION_SPAN",

    "unique_ports":
        "HIGH_PORT_DIVERSITY",

    "unique_services":
        "HIGH_SERVICE_DIVERSITY",

    "non_default_port_observations":
        "HIGH_NON_DEFAULT_PORT_ACTIVITY",

    "non_default_ports":
        "HIGH_NON_DEFAULT_PORT_DIVERSITY",

    "non_1037_service_observations":
        "HIGH_NON_DEFAULT_SERVICE_ACTIVITY",

    "min_reported_height":
        "UNUSUAL_LOW_REPORTED_HEIGHT",

    "max_reported_height":
        "UNUSUAL_HIGH_REPORTED_HEIGHT",

    "mean_height_deviation":
        "UNUSUAL_MEAN_HEIGHT_DEVIATION",

    "mean_absolute_height_deviation":
        "HIGH_MEAN_HEIGHT_DEVIATION",

    "max_absolute_height_deviation":
        "EXTREME_HEIGHT_DEVIATION",

    "height_deviation_over_100":
        "FREQUENT_HEIGHT_DEVIATION",

    "height_deviation_over_1000":
        "LARGE_HEIGHT_DEVIATION",

    "height_deviation_over_10000":
        "EXTREME_HEIGHT_DEVIATION",

    "mean_observations_per_hour":
        "HIGH_HOURLY_ACTIVITY",

    "max_observations_per_hour":
        "HIGH_HOURLY_PEAK_ACTIVITY",

    "hourly_activity_std":
        "HIGH_HOURLY_VARIABILITY",

    "hourly_activity_variance":
        "HIGH_HOURLY_VARIANCE",

    "mean_observations_per_day":
        "HIGH_DAILY_ACTIVITY",

    "max_observations_per_day":
        "HIGH_DAILY_PEAK_ACTIVITY",

    "daily_activity_std":
        "HIGH_DAILY_VARIABILITY",

    "hourly_burst_ratio":
        "HIGH_HOURLY_BURST",

    "daily_burst_ratio":
        "HIGH_DAILY_BURST",

    "hourly_activity_cv":
        "HIGH_HOURLY_ACTIVITY_VARIABILITY",

    "daily_activity_cv":
        "HIGH_DAILY_ACTIVITY_VARIABILITY"
}

# ------------------------------------------------------------
# REFERENCE VALUES
#
# Use training population to determine unusually high/low
# feature values.
# ------------------------------------------------------------

train_nodes = scores[
    scores["dataset_split"] == "train"
]["node_id"]

train_features = features[
    features["node_id"].isin(train_nodes)
].copy()

# ------------------------------------------------------------
# ROBUST THRESHOLDS
# Median + 3*MAD
# ------------------------------------------------------------

robust_thresholds = {}

for feature in reason_map:

    if feature not in train_features.columns:
        continue

    values = pd.to_numeric(
        train_features[feature],
        errors="coerce"
    ).dropna()

    if len(values) == 0:
        continue

    median = values.median()

    mad = np.median(
        np.abs(values - median)
    )

    # Prevent zero MAD
    if mad == 0:
        q99 = values.quantile(0.99)

        robust_thresholds[feature] = {
            "median": float(median),
            "mad": float(mad),
            "upper": float(q99),
            "lower": float(values.quantile(0.01))
        }

    else:

        robust_thresholds[feature] = {
            "median": float(median),
            "mad": float(mad),
            "upper": float(
                median + 3 * 1.4826 * mad
            ),
            "lower": float(
                median - 3 * 1.4826 * mad
            )
        }

# ------------------------------------------------------------
# GENERATE REASONS
# ------------------------------------------------------------

def generate_reasons(row):

    reasons = []

    for feature, code in reason_map.items():

        if feature not in robust_thresholds:
            continue

        value = row[feature]

        if pd.isna(value):
            continue

        ref = robust_thresholds[feature]

        # For height lower bound
        if feature in [
            "min_reported_height"
        ]:

            if value < ref["lower"]:
                reasons.append(code)

        # For max-type features
        else:

            if value > ref["upper"]:
                reasons.append(code)

    # Remove duplicates while preserving order
    reasons = list(dict.fromkeys(reasons))

    return reasons


holdout["reason_codes"] = holdout.apply(
    generate_reasons,
    axis=1
)

# ------------------------------------------------------------
# CANDIDATE CLASS
# ------------------------------------------------------------

holdout["candidate_level"] = np.select(
    [
        holdout["anomaly_score"] >= threshold_99,
        holdout["anomaly_score"] >= threshold_95
    ],
    [
        "HIGH",
        "ELEVATED"
    ],
    default="BASELINE"
)

# ------------------------------------------------------------
# REASON COUNT
# ------------------------------------------------------------

holdout["reason_count"] = (
    holdout["reason_codes"]
    .apply(len)
)

# ------------------------------------------------------------
# TOP CANDIDATES
# ------------------------------------------------------------

holdout = holdout.sort_values(
    "anomaly_score",
    ascending=False
).reset_index(drop=True)

holdout["rank"] = (
    np.arange(len(holdout)) + 1
)

# Convert list to readable string for Parquet/GitHub
holdout["reason_codes_text"] = (
    holdout["reason_codes"]
    .apply(
        lambda x: "|".join(x)
        if len(x) > 0
        else "NO_EXTREME_FEATURE_REASON"
    )
)

# ------------------------------------------------------------
# SELECT OUTPUT
# ------------------------------------------------------------

output_cols = [
    "rank",
    "node_id",
    "first_observed",
    "last_observed",
    "anomaly_score",
    "candidate_level",
    "reason_count",
    "reason_codes_text"
]

final_candidates = holdout[
    output_cols
].copy()

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

final_candidates.to_parquet(
    OUT_PATH,
    index=False
)

# ------------------------------------------------------------
# DISPLAY
# ------------------------------------------------------------

print("\n================================================")
print("TOP 20 FINAL HOLDOUT CANDIDATES")
print("================================================")

print(
    final_candidates.head(20).to_string(
        index=False
    )
)

print("\n================================================")
print("CANDIDATE LEVELS")
print("================================================")

print(
    final_candidates[
        "candidate_level"
    ].value_counts()
)

print("\n================================================")
print("REASON CODE FREQUENCY")
print("================================================")

reason_frequency = {}

for codes in final_candidates["reason_codes_text"]:

    for code in codes.split("|"):

        if code == "NO_EXTREME_FEATURE_REASON":
            continue

        reason_frequency[code] = (
            reason_frequency.get(code, 0) + 1
        )

reason_frequency = dict(
    sorted(
        reason_frequency.items(),
        key=lambda x: x[1],
        reverse=True
    )
)

for code, count in list(
    reason_frequency.items()
)[:20]:

    print(
        f"{code}: {count}"
    )

print("\nSaved:")
print(OUT_PATH)

print("\n================================================")
print("STEP 85 COMPLETE")
print("================================================")

Feature matrix: (21122, 29)
Holdout scores: (6251, 8)
Merged holdout: (6251, 36)

================================================
TOP 20 FINAL HOLDOUT CANDIDATES
================================================
 rank                                                          node_id      first_observed       last_observed  anomaly_score candidate_level  reason_count                                                                                                                                                                                                                                                                                              reason_codes_text
    1 4bd2028478f1b968a8146a5e12124a76b129b12c75a0bdea98df02dc6b48d272 2020-06-07 00:00:50 2020-07-09 23:48:52       0.218920            HIGH             6                                                                                                                                                                        UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST|HIGH_DAILY_BURST
    2 6f7346021cef2ae517fe7a246d71f40b0840a63fc442f39ccf0488ec64a14daf 2020-07-09 00:02:19 2020-07-09 23:48:52       0.216420            HIGH             4                                                                                                                                                                                                              UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_BURST
    3 54f1e97e745d43bc47ee8cd7155b0866cc7402b75cb30434cea9e246c2ab21a4 2020-06-07 00:00:50 2020-07-09 23:48:52       0.216167            HIGH            10                                                                    HIGH_PORT_DIVERSITY|UNUSUAL_LOW_REPORTED_HEIGHT|UNUSUAL_HIGH_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_PEAK_ACTIVITY|HIGH_HOURLY_VARIANCE|HIGH_DAILY_PEAK_ACTIVITY|HIGH_HOURLY_BURST|HIGH_DAILY_BURST
    4 4bff7ba88978add64b4108fdf62e47040e028fc6b45b3f67432e9052188e59e3 2020-06-07 00:00:50 2020-06-07 23:57:10       0.212128            HIGH             9                                                                                 HIGH_PORT_DIVERSITY|UNUSUAL_HIGH_REPORTED_HEIGHT|UNUSUAL_MEAN_HEIGHT_DEVIATION|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_ACTIVITY|HIGH_HOURLY_PEAK_ACTIVITY|HIGH_DAILY_ACTIVITY|HIGH_DAILY_PEAK_ACTIVITY
    5 83f76f18924eab6c39fef82e6551e82fd0415a458dada8a9cef31f915b8aaf7b 2020-03-02 19:46:26 2020-03-02 21:02:15       0.209801            HIGH             7                                                                                                                                UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIABILITY|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST|HIGH_HOURLY_ACTIVITY_VARIABILITY
    6 9e800520846bac1b72de84db6fa3a51700ef2b06a7669c105f30a3ad9f08ca96 2020-07-09 00:02:19 2020-07-09 23:48:52       0.208757            HIGH             4                                                                                                                                                                                                              UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_BURST
    7 e834c32836a3b6ba7935df56594e1796b795eb1758e30fe87e9321c5b6d3808e 2020-07-09 00:02:19 2020-07-09 23:48:52       0.205830            HIGH             4                                                                                                                                                                                                              UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_BURST
    8 d7b27e465bdd39c2aa0fee75b91a9d89856477634abc322eb2a710e6610323af 2020-02-27 14:54:45 2020-02-29 14:26:55       0.205761            HIGH             9                                                                               UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIABILITY|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST|HIGH_DAILY_BURST|HIGH_HOURLY_ACTIVITY_VARIABILITY|HIGH_DAILY_ACTIVITY_VARIABILITY
    9 764778c0edaa31797e38fa16ca23e77da3ae542a503419ee3206f3053fdc6711 2020-02-28 12:54:35 2020-02-28 16:18:24       0.197492            HIGH             6                                                                                                                                                        UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST|HIGH_HOURLY_ACTIVITY_VARIABILITY
   10 766fd7fa630f5e115a56b5af8a5d096bdbba8ea3ea499593702af6321b28da71 2020-03-01 18:50:16 2020-03-01 20:46:16       0.197145            HIGH             6                                                                                                                                                        UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST|HIGH_HOURLY_ACTIVITY_VARIABILITY
   11 6a681ea58c47c39f2f892f2f9977db7ea2b7634ec83018989f43caf48c7b7fdf 2020-06-07 00:00:50 2020-06-07 23:57:10       0.193961            HIGH             5                                                                                                                                                                                         UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST
   12 361c3b1c83a0be4786afbd662c776ecab4e8ba5d92b7a0e655407366a9511976 2020-06-07 00:00:50 2020-07-09 23:48:52       0.192301            HIGH            13 HIGH_PORT_DIVERSITY|HIGH_NON_DEFAULT_PORT_DIVERSITY|UNUSUAL_HIGH_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|HIGH_HOURLY_ACTIVITY|HIGH_HOURLY_PEAK_ACTIVITY|HIGH_HOURLY_VARIABILITY|HIGH_HOURLY_VARIANCE|HIGH_DAILY_ACTIVITY|HIGH_DAILY_PEAK_ACTIVITY|HIGH_DAILY_VARIABILITY|HIGH_HOURLY_BURST|HIGH_DAILY_BURST
   13 4aefe0fbc7bf46c438cdcbe63a1366a723c58452fd31206b9b7c4a5bc60f1e97 2020-02-29 01:34:25 2020-03-01 19:06:25       0.191140            HIGH             7                                                                                                                            UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_BURST|HIGH_DAILY_BURST|HIGH_HOURLY_ACTIVITY_VARIABILITY|HIGH_DAILY_ACTIVITY_VARIABILITY
   14 2ce30489f94b1ef563f45122dae19d497fa0139e442a5a7a4ecae54878098999 2020-06-07 10:04:40 2020-06-07 15:53:10       0.190119            HIGH             5                                                                                                                                                                             UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_BURST|HIGH_HOURLY_ACTIVITY_VARIABILITY
   15 ae15c4406ff05c4c19cb3935b4f2b3b4ea56ef025ac197485291aaf839874ca7 2020-07-09 00:02:19 2020-07-09 23:37:00       0.189191            HIGH             4                                                                                                                                                                                                              UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_BURST
   16 b26ef664aac18813262c9777f120975e7406a4ef2db5ac24007a15495b2a1938 2020-06-07 00:00:50 2020-06-07 23:57:10       0.188899            HIGH             3                                                                                                                                                                                                                                UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION
   17 80bdf25ec1d5754bc1821bd6c67dfd1919b90fff7ddf3057558c017a3650a3be 2020-02-25 11:50:33 2020-02-27 01:18:53       0.188619            HIGH             7                                                                                                                                        UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST|HIGH_DAILY_BURST|HIGH_DAILY_ACTIVITY_VARIABILITY
   18 b79320415fdf3e7ed9156a99a66a0cab4f1e49e4e7f7d239fff3db8fcc7b2699 2020-02-25 11:50:33 2020-03-02 23:58:36       0.188178            HIGH             3                                                                                                                                                                                                                                UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION
   19 0dc04402dc5d0812237d7987e96143100a7145a21be478215f3ef7e90521a266 2020-02-25 13:18:23 2020-02-26 11:54:43       0.187760            HIGH             6                                                                                                                                                                        UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_VARIANCE|HIGH_HOURLY_BURST|HIGH_DAILY_BURST
   20 070033c4f2667f0559dd9e87003b8c7607544bbe81b3304d3a999aaf7ef6e876 2020-02-29 07:22:25 2020-03-02 17:42:15       0.187099            HIGH             6                                                                                                                                                            UNUSUAL_LOW_REPORTED_HEIGHT|HIGH_MEAN_HEIGHT_DEVIATION|EXTREME_HEIGHT_DEVIATION|HIGH_HOURLY_BURST|HIGH_DAILY_BURST|HIGH_HOURLY_ACTIVITY_VARIABILITY

================================================
CANDIDATE LEVELS
================================================
candidate_level
BASELINE    5982
ELEVATED     223
HIGH          46
Name: count, dtype: int64

================================================
REASON CODE FREQUENCY
================================================
UNUSUAL_HIGH_REPORTED_HEIGHT: 4208
HIGH_MEAN_HEIGHT_DEVIATION: 3489
HIGH_HOURLY_BURST: 3407
HIGH_DAILY_BURST: 2173
HIGH_HOURLY_VARIANCE: 1783
EXTREME_HEIGHT_DEVIATION: 742
HIGH_DAILY_ACTIVITY_VARIABILITY: 713
HIGH_HOURLY_ACTIVITY_VARIABILITY: 606
UNUSUAL_MEAN_HEIGHT_DEVIATION: 296
UNUSUAL_LOW_REPORTED_HEIGHT: 278
HIGH_HOURLY_VARIABILITY: 100
HIGH_DAILY_VARIABILITY: 63
HIGH_PORT_DIVERSITY: 36
HIGH_HOURLY_PEAK_ACTIVITY: 27
HIGH_DAILY_PEAK_ACTIVITY: 25
HIGH_HOURLY_ACTIVITY: 22
HIGH_NON_DEFAULT_PORT_DIVERSITY: 14
HIGH_DAILY_ACTIVITY: 13
HIGH_SERVICE_DIVERSITY: 1

Saved:
/content/drive/MyDrive/Bitcoin P2P Dataset/processed/p2p_final_explainable_candidates_v1.parquet

================================================
STEP 85 COMPLETE
================================================

In [ ]:
# ============================================================
# STEP 86 — CREATE GITHUB-READY P2P MODEL PACKAGE
# ============================================================

import os
import shutil
import json

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"
PROCESSED = os.path.join(BASE, "processed")

PACKAGE = os.path.join(
    BASE,
    "BIT-TRACE-P2P-GitHub"
)

MODEL_DIR = os.path.join(
    PACKAGE,
    "model"
)

RESULTS_DIR = os.path.join(
    PACKAGE,
    "results"
)

# ------------------------------------------------------------
# CREATE DIRECTORIES
# ------------------------------------------------------------

os.makedirs(
    MODEL_DIR,
    exist_ok=True
)

os.makedirs(
    RESULTS_DIR,
    exist_ok=True
)

# ------------------------------------------------------------
# SOURCE → DESTINATION
# ------------------------------------------------------------

files_to_copy = {

    # MODEL
    "p2p_final_isolation_forest_v1.joblib":
        os.path.join(
            MODEL_DIR,
            "isolation_forest.joblib"
        ),

    "p2p_final_scaler_v1.joblib":
        os.path.join(
            MODEL_DIR,
            "scaler.joblib"
        ),

    "p2p_final_feature_config_v1.json":
        os.path.join(
            MODEL_DIR,
            "feature_config.json"
        ),

    "p2p_final_model_metadata_v1.json":
        os.path.join(
            MODEL_DIR,
            "model_metadata.json"
        ),

    # RESULTS
    "p2p_final_evaluation_report_v1.json":
        os.path.join(
            RESULTS_DIR,
            "evaluation_report.json"
        ),

    "p2p_final_reproducibility_v1.json":
        os.path.join(
            RESULTS_DIR,
            "reproducibility.json"
        ),

    "p2p_final_topk_evaluation_v1.parquet":
        os.path.join(
            RESULTS_DIR,
            "topk_evaluation.parquet"
        ),

    "p2p_final_explainable_candidates_v1.parquet":
        os.path.join(
            RESULTS_DIR,
            "explainable_candidates.parquet"
        )
}

# ------------------------------------------------------------
# COPY
# ------------------------------------------------------------

print("Copying final artifacts...\n")

for src_name, dst in files_to_copy.items():

    src = os.path.join(
        PROCESSED,
        src_name
    )

    if not os.path.exists(src):
        print("MISSING:", src_name)
        continue

    shutil.copy2(
        src,
        dst
    )

    size_mb = (
        os.path.getsize(dst)
        / 1024**2
    )

    print(
        f"OK  {src_name:<55} "
        f"{size_mb:.2f} MB"
    )

# ------------------------------------------------------------
# REQUIREMENTS
# ------------------------------------------------------------

requirements = """numpy
pandas
scikit-learn
joblib
pyarrow
"""

with open(
    os.path.join(
        PACKAGE,
        "requirements.txt"
    ),
    "w",
    encoding="utf-8"
) as f:

    f.write(requirements)

print("\nrequirements.txt created.")

# ------------------------------------------------------------
# PACKAGE MANIFEST
# ------------------------------------------------------------

manifest = []

for root, dirs, files in os.walk(PACKAGE):

    for file in files:

        path = os.path.join(
            root,
            file
        )

        relative = os.path.relpath(
            path,
            PACKAGE
        )

        manifest.append({
            "file": relative,
            "size_bytes": os.path.getsize(path)
        })

manifest_path = os.path.join(
    PACKAGE,
    "package_manifest.json"
)

with open(
    manifest_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        {
            "package": "BIT-TRACE P2P Anomaly Detection",
            "version": "v1",
            "files": manifest
        },
        f,
        indent=2
    )

# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n================================================")
print("GITHUB PACKAGE CREATED")
print("================================================")

print("Location:")
print(PACKAGE)

print("\nFiles:")

for item in manifest:
    print(
        f"{item['file']:<55} "
        f"{item['size_bytes']/1024**2:.2f} MB"
    )

print("\n================================================")
print("STEP 86 COMPLETE")
print("================================================")

Copying final artifacts...

MISSING: p2p_final_isolation_forest_v1.joblib
MISSING: p2p_final_scaler_v1.joblib
MISSING: p2p_final_feature_config_v1.json
MISSING: p2p_final_model_metadata_v1.json
MISSING: p2p_final_evaluation_report_v1.json
MISSING: p2p_final_reproducibility_v1.json
MISSING: p2p_final_topk_evaluation_v1.parquet
MISSING: p2p_final_explainable_candidates_v1.parquet

requirements.txt created.

================================================
GITHUB PACKAGE CREATED
================================================
Location:
/content/drive/MyDrive/Bitcoin P2P Dataset/BIT-TRACE-P2P-GitHub

Files:
requirements.txt                                        0.00 MB

================================================
STEP 86 COMPLETE
================================================

In [ ]:
# ============================================================
# STEP 88 — CREATE DEPLOYABLE P2P MODEL BUNDLE
# ============================================================

import os
import json
import joblib
import shutil

BASE = "/content/drive/MyDrive/Bitcoin P2P Dataset"
PROCESSED = os.path.join(BASE, "processed")

PACKAGE = os.path.join(
    BASE,
    "BIT-TRACE-P2P-GitHub"
)

MODEL_DIR = os.path.join(
    PACKAGE,
    "model"
)

INFERENCE_DIR = os.path.join(
    PACKAGE,
    "inference"
)

os.makedirs(
    MODEL_DIR,
    exist_ok=True
)

os.makedirs(
    INFERENCE_DIR,
    exist_ok=True
)

# ------------------------------------------------------------
# EXISTING ARTIFACTS
# ------------------------------------------------------------

MODEL_PATH = os.path.join(
    PACKAGE,
    "model",
    "isolation_forest.joblib"
)

SCALER_PATH = os.path.join(
    PACKAGE,
    "model",
    "scaler.joblib"
)

CONFIG_PATH = os.path.join(
    PACKAGE,
    "model",
    "feature_config.json"
)

METADATA_PATH = os.path.join(
    PACKAGE,
    "model",
    "model_metadata.json"
)

# ------------------------------------------------------------
# LOAD EXISTING ARTIFACTS
# ------------------------------------------------------------

print("Loading saved model artifacts...")

model = joblib.load(
    MODEL_PATH
)

scaler = joblib.load(
    SCALER_PATH
)

with open(
    CONFIG_PATH,
    "r",
    encoding="utf-8"
) as f:
    config = json.load(f)

with open(
    METADATA_PATH,
    "r",
    encoding="utf-8"
) as f:
    metadata = json.load(f)

print("Model loaded.")
print("Scaler loaded.")
print("Features:", len(config["features"]))

# ------------------------------------------------------------
# CREATE SINGLE DEPLOYMENT BUNDLE
# ------------------------------------------------------------

bundle = {
    "model": model,
    "scaler": scaler,
    "feature_columns": config["features"],
    "log1p_features": config["log1p_features"],
    "train_95_threshold": config["thresholds"][
        "train_95_percentile"
    ],
    "train_99_threshold": config["thresholds"][
        "train_99_percentile"
    ],
    "score_definition": config[
        "score_definition"
    ],
    "version": "v1"
}

BUNDLE_PATH = os.path.join(
    MODEL_DIR,
    "p2p_anomaly_detector.joblib"
)

joblib.dump(
    bundle,
    BUNDLE_PATH
)

print("\nDeployment bundle created:")
print(BUNDLE_PATH)

print(
    "Size:",
    f"{os.path.getsize(BUNDLE_PATH)/1024**2:.2f} MB"
)

# ------------------------------------------------------------
# CREATE INFERENCE MODULE
# ------------------------------------------------------------

INFERENCE_CODE = r'''
import joblib
import numpy as np
import pandas as pd


class P2PAnomalyDetector:
    """
    BIT-TRACE P2P anomaly detector.

    Loads the trained Isolation Forest together with:
    - StandardScaler
    - feature ordering
    - log1p preprocessing configuration
    - train-derived anomaly thresholds
    """

    def __init__(self, model_path):
        bundle = joblib.load(model_path)

        self.model = bundle["model"]
        self.scaler = bundle["scaler"]

        self.feature_columns = bundle[
            "feature_columns"
        ]

        self.log1p_features = bundle[
            "log1p_features"
        ]

        self.threshold_95 = bundle[
            "train_95_threshold"
        ]

        self.threshold_99 = bundle[
            "train_99_threshold"
        ]

    def _preprocess(self, data):
        """
        Apply the same preprocessing used during training.
        """

        if isinstance(data, dict):
            data = pd.DataFrame([data])

        elif not isinstance(data, pd.DataFrame):
            data = pd.DataFrame(data)

        missing = [
            feature
            for feature in self.feature_columns
            if feature not in data.columns
        ]

        if missing:
            raise ValueError(
                f"Missing required features: {missing}"
            )

        X = data[
            self.feature_columns
        ].copy()

        # Same log1p preprocessing used during training
        for feature in self.log1p_features:

            X[feature] = np.log1p(
                np.clip(
                    X[feature].astype(float),
                    0,
                    None
                )
            )

        # Safety handling for missing values
        for feature in self.feature_columns:

            if X[feature].isna().any():

                X[feature] = X[
                    feature
                ].fillna(
                    X[feature].median()
                )

        X_scaled = self.scaler.transform(X)

        return X_scaled

    def predict(self, data):
        """
        Return anomaly score and candidate level.
        """

        X_scaled = self._preprocess(data)

        scores = -self.model.decision_function(
            X_scaled
        )

        results = []

        for score in scores:

            if score >= self.threshold_99:
                level = "HIGH"

            elif score >= self.threshold_95:
                level = "ELEVATED"

            else:
                level = "BASELINE"

            results.append({
                "anomaly_score": float(score),
                "candidate_level": level
            })

        return results
'''

INFERENCE_PATH = os.path.join(
    INFERENCE_DIR,
    "p2p_detector.py"
)

with open(
    INFERENCE_PATH,
    "w",
    encoding="utf-8"
) as f:
    f.write(INFERENCE_CODE)

print("\nInference module created:")
print(INFERENCE_PATH)

# ------------------------------------------------------------
# CREATE SIMPLE TEST SCRIPT
# ------------------------------------------------------------

TEST_CODE = r'''
from p2p_detector import P2PAnomalyDetector


MODEL_PATH = "../model/p2p_anomaly_detector.joblib"

detector = P2PAnomalyDetector(
    MODEL_PATH
)

# Example:
# Replace these values with a real 28-feature observation.

sample = {
    "observation_count": 100,
    "active_days": 5,
    "active_hours": 20,
    "observation_span_seconds": 100000,

    "unique_ports": 1,
    "unique_services": 1,

    "non_default_port_observations": 0,
    "non_default_ports": 0,
    "non_1037_service_observations": 0,

    "min_reported_height": 620000,
    "max_reported_height": 620100,

    "mean_height_deviation": 10,
    "mean_absolute_height_deviation": 10,
    "max_absolute_height_deviation": 20,

    "height_deviation_over_100": 0,
    "height_deviation_over_1000": 0,
    "height_deviation_over_10000": 0,

    "mean_observations_per_hour": 5,
    "max_observations_per_hour": 10,

    "hourly_activity_std": 2,
    "hourly_activity_variance": 4,

    "mean_observations_per_day": 20,
    "max_observations_per_day": 30,

    "daily_activity_std": 5,

    "hourly_burst_ratio": 1,
    "daily_burst_ratio": 1,

    "hourly_activity_cv": 0.2,
    "daily_activity_cv": 0.2
}

result = detector.predict(sample)

print(result)
'''

TEST_PATH = os.path.join(
    INFERENCE_DIR,
    "test_inference.py"
)

with open(
    TEST_PATH,
    "w",
    encoding="utf-8"
) as f:
    f.write(TEST_CODE)

print("\nTest script created:")
print(TEST_PATH)

# ------------------------------------------------------------
# FINAL MODEL CARD
# ------------------------------------------------------------

MODEL_CARD = {
    "name": "BIT-TRACE P2P Anomaly Detector",
    "version": "v1",
    "algorithm": "Isolation Forest",
    "features": 28,
    "estimators": 300,

    "training_nodes": 14871,
    "holdout_nodes": 6251,

    "train_95_threshold": bundle[
        "train_95_threshold"
    ],

    "train_99_threshold": bundle[
        "train_99_threshold"
    ],

    "holdout_above_95": {
        "count": 269,
        "rate": 0.0430
    },

    "holdout_above_99": {
        "count": 46,
        "rate": 0.0074
    },

    "ground_truth_available": False,

    "accuracy": None,

    "evaluation_note":
        "Ground-truth anomaly labels are unavailable. "
        "Temporal holdout and threshold-based evaluation "
        "are used instead.",

    "reproducibility": {
        "tested_nodes": 6251,
        "exact_matches": 6251,
        "maximum_difference": 0.0,
        "status": "PASS"
    }
}

MODEL_CARD_PATH = os.path.join(
    MODEL_DIR,
    "model_card.json"
)

with open(
    MODEL_CARD_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        MODEL_CARD,
        f,
        indent=2
    )

print("\nModel card created.")

# ------------------------------------------------------------
# FINAL STRUCTURE
# ------------------------------------------------------------

print("\n================================================")
print("DEPLOYABLE MODEL PACKAGE")
print("================================================")

for root, dirs, files in os.walk(PACKAGE):

    level = root.replace(
        PACKAGE,
        ""
    ).count(os.sep)

    indent = "  " * level

    print(
        f"{indent}{os.path.basename(root)}/"
    )

    for file in files:

        path = os.path.join(
            root,
            file
        )

        size = (
            os.path.getsize(path)
            / 1024**2
        )

        print(
            f"{indent}  {file} "
            f"({size:.2f} MB)"
        )

print("\n================================================")
print("STEP 88 COMPLETE")
print("================================================")

In [ ]:
# ============================================================
# STEP 89 — FINAL FIXED PACKAGE + VERIFIED ZIP
# ============================================================

import os
import shutil
import json
from google.colab import files

DRIVE_PACKAGE = (
    "/content/drive/MyDrive/Bitcoin P2P Dataset/"
    "BIT-TRACE-P2P-GitHub"
)

LOCAL_PACKAGE = "/content/BIT-TRACE-P2P-GitHub"
ZIP_PATH = "/content/BIT-TRACE-P2P-GitHub-FINAL.zip"

# ------------------------------------------------------------
# 1. CHECK DRIVE PACKAGE
# ------------------------------------------------------------

print("Checking Google Drive package...")

if not os.path.exists(DRIVE_PACKAGE):
    raise FileNotFoundError(
        "BIT-TRACE-P2P-GitHub package not found on Drive."
    )

# ------------------------------------------------------------
# 2. SHOW EVERYTHING CURRENTLY ON DRIVE
# ------------------------------------------------------------

print("\nCurrent Drive package contents:\n")

for root, dirs, files_in_dir in os.walk(DRIVE_PACKAGE):

    relative = os.path.relpath(
        root,
        DRIVE_PACKAGE
    )

    print(
        f"\n[{relative}]"
    )

    for f in files_in_dir:
        path = os.path.join(root, f)

        print(
            f"  {f} "
            f"({os.path.getsize(path)/1024**2:.2f} MB)"
        )

# ------------------------------------------------------------
# 3. REMOVE OLD LOCAL COPY
# ------------------------------------------------------------

if os.path.exists(LOCAL_PACKAGE):
    shutil.rmtree(LOCAL_PACKAGE)

if os.path.exists(ZIP_PATH):
    os.remove(ZIP_PATH)

# ------------------------------------------------------------
# 4. COPY DRIVE PACKAGE TO LOCAL COLAB STORAGE
# ------------------------------------------------------------

print("\nCopying package from Drive to local storage...")

shutil.copytree(
    DRIVE_PACKAGE,
    LOCAL_PACKAGE
)

print("Local copy created.")

# ------------------------------------------------------------
# 5. CHECK REQUIRED FILES
# ------------------------------------------------------------

required_files = [

    "model/p2p_anomaly_detector.joblib",
    "model/isolation_forest.joblib",
    "model/scaler.joblib",
    "model/feature_config.json",
    "model/model_metadata.json",
    "model/model_card.json",

    "inference/p2p_detector.py",
    "inference/test_inference.py",

    "results/evaluation_report.json",
    "results/reproducibility.json",
    "results/topk_evaluation.parquet",
    "results/explainable_candidates.parquet",

    "requirements.txt",
    "README.md"
]

print("\n================================================")
print("REQUIRED FILE CHECK")
print("================================================")

missing = []

for relative_path in required_files:

    full_path = os.path.join(
        LOCAL_PACKAGE,
        relative_path
    )

    if os.path.exists(full_path):

        size = (
            os.path.getsize(full_path)
            / 1024**2
        )

        print(
            f"OK      {relative_path:<55}"
            f"{size:.2f} MB"
        )

    else:

        print(
            f"MISSING {relative_path}"
        )

        missing.append(
            relative_path
        )

# ------------------------------------------------------------
# STOP IF PACKAGE IS INCOMPLETE
# ------------------------------------------------------------

if missing:

    print("\n================================================")
    print("PACKAGE INCOMPLETE")
    print("================================================")

    print(
        "\nMissing files:"
    )

    for f in missing:
        print(
            " -",
            f
        )

    raise RuntimeError(
        "Package is incomplete. ZIP was NOT created."
    )

# ------------------------------------------------------------
# 6. ZIP LOCAL COPY
# ------------------------------------------------------------

print("\n================================================")
print("CREATING VERIFIED ZIP")
print("================================================")

shutil.make_archive(
    "/content/BIT-TRACE-P2P-GitHub-FINAL",
    "zip",
    root_dir="/content",
    base_dir="BIT-TRACE-P2P-GitHub"
)

# ------------------------------------------------------------
# 7. VERIFY ZIP SIZE
# ------------------------------------------------------------

zip_size = (
    os.path.getsize(ZIP_PATH)
    / 1024**2
)

print(
    f"\nZIP size: {zip_size:.2f} MB"
)

# ------------------------------------------------------------
# 8. VERIFY ZIP CONTENTS
# ------------------------------------------------------------

import zipfile

print("\n================================================")
print("ZIP CONTENT VERIFICATION")
print("================================================")

with zipfile.ZipFile(
    ZIP_PATH,
    "r"
) as z:

    zip_files = z.namelist()

    print(
        "Files inside ZIP:",
        len(zip_files)
    )

    for required in required_files:

        zip_path = (
            "BIT-TRACE-P2P-GitHub/"
            + required
        )

        if zip_path in zip_files:
            print(
                "OK     ",
                required
            )

        else:
            print(
                "MISSING",
                required
            )

# ------------------------------------------------------------
# 9. DOWNLOAD
# ------------------------------------------------------------

print("\n================================================")
print("DOWNLOAD STARTING")
print("================================================")

files.download(
    ZIP_PATH
)

print("\n================================================")
print("STEP 89 COMPLETE")
print("================================================")

Checking Google Drive package...

Current Drive package contents:


[.]
  package_manifest.json (0.00 MB)
  requirements.txt (0.00 MB)

[results]

[model]

Copying package from Drive to local storage...
Local copy created.

================================================
REQUIRED FILE CHECK
================================================
MISSING model/p2p_anomaly_detector.joblib
MISSING model/isolation_forest.joblib
MISSING model/scaler.joblib
MISSING model/feature_config.json
MISSING model/model_metadata.json
MISSING model/model_card.json
MISSING inference/p2p_detector.py
MISSING inference/test_inference.py
MISSING results/evaluation_report.json
MISSING results/reproducibility.json
MISSING results/topk_evaluation.parquet
MISSING results/explainable_candidates.parquet
OK      requirements.txt                                       0.00 MB
MISSING README.md

================================================
PACKAGE INCOMPLETE
================================================

Missing files:
 - model/p2p_anomaly_detector.joblib
 - model/isolation_forest.joblib
 - model/scaler.joblib
 - model/feature_config.json
 - model/model_metadata.json
 - model/model_card.json
 - inference/p2p_detector.py
 - inference/test_inference.py
 - results/evaluation_report.json
 - results/reproducibility.json
 - results/topk_evaluation.parquet
 - results/explainable_candidates.parquet
 - README.md

RuntimeError: Package is incomplete. ZIP was NOT created.